### ISSUE TITLE
Failed to start 3proxy 3proxy as a service in Windows10

### ISSUE THREAD

**Issue by getmefree** [z3APA3A/3proxy#100]
I compiled 3proxy and cd to 3proxy-devel\bin , copy 3proxy.cfg from example
cd to 3proxy-devel\bin and run: 3proxy.exe --install 3proxy.cfg
but it return: Failed to start service: No error

I open services.msc and find a service named '3proxy tiny proxy server'
however it cannot be start and it says:
Error 1053:The service did not respond to the start or control request in a timely fashion.

I can't find any solution, please help me
Thanks

**Comment by z3APA3A** [comment]
See related FAQ section
http://3proxy.ru/faqe.asp#SERVICE

**Comment by getmefree** [comment]
Thanks for your reply.

I checked reasons lists in  Q: Why doesn't 3proxy work as service under Windows?
First, the version of mine is 3proxy-0.9-devel which great than 0.5.2
and use '3proxy.exe --install D:\Documents\3proxy.cfg' but the return is the same
Above command ran with Administrator
I checked ACLs, my account has 'full control' towards these files
my 3proxy.cfg is in same location with 3proxy.exe
my account(Administrator) surely has rights to install or start service 
service is installed but no started 

And now , it also return this:
Failed to open Service Manager: No error
To ensure the problem is not machine-related
I ran 3proxy in another pc , the problem still exist

**Comment by z3APA3A** [comment]
A main problem is you probably have no valid config file or it contains relative paths, try to run 3proxy manuallly with same config and check the errors.

**Comment by getmefree** [comment]
Finally, I solved that by myself
Here is the solution:
Any command(Bash) with 3proxy should run with Administrator Command Prompt

If it says Failed to open Service Manager: No error
run '3proxy.exe 3proxy.cfg' FIRST! 
open taskmgr.exe to make sure that 3proxy.exe is running in backgroud
THEN run '3proxy.exe --install 3proxy.cfg'

If it says Failed to create service: No error
run '3proxy.exe --remove' first and make sure the 'remove procedure' did not reply any error
and run 3proxy.exe --install 3proxy.cfg

Thanks anyway
