### ISSUE TITLE
parent proxy authentification и 3proxy

### ISSUE THREAD

**Issue by bsploit** [z3APA3A/3proxy#102]
Спасибо за прекрасное ПО, очень часто выручает. Столкнулся со следующей проблемой, есть 3proxy основная задача которого просто передать все что к нему пришло на вышестоящий прокси. Этот вышестоящий прокси запрашивает аутентификацию с помощью 407 кода, предлагая следующие варианты negotiate, ntlm:
HTTP/1.1 407 Proxy Authentication Required
Proxy-Authenticate: NEGOTIATE
Proxy-Authenticate: NTLM

при этом такое впечатление, что заголовки Proxy-Authenticate рубит 3proxy и пользователю они не отдаеются. Как это можно обойти?

текущая конфигурация такая:
allow *
parent 1000 http 192.168.1.1 8080 
parent 1000 connect 192.168.1.1 8080 
proxy -a -p4888

**Comment by remittor** [comment]
Попробуйте добавить опцию "-T" (transparent).

**Comment by z3APA3A** [comment]
Да, во-первых второго parent вообще не надо, во-вторых параметр -T в proxy.
