### ISSUE TITLE
Некорректно работает команда monitor

### ISSUE THREAD

**Issue by Alex181** [z3APA3A/3proxy#103]
CentOS 7
В конфиге прописываю:
monitor "/usr/local/etc/3proxy/3proxy.cfg"

Протокол SOCKS
socks -i192.168.1.1 -p33333 -e192.168.1.1

Разрешаю доступ только со своего IP на IP socks:
allow * 192.168.1.10/24 192.168.1.1 * * * *

Запускаю сервис.

Проверяю чекером. Прокси работает нормально.

Меняю в конфиге разрешенный IP:
allow * 192.168.1.11/24 192.168.1.1 * * * *

Проверяю чекером. Меня не пускает. Т.е. конфиг перечитан на лету. Прокси работает нормально.

Меняю в конфиге разрешенный IP назад (мой IP):
allow * 192.168.1.10/24 192.168.1.1 * * * *

Проверяю чекером. Меня все равно не пускает. Что то застряло. 
Перезагрузка 3proxy решает проблему и после нее опять работает нормально.

ИМХО, баг. Прошу поправить. Очень хотелось бы, чтобы конфиги нормально перечитывались автоматом.

P.S. Пробовал аналогично с внешними файлами (includ, $). Картина та же.

**Comment by z3APA3A** [comment]
Что полностью прописано в конфигу и что в логах когда "не пускает"?

**Comment by shark136** [comment]
Если мне память не изменяет, то была рекомендация мониторить не сам файл конфига, а создать отдельный файл для этого.

**Comment by z3APA3A** [comment]
Так а файл-то ты меняешь после изменения конфиги?

**Comment by Alex181** [comment]
Потратил день на исследования. Запускал 3proxy на 3-х VPS'ах под CentOS 7.
Везде наблюдалась его нестабильная работа, вплоть до отказа стартовать сервис. И вышеописанный мной глюк тоже проявлялся. Ничего понять не мог.
Начал действовать "методом научного тыка". С его помощью выяснил, что все дело было в ДНС. 

В конфиге 3proxy был прописан локальный ДНС 127.0.0.1. На всех трех VPS'ах был установлен BIND 9. Но, в нем не были разрешены рекурсивные запросы с локальных IP.
После разрешения рекурсии для локальных IP все, вроде, заработало.

Пользуясь случаем, хочу поблагодарить за качественный софт и своевременный отклик.

Пожелание: Было бы не плохо ввести дополнительную проверку корректной работы ДНС. Чтобы ошибку выдавало, если что не так.
А то непостоянные глюки, возникающие в этом случае не позволяют быстро понять где собака порылась.

Удачи!

**Comment by z3APA3A** [comment]
3proxy при проблемах с разрешением имен дает в лог код ошибки 100.
