### ISSUE TITLE
Разные цепочки HTTP прокси в зависимости от URL, возможно ли?

### ISSUE THREAD

**Issue by trafostream** [z3APA3A/3proxy#104]
Можно ли как-то настроить http прокси таким образом, чтобы в зависимости от URL в запросе срабатывал тот или иной parent прокси?
К примеру трафик для SITE1 идет через PROXY1, а трафик для SITE2 идет через PROXY2.

**Comment by z3APA3A** [comment]
Для разных сайтов или разных URI?

**Comment by trafostream** [comment]
И в идеале оба варианта. Приоритетный разные хосты.

**Comment by z3APA3A** [comment]
allow * * host1
parent 1000 proxy1
allow * * host2
parent 1000 proxy2
