### ISSUE TITLE
Разные parent HTTP прокси в зависимости от URI

### ISSUE THREAD

**Issue by trafostream** [z3APA3A/3proxy#105]
Как настроить HTTP прокси, чтобы в зависимости от URI в запросе срабатывал тот или иной PARENT прокси?
Спасибо.

**Comment by z3APA3A** [comment]
Я тебе ответил в https://github.com/z3APA3A/3proxy/issues/104. Если тебе нужен именно полнофункциональный обратный веб прокси / сервер, то используй что-то специально для этих целей написанное, например nginx.
