### ISSUE TITLE
SOCKS proxy ignore -6 for resolve

### ISSUE THREAD

**Issue by termeee** [z3APA3A/3proxy#107]
Добрый день.

Имеем такую проблему:
в опция запуска socks явно прописано -6

Когда через socks6 обращаемся к ресурсу, доступному по dual-stack он вместо обращения к ipv6 адресу обращается через mapped ipv4.

лог:

`161026202350.503 20000 00004 - 77.79.x.x:56375 ::ffff:178.62.9.171:80 0 0 0 CONNECT ::ffff:178.62.9.171:80

161026202350.566 20000 00004 - 77.79.x.x:56376 ::ffff:178.62.9.171:80 0 0 0 CONNECT ::ffff:178.62.9.171:80

161026202350.629 20000 00004 - 77.79.x.x:56377 ::ffff:178.62.9.171:80 0 0 0 CONNECT ::ffff:178.62.9.171:80

161026202350.692 20000 00004 - 77.79.x.x:56378 ::ffff:178.62.9.171:80 0 0 0 CONNECT ::ffff:178.62.9.171:80

161026202350.757 20000 00004 - 77.79.x.x:56379 ::ffff:178.62.9.171:80 0 0 0 CONNECT ::ffff:178.62.9.171:80
`

для примера взял myip.ru: 
`host myip.ru

myip.ru has address 178.62.9.171

myip.ru has IPv6 address 2a03:b0c0:1:d0::b6:2001

myip.ru mail is handled by 10 myip.ru.
`

конфиг:

`internal x.x.x.x

nscache 65536

timeouts 1 5 30 60 180 1800 15 60

flush

auth strong

users andy:CL:xxxx

users vova:CL:xxxx

users misha:CL:xxxx

allow andy

parent 1000 extip xxx:xxxx:xxxx:f97a:2dac:b236:7cf9:7aa5 0

allow vova

parent 1000 extip xxx:xxxx:xxxx:e14:b975:5a90:ea6f:5310 0

allow misha

parent 1000 extip xxx:xxxx:xxxx:1812:328d:1dd0:c021:53b2 0

socks -6 -p20000 -ix.x.x.x -l

proxy -6 -ix.x.x.x -p10000

flush
`

http работает корректно.

**Comment by z3APA3A** [comment]
По логу видно, что клиент запрашивал не имя, а адрес IPv4. Соответственно прокси в такой ситуации ничего не может сделать, кроме как транслировать адрес IPv4 в IPv6 в надежде что найдется шлюз.
Чтобы прокси разрешал имена, надо в клиенте включить опцию разрешения имен через прокси, иначе до прокси никаких имен не доходит.

**Comment by termeee** [comment]
оно так же не работает, когда хостнейм передаётся:
161027143328.283 20000 00004 - 77.79.x.x:64624 2a00:1450:4010:c0b::8b:80 0 0 0 CONNECT ipv6.google.com:80
161027143328.369 20000 00004 - 77.79.x.x:64625 2a00:1450:4010:c0b::65:80 0 0 0 CONNECT ipv6.google.com:80

**Comment by z3APA3A** [comment]
Не работает, потому что у тебя auth strong а в запросе нет имени и пароля.
Если ты в браузере тестируешь - браузеры не умеют делать парольную авторизацию в socks.
