### ISSUE TITLE
Please help with an answer and advice.

### ISSUE THREAD

**Issue by visomymail** [z3APA3A/3proxy#1093]
For the second week I have been struggling with how to make access via IP without authorization, no methods work. Does the program support this option? If yes, tell me how this can be implemented. Thank you.

**Comment by karinaardos** [comment]
> Уже вторую неделю бьюсь над тем, как сделать доступ по IP без авторизации, никакие способы не работают. Поддерживает ли программа эту опцию? Если да, подскажите, как это можно реализовать. Спасибо.

add you config in 3proxy.cfg

flush
auth iponly
allow * 123.123.123.123 (Indicate your IP address here from which you will enter)  
proxy -p9999
