### ISSUE TITLE
Questions, comments, bugreports and feature requests

### ISSUE THREAD

**Issue by z3APA3A** [z3APA3A/3proxy#11]
For feature requests and bugreports please create an issue.
If you have any questions or comments you can create an issue or write to 3proxy@3proxy.ru.
Please read at least FAQ and How To before asking:
http://3proxy.ru/doc/
http://3proxy.ru/documents/

**Comment by aarishcs2** [comment]
we are getting issues with the new version of 3proxy on windows it complaints about the trojan  odbc32.dll is there any fix for this ?

**Comment by z3APA3A** [comment]
Can you provide screenshot?
3proxy doesn't distribute odbc32.dll, it uses system one.

**Comment by aarishcs2** [comment]
Here is the screen shot.
![odbc32_error](https://user-images.githubusercontent.com/38554577/39071017-290afe3c-4503-11e8-8e21-c7c52d4d10b2.PNG)

**Comment by z3APA3A** [comment]
Oops, sorry, I found I really left testing odbc32.dll in bin64 folder.
Don't worry, it's harmless (it's a simple test file to check DLL injection, it 'Trojans' (that is replaces with MessageBox) every ODBC32.dll method to show which one is invoked. Just delete odbc32.dll from 3proxy folder or download new distro.

**Comment by aarishcs2** [comment]
thank you for your help :) . its working now

**Comment by aarishcs2** [comment]
bro do you have any idea or lead how to go about configuring the routing issue in linux ?

**Comment by aarishcs2** [comment]
cause windows its simple but need to set this up in raspberry and still the IOT windows is not getting the drivers for the dongle . so creating issues .

**Comment by wwwiulian** [comment]
I want to deny all websites, except one (instagram.com) and I can't seem to make it work.

Can you pls share an example. Thank you!

**Comment by z3APA3A** [comment]
You should allow either the list of domains usdr by instagram or the list of networks used by instagram and deny the rest.

allow * * list,domains,or,list,networks
deny *

**Comment by gitlsl** [comment]
can you add  static link(.lib)   generate  support

**Comment by z3APA3A** [comment]
I bet you actually mean something else, or, at least, you have to clarify what to you expect to have in static lib. Can you explain your task?

**Comment by gitlsl** [comment]
If we make the core proxy function of 3proxy into a static link library or a share dll,  we can facilitate the conduct of secondary development. Otherwise, it would be more troublesome to add a function now.

**Comment by z3APA3A** [comment]
I don't see how linking the static library can facilitate new functionality development.

3proxy supports plugin mechanism for extensions, it's described here: 
https://3proxy.ru/doc/devref.rtf
This documentation may be outdated and incomplete, but it's a good point to start with anyway.

**Comment by vaygr** [comment]
Would be really nice to get multiple listening port support via `-p` per proxy instance.

Either `-p portA -p portB` or `-p portA,portB` would be fine for the syntax.

**Comment by z3APA3A** [comment]
what's the reason to have same service in same configuration on multiple ports?

**Comment by vaygr** [comment]
Well, multiple ports is a regular feature of any UNIX daemon. One use case could be keeping backward compatibility: moving users from previous proxy server that was listening on one port to a new 3proxy installation listening on another.

I guess this can be achieved via running tcppm instance, but still..

**Comment by z3APA3A** [comment]
you can simply use
<config>
proxy -p1234
proxy -p1235
it runs proxy on 2 ports with same config.

**Comment by phantomcraft** [comment]
@z3APA3A 

Could you implement IPv6 support in TransparentPlugin?

There are some transparent forwarders out there, but some are heavy on memory usage, others are buggy, no IPv6 support, huge dependencies. I wanna put 3proxy on my router.

**Comment by z3APA3A** [comment]
There is no documentation on SO_ORIGINAL_DST with IPv6, so I'm not sure if it can be done.
Try devel with 5471e0faf4cb65075bea20bd660cc22a5dd5b65c, I've attempted to fix it, but I have no chance to test it works.

**Comment by phantomcraft** [comment]
It doesn't work yet.

You can test with network namespaces:

```
ip netns add nsx
ip link add vethx type veth peer name peerx netns nsx
ip link set vethx up
ip add add 10.0.0.1/24 dev vethx
ip addr add fd00::1/64 dev vethx 
ip netns exec nsx ip link set peerx up
ip netns exec nsx ip addr add 10.0.0.2/24 dev peerx 
ip netns exec nsx ip addr add fd00::2/64 dev peerx
ip netns exec nsx ip route add default via 10.0.0.1
ip netns exec nsx ip route add default via fd00::1
iptables -t nat -A PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination 10.0.0.1:7777
ip6tables -t nat -A PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination [fd00::1]:7777
ip link add br0 type bridge 
ip link set br0 up
ip addr add 10.0.1.1/24 dev br0
ip addr add fd01::1/64 dev br0

/dev/shm/3proxy << EOT
log
auth iponly
allow *
socks -64 -i127.0.0.1 -p1180
external 0.0.0.0
external ::
flush
plugin /dev/shm/TransparentPlugin.ld.so transparent_plugin
log
auth iponly
allow *
parent 1000 socks5 127.0.0.1 1180
transparent
tcppm -64 -i:: 7777 ::1 11111
notransparent
end
EOT
```

**In other terminal tab, iperf3 is launched:**

`iperf3 -s -B :: -p 5201`

**In another one, iperf3 is driven to connect to it's server listening on bridge address:**

`ip netns exec nsx iperf3 -c fd01::1 -p 5201 -t 3`

**iperf3 shows:**
   _iperf3: error - control socket has closed unexpectedly_

**and 3proxy:**
   _190812155104.290 1180 00000 - 127.0.0.1:1180 :::0 0 0 0 Accepting connections [10528/2748733184]
   190812155104.291 7777 00000 - :::7777 :::0 0 0 0 Accepting connections [10528/2748643072]
   190812155140.125 7777 00100 - fd00::2:52748 0.0.0.0:0 0 0 0 fd01::1_

**When changing "-i::" to "-i0.0.0.0" in tcppm line, iperf3 works normally with bridge IPv4 address:**

`ip netns exec nsx iperf3 -c 10.0.1.1 -p 5201 -t 3`
_Connecting to host 10.0.1.1, port 5201
   [  5] local 10.0.0.2 port 56390 connected to 10.0.1.1 port 5201
   [ ID] Interval           Transfer     Bitrate         Retr  Cwnd
   [  5]   0.00-1.00   sec  3.38 GBytes  29.0 Gbits/sec    0    223 KBytes       
   [  5]   1.00-2.00   sec  3.42 GBytes  29.3 Gbits/sec    0    221 KBytes       
   [  5]   2.00-3.00   sec  3.36 GBytes  28.9 Gbits/sec    0    226 KBytes       
   [ ID] Interval           Transfer     Bitrate         Retr
   [  5]   0.00-3.00   sec  10.2 GBytes  29.1 Gbits/sec    0             sender
   [  5]   0.00-3.04   sec  10.2 GBytes  28.7 Gbits/sec                  receiver
   iperf Done._

**3proxy output now:**
   _190812155446.600 1180 00000 - 127.0.0.1:1180 :::0 0 0 0 Accepting connections [10650/1164019456]
   190812155446.601 7777 00000 - 0.0.0.0:7777 :::0 0 0 0 Accepting connections [10650/1163929344]
   190812155453.258 1180 00000 - 127.0.0.1:57425 10.0.1.1:5201 9790593901 0 0 CONNECT 10.0.1.1:5201
   190812155453.258 7777 00000 - 10.0.0.2:56394 127.0.0.1:1180 9790593901 22 1 10.0.1.1
   190812155453.342 7777 00000 - 10.0.0.2:56392 127.0.0.1:1180 437 329 1 10.0.1.1
   190812155453.342 1180 00000 - 127.0.0.1:44985 10.0.1.1:5201 437 307 0 CONNECT 10.0.1.1:5201_

**Cleaning:**

```
iptables -t nat -D PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination 10.0.0.1:7777
ip6tables -t nat -D PREROUTING -i vethx -p tcp --syn -j DNAT --to-destination [fd00::1]:7777
ip netns del nsx && ip li del br0
```

**Comment by z3APA3A** [comment]
Try devel with latests patches cb217d79c16769dc63f8ba86c082778a705a7de9, it hopefully should work.

**Comment by phantomcraft** [comment]
Thanks @z3APA3A , it's working fine now.

I have 2 feature suggestions for 3proxy, I don't know if you'll find relevant:

1 - DNS Tunneling over parent proxies: with TransparentPlugin fired up with 3proxy serving a virtual machine or a sandbox/container, a option like "-t" on dnspr would help to make this VM or network namespace fully isolated from host network without using external software like DNS2SOCKS or tdnsd.

2 - Multiple DNS servers support: it would make DNS requests faster and also be useful when reading a server list from file in a shell script (that's I do here).

**Comment by z3APA3A** [comment]
Currently, UDP is not supported for parent proxy, UDP tunneling is possible for DNS over TCP. So both 1 abd 2 can be implemented but it will be slow, because every request creates separate TCP connection.
To tunnel DNS over TCP via parent proxy and do a round roubin between few DNS use e.g.
```
nserver 127.0.0.1:5353/tcp
nscache 1000000
...
flush
allow *
 tunnel through parent proxy
parent 1000 parent proxy configuration here
 round robin between DNS
parent 333 tcp DNS1 53
parent 333 tcp DNS2 53
parent 334 tcp DNS3 53
 1.1.1.1 is not actually used here because is overloaded with 'parent tcp'
tcppm 5353 1.1.1.1 53
flush
...
```

**Comment by phantomcraft** [comment]
@z3APA3A Perhaps an option in dnspr to send TCP/UDP DNS queries to upstream servers like tcppm in your example config does, would be nice.

Thanks.

**Comment by phantomcraft** [comment]
I think that dnspr, nscache, nscache6, nsrecord, fakeresolve and dialler should obey flush line in 3proxy config.

So, in configurations like this, it can resolve domain names passed into parent line when dnspr with tcppm and parent tcp+proxy addresses, and can reduce the occasional need for an external dialler:

```
nserver [::1]:10053/tcp
dnspr -i[::] -p53
flush
...
nserver 9.9.9.9:53/tcp
## no flush in order to resolve domain names bellow:
allow *
parent 1000 socks5 127.0.0.1 9050
parent 500 tcp resolver1.dns.watch 53
parent 500 tcp resolver2.dns.watch 53
tcppm -i::1 10053 127.0.0.1 11111
end
```

Another aesthetic thing is that tcppm doesn't work when the rewritten source address is IPv6:

```
...
parent 1000 tcp ::1 5201
tcppm -i::1 10053 ::1 11111
...
```

^^ It should be always an IPv4 address, not one like "::1" or "::ffff:127.0.0.1"

**Comment by z3APA3A** [comment]
Try 
parent 1000 tcp [::1] 5201.
in some cases IPv6 needs to be bracketed.

Under current  architecture, some objects including caches, bandlimiters, userlists, etc are global and are shared between all services. This behavior is optimal for most use cases. If you need to run few services with completely separate configuration, run few 3proxy instances with different config files.

**Comment by hos8in** [comment]
Hi
Is it possible to limit multiple login per username?
I want to allow only one device (or ip) to login with same username

**Comment by z3APA3A** [comment]
It's not clear what exactly do you need. Check 'connlim' and 'allow' commands. e.g.
allow user1,user2,user3 ip1
allows user1 user2 and usre3 to login from ip1.

**Comment by hos8in** [comment]
Thanks for your reply
I want to stop people from sharing their username password
Every username can only be used on one device (or one ip) at the same time

**Comment by z3APA3A** [comment]
Try latest devel with configuration like
```
users testuser:CL:testpass
...
authcache ip,user,pass,limit 120
auth cache strong
proxy
...
``
it should prevent user from changing IP during cache time (120 seconds in example)

**Comment by phantomcraft** [comment]
@z3APA3A

3proxy fails in configurations like this (for data mining):

```
allow *
parent 1000 socks5 127.0.0.1 9050
parent 200 tcp google.com 80
parent 200 tcp facebook.com 80
parent 200 tcp doubleclick.net 80
parent 200 tcp google-analytics.com 80
parent 200 tcp akamaihd.net 80
tcppm -i:: 8080 [::1] 12345
```

If there is an error in lookup or DNS resolver can't resolve all the domains in less than 30 secs, 3proxy ends and show this message:

_Command: 'parent' failed with code 5, line 8_

An option to allow retrying the DNS names or wait as much as possible for this would be nice, and also, to skip dead domains.

Could you implement this?

**Comment by z3APA3A** [comment]
you can specify "nserver" more than once (even with same IP), e.g.
nserver 127.0.0.1
nserver 127.0.0.1
nserver 8.8.8.8/tcp
- to make 3proxy to perform 3 attempts to resolve name (2 attempts via 127.0.0.1 + one attempt via 8.8.8.8 via tcp) + set name resolution timeout via 'timeouts' command.

I do not want to add "skip dead domains" or something like this or even parent proxy server checking feature, because I want 3proxy to always have predictable behavior in any point in time.

**Comment by z3APA3A** [comment]
continue in #395
