### ISSUE TITLE
3proxy + profixier

### ISSUE THREAD

**Issue by warmwave** [z3APA3A/3proxy#111]
Через profixier не работатет IPv6:

nserver 8.8.8.8
nserver 8.8.8.4
timeouts 1 5 30 60 180 1800 15 60

nscache 65535
nscache6 65535

log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F

monitor "/usr/local/3proxy/3proxy.cfg"

daemon
auth strong
users proxyuser:CL:zXGHQD7szBa7aXdGyynD
proxy -6 -p33128 -n -a -iXX.XX.XX.XX -e2a00:f940:1:1:2::8b8
proxy -p33128 -n -a -iYY.YY.YY.YY -eYY.YY.YY.YY

flush
auth none
#auth strong
#users proxyuser:CL:zXGHQD7szBa7aXdGyynD
allow * * * *
allow * * * *
socks -6 -p33129 -n -a -iXX.XX.XX.XX -e2a00:f940:1:1:2::8b8
socks -p33129 -n -a -iYY.YY.YY.YY -eYY.YY.YY.YY

setgid 65534
setuid 65534

Подскажите, куда копать?

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by warmwave** [comment]
1478205312.480  SOCK5.33129 00100 - XX.XX.XX.XX:55152 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205312.531  SOCK5.33129 00100 - XX.XX.XX.XX:55155 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205318.918  SOCK5.33129 00013 - XX.XX.XX.XX:55164 ::ffff:5.45.78.17:443 0 0 0 CONNECT_::ffff:5.45.78.17:443
1478205318.922  SOCK5.33129 00100 - XX.XX.XX.XX:55176 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205318.928  SOCK5.33129 00100 - XX.XX.XX.XX:55194 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205319.498  SOCK5.33129 00100 - XX.XX.XX.XX:3806 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205319.547  SOCK5.33129 00100 - XX.XX.XX.XX:55214 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.072  SOCK5.33129 00100 - XX.XX.XX.XX:55220 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.128  SOCK5.33129 00100 - XX.XX.XX.XX:55233 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.185  SOCK5.33129 00100 - XX.XX.XX.XX:55245 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.232  SOCK5.33129 00100 - XX.XX.XX.XX:55254 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.266  SOCK5.33129 00100 - XX.XX.XX.XX:55257 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.318  SOCK5.33129 00100 - XX.XX.XX.XX:55259 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.430  SOCK5.33129 00100 - XX.XX.XX.XX:55266 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.568  SOCK5.33129 00100 - XX.XX.XX.XX:55272 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.687  SOCK5.33129 00100 - XX.XX.XX.XX:55287 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.707  SOCK5.33129 00100 - XX.XX.XX.XX:55296 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.708  SOCK5.33129 00100 - XX.XX.XX.XX:55298 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.751  SOCK5.33129 00100 - XX.XX.XX.XX:55305 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.785  SOCK5.33129 00100 - XX.XX.XX.XX:55320 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.803  SOCK5.33129 00100 - XX.XX.XX.XX:55323 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.828  SOCK5.33129 00100 - XX.XX.XX.XX:55329 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.828  SOCK5.33129 00100 - XX.XX.XX.XX:55326 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.828  SOCK5.33129 00100 - XX.XX.XX.XX:55332 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.837  SOCK5.33129 00100 - XX.XX.XX.XX:55335 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205320.917  SOCK5.33129 00100 - XX.XX.XX.XX:55341 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205321.235  SOCK5.33129 00013 - XX.XX.XX.XX:3809 ::ffff:78.140.60.55:12802 0 0 0 CONNECT_::ffff:78.140.60.55:12802
1478205321.481  SOCK5.33129 00100 - XX.XX.XX.XX:55365 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205321.533  SOCK5.33129 00100 - XX.XX.XX.XX:55368 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205321.777  SOCK5.33129 00100 - XX.XX.XX.XX:55374 0.0.0.0:0 0 0 0 CONNECT_:::0
1478205322.408  SOCK5.33129 00100 - XX.XX.XX.XX:55389 0.0.0.0:0 0 0 0 CONNECT_:::0

**Comment by z3APA3A** [comment]
У тебя соксификатор сам разрешает имена и запрашивает уже адреса IPv4. Включи в соксификаторе разрешение имен через сервер.

**Comment by warmwave** [comment]
Включено - http://joxi.ru/82Q7d9xCjjNoNr

**Comment by z3APA3A** [comment]
Если бы было включено - в логах были бы имена, а не IP.
