### ISSUE TITLE
Добавление большого количества адресов

### ISSUE THREAD

**Issue by gggrafff** [z3APA3A/3proxy#113]
Добрый день.

Есть сервер на Ubuntu-14.04-amd64. Необходимо поднять на нём много прокси. После того, как количество адресов, добавляемых для интерфейса, переваливает за 300 (даже если прокси-сервер все их не использует), прокси перестают работать все сразу.

Адреса добавляю вот так: ifconfig tun6to4 inet6 add 2001:470:c842:69d:798a:3d1d:307d:bbef/48

299 адресов - работают. 301 - не работают.

Начал искать, думал, нужно изменить ограничение на количество сокетов, но не помогло (пользовался http://forum.ubuntu.ru/index.php?topic=81465.0).

Поиск в переменных sysctl: 

# sysctl --all | grep 300 
kernel.keys.gc_delay = 300 
net.core.netdev_budget = 300 
net.ipv4.neigh.default.base_reachable_time_ms = 30000 
net.ipv4.neigh.eth0.base_reachable_time_ms = 30000 
net.ipv4.neigh.lo.base_reachable_time_ms = 30000 
net.ipv4.neigh.sit0.base_reachable_time_ms = 30000 
net.ipv4.neigh.tun6to4.base_reachable_time_ms = 30000 
net.ipv4.route.gc_timeout = 300 
net.ipv6.neigh.default.base_reachable_time_ms = 30000 
net.ipv6.neigh.lo.base_reachable_time_ms = 30000 
net.ipv6.neigh.sit0.base_reachable_time_ms = 30000 
net.ipv6.neigh.tun6to4.base_reachable_time_ms = 30000 
vm.dirty_expire_centisecs = 3000

Вроде, ничего подходящего.

Адреса для интерфейса добавляются и пингуются нормально. 
На форуме сказали, что нет ограничения на количество адресов для интерфейса и смотреть нужно в сторону ограничений 3proxy.
Этому есть контраргумент, но не знаю, насколько весомый: я добавлял 200 адресов и вешал на них 400 прокси (на разных портах) - работало. А добавление более чем 300 адресов, даже если не все они используются 3proxy приводит к неработоспособности.

Подскажите, пожалуйста, с чем может быть связано, как исправить это ограничение?

**Comment by gggrafff** [comment]
Вот что говорят на linux.org.ru: 
> Насколько я знаю, никаких ограничений на количество адресов на интерфейс в современных ядрах нет. Если всё добавляется без ошибок и пингуется, то надо смотреть в сторону настроек 3proxy.

> Вот честно, ни разу не работал с 3proxy, но если адреса сами по себе работают, логично предположить, что проблема не в ограничениях системы. Когда-то давно было ограничение в 255 адресов на интерфейсе, но я уже не помню даже, как давно это было. Поэтом и подумал, что может проблема не в ядре и не в сетевых настройках.
> Тем более, раз удалось запустить 400 прокси, значит и не в количестве сокетов проблема. Сокет занимается не тогда, когда ты адрес на интерфейс вешаешь, а когда ты порт занимаешь.

**Comment by z3APA3A** [comment]
В 3proxy нет ограничений. Смотри в сторону ограничений на сокеты, процессы, и т.п. (каждый сервис требует открытого порта и пораждает отдельный поток).
