### ISSUE TITLE
http proxy -a not truly anonymous for ipv6

### ISSUE THREAD

**Issue by killerhis** [z3APA3A/3proxy#115]
Hi,

I've been testing 3proxy for a while now and I've encounter some problems regarding the -a anonymity. So does the -a still send a "HTTP_X_FORWARDED_FOR" in the header for ipv6 (-6). I encouter some issue creating new Facebook accounts using 3proxy and ipv6, so there are probably more footprints leaked. I don't have this issue with other proxies such as Squid, but I love 3proxy for it's simplicity and low memory usage.

Can someone investigate the footprints 3proxy leaves with "-a -6" setting?

**Comment by z3APA3A** [comment]
I can't confirm this behavior. What makes you think 3proxy sends X-Forwarded-For?

**Comment by killerhis** [comment]
https://www.find-ip.net/proxy-checker

Also my facebook accounts are getting banned using 3proxy, when I use the same ip range with a Squid it's all fine. So I assume there is some foodprint left behind by 3proxy using "-a -6".

**Comment by z3APA3A** [comment]
And what does https://www.find-ip.net/proxy-checker shows for you?

**Comment by killerhis** [comment]
REMOTE_PORT	10795	
HTTP_CACHE_CONTROL	no-cache	
HTTP_PRAGMA	no-cache	
HTTP_X_FORWARDED_FOR	[my 3proxy ipv6]

**Comment by z3APA3A** [comment]
3proxy doesn't generate X-Forwarded-For header with real IP in any config. It uses "Forwarded:" header (RFC 7239) if ran without -a  and this header has different structure.

**Comment by z3APA3A** [comment]
Also, there is no way for proxy to add any headers to https:// content.
