### ISSUE TITLE
Questions about counter

### ISSUE THREAD

**Issue by chenxsan** [z3APA3A/3proxy#117]
1. The [`counters.sample`](https://github.com/z3APA3A/3proxy/blob/devel/cfg/counters.sample) was created in 2014, so I'm wondering if this statement still true:

```
# There is no way to configure it in a single line, we need a line
# for every user we have
countin "3/User 1" D 20 user1 * * 80,81,8080-8088
countin "4/User 2" D 20 user2 * * 80,81,8080-8088
# ...
countin "202/User 200" D 20 user200 * * 80,81,8080-8088
```
Can I do it in a single line now? It's inconvenient when I need to manage a lot of users dynamically.

2. If I can run two instances of 3proxy, can I set the `counter` file to the same file, like:

```
counter "/etc/3proxy/3profy.3cf"
```
I want to run 3proxy on two servers, and users are allowed to access both of them, how can I share the 3proxy limit with each other.

3. What's the difference between `countin` with `countout`, there's only `countin` in the example. Say I'm downloading files from the proxy, does the files' size belongs to `countin`?

Thanks for your time.

**Comment by z3APA3A** [comment]
1. 3proxy is really simple yet flexible, counter is not bounded to user (unless you bound it to user), it can be bounded to any combination of user, IP, port, time, weekday, etc. If you have a lot of users and every user needs to be separately accounted  - you need a separate counter. If you you manage users dynamically, you should also manage counters dynamically - generate counter for every user, that's actually simple.
Alternatively, you can use any log parsing software for accounting if you need no realtime actions.

2. No, you can not. 3proxy writes counter files periodically, but only reads it on startup, there is no way to exchange information and have common counters between 2 instances. But actually I see no reason to have 2 instances of proxy on the same host.

3. countin accounts incoming traffic, countout accounts outgoing traffic, if you downloading files you have mostly incoming traffic with relatively high countin and relatively low countout.
