### ISSUE TITLE
Как запретить или разрешить доступ к сервисам 3proxy с определенных MAC адресов?

### ISSUE THREAD

**Issue by k64t34** [z3APA3A/3proxy#118]
Как запретить или разрешить доступ к сервисам 3proxy с определенных MAC адресов?

**Comment by z3APA3A** [comment]
По Mac адресам - никак, если все адреса локальные, можно сделать статическую привязку в ARP или разбавать через DHCP. А еще лучше использовать auth dnsname совместно с DHCP и привязкой.

**Comment by k64t34** [comment]
Уточнение - планировал использовать 3proxy под Windows.
Возможно ли  будет  использовать фильтрацию по MAC  если создать  внешний  плагин?

**Comment by z3APA3A** [comment]
Да, можно, но опять же при условии что клиенты в локальной сети без маршрутизации. MAC-адрес виден только на канальном уровне.

**Comment by k64t34** [comment]
Можете дать пример использования auth dnsname.
Имя хоста нужно вставлять в sourcelist?
Имя хоста должно быть с доменом?

auth dnsname
allow * host.firm.ru

**Comment by z3APA3A** [comment]
При использовании auth dnsname обратное имя клиентского хоста используется в качестве имени пользователя. Имя хоста должно быть то, которое разрешается по IP-адресу. Прямое и обратное разрешение обязательно должны совпадать (т.е. клиентский IP должен резолвится имя, а имя должно резолвиться в тот же клиентский IP). И лучше использовать authcache, иначе будет слишком много запросов.

authcache ip 300
auth cache dnsname
allow host1.my.domain,host2.my.domain
