### ISSUE TITLE
Major issues with name resolve using localhost DNS

### ISSUE THREAD

**Issue by basiliocat** [z3APA3A/3proxy#120]
3proxy returns 502 on HTTPS CONNECT to some hosts, for example https://market.yandex.ru. 
OS is FreeBSD 11.0, local resolver is BIND 9.10. Local DNS returns names in uppercase: 
\# nslookup market.yandex.ru 127.0.0.1
Non-authoritative answer:
Name:	market.YANDEX.ru
Address: 213.180.204.22
Remote DNS servers, which return names in lower case, works ok.

I've debugged it down to udpresolve() at auth.c:1167, here we have 
flen = buf[k+11] + (((unsigned short)buf[k+10])<<8);
k=34 
k+11=45,k+10=44 and buf[k+11]=68, buf[k+10]=78
resulting flen= 20036
while len = 196 (actual packet length, caught by tcpdump is IP: 62 bytes, UDP - 42 bytes)
So, next condition at auth.c:1168 is true:
if((k+12+flen) > len) {
Here's dump of buf (taken at auth.c:1168):
(gdb) x/190b buf
0x3f    0xdf    0x81    0x80    0x00    0x01    0x00    0x01
0x00    0x02    0x00    0x04    0x06    0x6d    0x61    0x72
0x6b    0x65    0x74    0x06    0x79    0x61    0x6e    0x64
0x65    0x78    0x02    0x72    0x75    0x00    0x00    0x01
0x00    0x01    0x06    0x6d    0x61    0x72    0x6b    0x65
0x74    0x06    0x59    0x41    0x4e    0x44    0x45    0x58
0xc0    0x1a    0x00    0x01    0x00    0x01    0x00    0x00
0x06    0xa6    0x00    0x04    0xd5    0xb4    0xcc    0x16
0xc0    0x29    0x00    0x02    0x00    0x01    0x00    0x03
0x3c    0xd7    0x00    0x06    0x03    0x6e    0x73    0x31
0xc0    0x13    0xc0    0x29    0x00    0x02    0x00    0x01
0x00    0x03    0x3c    0xd7    0x00    0x06    0x03    0x6e
0x73    0x32    0xc0    0x13    0x03    0x6e    0x73    0x31
0xc0    0x29    0x00    0x01    0x00    0x01    0x00    0x03
0x58    0xf7    0x00    0x04    0xd5    0xb4    0xc1    0x01
0x03    0x6e    0x73    0x32    0xc0    0x29    0x00    0x01
0x00    0x01    0x00    0x03    0x58    0xf7    0x00    0x04
0x5d    0x9e    0x86    0x01    0xc0    0x64    0x00    0x1c
0x00    0x01    0x00    0x03    0x3c    0xd7    0x00    0x10
0x2a    0x02    0x06    0xb8    0x00    0x00    0x00    0x00
0x00    0x00    0x00    0x00    0x00    0x00    0x00    0x01
0xc0    0x78    0x00    0x1c    0x00    0x01    0x00    0x03
0x3c    0xd7    0x00    0x10    0x2a    0x02    0x06    0xb8
0x00    0x00    0x00    0x01    0x00    0x00

**Comment by z3APA3A** [comment]
Can you try latest devel (patch: afbc27eac47bb8c01b9a4debda00da57f0cab66b)

**Comment by basiliocat** [comment]
Nope, udpresolve still returns 0, here's trace:
Breakpoint 8, udpresolve (af=2, name=0x801c13040 "market.yandex.ru", value=0x8018174c4 "", retttl=0x0, param=0x0, makeauth=0) at auth.c:1163
1163			for (j = 0; j < na; j++) {
(gdb) print na
$8 = 1
(gdb) n
1164				while(buf[k] < 192 && buf[k] !=0 && (k+buf[k]) < len) k+= buf[k];
(gdb) print k
$9 = 34
(gdb) print buf[k]
$10 = 6 '\006'
(gdb) n
1165				if(!buf[k]) k--;
(gdb) print k
$11 = 156
(gdb) n
1166				if((k+(af == AF_INET6?28:16)) > len) {
(gdb) print k
$13 = 155
(gdb) print len
$14 = 196
(gdb) print af
$15 = 2
(gdb) n
1169				flen = buf[k+11] + (((unsigned short)buf[k+10])<<8);
(gdb) n
1170				if((k+12+flen) > len) {
(gdb) print flen
$18 = 0
(gdb) n
1173				if(makeauth != 1){
(gdb) n
1174					if(buf[k+2] != 0 || **buf[k+3]** != (af == AF_INET6?0x1c:0x1) || **flen** != (af == AF_INET6?16:4)) {
(gdb) print buf[k+2]
$20 = 0 '\0'
(gdb) print **buf[k+3]**
$21 = **0** '\0'
(gdb) print **flen**
$22 = **0**
(gdb) n
1175						k+= (12 + flen);
(gdb) n
1176						continue; 		/* we need A IPv4 */
(gdb) n
1163			for (j = 0; j < na; j++) {		
(gdb) n
1203		}
(gdb) n
1044		for(i=0; i<n; i++){
(gdb) n
1204		return 0;

**Comment by z3APA3A** [comment]
Yes, I see the bug, try this patch a9fb0ea9696bcbfb99b679c6bf5a6333e612fce1
I have no resolver with behavior like this, so I can't test it by myself, sorry.

**Comment by basiliocat** [comment]
Patch a9fb0ea seems to work, thanks!
