### ISSUE TITLE
0.8.7 Errors on Windows XP

### ISSUE THREAD

**Issue by S60Team** [z3APA3A/3proxy#121]
When i launch 0.8.7 Full on Windows XP i get this error: inet_pton not found in DLL WS2_32.dll
When i launch 0.8.7 Lite - plugins not work:
start not found in StringsPlugin.dll, code: 127
Command: 'plugin' failed with code 2, line 15

Code
plugin "StringsPlugin.dll" start c:\proxy\3proxy\bin\rus.3ps
plugin PCREPlugin.dll pcre_plugin

When i launch 0.8.6 - all works great!
Can i recommend you my article "Using 3proxy as AdBlock"?
Can you add it to ypur Wiki?
PS: What about WebSocket in 3proxy? Does it work?
PPS: OpenWatcom libraries is about 80mb. it's very big for program so small.

**Comment by z3APA3A** [comment]
Try lite version with latest devel (with this patch: c650d3220685f5633cd5c29a74003067e4f36266).

**Comment by S60Team** [comment]
I get same 2 errors when enabling Plugins.

**Comment by z3APA3A** [comment]
Sorry, binaries were not updated. Try again.

**Comment by z3APA3A** [comment]
Any succcess?

**Comment by S60Team** [comment]
Downloaded 0.9dev-lite from link above and 0.8.7-lite.
Still getting errors:
start not found in StringsPlugin.dll, code: 127
Command: 'plugin' failed with code 2, line 5

Config (c:\3proxy\bin):
plugin "StringsPlugin.dll" start c:\3proxy\bin\rus.3ps
plugin PCREPlugin.dll pcre_plugin

**Comment by z3APA3A** [comment]
It was not that easy. Try to update again.
