### ISSUE TITLE
How can I read report from 3cf file.

### ISSUE THREAD

**Issue by chenxsan** [z3APA3A/3proxy#123]
According to the documentation [here](https://3proxy.ru/doc/man3/3proxy.cfg.3.html):

```
Report is text file with counter values in format:
<COUNTERNUMBER> <TRAF>

```
And I had `counter` in my config:

```
counter /usr/local/etc/3proxy/3proxy.3cf H /usr/local/etc/3proxy/traf/traf
```
But when I tried to view 3cf file in `less`, I got:

```
"3proxy.3cf" may be a binary file.  See it anyway?
``` 
I'm wondering if I misunderstood something here.

**Comment by z3APA3A** [comment]
Hourly text reports are in /usr/local/etc/3proxy/traf/traf directory.
