### ISSUE TITLE
3proxy Support SHA256 Signature?

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#124]
I'm trying use SHA256 Signature but 3proxy crashed or how to generate a certificate with long time expires, Thanks,

**Comment by z3APA3A** [comment]
can you describe your problem in details? Proxy is not affected with SSL/TLS configuration in any way, for TLS/SSL it simply passes the data without any parsing.

**Comment by RedToor** [comment]
I'm using TLS plugin(ssl_mitm) when I start the proxy and go to google.com for example.
[https://s29.postimg.org/z7ida2m9j/Sin_t_tulo.png](imagen)

**Comment by z3APA3A** [comment]
You have to install 3proxy's certificate as a trusted root into the browser

**Comment by z3APA3A** [comment]
Currently, plugin only works with SHA1 signatures, but it should not lead to any problems for self-signed certificates.

**Comment by RedToor** [comment]
Oks, in the browser the SHA1 signatures is deprecated.

how to build the plugin for to will add SHA256 signature, I'm on Windows and use MinGW but I have much problems in compilation?.

**Comment by z3APA3A** [comment]
I've added a patch to devel to sign with SHA-2:
https://github.com/z3APA3A/3proxy/commit/3c9ff54ae810e32f3e7857784f5c51e63c011e02

**Comment by z3APA3A** [comment]
Proxy and plugin must be built with same compiler. For mingw you can use Makefile.win

**Comment by RedToor** [comment]
Oks Thank so much...

**Comment by RedToor** [comment]
Sorry , I have this proble undefined reference to `SSL_set_tlsext_host_name' when compilate

C:\Users\putin\AppData\Local\Temp\ccIyeyLA.o:my_ssl.c:(.text+0x519): undefined reference to `SSL_set_tlsext_host_name'

**Comment by z3APA3A** [comment]
Which version of OpenSSL do you use?

**Comment by RedToor** [comment]
Hi, I solved, I started a new project with VS15 and it was good, but not does work with proxy, I created the project as static library.

**Comment by z3APA3A** [comment]
3proxy should be built with Makefiles, creating MSVC project for it is not trivial.
I've uploaded latest devel versions:
http://3proxy.ru/current/3proxy-0.9-devel.zip
http://3proxy.ru/current/3proxy-0.9-x64-devel.zip

**Comment by RedToor** [comment]
Thanks so much.

**Comment by RedToor** [comment]
one last question I can capture post data completly.

**Comment by z3APA3A** [comment]
Yes, you can via plugin's filters API.

**Comment by RedToor** [comment]
Oks, but from source-code of TLS plugin(ssl_mitm), What funcion I can edict ?

**Comment by z3APA3A** [comment]
SSL plugin does certificate spoofing and traffic encoding / decoding, it doesn't process any data.
To process data you may need traffic filtering plugin, an example is PCREPlugin.
What are you trying to do? If you need UI to look inside TLS, you may probably want Fiddler or Charles. 3proxy is a server, it's "set and forget" type application, not the tool you may want to interact, you should know exactly how do you want it to work.

**Comment by RedToor** [comment]
I want save data that is passing via proxy as post data, also I want inject  a banner html into the page.

**Comment by RedToor** [comment]
is possible?

**Comment by z3APA3A** [comment]
It's possible. Not easy yet, because 3proxy doesn't caching. You can not simply insert banner, you need also correct Content-Length / chunk size headers.

**Comment by RedToor** [comment]
but if I insert diretly in _ssl_recv_ , ssl_recvfrom , ssl_read no is necesary modify the head response or yes?
