### ISSUE TITLE
Работа одного ip6 на двух протоколах

### ISSUE THREAD

**Issue by Piduna** [z3APA3A/3proxy#127]
Добрый день.  Хочу задать вопрос по поводу назначения одному ip6 адресу двух протоколов, таких как proxy и socks . Выдержка из моего конфига:

```
proxy -6 -n -a -i<одинаковый ip4> -e<первый ip6> -p18349
socks -6 -n -a -i<одинаковый ip4> -e<первый ip6> -p37340
socks -6 -n -a -i<одинаковый ip4> -e<второй ip6> -p37341
...
```

Смогут ли работать proxy и socks первой и второй строки у разных клиентов. Версия 3proxy – 0.8.6.

**Comment by z3APA3A** [comment]
Да, смогут.
