### ISSUE TITLE
Questions SSL-Plugin

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#128]
I use SslPlugin and PCREPlugin and not does work in SSL page.

* What openssl version do you use?
* is possible migrate SslPlugin to Windows XP?
* What compiler version do you use?
* PCREPlugin No work SslPlugin?
* If exists sha1_hash in src_cert (120 my_ssl.c)?

if I insert diretly in ssl_recv , ssl_recvfrom , ssl_read no is necesary modify the head response or yes?

-----
I try compilate [Error](https://s28.postimg.org/lb3fhnhbh/Sin_t_tulo.png) and compilating with MSVC15
(sorry for insisting.)

**Comment by z3APA3A** [comment]
I can't reproduce issue, for me PCRE works with SSL. Any OpenSSL version with SNI support can be used. Currently, 3proxy comes compiled with MSVS 10 + Windows SDK 7.1 (full version) / OpenWatcom 2.0 (lite version).

**Comment by RedToor** [comment]
if I want change something in facebook with PCREPlugin is not does work, why ?
