### ISSUE TITLE
Tunnel filter. (PAC file)

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#129]
How can I configure my proxy just to pass certain pages or failing a specific program, example

`if HOST REQUEST is www.example.com -> USE PROXY` or 
`if Program is  chrome -> USE PROXY`

**Comment by z3APA3A** [comment]
PAC file is used by browser itself, it's not processed by proxy. To control access via 3proxy you can use with ACLs 
http://3proxy.ru/howtoe.asp#ACL
e.g.
allow * * www.example.com 
or use PCREPlugin to filter by e.g. User-Agent header
http://3proxy.ru/plugins/PCREPlugin/
