### ISSUE TITLE
Не получается собрать v08x на Debian 8.2 jessie

### ISSUE THREAD

**Issue by sanyo-ok** [z3APA3A/3proxy#13]
может, пакетов каких не хватает, надо поставить?
мета build-essential установлен
а IPv6 только в 08 поддерживается? в 07 IPv6 нету?

gcc -o 3proxy -Wall -O2 -pthread   3proxy.o mainfunc.o auth.o datatypes.o srvproxy.o srvpop3p.o srvsmtpp.o srvftppr.o srvsocks.o srvtcppm.o srvicqpr.o srvudppm.o sockmap.o sockgetchar.o myalloc.o common.o mycrypt.o md5.o md4.o base64.o ftp.o smbdes.o ntlm.o stringtable.o srvwebadmin.o srvdnspr.o plugins.o  -lcrypto -lssl -ldl
/usr/bin/ld: cannot find -lcrypto
/usr/bin/ld: cannot find -lssl
collect2: error: ld returned 1 exit status
Makefile.inc:168: recipe for target '3proxy' failed
make[1]: *** [3proxy] Error 1
make[1]: Leaving directory '/usr/src/3proxy/08/src'
Makefile.inc:6: recipe for target 'all' failed
make: *** [all] Error 2
root@vpsX:/usr/src/3proxy/08# Write failed: Broken pipe

**Comment by sanyo-ok** [comment]
и еще несколько отвлеченный от темы вопрос, правильно ли я понимаю, что с помощью 6to4
можно получить почти неограниченое количество адресов IPv6?
https://version6.ru/ways

можно ли их задействовать в качестве исходящих для 3proxy?
а в качестве входящего использовать один и тот же IPv4 с разными портами или логинами?

**Comment by z3APA3A** [comment]
Либо установи библиотеки OpenSSL (скорее всего, называются что-нибудь типа libssl-dev) либо убери -lcrypto -lssl из LIBS и SSLPlugin из PLUGINS.

IPv6 есть только в 0.8, собственно это основное что в нем появилось.

По второму вопросу - да, но связь может быть не со всеми IPv6 адресами, зависит от наличия шлюзов.

**Comment by sanyo-ok** [comment]
скомпилировать под 64 бита удалось, 

подскажите, как скомпилировать под 32 бита, какой ключ какому make указать?

**Comment by z3APA3A** [comment]
Я не в курсе, можно ли на amd64 собирать код для i386 без кросс-компиляции. Если собирать на i386, то ничего дополнительно не требуется.

**Comment by sanyo-ok** [comment]
а насколько вырастет потребление памяти в процентах при аналогичной нагрузке в x64 по сравнению с x32, насколько я знаю в 32битной оси память расходуется экономнее, актуально для VPS

**Comment by z3APA3A** [comment]
Существенной разницы не будет, основной расход памяти это стеки потоков и буферы для данных, которые напрямую от разрядности ОС не зависят.

**Comment by sanyo-ok** [comment]
немного не по теме

Как думаете для DotNet программ типа ZennoPoster, есть разница в какой венде они запускаются 32/64? там  ведь N браузеров стартует

**Comment by z3APA3A** [comment]
Есть, на .Net фактически происходит компиляция на конечной машине

**Comment by sanyo-ok** [comment]
в том смысле, что есть ли разница по потреблению памяти в вариантах венды 32/64 бит

скорее всего сборки ZennoPoster обрабатываются ngen, после чего хранятся уже в скомпилированном виде соответствующей разрядности

интересно
1) есть ли значительный перерасход памяти base.exe в варианте 64 бит по сравнению с 32-мя

2) base.exe обычно потребляет  в пределах 1 гига, т.е. можно запускать в режиме 32 бита CPU, 36 бит адресного пространства с переключением страниц, 64 гигабайта оперативки
Вопрос: будет ли в режиме 32 бит+64 гига тормозить по сравнению с 64 бит и насколько, если несколько процентов 1-5% - это незначительно

http://rutracker.org/forum/viewtopic.php?t=4694409

**Comment by z3APA3A** [comment]
Я не думаю, что ты здесь найдешь ответ на этот вопрос и порекомендовал бы просто попробовать на виртуалках оба варианта с тестовой нагрузкой.
