### ISSUE TITLE
Changing string in facebook

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#130]
if I want change something in facebook(www.facebook.com) with PCREPlugin is not does work is my config:

         auth none
         internal 127.0.0.1
         plugin SslPlugin.dll ssl_plugin
         plugin PCREPlugin.dll pcre_plugin
         ssl_mitm
         pcre_rewrite srvdata dunno "2017" "2018"
         proxy -p3129

**Comment by z3APA3A** [comment]
It's not that easy. Even SSL-stripped content is not necessary in cleartext, it may be gzip'ed

**Comment by RedToor** [comment]
Thanks for answer, The some pages this happens.

`pcre_rewrite srvdata dunno "2017" "2018"` WORK
`pcre_rewrite srvdata dunno "2017" "20188"` NOT DOES WORK, (ERR_INVALID_CHUNKED_ENCODING)

is error of decoding (gzip) or size of chunked?

**Comment by z3APA3A** [comment]
If you change the size of data, you should also change the size of chunk and/or content-length

**Comment by RedToor** [comment]
bro u have ICQ or something other medio for communication? is for bussines.
