### ISSUE TITLE
minor typo in man page

### ISSUE THREAD

**Issue by mumixam** [z3APA3A/3proxy#132]
https://github.com/z3APA3A/3proxy/blob/88263ebde93c3d7fdcf493f8804576cf1197e57d/man/3proxy.cfg.3#L463
"is auth is" should be "if auth is"

**Comment by the1337guy** [comment]
Any updatse about this? Can be easily fixed.

**Comment by z3APA3A** [comment]
There is a lot of bugs in English documentation, it needs to be audited by native speaker. Making an issue for every typo is just worthless.

**Comment by mumixam** [comment]
would you merge a PR for English docs?
