### ISSUE TITLE
Feature request: не резолвить имя прокси сервера

### ISSUE THREAD

**Issue by davidzb3** [z3APA3A/3proxy#137]
Есть прокси сервер abcdefabcdefabcd.onion, который не преобразуется в ip адрес, а доступен только через socks5 на 127.0.0.1:9050.
Конфиг, который, как я думал, позволит пользоваться этим прокси к сожалению не работает:
```
 fakeresolve
 auth iponly
 allow * *
 parent 1000 socks5 127.0.0.1 9050
 parent 1000 connect+ abcdefabcdefabcd.onion 8081
 proxy -a -p8080
 flush
 end
```

Прошу добавить комманду типа "noresolve", которая будет запрещать резолвить имя proxy/socks/tcppm сервера через dns или заменять его на 127.0.0.2, а будет посылать hostname в запрос.

**Comment by z3APA3A** [comment]
попробуй текущий devel с socks5+

**Comment by ricary37** [comment]
неправильно собирается пакет на отправку в порт 9050.
вот что посылается согласно tcpdump:
если connect+ a:8080 => 0501 0003 0490 02a6 011f 90
если connect+ aa:8080 => 0501 0003 0490 923b 021f 90
если connect+ aaa:8080 => 0501 0003 0490 6294 011f 90
проблема в buf[3] с hostname.

**Comment by z3APA3A** [comment]
Можешь показать конфиг и дать tcpdump?
Ты уверен что все файлы обновил / пересобрал, не может быть что что-то из conf.c / auth.c осталось непересобранным?

**Comment by ricary37** [comment]
собирал в новой папке: mkdir tmp;wget ...;...;make -f Makefile.Linux
конфиг и tcpdump выслал на email.
могу дать доступ к vps.

**Comment by z3APA3A** [comment]
Попробуй с последнем патчем.

**Comment by ricary37** [comment]
проверил socks4+ и connect+ работают.
спасибо!
