### ISSUE TITLE
IPv6 only proxy is not authenticated with iponly

### ISSUE THREAD

**Issue by tomassiro** [z3APA3A/3proxy#140]
In version 0.8.8 an IPv6 only proxy (example:  proxy -p802 -6 -a -i2001:2300:60:4508:0:4351:8314:f79b -e2001:2300:60:4508:0:4351:8314:f79b) cannot be authenticated using "auth iponly" it can only be authenticated using "auth strong" with a username and password.

This issue has also been confirmed in the 0.9 beta version.

**Comment by z3APA3A** [comment]
What do you have in config and log files?

**Comment by tomassiro** [comment]
I was trying to use an IPv6 only proxy with an IPv4 auth IP. I added my IPv6 address as an auth IP and it works. I know it's pretty bad but hopefully finds this useful.
