### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by poiuylkjhg** [z3APA3A/3proxy#141]
я запускаю 
3proxy.exe "C:\Program Files\3proxy-0.8.7\bin\3proxy.cfg"
и получаю сообщение
Точка входа в процедуру inet_pton не найдена в библиотеке DLL WS2_32.dll
Что это значит?

**Comment by z3APA3A** [comment]
Это значит, что вы на старой версии Windows пытаетесь запустить полную версию 3proxy, а для этого существует lite.
