### ISSUE TITLE
Failed loading Plugin on Linux

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#142]
I'm trying load SSLPlugin on linux _plugin SSLPlugin.ld.so ssl_plugin_ but  `Command: 'plugin' failed with code 1, line 7`

**Comment by z3APA3A** [comment]
You must specify full path to plugin.

**Comment by RedToor** [comment]
Thanks so much.

**Comment by RedToor** [comment]
./3proxy: symbol lookup error: /root/3proxy/src/SSLPlugin.ld.so: undefined symbol: CRYPTO_num_locks

**Comment by RedToor** [comment]
Error: `./3proxy: symbol lookup error: /root/3proxy/src/SSLPlugin.ld.so: undefined symbol: CRYPTO_num_locks`
