### ISSUE TITLE
plugin failed with code 1, line 1

### ISSUE THREAD

**Issue by poiuylkjhg** [z3APA3A/3proxy#143]
I launch
3proxy.exe "C:\Program Files\3proxy-0.8.7-lite\bin\3proxy.cfg"
-------------------------
and get this message
-------------------------
Failed to load C:\Program Files\3proxy-0.8.7-lite\bin\SslPlugin.dll, code 126
Command: 'plugin' failed with code 1, line 1
-------------------------
I want to change
Accept-Encoding: gzip, deflate
client header for
Accept-Encoding: identity
in the request using ssl and then forward this request
to another socks proxy i.e. into TOR
what am I doing wrong?
-------------------------
Here is my 3proxy.cfg
-------------------------
plugin "C:\Program Files\3proxy-0.8.7-lite\bin\SslPlugin.dll" ssl_plugin
ssl_certcache "C:\Program Files\3proxy-0.8.7-lite\bin"
ssl_mitm
#################
plugin "C:\Program Files\3proxy-0.8.7-lite\bin\PCREPlugin.dll" pcre_plugin
pcre_options PCRE_CASELESS 
pcre_rewrite cliheader dunno "^Accept-Encoding: .*$" "Accept-Encoding: identity"
#################
monitor 3proxy.cfg
auth none

allow *
parent 1000 socks5+ 127.0.0.1 9150
proxy -n -p8119 -u -a -46 -t -i127.0.0.1

end

**Comment by z3APA3A** [comment]
See release notes for 3proxy 0.8.8.
https://github.com/z3APA3A/3proxy/releases
