### ISSUE TITLE
Segmentation fault : loading PCREPlugin

### ISSUE THREAD

**Issue by RedToor** [z3APA3A/3proxy#144]
in config file `plugin /root/3proxy/src/PCREPlugin.ld.so pcre_plugin` and when run: `Segmentation fault`

**Comment by z3APA3A** [comment]
1. make sure plugin is compiled from the same sources as main proxy
2. try to use 'stacksize'

**Comment by RedToor** [comment]
1) yes is the same version
2) how to? command line or config file?

**Comment by z3APA3A** [comment]
command line
http://3proxy.ru/doc/man3/3proxy.cfg.3.html

**Comment by RedToor** [comment]
Nothing , same error.

**Comment by z3APA3A** [comment]
show full configuration
