### ISSUE TITLE
3proxy

### ISSUE THREAD

**Issue by Bosheit** [z3APA3A/3proxy#145]
Добрый вечер, прошу прошение если не по теме.
в данном видео: https://www.youtube.com/watch?v=2KK0pZBEPgU
момент( 4:24) когда молодой человек пишет команду "services.nsc" у него открывается окно, а когда я пишу эту же команду выдает ошибку:
"C:\Program Files\3proxy\bin64>services.nsc
'services.nsc' is not recognized as an internal or external command,
operable program or batch file."
Кто знает, в чем может быть проблема?

**Comment by shark136** [comment]
открытие апплета "Службы" - команда "services.msc"-- Новоселов Михаил

**Comment by Bosheit** [comment]
Открыл, но почему то там нет службы "3proxy"

**Comment by z3APA3A** [comment]
Установи службу
http://3proxy.ru/howtor.asp#INSTNT
устанавливать надо из повышенной командной строки (командную строку запустить от имени администратора)
