### ISSUE TITLE
Does nsrecord support one domain has multiply ips?

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#146]
Hi,
    Some websites use cdn,so on domain has multiply ips.

Does nsrecord support one domain has multiply ips?When client access the specified website via proxy,3proxy connect to one random ip.
    
Example:

nserver 8.8.8.8
nserver 8.8.4.4
nsrecord  www.testsite.com 192.168.1.10
nsrecord  www.testsite.com 192.168.1.11
nsrecord  www.testsite.com 192.168.1.12
……
nscache 65536
……

Kindly regards
Rain

**Comment by z3APA3A** [comment]
No, 3proxy attempts to use the same IP even in the case of the external resolver, because this better matches behavior of the client. You can either use local DNS server without 3proxy caching and create the zone or use 'parent' in 3proxy for round-robin.
