### ISSUE TITLE
Снижение работоспособности при большом количестве прокси

### ISSUE THREAD

**Issue by gggrafff** [z3APA3A/3proxy#148]
Добрый день
Когда поднимаю порядка 1000 адресов, наблюдается снижение работоспособности. Прокси начинают отвечать через раз. Возвращают 502 bad gateway.
Выхожу из ситуации, запуская вторую копию 3proxy на этом же компе. 
То есть 1200 адресов в одном конфиге работают плохо. По 600 адресов в двух конфигах работают хорошо.
Скажите, пожалуйста, чем может быть вызвано данное ограничение? Сам 3proxy не вывозит? Или система накладывает ограничения? ОС: debian 8.
Можно ли как-то это ограничение снять? 
Спасибо.

**Comment by z3APA3A** [comment]
Что значит "1200 адресов в одном конфиге"? Как они заданы? Что в логах при 502й ошибке?

**Comment by gggrafff** [comment]
В 3proxy.cfg создано n пользователей. В сумме у них всех m прокси поднято. Когда m становится очень большим, работать начинает плохо.
В логах при этом пишутся ошибки 00100:
Date:30.03.2017 Time:08:36:23.409 User:tozyb Proxy:PROXY Port:4413 **Error:00100** Server:0.0.0.0:0 Query:0.0.0.0:443 Out:0byte In:0byte Host:www.instagram.com Chain:0 Text:CONNECT www.instagram.com:443 HTTP/1.1
Заданы стандартно:
proxy -6 -n -a -p2351 -i185.130.104.133 -e2a07:4dc0:1ed:f767:ad27:d99f:ef00:6035
Если запускать два 3proxy, каждый со своим конфигом, и поделить m адресов между ними, то работает стабильно.

**Comment by z3APA3A** [comment]
А nserver прописан?

**Comment by gggrafff** [comment]
в 3proxy.cfg - нет
dns-nameservers прописаны в /etc/network/interfaces

**Comment by z3APA3A** [comment]
А ты пропиши nserver/nscache/nscache6, потому что стандартный резолвер в glibc ужасно работает при большом количестве интерфейсов.

**Comment by gggrafff** [comment]
Прописал
nserver 2001:4860:4860::8888
nscache 65536
nscache6 65536
работало всё. добавил ещё 500 прокси (всего около 1300 стало), перестало работать.

**Comment by z3APA3A** [comment]
с какой ошибкой? И как в итоге выглядит конфиг?

**Comment by z3APA3A** [comment]
и на какой версии 3proxy

**Comment by z3APA3A** [comment]
и на какой платформе, под какими пользователями и что показывает ulimit -a?

**Comment by gggrafff** [comment]
сервер vps. ОС linux debian 8. работаю от root. 3proxy-0.8.6
с логами позже скажу. логфайл много весит, качаю. 
конфиг
log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "GDate:%d.%m.%Y Time:%H:%M:%S.%. User:%U Proxy:%N Port:%p Error:%E Client:%C:%c Server:%R:%r Query:%Q:%q Out:%Obyte In:%Ibyte Host:%n Chain:%h Text:%T"
rotate 30
pidfile /usr/local/etc/3proxy/3proxy.pid
maxconn 100
nserver 2001:4860:4860::8888
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
daemon
setgid 65535
setuid 65535
flush
auth strong
users много пользователей abc:CL:def
много проксей. Записи вида:
allow abc
proxy -6 -n -a -p2272 -i185.130.104.133 -e2a07:4dc0:1ed:2c3b:b7b3:3ca3:c0ad:266f
...

root@DS844605:~# sysctl -a | grep kernel.threads-max
kernel.threads-max = 27700

root@DS844605:~# uname -a
Linux DS844605.clientshostname.com 4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux

root@DS844605:~# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 13850
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 13850
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by gggrafff** [comment]
Включена служба ndppd ещё.

**Comment by gggrafff** [comment]
весь лог файл не скачал пока, приведу фрагменты. Такие записи нашёл:
Date:31.03.2017 Time:20:43:56.425 User:kulakov Proxy:PROXY Port:2272 Error:00100 Client:91.228.155.195:53210 Server:0.0.0.0:0 Query::::443 Out:0byte In:0byte Host:www.facebook.com Chain:0 Text:CONNECT www.facebook.com:443 HTTP/1.1
Date:31.03.2017 Time:20:44:01.744 User:- Proxy:PROXY Port:2272 Error:00511 Client:91.228.155.195:53212 Server:2a07:4dc0:1ed:2c3b:b7b3:3ca3:c0ad:266f:0 Query:0.0.0.0:0 Out:0byte In:0byte Host:[0.0.0.0]
аналогично для другого адреса:
Date:31.03.2017 Time:20:44:03.723 User:kulakov Proxy:PROXY Port:2273 Error:00100 Client:91.228.155.195:30616 Server:0.0.0.0:0 Query::::443 Out:0byte In:0byte Host:www.facebook.com Chain:0 Text:CONNECT www.facebook.com:443 HTTP/1.1
Date:31.03.2017 Time:20:44:08.775 User:- Proxy:PROXY Port:2273 Error:00511 Client:91.228.155.195:30618 Server:2a07:4dc0:1ed:8df8:58f9:fece:63ff:4762:0 Query:0.0.0.0:0 Out:0byte In:0byte Host:[0.0.0.0]

они образовались, когда чекал прокси чекером https://proxy6.net/checker при большом количестве поднятых адресов. когда адресов было мало, то все обращения завершались с кодом Error:00000

**Comment by z3APA3A** [comment]
3proxy сейчас актуальный 0.8.9. Каждый запущенный прокси требует 1 сокет (файловый дискриптор), 1 поток (процесс) и порядка 32-128КБ стека. Каждый клиент требует 2 сокета, 1 поток и порядка 16-128К стека. Исходя из этого смотри какие тебе нужны ограничения на файлы, потоки и стек.

**Comment by gggrafff** [comment]
хорошо. спасибо. буду пробовать

**Comment by tomassiro** [comment]
Did you find a solution gggrafff? I am having the same problem.
