### ISSUE TITLE
почему не работает авторизация

### ISSUE THREAD

**Issue by euglv** [z3APA3A/3proxy#15]
Здравствуйте, вот такой простой конфиг:
````
service
users pro:CL:pass1 p:CL:pass2
log "D:\Programs\3proxy\log\log" D
rotate 30
auth strong 
allow pro,p
proxy 
socks
````
Но прокси сервер не принемает авторизацию. Chrome, windows server 2012 r2 - постоянно спрашивает имя пользователя/пароль. Internet Explorer после трёх вводов правильного пароля (pass1 для пользователя pro) показывает ошибку:
````
407 Proxy Authentication Required

Access to requested resource disallowed by administrator or you need valid username/password to use this resource
````

Если вместо `auth strong` написать `auth none` - прокси работает и пароль не спрашивает.
Подскажите, что я делаю не так?

**Comment by euglv** [comment]
Вот правильный конфиг:
````
service
users pro:CL:pass1 p:CL:pass2
log "D:\Programs\3proxy\log\log" D
rotate 30
auth strong
flush
allow pro,p
proxy 
socks
````
Теперь работает.

**Comment by z3APA3A** [comment]
Первый конфиг был правильным, flush в данном случае ни на что не влият. А причину, почему проходила аутентификация  лучше посмотреть по логам. Для старых версий 3proxy может потребоваться ключик -n для proxy.
