### ISSUE TITLE
Как принять лицензионное соглашение из консоли CMD?

### ISSUE THREAD

**Issue by FlipWho** [z3APA3A/3proxy#150]
Добрый день, всё никак не разберусь, что нужно дописать к строчке в батнике, чтобы автоматически принять лицензионное соглашение при установке 3proxy как сервис на Windows? Когда "висишь" на проброшенном порту при перезапуске службы порт отваливается, потому что соглашение не принято и заново не пробрасывается, пока не зайдёшь на сервер другим любым способом и не примешь это соглашение.

C:\3proxy\3proxy.exe --install C:\3proxy\3proxy.cfg

[Скриншот окна с лицензионным соглашением](http://joxi.ru/eAON5qMUNByp2o.jpg)

**Comment by z3APA3A** [comment]
Можешь сделать свою сборку 3proxy и убрать из нее запрос, это не является нарушением условий лицензии.

**Comment by FlipWho** [comment]
Честно признаться, я рукожоп... Где можно почитать об этом?

1 мая 2017 г. 6:41 PM пользователь "Vladimir Dubrovin" <
notifications@github.com> написал:
