### ISSUE TITLE
Создание нескольких прокси(ipv4)

### ISSUE THREAD

**Issue by Proxyman01** [z3APA3A/3proxy#152]
Подскажите плиз!
VPS Ubuntu 16.04.2 LTS. На нем успешно установил 3proxy 
С таким конфигом работает все на ура! Но.... Только с одним(основным) прокси! Вот работающий конфиг(3proxy.cfg):
proxy -p3128 -a -i1.1.1.1 -e1.1.1.1
users username:CL:password
allow username

Но как только дописываю вторую строку, второй прокси не работает! Что делать? 
пример не работающей конфигурации:
proxy -p3128 -a -i1.1.1.1 -e1.1.1.1
proxy -p3129 -a -i2.2.2.2 -e2.2.2.2
users username :CL:password
allow password

**Comment by z3APA3A** [comment]
allow username1
proxy -pP1 -iIP1 -eIP1
flush
allow username2
proxy -pP2 -iIP2 -eIP2

при этом IP1 и IP2 должны быть локально сконфигурирована на хосте с 3proxy.

**Comment by Proxyman01** [comment]
Чет не прет ) 
Starting 3Proxy
users: extra operand 'username2:CL:password2'
Try 'users --help' for more information.
/etc/3proxy/3proxy.cfg: 2: /etc/3proxy/3proxy.cfg: auth: not found
/etc/3proxy/3proxy.cfg: 4: /etc/3proxy/3proxy.cfg: allow: not found

**Comment by z3APA3A** [comment]
Все это писать надо в 3proxy.cfg, а не в командную строку.

**Comment by Proxyman01** [comment]
Я все так и сделал! Это после сохранения конфига и рестарта такой ответ в командной строке.

**Comment by z3APA3A** [comment]
Ну ты вместо того, тобы скормить конфиг 3proxy скармливаешь его шелу.

**Comment by Proxyman01** [comment]
sh scripts/rc.d/proxy.sh start все работало с 1 прокси с этой командой. (когда сохранял конфиг и выходил).
Сорри я нуб, делал все по какому-то мануалу с тырнета. А как скормить конфиг 3proxy?

**Comment by z3APA3A** [comment]
Если ты запускаешь 3proxy.cfg как скрипт, то убедись, что в нем первой строкой идет что-то типа
#!/usr/local/bin/3proxy
или запускай не его, а 3proxy с путем к конфигу в качестве параметра.

**Comment by Proxyman01** [comment]
#!/usr/local/bin/3proxy
users username1:CL:password1 username2:CL:password2
auth strong
allow username1
proxy -pP1 -iIP1 -eIP1
flush
allow username2
proxy -pP2 -iIP2 -eIP2

Сохраняю и ввожу в шелле  sh scripts/rc.d/proxy.sh start 
И тоже самое пишет.

**Comment by z3APA3A** [comment]
Ну я же не знаю что у тебя в proxy.sh. Наверно таки лучше со всем этим идти к автору того мануала, по которому ты все это делал.

**Comment by Proxyman01** [comment]
Спасибо! Вроде врубился! Нужно лезть в proxy.sh и менять там что-то! Автор мануала неизвестен )))

**Comment by Proxyman01** [comment]
Вобщем оказывается нужно было прописать второй ip в etc/network/interfaces. 
Спасибо за уделенное время! Все работает! 
А можно узнать как в конфиге 3proxy.cfg прописать один логин и пароль на все создаваемые прокси?

PS: Сколько прокси(ipv4) на одном vps(самый простой) рекомендовано?

**Comment by z3APA3A** [comment]
Со стороны 3proxy ограничений нет, как правило он не является узким местом, все упирается в ресурсы и ограничения vps (по памяти, сокетам/дискрипторам, процессам/потокам).
