### ISSUE TITLE
3proxy не рестартует в Windows XP

### ISSUE THREAD

**Issue by rstaganrog** [z3APA3A/3proxy#154]
В Windows XP SP3 для 3proxy-0.8.9-lite имеем такой конфиг: 

service 
log "c:\3proxy\l\3proxy.log" D 
 
auth iponly 
allow * 
deny * 
maxconn 1000 
proxy 
 
flush 
allow * 
admin 
 
 
Для воспроизведения проблемы просто входим в админку и нажимаем в ней ссылку Reload. 

Прокси начинает перезагрузку (Reload scheduled), после чего админка перестаёт отзываться, прокси перестаёт раздавать интернет (службы/процессы 3proxy в это время работают, файл лога не удаляется поскольку заблокирован работающим процессом 3proxy). 

После ручного рестарта службы админка оживает, прокси начинает раздавать интернет.

**Comment by rstaganrog** [comment]
Аналогичная проблем с таким странным рестартом возникает и в случае, если в лог прописать мониторинг изменения файла конфига с целью рестарта прокси после корректировки конфига. 

В этом случае после правки файла конфига прокси точн также работает как служба и виден как процесс в диспетчере задач, но прекращает раздавать интернет. После ручного рестарта службы раздача интернета возобновляется.

**Comment by rstaganrog** [comment]
после описанного выше "странного рестарта" последняя запись в логе:
  170506085624.480 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting thread 

После неё до ручного рестарта службы в логе ничего нет

**Comment by rstaganrog** [comment]
Перепробовал все доступные версии. Последняя версия, на которой нет проблем - 3proxy-0.8.6-lite, далее - уже работает с ошибками

**Comment by z3APA3A** [comment]
Видимо, это особенность реализации fopen в Watcom, из-за нее фейлится открытие файла журнала на перезагрузке. Попробуй
http://3proxy.ru/current/3proxy-0.9-lite-devel.zip
если поможет - включу фикс в 0.9. В 0.8 патчить не буду, т.к. особенность компилятора.

**Comment by rstaganrog** [comment]
Нет, всё по-прежнему - после вызова Reload в админке:

3proxy tiny proxy server 3proxy-0.9-devel (170508144458) configuration
Reload scheduled

после этого процесс в диспетчере задач - живой, служба - работает, но  
админка уже не доступна

админка оживает после рестарта службы



Vladimir Dubrovin <notifications@github.com> писал(а) в своём письме Mon,  
08 May 2017 14:58:03 +0300:

>
> Видимо, это особенность реализации fopen в Watcom, из-за нее фейлится  
> открытие файла журнала на перезагрузке. Попробуй
> http://3proxy.ru/current/3proxy-0.9-lite-devel.zip
> если поможет - включу фикс в 0.9. В 0.8 патчить не буду, т.к.  
> особенность компилятора.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/

**Comment by z3APA3A** [comment]
А если запустить не как службу, а просто как приложение, что-нибудь будет в консоли?

**Comment by z3APA3A** [comment]
Да, недоделал - возьми текущий devel

**Comment by rstaganrog** [comment]
Да, на версии
   3proxy-0.9-devel (170508175345)
проблема решена

Можно ли её использовать как прокси на реальной сети (около 100 машин)?
Или имеет смысл подождать релиз?

Vladimir Dubrovin <notifications@github.com> писал(а) в своём письме Mon,  
08 May 2017 17:57:05 +0300:

>
> Да, недоделал - возьми текущий devel
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/

**Comment by rstaganrog** [comment]
Как оказалось, проблема решилась частично.

После Reload в админке прокси продолжает работать.

А вот если сделать мониторинг изменения конфига - то после изменения  
конфига прокси уже не работает, хотя процесс и служба активны. Помогает  
только рестарт службы.


Vladimir Dubrovin <notifications@github.com> писал(а) в своём письме Mon,  
08 May 2017 17:57:05 +0300:

>
> Да, недоделал - возьми текущий devel
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/

**Comment by rstaganrog** [comment]
уточнение по версии
   3proxy-0.9-lite-devel-170508175345:

при мониторинге конфига - изменение конфига ИНОГДА приводит ошибке  
перезагрузки прокси (решается рестартом службы), ИНОГДА после изменения  
конфига прокси автоматически перезапускается без проблем (рестарт службы  
не нужен)

еще в этой же версии замечена странность: изменение bandlimin иногда  
приводит к реальному ограничению скорости, заданному в этом параметре, а  
иногда изменение этого параметра в конфиге как бы игнорируется - реально  
действует не новое значение, а предыдущее его значение (причём если  
смотреть значение этого параметра в админке по ссылке Cоnfig - то видно,  
что актуально не предыдущее, а уже новое значение параметра)

закономерности в проявлении этих ошибок выявить не удалось


Vladimir Dubrovin <notifications@github.com> писал(а) в своём письме Mon,  
08 May 2017 17:57:05 +0300:

>
> Да, недоделал - возьми текущий devel
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/

**Comment by z3APA3A** [comment]
Текущий devel попробуй

**Comment by rstaganrog** [comment]
Похоже, что все проблемы решились.
Спасибо! 
)

**Comment by rstaganrog** [comment]
Можно ли 3proxy-0.9-lite-devel-170512222912 использовать на реальной сети (около 100 машин)?
Или имеет смысл подождать релиз?
))

**Comment by z3APA3A** [comment]
Можно, от релиза он отличается только правками по этой проблема и кодом RADIUS-авторизации.

**Comment by rstaganrog** [comment]
Собственно, вопрос связан с этой информацией на сайте:

"Ветка 0.8 считается стабильной, разработка ведется в ветке 0.9. Ветка 0.7  
больше не поддерживается, за исключением исправлений, связанных с  
безопасностью."

Или, действительно, несмотря на текст на сайте - ветка 0.9 уже пригодна к  
эксплуатации?

Vladimir Dubrovin <notifications@github.com> писал(а) в своём письме Sat,  
13 May 2017 01:56:20 +0300:

>
> Можно, от релиза он отличается только правками по этой проблема и кодом  
> RADIUS->авторизации.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Написано с помощью почтового клиента Opera: http://www.opera.com/mail/

**Comment by z3APA3A** [comment]
0.9 еще не успела сильно уйти от 0.8, там добавлен новый функционал, в котором могут быть ошибки, но на старый функционал он не влияет.
