### ISSUE TITLE
Function "parent  extip" can't randomly choose outgoing ip when use "auth cache iponly"

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#155]
Dear 3proxy developer,
       I am using 3proxy 0.8.9 on centos 6.8 64bit, and setup proxy with "parent 100 extip" to randomly choose outgoing ip.

There is a bug on some client ip connect proxy ip when use "auth cache iponly",it always  choose the default ip of proxy server with its outgoing ip,it means the outgoing ip nerver change.

Most of clients ip are working well,the outgoing ips are randomly changing everytime.

If I use the "auth cache iponly strong" way,it also working,they also choose random outgoing ips.

Kindly regards

Rain

**Comment by z3APA3A** [comment]
parent weight must be 1000.

**Comment by raintears2** [comment]
I am sure the sum of all parent weight is  1000.

authcache ip 900
auth cache iponly strong

I use both iponly and strong. Is it right?

When use user and password,the extip are working,randomly select outgoing ip
When use iponly  for client ips,some are working,some are always use the default main ip for outgoing ip.

**Comment by z3APA3A** [comment]
send a full config (you can mask usernames/password/networks).
And I still don't understand what's a reason to use authcache in this case?

**Comment by raintears2** [comment]
There is no relation to authcache, I delete the authcache then problem still exists.
I also have sent the screenshot of test result  to your email 3proxy@3proxy.ru


nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users $/root/3proxypassword
maxconn  100
daemon

pidfile /var/run/3proxy.pid
auth iponly strong


allow * $/etc/ipsallow
allow $/etc/usersallow
parent 250 extip 1.1.1.1 0
parent 250 extip 2.2.2.2 0
parent 250 extip 3.3.3.3 0
parent 250 extip 4.4.4.4 0
allow * $/etc/ipsallow
allow $/etc/usersallow

proxy -a -n -p20001 -i192.168.1.100

**Comment by z3APA3A** [comment]
'parent' extends 'allow' and only affects last preceding 'allow' command. In your case, 'parent' will be applied to
allow $/etc/usersallow 
You must specify 'parent's after every 'allow' command, if the traffic for this rule must be redirected.
Last two 'allow' are useless.

**Comment by raintears2** [comment]
Yes,I follow you said,it's working now.

Another question:
I want both iponly and strong authentication , how to cache authentication without 15min for them?

authcache  ip,user  900
auth iponly strong

Is this right?

**Comment by z3APA3A** [comment]
authcache is not required here, browser sends authentication information with every request.  What for you want to cache authentication? To allow users from the same IP to use services without authentication within 15 minutes after logon?

**Comment by raintears2** [comment]
Yes,allow users from the same IP to use services without authentication within 15 minutes after logon.

**Comment by z3APA3A** [comment]
authcache ip 900
auth iponly cache strong
