### ISSUE TITLE
make install 0.9 devel fail on centos 6.8 64bit

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#156]
Hi,
    I want to install 3proxy devel version on Centos 6.8 64bit,the install script is below.

wget -O 3proxy-devel.zip --no-check-certificate https://github.com/z3APA3A/3proxy/archive/devel.zip
unzip 3proxy-devel.zip
cd 3proxy-devel

make -f Makefile.Linux
make -f Makefile.Linux install

The result is failed:

make -f Makefile.Linux
cat Makefile.Linux > src/Makefile.var
make[1]: Entering directory `/root/3proxy-devel/src'
make[2]: Entering directory `/root/3proxy-devel/src/plugins/StringsPlugin'
gcc -o ../../StringsPlugin.ld.so -O2 -pthread -shared StringsPlugin.o
make[2]: Leaving directory `/root/3proxy-devel/src/plugins/StringsPlugin'
make[2]: Entering directory `/root/3proxy-devel/src/plugins/TrafficPlugin'
gcc -o ../../TrafficPlugin.ld.so -O2 -pthread -shared TrafficPlugin.o
make[2]: Leaving directory `/root/3proxy-devel/src/plugins/TrafficPlugin'
make[2]: Entering directory `/root/3proxy-devel/src/plugins/PCREPlugin'
gcc -o ../../PCREPlugin.ld.so -O2 -pthread -shared pcre_compile.o pcre_config.o pcre_dfa_exec.o pcre_exec.o pcre_fullinfo.o pcre_get.o pcre_globals.o pcre_newline.o pcre_ord2utf8.o pcre_refcount.o pcre_study.o pcre_tables.o pcre_valid_utf8.o pcre_version.o pcre_xclass.o pcre_plugin.o pcre_maketables.o pcre_ucd.o pcre_table.o
make[2]: Leaving directory `/root/3proxy-devel/src/plugins/PCREPlugin'
make[2]: Entering directory `/root/3proxy-devel/src/plugins/TransparentPlugin'
gcc -o ../../TransparentPlugin.ld.so -O2 -pthread -shared transparent_plugin.o
make[2]: Leaving directory `/root/3proxy-devel/src/plugins/TransparentPlugin'
make[1]: Leaving directory `/root/3proxy-devel/src'

make -f Makefile.Linux install
/usr/bin/install -m 755 -d /usr/local/bin
/usr/bin/install -m 755 -s src/3proxy src/dighosts src/ftppr src/mycrypt src/pop3p src/proxy src/socks src/tcppm src/udppm /usr/local/bin
/usr/bin/install: cannot stat `src/dighosts': No such file or directory
make: *** [install-bin] Error 1

**Comment by z3APA3A** [comment]
should work now.
