### ISSUE TITLE
Log proxy IP

### ISSUE THREAD

**Issue by hkotanjyan** [z3APA3A/3proxy#157]
Здравствуйте 
Как добавить ip интерфейса в лог к которому подключаться пользователь ?

Пример  лог формата 
logformat "%u %U %C %n %I"
log /var/log/3proxy/access.log

Какой символ представляет IP Сервера ?

**Comment by shark136** [comment]
https://github.com/z3APA3A/3proxy/wiki/3proxy.cfgраздел logformat, там есть все команды выбирайте что вам надо.-- Новоселов Михаил

**Comment by z3APA3A** [comment]
%i

**Comment by hkotanjyan** [comment]
Да верно это маленький %i
Этого не было в доках спасибо
