### ISSUE TITLE
Segmentation fault, CentOS 6.9

### ISSUE THREAD

**Issue by jamaicada** [z3APA3A/3proxy#158]
Hello! I've got a problem with a random crashes on CentOS 6.9 32 bit.
Here comes all info I've got at the moment:
1. OS version
cat /etc/redhat-release
CentOS release 6.9 (Final)
2. Kernel 
uname -vr
2.6.32-696.1.1.el6.i686 #1 SMP Tue Apr 11 16:37:48 UTC 2017
3. 3proxy version
/opt/3proxy/3proxy -V
3proxy tiny proxy server 3proxy-0.8.9 (170202011430)
4. Dmesg log
```
3proxy[30084]: segfault at b5a10fe0 ip 00b5162e sp b5a10fc0 error 6 in libc-2.12.so[a47000+191000]
3proxy[4849]: segfault at b4fb0fe0 ip 0056362e sp b4fb0fc0 error 6 in libc-2.12.so[459000+191000]
3proxy[6114]: segfault at b4f58fe0 ip 004c062e sp b4f58fc0 error 6 in libc-2.12.so[3b6000+191000]
3proxy[29299]: segfault at b4a18fe0 ip 002c362e sp b4a18fc0 error 6 in libc-2.12.so[1b9000+191000]
3proxy[29393]: segfault at b38f0fe0 ip 002c362e sp b38f0fc0 error 6 in libc-2.12.so[1b9000+191000]
```
5. Security limits are fine
a) cat /etc/security/limits.conf | grep nofile
```
* soft nofile 1024000
* hard nofile 1024000
```
b) cat /etc/security/limits.d/90-nproc.conf
```
*          soft    nproc     100000
root       soft    nproc     unlimited
```
c) sysctl -a | grep kernel.threads-max
kernel.threads-max = 7772
d)  sysctl -a | grep fs.file-max
fs.file-max = 999999
6. Lib C version
yum info glibc
```
Installed Packages
Name        : glibc
Arch        : i686
Version     : 2.12
Release     : 1.209.el6_9.1
Size        : 13 M
Repo        : installed
From repo   : updates
```
What else I can check to prevent random segfaults?
Thanks.

**Comment by z3APA3A** [comment]
what do you have in config?

**Comment by jamaicada** [comment]
https://pastebin.com/dAqsxKN0
where exampleuser is one of 73 different users with different pass. IPs, usernames and passwords were changed.

**Comment by z3APA3A** [comment]
Try to use 'stacksize':
http://3proxy.ru/faqe.asp
in you configuration, with multiple IPs, there are race conditions issues on glibc resolver, So you can also increase nscache size to avoid resolutions and run proxy with -4 to avoid IPv6 resolutions which you do not cache. In addition, check if you have enough threads and stack memory in limits, each started proxy/socks and each connected client requires thread and almost all memory used by proxy is stack.
