### ISSUE TITLE
# bash: fork: retry: no child processes 

### ISSUE THREAD

**Issue by flyrider** [z3APA3A/3proxy#159]
При нагрузке 3proxy большим кол-вом потоков (100-1000). Возникает ошибка:
# bash: fork: retry: no child processes 

Проксирование перестает работать.
~$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 3838
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 999999
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 999999
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

~$ sysctl -p
net.ipv4.tcp_keepalive_time = 300
net.ipv4.tcp_keepalive_intvl = 30
net.netfilter.nf_conntrack_generic_timeout = 500
net.netfilter.nf_conntrack_tcp_timeout_established = 200000
net.netfilter.nf_conntrack_max = 10048576
net.netfilter.nf_conntrack_max = 10048576
fs.file-max = 999999
sysctl: setting key "fs.file-nr"
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 5
net.ipv4.conf.default.rp_filter = 1
vm.swappiness = 10
vm.vfs_cache_pressure = 50
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
net.ipv4.tcp_window_scaling = 0
net.ipv4.ip_default_ttl = 128
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_rmem = 4096 87380 4194304
net.ipv4.tcp_wmem = 4096 87380 4194304
net.core.somaxconn = 6000
net.ipv4.tcp_max_tw_buckets = 1440000
net.ipv4.ip_local_port_range = 1024 65023
net.ipv4.tcp_fin_timeout = 30
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
sysctl: cannot stat /proc/sys/net/ipv4/netfilter/ip_conntrack_max: Нет такого файла или каталога
net.core.netdev_max_backlog = 10000
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 3
net.ipv4.tcp_max_syn_backlog = 2048
net.ipv4.tcp_synack_retries = 3
net.ipv4.tcp_syncookies = 1
net.ipv4.conf.all.rp_filter = 1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_max_orphans = 262144
~$

**Comment by z3APA3A** [comment]
Где эта ошибка возникает и как связаны bash и 3proxy?

**Comment by flyrider** [comment]
bash я думаю никак не связан. Через какое-то время после запуска большого кол-ва потоков, возникает проблема, что не возможно выполнить ни одну команду. При этом память пустая

**Comment by z3APA3A** [comment]
Каждая запущенная служба и подключенный клиент требуют
1 поток (процесс)
2 сокета (файловых дескриптора)
некое количество памяти, порядка от 64К до 256К (зависит от stacksize и системы), примерно поровную heap и stack.
ищи в какие ресурсы ты упираешься. Если у тебя VPS, вполне может быть, что количество процессов ограничено хостером.
