### ISSUE TITLE
proxy and socks listen error no output

### ISSUE THREAD

**Issue by hz86** [z3APA3A/3proxy#160]
3proxy-0.8.9
proxy and socks listen error no output

src/socks.c
line:284        case 2:
line:285            so._listen (param->remsock, 1);

**Comment by z3APA3A** [comment]
Does it lead to any negative results? If listen() fails, error will be generated on poll(), line 290.

**Comment by hz86** [comment]
my system is win
port occupied no error output
want to output errors to help find the problem
