### ISSUE TITLE
Docker : connections not accessible on host if not using --net=host

### ISSUE THREAD

**Issue by trompx** [z3APA3A/3proxy#161]
Hello,

First thanks for sharing the excellent 3proxy!
I have an issue when trying to setup multiple proxies on one server.

If I start 3proxy with `proxy -p3128` the proxy works. But when I add multiple ips like:
```
proxy -n -a -ix.x.x.x -ex.x.x.x -p3128
proxy -n -a -iy.y.y.y -ey.y.y.y -p3128
```
it fails.

I struggled a bit but then I found out with `netstat -tulnp | grep LISTEN` that the connections created by 3proxy where not forwarded to the host so I had:

```
tcp6       0      0 :::80                   :::*                    LISTEN      5405/docker-proxy
tcp6       0      0 :::3128                 :::*                    LISTEN      29606/docker-proxy
```

I stumble upon this issue on docker https://github.com/moby/moby/issues/13914 saying that the port should be correctly exposed if defined in the Dockerfile and when running the container with -p which I did.
I start my container on a private network with a specific ip with `--net={{ mydocker_network }} --ip={{ my_container_ip }}` so it should work but it does not.

I remember using squid with multiple ips without the --net=host flag so maybe you have an idea about what could prevent the connection being passed to the host?

If I use --net=host
```
tcp        0      0 x.x.x.x:3128        0.0.0.0:*                   LISTEN      30779/3proxy
tcp6       0      0 :::80                   :::*                    LISTEN      5405/docker-proxy
```
 it works but I would really like not to use it especially if I want to open some proxy to the outside.

Thanks in advance

**Comment by z3APA3A** [comment]
I neither work with docker not maintain 3proxy docker, you better ask on some docker related resource. At least, you should check the log files: if 3proxy is unable to bind to specified file, the problem is in interface configuration inside the docker. If 3proxy starts, but you are unable to connect - the problem may be related to NAT configuration as an discussion in the article you are referring to suggests.
