### ISSUE TITLE
Нет переключения на работащий IPv4 адрес (протокол)

### ISSUE THREAD

**Issue by click0** [z3APA3A/3proxy#162]
Здравствуйте.
3proxy-0.8.7 (160904162014)
FreeBSD 11.0-STABLE #0 r309276: Tue Nov 29 13:33:29 EET 2016

При добавлении нового инстанса в работающий конфиг 3proxy:
`proxy -64 -n -a -p1331 -e{$ipv6} -e{ipv4}`

Не проходит тест Fallback у сервиса http://ipv6-test.com/
В описании теста:
`Whether or not your browser falls back to the other protocol if its default above does not work`

Полный конфиг 3proxy

> daemon
> pidfile /var/run/3proxy.pid
> nscache 65536
> nserver 127.0.0.1
> config /usr/local/etc/3proxy.cfg
> monitor /usr/local/etc/3proxy.cfg
> rotate 60
> users userbla-bla-bla ...
> maxconn 512
> auth strong
> deny * * 127.0.0.1
> allow *
> flush
> allow userbla-bla-bla 
> socks -p1326
> proxy -p1327
> socks -6 -n -a -p1328 -e{ipv6}
> proxy -6 -n -a -p1329 -e{ipv6}
> socks -64 -n -a -p1330 -e{ipv6} -e{ipv4}
> proxy -64 -n -a -p1331 -e{ipv6} -e{ipv4}

**Comment by z3APA3A** [comment]
Да, прокси не перебирает IP-адреса, если имя разрешается в несколько адресов и часть из них испытывают проблемы с подключением. Добавлять такой фунционал пока не планируется.
