### ISSUE TITLE
Ошибка при сборке Centos 7

### ISSUE THREAD

**Issue by aroun** [z3APA3A/3proxy#163]
Пытаюсь собрать 3proxy в Centos 7 x64

```
yum update -y
yum install nano mc net-tools
yum install epel-release -y
yum update -y
yum update && yum -y install wget gcc mc net-tools nano
cd /usr/src
wget https://3proxy.ru/current/3proxy-0.9-devel.tgz
tar -xvzf 3proxy-0.9-devel.tgz
Перед компиляцией используя nano добавим одну строчку в @src/proxy.h@, чтобы сервер был анонимным
@#define ANONYMOUS 1@
```

```
ln -s /usr/lib64/libcrypto.so.10 /usr/lib/libcrypto.so
ln -s /usr/lib64/libssl.so.10 /usr/lib/libssl.so
make -f Makefile.Linux
```

```
make -f Makefile.Linux
cat Makefile.Linux > src/Makefile.var
make[1]: Entering directory `/usr/src/3proxy/src'
gcc -o 3proxy -O2 -pthread   3proxy.o mainfunc.o auth.o authradius.o conf.o datatypes.o srvproxy.o srvpop3p.o srvsmtpp.o srvftppr.o srvsocks.o srvtcppm.o srvicqpr.o srvudppm.o sockmap.o sockgetchar.o myalloc.o common.o mycrypt.o md5.o md4.o base64.o ftp.o smbdes.o ntlm.o stringtable.o srvwebadmin.o srvdnspr.o plugins.o  -ldl
conf.o: In function `h_radius':
/usr/src/3proxy/src/conf.c:1286: undefined reference to `closesocket'
collect2: error: ld returned 1 exit status
make[1]: *** [3proxy] Error 1
make[1]: Leaving directory `/usr/src/3proxy/src'
make: *** [all] Error 2

```
В этой строчке вот такой код:

```
        for(; oldrad; oldrad--){
                if(radiuslist[oldrad].logsock >= 0)closesocket(radiuslist[oldrad].logsock);
                radiuslist[oldrad].logsock = -1;
        }
```

Если его заккоментить - то все ок.

**Comment by aroun** [comment]
bash -x /etc/init.d/3proxy
+ $'\r'
/etc/init.d/3proxy: line 9: $'\r': command not found
/etc/init.d/3proxy: line 10: syntax error near unexpected token `$'in\r''
'etc/init.d/3proxy: line 10: `case "$1" in

**Comment by aroun** [comment]
Скопировал 

`cat /scripts/rc.d.proxy.sh > /etc/init.d/3proxy`

Начался вообще трэш:

```
/etc/init.d/3proxy
bash: /etc/init.d/3proxy: /bin/sh^M: bad interpreter: No such file or directory
```
Помогло пересохранить скрипт в vi

`:set fileformat=unix`
И потом сохранить
`:wq!`

Странно что он в исходниках в таком формате сохранен...(

**Comment by aroun** [comment]
Скрипт 3proxy-linux-install.sh был неплохой задумкой, но он явно заточен на debian-подобные ОС, он мне на centos 7 пытается apt-get выполнить, выглядит как-то заумно, вываливается с ошибкой, 

```
Package "build-essential" was not installed.
The installation can not be continued!
+ exit 255
```

**Comment by aroun** [comment]
Может вам нужна помощь в написании этих скриптов?

**Comment by aroun** [comment]
В /scripts/3proxy.cfg скорее всего в директиве log ошибка:

```
cat ../../3proxy/scripts/3proxy.cfg | grep log
log /usr/local/etc/3proxy/log/log D
```
Судя по типичным примерам установки, например по этому - https://3proxy.ru/doc/ru/example1.txt каталог должен быть все-таки logs а не log

**Comment by z3APA3A** [comment]
> /usr/src/3proxy/src/conf.c:1286: undefined reference to `closesocket'
было вчера поправлено этим коммитом:
https://github.com/z3APA3A/3proxy/commit/305f01acb56ca688f070b402bc3c4caa9e13601c

> bash: /etc/init.d/3proxy: /bin/sh^M: bad interpreter: No such file or directory
git игнорирует изменения связанные с терминаторами строк, попробовал передобавить файлы, возможно это поможет.

> Может вам нужна помощь в написании этих скриптов?
Если сделаешь аналогичные скрипты для RH-based дистрибутивов - будет замечательно.

> log /usr/local/etc/3proxy/log/log D
поправил
