### ISSUE TITLE
ftpproxy passive mode fails with connect from internal server to proxy.

### ISSUE THREAD

**Issue by jhaprins** [z3APA3A/3proxy#164]
[ftppcap.zip](https://github.com/z3APA3A/3proxy/files/1106115/ftppcap.zip)

I'm trying to setup a ftp proxy to allow systems on an internal IPv6 only network to do ftp transfers from servers in the outside world. When they connect to the outside world using ftppr, the first part of the connection works just fine, but when the server sends back a passive mode with a port the internal system tries to setup a connection to this port on the proxyserver buth the proxyserver does not have this port open. 

Attached is a packet capture and the failed connection setup can be found in packet number 48/49
3proxy version 0.8.10.

Config file:

nscache 65536
timeouts 1 5 30 60 180 1800 15 60
daemon
log /var/log/3proxy/3proxy.log
logformat "L%d-%m-%Y %H:%M:%S %z %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /bin/gzip %F
rotate 30
auth iponly
internal 2a02:b70:0:14:0:0:3128:1
auth none
ftppr

**Comment by z3APA3A** [comment]
Are you sure ftp client is IPv6 compatible? FTP does not support IPv6 natively and server replies with faked address. Client should ignore this address and only use port number from server's reply. Can you provide e.g. traffic dump between server and client?

**Comment by jhaprins** [comment]
I already attached a pcap file to the case.
It's zipped, just unpack it and open in wireshark.
The IPv6 traffic in the packet capture is between client and proxy.
The IPv4 traffic in the packet capture is between proxy and ftp server.

Jan Hugo Prins

**Comment by z3APA3A** [comment]
Thanks, i didn't notices.

**Comment by z3APA3A** [comment]
The problem here is cient issues command EPSV 2, which is not currently supported by 3proxy.

**Comment by z3APA3A** [comment]
Try latest devel with this patch:
https://github.com/z3APA3A/3proxy/commit/481b9e389f1ff91187c35fdb787d04388658c850

**Comment by jhaprins** [comment]
[ftp2_pcap.zip](https://github.com/z3APA3A/3proxy/files/1106976/ftp2_pcap.zip)

Hi, I have tried the devel version with this patch and the result is not that good.
What I see is that the ftp process freezes and starts sending retransmits after the client has send the EPSV 2 command. 

Attached is the pcap file for my test run.

Jan Hugo Prins

**Comment by z3APA3A** [comment]
Try the last fix. It's probably some firewall's reaction on 227 code instead of 229, I've changed the code.

**Comment by jhaprins** [comment]
This new fix does the trick, and we have it now up and running. Thanks a lot.
