### ISSUE TITLE
Question Unique auth for each proxy

### ISSUE THREAD

**Issue by jameskkv** [z3APA3A/3proxy#166]
How can i create a unique username:password auth for each created proxy, if a server has more than 1 proxy?

I have created all with the same username pass, now i am figuring out how to create each proxy with it's own auth.

Edit: This is also because i need to create it under ipv6 via ipv4.

**Comment by z3APA3A** [comment]
users user1:CL:pass1 user2:CL:pass2 ...

allow user1
proxy -p1
flush
allow user2
proxy -p2
flush
allow user3
proxy -p3
...
