### ISSUE TITLE
socks proxy sends DNS queries to interface other than specified in "external" setting

### ISSUE THREAD

**Issue by bryx666** [z3APA3A/3proxy#17]
I have a standard notebook running Windows 7 x64. I am connected to a closed network via the wired adapter and to the Internet via the wireless adapter. wired is set as the preferred adapter and has the highest routing priority. There is a DNS server on this closed network for internal hosts and it does not resolve any external names.

I am hoping to setup 3proxy to bind to the wireless interface and allow a browser to connect to the public Internet through it, while all the other programs keep on happily using the wired adapter. This is my configuration, cut down to the bare minimum:

              nserver 8.8.8.8
              nserver 8.8.4.4
              nscache 65536

              external 192.168.0.50
              internal 127.0.0.1

              socks

What did I expect from this? That the proxy only accept connections from my own PC, that it did DNS lookups by itself using Google DNS (not rely on Windows DNS client) and serve all requests by using the wireless interface.

Sadly, it did not work.

Using a network monitor, I can see that the proxy is creating a DNS query properly and sending that query to the configured DNS server, but it attempts to do this through the default interface which will never be able to route to it. No DNS response, timeout, "no page for you"!

If I try to access an IP address directly, it seems that this traffic is indeed sent to the "external" interface, it appears the issue is just with the DNS queries.

I am not sure if this is a bug or what I want is a new feature or I am just wrong, I do hope this is the correct place to mention it and hope it can be fixed/incorporated. Thank you very much.

**Comment by z3APA3A** [comment]
DNS server can be in either internal or external network, so 3proxy does not use this setting for DNS resolution. Just add a route for DNS server via preferred network, e.g.
route add -p 8.8.8.8 192.168.0.1

**Comment by bryx666** [comment]
Hi, thanks for the quick response.

Adding a static route would do the trick, yes, but since that is system-wide it requires admin privileges which people running on organization managed computers normally don't have (me!). Running the proxy does not require admin so it would, in my humble opinion, be a more appropriate place to have it.

Maybe an option or switch?

**Comment by z3APA3A** [comment]
I can't say it's quite common system configuration you have no valid route for DNS resolver. As a workaround, you can set
nserver 127.0.0.1
udppm -s 53 8.8.8.8 53
In 0.8 you can use port different from 53 , e.g.
nserver 127.0.0.1:5353
udppm -s 5353 8.8.8.8 53
