### ISSUE TITLE
More than 1000 parents

### ISSUE THREAD

**Issue by israelidanny** [z3APA3A/3proxy#171]
Is it possible to utilize more than 1000 parent proxies?

Currently I am making a list of 1000 parent proxies and giving each a weight of 1. What if I want to utilize more than 1000?

**Comment by z3APA3A** [comment]
You can make a cascade proxy, randomly choosing first parent and second parent.

**Comment by israelidanny** [comment]
What do you mean by a cascade proxy? Can you elaborate just a tiny bit, what would the approach be config-wise?

**Comment by z3APA3A** [comment]
If you need 10000 random parents, make 10 proxies with 1000 parents and choose one of this proxies randomly.

**Comment by israelidanny** [comment]
I see. Would an 11-th proxy that uses those 10 as parents (forwards locally?) work if I configure it? My intention is to abstract the parent proxy choosing completely.

**Comment by z3APA3A** [comment]
Why not?
But actually I don't understand design like this, if you have >1000 proxies you definitely use the scripting on the client side, why not you make a proxy choosing on the client site, cause it solves all your problems?

**Comment by israelidanny** [comment]
My calls are being performed from various IP's that are out of my control (cloud lambda functions), while the thousands of proxies are all allowing only one IP. Therefore, the purpose of my 3proxy configuration is to allow a certain IP range to access those proxies randomly rather than one designated IP.

**Comment by israelidanny** [comment]
Alright, so I did something like this:
```
allow *
parent 200 socks5+ 163.172.186.22 10135 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.152.122 10093 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.183.46 10150 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.189.233 10050 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.155.236 10007 SOME_USER SOME_PASS
proxy -n -p33120 -a
flush

allow *
parent 200 socks5+ 163.172.186.190 10144 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.184.161 10004 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.188.114 10226 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.155.236 10177 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.184.24 10009 SOME_USER SOME_PASS
proxy -n -p33121 -a
flush

allow *
parent 200 socks5+ 163.172.183.46 10064 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.170.83 10198 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.169.211 10157 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.184.46 10205 SOME_USER SOME_PASS
parent 200 socks5+ 163.172.186.190 10119 SOME_USER SOME_PASS
proxy -n -p33122 -a
flush

allow *
parent 500 socks5 127.0.0.1 33120
parent 250 socks5 127.0.0.1 33121
parent 250 socks5 127.0.0.1 33122
proxy -n -p3128 -a
```

If I connect to either port `33120`, `33121` or `33122` it works perfectly, but connecting to port `3128` leaves me with the following errors in the log:
```
1499920255.141 PROXY.3128 00052 - 84.229.51.192:61997 127.0.0.1:33120 0 0 1 GET http://REDACTED_URL/test.php HTTP/1.1
1499920255.141 PROXY.33120 00511 - 127.0.0.1:59554 0.0.0.0:0 0 0 0 ^E^A
```

**Comment by z3APA3A** [comment]
it's because you you have http 'proxy' on the port 33120+, but in 'parent' you configured these ports as socks5.
parent 500 socks5 127.0.0.1 33120

**Comment by israelidanny** [comment]
*facepalm* .. Yup, you're right. It all worked once I changed to the `socks` command.
