### ISSUE TITLE
external 0.0.0.0

### ISSUE THREAD

**Issue by AntonOrnatskyi** [z3APA3A/3proxy#172]
Добрый день, а описанное в документации значение 0.0.0.0 для внешнего IP - должно работать в 0.8? У меня сваливается парсинг конфига на этой строчке, да и судя по коду - scanaddr пересчитывает его в 0, который далее поднимается по коду до
res = getip46(46, argv[1], (struct sockaddr *)&conf.extsa);
if(!res) return 1;
в h_external

Не может ли там быть неточности в районе возврата из getip46
return (((struct sockaddr_in *)sa)->sin_addr.s_addr = getip(name))? AF_INET:0;

Или я недоразобрался?

**Comment by z3APA3A** [comment]
lite-версия используется?

**Comment by AntonOrnatskyi** [comment]
Форкал мастер ветку несколько недель тому. Компилю msvc из 15 студии, под WIN32. Использую 3proxy, не отдельно proxy модуль. По поводу Lite версии пошел rtfm делать сильно. Не помню чем отличается.

**Comment by z3APA3A** [comment]
Эта проблема возникает только при использовании /D NOIPV6.
пофиксил в 6010190940772c84b38acacab09c7372eb1a8155.
