### ISSUE TITLE
Odd networking problem (only when using strong auth)

### ISSUE THREAD

**Issue by israelidanny** [z3APA3A/3proxy#174]
So, I managed to *almost* resolve my issues. 

The proxy setup now works perfectly and successfully but *only* when I access it from the local shell like this:
`curl -v --socks5 127.0.0.1:3128 -L SOME_URL`

Log output:
```
1500795283.319 SOCKS.33120 00000 - 0.0.0.0:33120 0.0.0.0:0 0 0 0 Accepting connections [20767/3742578432]
1500795283.334 SOCKS.33121 00000 - 0.0.0.0:33121 0.0.0.0:0 0 0 0 Accepting connections [20767/3742545664]
1500795283.344 SOCKS.33122 00000 - 0.0.0.0:33122 0.0.0.0:0 0 0 0 Accepting connections [20767/3742512896]
1500795283.353 SOCKS.33123 00000 - 0.0.0.0:33123 0.0.0.0:0 0 0 0 Accepting connections [20767/3742480128]
1500795283.363 SOCKS.33124 00000 - 0.0.0.0:33124 0.0.0.0:0 0 0 0 Accepting connections [20767/3742447360]
1500795283.370 SOCKS.33125 00000 - 0.0.0.0:33125 0.0.0.0:0 0 0 0 Accepting connections [20767/3742414592]
1500795283.380 SOCKS.33126 00000 - 0.0.0.0:33126 0.0.0.0:0 0 0 0 Accepting connections [20767/3742381824]
1500795283.381 SOCKS.3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting connections [20767/3742349056]
1500795293.585 SOCK5.3128 00000 - 127.0.0.1:37806 127.0.0.1:33124 88 1286 1 CONNECT 188.226.238.176:80
1500795293.594 SOCK5.33124 00000 - 127.0.0.1:47250 163.172.186.22:10239 88 1286 1 CONNECT 188.226.238.176:80
```

However, if I try to access it from the outside via strong auth, or even locally, but using strong auth, like so:
`curl -v --proxy-user ofirseo:somepass --socks5 127.0.0.1:3128 -L SOME_URL`

It manages to connect to the 3128 proxy, but doesn't connect to parent proxies. Instead, I access the URL requested with the IP of the 3128 child proxy. This happens instantly with no delay. 

Here are logs for this kind of connection constellation:
```
1500795612.436 SOCKS.33120 00000 - 0.0.0.0:33120 0.0.0.0:0 0 0 0 Accepting connections [20899/4098197248]
1500795612.443 SOCKS.33121 00000 - 0.0.0.0:33121 0.0.0.0:0 0 0 0 Accepting connections [20899/4098164480]
1500795612.451 SOCKS.33122 00000 - 0.0.0.0:33122 0.0.0.0:0 0 0 0 Accepting connections [20899/4098131712]
1500795612.458 SOCKS.33123 00000 - 0.0.0.0:33123 0.0.0.0:0 0 0 0 Accepting connections [20899/4098098944]
1500795612.464 SOCKS.33124 00000 - 0.0.0.0:33124 0.0.0.0:0 0 0 0 Accepting connections [20899/4098066176]
1500795612.470 SOCKS.33125 00000 - 0.0.0.0:33125 0.0.0.0:0 0 0 0 Accepting connections [20899/4098033408]
1500795612.477 SOCKS.33126 00000 - 0.0.0.0:33126 0.0.0.0:0 0 0 0 Accepting connections [20899/4098000640]
1500795612.477 SOCKS.3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting connections [20899/4097967872]
1500795617.755 SOCK5.3128 00000 ofirseo 127.0.0.1:37814 188.226.238.176:80 88 1262 0 CONNECT 188.226.238.176:80
1500795830.401 SOCKS.3128 00401 - 110.249.208.157:27948 0.0.0.0:0 0 0 0 UNKNOWN 0.0.0.0:0
1500795866.717 SOCKS.3128 00401 - 110.249.208.157:18446 0.0.0.0:0 0 0 0 UNKNOWN 0.0.0.0:0
```
It looks like the connection happened successfully, but in reality - I never got anything from the parent... and weirdly enough - a few minutes(!) later (look at the timestamp: 1500795830.401) it shows a 00401 failure in the logs (way after the client received a response from the proxy).

Here is the config:
```
fakeresolve
log /var/log/3proxy.log D
logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
users ofirseo:CL:somepass

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33120 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33121 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33122 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33123 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33124 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33125 -a 
flush

auth iponly
allow *
# 1000 parents here with weight of 1
socks -n -p33126 -a 
flush

auth strong iponly
allow ofirseo
allow * 127.0.0.1
parent 136 socks5+ 127.0.0.1 33120
parent 136 socks5+ 127.0.0.1 33121
parent 136 socks5+ 127.0.0.1 33122
parent 136 socks5+ 127.0.0.1 33123
parent 136 socks5+ 127.0.0.1 33124
parent 136 socks5+ 127.0.0.1 33125
parent 184 socks5+ 127.0.0.1 33126
socks -n -p3128 -a 
```

**Comment by z3APA3A** [comment]
1. if you want to use 
auth strong iponly
you should place IP-based rules prior to user-based.
2. "parent" only extends last "allow" command. In you configuration this block

> allow * 127.0.0.1
> parent 136 socks5+ 127.0.0.1 33120
> parent 136 socks5+ 127.0.0.1 33121
> parent 136 socks5+ 127.0.0.1 33122
> parent 136 socks5+ 127.0.0.1 33123
> parent 136 socks5+ 127.0.0.1 33124
> parent 136 socks5+ 127.0.0.1 33125
> parent 184 socks5+ 127.0.0.1 33126

will never work and

> allow ofirseo

does not have parents.

**Comment by israelidanny** [comment]
So, just as a clarification - I need to restate the allow rules before every single parent?

Do I need to flush in between? Or do I only flush after the `socks` command?

**Comment by israelidanny** [comment]
I made all the adjustments you suggested (allow before every parent), and it still doesn't work.

Again it works when accessing it as 127.0.0.1, but won't work when accessing it from outside or by external IP or by strong auth.

The behavior is 100% the same. It seems like some sort of bug.  How does it make sense that one config works when accessed via 127.0.0.1 but fails to connect to any parent when connecting as strong auth / outside IP.

**Comment by z3APA3A** [comment]
NO.
you need parents after every allow. 'allow' specifies allowed traffic pattern, 'parent' extends 'allow' to redirect allowed traffic. Traffic will follow first matching 'allow'+'parent's rule

**Comment by israelidanny** [comment]
Thank you for your patience, and help - and forgive me again for being slow to understand the way this config works.

If I have 5 different parents, each with a weight of 200, do I put an "allow"  statement before *each* parent? Or before the list of parents that together comprise the 1000 total weight?

**Comment by z3APA3A** [comment]
in last example 4 parents extend 
"allow * * * 80"
command to create 3-hops proxy chain (weight is 3000) for traffic with destination to TCP 80.
in this configuration
```

allow user
allow * * * 80
parent 1000 socks5 192.168.10.1 1080
parent 1000 connect 192.168.20.1 3128
parent 300 socks4 192.168.30.1 1080
parent 700 socks5 192.168.40.1 108
```
traffic for user 'user' is not redirected. To have same redictions for both allow rules one have to configure something like

```
allow user
parent 1000 socks5 192.168.10.1 1080
parent 1000 connect 192.168.20.1 3128
parent 300 socks4 192.168.30.1 1080
parent 700 socks5 192.168.40.1 108
allow * * * 80
parent 1000 socks5 192.168.10.1 1080
parent 1000 connect 192.168.20.1 3128
parent 300 socks4 192.168.30.1 1080
parent 700 socks5 192.168.40.1 108

```

**Comment by israelidanny** [comment]
I think I finally got it to work, thank you so much!
