### ISSUE TITLE
Can a HTTP proxy connect to SOCKS parent proxies?

### ISSUE THREAD

**Issue by israelidanny** [z3APA3A/3proxy#175]
I have another question, I have multiple SOCKS parents, and one of my coworkers wants to connect to them, but he can only utilize an HTTP proxy.

If I have something like this:
```
auth strong
allow ofirseo
parent 110 socks5 127.0.0.1 33120
parent 110 socks5 127.0.0.1 33121
parent 110 socks5 127.0.0.1 33122
parent 110 socks5 127.0.0.1 33123
parent 110 socks5 127.0.0.1 33124
parent 110 socks5 127.0.0.1 33125
parent 110 socks5 127.0.0.1 33126
parent 110 socks5 127.0.0.1 33127
parent 120 socks5 127.0.0.1 33128
proxy -n -p3128 -a
flush
```

Right now it fails with the following corresponding log:
```
1500992432.322 SOCKS.33120 00000 - 0.0.0.0:33120 0.0.0.0:0 0 0 0 Accepting connections [7802/2442520320]
1500992432.327 SOCKS.33121 00000 - 0.0.0.0:33121 0.0.0.0:0 0 0 0 Accepting connections [7802/2442487552]
1500992432.333 SOCKS.33122 00000 - 0.0.0.0:33122 0.0.0.0:0 0 0 0 Accepting connections [7802/2442454784]
1500992432.338 SOCKS.33123 00000 - 0.0.0.0:33123 0.0.0.0:0 0 0 0 Accepting connections [7802/2442422016]
1500992432.345 SOCKS.33124 00000 - 0.0.0.0:33124 0.0.0.0:0 0 0 0 Accepting connections [7802/2442389248]
1500992432.351 SOCKS.33125 00000 - 0.0.0.0:33125 0.0.0.0:0 0 0 0 Accepting connections [7802/2442356480]
1500992432.358 SOCKS.33126 00000 - 0.0.0.0:33126 0.0.0.0:0 0 0 0 Accepting connections [7802/2442323712]
1500992432.364 SOCKS.33127 00000 - 0.0.0.0:33127 0.0.0.0:0 0 0 0 Accepting connections [7802/2442290944]
1500992432.370 SOCKS.33128 00000 - 0.0.0.0:33128 0.0.0.0:0 0 0 0 Accepting connections [7802/2442258176]
1500992432.370 SOCKS.1080 00000 - 0.0.0.0:1080 0.0.0.0:0 0 0 0 Accepting connections [7802/2442225408]
1500992432.371 PROXY.3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting connections [7802/2442192640]
1500992442.335 PROXY.3128 00064 ofirseo 212.252.119.167:33562 127.0.0.1:33127 0 22 1 GET http://vpnmanager.hopy.com/t.php HTTP/1.1
1500992442.336 SOCK5.33127 00063 - 127.0.0.1:50458 163.172.143.58:10108 0 22 1 CONNECT 127.0.0.2:80
1500992458.607 PROXY.3128 00064 ofirseo 212.252.119.167:34173 127.0.0.1:33122 0 22 1 GET http://vpnmanager.hopy.com/t.php HTTP/1.1
1500992458.607 SOCK5.33122 00063 - 127.0.0.1:58739 163.172.183.46:10272 0 22 1 CONNECT 127.0.0.2:80
1500992459.398 PROXY.3128 00064 ofirseo 212.252.119.167:33680 127.0.0.1:33120 0 22 1 GET http://vpnmanager.hopy.com/t.php HTTP/1.1
1500992459.398 SOCK5.33120 00063 - 127.0.0.1:40798 163.172.183.46:10174 0 22 1 CONNECT 127.0.0.2:80
```

As a simple test, I had the exact same setup, but with a `socks` proxy, and it works perfectly. Is what I'm trying to do even possible? Can I forward HTTP proxy traffic to a SOCKS proxy?

**Comment by z3APA3A** [comment]
If you use 'fakeresolve' you should either make sure all proxies, including external, are configured as proxy/socks5+/socks4+/connect+ to allow name resolution via parent, or you should configure your client to use 3proxy as "connect" type proxy and pass IP address instead of URI, otherwise proxy can not resolve target hostname.

**Comment by israelidanny** [comment]
Adjusted all the parents to be `socks5+`, still same exact behavior. Any other possible reasons?

**Comment by z3APA3A** [comment]
The reason is still same. Are you sure cascade proxies are also configured as socks5+ and target proxies support name resolution? What do you have in logs in this case?

**Comment by israelidanny** [comment]
It's probably the target proxies that are the fault, thanks! 

You're really great at supporting this codebase. But perhaps I could suggest to write down every single error code's meaning rather than "50-69 = SOCKS5 errors"?

In my case, if I knew the meaning of the error code, I'd bug you way less for specific implementation details :)

**Comment by z3APA3A** [comment]
Switch all proxies back to socks5 and configure name resolution instead of fakeresolve. For http 'proxy' name resolution is required, because client sends URI and doesn't send IP address in request.

There are few situations you can add something useful to error code, but in most cases it simply means you expected some data from the client or server without any success. Is there any actual difference for you between "server issued wrong reply code" and "server closed connection unexpectedly"?
