### ISSUE TITLE
Нестабильная работа

### ISSUE THREAD

**Issue by Austrian** [z3APA3A/3proxy#176]
ОС Centos 7. Конфиг:

pidfile /usr/local/etc/3proxy/3proxy.pid
daemon
log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
setgid 65535
setuid 65535
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users a1:CL:p1
users a2:CL:p2

auth strong
flush
allow a1
socks -6 -n -a -eYYYY:YYYY:YYYY:Y::Y
proxy -6 -n -a -eYYYY:YYYY:YYYY:Y::Y

И http через браузер, и сокс через curl работают отлично. Но если добавить к конфигу еще один блок с пользователем: 

auth strong
flush
allow a2
socks -6 -n -a -eXXXX:XXXX:XXXX:X::X
proxy -6 -n -a -eXXXX:XXXX:XXXX:X::X

То работа становится нестабильной: в браузерах постоянно запрашивается логин и пароль, а сокс через curl грузит раз в несколько попыток. Подскажите пожалуйста, в чем может быть проблема. Спасибо!

**Comment by z3APA3A** [comment]
daemon надо давать до pidfile
для IPv6 надо не nscache а nscache6 + в любом случае желательно nserver
а что не работает можно понять только по конкретному конфигу с видимыми портами и хотя бы не полностью маскированными IP и соответствующему фрагменту лога, жалетально в стандартном формате.

**Comment by Austrian** [comment]
Для каждого блока с пользователем необходимо выделить отдельный порт?

**Comment by z3APA3A** [comment]
При такой конфигурации, когда на каждого пользователя запускается отдельная служба - да. Можно сделать так:
```
...
allow user1
parent 1000 extip1 0
allow user2
parent 1000 extip2 0
allow user3
parent 1000 extip3 0
proxy
socks
...
```
