### ISSUE TITLE
Не работает nobandlimin

### ISSUE THREAD

**Issue by avilios** [z3APA3A/3proxy#177]
Добрый день. Очень понравился ваш прокси. Использую для урезания скорости. Но не пойму почему не работает nobandlimin. Хочу чтобы для всех пользователей был белый список сайтов для которых резак бы не срабатывал. Для примера сайт eset.com. Но исключение не срабатывает. Помогите, кто знает!!

Версия 0.8.10 . В качестве ОС Windows Server 2008 R2

auth iponly
log C:\3proxy\logs\3proxy.log D
rotate 30
proxy
internal 192.168.1.254
external 192.168.1.215
nobandlimin * * eset.com
bandlimin 524288 * 192.168.1.2

**Comment by z3APA3A** [comment]
Скорей всего, содержимое тянется не с eset.com а с другого домена, проверьте по логам. Можно использовать *.eset.com

**Comment by avilios** [comment]
Спасибо большое! Работает ... если будут вопросы - напишу!
