### ISSUE TITLE
HTTPS proxy or proxy for HTTPS:// pages?

### ISSUE THREAD

**Issue by olloff** [z3APA3A/3proxy#178]
@z3APA3A Can you, please, help me with you expert opinion about your awesome proxy? This concerns https://github.com/FelisCatus/SwitchyOmega/issues/1144#issuecomment-320848184
As far as I can understand, I may have a wrong setup [(3proxy.cfg on a linux VDS)](https://github.com/z3APA3A/3proxy/files/1206990/3proxy.cfg.txt): 

- I use single instance of 3proxy for bot HTTP and HTTPS proxy;
- when I configure named extension to use this instance of 3proxy as HTTPS proxy for https:// protocol all https-pages are loading with ERR_PROXY_CONNECTION_FAILED;
- when I configure it to use this instance of 3proxy as HTTP proxy for https:// protocol all https-pages are loading correctly.

As a disclaimer, I'm not really can tell difference between HTTPS/secure proxy and HTTP proxy with https:// support.   
Can you tell where my mistake is? Does HTTPS proxy mean i need to use separate instance of 3proxy of specific configuration?

**Comment by z3APA3A** [comment]
probably, you misunderstand difference http:// and https:// proxy, there is no need for https:// to support https:// protocol between client and web server, HTTP proxy supports both http and https. https:// is required to encrypt traffic between proxy client and proxy with TLS. You can use something like [stunnel](https://www.stunnel.org/static/stunnel.html) to add TLS between proxy client and proxy.
