### ISSUE TITLE
Блокировка сайтов по списку

### ISSUE THREAD

**Issue by avilios** [z3APA3A/3proxy#179]
Добрый день. Подскажите как правильно блокировать сайты по списку в файле?
Может я использую неверный формат файла?
Блокировка не работает.
Версия прокси 0.8.10

auth iponly
log C:\3proxy\logs\3proxy.log D
rotate 30
proxy
deny * * "C:\3proxy\bin\block_anonim.txt"

Содержимое файла
anonim.pro *, *.anonim.pro *, hideme.ru *, *.hideme.ru *, *.hidemy.name *, hidemy.name *

**Comment by z3APA3A** [comment]
потому что документацию надо читать. Во-первых список должен быть без пробелов, во-вторых

https://3proxy.ru/faqr.asp#LIMITS
....нарушение порядка ввода команд (команды выполняются последовательно, запуск сервиса proxy, socks, tcppm и т.д. должен осуществляться после того, как указана его конфигурация)....

**Comment by avilios** [comment]
А почему тогда такая конфигурация не работает? Не пускает в инет 123 IP. Разместил proxy в конце! Помогите разобраться! Ещё помогите как например заблокировать ya.ru для моего конфига.

auth iponly
log C:\3proxy\logs\3proxy.log D
rotate 30

internal 192.168.1.254
external 192.168.1.215

bandlimin 262144 * 192.168.1.123

proxy

**Comment by z3APA3A** [comment]
Что не работает и что в логах? Покси перезапустил с этой конфигурацией?
Да, и файл включается макросом $
$"C:\3proxy\bin\block_anonim.txt"

**Comment by avilios** [comment]
Спасибо за классную проксю! Разобрался сам)

**Comment by Qwoker** [comment]
Здравствуйте, пытаюсь ограничить доступ с прокси на все адреса, кроме определенных подсетей и доменов

daemon
auth strong
allow site.ru,91.108.16.0/22, 91.108.56.0/23, 149.154.168.0/22
deny *
users frock:CL:0s6U307O8DxaCBDl3ND4


proxy -n -a -p3124 -i1.1.1.1 -e1.1.1.1
socks -i1.1.1.1 -e1.1.1.1 -p7819

Такой вот конфиг, но что-то совсем ниче не работает с ним.
Что я делаю не так? Был бы рад, если прислали бы мне конфиг с корректировками. Спасибо

**Comment by z3APA3A** [comment]
Посмотри в мануале синтаксис команды allow, у тебя там треш. 
И не стоит писать в чужие закрытые тикеты, пиши в специально отведенный 
https://github.com/z3APA3A/3proxy/issues/245
или создай свой.
