### ISSUE TITLE
Работа с несколькими интерфейсами

### ISSUE THREAD

**Issue by U-III** [z3APA3A/3proxy#180]
Доброго времени суток.
У меня к ПК (Ubuntu 16.04) подключено несколько 4G модемов HiLINK.
Они как роутеры. То есть сами подключаются к интернету, имеют DHCP сервер (192.168.ххх.1).
И в ПК видятся как сетевое соединение 192.168.ххх.100
Я настраиваю 3proxy так
```
proxy -n -a -p8101 -i192.168.0.28 -e192.168.101.100
proxy -n -a -p8102 -i192.168.0.28 -e192.168.102.100
proxy -n -a -p8103 -i192.168.0.28 -e192.168.103.100
```
Проброс срабатывает только на текущем (выбранном системой) подключении к интернет.
То есть крайнем подключенном.
Что необходимо сделать чтоб через 3proxy - ходили все соединения одновременно.

**Comment by z3APA3A** [comment]
Видимо, ты включил ip forwarding в ядре (для прокси он не требуется). Необходимо либо отключать ip forwarding либо настраивать source routing.

**Comment by U-III** [comment]
Вот реально не включал. 
```
root@orangepilite:~# sudo cat /proc/sys/net/ipv4/ip_forward
0
```

**Comment by z3APA3A** [comment]
Тогда проверяйте что для каждого интерфейса есть дефолтный маршрут. Или все равно используйте source routing.

**Comment by z3APA3A** [comment]
Добавил для этих ваших линухов опции -Do (исходящий интерфейс) и -Di (входящий интерфейс), например
proxy -p1234 -Doeth1

**Comment by z3APA3A** [comment]
в devel

**Comment by U-III** [comment]
Спасибо - а что оно дает и что в них прописывать? Подскажите пожалуйста?

**Comment by z3APA3A** [comment]
У тебя модемы подключены как отдельные интерфейсы? Тогда для каждого прокси соответствующий интерфейс.

**Comment by U-III** [comment]
Я уже понял. Просто интерфейсы у меня динамичные. И модемов не 3 вовсе... у них даже у HiLink - макадрес один и тот же , в убунту они поэтому rename1-... обзываются и при каждой перезагрузке в разном порядке. Но в модемах строго зашито  192.168.101.1 - 192.168.200.1 Может подскажите что настроить.
И кстати столкнулся с еще одной проблемой. В локальной сети порт доступен (1 пока) и работает - но когда пробрасываю на него порт с роутера - порт оказывается недоступен. Причем у меня поднят апачь и php на 80 порту со страничкой управления модемами - она тоже не доступна через роутер (проброс с внешнего порта на внутренный). 
А если делаю так - с роутера проброс на виндовс комп - а с него на прокси - то все работает.
Я вроде не тупой. Но просто с такой организацией прокси впервые столкнулся

**Comment by z3APA3A** [comment]
Напиши скриптик который парсит интерфейсы и строит правильный конфиг, вызывай его через 'system' и включи полученный конфиг через 'include'.

**Comment by U-III** [comment]
Спасибо за совет. Но в этом я еще не силен. Будем думать с помощью гугла)))

**Comment by U-III** [comment]
А где мне 0,9 скачать то. Дай прямую ссылку на архив

**Comment by z3APA3A** [comment]
https://github.com/z3APA3A/3proxy/archive/devel.zip
или git clone https://github.com/z3APA3A/3proxy.git

**Comment by yazhog** [comment]
Извиняюсь что в закрытой.

Столкнулся с той же проблемой.

Скомпилил devel версию, предлагаемое вами решение не работает.

Пробовал и -Doeth1 и -Deeth1, ноль реакции

**Comment by sstepanovvl** [comment]
> Добавил для этих ваших линухов опции -Do (исходящий интерфейс) и -Di (входящий интерфейс), например
> proxy -p1234 -Doeth1

Поправлю чуть-чуть...
-Di (Входящий интерфейс), -De (Исходящий интерфейс)

**Comment by Emilio111** [comment]
Спасибо вам. Я тоже долго мучился пока не увидел ваш пост.Почему то ни где нет нормальной инфы по Девел версии и автор сам тоже не охотно делится,приходится методом тыка все настраивать.

> 
> 
> > Добавил для этих ваших линухов опции -Do (исходящий интерфейс) и -Di (входящий интерфейс), например
> > proxy -p1234 -Doeth1
> 
> Поправлю чуть-чуть...
> -Di (Входящий интерфейс), -De (Исходящий интерфейс)

Спасибо вам. Я тоже долго мучился пока не увидел ваш пост.Почему то ни где нет нормальной инфы по Девел версии и автор сам тоже не охотно делится,приходится методом тыка все настраивать.

**Comment by z3APA3A** [comment]
Вся документация, включая
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
содержит в т.ч. опции devel-версии,в т.ч. и -Di/-De

**Comment by Emilio111** [comment]
Добрый день Владимир. Вот мои настройки.Rassbian Buster. использую 2 модема 3G.дело в том что при отключении eth1 сразу подключается eth2 ,и интернет уже идет через eth2 игнорируя порт.а когда отключены оба интерфейса интернет идет через wlan0,как будто прокси вообще нет. не хочу подключать дополнительные скрипты c iprout2. подскажите как исправить это?
  
>Пятница, 22 мая 2020, 16:03 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Вся документация, включая
>https://3proxy.ru/doc/man3/3proxy.cfg.3.html
>содержит в т.ч. опции devel-версии,в т.ч. и -Di/-De
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by z3APA3A** [comment]
это конфигурация внутри chroot, -Di/-De не будут работать с setuid/chroot конфиграцией, т.к. для них требуется чтобы прокси был запущен от рута.

**Comment by Emilio111** [comment]
то есть получается что если 3proxy запущу от рута то нормально будет работать?
если да то подскажите пожалуйста как сделать это?
  
>Понедельник, 25 мая 2020, 15:34 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>это конфигурация внутри chroot, -Di/-De не будут работать с setuid/chroot конфиграцией, т.к. для них требуется чтобы прокси был запущен от рута.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by z3APA3A** [comment]
Где-то, скорей всего в /etc/3proxy у тебя есть конфиг, с примерно таким содержимым:

```
#!/bin/3proxy
daemon
pidfile /var/run/3proxy/3proxy.pid
chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg
```

в нем надо

chroot /usr/local/3proxy proxy proxy

заменить на

chroot /usr/local/3proxy

чтобы прокси работал из-под рута.

**Comment by z3APA3A** [comment]
Хотя возможно у тебя уже и не chroot конфиг, раз он тоже в /etc/3proxy, но комментарии остались.

**Comment by Emilio111** [comment]
Спасибо.щас проверю и отпишусь
  
>Понедельник, 25 мая 2020, 19:27 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Хотя возможно у тебя уже и не chroot конфиг, раз он тоже в /etc/3proxy, но комментарии остались.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by Emilio111** [comment]
проблема не исчезла но скорость просто космос,в других версиях 3proxy такой скорости нет.
интересно только я столкнулся с такой проблемой или уже обращались? что посоветуете еще? 
>Понедельник, 25 мая 2020, 19:22 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Где-то, скорей всего в /etc/3proxy у тебя есть конфиг, с примерно таким содержимым:
>#!/bin/3proxy
>
>daemon
>
>pidfile /var/run/3proxy/3proxy.pid
>
>chroot /usr/local/3proxy proxy proxy
>
>include /conf/3proxy.cfg
>
>
>в нем надо
>chroot /usr/local/3proxy proxy proxy
>заменить на
>chroot /usr/local/3proxy
>чтобы прокси работал из-под рута.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by Emilio111** [comment]
и еще не понятный момент..файл /etc/3proxy является скриптом,а 3proxy.cfg где писать? я перепробовал несколько вариантов,в любом из них все работает на ура только с той проблемой что писал выше.
  
>Понедельник, 25 мая 2020, 19:22 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Где-то, скорей всего в /etc/3proxy у тебя есть конфиг, с примерно таким содержимым:
>#!/bin/3proxy
>
>daemon
>
>pidfile /var/run/3proxy/3proxy.pid
>
>chroot /usr/local/3proxy proxy proxy
>
>include /conf/3proxy.cfg
>
>
>в нем надо
>chroot /usr/local/3proxy proxy proxy
>заменить на
>chroot /usr/local/3proxy
>чтобы прокси работал из-под рута.
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by z3APA3A** [comment]
Попробуй нормально описать:
1. Что ты делаешь
2. Какой результат ты ожидаешь
3. Какой результат ты наблюдаешь по факту

**Comment by Emilio111** [comment]
1.все собрано на Raspbian pi 3+b,raspbian buster. 3G modem 2 штуки. Устоновил девел версию, прописал такой конфиг
                              sudo nano /usr/local/3proxy/conf/3proxy.cfg
monitor /usr/local/3proxy/conf/3proxy.cfg
daemon
timeouts 1 5 30 60 180 1800 15 60
maxconn 50
nscache 65536
log /dev/null
#log /3proxy/logs/3proxy.log D
auth none
#users 111111:CL:111111
#users 222222:CL:222222
nserver 8.8.8.8
nserver 8.8.4.4
 
proxy -n -a -p3128 -Diwlan0 -Deeth2
proxy -n -a -p3228 -Diwlan0 -Deeth1
flush
 
Заменил chroot /usr/local/3proxy proxy proxy на chroot /usr/local/3proxy
чтобы прокси работал из-под рута.
2.Ожидаю результат такой, при отключении или зависаний одного 3g модема,например eth1, чтобы eth2 не включался в место eth1 и не брал функцию eth1 на себя. аналогично когда отключены оба 3г модема чтоб интернет не ходил через мой домашний роутер.
3. на данный момент когда отключены оба модема интернет всеровно работает и показывает мой внешний ip от провайдера. то есть порты 3128 и 3228 как бы становятся одним целым и им без разницы какой модем или интерфейс ходят через них. Если оба модема подключены и не завис один изних то все работает идеально и скорость отличная.   
>Вторник, 26 мая 2020, 13:17 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Попробуй нормально описать:
>*  Что ты делаешь
>*  Какой результат ты ожидаешь
>*  Какой результат ты наблюдаешь по факту
>—
>You are receiving this because you commented.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Emil xxx

**Comment by z3APA3A** [comment]
> Ожидаю результат такой, при отключении или зависаний одного 3g модема,например eth1, чтобы eth2 не включался в место eth1 и не брал функцию eth1 на себя. аналогично когда отключены оба 3г модема чтоб интернет не ходил через мой домашний роутер.

Сделай привязку по IP, а не по интерфейсам и настрой source routing.

**Comment by Emilio111** [comment]
Делал привязку по ip,проблема остаётся.Дело в том что с source routing
и другие версии 3proxy работают не плохо.Собственно почему я начил настраивать Девел версию,потому что в Девел после перезагрузски сети или физического вытыкания втыкания модемов не нужно запускать скрипт с маршрутами. не хочу костыли переделывать в виде скриптов с source routing.Вы скажите,если и в Девел версии без скриптов и source routing не обойтись,чтоб я оставил в покое уже это дело и занялся настройкой iproute2
  
>Четверг, 28 мая 2020, 14:14 +04:00 от Vladimir Dubrovin <notifications@github.com>:
> 
> 
>Ожидаю результат такой, при отключении или зависаний одного 3g модема,например eth1, чтобы eth2 не включался в место eth1 и не брал функцию eth1 на себя. аналогично когда отключены оба 3г модема чтоб интернет не ходил через мой домашний роутер.
Сделай привязку по IP, а не по интерфейсам и настрой source routing.
—
You are receiving this because you commented.
Reply to this email directly,  view it on GitHub , or  unsubscribe .  
 
--
Emil xxx
