### ISSUE TITLE
Не стартует СЕРВЕР

### ISSUE THREAD

**Issue by avilios** [z3APA3A/3proxy#181]
Добрый день.

Почему при наличии вот такой блокировки сервер не стартует? (как служба)
deny * * *.200.122.132.216,200.122.132.216

а при такой стартует
deny * * 200.122.132.216

**Comment by z3APA3A** [comment]
Потому что *.200.122.132.216 это неправильный синтаксис.

**Comment by avilios** [comment]
а как правильно написать?

**Comment by z3APA3A** [comment]
А что ты хочешь написать?

**Comment by avilios** [comment]
Ну например, чтобы блокировались поддомены.

**Comment by z3APA3A** [comment]
deny * * *.example.com

**Comment by avilios** [comment]
Я правильно понимаю, что при указании ИП адреса домена в списке блокировки - все его поддомены тоже блокируются? С именем всё понятно, а вот с ИП адресом не совсем. Объясните если что-то не так понимаю.

**Comment by z3APA3A** [comment]
При указании IP-адреса блокируется доступ к IP-адресу.

**Comment by avilios** [comment]
Понял. Спасибо!
