### ISSUE TITLE
IPv6 Fallback to IPv4

### ISSUE THREAD

**Issue by MathewCNichols** [z3APA3A/3proxy#182]
Hello, it looks like IPv6 will not fallback to IPv4 when using 3proxy. It does in srelay, but 3proxy is much faster and reliable in my testing!

3proxy.cfg is using the "socks -64" parameter for IPv6 preference.

You can test here: http://ipv6-test.com/

Please let me know if I can help out in any way. I love 3proxy!

**Comment by z3APA3A** [comment]
3proxy does not perform any fallback / automatic switching operations.
