### ISSUE TITLE
3proxy блокировка рекламы

### ISSUE THREAD

**Issue by avilios** [z3APA3A/3proxy#183]
Добрый день. Подскажите как можно при помощи 3proxy резать рекламу... в инете ничего толком не нашёл. Спасибо!

**Comment by z3APA3A** [comment]
А по каким критериям ты ее хочешь резать?

**Comment by avilios** [comment]
Так же как её режет adguard или adblock... типа вырезать из страниц куски и направлять пользователю уже отфильтрованный контент без рекламы.

**Comment by z3APA3A** [comment]
Для этого надо, чтобы кто-то, как в adguard или adblock, сидел и составлял правила для блокировки.
