### ISSUE TITLE
Не открывается сайт https://61.sir.egov.local/tp-manager/ - ошибка 00100 

### ISSUE THREAD

**Issue by rstaganrog** [z3APA3A/3proxy#184]
https://61.sir.egov.local/tp-manager/ - сайт в системе Госуслуг. Если Открывать этот сайт без прокси, то в браузере появляется страница таким сообщением: 

Возникла проблема с сертификатом безопасности этого веб-сайта.
Сертификат безопасности этого веб-сайта не был выпущен доверенным центром сертификации.
Наличие ошибок в сертификате безопасности может указывать на попытку обмана или перехвата данных, которые вы отправляете на сервер.  
Мы рекомендуем вам закрыть эту веб-страницу и не работать с данным веб-сайтом.  
Recommended iconClick here to close this webpage. 
Not recommended iconContinue to this website (not recommended).  

Если на открывшейся странице всё-таки нажать на Not recommended iconContinue to this website (not recommended), то далее происходит переход на страницу
https://esia.gosuslugi.ru/idp/rlogin?cc=bp

--

Если же страницу https://61.sir.egov.local/tp-manager/ открывать через прокси, то в логе видим:

"CONNECT 61.sir.egov.local:443 HTTP/1.0" 00100 0 0 PROXY/0.0.0.0:0

Видимо, проблема в том, что если при входе без прокси выдаёт сообщение "Возникла проблема с сертификатом безопасности этого веб-сайта", но с возможностью всё же перейти на следующую страницу, то в случае прокси переход не происходит и страница прсто не открывается.

--

Поскольку на вопрос с сертификатами на госуслугах мы повлиять не можем, то можно ли как-то решить эту проблему при работе с прокси, так чтобы всё происходило так же как и без прокси - либо запрашивать подтверждение перехода (с сообщением о проблеме сертификата), либо вообще сразу переходить на следующую страницу?

Используется 3proxy-0.9-lite-devel-170512222912

**Comment by z3APA3A** [comment]
Публичного домена .local вообще и сайта 61.sir.egov.local  в Internet не существует, 
это какой-то локальный сайт. 00100 это ошибка разрешения имени, что вполне логично.

>host 61.sir.egov.local 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases:

Host 61.sir.egov.local not found: 3(NXDOMAIN)

должен ли он существовать и разрешаться на сервере имен, который используется в 3proxy знает только тот, кто все это конфигурировал.

**Comment by rstaganrog** [comment]
Да, действительно, этот домен находится в защищённой сети ViPNet.
Просто если входить на это сайте без прокси, то браузер при переходе по этому адресу рисует новую страницу с информацией о проблеме с сертификатом, где переспрашивает - уверены ли вы, что хотите перейти на опасную страницу - мы говорим - ДА, уверены - после чего осуществляется дальнейшее перенаправление уже на другую страницу портала Госуслуг.

Если открывать в прокси - то страница просто сразу не открывается, безо всяких предупреждений и возможности перехода.

Для проверки разрешения DNS имени делаю пинги на 61.sir.egov.local - они проходят успешно, т.е. имя разрешается.

Дело, видимо, в том, что прокси (разрешив имя) сталкивается с той же проблемой сертификата, что и при открытии страницы без прокси, но на этом всё и заканчивается. 

Можно ли как-то определить эту ситуацию и продолжить обработку проблемной (с точки зрения сертификата) страницы так же, как это происходит при  открытии этой страницы без прокси?

**Comment by z3APA3A** [comment]
Пинги делаете с какого хоста, того где установлен 3proxy?
nserver при этом прописан в 3proxy?

**Comment by rstaganrog** [comment]
Поскольку это узел закрытой сети, может быть я могу включить какое-то дополнительное более расширенное логгирование, которое поможет понять все действия, происходящие при открытии такой страницы?

**Comment by rstaganrog** [comment]
да, пинги на машине с прокси

**Comment by rstaganrog** [comment]
nserver 8.8.8.8

**Comment by z3APA3A** [comment]
Зачем какое-то дополнительное логгирование, если проблема уже понятна? 3proxy не может разрешить имя 61.sir.egov.local в IP адрес.
8.8.8.8 ничего не знает про 61.sir.egov.local. Если вы хотите, чтобы 3proxy использовал системный резолвер, тот же который использует ping - убирайте nserver. В качестве альтернативы можно добавить адрес 61.sir.egov.local через команду nsrecord, в надежде что он не меняется.

**Comment by rstaganrog** [comment]
да, убрал - заработало)
спасибо

**Comment by rstaganrog** [comment]
Возникла новая форма проблемы доступа к 61.sir.egov.local (узлу закрытой сети ViPNet) в сочетании  необходимостью разрешать доступ к интернету компьютерам по DNS (не по IP)

Итак, на машине с прокси пинги на 61.sir.egov.local идут.
Как Вы и рекомендовали, для того, чтобы прокси (сидящий на 192.168.0.41) мог разрешить обращение 61.sir.egov.local - убрал из конфига nserver 8.8.8.8 (nserver  в конфиге не осталось вообще). В этом случае прокси нормально отдаёт 61.sir.egov.local

Но если для allow использовать разрешение машинам из локальной сети не по IP-адресам, а по DNS-именам в локальной сети - нужно использовать nserver с указаниме DNS сервера в локальной сети - nserver  192.168.0.21

Но в этом случае прокси перестаёт видеть и отдавать 61.sir.egov.local

Как быть, если нужно разрешать доступ к интернету по DNS-именам машин в локальной сети?

**Comment by z3APA3A** [comment]
Здесь в принципе не бывает нормального решения, т.к. у вас два разных непересекающихся пространства DNS-имен не имеющих отношения к Internet обрабатываемых разными DNS-серверами. Могу предложить прописать 61.sir.egov.local как nsrecord

**Comment by rstaganrog** [comment]
а вот такой вопрос - если на машине с прокси нормально разрешаются все локальные DNS-имена, то почему в конфиге прокси нужно обязательно указывать nserver 192.168.0.21 (локальный ДНС) - почему прокси не может разрешить эти локальные имена без nserver 192.168.0.21, так как это разрешает машина с прокси вне прокси?

**Comment by rstaganrog** [comment]
может быть можно доработать прокси так, чтобы он разрешал локальные имена без nserver 192.168.0.21 ?

**Comment by rstaganrog** [comment]
... в том случае если вне прокси (на машине с прокси) эти имена разрешаются без проблем

**Comment by z3APA3A** [comment]
Это не локальное имя.
Можно прописать два NS-сервера, первый локальный, второй - который приходит при установке VPN-соединения (можно узнать через ipconfig /all)

**Comment by rstaganrog** [comment]
я, наверное, о другом)

без nserver 192.168.0.21 - 61.sir.egov.local работает - всё хорошо

можно ли доработать так, чтобы без nserver 192.168.0.21 также разрещались лоакльные ДНС-имена, если они разрешаются вне прокси на машине с прокси?

**Comment by z3APA3A** [comment]
DNS нужен чтобы разрешать PTR-записи для auth dnsname, в Windows до Vista/2008 нет возможности сделать это через системный резолвер.

**Comment by rstaganrog** [comment]
С одной стороны для использования в allow DNS-имён требуется использовать локальный DNS-сервер 192.168.0.21, но с другой - конструкция nserver 192.168.0.21 будет мешать разрешению имени  61.sir.egov.local.

В то же время сейчас, без nserver 192.168.0.21, всё работает как нужно, в том числе и доступ к  61.sir.egov.local. При этом в allow используются IP-адреса.

Тогда почему бы не оставить конфиг таким как есть (не указывая nserver 192.168.0.21), но конструкцию auth cache dnsname модернизировать как-нибудь так:
auth cache dnsname 192.168.0.21 

Здесь можно добавить опциональный параметр: "DNS-сервер для разрешения локальных имён". Его значение в этом примере - 192.168.0.21 

Т.е.  nserver 192.168.0.21 в конфиге отсутствует и не мешает разрешать  61.sir.egov.local, но для разрешения локальных DNS-имён в конструкциях типа allow используется параметр"DNS-сервер для разрешения локальных имён" из конструкции auth cache dnsname 192.168.0.21.

**Comment by rstaganrog** [comment]
Ни для каких иных целей адрес 192.168.0.21 из auth cache dnsname 192.168.0.21 - не используется.

**Comment by rstaganrog** [comment]
Можно ли реализовать что-то подобное?

**Comment by z3APA3A** [comment]
nserver нужен для auth dnsname.

Нет, усложнять резолвинг в 3proxy не планируется, т.к. при корректных конфигурациях DNS его вполне хватает. Подразумевается, что если у тебя нестандартная конфигурация DNS, как здесь - с двумя разными доменами не разрешимыми через один резолвер - ты можешь поставить локальный резолвер и сконфигурировать его так, как тебе надо. Но проблема в том, что в локальном резолвере тебе придется делать ровно то же самое - прописывать два DNS-сервера.
