### ISSUE TITLE
 allow <userlist> <sourcelist> ... - можно ли в <sourcelist> указать DNS-имя?

### ISSUE THREAD

**Issue by rstaganrog** [z3APA3A/3proxy#185]
Так проще было бы управлять разрешениями для машин в локальной сети, указывая их имя в домене Windows.

**Comment by rstaganrog** [comment]
В соответствии с документацией этого сделать нельзя:
<sourcelist> - список сетей клиентов через запятую. Сеть задается в формате xxx.yyy.zzz.mmm/l, где l - длина маски сети (количество ненулевых байт). Например, 192.168.1.0/24 соответствует сети с маской 255.255.255.0

**Comment by rstaganrog** [comment]
В то время как < targetlist > указание DNS-имени работает.

Было бы хорошо сделать так и для < sourcelist > .

**Comment by z3APA3A** [comment]
Использовать имя может быть и можно, но по факту оно будет разрешаться в IP-адрес при считывании конфигурации.
Если необходимо авторизовать клиента по DNS-имени - нужно использовать auth dnsname.

**Comment by rstaganrog** [comment]
если я правильно понял, в конфиге нужно написать так:
auth dnsname
allow * computername.my-domanename.local *

Тогда computername.my-domanename.local в локальной сети получит доступ к инету. Верно?

Но так не работает.

**Comment by z3APA3A** [comment]
Нет, не так. При auth dnsname имя компьютера используется вместо имени пользователя

```
authcache ip 900
auth cache dnsname
allow computername.my-domanename.local 
```
естественно, при этом должна быть обратная зона, computername.my-domanename.local должно резолвиться в IP-адрес.

**Comment by rstaganrog** [comment]
Сделал такой конфиг

service
monitor "c:\3proxy\3proxy.cfg"
authcache ip 900
auth cache dnsname
allow computername
deny *
proxy
--
nslookup computername на машине с прокси успешно разрешает имя

При открытии страницы в браузере через прокси три раза всплывает окно аутентификации по виду похожее на окно аутентификации в Windows. 
Три раза ввожу доменного пользователя (администратора домена) и его пароль - после трёх таких раз страница так и не открывается.

Если вместо 
  allow computername
в конфиге написать
  allow computername.my-domanename.local 

то всё происходит ровно так же. При этом nslookup computername.my-domanename.local на машине с прокси также успешно разрешает имя.

--

С таким же конфигом всё работает как надо:

service
monitor "c:\3proxy\3proxy.cfg"
auth iponly
allow * 192.168.0.108 *
deny *
proxy

**Comment by z3APA3A** [comment]
а 
nslookup IP
проходит?
если не проходит - значит у тебя нет обратной зоны. Если проходит - включи лог и посмотри, какое имя туда пишется.

**Comment by rstaganrog** [comment]
nslookup 192.168.0.108
на машине с прокси резолвится в computername.my-domanename.local

**Comment by rstaganrog** [comment]
это после того, как три раза всплыла форма аутентификации

в эту форму ввёл имя доменного администратора uszn\usznadmin и его пароль

**Comment by rstaganrog** [comment]
И, насколько я понимаю, при такой форме аутентификации (даже если прокси успешно отдаст страницу), то пользователю всё равно придётся вводить логин и пароль в форму аутентификации?

Если так - то это не то что нужно.

**Comment by rstaganrog** [comment]
Изначально стоит задача разрешить доступ машинам (а не пользователям), но при этом указывать не IP-адрес в формате xxx.xxx.xxx.xxx, а доменное имя машины.

**Comment by z3APA3A** [comment]
для dnsauth обязательно надо указывать nserver.

нет, не придется, 

Но с dnsauth действительно была ошибка, бери devel-версию.

**Comment by rstaganrog** [comment]
nserver - локальный доменный, верно?

**Comment by z3APA3A** [comment]
да

**Comment by rstaganrog** [comment]
Машина, на которой для локальной сети работает реальный прокси имеет Windows XP. Для этой машины я беру сборку 3proxy-0.8.10-lite.zip.

Чтобы никому не мешать во время проверки, я запустил прокси на машине с Windows 2008 R2. Можно на этой машине продолжить проверки со сборкой 3proxy-0.8.10-lite.zip или обязательно нужно скачать 3proxy-0.8.10.zip ?

**Comment by z3APA3A** [comment]
можно.

**Comment by rstaganrog** [comment]
на странице загрузки об этих сборках написано так:
3proxy-0.8.10.zip Windows binaries, include universal 3proxy tiny proxy server 32-bit version, utilities and documentation, reqires Windows Vista/Window 2008 Server or above.
3proxy-0.8.10-lite.zip Windows binaries compiled with gcc. Works with Windows 95/98/NT/2000/XP/2003.

**Comment by rstaganrog** [comment]
ok)

**Comment by rstaganrog** [comment]
Установил 3proxy-0.9-lite-devel-170908160033

Такой конфиг:
service
nserver 8.8.8.8
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D
authcache ip 900
auth cache dnsname
allow vm.uszn.local 
deny *
proxy

**Comment by rstaganrog** [comment]
Лог:
170908180544.958 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [1088/5588]
170908180548.358 3128 00004 - 192.168.0.36:49459 0.0.0.0:0 43 43 0 CONNECT www.google.ru:443 HTTP/1.1
170908180549.407 3128 00004 - 192.168.0.36:49460 0.0.0.0:0 43 43 0 GET http://vz.ru/ HTTP/1.1
170908180601.874 3128 00004 uszn\usznadmin 192.168.0.36:49462 0.0.0.0:0 43 43 0 GET http://vz.ru/ HTTP/1.1
170908180606.066 3128 00004 - 192.168.0.36:49465 0.0.0.0:0 43 43 0 GET http://vz.ru/favicon.ico HTTP/1.1

**Comment by rstaganrog** [comment]
Эти команды
nslookup vm.uszn.local
nslookup 192.168.0.36
выдают:
Сервер:  server1.uszn.local
Address:  192.168.0.21

Имя:     vm.uszn.local
Address:  192.168.0.36

Сервер:  server1.uszn.local
Address:  192.168.0.21

Имя:     vm.uszn.local
Address:  192.168.0.36

**Comment by rstaganrog** [comment]
В браузере при попытке открытия vz.ru запрашивается ввод пользователя и пароля, но страница так и не открывается (см. лог)

**Comment by rstaganrog** [comment]
Если я правильно понял такой конфиг не должен требовать ввод пользователя-пароль при загрузке страницы?

**Comment by rstaganrog** [comment]
и клиент (браузер) и прокси находятся на одной и той же машине vm.uszn.local

vm.uszn.local - 192.168.0.36
server1.uszn.local -192.168.0.21(доменный сервер)

**Comment by z3APA3A** [comment]
nserver 8.8.8.8
ничего не знает об именах вашей локальной сети, надо оставить только локальный nserver.

**Comment by rstaganrog** [comment]
оставил только локальный - заработало
спасибо
--
получается несколько днс-серверов в конфиге нельзя указывать?
в настройках сетевого подключения в винде можно указать два - и 8.8.8.8 и 192.168.0.21

**Comment by rstaganrog** [comment]
bandlimin 5000000 * vm.uszn.local
bandlimin 2000000 * 192.168.0.1/24
В такой последовательности в конфиге я хотел бы для всей подсети ограничить скорость в 2000000, а для машины vm.uszn.local - 5000000 

Однако, по факту vm.uszn.local также получает скорость 2000000 

Если поменять строки в конфиге местами - ничего не меняется

Так и должно быть?

**Comment by z3APA3A** [comment]
Несколько DNS можно указать, но локальный должен идти первым, и при проблемах с ним все все равно отвалится, т.к. тебе разрешение локальных имен будет критично.

Чтоб сделать "за исключением" во-первых надо перед вторым banlimin добавить nobandlimin с исключением. Во-вторых, если ты хочешь имя определять по dnsauth, то указывать его надо как имя пользователя: 

bandlimin 5000000 vm.uszn.local
nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.1/24

и 2000000 в данном случае будет не на одну машину, а на всю сеть.

**Comment by rstaganrog** [comment]
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

bandlimin 5000000 vm.uszn.local
nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.1/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

**Comment by rstaganrog** [comment]
в этом конфиге добавлена машина smew1.uszn.local (192.168.0.41)

в итоге vm.uszn.local имеет скорость 5000000, а smew1.uszn.local - не ограничивает скорость вообще (10 Мбит/с)

**Comment by rstaganrog** [comment]
нужно же, что чтобы за исключением vm.uszn.local все остальные машины в подсети были ограничены скоростью 2000000 - в том числе smew1.uszn.local

**Comment by rstaganrog** [comment]
Ну, и если сформулировать задачу в общем виде, нужно определить следующую систему ограничений скорости:
- для нескольких компьютеров (заданных по DNS-имени или по IP-адресу)  в подсети 192.168.0.1/24 скорость неограничена
- для нескольких компьютеров (заданных по DNS-имени или по IP-адресу)  в подсети 192.168.0.1/24 скорость ограничена значением Limit1
- для нескольких компьютеров (заданных по DNS-имени или по IP-адресу)  в подсети 192.168.0.1/24 скорость ограничена значением Limit2 
- для всех остальных компьютеров подсети 192.168.0.1/24 скорость ограничена значением Limit0

**Comment by rstaganrog** [comment]
Это возможно?

**Comment by z3APA3A** [comment]
Ну попробуй начать с правильного задания сети, сеть не 192.168.0.1/24 а 192.168.0.0/24

**Comment by rstaganrog** [comment]
Ок, вот конфиг:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

bandlimin 5000000 vm.uszn.local
#nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

**Comment by rstaganrog** [comment]
Сделал. Вот конфиг:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

bandlimin 5000000 vm.uszn.local
nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

**Comment by rstaganrog** [comment]
всё по-прежнему: vm.uszn.local имеет скорость 5000000, а smew1.uszn.local - не ограничивает скорость вообще (10 Мбит/с - скорость провайдера)

**Comment by z3APA3A** [comment]
А что в логах по нему?

**Comment by rstaganrog** [comment]
Лог теста скорости: https://yadi.sk/d/Kp6GP0UE3Mmazu

**Comment by rstaganrog** [comment]
Сначала проверил vm.uszn.local, потом allow smew1.uszn.local

**Comment by rstaganrog** [comment]
Проверял через speedtest.net

**Comment by z3APA3A** [comment]
Что в логах 3proxy, какое имя и IP показывается у юзера без ограничения скорости?

**Comment by rstaganrog** [comment]
т.е. убрать 
  bandlimin 5000000 vm.uszn.local 
и проверить скорость и логи для 
  vm.uszn.local 
?

**Comment by rstaganrog** [comment]
конфиг:

**Comment by rstaganrog** [comment]
и его лог для теста скорости  vm.uszn.local - https://yadi.sk/d/7fM2T-0J3MnGUk

**Comment by rstaganrog** [comment]
вариант конфига вообще без ограничений скорости:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

#bandlimin 5000000 vm.uszn.local
#nobandlimin vm.uszn.local
#bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

**Comment by rstaganrog** [comment]
и лог для этого конфига для теста скорости vm.uszn.local - https://yadi.sk/d/xUOTfvJ-3MnHEs

**Comment by z3APA3A** [comment]
Зачем все это?

Ты можешь дать конфиг, соответствующее этому конфигу описание проблемы и соответствующий этому конфигу и описанию проблемы лог 3proxy?

**Comment by rstaganrog** [comment]
два варианта полных конфига и после каждого - логи для этих конфигов

**Comment by z3APA3A** [comment]
Я не знаю что ты хотел дать, потому что часть урлов не открывается, а в остальных логов по второму клиенту нет вообще. Можешь просто дать проблемный конфиг и соответствующий ему лог?

**Comment by rstaganrog** [comment]
весь лог большой - сотня-две строк - сюда вставлять наверное не лучший вариант
какие строки лога сюда скопировать?

**Comment by rstaganrog** [comment]
конфиг вообще без ограничений скорости:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

#bandlimin 5000000 vm.uszn.local
#nobandlimin vm.uszn.local
#bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local
allow smew1.uszn.local

deny *
proxy

и первые строки лога для него:
170911100152.199 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [7340/7184]
170911100153.593 3128 00000 vm.uszn.local 192.168.0.36:59492 172.217.20.162:443 372 3813 0 CONNECT googleads.g.doubleclick.net:443 HTTP/1.1
170911100158.949 3128 00000 vm.uszn.local 192.168.0.36:59496 157.240.2.35:443 1254 486 0 CONNECT www.facebook.com:443 HTTP/1.1
170911100158.070 3128 00000 vm.uszn.local 192.168.0.36:59498 34.252.220.93:80 543 475 0 GET http://zdbb.net/l/Wfa1TnvgEeSaxSIACh-JyA?action=start&gtmcb=729916363 HTTP/1.1
170911100158.357 3128 00000 vm.uszn.local 192.168.0.36:59502 104.76.55.218:80 545 293 0 GET http://a.zdbb.net/core/site?acct=speedtest&action=start&gtmcb=729916363 HTTP/1.1
170911100159.890 3128 00000 vm.uszn.local 192.168.0.36:59506 95.174.96.15:8080 780 418 0 CONNECT speedtest.mlzone.ru:8080 HTTP/1.1

**Comment by rstaganrog** [comment]
годится?

**Comment by rstaganrog** [comment]
конфиг с ограничением для всех:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

#bandlimin 5000000 vm.uszn.local
#nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local
allow smew1.uszn.local

deny *
proxy

и строки лога для него:
170911095533.830 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [7116/8220]
170911095536.576 3128 00000 vm.uszn.local 192.168.0.36:57977 172.217.20.194:80 635 492 0 GET http://googleads.g.doubleclick.net/pagead/gen_204?id=wfocus&gqid=YFy2WYeAFZSDygXWoqXoCQ&qqid=CKv8tNjtnNYCFQyKsgodf10CUQ&fg=1 HTTP/1.1

**Comment by rstaganrog** [comment]
>> Что в логах 3proxy, какое имя и IP показывается у юзера без ограничения скорости?
В предыдущем посте полный конфиг без ограничения скорости и лог для него.
Что-нибудь можно сказать по этой информации?

**Comment by rstaganrog** [comment]
вот полный конфиг с ограничением скорости:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D

bandlimin 5000000 vm.uszn.local
nobandlimin vm.uszn.local
bandlimin 2000000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

--
здесь smew1.uszn.local имеет неограниченную скорость (скорость провайдера - 10 Мбит/с), хотя в соответствии с конфигом скорость для smew1.uszn.local должна быть 2000000 
--

первые строки лога для этого конфига:
170912072509.352 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [8032/7452]
170912072515.459 3128 00000 smew1.uszn.local 192.168.0.41:3042 172.217.20.162:80 1015 567 0 GET http://pagead2.googlesyndication.com/activeview?avi=BL4EcmIu3WdvlE5qNygWquY6wDwC26_zt6gUAABABOAHIAQLgAgDIA5kE4AQBoAYC0ggFCIBhEAHCExgKEBisyM6WAyIICAMQARgBIAAYkuXszAM&cid=CAASEuRoX6cgYLFUXBtwoDLmO5G5bg&id=osdtos&ti=1&r=u&adk=2869100164&tt=100447&bs=918,931&mtos=12437,12437,12437,12437,12437&tos=12437,0,0,0,0&p=296,210,546,510&inapp=0&mcvt=12437&rs=3&ht=0&tfs=85352&tls=110755&mc=1&lte=1&bas=1&bac=1&bos=945,1030&ps=1222,1338&ss=1920,1080&pt=10308&deb=1-5-7-395-848-4&tvt=75833&avms=geo&uc=193&tgt=DIV&cl=1&cec=13&clc=1&cac=0&cd=300x255 HTTP/1.1
170912072516.901 3128 00000 smew1.uszn.local 192.168.0.41:3051 185.33.223.83:80 1097 2714 0 GET http://ib.adnxs.com/jpt?callback=pbjs.handleAnCB&callback_uid=101b3fe6e5474579&psa=0&id=5603421&size=300x250&household_carrier=undefined&referrer=http%3A%2F%2Fwww.speedtest.net%2F%3Ftest-2 HTTP/1.1
170912072516.911 3128 00000 smew1.uszn.local 192.168.0.41:3047 62.67.193.41:80 3504 1171 0 GET http://fastlane.rubiconproject.com/a/api/fastlane.json?account_id=11576&site_id=79558&zone_id=475148&size_id=15&p_pos=btf&rp_floor=0.01&rp_secure=0&tk_flint=pbjs_lite_v0.24.1&p_screen_res=1920x1080&rand=0.8397040387145327&rf=http%3A%2F%2Fwww.speedtest.net%2F%3Ftest-2 HTTP/1.1
170912072516.915 3128 00000 smew1.uszn.local 192.168.0.41:3050 185.33.223.198:80 1097 2629 0 GET http://ib.adnxs.com/jpt?callback=pbjs.handleAnCB&callback_uid=10059db53c89b351&psa=0&id=5603420&size=160x600&household_carrier=undefined&referrer=http%3A%2F%2Fwww.speedtest.net%2F%3Ftest-2 HTTP/1.1

**Comment by rstaganrog** [comment]
В двух предыдущих постах полные конфиги 1)без ограничения скорости и 2)с ограничением скорости + логи для этих конфигов

**Comment by z3APA3A** [comment]
Нужен конфиг, проблема и лог иллюстрирующий проблему, т.е. снятый в момент замера скорости. По которому можно, в частности, понять какой объем данных в какой период времени для какого пользователя передавался.
Очень желательно, чтобы в логах были %b %B и %D.

**Comment by rstaganrog** [comment]
Происходят непонятные вещи...
Настроил конфиг для воспроизведения ошибки, запустил тест и... и несколько раз подряд скорость ограничивалась как положено на обеих машинах! После каждого теста останавливал и запускал прокси.

Подумал было, что всё решилось вдруг само собой и видимо я в прошлые разы куда-то не туда смотрел.

Но не тут-то было. Собрался завершить тестирование. Рестартовал напоследок прокси, проверил скорость. И тут всё стало "по старому" - на smew1.uszn.local скорость опять перестала ограничиваться! Несколько рестартов прокси - ошибка неограничения скорости для smew1.uszn.local  стабильно повторяется несколько раз!

**Comment by rstaganrog** [comment]
конфиг:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D
logformat "L%b %B %D --- %t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

bandlimin 7000000 vm.uszn.local
nobandlimin vm.uszn.local
bandlimin 3500000 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local 
allow smew1.uszn.local 

deny *
proxy

**Comment by rstaganrog** [comment]
[3proxy.log.2017.09.13.txt](https://github.com/z3APA3A/3proxy/files/1300710/3proxy.log.2017.09.13.txt)

**Comment by z3APA3A** [comment]
Я не наблюдаю в этом логе ни одного запроса крупней 4х килобайт и скоростей выше 135177 байт в секунду (~1000000 бит в секунду).  Или у тебя не тот лог, или трафик, кторым ты меряешь скорость, не попадает в прокси.

**Comment by rstaganrog** [comment]
ну это видимо особенность сервиса speedtest.net - мерять мелкими порциями

**Comment by z3APA3A** [comment]
в этом логе вообще ни одного запроса к speedtest.net нет.

**Comment by z3APA3A** [comment]
точнее есть два - суммарно на килобайт. Остальное - реклама.

**Comment by rstaganrog** [comment]
ну не знаю, он же сначала определяет ближний хост, с которым будет делать тестовый обмен , поэтому замер идёт видимо ровно на эти ближние хосты

**Comment by rstaganrog** [comment]
корректности связки лог-прокси-браузер проверил ровно так:
- проверил прокси для Google Chrome (192.168.0.36)
- выключил прокси, удалил лог, запустил прокси, в браузере нажал кнопку BEGIN TEST
- лог наполнился, строки для smew1 в нём появились

**Comment by rstaganrog** [comment]
т.е. всё корректно, ошибки здесь не может быть

**Comment by rstaganrog** [comment]
что непонятнее всего - несколько раз (каждый раз с рестартом прокси) - ограничение на smew1 работало КАК ПОЛОЖЕНО! ))

**Comment by rstaganrog** [comment]
попробовал вместо speedtest.net взять тестер от Ростелеком

вроде бы работает так как ожидается))

**Comment by rstaganrog** [comment]
понаблюдаю ещё

**Comment by rstaganrog** [comment]
тогда вопрос если нужно определить следующую систему ограничений скорости:
- для компьютеров C1, C2, C3 (заданных по DNS-имени) в подсети 192.168.0.0/24 - скорость неограничена
- для компьютеров C4, C5, C6 (заданных по DNS-имени) в подсети 192.168.0.0/24 - скорость ограничена значением Limit1
- для компьютеров C7, C8, C9 (заданных по DNS-имени) в подсети 192.168.0.0/24 - скорость ограничена значением Limit2 
для всех остальных компьютеров подсети 192.168.0.0/24 - скорость ограничена значением Limit0,

то конфиг должен выглядеть так:
service
nserver 192.168.0.21
monitor "c:\3proxy\3proxy.cfg"
log "c:\3proxy\l\3proxy.log" D
logformat "L%b %B %D --- %t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

nobandlimin C1
nobandlimin C2
nobandlimin C3

bandlimin Limit1 C4
nobandlimin C4
bandlimin Limit1 C5
nobandlimin C5
bandlimin Limit1 C6
nobandlimin C6

bandlimin Limit2 C7
nobandlimin C7
bandlimin Limit2 C8
nobandlimin C8
bandlimin Limit2 C9
nobandlimin C9

bandlimin Limit0 * 192.168.0.0/24

authcache ip 900
auth cache dnsname

allow vm.uszn.local
allow smew1.uszn.local

deny *
proxy

**Comment by rstaganrog** [comment]
верно?

**Comment by rstaganrog** [comment]
мне не очень понятно почему после
bandlimin Limit1 C4
нужно обязательно добавлять
nobandlimin C4

иначе правило
bandlimin Limit0 * 192.168.0.0/24
не сработает

**Comment by z3APA3A** [comment]
в nobandlimin / allow пользователей можно указывать через запятую.

Любой трафик попадает под все бендлимитеры, которые имеют соответствующую ACL, а не под один. Например, у тебя может быть лимит 1 Mbps на пользователя и 3Mbps на группу из 10 пользователей, куда входит тот же пользователь. будет срабатывать тот лимит, который в настоящее время является "узким местом" (пока пользователь качает один - 1Mbps, если качают все - то узким местом будет ограничение на группу). nobandlimin исключает трафик из всех последующих правил.

**Comment by rstaganrog** [comment]
Ясно, спасибо

И еще вопрос - в приведённом выше конфиге ЛЮБОЙ из компьютеров C1, C2, ..., C9 может быть определён не по доменному имени, а по IP-адресу - в любых конструкциях bandlimin, nobandlimin, allow в любых сочетаниях?

В том числе, например конкретный компьютер, используемый в одной из конструкций  bandlimin, nobandlimin, allow по DNS-имени - может участвовать в других конструкциях  bandlimin, nobandlimin, allow по IP-адресу и наоборот?

**Comment by rstaganrog** [comment]
>>Например, у тебя может быть лимит 1 Mbps на пользователя и 3Mbps на группу из 10 пользователей, куда входит тот же пользователь. будет срабатывать тот лимит, который в настоящее время является "узким местом" (пока пользователь качает один - 1Mbps, если качают все - то узким местом будет ограничение на группу). nobandlimin исключает трафик из всех последующих правил.

вот такая последовательность:
bandlimin 5000 C1
nobandlimin C1
bandlimin 2000 * 192.168.0.0/24

будет ли идентична такой:
bandlimin 2000 * 192.168.0.0/24
bandlimin 5000 C1
?

Или порядок следования bandlimin  здесь не важен?

**Comment by z3APA3A** [comment]
Порядок важен при наличии nobandlimin, иначе действуют все bandlmin под которые попадает трафик.

**Comment by rstaganrog** [comment]
>>иначе действуют все bandlmin под которые попадает трафик.
1)вне зависмости от порядка применяется самое узкое ограничение?
2)применяются по порядку и при очередном применении по порядку выполняется проверка на попадание в ограничение?
