### ISSUE TITLE
Варианты аутентификации доменными пользователями

### ISSUE THREAD

**Issue by rstaganrog** [z3APA3A/3proxy#186]
Ключ -n используется для аутентификации в домене Windows. Конфиг для этого выглядит примерно так:
plugin "WindowsAuthentication.dll" WindowsAuthentication "3ProxyAllowedGroup" 
authcache user,password 60 
auth cache windows 

Минусом этого решения является запрос учётных данных доменного пользователя при запуске браузера.

Можно ли сделать так, чтобы этот запрос при старте браузера не выдавался?

--

Как использовать такой ключ прокси:
-n1 

В документации о нём сказано лишь: enable NTLMv1 authentication

Примеров найти не удалось.

**Comment by z3APA3A** [comment]
Современные браузеры не поддерживают прозрачную аутентификацию на прокси, вводить имя и пароль при авторизации учетной записью в любом случае придется.
-n отключает NTLMv1, -n1 включает. Сейчас в прокси по умолчанию NTLMv1 отключен, так что указывать -n смысла нет.
Начиная с Windows XP, NTLMv1 по умолчанию не используется клиентом, так что его включение ни к чему хорошему не приведет.
