### ISSUE TITLE
countersutil missing from source repo

### ISSUE THREAD

**Issue by jekader** [z3APA3A/3proxy#187]
The docs mention there's an utility to manage traffic counters called "countersutil", however it is not present in this code repo. It's a useful management tool, so would be great to have it available again.

Docs mentioning this utility:
https://github.com/z3APA3A/3proxy/blob/devel/doc/html/howtor.html#L724
https://github.com/z3APA3A/3proxy/blob/devel/doc/html/howtoe.html#L715

**Comment by z3APA3A** [comment]
countersutil was useful to migrate between 2 counters format under Windows, then 3proxy was switched to 64-bit timestamps in 0.5 version, it's probably not compatible with latest versions and I see no reason to maintain it. How do you want to use it?

**Comment by jekader** [comment]
Several use cases I see:
1) view current stats without having to wait for a report to get generated
2) reset counters for a certain user or all of them

**Comment by z3APA3A** [comment]
Current counters state can be seen via web interface (admin), also, counters may be enabled/disabled. Resetting the value can be done by changing the counter number for specific rule in the config. Resetting counters for all users can be done by removing counters file.
I can add functionality to dump/restore counters to/from some text format with standalone utility or via web interface. If you really need it - file a feature request.

**Comment by jekader** [comment]
Thanks for the description. It wasn't clear what countersutil was capable of from the docs. At this point we can just drop any mentions of it from docs and close this.

Would be nice to have a CLI to automate counter management, but I'll try to use the WebAdmin for that purpose instead.
