### ISSUE TITLE
А реально сделать шифрование между клиентом и прокси (https)?

### ISSUE THREAD

**Issue by Vshop777** [z3APA3A/3proxy#189]
Именно шифрование на стадии передачи данных от клиента до прокси 
client<-SSL->proxy

Тут пишут что браузеры поддерживают другие сервера
https://dev.chromium.org/developers/design-documents/secure-web-proxy

**Comment by z3APA3A** [comment]
На той же странице написано как это сделать с помощью stunnel. Прикрутить к прокси не сложно, но большого смысла и спроса нет, т.к. вручную прописать такой тип прокси в браузере невзможно.

**Comment by z3APA3A** [comment]
Я об этом и написал. Браузеры поддерживают, но только Хром и только в виде параметра командной строки или через файл автоконфигурации. Прописать в браузере руками в настройках прокси такой тип прокси не получится.
