### ISSUE TITLE
[RFE] connect to parent proxy using hostname and not IP

### ISSUE THREAD

**Issue by jekader** [z3APA3A/3proxy#190]
Currently, when a parent proxy of "connect" type is defined, the connection goes via IP resolved by 3proxy. 

This has limitations in the following scenarios:
1) the parent proxy has an internal DNS view with domain test123.local and 3proxy cannot resolve this hostname. Client connections to 3proxy will fail with 502 "Host Not Found or connection failed" errors and no attempts to connect to the parent
2) the parent proxy is in a different geographical location than 3proxy. A client requests a CDN link with GeoDNS enabled. In this case, DNS resolution will be done by 3proxy and will get an IP closest to it.  The parent will download content not from a nearby CDN location, but from where 3proxy is. Alternatively, no download will happen at all if the FQDN is blocked in the location where 3proxy is doing DNS resolution even though the parent can resolve it.

This RFE proposes to send CONNECT requests to the requested FQDN instead of the IP when no "nserver" configuration was added.

**Comment by z3APA3A** [comment]
To use hostname instead of IP use parent type http/connect+/socks4+/socks5+
