### ISSUE TITLE
Предложение: всё, что после символа # в текущей строке конфига - комментарий

### ISSUE THREAD

**Issue by rstaganrog** [z3APA3A/3proxy#191]
Собственно сабж - можно ли добавить такую функциональность?

Когда нужно прокомментировать несколько десятков строк - приходится писать комментарий перед комментируемой строкой. Соответственно количество строк в конфиге удваивается, ухудшается читабельность.

Если же разрешить символ начала комментария в произвольном месте конфига (от символа # и до конца строки) - строк в откомментированном конфиге будет в два раза меньше.

**Comment by z3APA3A** [comment]
Нет, это несовместимо с текущим форматом файла, т.к. # это вполне обычный символ, который может содержаться в имени, пароле или других литералах.

**Comment by rstaganrog** [comment]
Хорошо, тогда может быть использовать другой признак комментария. Например:
-- (два тире подряд, используется в некоторых языках)
// (две косых черты, используется в некоторых языках
; (точка с запятой)

Или иной признак.

**Comment by rstaganrog** [comment]
комментарий в семантически значимой строке конфига позволил бы заметно повысить компактность и читабельность конфига

**Comment by z3APA3A** [comment]
-- используется в любых punycode-доменах, // запросто может встретиться в локальных путях, ; тоже не редкий символ.
Так а что мешает хранить конфиги с любыми комментариями и в любых форматах, хоть в CSV хоть в XML хоть вообще в базах данных, а при запуске генерировать их в формате 3proxy через system и включать через include?

**Comment by rstaganrog** [comment]
>>хоть в CSV хоть в XML хоть вообще в базах данных, а при запуске генерировать их в формате 3proxy через system и включать через include?

Ну  это усложняет процесс, нужно предпринимать дополнительные действия. Хотелось бы максимальной простоты.)

>>// запросто может встретиться в локальных путях
Ок. Три слэша подряд - точно не встретится в путях)) Вариант?
