### ISSUE TITLE
HTTP proxies connect to SOCKS5 parent proxies

### ISSUE THREAD

**Issue by digi7boy** [z3APA3A/3proxy#195]
I have external socks5 proxies and I want to assign 1 by one to a http proxy. I've made some researches on google but I didn't find something to make it work. Now my settings are (which doesn't work)

#
auth strong
allow [username]
parent 1000 socks5+ 89.15.XXX.1XX 2X305 <- first external socks5
proxy -p7777 -a -i73.XX.2XX.2X4 <- main server ip
flush
#
auth strong
allow [username]
parent 1000 socks5+ 212.51.XXX.1XX 1X547 <- second external socks5
proxy -p7788 -a -i73.XX.2XX.2X4 <- second server ip
flush
#

I want my customer to connect to HTTP proxy 92.XX.2XX.2XX:7777 or 73.XX.2XX.2X4:7788 and have the external (main or second) IP the socks5 IP. Is that possible? If yes could you please help me with the correct conf settings? 

Thank you so much

PS: I'm using the last version of 3proxy.

Full 3proxy.conf

#!/usr/local/bin/3proxy
daemon

pidfile /etc/3proxy/3proxy.pid

nserver 8.8.8.8
nserver 8.8.4.4

nscache 65536

timeouts 1 5 30 60 180 1800 15 60

users username:CL:password

log /etc/3proxy/log/3proxy.log D

logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

archiver rar rar a -df -inul %A %F

rotate 30

#
auth strong
allow username
parent 1000 socks5+ 51.51.51.51 10663
proxy -p7777 -a -i80.80.80.80
#
auth strong
allow username
parent 1000 socks5+ 12.12.12.12 50923
proxy -p7788 -a -i80.80.80.81

**Comment by z3APA3A** [comment]
What results do you get, how these results are different from your expectations and what do you have in logs?

This config may be correct, depending on your configuration and expected results, you may want to add -e to specify outgoing interface for proxy (it should be local interface). If socks5 requires login/password you should specify one in "parent" command. Also, you may want to use 'fakeresolve' instead of nserver/nscache to avoid local name resolutions and resolve all names through parent proxy.

**Comment by digi7boy** [comment]
I love 3proxy now. It was my fault. I've forgot to add user/pass to my application. Now I've set fakeresolve instead nserv but I left the nscache there. Should I remove it too?

Now I want you to ask something about making a socks5 from a SSH tunneling. Does 3proxy can make something similar with ssh command in shell to maintain a socks port opened too?

**Comment by z3APA3A** [comment]
nscache is useless with fakeresolve.
If you need ssh, you can use ssh, if you need ssl, you can use stunnel, what do you expect from 3proxy in addition to that?

**Comment by digi7boy** [comment]
Nothing but I don't have knowledge how to make open a HTTP port from a ssh server with 3proxy... :(

**Comment by z3APA3A** [comment]
What do you mean "open a HTTP port"?

**Comment by digi7boy** [comment]
I mean how I make a HTTP port from socks5 I want to create/make a HTTP port from SSH machine. Because now I'm doing the following:

1. ssh -qfN -D localhost:1080 username@remote_ip -p remote_port (because is different than 22)
2. after I made a socks port from the ssh I go to 3proxy config and do the rest like a normal socks5

What I've asked is if I can avoid the Step 1 and make everything from 3proxy.cfg file as I do with socks5.

**Comment by z3APA3A** [comment]
You have to create init-script (or use one provided with 3proxy in scripts/rc.d) to start 3proxy automatically. Init scripts may depend on Linux distro, check documentation for you distro on how to create, place and install init scripts.
