### ISSUE TITLE
<Вопрос> Ограничение доступа к ресурсам сети Интернет при помощи white- & blacklists.

### ISSUE THREAD

**Issue by Yuri-01** [z3APA3A/3proxy#196]
Здравствуйте.

Скажите, прав.ли я понимаю, что при помощи "3proxy" нет возм.организовать ограниченный доступ к сайтам по "белому" или "чёрному" спискам таковых сайтов?

Дополнение:
Как я понимаю, для огранич,доступа существуют команды **allow** и **deny**, но, ограничить/разрешить с их помощью можно доступ ресурсам сети Интернет по адресам (параметр - **targetlist**), а не FQDN, URL, domain etc.
Так?
... И... ещё... Если я не прав и ограничить доступ возможно по именам ( FQDN, URL, domain и пр.), то м.ли этот список ("чёрный" / "белый") оформить в виде самостоят.файла и импортировать его в файл конф."3proxy"?

**Comment by z3APA3A** [comment]
Использовать доменные имена можно, но работать это будет только при условии что в запросе клиента имеется имя, см. allow/deny в
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
URL можно фильтровать для нешифрованного трафика через PCRE
https://3proxy.ru/plugins/PCREPlugin/
шифрованный трафик можно (но не рекомендуется для production) дешифровать через подмену сетртификата
https://3proxy.ru/plugins/SSLPlugin/

включать внешние файлы можно через include или $.

**Comment by Yuri-01** [comment]
Спасибо.

Посм.позже. Возникнут сложности – обращусь ещё раз.

Ю.
