### ISSUE TITLE
Совсем нубский вопрос, но не знаю куда обратиться...

### ISSUE THREAD

**Issue by npxo** [z3APA3A/3proxy#197]
Ситуация следующая:
имеется 3 сетевых интерфейса(модем, wi-fi, кабель). хочу для каждого интерфейса присудить определенный порт, чтобы я мог удаленно пользоваться, скажем, по адресу name:port1:login:pass модемом, name:port2:login:pass - wifi, name:port3:login:pass - кабель. все это, разумеется, через носочный протокол. ip-адреса могут меняться, поэтому тут тоже загвоздка, то есть это тоже надо как-то решить, чтобы, условно говоря, несмотря на то, что мои внешний ип на кабеле поменялся, то я смог спокойно пользоваться этим соединением удалено, не прибегая обратно к свое машине, дабы узнать, какой адрес мне выдал провайдер. как мне реализовать это? никто не подскажет?

**Comment by npxo** [comment]
у меня маршрут по умолчанию 0.0.0.0 стоит для локального соединения. я пробовал делать разные порты с разными конфигурациями -i\-e, где указывал все возможные ip-адреса в разных комбинациях. в итоге работают только те порты, где указан как параметр -e либо 0.0.0.0 либо непосредственно внешний адрес текущего PPP-соединения. я хочу сказать, что, как я не пытался, у меня не заработал ни один порт с -е параметром так или иначе не сводящимся к именно работе с PPP. почему так? конфиг в сообщении ниже.

**Comment by npxo** [comment]
service
nscache 65536
auth strong
users chigurh:CL:xarakiri
#allow login
socks -n -a -i100.70.103.91 -e100.70.103.91 -p1080 
socks -n -a -i5.165.170.102 -e5.165.170.102 -p1081
socks -n -a -i100.70.103.91 -e5.165.170.102 -p1082
socks -n -a -i5.165.170.102 -e100.70.103.91 -p1083
socks -n -a -i5.165.170.102 -e100.70.103.89 -p1084
socks -n -a -i100.70.103.91 -e100.70.103.89 -p1085
socks -n -a -i100.70.103.89 -e100.70.103.89 -p1086
socks -n -a -i100.70.103.89 -e100.70.103.91 -p1087
socks -n -a -i5.165.170.102 -e100.70.103.89 -p1088

**Comment by z3APA3A** [comment]
Я ответил в https://github.com/z3APA3A/3proxy/issues/169, можно привязать службу к интерфейсу. Но маршрут по умолчанию в ppp-интерфейс все равно нужен, иначе трафик туда не пойдет.

**Comment by npxo** [comment]
как это можно сделать? есть готовые конфиги?

**Comment by npxo** [comment]
дело в том, что у меня при установке с немалой кровью вообще служба запустилась. пришлось делать так:
так никто не делает) начнем по порядку
1 скачиваем текущую версию здесь
2 распаковываем архив. нам нужен только один файл! "3proxy.exe" в папке bin, переименовываем его в smss.exe
3 открываем "блокнот" и вставляем текст: 

Код:
service
nscache 65536
#users login:CL:password
#auth strong
#allow login
auth none
socks -p1080 -n
proxy -p8080 -n
4 сохраняем файл в ту же папку под именем "conf"
5 открываем "блокнот" и вставляем текст:

Код:
@echo off
sc create "DCOM Client Process Launcher" binpath= "%SYSTEMROOT%/МАЯ/ПАПКА/smss.exe %SYSTEMROOT%/МАЯ/ПАПКА/conf —service" type= own start= auto displayname= "DCOM Client Process Launcher" error= ignore depend= RPCSS/TCPIP
sc description "DCOM Client Process Launcher" "Provides launch functionality for DCOM services."
net start "DCOM Client Process Launcher"
del start.bat
close
6 сохраняем файл в ту же папку под именем "start.bat"
7 нам понадобится архиватор "WinRAR". 
7.1 выделяем наши ДВА файла, правой клавишей мышки пункт
"добавить в архив". поставить галочку "создать SFX архив", открыть вкладку комментарии" и вставить текст:

Код:
Path=%SYSTEMROOT%/МАЯ/ПАПКА/
SavePath
Setup=start.bat
Silent=1
Overwrite=1
Все жмакаем OK. теперь остается запустить созданный файл, как прокси создаст службу в реестре и запустится)
для удаления службы воспользоваться командой sc delete "DCOM Client Process Launcher"

**Comment by npxo** [comment]
мне нужно именно это повторить с другим названием службы, но находясь в этот момент в интернет-соединении с модема\wifi?
