### ISSUE TITLE
3proxy, tcppm, MS Windows Server 2003, TCP window scaling

### ISSUE THREAD

**Issue by stripostripa** [z3APA3A/3proxy#198]
Добрый день!
Схема подключения:
PC 10.10.10.1 --NETWORK1-- 3proxy host 10.10.20.1 --NETWORK2--  server 10.10.30.1

Использую модуль tcppm, при обращении с PC 10.10.10.1 на 10.10.20.1 TCP/2222, клиент перенаправляется на 10.10.30.1 TCP/22.

1). Передаю файл по scp PC 10.10.10.1 -> server 10.10.30.1 (без участия прокси) - скорость передачи в норме.
2). Передаю файл по scp с прокси 3proxy host 10.10.20.1 -> server 10.10.30.1 - скорость передачи в норме.
3). Если я передаю файл по scp PC 10.10.10.1 -> server 10.10.30.1  через прокси (т.е. устанавливаю tcp session 10.10.10.1 -> 10.10.20.1 TCP/2222) - скорость передачи не превышает 800Kbit/s.

Проанализировал дампы, вижу, что в 3-ем сценарии 3proxy при установке TCP сессии 10.10.10.1 -> 10.10.20.1 TCP/2222 выставляет параметр TCP Window scale = 0, что не позволяет использовать механизим TCP window scaling . Во 2-ом сценарии 3proxy предлагает использовать TCP Window scale = 7 - что позволяет передавать файлы на большой скорости.

Вопрос:
Подскажите, пожалуйста, каким образом можно заставить 3proxy выставить корректный TCP Window scale в 3-ем сценарии, чтобы можно было передавать файлы через прокси с большой скоростью?

Спасибо.

С уважением, Дмитрий.

**Comment by z3APA3A** [comment]
В Windows 2003 Windows Scaling включается при установке TCPWindowSize в значение выше 64K, поищите статьи по настройке/оптимизации сетевых параметров в Windows 2003. От 3proxy тут ничего не зависит.
