### ISSUE TITLE
Как исключить url из аутентификации в 3proxy?

### ISSUE THREAD

**Issue by umocolombo** [z3APA3A/3proxy#199]
Здравствуйте, не могу разобраться, каким образом можно исключить определенные URL из проверки auth strong?
Например для *.viber.com

**Comment by z3APA3A** [comment]
auth iponly strong
allow * * *.viber.com
deny -
allow *

**Comment by umocolombo** [comment]
Благодарю! 10.10.2017, 16:29, "Vladimir Dubrovin" <notifications@github.com>:auth iponly strongallow * * *.viber.comdeny -allow *—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
