### ISSUE TITLE
Length of proxy username and password

### ISSUE THREAD

**Issue by qwertydzen** [z3APA3A/3proxy#2]
Hi, 

First of all. Thank you for such great software! Use it from 2007.

Could you increase a limitations for username and password till 64 chars?
32  are very small. Some proxy-services control settings of proxy by username.

Thank you very much!

**Comment by z3APA3A** [comment]
Currently limitation for HTTP proxy is ~250 characters for 
username+password. Where do you observer 32 characters limitation? Can 
you describe problem in details, because limitation may be not a real issue?

**Comment by qwertydzen** [comment]
Thank you for prompt reply!
Downloaded the latest version 0.8-devel

Remote config
```
internal 0.0.0.0
external 0.0.0.0

users lum-customer-testeduser-zone-gen-country-us-session-1:CL:123ewqwesd32

logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
auth strong
allow lum-customer-testeduser-zone-gen-country-us-session-1
parent 1000 socks5 127.0.0.1 9050

log
proxy -p1111 -a
```
 
local config 
```
internal 0.0.0.0
external 0.0.0.0

logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
auth iponly 
allow *
parent 1000 http 127.0.0.1 1111 lum-customer-testeduser-zone-gen-country-us-session-1 123ewqwesd32

log
proxy -p4388 -a
```

So the bug in last "local config" when 3proxy get  proxy username and password. 

Log in a "remote config" looks like, if I use remote proxy from a local proxy.   
```
127.0.0.1 - lum-customer-testeduser-zone-gen [26/Mar/2015:12:00:53 +0300] "GET http://www.lagado.com/proxy-test HTTP/1.1" 00005 0 0 PROXY/0.0.0.0:0
```

But when I connect directly to the remote-config and specify proxy credentials in a browser I got in log right answer
```
127.0.0.1 - lum-customer-testeduser-zone-gen-country-us-session-1 [26/Mar/2015:11:59:58 +0300] "GET http://www.lagado.com/proxy-test HTTP/1.1" 00000 4985 328 PROXY/127.0.0.1:9050
```

So issue in reading username and password form parent string in config.
Highly appreciate your attention and fix!

**Comment by qwertydzen** [comment]
I have sent fix in pull-request

**Comment by qwertydzen** [comment]
Ping?

**Comment by z3APA3A** [comment]
Thanks, pulled into -devel

**Comment by z3APA3A** [comment]
P.S. I don't recommend to use usernames like this for HTTP, because username is transmitted base64-encoded in every request.
