### ISSUE TITLE
Thread un-safe code in my_ssl.c

### ISSUE THREAD

**Issue by 8ollainh** [z3APA3A/3proxy#201]
Function name : ssl_copy_cert(SSL_CERT cert)
Error line : 115 ~ 116
Error code : 
`static char hash_name_sha1[sizeof(src_cert->sha1_hash)*2 + 1];`
`static char cache_name[200];`

Error issue : **static** variable is thread un-safe.
This code sometimes causes error that saved with different file name.
And incorrectly stored certificate files will generate persistent errors.

**Comment by z3APA3A** [comment]
Should be fixed with 2c8bf28065580875fec9bcb33e21ef3f53d1bf50
