### ISSUE TITLE
поддерживает ли версия 0.8.10 so_blindtodevice?

### ISSUE THREAD

**Issue by npxo** [z3APA3A/3proxy#204]
кроме того, если поддерживает, то объясните, бога ради, почему при запуске 3proxy в убунте у меня ошибка для 8 строки в параметрах -socks/-proxy, а выглядит она(строка) так:
-socks -p1080 -Dewlo1 -Dippp0
ppp0 - интерфейс модема
wlo1 - интерфейс wifi
здесь есть ошибка или причина проблем все-таки старая версия программы?

**Comment by npxo** [comment]
когда убираю параметры блинда, то все все замечательно работает. в логах ошибки перечислены доступные параметры, где нет пресловутого -De /-Di. если все-таки дело в версии, то подскажите, как можно обновить программу одной командой. главное, чтобы не пришлось все заново настраивать. есть варианты?

**Comment by npxo** [comment]
код ошибки 40

**Comment by z3APA3A** [comment]
Нет, опция поддерживается только в 0.9 (devel) версии.

**Comment by npxo** [comment]
ёперный театр! пойду спать, совсем рассеянный стал, подумал, что 0.8 - девелоперская)) спасибо за ответ!

**Comment by npxo** [comment]
не подскажите, как по-быстрому можно обновиться на убунте? есть какие-то команды? или удалять все и вся и по новой компилировать, создавать директории, пилить конфиг?

**Comment by z3APA3A** [comment]
Конфиги совместимы, достаточно просто пересобрать бинарники.
