### ISSUE TITLE
Ошибка с кодом 40

### ISSUE THREAD

**Issue by npxo** [z3APA3A/3proxy#205]
поставил 0.9 версию, в файле конфигурации написал на проблемной строке:
"socks -p1080 -Dewlo1 -Diwwx0c5b8f279a64", где "wlo1" желательный интерфейс для приема, а "wwx0c5b8f279a64" желательный интерфейс для выхода. почему может быть такая проблема? в логах ошибки опять нет упоминания про опцию -De\Di, версия 0.9-devel (171028203145), линукс убунта 16.04.03.

**Comment by npxo** [comment]
без параметров -Dewlo1 -Diwwx0c5b8f279a64 все прекрасно работает

**Comment by npxo** [comment]
может, мне нужно поставить какой-то модуль на ОС. какой, если не секрет?

**Comment by npxo** [comment]
проблема решилась изменением букв "D" на "d". это важно, иначе не запускается

**Comment by npxo** [comment]
тем временем опция вообще ничего не меняет, шарится только один интерфейс. я что-то делаю не так?

**Comment by z3APA3A** [comment]
Что в конфиге? Что в логе?

**Comment by npxo** [comment]
https://drive.google.com/open?id=0B6lsYFn8m5vtU295Q001ZWFIY1U - конфиг
https://drive.google.com/open?id=0B6lsYFn8m5vtUi04RjJzRnB1R3c - лог

**Comment by npxo** [comment]
делал по этому гайду https://community.vscale.io/hc/ru/community/posts/115001609005-%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D0%BF%D1%80%D0%BE%D0%BA%D1%81%D0%B8-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0-3proxy-%D0%BD%D0%B0-Debian-Ubuntu

**Comment by npxo** [comment]
что бы я не делал, какую бы ОС не ставил всегда один результат. 3proxy принимает на любой ip-адрес, на любой сетевой интерфейс(хоть виртуальный, хоть физический), но выдает искючительно ip-адреса ppp от кабеля и никак иначе. пробовал в конфигах писать d с большой буквы - ни разу не получилось без ошибок запустить, пробовал все девайсы указывать после -de\-di - разницы ноль. пробовал указывать 100500 ip-адресов, которые выдавало через ifconfig, все комбинации, все вариации, десятки часов и все в пустую - результат един всегда. мне нужно по сути раздавать ip-адреса модемов для работы в арбитраже в своих целях. планировалось создание массы виртуальных сетевых интерфейсов под каждый порт и поэтому функция бинда должна работать максимально стабильно, но ничего не получается. помогите, прошу. я не особенно опытный человек в линуксе. может, мне надо какие-то модули поставить на базовую убунту, чтобы пркоси заработали как надо?

**Comment by npxo** [comment]
может дело как раз в модемах оператора сотовой связи? их никак не расшарить?

**Comment by npxo** [comment]
такое ощущение, что прокси игнорирует команду -de\-di с маленькой буквы и тупо идет по умолчанию выход в инет для пркоси-клиента

**Comment by z3APA3A** [comment]
-d это запустить как демон, к интерфейсам отношения не имеет.
Я не вижу в логе никаких 40х ошибок.
Что у тебя в ifconfig по этим интерфейсам? На обоих интерфейсах IP адрес привязан? Для обоих адресов наружу есть маршрут по-умолчанию, ты можешь сделать
ping -I адрес_интерфейса 8.8.8.8
?

**Comment by npxo** [comment]
1. не понимаю, как понять, привязан ip или нет. указан, он динамичный на всех интерфейсах. всегда указывается после ключевой фразы "inet addr:". после этого идет ключевая фраза "Bcast:", и ключевая фраза "Mask:", где указана маска подсети.
2.после пинга пишет:"PING 8.8.8.8 (8.8.8.8) from 100.84.42.230 wwx0c5b8f279a64: 56(84) bytes of data."
3. как понять маршрут по умолчанию? если это "Bcast:", то он разный у всех, иногда бывает со значениями 0.0.0.0, но на практике через этот интерфейс никогда не было выхода в интернет на прокси сервере( такой маршрут выпал для модема, а он не хочет использоваться, когда есть кабель)

**Comment by npxo** [comment]
Вот содержание моего файла инициализации:
#!/bin/sh
#
### BEGIN INIT INFO
# Provides: 3Proxy
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Initialize 3proxy server
# Description: starts 3proxy
### END INIT INFO

case "$1" in
 start)
 echo Starting 3Proxy

 /usr/bin/3proxy /etc/3proxy/3proxy.cfg
 ;;

 stop)
 echo Stopping 3Proxy
 /usr/bin/killall 3proxy
 ;;

 restart|reload)
 echo Reloading 3Proxy
 /usr/bin/killall -s USR1 3proxy
 ;;
 *)
 echo Usage: \$0 "{start|stop|restart}"
 exit 1
esac
exit 0

**Comment by npxo** [comment]
#!/bin/sh
#
### BEGIN INIT INFO
# Provides: 3Proxy
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Initialize 3proxy server
# Description: starts 3proxy
### END INIT INFO

case "$1" in
 start)
 echo Starting 3Proxy

 /usr/bin/3proxy /etc/3proxy/3proxy.cfg
 ;;

 stop)
 echo Stopping 3Proxy
 /usr/bin/killall 3proxy
 ;;

 restart|reload)
 echo Reloading 3Proxy
 /usr/bin/killall -s USR1 3proxy
 ;;
 *)
 echo Usage: \$0 "{start|stop|restart}"
 exit 1
esac
exit 0

**Comment by npxo** [comment]
может, для модема надо указывать "Bcast:" в ip-адрес, а не "inet addr:"?

**Comment by npxo** [comment]
вот такая вот ошибка, когда пишешь на проблемной строчке "socks -p1080 -Dewwx0c5b8f279a64 -Diwwx0c5b8f279a64":
Starting 3proxy
socks of 3proxy-0.9-devel (171028203145)
Usage: socks oprtions
Available option are:
 -u never ask for username
 -u2
 - и так далее
 -n - no NTML support
      Example: socks -i127.0.0.1
Service not started on line: 10
Command: "socks" failed with code 40, line 10

**Comment by npxo** [comment]
что самое забавное - это то, что команды -De/-Di в этом списке нет.

**Comment by npxo** [comment]
когда пытаешься создать прокси на любом модеме, даже если воткнуть только его, а остальные интерфейсы тупо отрубить, то он не работает. будь то мегафон, будь то прошитый свисток, будь то заводской, дело даже не в биндах, но они однозначно не работают - выбивает на ошибку.

**Comment by npxo** [comment]
у вас есть возможность, время, желание связаться по skype\discord\ts\rc итд?

**Comment by npxo** [comment]
теперь модем определился как ppp0 и после пинга добавляются к тому, что писал еще строчки
64 bytes from 8.8.8.8: icmp_seq=1 ttl=40 time=584ms
64 bytes from 8.8.8.8: icmp_seq=2 ttl=40 time=284ms
64 bytes from 8.8.8.8: icmp_seq=3 ttl=40 time=313ms
итд

**Comment by npxo** [comment]
у меня все замечательно работает, но на кабеле pppoe дом.ру, прекрасано раздает прокси, все отлично летает, а вот на модемах шляпа. мне удавалось достичь того, что с модема начал приниматься сигнал, а выводится на кабель, но никак не наоборот. я вообще ничего не понимаю. что мне делать?

**Comment by npxo** [comment]
я тут прочитал, что надо что-то делать с "/etc/network/interfaces". я там ничего не делал. надо? что мне туда прописывать. вообще интернет с модемов работает без проблемы. стоит ли вообще поднимать интерфейсы?

**Comment by z3APA3A** [comment]
Если у тебя пинги не ходят с src-адреса интерфейса, то у тебя проблема с маршрутизацией, а не с прокси, со стороны прокси тебе помочь нечем, разбирайся как добавить недостающие маршруты.

**Comment by npxo** [comment]
а как же нерабочие -De\-Di?

**Comment by npxo** [comment]
с маршрутизацией ясно, разберусь. основная проблема это ошибка при вводе опции -De\Di. я так и не получил вразумительный ответ.

**Comment by z3APA3A** [comment]
Возьми версию через git clone, там совершенно точно все работает.

**Comment by npxo** [comment]
можно ссылку? не нашел, к сожалению

**Comment by npxo** [comment]
https://github.com/z3APA3A/3proxy это по этой ссылке просто клонировать?

**Comment by z3APA3A** [comment]
Там же и загрузка есть.

**Comment by fenix957** [comment]
Клонировал все ветки и 9,3 9,4 10 devel 
Но везде ошибка 

`proxy of 3proxy-0.9.4 ()
Usage: proxy options
Available options are:
 -u never ask for username
 -u2 always ask for username
 -fFORMAT logging format (see documentation)
 -l log to stderr
 -lFILENAME log to FILENAME
 -b(BUFSIZE) size of network buffer (default 4096 for TCP, 16384 for UDP)
 -S(STACKSIZE) value to add to default client thread stack size
 -t be silent (do not log service start/stop)

 -iIP ip address or internal interface (clients are expected to connect)
 -eIP ip address or external interface (outgoing connection will have this)
 -rHOST:PORT Use IP:port for connect back proxy instead of listen port
 -RHOST:PORT Use PORT to listen connect back proxy connection to pass data to
 -4 Use IPv4 for outgoing connections
 -6 Use IPv6 for outgoing connections
 -46 Prefer IPv4 for outgoing connections, use both IPv4 and IPv6
 -64 Prefer IPv6 for outgoing connections, use both IPv4 and IPv6
 -ocOPTIONS, -osOPTIONS, -olOPTIONS, -orOPTIONS -oROPTIONS - options for
 to-client (oc), to-server (os), listening (ol) socket, connect back client
 (or) socket, connect back server (oR) listening socket
 where possible options are: 
	TCP_NODELAY
	SO_REUSEADDR
	SO_REUSEPORT
	SO_KEEPALIVE
	SO_DONTROUTE
 -pPORT - service port to accept connections
 -n - no NTLM support
	Example: proxy -i127.0.0.1

Service not started on line: 18
Command: 'proxy' failed with code 40, line 18
`

Может с каким то ключом нужно запускать или с каким то флагом компилировать ? 

Выполняю от рута 
 /usr/local/3proxy/bin/3proxy 1.cfg
13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021

**Comment by z3APA3A** [comment]
Что указано в команде proxy в строке 18?

**Comment by fenix957** [comment]
> Что указано в команде proxy в строке 18?

proxy -n -a -Diem0 -Devlan101 -p50183

В общем я так понял проблема в том что у  freebsd нет привязки  к интерфейсу 

-DiINTERFACE, -DeINTERFACE bind internal interface / external inteface to given INTERFACE (e.g. eth0) if SO_BINDTODEVICE

А такое SO_BINDTODEVICE вроде как нет во freebsd

**Comment by z3APA3A** [comment]
С какими правами запускается 3proxy? chroot / setuid в конфиге есть?

**Comment by fenix957** [comment]
> С какими правами запускается 3proxy? chroot / setuid в конфиге есть?

нет напрямую от рута

**Comment by z3APA3A** [comment]
А зачем вообще потребовался биндинг к интерфейсу вместо биндинга к IP?

**Comment by fenix957** [comment]
Ip  на интерфейсе динамический каждый раз меняется

**Comment by z3APA3A** [comment]
Биндинга к интерфейсам в FreeBSD нет, сделай перегенерацию конфигурации 3proxy в скрипте который интерфейс подключает. В Linux для этого есть ifup-скприты. возможно в FreeBSD это можно сделать через /etc/rc.d/netif
