### ISSUE TITLE
3poxy + dial up (3g модемы) = Работают не все прокси

### ISSUE THREAD

**Issue by Salyverona** [z3APA3A/3proxy#207]
Приветствую, постараюсь детально объяснить свою проблему
На Win 7 установлен 3proxy
К ПК подключено 2 x 3G модема
Создано 2 dil up подключения:
Connect 1 (использую 3g модем 1)
Connect 2 (использую 3g модем 2)

Конфиг 3proxy:
log c:\3proxy\logs\3proxy.log
auth none
proxy -p3128 -i192.168.0.25 -e10.201.169.252
proxy -p3129 -i192.168.0.25 -e10.194.41.244

Проблема:
В один момент времени работает только 1 прокси. Самый последний в списке
То есть, если подключаться по порту 3128 - идет запрос логина/пароля. 
Но при попытке перейти на любой сайт получаю:
403 Access Denied
Access control list denies you to access this resource 
При подключении к 3129 - все отлично

Если отключить второй 3g модем от ПК или просто разорвать соединение. 
Подключение по 3128 начинает работать 

Буду благодарен за помощь

**Comment by z3APA3A** [comment]
При auth none прокси не может запрашивать имя и пароль, значит на этом же порту висит другой экземпляр с другой конфигурацией, убейте все лишние.

**Comment by Salyverona** [comment]
Спасибо за ответ
В первом посту скопировал не тот конфиг, но это не особо меняет суть дела.

Запущен только один экземпляр. 
Если в конфиге auth none - конечно запроса на авторизацию нет и работает только последний прокси в списке.  Если в конфиге auth strong - то опять же работает только последний прокси в списке. Хотя  для первого прокси - запрос на ввод логина/пароля получаю - но открыть какой либо сайт не могу

Модемы исправны. Для каждого dial up подключения в настройках выбран свой модем. Оба подключения активны

**Comment by z3APA3A** [comment]
Тогда смотри что в логах и что в конфиге, и почему конфиг не пропускает запрос.
