### ISSUE TITLE
Работа 3proxy  в transparent-режиме (перенаправление через iptables)

### ISSUE THREAD

**Issue by EvgenNSK** [z3APA3A/3proxy#208]
Прошу консультацию:
Длительное время работала связка squid3 + Netfilter, при котором весь траффик на destination port 80 автоматом заворачивался на внутренний IP шлюза на порт 3128. Директива http_port, понятное дело, имела доп.опцию transparent.
Машина на Ubuntu Server 16.04 LTS

Собственно, сейчас я перевожу шлюз на 3proxy. Все работает, пока в браузере прокси:порт прописан явно, но если завернуть траффик через Netfilter, то браузер сыпет ошибками SSL для https-сайтов.
Ошибка вида:
> При соединении с 2ip.ru произошла ошибка. SSL получило запись, длина которой превышает максимально допустимую. Код ошибки: SSL_ERROR_RX_RECORD_TOO_LONG

Конфиг на шлюзе:
```
daemon
setgid 126
setuid 118
pidfile /var/run/3proxy.pid
plugin /usr/local/bin/TransparentPlugin.ld.so transparent_plugin
internal 0.0.0.0
external 0.0.0.0
nserver 127.0.0.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
log /dev/null


flush
auth iponly
allow *
parent 1000 http 192.168.2.1 31280
proxy -n -p31280 -4 -T
```

В директиве proxy, как видите, опция -Т присутствует.
Имеется вышестоящий 3proxy.
Все работает корректно, при ручном указании прокси:порт, сервис 2ip показывает внешний IP машины, которая стоит за родительским прокси. Т.е. к перенаправлению у меня вопросов нет.
Прошу указать, какие директивы и в какой вид требуется исправить для того, чтобы 3proxy корректно обрабатывал траффик, который на него перебрасывает Netfilter.

**Comment by z3APA3A** [comment]
Нельзя заворачивать https трафик в прокси без декодирования. При использовании TransparentPlugin https трафик надо заворачивать в tcppm и parent ставить connect.

**Comment by EvgenNSK** [comment]
Правильно ли я понимаю, что для описанной задачи необходимо применять "Плагин SSL\TLS для 3proxy", с формированием кэша подменных сертификатов?
В то случае, если я буду использовать TransparentPlugin, необходимо выполнять "переброску" соединения путем жестких конструкций на базе tcppm?

**Comment by EvgenNSK** [comment]
Здравствуйте, Владимир!

Спасибо за уделяемое время.

Что я хочу?

Кратко предыстория:
Имеется контора (небольшой офис) подключенный к интернету. По договору на юр.лицо у них скорость всего 4 мегабита.
А хочется скорость побольше, и без существенной доплаты.
У этого же провайдера сделали еще одно подключение (вообще в другом районе города), но на физ.лицо. Скорость доступа в интернет - 100 мегабит. Абонентка - 500 рублей.
Скорость внутри сети провайдера - 100 мегабит.
У "юрика" и "физика" шлюзы на Ubuntu Server 16.04

Хитрый план руководства: прокинуть от "юрика" до "физика" OpenVPN-туннель, завернув туда траффик маршрутом по умолчанию.
Маршрут до основных сервисов провайдера прописан вручную (местные DNS-ы, сайт с личным кабинетом и т.д.), указан местный шлюз провайдера.
А директор 1 раз в месяц доплачивает 500 руб. одному из сотрудников, у которого подключение на "физика".

Ну, собственно, года три уже так работает. 
HTTP-траффик кидается через два Squid-а (один сквид у "юрика", у него в настройках прописан второй сквид на стороне "физика" как parent).
Но чтобы бегал HTTPS-траффик, приходится рулить маршрутом по умолчанию, что сопровождается определенными неудобствами.
Открываешь 2ip.ru - показывает "белый" IP "физика", как и должно быть.

Ну так вот:
Решил пересесть с "кальмара" на Ваш продукт, т.к. HTTPS-проксирование он делает замечательно.

Поднял 2 экземпляра (концепция как у сквида): один у "физика", второй - у "юрика". Тот, что у "физика", прописан родительским в конфиге у "юрика" (тот самый 192.168.2.1).

Если в офисе у юрика прописать в браузере настройки прокси: внутренний IP-шлюза "юрика" с портом 31280, то все сайты открываются, и HTTP и HTTPS.
Но на каждый ПК ногами ходить - не технологично, при перенастройке прокси у них инет будет пропадать.

Еще во времена "сквида" на iptables было простое правило: весть транзитный траффик из локалки "юрика" на порт 80 заворачивать на внутренний IP и порт 3128.
Добавил в правило кроме 80-го порта еще и 443.
В настройках браузера выставил "без прокси". Теперь по идее траффик должен заворачиваться автоматом.

Так вот, HTTP - работает, а при открытии HTTPS-сайтов браузер пишет вот такую лажу (на месте 2ip.ru там любой сайт, хоть гугл):

При соединении с 2ip.ru произошла ошибка. SSL получило запись, длина которой превышает максимально допустимую. Код ошибки: SSL_ERROR_RX_RECORD_TOO_LONG 

Вот и возник вопрос: что я делаю не так?

? Правильно ли я понимаю Ваш вариант конфига:
На стороне "юрика" конфиг должен предполагать 1 слушающий порт для HTTP, и еще плюс одно перенаправление траффика для HTTPS.
Правил на iptables должно быть 2: одно - кидает транзитный траффик с портом назначения TCP\80 на локальный порт 31280, второе правило - для HTTPS - кидает транзитный траффик с портом назначения TCP\443 на локальный порт 31281.
Вроде все правильно понял?

Но совсем не понял, как работает вот это:

tcppm 31281 127.0.0.1 31282

Получается, что на 127.0.0.1 (на локалхосте) на порту 31282 нужно заранее открыть некий слушающий сервис.
Как это работает? Как 3proxy понимает, что надо сделать далее с траффиком, который прилетел на порт 31281?

Строчками выше у нас указан "родитель", но там и близко нет упоминания какого-либо порта 31282:

parent 1000 http 192.168.2.1 31280

Видимо, это особенности работы плагина?

Простите, что отнимаю время, но поясните, пожалуйста.

**Comment by z3APA3A** [comment]
Если нет необходимости отдельно разбирать HTTP-трафик и логать запросы, то достаточно только одного правила, которое будет перенаправлять любой трафик, который надо проксировать через внешний прокси в порт tcppm.

**Comment by EvgenNSK** [comment]
Ничего логировать не надо.
log /dev/null

Все, что надо - настроить 3proxy на шлюзе "юрика" так, чтобы выполнялось прозрачное перенаправление траффика пользователей к вышестоящему родителю.

Введено  в NetFilter на этом же шлюзе классическое правило:
iptables-t nat -A PREROUTING -i eth1 -p tcp -m multiport --dport 80,443 --jump DNAT --to 192.168.1.1:31280
(тут eth1 - внутренний интерфейс шлюза "юрика", 192.168.1.1 - его IP-адрес)
которое завернет весь транзитный траффик на HTTP\HTTPS-серверы к себе на локальный порт 31280.
На этом порту сидит и ждет 3proxy, и когда к нему прилетит запрос, он должен передать его вышестоящему родителю на 192.168.2.1:31280.

Еще раз спрошу Вас по поводу этого фрагмента конфига - нет ли тут какой-нибудь опечатки:
flush
allow *
parent 1000 connect 192.168.2.1 **31280**
plugin /usr/local/bin/TransparentPlugin.ld.so transparent_plugin
tcppm 31281 127.0.0.1 **31282**

Если опечатки нет - в 2-х словах, как это работает? На порту 31282 у нас ничего нет! Правило tcppm отправляет "в никуда"?

**Comment by z3APA3A** [comment]
Прокси ничего не логгирует по умолчанию, log /dev/null заставляет прокси делать лишнюю работу - формировать ненужные логи.

адрес и порт назначения в tcppm можно поставить любые, они будут переписываться transparent-плагином. Какой у тебя порт parent - тебе видней.

**Comment by EvgenNSK** [comment]
_log /dev/null заставляет прокси делать лишнюю работу - формировать ненужные логи._
Вот это хорошее замечание. В некоторых мануалах указано, что надо указывать явно /dev/null, а то иначе куда-нибудь 3proxy начнет складывать логи (которыми потом может воспользоваться товарищ майор из соответствующего ведомства).
Мне-то логи в принципе не нужны.

Ваш вариант скрипта с описанием портов:

auth iponly
allow *
parent 1000 http 192.168.2.1 31280
proxy -n -p31280 -4
flush
allow *
parent 1000 connect 192.168.2.1 31280
plugin /usr/local/bin/TransparentPlugin.ld.so transparent_plugin
tcppm 31281 127.0.0.1 31282

Работает отлично!

Более того, на родительском прокси (который "физ.лицо") я использовал аналогичное решение:

flush
auth iponly
allow *
maxconn 1000
proxy -n -p31280 -4 -a1

flush
auth iponly
allow *
parent 1000 connect 0.0.0.0 0
plugin /usr/local/bin/TransparentPlugin.ld.so transparent_plugin
tcppm 31281 127.0.0.1 31282

В результате, если у "юрлица" на iptables завернуть http-трафик прямо на "физ.лицо" на порт 31280, а https - на 31281, то все работает, и получается, что экземпляр 3proxy на шлюзе "юр.лицо" простаивает без работы.

Большое спасибо!
Если возможно, прикрепите к данной ветке обсуждения пометку "РЕШЕНО" на случай, если кто-то будет гуглить эту же тему.
