### ISSUE TITLE
помогите с PCRE

### ISSUE THREAD

**Issue by g-karpov** [z3APA3A/3proxy#209]
Мой конфиг:
```
auth iponly
plugin c:\3proxy\bin64\PCREPlugin.dll pcre_plugin
pcre request allow "www\.msftncsi\.com\/ncsi\.txt" * * * 80 HTTP_GET
pcre request allow "www\.microsoft\.com\/pkiops\/crl" * * * 80 HTTP_GET
pcre request allow "ocsp\.digicert\.com\/" * * * 80 HTTP_GET
pcre request allow "ocsp\.thawte\.com\/" * * * 80 HTTP_GET
pcre request allow "crl\.thawte\.com\/" * * * 80 HTTP_GET
```
соответствующие запросы блокируются.
Пробовал варианты:
```
pcre request allow "http:\/\/www\.msftncsi\.com\/ncsi\.txt" * * * 80 HTTP_GET - ИМХО самый правильный
pcre request allow "www\.msftncsi\.com\/ncsi\.txt" * 
pcre request allow ":\/\/www\.msftncsi\.com\/ncsi\.txt" *
```

При этом
`allow * * www.msftncsi.com,crl.microsoft.com 80 HTTP_GET`
работает, но это проверка на hostname, что не всегда подходит и не достаточно безопасно.

Что я делаю не так? Как можно получить отладочную информацию?

**Comment by z3APA3A** [comment]
pcre request allow и allow/deny никак не связаны и действуют независимо друг от друга. Т.е. если имеется deny запрещающий доступ к сайту, pcre request allow никак не повлияют, т.к. до разбора запроса просто не дойдет.

**Comment by g-karpov** [comment]
Это крайне неожиданно и от того ещё не понятнее.
Как реализовать фильтрацию по URL?
К сожалению описание модуля слишком скупое по крайней мере для меня.

**Comment by z3APA3A** [comment]
На уровне сети разрешить запросы по пользователям, IP или вообще все через allow/deny, на уровне PCRE разрешить запросы по белому списку и запретить все остальные через pcre request allow / pcre request deny.
