### ISSUE TITLE
как через 3proxy трафик на определенный ресурс (ya.ru, google.com) перекидывать на определенный интерфейс, а остальной трафик шел на указанный изначально при поднятии прокси?

### ISSUE THREAD

**Issue by npxo** [z3APA3A/3proxy#211]

**Comment by npxo** [comment]
кстати, маскарад в построутинге можешь приоритено выше перебивать настройки 3прокси?

**Comment by z3APA3A** [comment]
Проще всего через parent extip + при необходимости source routing, например
allow * * ya.ru,google.com
parent 1000 extip 1.2.3.4 0
для запросов попадающих под allow будет использовать адрес источника 1.2.3.4
