### ISSUE TITLE
what is sys/timeb.h needed for?

### ISSUE THREAD

**Issue by Jimmy-Z** [z3APA3A/3proxy#212]
I'm trying to compile this for Android using NDK, apparently commenting out `#includ <sys/timeb.h>` in proxy.h is enough to make it work, well, aside from some Makefile modifications.

**Comment by z3APA3A** [comment]
it's required for ftime(), ftime() is currently only used for Windows, for POSIX systems gettimeofday() is used instead, so you can safely remove it or move to #ifdef _WIN32 section.

**Comment by z3APA3A** [comment]
P.S. If you provide working Makefile I can add it.

**Comment by Jimmy-Z** [comment]
Thanks for the explanation, the Makefile is hardcoded to target armv7a, and all plugins are disabled, if you're OK with that.
[Makefile.Android.txt](https://github.com/z3APA3A/3proxy/files/1501252/Makefile.Android.txt)
