### ISSUE TITLE
Rate limit for every individual connect

### ISSUE THREAD

**Issue by hanbang-wang** [z3APA3A/3proxy#216]
I know now there's a `bandlimin`, but it limits the sum of the bandwidth of every request went through this filter, which is merely the case. I often meet the situation where it requires to limit every single connect, so could you please add this function?

**Comment by z3APA3A** [comment]
I see no any practical impact in it, why you consider bandlimin is inappropriate for your case?

**Comment by hanbang-wang** [comment]
Say I want to have 10M of bandwidth to be used for proxy, and there will be 10 people using it. Using `bandlimin` would mean they share a total of 10M, so the real situation could be one guy taking 9M away and other nine guys share 1M. What I really want to do is to limit every user to 1M, so the sum would not surpass 10M, and everyone could share equal speed.

**Comment by z3APA3A** [comment]
In this case you should create 10 bandlimin's, 1 per user or per IP, depending on how do you identify the user (not per connection). Single user may create multiple connections.
This scripts demonstrates creating bandlimiters and counters on user addition:
https://github.com/z3APA3A/3proxy/blob/devel/scripts/add3proxyuser.sh

**Comment by z3APA3A** [comment]
e.g. 
bandlimin 512000 user1
bandlimin 512000 user2
...
bandlimin 512000 user10
