### ISSUE TITLE
 Диагностика ошибки 502 Bad Gateway "Failed to connect parent proxy"

### ISSUE THREAD

**Issue by v1pka** [z3APA3A/3proxy#222]
Использую 3proxy для подключения к родительскому хосту - иногда 3proxy говорит, что все плохо для http ресурсов, но при этом все https ресурсы отлично открываются. Пробовал увеличить таймауты, но не помогло. Соответственно вопрос - как диагностировать проблему?
Текущий конфиг:
```
timeouts 100 500 300 600 1800 18000 1500 600

nserver 10.0.0.100
nserver 8.8.8.8
nserver 8.8.4.4
# nscache is good to save speed, traffic and bandwidth
nscache 65536
 
log "C:\Work\Proxy\logs\3proxy.log" D

logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T %I %D"

archiver rar rar a -df -inul %A %F

rotate 10

auth iponly

allow *

parent 1000 connect+ PROXY.MYHOST.RU 8000 login password

deny *

proxy -n
monitor "C:\Work\Proxy\cfg\3proxy.cfg"
```

**Comment by z3APA3A** [comment]
В логе есть код ошибки.

А зачем используется connect+ прокси, у родительского прокси может быть ограничение и он может пускать через CONNECT только запросы на 443й порт. Правильней использовать http прокси.

**Comment by v1pka** [comment]
В лог ошибок не пишется :( Как включить дебаг мод - не нашел.
При указании прокси вида:
parent 1000 http PROXY.MYHOST.RU 8000 login password
пишет Host Not Found or connection failed

**Comment by z3APA3A** [comment]
В лог пишется 5-значный код ошибки.
Убедись что nserver правильно прописан или используй fakeresolve

**Comment by v1pka** [comment]
Вроде заработало. Спасибо!
