### ISSUE TITLE
При запуске скомпилированной новой версии cpu в 100% 

### ISSUE THREAD

**Issue by xvost** [z3APA3A/3proxy#223]
Доброго дня.
Сегодня попробовали собрать/запустить свежую версию, но после старта загрузка cpu уперлась в 100% и прокси не работали.

Подробности о системе 

root@vps15072:# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie
root@vps15072:# uname -a
Linux vps15072 4.9.0-0.bpo.5-amd64 #1 SMP Debian 4.9.65-3+deb9u2-bpo8+1 (2017-01-05) x86_64 GNU/Linux
root@vps15072:# gcc -v
Используются внутренние спецификации.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Целевая архитектура: x86_64-linux-gnu
Параметры конфигурации: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Модель многопоточности: posix
gcc версия 4.9.2 (Debian 4.9.2-10) 
root@vps15072:~#

**Comment by z3APA3A** [comment]
Какую свежую версию и с каким конфигом?

**Comment by xvost** [comment]
Версия 0.9-devel
Конфиг
```
daemon
maxconn 10000
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
setgid 65535
setuid 65535
flush
auth strong
users admin:CL:admin
allow admin
proxy -6 -n -a -p30000 -i*.*.33.210 -e*:*:4ad6:fca3:da3e:4a4c:0ec3:9d69
proxy -6 -n -a -p30001 -i*.*.33.210 -e*:*:75e5:aafe:6863:999e:bc97:2346
proxy -6 -n -a -p30002 -i*.*.33.210 -e*:*:0d04:261c:c865:6bbf:26f5:fba5
```

**Comment by z3APA3A** [comment]
У меня не вопроизводится. Можешь попробовать сократить конфигурацию до минимальной, типа
log ./3proxy.log
proxy
посмотреть будет ли проблема в такой конфигурации, если будет - то что в логе. Если в такой конфигурации проблемы нет - то постепенно упростить конфиг чтобы понять что именно вызывает проблему?

**Comment by z3APA3A** [comment]
должно быть поправлено в 
6e240defdbdb47dcd139799fb594a73f81f237c2
