### ISSUE TITLE
Прокси при старте чего-то молча ждет, порты не слушает, лог-файл создается однако он пустой [ Debian9.3 amd64 kernel 4.14 (конфиг ядра взят от 4.9 из дистра) ]: 

### ISSUE THREAD

**Issue by IvankoB** [z3APA3A/3proxy#224]
Что собралось:
https://tashkent.publicvm.com/cloud/index.php/s/DBQocXFQq1ysFRt

Чем собран :
==
gcc (Debian 6.3.0-18) 6.3.0 20170516

**Comment by z3APA3A** [comment]
Дубль https://github.com/z3APA3A/3proxy/issues/223, должно быть поправлено последним коммитом.

**Comment by IvankoB** [comment]
Коммит:
@@ -1509,7 +1509,7 @@ struct commands commandhandlers[]={
        {commandhandlers+58, "delimchar",h_delimchar, 2, 2},
        {commandhandlers+59, "authnserver", h_authnserver, 2, 2},
        {commandhandlers+60, "stacksize", h_stacksize, 2, 2},
-       {commandhandlers+51, "force", h_force, 1, 1},
+       {commandhandlers+61, "force", h_force, 1, 1},
        {commandhandlers+62, "noforce", h_noforce, 1, 1},

не помог, тут что-то другое. В моем случае проц не грузится, видимо дело в не лупе.

**Comment by z3APA3A** [comment]
Тогда смотри что написано в том таске - давай конфиг, пробуй с самым простым конфигом, смотри что вызывает проблему.

**Comment by IvankoB** [comment]
давай конфиг, пробуй с самым простым конфигом, смотри что вызывает проблему.
==========================
C сэмпл-конфигом из гита и даже всеми закомменченными прокси-командами в нем - то же самое. 
Какие есть предложения  по части "посмотреть" в такой молчаливой ситуации  ? На компе сложнй айпитэйблз-конфиг, но он по идее не может мешать иниту слушания.
Может внедрит нечто вроде протоколоивания (в стдэрр) этапов иницилизации ?

**Comment by z3APA3A** [comment]
Можешь запустить с конфигом

log
proxy

?

**Comment by IvankoB** [comment]
Зараз зробымо :)))

**Comment by z3APA3A** [comment]
Если запускается - начни приводить этот конфиг постепенно к своему, и смотри после чего работать перестанет.

**Comment by IvankoB** [comment]
В тестовом скрипте трошки напутал с расширениями файлов конфига - а софтина если не находит скормленный конфиг то похоже что переходит в ожидание стдин-ввода конфига. Если это так, то нельзя ли матюкаться в духе "такой конфиг-файл не существует " и аварийно выходить?
После последнего коммита и подстройки "ulimits -n 99999"  в демон-скрипте похоже что все заработало. 
Спасибо за терпение :)
