### ISSUE TITLE
Архитектура сервера ARM64

### ISSUE THREAD

**Issue by sysrise** [z3APA3A/3proxy#225]
Здравствуйте,
Имеется VDS, операционная система Linux(Debian) на ARM64, есть ли смысл пробовать запустить на нем 3proxy? Squid использовать по многим причинам не очень хочется.

**Comment by z3APA3A** [comment]
Так а в чем проблема? 3proxy всегда работал на ARM и в BE и LE.

**Comment by sysrise** [comment]
Спасибо за ответ, развеяли сомнения. Смущало то, что не все пакеты работают на этой архитектуре, те которые выходят за рамки системного репозитория.
