### ISSUE TITLE
Configuration and monitor issue

### ISSUE THREAD

**Issue by michaeladm** [z3APA3A/3proxy#226]
Есть пара неприятных моментов.

1.
Как в такой конфигурации задать в обход парент-прокси доступ к веб-серверу на той же машине ( 10.0.0.1:80 - на клиентах нет возможности указать, что не использовать сокс-прокси для этого адреса ):
flush
allow * 10.0.0.120 * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 8080
allow * 10.0.0.120 * 80
allow * 10.0.0.120 * 443,1025-65535
parent 1000 connect 127.0.0.1 8081
socks -e127.0.0.1 -i10.0.0.1 -p33120
суть в том, что при использовании клиентами варианта tun2socks или его собрата для iOS - Potatos , при обращении к апачу http://10.0.0.1/ программа 3proxy "вешается" - происходит переинициализация (сброс всех соединений, и инициализация новых). При использовании обычных компутеров с Mozilla-сокс5 настройками такой неприятности не наблюдается - к 10.10.0.1 подключается через парент-прокси (это можно пережить), тем более можно указать, что "не нужно к этому адресу через сокс".

2.
При использовании такого варианта:
monitor "/usr/local/www/3proxy/proxy/34121.txt"
monitor "/usr/local/www/3proxy/proxy/34122.txt"
monitor "/usr/local/www/3proxy/proxy/34123.txt"
flush
allow *
include "/usr/local/www/3proxy/proxy/34121.txt"
proxy -a -e1.3.8.51 -i127.0.0.1 -p34121
flush
allow *
include "/usr/local/www/3proxy/proxy/34122.txt"
proxy -a -e1.3.8.51 -i127.0.0.1 -p34122
flush
allow *
include "/usr/local/www/3proxy/proxy/34123.txt"
proxy -a -e1.3.8.51 -i127.0.0.1 -p34123
где в текстовых файликах записываются новые (постоянно меняющиеся) парент-прокси.
Все было бы хорошо, но, если какой нибудь парент-прокси (новый) - не удачный (не верный домен прокси сервера, гдето) то происходит полная переинициализация 3proxy. В логах это выглядит так
H3832.444 05-02 h{0} Err{00000} TCPPM:23098 Cl[127.0.0.1:23098] Rip[1.3.8.51:0] Req[0.0.0.0:0] Exiting thread in{0} out{0}
H3832.444 05-02 h{0} Err{00000} PROXY:24099 Cl[127.0.0.1:24099] Rip[1.3.8.51:0] Req[0.0.0.0:0] Exiting thread in{0} out{0}
H3832.444 05-02 h{0} Err{00000} TCPPM:23079 Cl[127.0.0.1:23079] Rip[1.3.8.51:0] Req[0.0.0.0:0] Exiting thread in{0} out{0}
... ... ...
H3835.243 05-02 h{0} Err{00000} ADMIN:62000 Cl[0.0.0.0:62000] Rip[0.0.0.0:0] Req[0.0.0.0:0] Accepting connections [69186/17589504] in{0} out{0}
H3835.244 05-02 h{0} Err{00000} SOCKS:23010 Cl[10.10.0.9:23010] Rip[127.0.0.10:0] Req[0.0.0.0:0] Accepting connections [69186/17590784] in{0} out{0}
H3835.246 05-02 h{0} Err{00000} PROXY:24010 Cl[127.0.0.1:24010] Rip[1.3.8.51:0] Req[0.0.0.0:0] Accepting connections [69186/17592064] in{0} out{0}
... ... ...
И, когда стартуешь 3proxy, если в парент-прокси мониторном файлике прописано что то не то, то - не стартует (пишет ошибку в строчке parent, и если таких файлов куча, то даже не реально найти, в каком из них проблема).
Как побороть такую неприятность?

**Comment by michaeladm** [comment]
с первым пунктом разобрался:
flush
allow * 10.0.0.0/24 10.0.0.0/24 *
parent 1000 http 0.0.0.0 0
allow * 10.0.0.0/24 10.0.0.0/24 *
allow * 10.0.0.120 * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 8080
allow * 10.0.0.120 * 80
allow * 10.0.0.120 * 443
parent 1000 connect 127.0.0.1 8081
#--- все остальные порты ----------------------------------
allow * 10.0.0.120
parent 1000 socks5 127.0.0.1 1080
#--- \ ----------------------------------
socks -e127.0.0.1 -i10.0.0.1 -p33120

3.
Вопрос связан с редким моментом, но важным. Есть до сих пор такие сервера у которых не стандартные порты (не 80 или 443), например http://portquiz.net:8080/ . В данном случае должен идти GET , т.к. это не HTTPS протокол, но на parent 1000 socks5 127.0.0.1 1080 уходит:
H-39-46.694 10-02 h{1} Err{00000} SOCK5:33120 Cl[10.0.0.120:54794] Rip[127.0.0.1:1080] Req[178.33.250.62:8080] CONNECT portquiz.net:8080 in{4562} out{371}
На прямую в браузере http://portquiz.net:8080/ открывается нормально, через сокс - нет.
Парент-сокс5 настроен так

**Comment by z3APA3A** [comment]
SOCKS сервер имеет методы CONNECT, BIND и UDPASSOC, для него все равно, что передается через соединение, HTTP или не HTTP. Если в браузере что-то не открывается - ищи проблему не в SOCKS, т.е. по логам соединение прошло.

**Comment by z3APA3A** [comment]
По monitor скорей всего ты не понимаешь как он работает. Не надо мониторить много файлов, достаточно мониторить один файл, который менять при изменении конфигурации.
