### ISSUE TITLE
SSLPlugin mitm mode not working

### ISSUE THREAD

**Issue by fens85** [z3APA3A/3proxy#227]
При таком конфиге:
```
plugin /tmp/SSLPlugin.ld.so ssl_plugin
ssl_certcache /tmp
daemon

log /var/log/3proxy/3proxy.log D
rotate 30

auth iponly
ssl_mitm
proxy -p8080 -I###.###.###.### -e###.###.###.### -n -a

setgid 65534
setuid 65534
```
Выдает ошибку: **symbol lookup error: /tmp/SSLPlugin.ld.so: undefined symbol: CRYPTO_num_locks**

если поменять _ssl_mitm_ на _ssl_nomitm_ то получаю:
Command: 'ssl_nomitm' failed with code 1, line 35

без указания _ssl_mitm_ и _ssl_nomitm_ 3proxy стартует нормально но соответственно в обычном режиме без подмены сертификатов.

Сертификат 3proxy.pem и ключи 3proxy.key и server.key на месте.
Архитектура amd64.
Ось GNU/LInux Ubuntu 16.04

**Comment by z3APA3A** [comment]
Какая версия 3proxy? Какая версия OpenSSL?

**Comment by fens85** [comment]
3proxy 0.8.10
OpenSSL 1.0.2g-1

**Comment by michaeladm** [comment]
Хотелось бы и для FreeBSD такое тоже. Компилироваться - компилируется, но ошибки, как выше описано - один в один.

**Comment by michaeladm** [comment]
избавился от одной ошибки - symbol lookup error: /tmp/SSLPlugin.ld.so: undefined symbol: CRYPTO_num_locks

**Comment by z3APA3A** [comment]
CRYPTO_num_locks должен быть во всех версиях OpenSSL начиная с 0.9.4. Если он не находится, скорей всего это означает что динамических библиотек OpenSSL нет в стандартном расположении, или 3proxy собран не с той версией OpenSSL которая установлена в системе.

**Comment by michaeladm** [comment]
на этой же системе собран squid с ssl_bump и openssl  - все работает

**Comment by michaeladm** [comment]
>>> что динамических библиотек OpenSSL нет в стандартном расположении
во FreeBSD   openssl идет в стандартной поставке самой системы, в стандартных расположениях всех системных библиотек и файлов - по путям самой системы

**Comment by z3APA3A** [comment]
Ну тогда возможно все еще проще, и в Makefile добавили SSLPlugin но не добавили -lssl и -lcrypto в LIBS, хотя в Makefile это написано

**Comment by z3APA3A** [comment]
Под FreeBSD я не тестировал SSL, но все должно быть аналогично Linux.

**Comment by michaeladm** [comment]
вот последние строчки из результата "make" :

**Comment by michaeladm** [comment]
ssl_plugin.c:392:21: warning: incompatible pointer types assigning to 'size_t (*)(int, void *, size_t, int, struct sockaddr *, socklen_t *)' (aka 'unsigned long (*)(int, void *, unsigned long, int, struct sockaddr *, unsigned int *)')
      from 'int (int, void *, size_t, int, struct sockaddr *, socklen_t *)' (aka 'int (int, void *, unsigned long, int, struct sockaddr *, unsigned int *)') [-Wincompatible-pointer-types]
                pl->so->_recvfrom = ssl_recvfrom;
                                  ^ ~~~~~~~~~~~~
6 warnings generated.
cc -fpic -c -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL my_ssl.c
cc -o../../SSLPlugin.so -pthread -shared ssl_plugin.o my_ssl.o -lcrypto -lssl
root@f12sgrw0:~/3proxy-devel#

**Comment by michaeladm** [comment]
т.е. SSLPlugin.so собран с ключами -lcrypto -lssl

**Comment by z3APA3A** [comment]
Так и в чем сейчас проблема?

**Comment by michaeladm** [comment]
но, к сожалению, толку - ноль. При указании ssl_mitm перед службой ничего не происходит. Инет как шел, так и идет (без видимых изменений). В логах тоже тишина по поводу какого то применения этого метода.
При указании ssl_nomitm - Command: 'ssl_nomitm' failed with code 1, line ... И такое же сообщение при указании ssl_mitm второй раз (перед второй службой в cfg)

**Comment by z3APA3A** [comment]
А какие видимые изменения ожидаются?

**Comment by michaeladm** [comment]
ну , я подозреваю, как и у squid, нужно в браузер установить сертификат, чтобы https сайты начали открываться, а не ругаться на отсутствие защищенного интернета.

**Comment by michaeladm** [comment]
а ничего такого не наблюдается, интернет как был, так и есть

**Comment by z3APA3A** [comment]
ssl_certcache задан?
3proxy.pem 3proxy.key server.key по этому пути лежат?
Доступ у прокси с теми правами что он работает в эту директорию и к файлам есть?
Конфиг который в начале неправильный, в /tmp такие вещи делать нельзя, там sticky bit + в конфиге suid делается уже после запуска прокси.

**Comment by z3APA3A** [comment]
+ стоит разок запустить без daemon, чтобы увидеть, что пишется в stderr.

**Comment by michaeladm** [comment]
daemon
pidfile /var/run/3proxy/3proxy.pid
log /var/log/3proxy/3proxy.log
plugin /usr/local/lib/3proxy/TransparentPlugin.so transparent_plugin
plugin /usr/local/lib/3proxy/SSLPlugin.so ssl_plugin
ssl_certcache /usr/local/www/SSL/
logformat "L%H-%M-%S.%. %d-%m h{%h} Err{%E} %N:%p Cl[%C:%c] Rip[%R:%r] Req[%Q:%q] %T in{%I} out{%O}"
rotate 1
nserver 127.0.0.1
nscache 65536
maxconn 400

allow * 192.168.0.0/24
parent 1000 http 2.2.2.2 3328 xxxxxxx xxxxxx
proxy -a -e1.1.1.1 -i192.168.0.1 -p20000

allow * 192.168.0.0/24
parent 1000 connect 2.2.2.2 3329 xxxxxxx xxxxxx
ssl_mitm
proxy -a -e1.1.1.1 -i192.168.0.1 -p20001

end

запускается от пользователя root

**Comment by michaeladm** [comment]
файлы 3proxy.key 3proxy.pem server.key взяты от сюда: https://github.com/z3APA3A/3proxy/releases/download/0.8.11/3proxy-0.8.11.zip

**Comment by michaeladm** [comment]
запустил без daemon - /usr/local/bin/3proxy /usr/local/etc/3proxy.cfg

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by michaeladm** [comment]
сделал упрощение - ssl_mitm поставил только перед службой на paret http  и о чудо! - затребовало сертификат, и начало работать.
А почему когда второй раз перед второй службой указываешь ssl_mitm ошибка ?
или ssl_mitm - это триггер - вкл, выкл, вкл ? Можно указать один раз выше в конфиге, где нужно - выключить по ходу в низ, если нужно опять включить?

**Comment by z3APA3A** [comment]
Да, попытка повторно включить включенный или выключить выключенный mitm дает ошибку.

**Comment by michaeladm** [comment]
Еще пару вопросов, что бы закрыть тему (заранее спасибо):
1. это работает для таких служб как tcppm и socks ?
2. в чем смысл server.key и как его делать самому. 3proxy.crt и 3proxy.key наверное можно сделать самому по аналогии инструкций для squid ssl_bump , или есть нюансы?

**Comment by michaeladm** [comment]
и еще, смущает такое:
10-02-41.768 04-03 h{1} Err{00000} PROXY:25120 Cl[10.10.0.120:62536] Rip[1.1.1.1:11111] Req[13.56.3.170:443] POST http://www.wish.com/api/client-resource-perf HTTP/1.1 in{418} out{2306}
10-02-41.838 04-03 h{1} Err{00000} PROXY:25120 Cl[10.10.0.120:62542] Rip[1.1.1.1:11111] Req[54.230.10.148:443] GET http://contestimg.wish.com/api/webimage/59b225554505db0d20d2cdb3-large.jpg
это в действительности туда уходят запросы по порту 443 в виде http:// или это в логи просто так светит?

**Comment by z3APA3A** [comment]
Пока mitm рассчитан только на connect-прокси и https траффик.
http:// в данном случае нормально, внутри HTTP-запроса не передается протокол, ссылку в логах формирует proxy который получает уже дешифрованный трафик.
