### ISSUE TITLE
3proxy просит лицензию

### ISSUE THREAD

**Issue by Maxim79** [z3APA3A/3proxy#228]
Здравствуйте! Запускаю 3proxy а окно открывается и закрывается. Удалось прочитать следующее : 

Please read license agreement in copying file You may not use this program without accepting license agreement

Как с этим быть ?

**Comment by fens85** [comment]
3proxy распространяется под лицензией BSD по этому данное ПО свободно распространяемое. А из текста следует что вам необходимо принять лицензионное соглашение перед использованием.
И тут возникает множество вопросов:
1. Что значит: Запускаю 3proxy а окно открывается и закрывается?
2. Какая Операционная система?
3. Какие настройки указанные в конфигурационном файле?

**Comment by Maxim79** [comment]
Операционная система Windows 8.1 professional Запускаю как положено из папки bin64 3proxy.exe файл Окно командной строки в которой показывается соединение и прочее показывается на одну секунду меньше. Я успел сделать скрин https://pp.userapi.com/c841129/v841129421/6a9ad/cOdBOhF2TzQ.jpg В конфигурационном файле не чего не менял. Скачиваю как есть и сразу запускаю.

**Comment by Maxim79** [comment]
На 7win все работало и окно не закрывалось показывая идущие соединения подключенных клиентов к моему прокси, точнее 3proxy. На 8.1 окно закрывается сразу не успев открыться. Делал совместимость с 7 win не помогло. 
1. Скачиваю 3proxy с официального сайта и из папки bin64 запускаю 3proxy.exe Окно которое должно показывать соединения, черное как cmd открылось и сразу закрылось. 
2. Операционная система 8.1
3. Настройки не менял все по умолчанию как скачал так и оставил.

**Comment by Maxim79** [comment]
Извините ! Разобрался Добавил файл конфигурации и все заработало. Хотя на 7 и без него окно открывалось а на 8.1 нет.
