### ISSUE TITLE
-DiINTERFACE, -DeINTERFACE

### ISSUE THREAD

**Issue by ToRRhino** [z3APA3A/3proxy#229]
Нашел в документации [ссылка](https://3proxy.ru/doc/man3/3proxy.cfg.3.html) параметры -DiINTERFACE, -DeINTERFACE, где сказано что можно указать интерфейсы вместо IP адреса. Работает ли это? может я что-то не так понял?

**Comment by z3APA3A** [comment]
Работает в devel-версии в системах подерживающих соответствующую сокетную опцию (Linux, FreeBSD, и т.п.)

**Comment by Cyph3r** [comment]
I cannot get this feature to work.

If I have ip x.x.x.x which is on eth1, then:

socks -ex.x.x.x
will work great, but:

socks -Deeth1
does not work. Log says 00012, if that helps.

**Comment by z3APA3A** [comment]
Probably you've specified both -De and external and external address do not belong to eth1.

**Comment by Cyph3r** [comment]
I'm not sure what you mean. This is my test config:
`auth none
flush
allow 3APA3A
maxconn 200
socks -Deeth1
`

**Comment by Cyph3r** [comment]
As I said, it works when exchanged for -ex.x.x.x. More auth settings are above the pasted segment of the config. It's pretty much default config.

Log:
1523813112.012  SOCK5.1080 00012 3APA3A ::ffff:x.x.x.x:62941 87.250.251.119:443 0 0 0 CONNECT_87.250.251.119:443

**Comment by z3APA3A** [comment]
I can't guess the missed section of config.
add %e to logformat to check address 3proxy attempts to bind and check if this address is configured to eth1 with ifconfig, it should give you idea why it fails to. If 3proxy attempt to bing "0.0.0.0" address, eth1 should have IPv4 address configured.

**Comment by Cyph3r** [comment]
Ok, you were right earlier. external earlier in config conflicted with -Deeth1. I didn't understand what you meant initially. Thanks for your help!

**Comment by Cyph3r** [comment]
But when I change to another eth, using -DeethX, like 1,2,3, it still goes out the default gateway, despite whichever I choose. This box has multiple external internet connections, one per eth interface. Do not have this issue when specify -ex.x.x.x.

**Comment by z3APA3A** [comment]
I think this queston has no relation to proxy. All non-local networks are routed through default gateway if no static route is given for destination address.
You can specify gateways via different interfaces, but I'm not sure how does it work in Linux.
Most probably, you have to use source routing (aka policy routing) instead.

**Comment by Cyph3r** [comment]
I understand your point, but then why does it work when using -ex.x.x.x ?

**Comment by z3APA3A** [comment]
I know neither details of your network configuration nor specifics of linux routing. In the case of -e you do not limit interfaces used for routing, traffic may go via different interface.

**Comment by VasiliPupkin256** [comment]
I am using version 0.8.13 and it still not recognize this option. I have this line in the config
`socks -i127.0.0.1 -Deeth1 -p1080`.

**Comment by z3APA3A** [comment]
-De / -Di are supported in 0.9 (devel) version.

**Comment by brian6932** [comment]
Does this not work on Windows (`0.9.4`)?

**Comment by z3APA3A** [comment]
Windows does not have separate option to bind interface, binding by IP in Windows binds both IP and interface.

**Comment by brian6932** [comment]
True that winsock's bind function doesn't, but you can resolve the `NetConnectionID` to it's respective `IPAddress`, you should be able to use this same WQL query in C.
```pwsh
$NetConnectionID = 'foo'

(Get-CimInstance -Query "
    select IPAddress from Win32_NetworkAdapterConfiguration
    where Index = $((
        Get-CimInstance -Query "
        select DeviceID from Win32_NetworkAdapter
        where NetConnectionID = '$NetConnectionID'"
    ).DeviceID)"
).IPAddress
```
