### ISSUE TITLE
crashes on v0.7, 502 error (00012) on v0.8

### ISSUE THREAD

**Issue by zett83** [z3APA3A/3proxy#23]
на Crashdump'ы кидал ссылку в skype, после всех экспериментов попробовал снова перебраться на 0.8 версию, крашится меньше, но очень много 502 ошибок у клиентов.

в логах много вот таких записей, как то уже писал на email об этой проблеме,
добавил патчик для дополнительного логирования, вот такое вот выводит:

18-11-2015 20:44:55 +0200 PROXY.42010 00012 <login> <ip> 0 0 0 GET <url> HTTP/1.1
18-11-2015 20:44:55 +0200 PROXY.42010 00000 <login ip ...> 0 0 0 Address already in use

почему и кем занят не понятно, причем на 0.7 версии с одинаковыми настройками, всё работает.
но крашится (

как будет время и желание гляньте pls, со своей стороны предоставлю любые данные.
если что можно через skype )

заранее спасибо.

**Comment by z3APA3A** [comment]
В каком месте ты залогировал, какая конфигурация? Какой maxconn, сколько одновременных подключений в момент, когда возникает проблема? Какая ОС, если линукс - что в /proc/sys/net/ipv4/ip_local_port_range ?

**Comment by zett83** [comment]
из давней переписки в email, в common.c поменял

        if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, sizeof(param->sinsl))==-1) {
            return 12;
        }

на

        if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, sizeof(param->sinsl))==-1) {
            (*param->srv->logfunc)(param, strerror(errno));
            return 12;
        }

в логе получил то что выше.


os: centos 6_x86_64 (виртуалка),
maxconn: 655350 (тут уже экспериментировал с разными)
/proc/sys/net/ipv4/ip_local_port_range: 25000   65000

limit'ы:

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 15591
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 5000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) unlimited
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

в момент того как, одновременных коннектов до 1200.
точно пока не скажу, но вообще это максимальное значение по zabbix'у.

ещё напомню, что на сервере около 255 ip'шников,
и ещё рядом крутятся accel-ppp (pptp|l2tp services), и openvpn.

обратно откатился на 0.7 всё же работающий но иногда падающий, таки лучше чем 502 ошибки и всё так-же падающий ( может я что-то не так конфигурю?

setgid 99
setuid 99

nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
maxconn 655350

timeouts 1 5 30 60 180 1800 15 60
daemon

дальше include с таким содержимым:
flush
users <user>:<pass>
auth strong
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
allow <user>

собственно и весь конфиг

**Comment by z3APA3A** [comment]
maxconn не должен быть больше доступного диапазона портов, в данном случае maxconn должен быть меньше 40000. 
А как организовано использование разных IP?

**Comment by z3APA3A** [comment]
И можешь поменять
    if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, sizeof(param->sinsl))==-1) {
        (*param->srv->logfunc)(param, strerror(errno));
        return 12;
    }
на что-нибудь типа
    if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, sizeof(param->sinsl))==-1) {
        char errbuf[256];
        sprintf(errbuf, "bind port: %uh, error: %.200s", (unsigned short)*SAPORT(&param->sinsl), strerror(errno));
        (*param->srv->logfunc)(param, errbuf);
        return 12;
    }

?

**Comment by zett83** [comment]
> А как организовано использование разных IP?

proxy -n -a -i<ip1> -e<ip1> -p41508
proxy -n -a -i<ip2> -e<ip2> -p41508
proxy -n -a -i<ip3> -e<ip3> -p41508
и т.д.

ок код подправил, запустил жду логи.

**Comment by z3APA3A** [comment]
Тогда maxconn должен быть меньше 40000, т.к. он задается отдельно на каждый proxy и соответственно на каждый IP

**Comment by zett83** [comment]
мм, т.е. 40000/кол-во прокси(628 на этом сервере )~= maxconn: 63 ?
и мы как бы упремся в кол-во возможных прокси я правильно понимаю?

**Comment by z3APA3A** [comment]
нет.
C скаждого IP можно установить не более 40000 соединений. 

Для каждого IP запущен отдельный прокси. maxconn ограничивает количество соединение на прокси, а не суммарно. Поэтому исходя из доступных портов, maxconn должен быть меньше 40000 (например, 20000), если нет других системных ограничений. А они есть.

Например, ограничение 5000000 на открытые файлы, каждое соединение требует 2 сокета, поэтому реально лучше ставить ограничение maxconn 4000, тогда шансы превысить количество открытых дескрипторов невелики. При этом максимальное теоретическое количество соединений будет 4000*628, максимальное количество открытых сокетов 628*4000*2.

**Comment by zett83** [comment]
всё, спасибо за разъяснения. наконец понял ) переконфигурил, буду дальше следить

**Comment by zett83** [comment]
00012 ошибки продолжает сыпать: но перед ней теперь в лог выводит это:
bind port: 33682h, error: Address already in use
и иногда это:
bind port: 32994h, error: Permission denied

выглядит вот где то так:
20-11-2015 02:06:02 +0200 PROXY.42122 00000 - ip:62020 ip:443 0 0 0 bind port: 32994h, error: Permission denied
20-11-2015 02:06:02 +0200 PROXY.42122 00012 - ip:62020 ip:443 0 0 0 CONNECT api.domain.com:443 HTTP/1.1

     maxconn: 4000

это уже в самом начале конфига

     setgid 99
     setuid 99

раньше помоему проблема с permission denied была в этом,
но сейчас то что ? )

**Comment by z3APA3A** [comment]
bind port: %uh

поменяй на

    bind port: %hu

это моя опечатка.
И попробуй добавить 

		*SAPORT(&param->sinsl) = 0;

перед

		if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, sizeof(param->sinsl))==-1) {
			return 12;
		}

**Comment by zett83** [comment]
поправил. вчера весь день, не было 00012, но было два краша (
а на другом сервере за день 5 раз упал. к сожалению crashdump'ы там отключены.
но ещё слежу.

**Comment by z3APA3A** [comment]
Дай еще раз бинарник и дампы

**Comment by zett83** [comment]
выслал ссыклу на email.

**Comment by z3APA3A** [comment]
Посмотри еще в dmesg что пишется pls

**Comment by zett83** [comment]
что то пусто в dmesg, но нашел вот такую запись в /var/log/messages:

Nov 23 01:04:40 3proxy: *** glibc detected *** /usr/bin/3proxy: free(): invalid pointer: 0x00002b0ef5fb5000 ***

по времени совпадет с дампом.

**Comment by z3APA3A** [comment]
Fixed few race conditions on configuration reload.
