### ISSUE TITLE
Несколько dialer

### ISSUE THREAD

**Issue by ToRRhino** [z3APA3A/3proxy#230]
Если я настрою прокси таким образом:
```
...
proxy -n -p8080 -i192.168.1.2 -e10.11.12.13
proxy -n -p8081 -i192.168.1.2 -e10.11.13.13
```

И в какой то момент **один** из выходных интерфейсов не будет доступен, то как поднять его используя команду **dialer**? Можно ли использовать несколько dialer? предполагается, что поднимаются разные выходные интерфейсы по-разному

**Comment by z3APA3A** [comment]
dialer будет дергаться при любой недоступности любого хоста. Определять доступность интерфейсов и т.п. - это уже задача диалер, напиши скрипт так, чтобы он работал со всеми интерфейсами или сам определял какой скрипт необходимо дернуть.
