### ISSUE TITLE
Внешний прокси

### ISSUE THREAD

**Issue by Maxim79** [z3APA3A/3proxy#231]
Здравствуйте ! Можно 3proxy использовать как внешний прокси. Скажем чтобы к нему подключались   пользователи интернет и потом выходили под другим ip в интернет. ? Если да то возможно это сделать на одном внешнем ip?

**Comment by ToRRhino** [comment]
Чтобы ответить нужны подробности? Предположим у вас статический IP (95.95.95.95) и вы хотите чтобы пользователи подключались к этому IP, а потом их запросы прокировались через тот же (95.95.95.95) IP?

**Comment by z3APA3A** [comment]
Да, можно.

**Comment by Maxim79** [comment]
Да статический адрес внешний и к нему подключается пользователь и под ним выходит далее в интернет ? Такое возможно ?

**Comment by Maxim79** [comment]
Можно защитить свою локальную сеть с помощью прокси ? Скажем на машине где стоит прокси поставить антивирус и тем самым убрать антивирусы с рабочих компьютеров?

**Comment by ToRRhino** [comment]
Как ранее писал z3APA3A, такое легко реализуется минимальными настройками. Однако, идея с антивирусами не реализуема, если под вирусами мы подразумеваем вредоносные программы. По поводу вирусов: может возможно так ограничить права пользователей на рабочих компах, чтобы нельзя было установить что-то ненужное, что может быть вредоносным ПО, но в этом я плохой помощник
