### ISSUE TITLE
Защита на прокси от вирусов

### ISSUE THREAD

**Issue by Maxim79** [z3APA3A/3proxy#232]
Можно защитить свою локальную сеть с помощью прокси ? Скажем на машине где стоит прокси поставить антивирус и тем самым убрать антивирусы с рабочих компьютеров?

**Comment by ToRRhino** [comment]
Стандартными средствами 3proxy это нельзя реализовать. Возможно есть прокси-серверы, которые способны такое делать (что вряд ли), но я еще не видел

**Comment by Maxim79** [comment]
ну а вообще какую защиту можно сделать на этом прокси ?

**Comment by ToRRhino** [comment]
Например, ограничить доступ по таким параметрам, как доступ к определенным сайтам, доступ относительно времени, доступ относительно объема трафика

**Comment by z3APA3A** [comment]
Сетевая фильтрация трафика не может заменить антивируса на рабочей станции.
