### ISSUE TITLE
Different parent for each user on one ip and port?

### ISSUE THREAD

**Issue by magnum-ferox** [z3APA3A/3proxy#236]
Hello. I have the opportunity to allocate only 1 port for the proxy.
But I want for each user to specify a different parent proxy.
Tell me how can I set this up?

3proxy tiny proxy server 3proxy-0.7 (140408012613)

**Comment by z3APA3A** [comment]
```
allow user1
parent 1000 ...parent1...
allow user2
parent 1000 ...parent2...
...
proxy
```

3proxy 0.7 is outdated and is not longer supported, current stable version is 0.8.11
