### ISSUE TITLE
Проблема при открытии 10к+ портов

### ISSUE THREAD

**Issue by Troodi** [z3APA3A/3proxy#237]
Имеется 2 сервера, на одном запускается всё окей, всё отлично работало, купил второй в 3 раза мощнее лимиты выставил хорошие:
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 386628
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1000000
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
Но получаю полный отказ сервера выполнять простейшие команды вроде "kill"
```
fork: retry: Resource temporarily unavailable
```
В логах иногда пролетает:
```
pthread_create(): Resource temporarily unavailable
```

Конфиг вида:
```
log
auth iponly
external ip
allow * ip
parent 1000 socks5+ ip port
fakeresolve
connlim 100 0 * *
socks -p3815
proxy
monitor "/var/cfg"
flush
```
Ну таких повторений 10 000 и более. В чем может быть проблема, уж весь гугл облазил. Потому как почему сервер который мощнее "отваливается", тогда как слабенький справляется на ура?

UP:  командой
 lsof | wc -l
Выяснилось что открытых дескрипторов файлов: 1863439
Отсюда вопрос, а что столько прокси не открыть? Может конфиг некорректен? Хотя всё равно странно что всё на разных серверах по разному.

**Comment by z3APA3A** [comment]
1. В вашей конфигурации есть открытый прокси. Если вы такую конфигурацию светите в интернет, вам любые ресурсы выжрут.
2. Какая версия 3proxy используется? В более старых версиях обязательно надо запрещать доступ к прокси через прокси или разводить внутренний и внешний интерфейсы если отсутствует авторизация по пользователям, иначе запрос типа http://proxy:port может приводить к тому, что прокси ресурсивно будет обращаться сам к себе и выжрет любые ресурсы. По логам это должно быть видно (прокси обращается сам к себе). В свежих версиях есть защита от рекурсии. 
3. Потребности прокси в ресурсах и как отлаживать проблемы нехватки ресурсов подробно обсуждается здесь:
https://3proxy.ru/highload.asp

**Comment by Troodi** [comment]
Версия девел. Да, я прочитал. Но даже ставим такой конфиг:
```
log
socks -p11450
flush
```
Ну открываем с 1001 по 11450 порт. Тут вообще никаких заморочек. Опять-таки один сервер держит, второй валится, кряхтит и возмущается. Рекурсии нет, да и всё равно проблема возникает только при открытии прокси, дальше же не продвигаемся.
