### ISSUE TITLE
ODBC prevents 3proxy runs on nanoserver.

### ISSUE THREAD

**Issue by fcicq** [z3APA3A/3proxy#238]
I downloaded mingw-w64 ver 3proxy from msys2 repo and copied the binary to nanoserver, and found 3proxy cant be run due to missing odbc32.dll.
socks.exe is ok.

with dependency walker, I found 3proxy is linked with user32.dll & odbc32.dll, while socks.exe only requires kernel32.dll, msvcrt.dll, ws2_32.dll.

maybe providing a version without linking to odbc (-DNOODBC)?

**Comment by z3APA3A** [comment]
I have no idea who is supporting msys2 repo and there is no any reason to use msys2 or mingw with 3proxy, because 3proxy is native Windows application and doesn't require POSIX emulation. You can download native 3proxy windows binaries from
https://github.com/z3APA3A/3proxy/releases
use "lite" version, it can be run on older Windows version and is compiled without ODBC support.

**Comment by fcicq** [comment]
sorry, nanoserver is 64bit only. the 64bit binary linked with odbc32.dll so it cant be running.

**Comment by fcicq** [comment]
api list for search: https://msdn.microsoft.com/en-us/library/mt588480(v=vs.85).aspx

**Comment by z3APA3A** [comment]
Try to add odbc32.dll from here:
https://github.com/z3APA3A/3proxy-archive/blob/master/odbc32/odbc32.zip
to 3proxy folder.
It's fake odbc32.dll, so ODBC will not work, but it will eliminate dynamic linking problmes.

**Comment by fcicq** [comment]
now I am able to see the help message. now I'm fight against other errors running as service (not related with 3proxy I think).

Thank you very much!

**Comment by fcicq** [comment]
working report:
New-Service -Name 3proxy -DisplayName 3proxy -BinaryPathName "c:\3proxy\3proxy.exe c:\3proxy\3proxy.cfg --service" 
New-NetFirewallRule -Name 3proxy -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort PORT

3proxy --install does not work because using MessageBox().

**Comment by fcicq** [comment]
the problem summary: 
1 official binary doesnt work, only the mingw-w64 msys2 socks.exe works. I may abandon here if I didnt found that. 
2 using dependency walker to find the odbc32.dll difference. thanks for the fake odbc32.dll. alternately I may prepare a toolchain to disable ODBC by NOODBC.
3 found the correct command line while --install not works.
on starting the service I got "net : The service is not responding to the control function."

**Comment by z3APA3A** [comment]
Last message probably means you have invalid configuration.

**Comment by z3APA3A** [comment]
Try to run
c:\3proxy\3proxy.exe c:\3proxy\3proxy.cfg
from command line

**Comment by fcicq** [comment]
already resolved. as --install cant work, I tried many times to seek the correct arguments though :( .
