### ISSUE TITLE
proxymain: srvinit: memleak -- free after memset

### ISSUE THREAD

**Issue by SiarheiVolkau** [z3APA3A/3proxy#239]
Function srvinit firstly cleanup all srv content and then attempt to free some of its fileds (logtarget and logformat).

memory freeing should be called before memset.

**Comment by z3APA3A** [comment]
It's a wrong statement.

**Comment by z3APA3A** [comment]
This check will never succeed so it may be ommited, but this fact doesn't lead to any memory leak. Attempting to check/free before memset() will cause access to uninitialized memory.

**Comment by SiarheiVolkau** [comment]
There are some misconcept and its really confusing:
1. if you want handle uninitialized srv inside srvinit you SHOULD NOT handle initialized in the same function and myfree related code is unnecessary.
2. if you want handle already initialized srv inside srvinit you SHOULD NOT handle uninitialized in the same function and initialization (memset) should be done outside srvinit.

From context i see srvinit() called only once, at startup, passed pointer are uninitialized.

**Comment by z3APA3A** [comment]
Yes, as it was said before, this construction is not required here, probably it's result of cut-n-paste. I will remove it. 
It doesn't change the fact initial report is completely incorrect. There is no memory leak or another bug in the code while supposed change introduces it.
