### ISSUE TITLE
Unnecessary check on NULL before free.

### ISSUE THREAD

**Issue by SiarheiVolkau** [z3APA3A/3proxy#240]
I see tons of constructions like:
`if(param->hostname) myfree(param->hostname);`
across all the codebase.

It's safe to pass NULL pointer to free() function, so resulting code will be just
`myfree(param->hostname);`

Thank you.

**Comment by z3APA3A** [comment]
This behavior is undefined for ANSI C compilers.

**Comment by SiarheiVolkau** [comment]
Seems like you are kidding me.
C89 [draft](http://port70.net/~nsz/c/c89/c89-draft.html#4.10.3.2) explicitly defines this behavior.

I found only 2 arhaic systems which non-compliant to free(NULL): PalmOS and 3BSD.
Are you really still support it?

**Comment by z3APA3A** [comment]
May be you are right. But since it doesn't lead to any negative impact, I see no issue here.
