### ISSUE TITLE
Как исправить баг с загрузкой страниц соц. сетей

### ISSUE THREAD

**Issue by Notturnos** [z3APA3A/3proxy#241]
Проки работает со всем нормально, кроме соц сетей, страницы не полностью грузяться, и не всегда авторизация проходит, не могу зайти в аккаунт. 3proxy 0.8.11 развернут на VPS. 
Пробовал с доменами, но ничего не изменилось. Подскажите, что можно сделать? 
Вот конфиг:

setgid 116
setuid 112
nserver DNS #моего сервера
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
#internal
users $/etc/3proxy/.proxyauth
daemon
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
auth cache strong
proxy -n -p3128 -a

**Comment by z3APA3A** [comment]
Зачем здесь auth cache тем более что authcache не сконфгурирован?
А что в логах?

**Comment by Notturnos** [comment]
Да я брал с инструкции конфиг, вписал как есть, практически. А можете скинуть правильный, плиз )

1521470557.596 PROXY.3128 00000 MYLOGIN MYIP:54052 81.17.30.22:443 1500 28608 0 CONNECT_81.17.30.22:443_HTTP/1.1
1521470564.464 PROXY.3128 00000 MYLOGIN MYIP:54071 87.240.129.71:443 534 3823 0 CONNECT_87.240.129.71:443_HTTP/1.1
1521470564.503 PROXY.3128 00000 MYLOGIN MYIP:54074 87.240.129.71:443 534 3815 0 CONNECT_87.240.129.71:443_HTTP/1.1
1521470564.579 PROXY.3128 00000 MYLOGIN MYIP:54077 87.240.129.71:443 534 3815 0 CONNECT_87.240.129.71:443_HTTP/1.1
1521470621.062 ADMIN.8081 00000 - 0.0.0.0:8081 0.0.0.0:0 0 0 0 Exiting_thread
1521470621.062 PROXY.3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting_thread
1521470621.063 PROXY.3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting_connections_[7772/1290848000]
1521470621.064 ADMIN.8081 00000 - 0.0.0.0:8081 0.0.0.0:0 0 0 0 Accepting_connections_[7772/1290778368]
1521470734.611 PROXY.3128 00000 MYLOGIN MYIP:54080 87.240.129.71:443 1153 4261 0 CONNECT_87.240.129.71:443_HTTP/1.1
1521470809.465 PROXY.3128 00094 MYLOGIN MYIP:54127 172.217.23.164:80 43 517 0 CONNECT_www.google.com:80_HTTP/1.1
1521470815.273 PROXY.3128 00000 MYLOGIN MYIP:54133 81.17.30.22:443 1409 152 0 CONNECT_81.17.30.22:443_HTTP/1.1
1521470817.086 PROXY.3128 00000 MYLOGIN MYIP:54142 81.17.30.22:443 1392 731 0 CONNECT_81.17.30.22:443_HTTP/1.1
1521470828.468 PROXY.3128 00000 MYLOGIN MYIP:54136 81.17.30.22:443 2308 53983 0 CONNECT_81.17.30.22:443_HTTP/1.1
1521470925.377 ADMIN.8081 00000 - 0.0.0.0:8081 0.0.0.0:0 0 0 0 Exiting_thread
1521470925.377 PROXY.3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting_thread
1521470925.378 PROXY.3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting_connections_[7772/1290880768]
1521470925.379 ADMIN.8081 00000 - 0.0.0.0:8081 0.0.0.0:0 0 0 0 Accepting_connections_[7772/1290848000]
1521471148.494 PROXY.3128 00094 MYLOGIN MYIP:54376 74.125.135.147:80 43 517 0 CONNECT_www.google.com:80_HTTP/1.1
1521471201.745 PROXY.3128 00000 MYLOGIN MYIP:54456 87.240.129.72:443 0 0 0 CONNECT_87.240.129.72:443_HTTP/1.1
1521471322.220 PROXY.3128 00000 MYLOGIN MYIP:54433 87.240.129.72:443 3753 283041 0 CONNECT_87.240.129.72:443_HTTP/1.1
1521471327.194 PROXY.3128 00000 MYLOGIN MYIP:54645 87.240.129.72:443 0 0 0 CONNECT_87.240.129.72:443_HTTP/1.1
1521471327.201 PROXY.3128 00000 MYLOGIN MYIP:54642 87.240.129.72:443 1361 23770 0 CONNECT_87.240.129.72:443_HTTP/1.1
1521471332.139 PROXY.3128 00000 MYLOGIN MYIP:54651 87.240.129.72:443 1124 72329 0 CONNECT_87.240.129.72:443_HTTP/1.1

**Comment by z3APA3A** [comment]
daemon надо ставить первой командой
auth cache strong
заменить на
auth strong
в этом куске лога нет каких-либо ошибок, все запросы успешно прошли.

**Comment by Notturnos** [comment]
Да уже поменял, и поэксперементировал с DNS, не помогает ((

**Comment by z3APA3A** [comment]
Так ищи ошибку в логе соответствующую проблемe, описывай конкретный симптом и соответствующую запись в логе. В этом фрагменте никаких ошибок не было. Если в логах ничего нет - значит у тебя не проходит часть соединений до прокси-сервера.

**Comment by z3APA3A** [comment]
Понятия не имею. Например, ты прописал прокси в хроме и при этом настроил на него проксификатор и у тебя получился двойная проксификация запроса, которая работать не будет.

**Comment by Notturnos** [comment]
Нет конечно. :) Я или то или другое включаю )) Сначало пробовал на проксификаторе, не получалось, потом выключил его и попробовал забить в винде, ну через настройки хрома, он не дает окно для ввода логина и пароя, тупо висит, а вот Опера в тот момент была включена и у нее появилось окно для ввода лог.пар.
Сейчас пробую понять, что это вообще было ))

**Comment by z3APA3A** [comment]
Chrome не умеет делать авторизацию через socks, через proxy должен.

**Comment by Notturnos** [comment]
В общем не понял я что делать с proxifire, все  браузеры работают, я почистил куки, работает все четко, а вот проксификатор не в какую... В проксификаторе стоит HTTPS, А в свойствах винды HTTP, может из за этого ... ниче не пойму ...

**Comment by Notturnos** [comment]
Спасибо за советы
