### ISSUE TITLE
DNS resolve в случае если все указанные nserver недоступны?

### ISSUE THREAD

**Issue by AntonOrnatskyi** [z3APA3A/3proxy#242]
Я правильно понимаю, что если ни один из указанных в конфиге серверов не отвечает - дефолтный сервер в системе использоваться не будет?
Если таки правильно понимаю, то может быть есть какой-нибудь способ указать его последним в списке?

**Comment by z3APA3A** [comment]
Да есть - указать его последним в списке.

Только если у вас такие проблемы с резолверами - поставьте локальный резолвер на ту же машину, где стоит прокси и используйте его, зачем так мучаться?

**Comment by AntonOrnatskyi** [comment]
Ну меня интересовала работа 3proxy в качестве легкого engine для backconnect proxy, там на машинках пользователей особенно не развернуться. Думал какой-нибудь способ вроде 
"nameserver default" найдется
Спасибо, что-нибудь придумаю.

**Comment by z3APA3A** [comment]
Так не указывайте nameserver и будет использоваться системный.
