### ISSUE TITLE
[Запрос фичи] Биндинг интерфейса по имени, а не по ip-адресу.

### ISSUE THREAD

**Issue by Andrew-Shtein** [z3APA3A/3proxy#246]
В линуксе было бы очень удобно иметь возможность биндить интерфейс по имени:
external tun0
internal eth1

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
См. -DiINTERFACE, -DeINTERFACE

**Comment by z3APA3A** [comment]
в devel
