### ISSUE TITLE
3proxy работает неправильно, если включен strict aliasing

### ISSUE THREAD

**Issue by h31** [z3APA3A/3proxy#247]
Проявляется как в 0.8.11, так и в devel из гита.

Файл common.c, строка 700 (printf я добавил сам):

```c
printf("1 SASIZE %d sizeof\n", SASIZE(&param->sinsl));
printf("2 SASIZE %d sizeof\n", SASIZE(&param->sinsl));
if(so._bind(param->remsock, (struct sockaddr*)&param->sinsl, (SASIZE(&param->sinsl)))==-1) {
	return 12;
}
```

Ожидаемый вывод для IPv6-адреса:
```
1 SASIZE 28 sizeof
2 SASIZE 28 sizeof
```

Реальный вывод:
```
1 SASIZE 16 sizeof
2 SASIZE 28 sizeof
```

16 - размер для IPv4-адреса, 28 - размер для IPv6-адреса. Проблема в том, что внутри SASIZE происходит каст к sockaddr_in. Из-за включенного по умолчанию strict aliasing-а GCC активирует хитрые оптимизации, которые ломают код. Если вызывать SASIZE больше двух раз, то выдаваемые результаты чередуются каким-то странным образом.

Как проверить, что баг воспроизводится:

1. Запустить ``` src/proxy -eIP:v6:address -a -6 -l```
2. Выполнить ```curl --proxy "http://proxy-address:3128/" -v https://v6.ifconfig.co```

Если баг проявляется, то сервер выдает ```HTTP/1.0 502 Bad Gateway``` и код ошибки 00012 (не удалось выполнить bind).

Собирал и запускал на Debian 9, gcc 6.3.0. На Ubuntu 16.04 с gcc 5.4.0 всё работает (там strict aliasing выключен).

Одно из решений проблемы - добавить `-fno-strict-aliasing` в Makefile. По крайней мере, у меня после этого всё заработало.

**Comment by h31** [comment]
Сейчас попробовал - спасает. Но мне больше нравится вариант с `-fno-strict-aliasing`, потому что `-O` выключает кучу разных оптимизаций, а этот флаг - только одну.

**Comment by z3APA3A** [comment]
Добавил в devel
