### ISSUE TITLE
3proxy постоянно падает

### ISSUE THREAD

**Issue by emergy** [z3APA3A/3proxy#248]
3proxy tiny proxy server 3proxy-0.8.10 (170625190910) собран и установлен на Debian 7. 
Мой конфиг:
```
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536

users "tg:CR:$1$90tVe3$HhkaezB37IDBXgZoDuW.01"
auth strong

log /var/log/3proxy/3proxy.log D
logformat "L[%d/%o/%Y:%H:%M:%S %z] %C %U ""%T"" %E %I %O %N/%R:%r"
rotate 3

external 0.0.0.0
internal 0.0.0.0

flush
allow tg * 91.108.4.0/22
allow tg * 91.108.8.0/22
allow tg * 91.108.12.0/22
allow tg * 91.108.16.0/22
allow tg * 91.108.56.0/22
allow tg * 149.154.160.0/22
allow tg * 149.154.164.0/22
allow tg * 149.154.168.0/22
parent 500 socks5 127.0.0.1 9050
maxconn 384
socks -p9999
```

на 9050 порту висит Tor

torrc:
```root@debian:~# grep -Ev '^#|^ *$' /etc/tor/torrc
ControlPort 9051
AutomapHostsOnResolve 1
ExitPolicy reject *:*
VirtualAddrNetworkIPv4 10.192.0.0/10
DNSPort 5353
SocksPort 0.0.0.0:9050 IsolateDestAddr
TransPort 0.0.0.0:9040
StrictNodes 0
ExitNodes {de}
DataDirectory /var/lib/tor
PidFile /var/run/tor/tor.pid
RunAsDaemon 1
User debian-tor
ControlSocket /var/run/tor/control
ControlSocketsGroupWritable 1
CookieAuthentication 1
CookieAuthFileGroupReadable 1
CookieAuthFile /var/run/tor/control.authcookie
Log notice file /var/log/tor/log
```
```
Tor version 0.2.4.29 (git-b7799afbadf62452).
```
3proxy запускается из под supervisord. Логи supervisord:
```00:30:28 libtorsocks(28943): SOCKS V4 connect rejected:
00:30:28 libtorsocks(28943): SOCKS server refused connection
*** Error in `/opt/3proxy/3proxy': free(): invalid next size (fast): 0x00007f12e0003ab0 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f12ec01c900 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fe830002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fe080002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fe7d4002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f50c8002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f05f0002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f390c0131d0 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f97e4002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007ff0c8002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f9188002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f6834002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007f243c00b660 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fb5a8032b40 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fb1f4002d60 ***
*** Error in `/opt/3proxy/3proxy': double free or corruption (out): 0x00007fba84002d60 ***
```

Оно в принципе работает, но частенько падает. Подозреваю, что когда перестраиваются маршруты в луковице или что-то вроде того...

**Comment by z3APA3A** [comment]
1. Попробуй увеличить stacksize
https://3proxy.ru/faqr.asp#CRASH
и используй devel, там поправлены опции сборки, которые могут стрелять на Debian.

2.

> parent 500 socks5 127.0.0.1 9050

суммарный вес parent должен быть кратен 1000, здесь должно быть 1000 а не 500.


Еще влиять не может, но:

 разрешение DNS здесь вообще не требуется, можно поставить fakeresolve вместо списка DNS если поставить тип родительского прокси socks5+

ACL можно свести в одну строку, перечислив сети через запятую.

**Comment by hhsnake** [comment]
На 2-х машинах стоит одна и та же версия 3proxy-0.9-devel
На ubuntu 1404 всё работает как часы
На CentOS release 6.9 (Final) падает непонятным образом через 1-5 минут после старта, причем работает нормально (клиенты ходят через прокси) и потом процесс пропадает, в логах ничего нету по поводу 3proxy

Как можно отследить причину? Есть ли какая-то опция, чтобы включить режим отладки или другие способы ?

**Comment by hhsnake** [comment]
Дополню, на Centos, до этого стояла сборка 0.6.1-10.el6 из репозитория epel, работало без проблем ))), дня 2 назад начало падать

**Comment by z3APA3A** [comment]
Увеличь stacksize (например stacksize 65536 в начале конфига) 
Попробуй последний devel (собрать с нуля) + напиши что в конфиге.
Если это не поможет - нужен бинарник + core file.

**Comment by z3APA3A** [comment]
@emergy
а у тебя проблема в том, что ты используешь torsocks, torsocks "присовывает" свой код к процессу 3proxy, но у 3proxy очень специфические внутренние механизмы (много потоков с маленькими стеками). Не надо использовать torsocks с 3proxy, он ему не нужен, 3proxy умеет сам подключаться куда надо.

**Comment by z3APA3A** [comment]
@hhsnake
3proxy именно крешится как процесс или просто перестает работать?

**Comment by hhsnake** [comment]
Крашится процесс

**Comment by z3APA3A** [comment]
В конфиге есть где-нибудь -l (указание лог-файла через аргумент, а не командой log)?

**Comment by hhsnake** [comment]
проверил, нету, есть строка из стандартного cfg
logformat "L%d-%m-%Y %H:%M:%S %z %N.%p %E %U %C:%c %R:%r %O %I %h %T"

**Comment by z3APA3A** [comment]
stacksize увеличил? Последний devel попробовал?

**Comment by z3APA3A** [comment]
Да, располжение исполняемых файлов только что поправил, сейчас поправил и скрипты установки.

**Comment by hhsnake** [comment]
Понятно, в чем дело. Процесс убивает хостинг-провайдер.

**Comment by z3APA3A** [comment]
Сейчас все бросили брать хостинг на Арубе, дают вполне подходящий VPS в cz за 1 евро месяц.
