### ISSUE TITLE
Анализатор логов WrSpy

### ISSUE THREAD

**Issue by NiKoLaNN** [z3APA3A/3proxy#249]
Огромнейшая просьба! Разместите на сайте в разделе "Скачать" или в вики программу WrSpy (версия 1.65 или новее).
Все ссылки на сторонние ресурсы не работают. 

Доступна только версия 1.3.5

**Comment by z3APA3A** [comment]
Ссылка есть здесь:
https://3proxy.ru/plugins/
но wrspy.ru не работает.

**Comment by NiKoLaNN** [comment]
Да, я именно поэтому попросил разместить, если есть конечно...

**Comment by z3APA3A** [comment]
Нет, я не связан с разработчиками. Но, насколько я вижу, домен недавно проплачен, т.е. есть шанс что и хостинг в ближайшее время вернется.

**Comment by RussIvan** [comment]
**2 NiKoLaNN **
Воспользуйтесь веб-архивом, я оттуда скачал, декабрь 17-го 
http://web.archive.org/web/20171220101448/http://www.wrspy.ru/
