### ISSUE TITLE
Запрет доступа на сайты в .рф

### ISSUE THREAD

**Issue by pmlkaovs** [z3APA3A/3proxy#25]
Здравствуйте.
Хочу поблагодарить Вас за столь прекрасный 3proxy!
Вопрос: есть ли возможность в 3proxy блокировать доступ на сайты в доменной зоне .рф? Если да, то как это сделать? Сайты в латинице блокируются замечательно! А в кирилице - не получается.
Спасибо.

**Comment by z3APA3A** [comment]
Используйте имена доменов в punycode, например *.xn--p1ai для *.рф

**Comment by z3APA3A** [comment]
https://www.punycoder.com/

**Comment by slonopot** [comment]
Приветствую!

Возникла проблема с пуникод-доменами. Блокировка через deny не работает.

Конфиг на примере дом.рф:

`users te:CL:st

log

auth strong

deny * * *.xn--d1aqf.xn--p1ai
deny * * xn--d1aqf.xn--p1ai
deny * * google.com
deny * * *.google.com
allow *

proxy -n -a -p1234 -i127.0.0.1 `

Лог:

`210414190735.644 1234 00000 te 127.0.0.1:50440 195.238.250.20:443 788 23976 0 CONNECT xn--d1aqf.xn--p1ai:443 HTTP/1.0
210414190738.800 1234 00001 te 127.0.0.1:50445 0.0.0.0:0 0 0 0 CONNECT google.com:443 HTTP/1.0`

При попытке запросить дом.рф соединение устанавливается, google.com закономерно блокируются.

Буду благодарен, если порекомендуете решение.
