### ISSUE TITLE
3proxy parent 127.0.0.1

### ISSUE THREAD

**Issue by mesb1** [z3APA3A/3proxy#251]
Приветствую.

Сервер с 1 интерфейсом (ну и плюс локалхост конечно).
3proxy 0.6.1 из epel.
На машине стоит tor и настроен дефолтно из коробки как был.
При старте слушает 127.0.0.1 9050 - если перевесить его на внешний ip - прописывание в устройстве как сокса - всё работает.
Решил для аутентификации перед ним поставить 3proxy.
Невзлетает совсем.

Основной конфиг 3proxy:
Неработает.

`setgid 500`
`setuid 500`
`nserver 77.88.8.2`
`nserver 8.8.8.8`
`nscache 65536`
`timeouts 1 5 30 60 180 1800 15 60`
`log /var/log/3proxy/3proxy.log D`
`logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"`
`users $/etc/3proxy.auth`
`daemon`
`auth cache strong`
`socks -p8881`
`allow *`
`parent 1000 socks5 127.0.0.1 9050`

Пробовал добавлять также:
`internal 0.0.0.0`
`external 127.0.0.1`
`fakeresolve`
`parent 1000 socks5+ 127.0.0.1 9050`
`parent 1000 socks5+ 0.0.0.0 9050`

Неработает.

По отдельности, не как парент, 3прокси работает нормально(если просто убрать строчки allow и parent).
Перевешивание тор с его сокс на внешний айпи с локахоста показывает что он тоже пашет нормально.

Прошу подсказки что я не так делаю.

**Comment by z3APA3A** [comment]
3proxy 0.6.1 устарел на много лет.
Нужная тебе конфигурация есть в этом комментарии:
https://github.com/z3APA3A/3proxy/issues/245#issuecomment-381645295
