### ISSUE TITLE
Внезапно заканчивается трафик

### ISSUE THREAD

**Issue by zavadski** [z3APA3A/3proxy#252]
Какие то странности подсчёта траффика - внезапно, обычно через день после удаления/обнуления файла счётчика, у пользователей массово (но не у всех!) возникает ограничение трафика.
Сервер 0.8.11 работает на ubuntu server.

Конфиг, что касается трафика:
counter /var/log/3proxy/traf/3proxy.3cf D /var/log/3proxy/traf/traf
nocountin * * 71.21.1.1,192.168.6.0/23,*.yandex.ru,*.yandex.net
countin "1/admin" D 1024 admin
countin "2/zavadskiy" D 1024 zavadskiy
countin "10/abdrahmanov" M 5120 abdrahmanov
countin "11/aitova" M 5120 aitova
countin "12/artyuhova" M 5120 artyuhova

Файл 3proxy.3cf создан вчера, он во вложении (загрузился только в следующем сообщении).
Сегодня получили ограничение трафика zavadskiy и artyuhova.
Файл ежедневного отчёта:
00001 00000000000000000000 #admin
00002 00000000000240953936 #zavadskiy
00010 00000000000000000000 #abdrahmanov
00011 00000000000004198576 #aitova
00012 00000000001633443855 #artyuhova

**Comment by zavadski** [comment]
[3proxy.zip](https://github.com/z3APA3A/3proxy/files/1927733/3proxy.zip)

**Comment by z3APA3A** [comment]
А что значит "удаление/обнуление файла счетчика"?

**Comment by zavadski** [comment]
Останавливаю службу и удаляю файл

**Comment by z3APA3A** [comment]
Скриптом?

**Comment by zavadski** [comment]
Нет, вручную...
Ещё недавно прокси работал на вин-сервере, на более старой версии 3proxy - всё было нормально. Позавчера развернул на убунте - и началась ерунда. Вроде и подсчёт трафика не особо нужен, но перестало же работать, решил вот сообщить :)

**Comment by z3APA3A** [comment]
Скорей всего, ты удаляешь файл при еще работающем прокси, 'service blablabla stop' обычно только отправляет сигнал на завершение, но не ждет завершения процесса, а прокси останавливается не мгновенно. В Windows 'net stop blablabla' завершается только когда служба переходит в соответствующее состояние.

**Comment by zavadski** [comment]
Да вроде ps ax | grep 3proxy ничего не отображал ;)

**Comment by zavadski** [comment]
Кстати, сейчас я не обнулял файл счётчика (который во вложении), просто закоментировал строку counter!
Разрешил его использование - и почти все получили ошибку 10!

**Comment by zavadski** [comment]
![3proxy-err](https://user-images.githubusercontent.com/38526037/38988112-8ab0722c-43c1-11e8-834a-97016ae2999f.png)

**Comment by z3APA3A** [comment]
Файл счетчиков используется для сохранения состояния, при этом сами счетчики функционируют независимо от файла. Отключение файла счетчиков не зануляет счетчики внутри файла и не останавливает подсчет трафика. Отключение и включение файла на ходу без остановки прокси дает непредсказуемый результат. Изменение номеров счетчиков без удаления файла - аналогично.

**Comment by zavadski** [comment]
Да не делаю я ничего перечисленного. Давайте проведём опыт - я выключаю 3proxy, убеждаюсь, что процесс отсутствует, удаляю файл счётчиков и включаю 3proxy с вышеуказаным конфигом?
