### ISSUE TITLE
How to run 3proxy on windows 10 IOT for raspberry pi-3 B model 

### ISSUE THREAD

**Issue by aarishcs2** [z3APA3A/3proxy#253]
Need help with getting this software running on a pi3 b model with windows 10 IOT so we can configure mobile proxies

**Comment by aarishcs2** [comment]
Okay .and facing once issue. We have usb 4g dongles. the pi is not detecting them in Windows 10 iot . Any idea who to fix them and start the us tethering ?

**Comment by z3APA3A** [comment]
I've added ARM64 Windows build to devel downloads
https://3proxy.ru/current/3proxy-0.9-devel-arm64.zip
but never had a chance to test it.

As for dongle, you probably need drivers. If dongle vendor doesn't provide drivers for Windows ARM64, try to identify the dongle's chipset and obtain a driver from chipset manufacture.

**Comment by aarishcs2** [comment]
I am configuring 3 proxy on Linux also but we are facing this issue aarish tinwala:
on Linux 1 dongle 2 proxies ipv4/ipv6 is working fine but the 2nd dongle is not working

Do you have a config for multiple proxies running on Linux? Or config file which can solve the routing issue when 2 usb modems are connected

**Comment by z3APA3A** [comment]
3proxy is application level service, it doesn't perform routing, you must configure routing on system level. 3proxy can bind to IP or to interface though.

**Comment by aarishcs2** [comment]
have you been able to configure anything near to it yet ? also i am facing issue in windows it is showing a trojan odbc32.dll . do you have any way to fix that part ?
