### ISSUE TITLE
Статистика в веб-интерфейсе и просто статистика подключений

### ISSUE THREAD

**Issue by pkMIXER** [z3APA3A/3proxy#255]
Добрый день! Подскажите, как можно увидеть статистику по подключенным пользователям, их трафику и потреблению? Нигде в мануале такого не нашёл, есть ли у 3proxy такой функционал?

**Comment by z3APA3A** [comment]
Да, см. службу 'admin' и команды подсчета трафика (counters, countin/countout/nocountin/nocountout).
