### ISSUE TITLE
Warning: too many connected clients

### ISSUE THREAD

**Issue by tazhate** [z3APA3A/3proxy#256]
`3proxy.log.2018.04.23:1524505251.612 SOCKS.3129 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Warning:_too_many_connected_clients_(100/100)`

How do i fix it? :\

I thought i can fix it with noconnlim, but it doesnt helped.

see:
```
Starting 3Proxy
Unknown command: 'noconnlim' line 48
```

my part of config:

```
allow user * *
nobandlimin * * * *
noconnlim * * user 
flush
maxconn 18024
socks -n -p3129 -a

```

**Comment by z3APA3A** [comment]
Use 'maxconn' to set per-service connection limit.

**Comment by xo2l** [comment]
Такая же ошибка
0.0.0.0:0 0.0.0.0:0 0 0 0 Warning: too many connected clients (100/100)
Хотя в cfg

auth none
log
proxy
maxconn 18024

Где то еще прописать надо?
