### ISSUE TITLE
SSLPlugin: no OPENSSL_Applink

### ISSUE THREAD

**Issue by michaelbokov** [z3APA3A/3proxy#259]
Добрый день. при попытке запустить 3proxy плагин ссл выходит ошибка OPENSSL_Uplink(000007FEE661B000,08): no OPENSSL_Applink
конфиг выглядит так:

auth none
plugin d:\bin64\SSLPlugin.dll ssl_plugin
ssl_certcache d:\bin64\
ssl_mitm
proxy -p3221
tcppm 44322 site.com 443

версия 3proxy-0.9-devel-x64-180423023321
нужночтобы соединения по https проходили. но пока даже не запускается

**Comment by z3APA3A** [comment]
Дистрибутив брал с сайта или сам собирал, DLLки OpenSSL какие используются?

**Comment by michaelbokov** [comment]
Дистрибутив с сайта, ключи шли с дистрибутивом. дополнительнос OpenSSL не ставил

**Comment by z3APA3A** [comment]
Попробуй с этим плугином, останется проблема с запуском?
https://cloud.mail.ru/public/2iQv/xjxk4DVpy

**Comment by michaelbokov** [comment]
Да, проблема осталась
OPENSSL_Uplink(000007FEE81AB000,08): no OPENSSL_Applink

**Comment by michaelbokov** [comment]
Что делать?

**Comment by z3APA3A** [comment]
Еще раз возьми отсюда
https://cloud.mail.ru/public/2iQv/xjxk4DVpy
сделал статическую сборку, вроде бы запускается. Или используй пока 0.8.11, там старый OpenSSL.

Все текущие ветки OpenSSL (1.0, 1.1, 1.2) имеют проблемы сборки с последними MSVC, причем у каждой версии разные.

**Comment by michaelbokov** [comment]
0.8.11 запустилась корректно.

**Comment by z3APA3A** [comment]
Поправил в devel.
А что у тебя лежит в d:\bin64\ ?

**Comment by z3APA3A** [comment]
И да, mitm будет работать только на proxy

**Comment by michaelbokov** [comment]
d:\bin64

_odbc32.dll
3proxy.cfg
3proxy.exe
3proxy.key
3proxy.pem
dighosts.exe
FilePlugin.dll
libeay32.dll
mycrypt.exe
PCREPlugin.dll
server.key
ssleay32.dll
SSLPlugin.dll
StringsPlugin.dll
TrafficPlugin.dll
utf8tocp1251.dll
WindowsAuthentication.dll

odbc32.dll переименовал, т.к. на него при запуске ругалось
![default](https://user-images.githubusercontent.com/26480836/39345555-c87c12e2-49f1-11e8-9124-dc482814047c.png)

**Comment by michaelbokov** [comment]
а, я как раз mitm на портмапинге пытаюсь использовать

**Comment by z3APA3A** [comment]
Да, это какое-то время назад лежал дистрибутив 0.8.12 с тестовой DLL'кой, в ней ничего страшного не было, просто выводила MessageBox на каждый вызов из odbc32. сейчас должен нормальный дистрибутив лежать.
