### ISSUE TITLE
Segfault на Ubuntu 14.04 

### ISSUE THREAD

**Issue by ariutk** [z3APA3A/3proxy#26]
Собирается без ошибок, но не запускается. Валится с segfault

**Comment by ariutk** [comment]
root@test:/usr/src/3proxy/src# gdb ./3proxy
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./3proxy...done.
(gdb) run 3proxy.cfg
Starting program: /usr/src/3proxy/src/3proxy 3proxy.cfg
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7fed700 (LWP 6845)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fed700 (LWP 6845)]
0x00007ffff767baea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff767baea in strlen () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff767b82e in strdup () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x0000000000403245 in srvinit (srv=srv@entry=0x7ffff7fec7c0, param=param@entry=0x7ffff7fec930) at proxymain.c:668
#3  0x0000000000404453 in mainfunc (argc=1, argv=0x64d2b0) at proxymain.c:182
#4  0x0000000000408c8f in startsrv (data=<optimized out>) at conf.c:65
#5  0x00007ffff79c0182 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007ffff76ed47d in clone () from /lib/x86_64-linux-gnu/libc.so.6
(gdb)

**Comment by z3APA3A** [comment]
О какой версии речь? О текущей из git?

**Comment by ariutk** [comment]
Да. https://github.com/z3APA3A/3proxy/commit/c263428cf67576884673c7391f90eb6d4e315dfc
Эта не валится https://github.com/z3APA3A/3proxy/commit/fcbb000b0e505bdab7d07a8b2fc763d2cc338178

**Comment by z3APA3A** [comment]
Поправил в a4e0f1fb9a311a85c55efa4cfcee77d823ec2e15  - проверь.

**Comment by ariutk** [comment]
Да, теперь все ок. Спасибо!

**Comment by z3APA3A** [comment]
fixed with a4e0f1fb9a311a85c55efa4cfcee77d823ec2e15
