### ISSUE TITLE
3proxy через 5-10 минут перестает принимать соединения

### ISSUE THREAD

**Issue by mrPsycho** [z3APA3A/3proxy#262]
здравствуйте,

пробую настроить ваше ПО, но есть что-то непонятное - отваливается через небольшой промежуток времени :( 

конфиг: 

    nscache 65536
    nserver 1.1.1.1 
    nserver 8.8.4.4
    config /conf/3proxy.cfg
    monitor /conf/3proxy.cfg
    log /logs/3proxy-%y%m%d.log D
    rotate 10
    counter /count/3proxy.3cf
    users $/conf/passwd
    include /conf/counters
    include /conf/bandlimiters
    auth strong
    deny * * 127.0.0.1
    allow *
    maxconn 1000
    proxy -n
    socks
    flush
    allow admin elegion
    admin -p8080

пользователей всего два. и через небольшой промежуток времени - демон работает, 
в логи сыпется вот это:

root@vps1052116:/etc/3proxy/conf# tail -n 100 /var/log/3proxy/3proxy-180426.log
180427065459.812 1080 00100 - 82.140.19.25:27952 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065459.561 1080 00004 - 82.140.19.25:25724 173.194.222.200:443 0 0 0 CONNECT 173.194.222.200:443
180427065459.869 1080 00100 - 82.140.19.25:17939 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065459.892 1080 00100 - 82.140.19.25:37347 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065459.945 1080 00100 - 82.140.19.25:64260 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065500.561 1080 00004 - 82.140.19.25:52019 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065500.916 1080 00100 - 82.140.19.25:29227 0.0.0.1:0 0 0 0 CONNECT client.dropbox.com:0
180427065500.986 1080 00100 - 82.140.19.25:54085 0.0.0.1:0 0 0 0 CONNECT client.dropbox.com:0
180427065501.564 1080 00004 - 82.140.19.25:8219 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065501.801 1080 00004 - 82.140.19.25:29046 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065501.868 1080 00100 - 82.140.19.25:47813 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065501.852 1080 00004 - 82.140.19.25:27605 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065501.940 1080 00100 - 82.140.19.25:18295 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065503.615 1080 00004 - 82.140.19.25:56764 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065503.796 1080 00004 - 82.140.19.25:51230 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065503.565 1080 00004 - 82.140.19.25:30431 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065503.615 1080 00004 - 82.140.19.25:13555 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065503.848 1080 00004 - 82.140.19.25:60792 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065504.055 1080 00004 - 82.140.19.25:22647 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065504.001 1080 00004 - 82.140.19.25:40731 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065504.048 1080 00005 elegion 82.140.19.25:54359 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065504.564 1080 00004 - 82.140.19.25:35057 173.194.222.200:443 0 0 0 CONNECT 173.194.222.200:443
180427065505.560 1080 00004 - 82.140.19.25:58408 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065506.564 1080 00004 - 82.140.19.25:49559 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065507.170 1080 00004 - 82.140.19.25:45140 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065507.114 1080 00004 - 82.140.19.25:11506 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065508.614 1080 00004 - 82.140.19.25:55955 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065508.564 1080 00004 - 82.140.19.25:44743 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065508.616 1080 00004 - 82.140.19.25:57425 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065508.618 1080 00004 - 82.140.19.25:20295 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065509.450 1080 00005 admin 82.140.19.25:29199 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065509.978 1080 00004 - 82.140.19.25:29677 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065509.926 1080 00004 - 82.140.19.25:43929 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065511.560 1080 00004 - 82.140.19.25:50666 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065512.561 1080 00004 - 82.140.19.25:32232 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065512.872 1080 00100 - 82.140.19.25:41585 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065512.947 1080 00100 - 82.140.19.25:31391 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065514.192 1080 00005 elegion 82.140.19.25:48043 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065513.813 1080 00004 - 82.140.19.25:58114 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065513.865 1080 00004 - 82.140.19.25:28960 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065514.561 1080 00004 - 82.140.19.25:64572 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065514.612 1080 00004 - 82.140.19.25:30125 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065514.612 1080 00004 - 82.140.19.25:4518 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065515.002 1080 00004 - 82.140.19.25:47527 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065515.057 1080 00004 - 82.140.19.25:54685 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065516.564 1080 00004 - 82.140.19.25:5807 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065516.873 1080 00100 - 82.140.19.25:42201 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065516.876 1080 00004 - 82.140.19.25:40038 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065516.824 1080 00004 - 82.140.19.25:42753 54.209.96.233:443 0 0 0 CONNECT 54.209.96.233:443
180427065516.948 1080 00100 - 82.140.19.25:47422 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065517.558 1080 00004 - 82.140.19.25:57406 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065519.620 1080 00004 - 82.140.19.25:30047 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065519.561 1080 00004 - 82.140.19.25:15237 173.194.222.200:443 0 0 0 CONNECT 173.194.222.200:443
180427065519.568 1080 00004 - 82.140.19.25:33997 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065519.588 1080 00005 admin 82.140.19.25:49713 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065519.621 1080 00004 - 82.140.19.25:2966 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065519.622 1080 00004 - 82.140.19.25:19897 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065519.627 1080 00004 - 82.140.19.25:9155 173.194.222.196:443 0 0 0 CONNECT 173.194.222.196:443
180427065520.951 1080 00100 - 82.140.19.25:36597 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065520.984 1080 00004 - 82.140.19.25:15753 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065520.872 1080 00100 - 82.140.19.25:38552 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065521.049 1080 00004 - 82.140.19.25:16003 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065521.957 1080 00100 - 82.140.19.25:42376 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065522.263 1080 00004 - 82.140.19.25:14519 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065522.315 1080 00004 - 82.140.19.25:48745 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065522.565 1080 00004 - 82.140.19.25:21900 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065522.636 1080 00100 elegion 82.140.19.25:21911 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065522.737 1080 00100 elegion 82.140.19.25:12550 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065522.841 1080 00100 elegion 82.140.19.25:15946 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065523.561 1080 00004 - 82.140.19.25:7979 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065524.342 1080 00005 elegion 82.140.19.25:2042 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065524.572 1080 00004 - 82.140.19.25:12343 173.194.222.200:443 0 0 0 CONNECT 173.194.222.200:443
180427065525.180 1080 00004 - 82.140.19.25:6115 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065525.436 1080 00004 - 82.140.19.25:43709 64.233.162.188:5228 0 0 0 CONNECT 64.233.162.188:5228
180427065525.125 1080 00004 - 82.140.19.25:22549 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065525.179 1080 00004 - 82.140.19.25:3331 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065525.232 1080 00004 - 82.140.19.25:5968 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065525.562 1080 00004 - 82.140.19.25:14685 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065525.611 1080 00004 - 82.140.19.25:15444 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065525.614 1080 00004 - 82.140.19.25:39529 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065526.789 1080 00100 elegion 82.140.19.25:5462 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065526.670 1080 00100 elegion 82.140.19.25:58355 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065526.907 1080 00100 elegion 82.140.19.25:32264 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065527.563 1080 00004 - 82.140.19.25:12773 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065528.739 1080 00004 - 82.140.19.25:50806 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065528.563 1080 00004 - 82.140.19.25:60322 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065528.673 1080 00004 - 82.140.19.25:15938 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065529.729 1080 00005 admin 82.140.19.25:58185 149.154.167.99:443 0 0 0 CONNECT 149.154.167.99:443
180427065530.316 1080 00004 - 82.140.19.25:2096 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065530.262 1080 00004 - 82.140.19.25:12071 54.173.251.77:443 0 0 0 CONNECT 54.173.251.77:443
180427065530.567 1080 00100 - 82.140.19.25:24133 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065530.611 1080 00004 - 82.140.19.25:44483 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065530.490 1080 00100 - 82.140.19.25:17933 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065530.562 1080 00004 - 82.140.19.25:47274 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065530.612 1080 00004 - 82.140.19.25:39163 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065530.613 1080 00004 - 82.140.19.25:56516 173.194.222.94:443 0 0 0 CONNECT 173.194.222.94:443
180427065530.645 1080 00100 - 82.140.19.25:62555 0.0.0.0:0 0 0 0 CONNECT 0.0.0.0:0
180427065531.369 1080 00004 - 82.140.19.25:57923 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065531.311 1080 00004 - 82.140.19.25:62567 34.192.22.91:443 0 0 0 CONNECT 34.192.22.91:443
180427065531.564 1080 00004 - 82.140.19.25:33120 162.247.242.19:443 0 0 0 CONNECT 162.247.242.19:443

что не так? сервер простаивает, те la около 0, 
iftop показывет тоже мизерные значения :(

**Comment by mrPsycho** [comment]
система - ubuntu 16.04
собрано из devel

**Comment by mrPsycho** [comment]
проверяю так, например:

     users-iMac:~ mrpsycho$ curl --verbose --socks5 185.34.52.116:1080 --proxy-user elegion:pass123 https://t.me
    * Rebuilt URL to: https://t.me/
    *   Trying 185.34.52.116...
    * TCP_NODELAY set
    * SOCKS5 communication to t.me:443
    * SOCKS5 connect to IPv4 149.154.167.99 (locally resolved)
    * Can't complete SOCKS5 connection to 0000:0000:0000:0000:0000:0000:0000:0000:0. (2)
    * Closing connection 0
    curl: (7) Can't complete SOCKS5 connection to 0000:0000:0000:0000:0000:0000:0000:0000:0. (2)


после /etc/init.d/3proxy restart:
    users-iMac:~ mrpsycho$ curl --verbose --socks5 rkn.e-legion.com:1080 --proxy-user elegion:pass123 https://t.me
    * Rebuilt URL to: https://t.me/
    *   Trying 185.34.52.116...
    * TCP_NODELAY set
    * SOCKS5 communication to t.me:443
    * SOCKS5 connect to IPv4 149.154.167.99 (locally resolved)
    * SOCKS5 request granted.
    * Connected to rkn.e-legion.com (185.34.52.116) port 1080 (#0)
    * ALPN, offering h2
    * ALPN, offering http/1.1
    * Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
    * successfully set certificate verify locations:
    *   CAfile: /etc/ssl/cert.pem
итд.

**Comment by mrPsycho** [comment]
присмотревшись, я увидел в консоли это:

    root@vps1052116:/etc/3proxy/conf# Invalid IP, IP range or CIDR, line 14
    Unable to parse ACL entry, line 14
    Command: 'allow' failed with code 1, line 14
    Command: 'include' failed with code 14, line 14

**Comment by mrPsycho** [comment]
что это означает?

**Comment by z3APA3A** [comment]
Что ты или смотришь не в тот конфиг или запускаешь 3proxy не тем способом.
убей все процессы 3proxy
killall -9 3proxy
запусти прокси через 
service 3proxy start
посмотри в 
ps ax | grep 3proxy
с каким файлом конфига он запускается и что у тебя в этом конфиге.

Конфиг который ты привел предназначен для запуска из chroot, напрямую 3proxy с ним запускать нельзя.

**Comment by z3APA3A** [comment]
Запускать надо с конфигом который лежит в /etc/3proxy из-под рута.
Если хочешь запускать руками из-под юзера  - делай отдельный конфиг и запускай 3proxy с этим конфигм.

**Comment by mrPsycho** [comment]
запускал я так:

    root@vps1052116:/etc/3proxy# /etc/init.d/3proxy start
    Starting 3Proxy

    root@vps1052116:/etc/3proxy# ps aux | grep pro
    proxy    29829  0.0  0.3 537172  3460 ?        Ssl  14:43   0:00 /bin/3proxy /etc/3proxy/3proxy.cfg
    root     29848  0.0  0.0  14152   976 pts/4    S+   14:43   0:00 grep --color=auto pro

`service` и `systemctl` не запускает демон:
    
    root@vps1052116:/etc/3proxy# service 3proxy start && ps aux | grep 3pro
    root     30149  0.0  0.0  14152   976 pts/4    S+   14:44   0:00 grep --color=auto 3pro
    root@vps1052116:/etc/3proxy# systemctl start 3proxy && ps aux | grep 3pro
    root     30153  0.0  0.0  14152   972 pts/4    S+   14:44   0:00 grep --color=auto 3pro
    root@vps1052116:/etc/3proxy# systemctl status 3proxy 
    ● 3proxy.service - LSB: Start/stop 3proxy
       Loaded: loaded (/etc/init.d/3proxy; bad; vendor preset: enabled)
       Active: active (exited) since Fri 2018-04-27 01:14:38 EEST; 13h ago
       Docs: man:systemd-sysv-generator(8)

    Apr 27 01:14:38 vps1052116.vpsnet.lt systemd[1]: Starting LSB: Start/stop 3proxy...
    Apr 27 01:14:38 vps1052116.vpsnet.lt 3proxy[9886]: Starting 3Proxy
    Apr 27 01:14:38 vps1052116.vpsnet.lt systemd[1]: Started LSB: Start/stop 3proxy.
    Apr 27 01:21:23 vps1052116.vpsnet.lt 3proxy[9886]: Invalid IP, IP range or CIDR, line 9
    Apr 27 01:21:23 vps1052116.vpsnet.lt 3proxy[9886]: Unable to parse ACL entry, line 9
    Apr 27 01:21:23 vps1052116.vpsnet.lt 3proxy[9886]: Command: 'allow' failed with code 1, line 9
    Apr 27 14:41:29 vps1052116.vpsnet.lt systemd[1]: Started LSB: Start/stop 3proxy.
    Apr 27 14:41:57 vps1052116.vpsnet.lt systemd[1]: Started LSB: Start/stop 3proxy.
    Apr 27 14:44:08 vps1052116.vpsnet.lt systemd[1]: Started LSB: Start/stop 3proxy.
    Apr 27 14:44:22 vps1052116.vpsnet.lt systemd[1]: Started LSB: Start/stop 3proxy.

**Comment by mrPsycho** [comment]
но идею я понял: поправил пути в конфиге.

всеравно что-то падает:
    root@vps1052116:/etc/3proxy/conf# /etc/init.d/3proxy start
    Starting 3Proxy

    root@vps1052116:/etc/3proxy/conf# ps aux | grep 3pro
    root     30280  0.1  0.3 537360  3516 ?        Ssl  14:49   0:00 /bin/3proxy /etc/3proxy/3proxy.cfg
    root     30348  0.0  0.0  14152   972 pts/4    S+   14:49   0:00 grep --color=auto 3pro
    root@vps1052116:/etc/3proxy/conf# Invalid IP, IP range or CIDR, line 14
    Unable to parse ACL entry, line 14
    Command: 'allow' failed with code 1, line 14
    Command: 'include' failed with code 14, line 14

    root@vps1052116:/etc/3proxy/conf# cat /etc/3proxy/3proxy.cfg
    #!/bin/3proxy
    daemon
    pidfile /var/run/3proxy/3proxy.pid
    #chroot /usr/local/3proxy proxy proxy
    include /etc/3proxy/conf/3proxy.cfg
 
    root@vps1052116:/etc/3proxy/conf# cat /etc/3proxy/conf/3proxy.cfg
    nscache 65536
    nserver 1.1.1.1
    nserver 8.8.4.4
    config /etc/3proxy/conf/3proxy.cfg
    monitor /etc/3proxy/conf/3proxy.cfg
    log /var/log/3proxy/3proxy-%y%m%d.log H
    rotate 10
    counter /etc/3proxy/conf/3proxy.3cf
    users $/etc/3proxy/conf/passwd 
    include /etc/3proxy/conf/counters
    include /etc/3proxy/conf/bandlimiters
    auth strong
    deny * * 127.0.0.1
    allow *
    proxy -n
    socks
    flush
    allow admin elegion
    admin -p8080

**Comment by z3APA3A** [comment]
Давай целиком содержание /etc/3proxy и /usr/local/3proxy, можно на 3proxy@3proxy.ru, логи можешь занулить, пароли на что-нибудь поменять.

**Comment by z3APA3A** [comment]
Так а кто закомментировал chroot? В /etc/3proxy/conf/3proxy.cfg все пути относительно chroot, если хочешь без chroot - меняй пути на абсолютные.

**Comment by z3APA3A** [comment]
Там не /etc/3proxy/ а /usr/local/3proxy префикс у chroot

**Comment by z3APA3A** [comment]
> allow admin elegion
elegion в данном случае стоит вместо IP-адреса. Должно быть
allow admin,elegion

**Comment by z3APA3A** [comment]
и убедись что все файлы указанные в users и include доступны эккаунту прокси

**Comment by mrPsycho** [comment]
окей. до меня дошло, кажется.
спасибо!
