### ISSUE TITLE
Проблема производительности связки connect back

### ISSUE THREAD

**Issue by flyrider** [z3APA3A/3proxy#263]
Добрый день!

Oчень давно используем 3proxy в своих продуктивах, но столкнулись со странным эффектом в производительности на связке connect-back и никак не можем разобраться.

При превышении ESTABLISHED соединений на прокси connect-back свыше 100 отмечается существенное увеличение времени ответа от прокси:
```
srv4007 ~$ netstat -an | grep EST | grep 4007 | wc -l
542
srv4007 ~$ netstat -an | grep EST | grep 4008 | wc -l
2
```
```
srv4007 ~$ time curl -x xxx:123@srv4007:4008 http://ya.ru/ -s

real	0m0.230s
user	0m0.008s
sys	0m0.000s
```
```
srv4007 ~$ time curl -x xxx:123@srv4007:4007 http://ya.ru/ -s

real	0m14.469s
user	0m0.008s
sys	0m0.004s
```
Конфигурационные файлы:

4007

```
daemon
log /log/proxy.log
timeouts 8 40 240 480 720 1800 60 60
maxconn 20000
auth iponly
allow * * *
tcppm -R0.0.0.0:3007 4007 0.0.0.0 4007
```
4008

```
daemon
log /log/proxy.log
timeouts 8 40 240 480 720 1800 60 60
maxconn 20000
auth iponly
allow * * *
tcppm -R0.0.0.0:3008 4008 0.0.0.0 4008
```
3007

```
daemon
timeouts 8 40 240 480 720 1800 60 60
log /log/proxy.log
maxconn 20000
users xxx:CL:123
auth strong
allow xxx *
proxy -rsrv1.prxdomain.com:3007
```
3008

```
daemon
timeouts 8 40 240 480 720 1800 60 60
log /log/proxy.log
maxconn 20000
users xxx:CL:123
auth strong
allow xxx *
proxy -rsrv1.prxdomain.com:3008
```

В логах на инициаторе петли "3007" записи типа:
```
180427202631.692 3128 00000 xxx 31.201.143.105:3007 77.240.29.19:443 679 5336 0 CONNECT 7.240.29.19:443 HTTP/1.0
```
В логах на srv4007 все аналогично. Видно что запрос уходит, доходит, но как уменьшить время ответа?

Между srv4007 и 3007 пинг не превышает 20ms и не растет при нагрузке на прокси.

sysctl на srv4007
```
srv4007 ~$ sysctl -p
net.ipv4.tcp_keepalive_time = 320
net.ipv4.tcp_keepalive_intvl = 300
net.ipv4.tcp_fin_timeout = 300
net.netfilter.nf_conntrack_generic_timeout = 320
net.netfilter.nf_conntrack_tcp_timeout_established = 1200
net.netfilter.nf_conntrack_max = 1000048576
net.netfilter.nf_conntrack_max = 1000048576
net.core.rmem_max = 1677721600
net.core.rmem_default = 167772160
net.core.wmem_max = 1677721600
net.core.wmem_default = 167772160
net.ipv4.tcp_rmem = 1024000 8738000 1677721600
net.ipv4.tcp_wmem = 1024000 8738000 1677721600
net.ipv4.tcp_mem = 1024000 8738000 1677721600
net.ipv4.udp_mem = 1024000 8738000 1677721600
```
limits на srv4007 (для root, 3proxy запускается под root) 
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 9860
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 204708
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

**Comment by z3APA3A** [comment]
Connect-back клиент устанавливает одно соединение за раз в блокирующем цикле, при большой нагрузке или когда одновременно приходит несколько запросов, частота соединений просто недостаточна и connect-back сервер долго ожидает следующего. Иначе клиент зафлудит сервер коннектами. В случае, когда коннекты нужны чаще, достаточно запускать несколько connect-back клиентов, т.е. просто продублировать строчку несколько раз, например

proxy -rsrv1.prxdomain.com:3007
proxy -rsrv1.prxdomain.com:3007
proxy -rsrv1.prxdomain.com:3007

тогда к серверу будет поддерживаться 3 "готовых к работе" коннекта.

P.S. но под высокие нагрузки он в любом случае не заточен

**Comment by flyrider** [comment]
Спасибо, попробовали. 
Действительно имеет место корреляция улучшения ответа с увеличением кол-ва строк клиентов. При 100 строках более менее стабильно, но при 300 уже начинают сыпаться ошибки Bad Gateway 502, вероятно, это как раз то самое "под высокие нагрузки он в любом случае не заточен". Нельзя ли какими-то твиками ядра это починить?

**Comment by z3APA3A** [comment]
Ну я не думаю что вам надо столько клиентов.
Сколько реально коннектов идет в секунду?

**Comment by z3APA3A** [comment]
на стороне сервера тоже можно запускать несколько служб, но больше 3-4 точно смысла не имеет. при этом пары портов -r -R можно делать разные и вешать, например, по 5 клиентов на каждый сервер:

tcppm -R0.0.0.0:3007 -olSO_REUSEPORT ...
tcppm -R0.0.0.0:3008 -olSO_REUSEPORT ...
tcppm -R0.0.0.0:3008 -olSO_REUSEPORT...

на клиенте

proxy -rsrv1.prxdomain.com:3007
...
proxy -rsrv1.prxdomain.com:3007
proxy -rsrv1.prxdomain.com:3008
...
proxy -rsrv1.prxdomain.com:3008
proxy -rsrv1.prxdomain.com:3009
...
proxy -rsrv1.prxdomain.com:3009


-olSO_REUSEPORT поддерживается в devel, нужен чтобы равномерно распределять нагрузку приходящую на порт 4007 между 3мя службами.

Но если у вас реально _такая_ нагрузка, то там может роутер тормозить на работе с NAT таблицей.

**Comment by z3APA3A** [comment]
Если 400 соединений в секунду и пинг 20 мс, то со стороны клиента надо не больше 80 proxy. Запустите, например 8 серверов (tcppm) с разными -R и по 10 клиентов на каждый.

**Comment by z3APA3A** [comment]
И в последней версии используется splice(), она многократно эффективней по нагрузке на процессор/шину/память, и используется меньше памяти, но требуется в вдва раза больше файловых дискрипторов, проверяйте ulimit'ы.

**Comment by flyrider** [comment]
Спасибо за информацию, проведем эксперименты с данными опциями. Нагрузка реальна такая - до тысячи соединений на петлю. А каким-то образом можно "увидеть" тормоза NAT таблицы?
Вообще раньше транспортом между клиентом и сервером вместо "петлевой схемы 3proxy" служил старый добрый p2p туннель (3прокси заворачивался в него на сервере) и такой проблемы не было, но скорость соединения была процентов на 25 хуже чем сейчас  с петлей.

**Comment by z3APA3A** [comment]
Если на стороне connect-back клиента стоит бытовой домашний роутер - то проблемы скорей всего есть, но разведение коннектов по нескольким портам возможно помогут их решить, раз при коннекте на другой порт у вас скорость нормальная.

В последней это в devel.

**Comment by z3APA3A** [comment]
имеет значение именно количество запросов в секунду, а не общее количество соединений. Их можно посчитать по количеству записей в лог файле.

**Comment by flyrider** [comment]
Спасибо, будем пробовать ваши рекомендации.

**Comment by flyrider** [comment]
Доброго дня!

В общем после ряда экспериментов под нашей нагрузкой с использованием разных комбинаций из описанных вами выше рекомендаций обнаружили следующее:

несколько клиентских петель и REUSEPORT дают некоторое улучшение.

Появляются "спонтанные" плавающие ошибки на некоторых прокси в текущей петлевой схеме:

```
curl -x xxx:123@srv4007:4007 http://ya.ru/ http://localhost/html/ -s --connect-timeout 5 -m 5
<html><head><title>407 Proxy Authentication Required</title></head>
<body><h2>407 Proxy Authentication Required</h2><h3>Access to requested resource disallowed by administrator or you need valid username/password to use this resource</h3></body></html>
```
Ошибка появившись иногда остается надолго и "лечится" ресартом процессов 3proxy на клиенте и сервере, иногда не с первого раза. Отловить ее довольно сложно (особенно на нашем сетапе, где тысячи таких вот клиентских петель). 

Не подскажете с чем может быть связано?

Естественно, username/password не меняется, там все статично прописано в скриптах и возникает как-то на ровном месте.

Спасибо!

**Comment by z3APA3A** [comment]
А что при этом в логах?

**Comment by z3APA3A** [comment]
Убедитесь, что у вас нет рейсов на обновлении конфигурации, когда конфигурация переписывается в момент, когда ее считывает прокси. Как это правильно делать есть в 
https://3proxy.ru/highload.asp

**Comment by flyrider** [comment]
Буду ждать всплытия проблемы, чтобы их получить. Не сохранил.
