### ISSUE TITLE
Заголовок Proxy-Connetion

### ISSUE THREAD

**Issue by nikitao23** [z3APA3A/3proxy#264]
Добрый день!
Если пустить HTTP трафик через 3proxy , то к Response Headers добавляется заголовок
Proxy-Connection.
Можно ли его как то убрать?
Заранее спасибо

**Comment by nikitao23** [comment]
поставил devil версию с сайта.
/help выдыет ( помимо самой справки) :
3proxy tiny proxy server 3proxy-0.9-devel (180427015446)
(c)3APA3A, Vladimir Dubrovin & 3proxy.ru

Но заголовки сохранились.

**Comment by z3APA3A** [comment]
В каком именно ответе выдается такой заголовок? Ты уверен что установил прокси и рестартовал его?

**Comment by z3APA3A** [comment]
Или может быть ты используешь StringsPlugin с кастомными ответами - тогда заголовки надо убирать там.

**Comment by nikitao23** [comment]
ну я сделал 3proxy.exe --unistall
Потом скопировал devel содержание devel архива в папку.
Потом сделал 3proxy.exe --install 3proxy.cfg
Проверяю по сайту : http://whatleaks.com через обычный FireFox ( плагинов нет).
Ну и снимал трафик HttpAnalyzerV7. Там В Response заголовках фигурирует.

**Comment by z3APA3A** [comment]
--uninstall не бывает, бывает --remove, предварительно надо сделать net stop 3proxy. 
Вполне может быть что сам сайт "видит" заголовки которых нет, и их же проставляет в ответе из-за того что использует reverse proxy. Снифь именно трафик, который идет от прокси к серверу и от прокси клиенту.

**Comment by nikitao23** [comment]
![image](https://user-images.githubusercontent.com/6884400/39383137-d32a5da0-4a70-11e8-9b52-8b1a546bfac8.png)

Наврал немного. Там заголовок Via появляется. По нему алерт, что прокси

**Comment by z3APA3A** [comment]
Используй -a для прокси в конфиге
(proxy -a)

**Comment by z3APA3A** [comment]
Да, я вообще не представляю зачем -a1 (спуфинг адреса клиента) кому-то использовать, это достаточно специфическая опция.

**Comment by nikitao23** [comment]
Значит че то не так вычитал в свое время. Ща попробуем

**Comment by nikitao23** [comment]
Спасибо большое! Помогло
