### ISSUE TITLE
521 ошибка

### ISSUE THREAD

**Issue by UNREALre** [z3APA3A/3proxy#265]
Привет!

Потратил почти день, но не могу понять в чем может быть причина.
Если открываем без https, то получаем в логе сразу 00521
Если с https, то чередование 94 с 521.

1524870068.781 PROXY.3128 00094 - 188.232.48.97:54307 5.255.255.70:443 186 4191 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870068.941 PROXY.3128 00521 - 188.232.48.97:54309 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.031 PROXY.3128 00094 - 188.232.48.97:54308 5.255.255.70:443 186 4191 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870069.178 PROXY.3128 00521 - 188.232.48.97:54311 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.301 PROXY.3128 00094 - 188.232.48.97:54310 5.255.255.70:443 186 4191 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870069.303 PROXY.3128 00521 - 188.232.48.97:54312 5.45.205.231:80 470 1398 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.458 PROXY.3128 00521 - 188.232.48.97:54314 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.550 PROXY.3128 00521 - 188.232.48.97:54315 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.693 PROXY.3128 00521 - 188.232.48.97:54316 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.841 PROXY.3128 00094 - 188.232.48.97:54317 5.255.255.70:443 186 4192 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870069.844 PROXY.3128 00521 - 188.232.48.97:54318 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870069.967 PROXY.3128 00521 - 188.232.48.97:54319 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.068 PROXY.3128 00521 - 188.232.48.97:54320 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.180 PROXY.3128 00094 - 188.232.48.97:54321 5.255.255.70:443 186 4192 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870070.332 PROXY.3128 00521 - 188.232.48.97:54323 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.334 PROXY.3128 00521 - 188.232.48.97:54324 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.419 PROXY.3128 00094 - 188.232.48.97:54322 5.255.255.70:443 186 4191 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870070.564 PROXY.3128 00521 - 188.232.48.97:54326 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.713 PROXY.3128 00521 - 188.232.48.97:54329 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.830 PROXY.3128 00521 - 188.232.48.97:54330 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.936 PROXY.3128 00521 - 188.232.48.97:54332 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870070.967 PROXY.3128 00094 - 188.232.48.97:54331 5.255.255.70:443 186 4191 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870071.123 PROXY.3128 00521 - 188.232.48.97:54334 5.45.205.231:80 470 1398 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870071.206 PROXY.3128 00521 - 188.232.48.97:54335 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870071.235 PROXY.3128 00094 - 188.232.48.97:54333 5.255.255.70:443 186 4190 0 CONNECT_yandex.ru:443_HTTP/1.1
1524870071.386 PROXY.3128 00521 - 188.232.48.97:54336 5.45.205.231:80 470 1808 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870071.495 PROXY.3128 00521 - 188.232.48.97:54337 5.45.205.231:80 470 1398 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1
1524870071.757 PROXY.3128 00521 - 188.232.48.97:54338 5.45.205.231:80 470 1398 0 POST_http://yandex.ocsp-responder.com/_HTTP/1.1

Конфиг самый базовый, без каких-либо запретов
setgid 117
setuid 112

nserver 8.8.8.8
nserver 77.88.8.8

nscache 65536

timeouts 1 5 30 60 180 1800 15 60

daemon

log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

proxy -n -p3128 -a

Буду очень признателен хотя бы за наводку, в какую сторону копать. Извиняюсь, если глупые вопросы, но перерыл все в инете, ничего не нашел...

**Comment by z3APA3A** [comment]
Какая версия прокси?

**Comment by UNREALre** [comment]
Версия была последняя, но все уже хорошо. Прошу прощения за беспокойство. Все оказалось банально - IP VPS у DigitalOcean, который я использовал, оказался в блоке РКН ... Такие дела) Спасибо Вам за софт, все работает превосходно!
