### ISSUE TITLE
Неправильный подсчет трафика

### ISSUE THREAD

**Issue by akatimka** [z3APA3A/3proxy#267]
Ребята подскажите пожалуйста, отчего трафик общий для всех считает?
![image](https://user-images.githubusercontent.com/20558554/39533712-7609dc1a-4e38-11e8-9303-96c54b49599f.png)
![image](https://user-images.githubusercontent.com/20558554/39533745-864be2a8-4e38-11e8-8cbd-a7b7a1151513.png)
![image](https://user-images.githubusercontent.com/20558554/39533823-bb732b58-4e38-11e8-9a94-0f1b35e904e5.png)

**Comment by z3APA3A** [comment]
Потому что во всех countin указал считать весь трафик.
https://3proxy.ru/howtor.asp#TRAFLIM
