### ISSUE TITLE
Encrypted traffic between two machines [Question]

### ISSUE THREAD

**Issue by DRSDavidSoft** [z3APA3A/3proxy#269]
Considering the following scenario:
```
Laptop <----> Server 1 <========> Server 2 <----> Internet
```
If **Server 1** and **Server 2** both run 3proxy, is there a way to link these two on an _encrypted_ channel such as [obfs4](https://github.com/Yawning/obfs4)?

There's an alternative to [use 3proxy with SoftEther](https://github.com/SoftEtherVPN/SoftEtherVPN/issues/135#issuecomment-76586203), but an embedded option with 3proxy seems more robust.

I'd like to share a SOCKS5 proxy from Server 2 to my Server 1, but the link marked with (`<=>`) is inspected and censored by my ISP, so I'd like to establish the upstream SOCKS5 chain connection using an encrypted channel to make sure my ISP can't monitor and block the connection.

**Comment by DRSDavidSoft** [comment]
@z3APA3A I appreciate your response, though I'd also appreciate if you could consider extending SSLPlugin as an alternative to SoftEther, even considering the added expense of more handshakes.

**Comment by johnnybubonic** [comment]
Hi, just some additions:

1. https-proxy (SSL/TLS-tunneled http proxy) is now actually supported in [Firefox as of version 33](https://bugzilla.mozilla.org/show_bug.cgi?id=378637) and [Chrome (via a cmdline argument or PAC file)](https://www.chromium.org/developers/design-documents/secure-web-proxy) (as well as curl and programmatic clients as well). (I think it's in Microsoft Edge as well, but their documentation's impossible to navigate so I have no idea.) Speaking as someone who works for a proxy/VPN provider, it's a lot more common than you may think. It's *very* common, especially with people using proxies in enterprise/corporate environments. They tend to greatly prefer the additional overhead over exposing their proxy credentials upstream.

2. Relatedly, https-proxy addresses a key flaw with plaintext proxies - without the SSL/TLS tunneling, *the proxy credentials are exposed in plaintext base64 on the wire*.

3. Why would the resource consumption be an issue? They should be freed when the connection closes, no? Assuming the host isn't holding open closed/closing sockets for an inordinate amount of time, why would this cause any more issues than, say, a regular http-proxy request with a large amount of headers? (Granted, the size is still more, but it should still be freed up as soon as the connection is finished closing, no?) Assuming you're running a proxy server that's handling the amount of connections where this would potentially be an issue, it's likely it's been scaled up to accommodate that anyways.
