### ISSUE TITLE
parent Request-URI и absoluteURI

### ISSUE THREAD

**Issue by ariutk** [z3APA3A/3proxy#27]
3proxy отправляет запрос родителю в формате

GET /pub/WWW/TheProject.html HTTP/1.1
Host: www.w3.org

squid нормально обрабатывает только absoluteURI
GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1

в результате 400 Bad Request.

Можно ли исправить это, либо добавить опцию изменяющую поведение.

**Comment by z3APA3A** [comment]
Как прописан парент? Если как http - все должно отправляться как Absolute URI, если как tcp - Request URI.

**Comment by ariutk** [comment]
auth iponly
allow *
parent 1000 http 127.0.0.1 3128
socks -a1 -6

**Comment by ariutk** [comment]
root@test:~# ngrep -q -W byline -d any port 3128
interface: any
filter: (ip or ip6) and ( port 3128 )

T 127.0.0.1:45013 -> 127.0.0.1:3128 [AP]
GET /raw HTTP/1.1.
User-Agent: curl/7.35.0.
Host: ipv6.myexternalip.com.
Accept: */*.
.


T 127.0.0.1:3128 -> 127.0.0.1:45013 [AP]
HTTP/1.1 400 Bad Request.
Server: squid.
Mime-Version: 1.0.
Date: Sun, 03 Jan 2016 13:08:12 GMT.
Content-Type: text/html;charset=utf-8.
Content-Length: 3405.
X-Squid-Error: ERR_INVALID_URL 0.
Vary: Accept-Language.
Content-Language: en.
X-Cache: MISS from test.
X-Cache-Lookup: NONE from test:3128.
Connection: close.

**Comment by ariutk** [comment]
Проверил tcp. С http единичный запрос отправляют

**Comment by z3APA3A** [comment]
SOCKS не работает с HTTP-запросами и не меняет их. Из socks необходимо сначала перенаправить трафик во внутренний http-прокси, который умеет работать с транспарентными запросами и только потом во внешний squid:
allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 3128
allow *
socks

**Comment by ariutk** [comment]
Попробовал так, но запрос уходит напрямую, не через parent

**Comment by ariutk** [comment]
Вероятнее всего, что я до конца не понимаю механизм взаимодействия компонентов между собой.

Хочу получить в результате Socks via HTTP. Который будет переадресовывать HTTP, HTTPs на вышестоящий squid в котором расписаны ACL.

**Comment by z3APA3A** [comment]
Что в конфиге, что в логах, какая версия 3proxy?

**Comment by z3APA3A** [comment]
Если https тоже надо пускать в squid, то
allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 3128
allow *
parent 1000 connect 127.0.0.1 3128
socks

**Comment by ariutk** [comment]
Версия https://github.com/z3APA3A/3proxy/commit/04870841616bee347a4692da6bd8f8cf3d9c5817

В конфиге

allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 3128
allow *
socks

Вот так работает 

allow *
parent 1000 http 127.0.0.1 3128
proxy -p3129 -6
flush
allow *
parent 1000 http 127.0.0.1 3129
socks -6

Но это костыль

**Comment by ariutk** [comment]
С connect тоже беда в develop ветке. Пакеты до сниффера на 3128 порту не доходят.

**Comment by ariutk** [comment]
IPv6 с connect вообще никак не дружит. 

T 127.0.0.1:37455 -> 127.0.0.1:3128 [AP]
CONNECT 0.0.0.0.]:47873 HTTP/1.0.
Proxy-Connection: keep-alive.
.

**Comment by z3APA3A** [comment]
Connect пофиксил в 0e9cc9e330e3878b32f66c09822e7bf390694634, правильный конфиг вот такой:
allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http 127.0.0.1 3128
allow * * * 80
allow *
parent 1000 connect 127.0.0.1 3128
socks

**Comment by ariutk** [comment]
Спасибо! При сборке
common.c: In function ‘logsyslog’:
common.c:633:2: error: expected ‘;’ before ‘if’
  if(!param->nolog)syslog(LOG_INFO, "%s", tmpbuf);
  ^
make[1]: *** [common.o] Ошибка 1
make[1]: Выход из каталога `/root/3proxy/src'
make: *** [all] Ошибка 2

**Comment by z3APA3A** [comment]
Поправил в 889c5caa1f727651016c42b73bc160219bab6a96

**Comment by ariutk** [comment]
Собралось. Конфиг работает отлично.
С connect по прежнему баг.

root@test:~# curl -k --socks5 localhost:1080 https://ipv6.myexternalip.com/raw
curl: (7) Can't complete SOCKS5 connection to 127.0.0.1:58150. (4)

В логах
160103171039.324 1080 00032 - 127.0.0.1:51860 127.0.0.1:3128 0 67 1 CONNECT 2a01:4f8:d13:16c1::2:443

Сниффер
T 127.0.0.1:58150 -> 127.0.0.1:3128 [AP]
CONNECT [42.1.4.248]:443 HTTP/1.0.
Proxy-Connection: keep-alive.
.

**Comment by ariutk** [comment]
connect+ тоже неправильно ведет себя.

Ожидание
T 127.0.0.1:41426 -> 127.0.0.1:3128 [AP]
CONNECT ipv6.myexternalip.com:443 HTTP/1.1.
Host: ipv6.myexternalip.com:443.
User-Agent: curl/7.35.0.
Proxy-Connection: Keep-Alive.
.

Реальность
T 127.0.0.1:51564 -> 127.0.0.1:3128 [AP]
CONNECT 2a01:4f8:d13:443 HTTP/1.0.
Proxy-Connection: keep-alive.
.

**Comment by ariutk** [comment]
http – работает с https правильно, но только с proxy

**Comment by z3APA3A** [comment]
CONNECT [42.1.4.248]:443 HTTP/1.0.
Proxy-Connection: keep-alive.

- это нормальный запрос

**Comment by ariutk** [comment]
Как 2a01:4f8:d13:16c1::2:443 превратился в [42.1.4.248]:443? Выше стоящий squid не понимает этого :-(

**Comment by z3APA3A** [comment]
Поправил последними патчами

**Comment by z3APA3A** [comment]
IPv6 connect parent fixed with 7f90b6eae2bba2c1effad4b7f7aa71864f87497e
