### ISSUE TITLE
can not work with socksCap64

### ISSUE THREAD

**Issue by gitlsl** [z3APA3A/3proxy#271]
```
log
logformat "- +_L%t.%.  %i.%e %E   %T"
socks -p12111  
```
this is my config 
when test tcp  get error 94
when test udp get error  465 or  sometimes socksCap64  show error but 3proxy log is ok

**Comment by z3APA3A** [comment]
94 means SOCKS client terminated connection (usually it happens if application closed without closing socket). 465 means SOCKS client handhaked UDP mapping didn't sent proper UDP packet. I can say nothing about socksCap64 and if it's expected results during the test or not.
