### ISSUE TITLE
Проблема с настройкой 3proxy

### ISSUE THREAD

**Issue by evgenmedia** [z3APA3A/3proxy#273]
Добрый день!
Сделал конфигурационный файл, но никак не могу подружить 3proxy с FreeRADIUS сервером

Вот мой конфиг:
setgid 115
setuid 109
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
daemon
radius fgfhgfghfgh x.x.x.x 
auth radius
socks  -n -a -iX.X.X.X -eX.X.X.X -p443
flush
end

При запуске получаю "Unknown command: 'radius' line 8"

**Comment by z3APA3A** [comment]
В какой версии 3proxy?

**Comment by z3APA3A** [comment]
Поддержка RADIUS есть только в devel
