### ISSUE TITLE
Просмотр статистики

### ISSUE THREAD

**Issue by evgenmedia** [z3APA3A/3proxy#275]
Добрый день!

Настроил socks5 прокси с авторизацией через FreeRADIUS, хочется посмотреть статистику по подключенным пользователям (username, ip)
Настроил опцию admin, но в веб-интерфейсе почему-то не отображается никакая информация по активным пользователям

Есть ли вариант просмотра хотя числа активных подключений?

Буду благодарен за пример вызова в консоли или пример файла конфигурации

Отдельное спасибо за продукт!

**Comment by z3APA3A** [comment]
Что значит не отображается? А что показывает http://proxy:admin_port/S ?

**Comment by z3APA3A** [comment]
Так а что показывает running services и с какими параметрами запущен admin?

**Comment by evgenmedia** [comment]
Running Services показывает именно то, что на скриншоте
Admin запущен в таком ключе: 
admin -p80
Больше никаких параметров не указывалось

**Comment by z3APA3A** [comment]
А каким браузером смотришь? В загрузках не смотрел - может у тебя браузер XML не поддерживает?

**Comment by evgenmedia** [comment]
Смотрю через браузер Safari на MacOS и через Google Chrome на MacOS

**Comment by z3APA3A** [comment]
Так в загрузках не смотрел, может быть XML просто как файл загружается?

**Comment by z3APA3A** [comment]
Если нет - давай больше информации, какая ОС, какой конфиг, пробовал ли с последней версией devel

**Comment by evgenmedia** [comment]
Авторизация по radius стоит для тестирования
В логах ничего необычного не увидел, там отображаются только подключения к самому прокси и неудачные попытки авторизации

**Comment by z3APA3A** [comment]
Так а обычное что по службе admin?

**Comment by evgenmedia** [comment]
Как я написал ранее, в логах отображаются только попытки авторизации ...

**Comment by z3APA3A** [comment]
И что в этих попытках написано? Если ты на RADIUS не авторизуешь эти запросы - то вполне логично что они не работают.

**Comment by z3APA3A** [comment]
У меня проблема не воспроизвелась, по крайней мере в текущем devel. Если таки она повторяется - нужны сведения о системе, конфигурация, логи (можно с вырезаной приватной информацией на 3proxy@3proxy.ru)

**Comment by z3APA3A** [comment]
P.S. не имеет отношения к вопросу, но все-таки - у тебя конфигурация явно под IPv6 снаружи, но при этом nscache есть а nscache6 нет.
