### ISSUE TITLE
3proxy и сервер RDP

### ISSUE THREAD

**Issue by Corpsgrinder** [z3APA3A/3proxy#276]
Приветствую. Никак не могу написать конфиг. Поэтому прошу помощи.
Есть сервер терминалов с 2-я сетевыми картами, к которому по RDP подключаются тонкие клиенты через сеть с адресом 10.*.*.*.
10.*.*.* - это закрытая сеть, в которой нет интернета, там поднят некоторый web-сервер. Через метрику эта сетевая карта этой сети приоритетом выше, поэтому все введенное в браузере идет через нее.
192.168.1.2 - адрес сетевой карты локальной сети, в которой есть интернет через шлюз 192.168.1.1

Вопрос:
Как настроить 3proxy так, чтобы у пользователя rdp работал бы интернет, если в настройках написать адрес прокси 192.168.1.2 через порт 3128.
Надеюсь, разборчиво написал. Буду благодарен наводящим вопросам, может быть тогда сам пойму в чем были ошибки.
Именно сейчас вылезает ошибка 502 Bad Gateway Host Not Found or connection failed.

**Comment by z3APA3A** [comment]
Ну по всей видимости
proxy -e192.168.1.2

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#INTEXT
