### ISSUE TITLE
Не работает 'auth strong' через SOCKS

### ISSUE THREAD

**Issue by Rapatool** [z3APA3A/3proxy#28]
3proxy 0.8. Centos-7 x86_64

Столкнулся с такой проблемой: при подключении к прокси по http все работает нормально, запрашивается авторизация, подключается, всё ок. А при подключении к тому же прокcи по socks даже авторизацию не запрашивает, выдает: ERR_SOCKS_CONNECTION_FAILED.
Причём, если авторизацию отключить, то всё работает нормально.

Логи при подключении к fb.com и 2ip.ru по http:
```
160115064621.213 8000 00000 vasya xxx.xxx.xxx.xxx:53350 173.252.120.68:80 378 282 0 GET http://fb.com/ HTTP/1.1
160115070624.774 8000 00090 vasya xxx.xxx.xxx.xxx:53515 178.63.151.224:80 864 33264 0 GET http://2ip.ru/ HTTP/1.1
```
при подключении к fb.com и 2ip.ru по SOCKS:
```
160115065143.650 1200 00004 - xxx.xxx.xxx.xxx:53416 31.13.81.36:443 0 0 0 CONNECT www.facebook.com:443
160115070608.470 1200 00004 - xxx.xxx.xxx.xxx:53511 178.63.151.224:80 0 0 0 CONNECT 2ip.ru:80
```

Конфиг:
```
daemon
log /var/log/3proxy.log Drotate 3
pidfile /usr/local/etc/3proxy/3proxy.pid
users vasya:CL:password
auth strong

proxy -n -a -p8000 -ixxx.xxx.xxx.xxx -exxx.xxx.xxx.xxx
socks -p1200 -ixxx.xxx.xxx.xxx -exxx.xxx.xxx.xxx

flush
allow vasya
timeouts 1 5 30 60 180 1800 15 60
```

**Comment by z3APA3A** [comment]
ACL необходимо задавать до запуска сервиса, а не после, в 3proxy порядок команд важен, все команды выполняются последовательно.
Судя по логам, клиент не отправляет в списке поддерживаемых методов авторизации по логину и паролю, в таком случае 3proxy соглашается на авторизацию без пароля (т.к. поддерживается смешнная авторизация) и запрос фейлится уже на проверке доступа к ресурсу. Поснифайте трафик между клиентом и сервером, необходимо чтобы в списке методов авторизации передавался метод с номером 2.

**Comment by z3APA3A** [comment]
Добавил в 0.8 75c63d2de6a7d9bcd4cad77ec68108213c43c356 опцию -u2 для socks - будет сразу реджектить на попытке аутентификации клиента, который не позволяет аутентифицироваться логином и паролем. Если это не поможет, значит ваш клиент не поддерживает такую аутентификацию.

**Comment by Rapatool** [comment]
Прошу прощения, все работает. Просто я проверял через хромобраузер, а они, как оказалось, не поддерживают аутентификацию через SOKS5. Проверил через Maxthon - всё Ok!
Спасибо за помощь! :)

**Comment by ka4a** [comment]
2018г хром до сих пор не работает авторизация по socks5
