### ISSUE TITLE
Is it possible to compile without OpenSSL? (Windows)

### ISSUE THREAD

**Issue by VirtualSmile** [z3APA3A/3proxy#281]
Hello! I've been trying to compile the most recent github dev branch (for the socket option fix) but I keep getting this:

`LINK : fatal error LNK1181: cannot open input file 'libeay32.lib'`   
`NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX86\x86\link.EXE"' : return code '0x49d'`

I'm using VS 2017 to compile with nmake /f Makefile.msvc.
I've tried installing 1.0.2 of OpenSSL in both directories (Windows and C:\OpenSSL-32/64) to no success.

Thanks!

**Comment by z3APA3A** [comment]
Either add path to OpenSSL headers/static libraries to INCLUDE/LIBS environment variables or remove "SSLPlugin" from "PLUGINS" in Makefile.msvc.
