### ISSUE TITLE
Ограничение скорости по величине содержимого

### ISSUE THREAD

**Issue by michaeladm** [z3APA3A/3proxy#283]
Возможно ли сделать ограничение скорости клиенту в зависимости от "Content-Length" ?
Скажем, что у нас есть http://www.hlam.net/file2.zip с Content-Length: 2000000, к примеру, и чтобы клиент его скачивал на определенной скорости. Или так:
file =<1MB client download with 400Kbit/s
file 1MB...5MB client donload with 4Mbit/s
file >5MB - no speed limit

Возможно ли это вообще?
Предыстория этой проблемы состоит в том, что есть уникальное оборудование, в нем работает уникальная программа (нет возможности исправить), и при очень маленьких размерах файла эта программа не успевает - сильно быстро скачивается по вифи, так что как будь то ничего не получила, - короче, глотает этот файл. Сделать медленнее соединение - тогда на больших файлах (иногда 10-20 ГБ) - можно не дождаться вообще.
Если это не возможно на 3proxy может кто подскажет софт который это умеет делать?

**Comment by z3APA3A** [comment]
Добавьте в proxy.c после метки

`REQUESTEND:`

например

`usleep(SLEEPTIME);`

это добавит секундную задержку в конце каждого запроса.
