### ISSUE TITLE
Скрыть DNS провайдера (DNS из настроек моего сетевого подключения)

### ISSUE THREAD

**Issue by GoldenBringer** [z3APA3A/3proxy#286]
Добрый день

Вопрос по теме: при работе через 3proxy в анонимном режиме "светится" реальный DNS провайдера, т.е. настроил прокси, подключился через него, захожу на https://whatleaks.com/ru/ и вижу здесь свой реальный DNS, а не DNS прокси сервера. Интересует как настроить 3proxy так, чтобы в данном сервисе https://whatleaks.com/ru/ и подобных сервисах, и подобных способах определения DNS, показывался не DNS провайдера (DNS который указан в настройках сетевого подключения), а DNS именно прокси сервера? Когда заказываю платные прокси или использую бесплатные Elite прокси - показывается DNS прокси сервера, а здесь как не пробовал скрипть реальный DNS - не получается :(

Буду благодарен за скорый ответ!

**Comment by GoldenBringer** [comment]
Как это сделать в браузере? Например в Mozilla?

**Comment by GoldenBringer** [comment]
Да и интересует не сторона клиента, а настройка прокси-сервера так, чтобы он не светил DNS клиента

**Comment by z3APA3A** [comment]
В настройках прокси-сервера очевидно: https://s.mail.ru/2gPZ/xcEkErbP2
Если используется HTTP прокси, то адреса разрешаются через прокси по умолчанию.
Прокси при всем желании не может светить DNS клиента, он ему не известен, если только сам прокси не использует тот же DNS.

**Comment by GoldenBringer** [comment]
Понял, спасибо за ответы! :)
