### ISSUE TITLE
502 Bad Gateway Host Not Found or connection failed

### ISSUE THREAD

**Issue by moobi08** [z3APA3A/3proxy#287]
добрый вечер. такая ситуация. есть  lan 192.168.56.136 и три сетевых во внешку. root@debian:~# traceroute ya.ru -i eth1
traceroute to ya.ru (87.250.250.242), 30 hops max, 60 byte packets
 1  192.168.15.1 (192.168.15.1)  29.061 ms  45.140 ms  49.044 ms
 2  * * *
 3  10.10.30.37 (10.10.30.37)  701.130 ms  684.905 ms  702.386 ms
 4  * * *
 5  * * *
 6  10.10.30.125 (10.10.30.125)  701.557 ms  116.436 ms  115.386 ms
 7  10.10.30.174 (10.10.30.174)  92.644 ms  65.769 ms  67.733 ms
 8  62.105.150.250 (62.105.150.250)  74.464 ms 62.105.150.248 (62.105.150.248)  69.622 ms  78.397 ms
 9  81.211.31.62 (81.211.31.62)  94.787 ms  58.426 ms  103.397 ms
10  195.239.153.234 (195.239.153.234)  113.679 ms  104.309 ms  100.068 ms
11  std-p2-be1.yndx.net (87.250.239.133)  81.021 ms  103.185 ms *
12  ya.ru (87.250.250.242)  65.198 ms  97.676 ms *
root@debian:~#
root@debian:~# traceroute ya.ru -i rename5
traceroute to ya.ru (87.250.250.242), 30 hops max, 60 byte packets
 1  hi.link (192.168.13.1)  14.152 ms  13.921 ms  13.747 ms
 2  * * *
 3  * * *
 4  * * *
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  37.29.5.73 (37.29.5.73)  754.223 ms  754.136 ms 37.29.5.77 (37.29.5.77)  754.045 ms
10  * * *
11  * * *
12  * * *
13  83.169.204.6 (83.169.204.6)  74.405 ms 83.169.204.38 (83.169.204.38)  74.251 ms 83.169.204.30 (83.169.204.30)  74.008 ms
14  83.169.199.91 (83.169.199.91)  73.845 ms  71.118 ms  71.001 ms
15  m9-p2-eth-trunk1.yndx.net (87.250.239.115)  86.625 ms m9-p1-be15.yndx.net (87.250.239.113)  88.665 ms std-p2-be14.yndx.net (87.250.239.62)  100.264 ms
16  * * *
17  ya.ru (87.250.250.242)  102.499 ms  102.140 ms *
root@debian:~#

root@debian:~# traceroute ya.ru -i rename4
traceroute to ya.ru (87.250.250.242), 30 hops max, 60 byte packets
 1  192.168.12.1 (192.168.12.1)  47.441 ms  47.107 ms  46.935 ms
 2  * * *
 3  10.10.32.49 (10.10.32.49)  1374.985 ms  1381.275 ms  1412.785 ms
 4  * * *
 5  * * *
 6  10.10.30.125 (10.10.30.125)  3662.249 ms 10.10.30.121 (10.10.30.121)  2615.034 ms 10.10.30.125 (10.10.30.125)  2614.842 ms
 7  10.10.31.58 (10.10.31.58)  2614.699 ms 10.10.30.174 (10.10.30.174)  2288.235 ms  2281.858 ms
 8  62.105.150.250 (62.105.150.250)  2250.068 ms  228.044 ms 62.105.150.248 (62.105.150.248)  389.986 ms
 9  81.211.31.62 (81.211.31.62)  433.078 ms  564.343 ms  663.347 ms
10  195.239.153.234 (195.239.153.234)  1034.774 ms  1042.904 ms  1775.299 ms
11  m9-p2-eth-trunk8.yndx.net (87.250.239.127)  1697.406 ms std-p2-be1.yndx.net (87.250.239.133)  1602.806 ms m9-p2-eth-trunk8.yndx.net (87.250.239.127)  2058.324 ms
12  * * *
13  ya.ru (87.250.250.242)  3165.985 ms  3189.829 ms *
root@debian:~#

пинги идут по интерфейсам во внешку тоже нормально. сделал простейший конфиг 
maxconn 50
log
nserver 8.8.8.8
auth iponly
allow * 192.168.56.1
internal 0.0.0.0
external 192.168.12.1
proxy -a -p4001
socks -p56710
tcppm 80 192.168.9.1 80
#proxy -a -p4000  -e192.168.15.1
#proxy -a -p4001  -e192.168.12.1
#proxy -p4002 -e192.168.13.1
  с ип 56.1 доступ к прокси. так вот если указываю external то вываливает 502. если уубираю то работает через одну из сетевых карт нормально. что не так делаю подскажите. голову сломал уже.

**Comment by z3APA3A** [comment]
а что в логах и что говорит 
ping -I 192.168.12.1 ya.ru?

**Comment by moobi08** [comment]
root@debian:~# ping -I 192.168.12.1 ya.ru
bind: Cannot assign requested address
root@debian:~# ping -I eth1 ya.ru
PING ya.ru (87.250.250.242) from 192.168.15.100 eth1: 56(84) bytes of data.
64 bytes from ya.ru (87.250.250.242): icmp_req=1 ttl=47 time=1860 ms
64 bytes from ya.ru (87.250.250.242): icmp_req=2 ttl=47 time=850 ms
64 bytes from ya.ru (87.250.250.242): icmp_req=3 ttl=47 time=65.9 ms
64 bytes from ya.ru (87.250.250.242): icmp_req=4 ttl=47 time=71.3 ms
^C
--- ya.ru ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3893ms
rtt min/avg/max/mdev = 65.937/712.146/1860.289/735.811 ms, pipe 2
root@debian:~#
110301054630.444 4001 00012 - 192.168.56.1:53121 104.31.13.154:80 0 0 0 GET http://www.waper.ru/chat/11832?r=x5dne9r&sid=icf7uokolkackn8breqa9fodb7 HTTP/1.1
110301054630.682 4001 00012 - 192.168.56.1:53122 104.31.13.154:80 0 0 0 GET http://www.waper.ru/favicon.ico HTTP/1.1

**Comment by moobi08** [comment]
eth1      Link encap:Ethernet  HWaddr 00:1e:10:1f:00:00
          inet addr:192.168.15.100  Bcast:192.168.15.255  Mask:255.255.255.0
          inet6 addr: fe80::21e:10ff:fe1f:0/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:58986 errors:342 dropped:0 overruns:0 frame:342
          TX packets:40624 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:64727800 (61.7 MiB)  TX bytes:6207769 (5.9 MiB)

root@debian:~# ping -I rename4 ya.ru
PING ya.ru (87.250.250.242) from 192.168.12.100 rename4: 56(84) bytes of data.
64 bytes from ya.ru (87.250.250.242): icmp_req=1 ttl=51 time=946 ms
64 bytes from ya.ru (87.250.250.242): icmp_req=2 ttl=51 time=568 ms
64 bytes from ya.ru (87.250.250.242): icmp_req=3 ttl=51 time=666 ms
^C
   блин помоему доперло) я ип роутера указывал а не сетевухи)

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#INTEXT

**Comment by moobi08** [comment]
помогло но не так как нужно( теперь по всем портам лезет с одного ип. раскоментил строки  нижние

**Comment by moobi08** [comment]
да я посмотрел но ип   находятся же в системе и активны. proxy -a -p4000 -i192.168.56.136  -e192.168.15.100
proxy -a -p4001 -i192.168.56.136  -e192.168.12.100
proxy -p4002 -i192.168.56.136 -e192.168.13.100
 и все  идет через один ип  как порты не прописывай

**Comment by z3APA3A** [comment]
Скорей всего, ты считаешь что выбор внешнего IP и внешнего интерфейса это одно и то же. В Linux это не так, по крайней мере при включенном ip forwarding. Либо нужно дополнительно настраивать source routing, чтобы пакеты с данного IP шли через нужный интерфейс, либо в devel-версии можно делать биндинг именно к интерфейсам 
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
см. -De

**Comment by moobi08** [comment]
понял спаибо то есть банально не ип указать можно будет а  интерфейс.  пересобирать нужно? по дефолту?

**Comment by z3APA3A** [comment]
Если актуальная девел-версия (не stable), то пересобирать не нужно.

**Comment by moobi08** [comment]
не стабильная собранна. сейчас перекачаем и соберем. просто  задание  вот такое уопоротое попалось и уже 4 суток долблюсь без перекура. сетевухи это модемы.
maxconn 50
log
nserver 8.8.8.8
auth iponly
allow * 192.168.56.1
internal 0.0.0.0
external 192.168.12.1
proxy -a -p4001
socks -p56710
tcppm 80 192.168.9.1 80
#proxy -a -p4000 -e192.168.15.1
#proxy -a -p4001 -e192.168.12.1
proxy -p4002-Di eth0  -De eth1
я верно  понял? спасибо за пояснения.

**Comment by z3APA3A** [comment]
без пробелов

**Comment by moobi08** [comment]
да понял. еще раз спасибо. отпишу сюда как получилось. не раз три прокс выручал.

**Comment by moobi08** [comment]
несколько раз пробовал пересобрать но бинарников нет(  -DWITH_POLL -DWITH_NETFILTER pcre_table.c
gcc -o ../../../bin/PCREPlugin.ld.so -O2 -fno-strict-aliasing -pthread -shared pcre_compile.o pcre_config.o pcre_dfa_exec.o pcre_exec.o pcre_fullinfo.o pcre_get.o pcre_globals.o pcre_newline.o pcre_ord2utf8.o pcre_refcount.o pcre_study.o pcre_tables.o pcre_valid_utf8.o pcre_version.o pcre_xclass.o pcre_plugin.o pcre_maketables.o pcre_ucd.o pcre_table.o
make[2]: Leaving directory `/root/3proxy/src/plugins/PCREPlugin'
make[2]: Entering directory `/root/3proxy/src/plugins/TransparentPlugin'
gcc -fpic -g -O2 -fno-strict-aliasing -c -pthread -DWITHSPLICE -DGETHOSTBYNAME_R -D_THREAD_SAFE -D_REENTRANT -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL -DWITH_NETFILTER transparent_plugin.c
gcc -o ../../../bin/TransparentPlugin.ld.so -O2 -fno-strict-aliasing -pthread -shared transparent_plugin.o
make[2]: Leaving directory `/root/3proxy/src/plugins/TransparentPlugin'
make[1]: Leaving directory `/root/3proxy/src'
root@debian:~/3proxy#

**Comment by moobi08** [comment]
наверное у меня лыжи не едут

**Comment by z3APA3A** [comment]
Где их нет?

**Comment by moobi08** [comment]
/root/3proxy/src'

**Comment by z3APA3A** [comment]
а в 3proxy/bin ?

**Comment by moobi08** [comment]
))) всегда раньше в src падало. спасибо есть все. сейчас тестанем

**Comment by moobi08** [comment]
увы не помогло 
proxy -a -p4001 -Dieth0 -Deeth1
proxy -p4002 -Dieth0 -Derename

**Comment by moobi08** [comment]
все идет через 1 ип .

**Comment by moobi08** [comment]
да поспать нужно было опечатка . спасибо огромное с меня сейчас донат. нехватало этой функции раньше лет 10 12 назад) темку наверное можно закрывать.  терпеливый вы человек в час ночи отвечать)

**Comment by moobi08** [comment]
proxy -a -p4000 -Dieth0 -Derename7
proxy -a -p4001 -Dieth0 -Deeth1
proxy -p4002 -Dieth0 -Derename6
 на 4000 и 4002 один и тот же ип. хотя устройства разные.

**Comment by z3APA3A** [comment]
external-то убери.

**Comment by moobi08** [comment]
maxconn 50
log
nserver 8.8.8.8
auth iponly
allow * 192.168.56.1
#internal 192.168.56.136
#external 192.168.15.100
#proxy -a -p4001
socks -p56710
tcppm 80 192.168.9.1 80
proxy -a -p4000 -Dieth0 -Derename7
proxy -a -p4001 -Dieth0 -Deeth1
proxy -p4002 -Dieth0 -Derename6

**Comment by z3APA3A** [comment]
добавь в логгирование %e, проверяй что через все интерфейсы есть default gateway.

**Comment by z3APA3A** [comment]
Это принципиально невозможно, т.к разные порты обслуживаются разными потоками. Ищи проблему в чем-то другом - отваливающийся интерфейс, несколько запущенных инстансов 3proxy с разными конфигурациями, проблемы с роутингом и т.п.

**Comment by moobi08** [comment]
проверил несколько раз. шлюз на всех сетевухах.
root@debian:~# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         hi.link         0.0.0.0         UG    0      0        0 rename10
default         192.168.12.1    0.0.0.0         UG    0      0        0 rename7
default         192.168.13.1    0.0.0.0         UG    0      0        0 rename8
default         192.168.10.1    0.0.0.0         UG    0      0        0 rename9
default         192.168.15.1    0.0.0.0         UG    0      0        0 eth1
192.168.10.0    *               255.255.255.0   U     0      0        0 rename9
192.168.12.0    *               255.255.255.0   U     0      0        0 rename7
192.168.13.0    *               255.255.255.0   U     0      0        0 rename8
192.168.14.0    *               255.255.255.0   U     0      0        0 rename10
192.168.15.0    *               255.255.255.0   U     0      0        0 eth1
192.168.56.0    *               255.255.255.0   U     0      0        0 eth0
root@debian:~#
 проверил пингом и трасировкой работает шлюз у каждого свой. и порт меняеш и проверяеш ип он один. потом переходиш на другой порт и он может там оказатся.. я сам понимаю что брдятина но так и есть. интерфейсы не отваливаются. попробую побольше поставить портов и погонять

**Comment by moobi08** [comment]
b xfcnj dsdfkbdftn Невозможно подключиться к прокси-серверу. Доступ запрещён
