### ISSUE TITLE
IP для выхода во внешний мир

### ISSUE THREAD

**Issue by GoldenBringer** [z3APA3A/3proxy#288]
Добрый день.

Подскажите, пожалуйста, есть такая строчка в конфиге для HTTP прокси:
proxy -n -a -iIP_ADD -eIP_ADD -p3535

На сервере есть основной IP_MAIN и дополнительный IP_ADD. Подключаюсь к прокси по IP_ADD, все подключается, но когда проверяю свой IP через прокси, то показывается не IP_ADD, а IP_MAIN. Т.е. не учитывается правило, с какого IP выходить во внешний мир.

Как можно решить данную проблему?

**Comment by z3APA3A** [comment]
нужен полный конфиг и лог, в формат лога желательно добавить %e.

**Comment by GoldenBringer** [comment]
daemon

pidfile /usr/local/etc/3proxy/3proxy.pid

nserver 127.0.0.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "G%d-%m-%Y %H:%M:%S | %U | %C | %R:%r | %O    | %I    |%n"
archiver gz /usr/bin/gzip %F
rotate 7

auth strong
users user:CL:password
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -n -a -iIP_ADD -eIP_ADD -p3535
maxconn 256
flush

auth strong
users user:CL:password
allow * * * *
socks  -n -a -iIP_ADD -eIP_ADD -p3536
maxconn 256
flush

auth strong
users user:CL:password
allow * * * *
ftppr  -n -a -iIP_ADD -eIP_ADD -p3537
maxconn 256
flush

dnspr

monitor "/usr/local/etc/3proxy/3proxy.cfg"

end



=======================================================
=======================================================



10-07-2018 13:36:02 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:02 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:03 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:13 | smart | REAL_IP | 34.242.115.195:443 | 197    | 4633    |sockjs-eu.pusher.com     |IP_ADD
10-07-2018 13:36:13 | smart | REAL_IP | 35.153.55.200:443 | 2409    | 5191    |timeline52-clientstats1.pusher.com       |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:18 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:37:04 | smart | REAL_IP | 34.253.147.176:443 | 1492    | 6480    |ws-eu.pusher.com        |IP_ADD
10-07-2018 13:37:04 | smart | REAL_IP | 108.62.50.234:443 | 1518    | 7022    |pushstream.tradingview.com       |IP_ADD
10-07-2018 13:37:04 | smart | REAL_IP | 209.58.134.234:443 | 2841    | 64790    |widgetdata.tradingview.com     |IP_ADD
10-07-2018 13:37:06 | smart | REAL_IP | 54.144.234.173:443 | 1751    | 5175    |stats.pusher.com        |IP_ADD
10-07-2018 13:37:11 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:37:12 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD

**Comment by GoldenBringer** [comment]
daemon

pidfile /usr/local/etc/3proxy/3proxy.pid

nserver 127.0.0.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "G%d-%m-%Y %H:%M:%S | %U | %C | %R:%r | %O    | %I    |%n"
archiver gz /usr/bin/gzip %F
rotate 7

auth strong
users user:CL:password
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -n -a -iIP_ADD -eIP_ADD -p3535
maxconn 256
flush

auth strong
users user:CL:password
allow * * * *
socks  -n -a -iIP_ADD -eIP_ADD -p3536
maxconn 256
flush

auth strong
users user:CL:password
allow * * * *
ftppr  -n -a -iIP_ADD -eIP_ADD -p3537
maxconn 256
flush

dnspr

monitor "/usr/local/etc/3proxy/3proxy.cfg"

end



=======================================================
=======================================================



10-07-2018 13:36:02 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:02 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:03 | - | 0.0.0.0 | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:12 | - | IP_ADD | IP_ADD:0 | 0    | 0    |IP_ADD    |IP_ADD
10-07-2018 13:36:13 | user | REAL_IP | 34.242.115.195:443 | 197    | 4633    |sockjs-eu.pusher.com     |IP_ADD
10-07-2018 13:36:13 | user | REAL_IP | 35.153.55.200:443 | 2409    | 5191    |timeline52-clientstats1.pusher.com       |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:17 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:36:18 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:37:04 | user | REAL_IP | 34.253.147.176:443 | 1492    | 6480    |ws-eu.pusher.com        |IP_ADD
10-07-2018 13:37:04 | user | REAL_IP | 108.62.50.234:443 | 1518    | 7022    |pushstream.tradingview.com       |IP_ADD
10-07-2018 13:37:04 | user | REAL_IP | 209.58.134.234:443 | 2841    | 64790    |widgetdata.tradingview.com     |IP_ADD
10-07-2018 13:37:06 | user | REAL_IP | 54.144.234.173:443 | 1751    | 5175    |stats.pusher.com        |IP_ADD
10-07-2018 13:37:11 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD
10-07-2018 13:37:12 | - | REAL_IP | 0.0.0.0:0 | 0    | 0    |0.0.0.0    |IP_ADD

**Comment by z3APA3A** [comment]
В этом логе ничего не видно, возьмите стандартный формат 
"G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T"
и добавьте у нему %e

**Comment by z3APA3A** [comment]
и вообще что-то у вас не так - журнал не соответствует формату

**Comment by GoldenBringer** [comment]
180710134714.895 3535 00000 user REAL_IP:60360 108.62.50.228:443 1277 187 0 CONNECT widgetdata-backup.tradingview.com:443 HTTP/1.1 IP_ADD
180710134725.069 3535 00000 user REAL_IP:60402 54.144.234.173:443 1476 425 0 CONNECT timeline51-clientstats1.pusher.com:443 HTTP/1.1 IP_ADD
180710134730.732 3535 00000 user REAL_IP:60400 109.236.87.80:443 4812 114163 0 CONNECT whatleaks.com:443 HTTP/1.1 IP_ADD
180710134730.775 3535 00000 user REAL_IP:60435 108.62.50.228:443 1277 187 0 CONNECT widgetdata-backup.tradingview.com:443 HTTP/1.1 IP_ADD

где:
REAL_IP - реальный IP пользователя
IP_ADD - дополнительный IP сервера, через который должен быть выход во внешний мир

**Comment by z3APA3A** [comment]
Приложение работает через  IP_ADD, но если у тебя роутинг идет через REAL_IP и на нем NAT, то снаружи будет виден REAL_IP.
Возможно, тебе нужен не -e а -De (биндинг к интерфейсу, поддерживается в devel)
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
или policy routing, который трафик от IP_ADD будет направлять в нужный интерфейс.

**Comment by GoldenBringer** [comment]
Спасибо, попробую, отпишусь
