### ISSUE TITLE
Фича: кооперация с IPTABLES:(PREROUTING & CONNMARK)

### ISSUE THREAD

**Issue by IvankoB** [z3APA3A/3proxy#289]
Есть проблемка. 
*.YOUTUBE.* и *.GOOGLE.* сидят на одних IPшниках, поэтому различить их на файрволе проблемно. Придется передавать (-t nat -A PREROUTING -j REDIRECT/DNAT - "прозрачное проксирование") HTTPS-запросы к ним на "опознание" в 3PROXY, далее нужно чтобы 3PROXY:
1) запросы к  GOOGLE возвращались в IPTABLES:PREROUTING с сохранением CONNMARK (по этим маркерам построен пропуск пакетов в PREROUTING & FORWARD, а также CBQ-шайпинг в POSTROUTING) 
2) запросы к  YOUTUBE пропускались и шэйпились в 3PROXY по заданным правилам

Или чтобы 3PROXY имел фичу [пере]назначать CONNMARK в коннектах по заданным критериям и возвращать их в цепочку, откуда они пришли (PREROUTING или FORWARD) - чтобы пропуск и шэйпинг делал файрвол на основании решений в 3PROXY.

**Comment by z3APA3A** [comment]
Такая схема не будет работать, она не имеет отношения к проксированию.
Во-первых, нельзя посредь коннекта начать пропускать его мимо прокси, это поломает коннект.
Во-вторых, 3proxy в таком случае тоже увидит только IP адреса, а не имена хостов, т.к. возьмет их от NAT. 

Для таких целей надо использовать DPI который будет смотреть в SNI или в отдаваемый сертификат в трафике.

**Comment by z3APA3A** [comment]
Режим, с проксированием по SNI и с возможностью применения разных политик для HTTPS трафика есть в squid, это организовать технически реально, но весь трафик все равно пойдет через прокси.

**Comment by IvankoB** [comment]
SQUIT, даже собранный с MITM, сейчас, в HTTPS-времена с проверкой сертификатов на домен, стал малополезен. 
3PROXY ценен в 1-ю очередь адекватностью к HTTPS.
Хочется придумать что-нибудь эдакое бо тема актульная. Типа модуль к IPTABLES для маркирования в проксях :)))

**Comment by IvankoB** [comment]
впервых, нельзя посредь коннекта начать пропускать его мимо прокси, это поломает коннект.
=========
А если новый коннект от прокси - INPUT для IP-tables (будет отработан в PREROUTING) , а для различения что от прокси - коннмарк(и) от прокси ?

**Comment by IvankoB** [comment]
Вместо коннмарков можно было бы использовать номера исходящих портов - если бы удалось их застабилизировать и гарантировать уникальность в пределах коннектов к локалхосту (файрволу).

**Comment by IvankoB** [comment]
Все 80/443-коннеты в PREROUTING заворачивать к 3PROXY, 3PROXY потом будет генерить новые коннекты к файрволу и принимать обратку. В принице сейчас работа через прокси выглядит именно так (коннекты от прокси идут в OUTPUT), но хотелось бы чтобы файрвол имел инфу об обработке в прокси.
Или при прозрачном проксировании 3PROXY не сможет различить "гугл" и "ютуб" ?

**Comment by IvankoB** [comment]
"Telegram" не смогли заблокировать тоже по этой причине ?

**Comment by IvankoB** [comment]
Также можно ипользовать поле "TOS" IP-пакетов (если это поле игнорируется при принятии QOS-решений на DSL- и опто-модемах) - оно сохраняется по всему маршруту пакетов. Правда в этом поле ограниченное количество значений.

**Comment by z3APA3A** [comment]
Прокси работает на прикладном уровне, он никак не связан ни с блокировками телеграмма ни с маркировками IP-пакетов.
