### ISSUE TITLE
В версии 0.8.0 не обрабатываются правила разрешенных IP подсетей

### ISSUE THREAD

**Issue by shark136** [z3APA3A/3proxy#29]
Версия 0.8 не обрабатывает диапазон разрешенных сетей
в версии 0.7 при попытке запроса в сеть не разрешенную к доступу - Error = 0x03 (Network unreachable) всё отлично блочит.
С тем же конфигом версия 0.8 - A default web page was successfuly loaded. - Пропускает

**Comment by z3APA3A** [comment]
Напишите пример конфига, который не работает. "Network unreachable" никак не связана с диапазоном разрешенных сетей.

**Comment by shark136** [comment]
daemon
pidfile /usr/local/3proxy/3proxy.pid
nserver 8.8.8.8
nscache 65536
log /usr/local/3proxy/logs/3proxy.log D
rotate 30
archiver gz /usr/bin/gzip %F
internal MY_EXT_IP
external MY_INT_IP
auth strong
users user:CL:password
allow user * 173.194.0.0/16,216.58.192.0/19,74.125.0.0/16,64.233.160.0/19,173.252.64.0/19,31.13.64.0/18,109.234.72.0/21 80,443,27015,47611
maxconn 1000
socks -p32076 -n
setgid 99
setuid 99

версии 0.7.x прекрасно работают с этим конфигом.

**Comment by z3APA3A** [comment]
Можно запись из лога, которая соответствует некорректному ограничению доступа?

**Comment by shark136** [comment]
160121113353.689 32076 00000 - xxxxxxxxxxxxxx xxxxxxxxxxxxxxx 0 0 0 Accepting connections [3685/3070757744]
160121113410.924 32076 00000 user 95.190.97.194:62613 109.234.76.150:80 50 103 0 CONNECT vindictus.nexoneu.com:80
160121113423.804 32076 00000 user 95.190.97.194:62614 208.85.110.205:80 48 97 0 CONNECT vindictus.nexon.net:80

**Comment by shark136** [comment]
109.234.76.150 - в списке разрешенных и тут норм, а вот 208.85.110.205 не должен пускать

**Comment by z3APA3A** [comment]
Действительно был баг, пофиксил в 359026cb5f3dccd2d8d97a32ea15935ce7a91722 - можешь проверить?

**Comment by shark136** [comment]
всё, теперь нормально Error = 0x02 (Connection not allowed by ruleset).

**Comment by z3APA3A** [comment]
Спасибо, зарелизил 0.8.1 с фиксом.
