### ISSUE TITLE
forward traffic to same IP but different port

### ISSUE THREAD

**Issue by xboxmasters** [z3APA3A/3proxy#291]
Hello, long time 3proxy user, first time running into this kind of an issue, just wanted to ask it it's possible.

I have a load balancer running on port 9999

Can I accept connections on 3proxy ports
111
112
113

and forward traffic to SAME ip and port 9999?

Thank you ! 👍

**Comment by z3APA3A** [comment]
Yes, you can do it with 'tcppm' for any tcp connection or with 'allow'+'parent' for 'proxy' for http traffic.
