### ISSUE TITLE
динамическое перенаправление

### ISSUE THREAD

**Issue by alex-vlaskin** [z3APA3A/3proxy#292]
Здравствуйте! Мне необходимо реализовать перенаправление на различные прокси-сервреры (parent) в зависимости от значений определенных заголовков запроса. Если это возможно реализовать плагином, то подскажите хотя бы схематично как это сделать?

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/devref.rtf

Сделать фильтр на заголовки, по окончании обработки заголовков менять param->hostname
Как делать фильтр на заголовки можно посмотреть в PCREPlugin.
