### ISSUE TITLE
Infinitely increasing CLOSE_WAIT

### ISSUE THREAD

**Issue by smokesmoke** [z3APA3A/3proxy#296]
I have SERVER in Docker container based on alpine:latest
Here is some parts of config:
```
timeouts 1 5 30 60 180 1800 15 60 15 5
nserver 8.8.8.8
flush
auth iponly
allow * $allowed_ips.list SERVER_BEHIND_NAT
tcppm -R0.0.0.0:10001 10002 SERVER_BEHIND_NAT 10002
```
So my SERVER listens to 2 ports: 10001, 10002
I can clearly see that with
`netstat -tulpen`

On my SERVER_BEHIND_NAT I have Docker container based on alpine:latest
I have this config:
```
timeouts 1 5 30 60 180 1800 15 60 15 5
auth none
proxy -rSERVER:10001
```

So my SERVER_BEHIND_NAT is accessible using SERVER:10002 and it works good.

**PROBLEM**
When SERVER_BEHIND_NAT is turned off and I try to access it using SERVER:10002 I see
CLOSE_WAIT states in netstat on SERVER for almost every request and they live there permanently and their count increases infinitely
`netstat -an | grep CLOSE_WAIT | wc -l`
and eventually I face too_many_connections error.
I simply do a
`curl --proxy SERVER:10002 --max-time 5 icanhazip.com`
from another machine and see how CLOSE_WAITs increases on SERVER.

I tried to play with timeouts and nothing helped so far. I don't see any problem on host machine of SERVER container.

Only restarting of the container solves the problem.

Please help and thanks in advance!
@z3APA3A 

P.S.
Можно и по-русски :)

**Comment by z3APA3A** [comment]
А версия devel точно используется последняя?

**Comment by smokesmoke** [comment]
К сожалению нет, используется стабильная версия 0.8.12. Так-как так и не смог скомпилить devel версию под Alpine Linux. Вот ошибка:
`sockmap.c:14:27: error: unknown type name 'loff_t'`
вроде в linux-headers, но ни в какую.
Попробовал devel версию на сервере под ubuntu:latest - полетело и кстати ошибка кажется исправлена
`Connect_back_not_received,_check_connback_client`
Очень хотелось бы скомпилить под Alpine Linux, может я что-то не догоняю. Помогите если возможно.
Сегодня протестирую другую вещь: клиент за NAT-ом попросту умирает и не отвечает если бездействует некоторое время, не знаю это из-за клиента (0.8.12) или было из-за сервера.

**Comment by smokesmoke** [comment]
Проблема умирания клиента продолжается. По всей видимости сервер тут не причем.
Люди может кто собирал devel версию под Alpine Linux ?
Отзовитесь пожалуйста.

**Comment by z3APA3A** [comment]
В Makefile.Linux убери -DWITHSPLICE в CFLAGS. Но вообще я бы рекомендовал использовать другую сборку Linux с норамальным libc, т.к. как раз в контейнерах SPLICE может давать до 10 кратного прироста производительности при высоком трафике.
