### ISSUE TITLE
Using device connected trough SSH as proxy

### ISSUE THREAD

**Issue by k0ngoz** [z3APA3A/3proxy#297]
I have an android phone that i want to work as a proxy. The phone is hosting a proxy and connected to my linux server with SSH with a remote port forward.

The connection from my phone looks like this on my server with 3proxy installed.

How do i make a proxy with 3proxy, and route the traffic trough the proxy hosted on the phone?

![image](https://user-images.githubusercontent.com/42274139/43964021-37f8b81a-9cbc-11e8-9b73-34acf7894bb8.png)

Would love to have some help
@z3APA3A

**Comment by miberlin** [comment]
You probably wanna open a -R ssh connection from your phone and then send the traffic from your server through the then opened port through the reverse ssh connection to the corresponding port on your phone. That is the port your 3proxy should then be listening to - and sends it out from there.
