### ISSUE TITLE
 weekdayslist and timeperiodslist for bandwidth, limits and quotas

### ISSUE THREAD

**Issue by dtouzeau** [z3APA3A/3proxy#299]
There is make sense to have possibility to set a weekdayslist and timeperiodslist 
for the following acls: 

- bandlimin 
- nobandlimin
- bandlimout
- nobandlimout
- connlim
- noconnlim
- countin
- countout
- nocountin
- nocountout

For example a rule that limit bandwidth during working day for specific protocols...

the documentation did not mention weekdayslist and timeperiodslist 
Is there a way to that ?

**Comment by z3APA3A** [comment]
You can use weekdays and timeperiods in any ACLs, including all mentioned above.
