### ISSUE TITLE
The procedure entry point inet_pton could not be located in the dynamic link library WS2_32.dll

### ISSUE THREAD

**Issue by Vzhik9** [z3APA3A/3proxy#30]
Windows Server 2003 R2 SP2 x32
Версия 0.8 х32 при запуске выводит сообщение "The procedure entry point inet_pton could not be located in the dynamic link library WS2_32.dll" и выгружается.
Версия 0.7.1.3 х32 работала без ошибок

**Comment by z3APA3A** [comment]
Для Windows версии до Vista / Server 2008 необходимо использовать версию lite
