### ISSUE TITLE
Possibility to skin errors pages

### ISSUE THREAD

**Issue by dtouzeau** [z3APA3A/3proxy#300]
I see that the return error pages such as 400,502,503... are fixed in proxy_stringtable in proxy.c

Is it possible to specify a local file that allows 3proxy to load it instead of using the preformatted code ?

Thanks!

**Comment by z3APA3A** [comment]
Yes, you can use
https://3proxy.ru/plugins/StringsPlugin/
There is an example of 3ps file in distribution.
