### ISSUE TITLE
Redirector plugin 

### ISSUE THREAD

**Issue by dtouzeau** [z3APA3A/3proxy#301]
In squid we have a possibility to load an external script in python.
For example allowing to force a redirect http code 302/301 to a specific URI.

This permit to connecting a squidguard or other associate external filter to the proxy.

Is it possible to provide such feature?

We are agree to provide revenue for such feature

**Comment by z3APA3A** [comment]
I see at least 2 different questions.
1. You can use https://3proxy.ru/plugins/StringsPlugin/ to replace any proxy reply with 301/302 redirect
2. https://3proxy.ru/doc/devref.rtf describes plugin functionality  to add any custom code to 3proxy
If you need something else or something more specific try to describe it in details.
