### ISSUE TITLE
auth strong problem

### ISSUE THREAD

**Issue by ghasemy50** [z3APA3A/3proxy#302]
hi,
i'm setup 3proxy with "parent proxy" enabled and config it correctly with "auth none" mode.
but, when i switch "auth strong" mode and set a username & password for it, socks will fail!
what is problem?

**Comment by z3APA3A** [comment]
It means allow/parent are configured incorrectly. With "auth none" allow and parent commands are ignored.
https://3proxy.ru/faqe.asp
