### ISSUE TITLE
Rotate dns servers if no 'answer' section?

### ISSUE THREAD

**Issue by slackhead** [z3APA3A/3proxy#304]
Hello

3p 0.8.12

I am using 3 DNS servers. One local and two others:

nscache 65536
nserver 127.0.0.1:5353
nserver 208.67.220.220:443/tcp
nserver 208.67.222.222:443/tcp
dnspr -p53

The local one often fails to find an address but the other two do. There is no timeout. It just returns no answer section at all. But I prefer to keep the first one if I can.

Is there a way of making dnspr try to the next server if this happens?

**Comment by z3APA3A** [comment]
it's against DNS specification for resolver, implementing non-standard DNS functionality in 3proxy is not a priority task. You would rather expect functionality like this in DNS-specific products liks dnsmasq.
