### ISSUE TITLE
0.8.1 проблемы с загрузкой содержимого по 443 порту

### ISSUE THREAD

**Issue by shark136** [z3APA3A/3proxy#31]
log - ver 0.8.1
160121152141.872 32076 00000 - XXXXXXXXXX:32076 XXXXXXXXXX:11272 0 0 0 Accepting connections [2391/3070385008]
160121152149.868 32076 00013 user 95.190.97.194:34819 173.194.32.190:443 0 0 0 CONNECT 173.194.32.190:443
160121152150.395 32076 00013 user 95.190.97.194:51046 173.194.32.190:443 0 0 0 CONNECT 173.194.32.190:443
160121152150.927 32076 00013 user 95.190.97.194:51048 173.194.32.190:443 0 0 0 CONNECT 173.194.32.190:443
160121152151.477 32076 00013 user 95.190.97.194:35331 173.194.32.190:443 0 0 0 CONNECT 173.194.32.190:443
160121152152.957 32076 00013 user 95.190.97.194:35074 109.234.76.160:443 0 0 0 CONNECT 109.234.76.160:443
160121152154.425 32076 00013 user 95.190.97.194:35586 173.194.32.135:443 0 0 0 CONNECT 173.194.32.135:443
160121152155.577 32076 00013 user 95.190.97.194:51057 109.234.76.160:443 0 0 0 CONNECT 109.234.76.160:443
160121152156.104 32076 00013 user 95.190.97.194:35587 109.234.76.160:443 0 0 0 CONNECT 109.234.76.160:443
160121152156.634 32076 00013 user 95.190.97.194:34946 109.234.76.160:443 0 0 0 CONNECT 109.234.76.160:443
160121152157.722 32076 00013 user 95.190.97.194:35458 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152158.276 32076 00013 user 95.190.97.194:35459 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152158.812 32076 00013 user 95.190.97.194:51064 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152159.343 32076 00013 user 95.190.97.194:51065 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152159.876 32076 00013 user 95.190.97.194:35202 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152201.804 32076 00013 user 95.190.97.194:35714 64.233.165.155:443 0 0 0 CONNECT 64.233.165.155:443
160121152202.670 32076 00000 user 95.190.97.194:51043 173.194.32.190:443 433 4261 0 CONNECT 173.194.32.190:443
160121152212.492 32076 00000 user 95.190.97.194:35715 64.233.165.157:443 0 0 0 CONNECT 64.233.165.157:443
160121152212.671 32076 00000 user 95.190.97.194:34947 109.234.76.190:443 474 4503 0 CONNECT 109.234.76.190:443
160121152222.672 32076 00000 user 95.190.97.194:51056 173.194.32.131:443 433 4261 0 CONNECT 173.194.32.131:443

log - ver 0.7.1.3
160121152415.457 32076 00000 - XXXXXXXXXX:32076 XXXXXXXXXX0 0 0 0 Accepting connections [2503/3074796400]
160121152435.733 32076 00000 user 95.190.97.194:51085 173.194.32.158:443 0 0 0 CONNECT 173.194.32.158:443
160121152445.732 32076 00000 user 95.190.97.194:35011 109.234.76.190:443 0 0 0 CONNECT 109.234.76.190:443
160121152446.557 32076 00094 user 95.190.97.194:51082 173.194.32.158:443 902 4698 0 CONNECT 173.194.32.158:443
160121152446.557 32076 00094 user 95.190.97.194:35394 173.194.32.158:443 934 4698 0 CONNECT 173.194.32.158:443
160121152446.558 32076 00094 user 95.190.97.194:35267 74.125.205.95:443 961 39234 0 CONNECT 74.125.205.95:443
160121152446.560 32076 00094 user 95.190.97.194:35395 109.234.76.160:443 4649 31767 0 CONNECT 109.234.76.160:443
160121152446.560 32076 00094 user 95.190.97.194:35138 109.234.76.160:443 6413 72713 0 CONNECT 109.234.76.160:443
160121152446.561 32076 00094 user 95.190.97.194:35266 109.234.76.190:443 235 145 0 CONNECT 109.234.76.190:443
160121152446.563 32076 00094 user 95.190.97.194:51089 109.234.76.160:443 8120 19506 0 CONNECT 109.234.76.160:443
160121152446.563 32076 00094 user 95.190.97.194:35650 109.234.76.160:443 1810 4016 0 CONNECT 109.234.76.160:443
160121152446.564 32076 00094 user 95.190.97.194:35651 173.194.32.167:443 1867 16359 0 CONNECT 173.194.32.167:443
160121152446.566 32076 00094 user 95.190.97.194:35010 109.234.76.190:443 3138 10720 0 CONNECT 109.234.76.190:443
160121152446.566 32076 00094 user 95.190.97.194:51094 109.234.76.190:443 3804 19225 0 CONNECT 109.234.76.190:443
160121152446.566 32076 00094 user 95.190.97.194:51088 109.234.76.160:443 6478 30059 0 CONNECT 109.234.76.160:443
160121152446.568 32076 00094 user 95.190.97.194:51095 109.234.76.190:443 1142 8854 0 CONNECT 109.234.76.190:443
160121152446.568 32076 00094 user 95.190.97.194:51096 109.234.76.190:443 1142 6513 0 CONNECT 109.234.76.190:443
160121152446.570 32076 00094 user 95.190.97.194:35522 173.194.32.167:443 1637 608 0 CONNECT 173.194.32.167:443
160121152446.570 32076 00094 user 95.190.97.194:51097 109.234.76.190:443 1728 18148 0 CONNECT 109.234.76.190:443
160121152446.570 32076 00094 user 95.190.97.194:35139 109.234.76.160:443 1794 2496 0 CONNECT 109.234.76.160:443

**Comment by z3APA3A** [comment]
В обоих логах видно, что часть запросов у вас проходит (код ошибки 00000) и часть не проходит (код ошибки 00000 или 00094). Поищите проблемы с сетью, попробуйте проверить доступность порта с прокси-сервера.

**Comment by shark136** [comment]
Конфиг тот же самый, что я уже давал. Всё работает до 0.7.1.3 включительно (уже 2 года), а вот после перехода на ветку 0.8 согласно логов.
Меняю 0.8 на 0.7 ветку и всё отлично.
Могу дать данные для доступа, ничего секретного там нету )

**Comment by z3APA3A** [comment]
Fixed with 375a2c9f6e694f528757614fff0455a4e9425076

**Comment by z3APA3A** [comment]
0.8.2 released, should fix the issue
