### ISSUE TITLE
настройки сервера на хай лоад // HIGH LOAD SERVER 3proxy SETTINGS ISSUE

### ISSUE THREAD

**Issue by viktorbuterin** [z3APA3A/3proxy#311]
Всем привет!
у нас такая мега проблема, даже админы с очень опытом серьезным не могут разобраться.
Опишу ситуацию - имеем два сервера для клиентов и один сервер-хаб, через который гоняем трафик с этих двух клиентских серверов.
Работает ваша три прокси.
Настройки выкрутили как нам кажется везде на максимум!
НО! 32-ядерный сервер-хаб почти незагруженный по процам (память три прокси как известно почти вообще не юзает), так вот не справляется с нагрузкой, очень часто на клиентских серверах отваливается соединение и мы получаем refused connection  и прочую ерунду.
Htop хаба показывает в среднем такие значения: 
Tasks: 150, 32000 thr; 1 running 
Load average: 2 2 2

ss -s показывает:

ss -s
Total: 49408 (kernel 0)
TCP:   55205 (estab 39903, closed 6007, orphaned 2, synrecv 0, timewait 5993/0), ports 0

Transport Total     IP        IPv6
*	  0         -         -        
RAW	  0         0         0        
UDP	  0         0         0        
TCP	  49198     49197     1        
INET	  49198     49197     1        
FRAG	  0         0         0        

мы уже всё пересмотрели, везде проверили какие настройки на хай лоад настроить можно было  - все сделали.

выражается проблема в основном так что соединение просто обрывается в самом начале запроса к какому-либо ресурсу через например файрфокс с настройкой прокси. причем если тут же нажать обновить страницу - чаще всего страница сразу же начинает подгружаться. 

вопрос -почему хабу может быть плохо ? 
помогите, уже год целый то и дело сталкиваемся с этим, уже не знаем что делать.
спасибо!
--------------------
Hello!
we have such a mega problem, even admins with very serious experience can not figure it out.
I will describe the situation - we have two servers for clients and one server hub through which we drive traffic from these two client servers.
Your three proxies are working.
Settings twisted as it seems to us everywhere to the maximum!
BUT! A 32-core hub server is almost unloaded in terms of proxy (as it’s known, the memory of three proxies almost does not work at all), it doesn’t cope with the load, very often the connection falls off on client servers and we get refused connection and other nonsense.
Htop hub shows on average such values:
Tasks: 150, 32000 thr; 1 running
Load average: 2 2 2

ss -s shows:

ss -s
Total: 49408 (kernel 0)
TCP: 55205 (estab 39903, closed 6007, orphaned 2, synrecv 0, timewait 5993/0), ports 0

Transport Total IP IPv6
* 0 - -
RAW 0 0 0
UDP 0 0 0
TCP 49198 49197 1
INET 49198 49197 1
FRAG 0 0 0

we have already reviewed everything, everywhere we checked what settings on the high-load it was possible to configure - we did everything.

the problem is mainly expressed so that the connection is simply terminated at the very beginning of the request to a resource through, for example, a firefox with a proxy setting. and if you immediately click refresh the page - most often the page immediately begins to load.

the question is - why the hub can be bad?
help, for a whole year now and again we come across this, we no longer know what to do.
thank!

**Comment by z3APA3A** [comment]
Я не могу что-то добавить к https://3proxy.ru/highload.asp
Ты упираешься либо в файловые дискрипторы (сокеты) либо в эфемерные порты либо в потоки. Про эфимерные порты все написано в статье выше. Поищи как поднять системные ограничения в твоем дистрибутиве. Например здесь
https://stackoverflow.com/a/26190804/9294715
есть хороший ответ от Vladimir Kunschikov с примерами как поднять системные лимиты на потоки.
