### ISSUE TITLE
Certificates for SSLPlugin plugin

### ISSUE THREAD

**Issue by maronz** [z3APA3A/3proxy#312]
I wanted to have "play around" with 3proxy and the SSLPlugin plugin.

In a first step, I've successfully build the required files using the v0.8.2 sources on a Linux Mint system (v18.3). That means I've installed the 'libssl-dev' package, added 'SSLPlugin' to the 'PLUGINS = ...' line in the 'Makefile.Linux' (and also made the required additions to the 'LIBS = ...' entry). I then copied the three certificate files (i.e. 3proxy.key, 3proxy.pem, and server.key) from the Windows binary (i.e. '3proxy-0.8.12.zip') to a 'cache' directory, and created a minimal config file.

A simple test with:
`    curl -kx localhost:3128 https://example.com | wc -c`
showed that (as expected)1270 bytes were transmitted, and the following line appeared in the LOG:
`    181022083539.042 3128 00000 - 127.0.0.1:37916 93.184.216.34:443 120 1592 0 GET http://example.com/ HTTP/1.1`

I then repeated all the steps, but this time using the current 'devel' sources (i.e. 'cc503ba'). Using again the same certificate files resulted in a failure message (i.e. `curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.`) and the LOG showed:
`    181022083825.292 3128 00000 - 127.0.0.1:37924 93.184.216.34:443 0 0 0 CONNECT example.com:443 HTTP/1.1`

I now wonder what 'openssl' commands one would need to use to generate a fresh set of certificate files. I guess that would anyway be required pretty soon, as I believe to have seen a certificate expiry date some time in the next month.

**Comment by z3APA3A** [comment]
In "devel" syntaxis of SSLPlugin is slightly changed, now command ssl_mitm is required in addition to configuring plugin, see
https://3proxy.ru/plugins/SSLPlugin/

**Comment by akohlsmith** [comment]
This answer does not answer the question.

There are three files required: `3proxy.pem`, `3proxy.key` and `server.key`. The question asks how to generate these files.

I have tried `openssl req -new -x509 -extensions v3_ca -keyout 3proxy.key -out 3proxy.pem -days 3650` 

This generates two files, and when starting 3proxy it asks for the passphrase, but then says SSL cert/keys failed to init:

```
# /bin/3proxy /etc/3proxy/3proxy.cfg
Enter PEM pass phrase:
failed to init SSL certificate / keys
```

The source file `SSLPlugin/my_ssl.c` suggests that `server.key` must be a private key, but I do not understand how to generate this file, and this is what the original question is also asking.

**Comment by z3APA3A** [comment]
Use -nodes to generate certificates without passphrase. server.key can be any key, you can use a copy of 3proxy.key or generate new one.
