### ISSUE TITLE
icqpr в develop версии

### ISSUE THREAD

**Issue by halit63** [z3APA3A/3proxy#313]
При запуске последней на текущий момент версии прокси с рабочим конфигом, включающим в себя команду icqpr, выдается ошибка 

C:\>3proxy
Unknown command: 'icqpr' line 797

В прошлогодней версии всё работает. Что-то изменилось?

**Comment by z3APA3A** [comment]
icqpr не разрабатывается и не поддерживается, т.к. протокол AOL OSCAR depricated c 2014 года, современные клиенты ICQ его не используют, в частности по причинам безопасности. Если его кто-то еще использует, стоит как можно быстрей от него отказаться.
