### ISSUE TITLE
Периодически возникает 00012 ошибка

### ISSUE THREAD

**Issue by andrejshulaev** [z3APA3A/3proxy#314]
добрый вечер

иногда перестает корректно работать прокси со следующим конфигом:

```daemon
log /usr/local/etc/3proxy/logs/3proxy30001.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 1
users test:CL:test
auth strong
allow test
socks -p30001 -e192.168.101.34
nserver 192.168.101.1
```

Логи:
```
1540398287.810 SOCK5.30001 00100 test 192.168.0.1:60204 192.168.101.34:0 0 0 0 CONNECT_0.0.0.0:0
1540398295.554 SOCK5.30001 00100 test 192.168.0.1:60207 192.168.101.34:0 0 0 0 CONNECT_0.0.0.0:0
1540398303.813 SOCK5.30001 00100 test 192.168.0.1:60216 192.168.101.34:0 0 0 0 CONNECT_0.0.0.0:0
1540402792.575 SOCK5.30001 00012 test 192.168.0.1:50140 64.233.162.99:80 0 0 0 CONNECT_www.google.com:80
1540402811.028 SOCK5.30001 00012 test 192.168.0.1:50153 92.123.155.49:80 0 0 0 CONNECT_detectportal.firefox.com:80
```
Помогает иногда перезагрузка прокси, всегда сервера целиком.

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS
это значит что не получилось прибиндить сокет к внешнему IP. Это может быть из-за недоступности интерфейса либо из-за нехватки эфемерных портов (при большом количестве одновременных соединений)
https://3proxy.ru/doc/highload.html

**Comment by z3APA3A** [comment]
Если не один из вариантов не подходит, убедись что используется актуальная версия, несколько ошибок, которые могли приводить к подобному поведению правились.
