### ISSUE TITLE
Proxy chains

### ISSUE THREAD

**Issue by pgswow** [z3APA3A/3proxy#315]
Здравствуйте!
Может ли 3proxy работать в режиме цепочек без указания parent в конфиге, а указывая цепочку из серверов в клиентской программе, например Super Socks5Cap?, так как заведомо количество узлов в цепочке может быть неизвестно, и сам состав цепочки заранее не известен.

**Comment by z3APA3A** [comment]
Может, от прокси здесь ничего не требуется кроме установки соединения до первого прокси, все остальное делает сам клиент.
