### ISSUE TITLE
Config and system Enviroment

### ISSUE THREAD

**Issue by torquemada163** [z3APA3A/3proxy#318]
Can I use enviroment variables in config file? 
How to call them?

**Comment by z3APA3A** [comment]
you can use inline values from the file via $, e.g.

`external $/path/to/file`

and "system" command

```
system "echo $VARNAME>>/path/to/file"
external $/path/to/file
```

**Comment by torquemada163** [comment]
Я пытаюсь все это упаковать в Docker.
Хочу передавать значение users через переменную окружения при запуске Docker. Как это лучше организовать?

**Comment by z3APA3A** [comment]
Ну можно так и сделать, как в предыдущем примере.
```
system "echo $PROXY_USERS>/var/run/3proxy/users"
users $/var/run/3proxy/users
system "unlink /var/run/3proxy/users"
```
