### ISSUE TITLE
FreeBSD: 3proxy 0.8.1 can't bind to interface

### ISSUE THREAD

**Issue by timp87** [z3APA3A/3proxy#32]
Hi!
After upgrading 3proxy from 0.7.1.3 to 0.8.1 (0.8.0 has the same problem) it stopped working on FreeBSD (at least).

$ tail /var/log/3proxy.log.2016.01.22
1453464413.007  ADMIN.80 00000 - 127.0.0.1:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464413.008  DNSPR.53 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464413.008  POP3P.110 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464413.008  TCPPM.25 00000 - 192.168.122.70:25 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.816  ADMIN.80 00000 - 127.0.0.1:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.817  POP3P.110 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.827  TCPPM.25 00000 - 192.168.122.70:25 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.827  PROXY.3128 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.827  SOCKS.1080 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
1453464425.828  DNSPR.53 00000 - 192.168.122.70:0 192.168.122.70:9217 0 0 0 bind():_Invalid_argument
etc

$ sockstat | grep 3pro
root     3proxy     2767  5  udp4   *:*                   *:*
root     3proxy     2767  6  tcp4   *:*                   *:*
root     3proxy     2767  7  tcp4   *:*                   *:*
root     3proxy     2767  8  tcp4   *:*                   *:*
root     3proxy     2767  9  tcp4   *:*                   *:*
root     3proxy     2767  10 tcp4   *:*                   *:*

I used config file from the distribution. The only change is nserver, extrenal and internal options.

**Comment by z3APA3A** [comment]
add your config and results of ifconfig please (or mail to 3proxy@3proxy.ru)

**Comment by z3APA3A** [comment]
Records from log with "Accepting connections" can also be useful.

**Comment by timp87** [comment]
$  ifconfig
vtnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
	options=6c07bb<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,JUMBO_MTU,VLAN_HWCSUM,TSO4,TSO6,LRO,VLAN_HWTSO,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
	ether 52:54:00:3e:ba:e5
	inet 192.168.122.70 netmask 0xffffff00 broadcast 192.168.122.255 
	nd6 options=29<PERFORMNUD,IFDISABLED,AUTO_LINKLOCAL>
	media: Ethernet 10Gbase-T <full-duplex>
	status: active
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
	options=600003<RXCSUM,TXCSUM,RXCSUM_IPV6,TXCSUM_IPV6>
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2 
	inet 127.0.0.1 netmask 0xff000000 
	nd6 options=21<PERFORMNUD,AUTO_LINKLOCAL>
	groups: lo 

$ egrep -v '^(#|$)' /usr/local/etc/3proxy.cfg
system "echo Hello world!"
nserver 192.168.122.1
nserver 192.168.122.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
users 3APA3A:CL:3apa3a "test:CR:$1$qwer$CHFTUFGqkjue9HyhcMHEe1"
daemon
log /var/log/3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver rar rar a -df -inul %A %F
rotate 30
auth iponly
external 192.168.122.70
internal 192.168.122.70
auth none
dnspr
auth strong
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -n
auth none
pop3p
tcppm 25 mail.my.provider 25
auth strong
flush
allow 3APA3A,test
maxconn 20
socks
auth strong
flush
internal 127.0.0.1
allow 3APA3A 127.0.0.1
maxconn 3
admin

**Comment by z3APA3A** [comment]
Please try with this commit: 4af5f2fde756c75d4394571b56d6a53e8b342fba

**Comment by timp87** [comment]
Seem like it helped!

**Comment by timp87** [comment]
When do you plan to release fixed version? Just for my information.

**Comment by z3APA3A** [comment]
in next 2 days.

**Comment by z3APA3A** [comment]
0.8.2 released, should fix the issue

**Comment by z3APA3A** [comment]
Previous bugfix was incomplete, fec0da52af04615c17dcf5ab6b91ca8afbae1c64 should fix the problem completely.

**Comment by timp87** [comment]
Well, hope so. Waiting for the 0.8.3 version.

**Comment by z3APA3A** [comment]
0.8.3 published.
