### ISSUE TITLE
Debian9 amd64: service doesn't run

### ISSUE THREAD

**Issue by IvankoB** [z3APA3A/3proxy#326]

**Comment by IvankoB** [comment]
It exits abnormally on "double free or corruption".

To fix this : 
1) chroot-ing must be excluded form /etc/3proxy/3proxy.cfg
2) so /usr/local/3proxt/conf/3proxy.cfg should use full paths within

Also for unattended start & usage /etc/init.d/3proxy should start from:
ulimit -n 99999
mkdir -p /var/run/3proxy/

**Comment by z3APA3A** [comment]
Please provide your config (passwords/usernames/ip information is not required and can be removed or masked) and information about proxy version.

**Comment by IvankoB** [comment]
How to insert image in this thread? The VM wheret the issue occurs can't pass text clipboard to the host for some reason.

**Comment by IvankoB** [comment]
The service doesn't start even with the default (after "make -f Makefile.Linux install") configuration.

Now the configs & daemon in mine are fixed thus service runs OK.

**Comment by z3APA3A** [comment]
"double free or corruption" means there is a binary error, to find and fix it I need detailed configuration. Binaries and core file can be very useful.

**Comment by IvankoB** [comment]
Hmm, now the DF|C error doesn't happen, not after fully clean reinstallation though.
But the command "mkdir -p /var/run/3proxy" before first run of the service is still required for the 'init.d' script to succeed.
The 'ulimit -n 99999' command (best in the 'init.d' script) is highly desirable so that DEBIAN doesn't warn  about possible lack of file descriptors.

**Comment by z3APA3A** [comment]
rundir creation was added here:
https://github.com/z3APA3A/3proxy/commit/dec10d4eddb2606f717bcb92a91c178528dc5256

Running 3proxy under high load / with large number of connections require additional settings, setting ulimit is not enough. Resources requirements are explained here:
https://3proxy.ru/doc/highload.html
For default maxconn values changing ulimit is usually not required.
