### ISSUE TITLE
Добавить поля "код состояния HTTP" и "MIME тип/подтип" в logformat для proxy

### ISSUE THREAD

**Issue by Bogdan107** [z3APA3A/3proxy#328]
Команда "curl -I www.google.com/favicon.ico" выдаёт (пример, сокращённый):
_HTTP/1.1 200 OK
Content-Type: image/x-icon_

В первой строке на позиции №2 указано число 200 - это <код состояния HTTP>. Этот код - обязательный атрибут http-заголовков.
В одной из строк указано поле "Content-Type" со значением "image/x-icon" - это <MIME тип/подтип>, описывающий тип содержимого. Данное поле в https-соединениях зашифровано и для 
прокси-сервера недоступно.

Прошу добавить поддержку параметра "код состояния HTTP" и "MIME тип/подтип" в логах PROXY.
"код состояния HTTP" - согласно RFC 7231.
"MIME тип/подтип" - согласно RFC 4855.
Предлагаю разместить эти значения в поле лога %T (service specific text), в позициях №4 и №5.

Поскольку эти атрибуты - базовые для соединения, то полагаю, что и 3proxy их получает в ответах от сервера и может ими оперировать. При этом выдумывать и анализировать чего-то без надобности - достаточно взять значения прямо из пакета данных и сложить в лог. Чтобы достать значение "URL", 3proxy распаковывает пакет запроса данных от клиента к серверу, а чтобы достать "код состояния" и "mime тип/подтип" - необходимо распаковать пакет ответа от сервера к клиенту.

Сейчас в логах PROXY поле %T выглядит так:
_"HEAD http://www.google.com/favicon.ico HTTP/1.1"_
Предлагаемый мною вариант выглядит так (для нешифрованных соединений):
_"HEAD http://www.google.com/favicon.ico HTTP/1.1 200 image/x-icon"_
или так (для шифрованных соединений):
_"CONNECT www.google.com:443 HTTP/1.1 200 -"_
В случае https/CONNECT поле "Content-Type" недоступно для 3proxy и вместо значения предлагаю выдавать стандартный "-" (признак отсутствия содержимого, выравнивает количесво параметров в строке).

Чтобы дополнительная раcпаковка ответного пакета не создавала задержек для высоконагруженных применений, предлагаю поддержку этих полей сделать опциональной - включать отдельной опцией конфигурации "logformat_proxy".

Сейчас формат поля %T (service specific text) можно описать как "%M %U %V", где:
- %M - метод доступа;
- %U - URL;
- %V - версия протокола HTTP.

Тогда для включения дополнительных полей (и, соответственно, дополнительных операций - дополнительной нагрузки на CPU) достаточно будет объявить в файле конфигурации опцию logformat_proxy со значением "%M %U %V %s %m", где:
- %s - код статуса соединения;
- %m - MIME тип/подтип содержимого.

**Comment by z3APA3A** [comment]
А есть ли смысл, с учетом того, что большая часть трафика сейчас идет с шифрованием?

**Comment by Bogdan107** [comment]
Сейчас в logformat для указания на конкретные елементы в %T используются не совсем очевидные формы записи %1-1T, %2-2T, и %3-3T (не совсем очевидные - это по себе сужу, ибо дошёл до них экспериментами, хотя даже руководство читал). Выведение формата строки %T в отдельный параметр конфигурации может упростить настройку формата вывода для каждого отдельного типа прокси (logformat_proxy - для PROXY, logformat_socks - для SOKS и т.д.).

MIME в CONNECT точно зашифровано. А вот код статуса соединения, предполагаю (не уверен), должен быть доступен для прокси даже при наличии шифрования.

**Comment by z3APA3A** [comment]
logformat можно отдельно задавать для каждого прокси через logformat. Все что идет внутри TLS включая все коды статусов не видно для прокси.

**Comment by z3APA3A** [comment]
В общем, реализовать это не сложно. Если еще будут запросы - сделаю, но пока смысла большого не вижу
