### ISSUE TITLE
Disconnect user who does not suit for new ACL after reconfiguration in runtime.

### ISSUE THREAD

**Issue by S-o-T** [z3APA3A/3proxy#33]
It will be quite logical to drop the established connections after reconfiguration in runtime, if that connections does not match new ACL.

Thanks.

**Comment by S-o-T** [comment]
А можно ли послать вам доната, с пожеланием реализации конкретного фичреквеста?)

**Comment by z3APA3A** [comment]
Можно.

**Comment by z3APA3A** [comment]
Если есть где - можешь попробовать devel-версию, но осторожней, я еще сам не тестировал.

**Comment by S-o-T** [comment]
В рабочем окружении под нагрузкой пока нет возможности потестировать, но ручками прогнал единичный конект - рвет после реконфигурации как и задумано.

**Comment by S-o-T** [comment]
Тестирую сейчас под нагрузкой (10-15 активных юзеров socks) последнюю дев версию. После релоада дропаются все соединения с 333 ошибкой.

**Comment by z3APA3A** [comment]
Попробуй текущий devel с последним фиксом

**Comment by S-o-T** [comment]
С последним фиксом все стало ок, рвутся только неразрешенные коннекты.
