### ISSUE TITLE
3proxy authentication with user and pass

### ISSUE THREAD

**Issue by Thomanphan** [z3APA3A/3proxy#331]
Hello
this is my code but don't work

I tried add allow user and ip but when I add it proxy will using real ip
111.236.74.60 is my ip, 127.0.0.1 9050 is tor ip and port

```
allow user
allow * 111.236.74.60 * *
parent 1000 socks5+ 127.0.0.1 9050
socks -p1337
flush
```

**Comment by z3APA3A** [comment]
'parent' only affects last 'allow' command, you should specify 'parent' after each 'allow' command.

**Comment by Thomanphan** [comment]
But how I can add socks with same port allow user and ip ?
