### ISSUE TITLE
can't install on windows 2012 R2 x64

### ISSUE THREAD

**Issue by linkodd** [z3APA3A/3proxy#333]
Ошибок нет, просто не смог запустить службу. Конфиг простейший. 
Тот же самый конфиг на windows 7 x64 спокойно "взлетел".
Вопрос. Куда копать и что делать?

**Comment by linkodd** [comment]
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
service
log c:\3proxy\logs\3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver rar rar a -df -inul %A %F
rotate 30
auth none
external 193.150.102.86
internal 127.0.0.1
socks
proxy

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#SERVICE

**Comment by linkodd** [comment]
Ок. Я поспешил с ошибкой, но проблема осталась. Винда 2012 не хочет запускать как службу ее. Без службы все ок. В противном случае ошибка 1053 служба не ответила своевременно.

**Comment by z3APA3A** [comment]
Там все написано, проверьте есть ли у эккаунта с которым работает служба доступ к исполняемому файлу, файлу конфига, логу и т.п.
