### ISSUE TITLE
Not finding my config file

### ISSUE THREAD

**Issue by mmslimjim** [z3APA3A/3proxy#334]
Hey, I have everything properly setup but when i go to start it, this is what i get. Thanks

Starting 3Proxy
/etc/3proxy/3proxy.cfg: 4: /etc/3proxy/3proxy.cfg: daemon: not found
/etc/3proxy/3proxy.cfg: 7: /etc/3proxy/3proxy.cfg: nserver: not found
/etc/3proxy/3proxy.cfg: 8: /etc/3proxy/3proxy.cfg: nserver: not found
/etc/3proxy/3proxy.cfg: 10: /etc/3proxy/3proxy.cfg: nscache: not found
/etc/3proxy/3proxy.cfg: 13: /etc/3proxy/3proxy.cfg: timeouts: not found
/etc/3proxy/3proxy.cfg: 17: /etc/3proxy/3proxy.cfg: log: not found
/etc/3proxy/3proxy.cfg: 19: /etc/3proxy/3proxy.cfg: logformat: not found
/etc/3proxy/3proxy.cfg: 21: /etc/3proxy/3proxy.cfg: archiver: not found
/etc/3proxy/3proxy.cfg: 23: /etc/3proxy/3proxy.cfg: rotate: not found
/etc/3proxy/3proxy.cfg: 25: /etc/3proxy/3proxy.cfg: auth: not found
/etc/3proxy/3proxy.cfg: 26: /etc/3proxy/3proxy.cfg: allow: not found

**Comment by z3APA3A** [comment]
You are trying to run config file as executable instead of running 3proxy. If for some reason you really want to run config file as a script, you need to put something like
`#!/path/to/3proxy/binary
`
to  beginning.

**Comment by mmslimjim** [comment]
Thanks ill give it a try

**Comment by mmslimjim** [comment]
Im having issues trying to setup my server with multiple configured IPs. By
chance do you have an instruction list or found a good one online? If not,
no worries. Thanks

**Comment by z3APA3A** [comment]
Examples can be found e.g. here:
https://3proxy.ru/highload.asp
