### ISSUE TITLE
Перенаправление UDP

### ISSUE THREAD

**Issue by ZarRoman** [z3APA3A/3proxy#335]
Доброго времени суток.
Пытаюсь перенаправить UDP порт. в конфиге создана строка 
udppm 2000 192.168.1.3 1111
При попытку обращения к ресурсу в логах возникает ошибка
190221125959.620 2000 00000 - 0.0.0.0:2000 0.0.0.0:0 0 0 0 Accepting connections [2184/8000]
190221125959.621 80 00000 - 0.0.0.0:80 0.0.0.0:0 0 0 0 Accepting connections [2184/5148]
190221130107.466 2000 00092 - 192.168.192.2:2005 192.168.1.3:1111 1 1 0
190221130207.488 2000 00092 - 192.168.192.2:2005 192.168.1.3:1111 3 30 0
190221130307.512 2000 00092 - 192.168.192.2:2005 192.168.1.3:1111 3 30 0
Как я понимаю при первом обращении ошибка 1 1 0
при повторных обращениях ошибка 3 30 0
При этом перенаправление TCP порта строкой
tcppm 80 192.168.1.1 80
работает нормально. Подскажите пожалуйста что делаю не так? при этом сам конфиг состоит из трёх строк
log
udppm 2000 192.168.1.3 1111
tcppm 80 192.168.1.1 80

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS
У тебя UDP mapping завершается по таймауту, для UDP это нормально, т.к. других способов завершения и не бывает, но чтобы не менялся порт между прокси и сервером лучше поднять таймаут UDP маппинга через timeouts (параметр STRING_LONG по умолчанию 60).

**Comment by ZarRoman** [comment]
таймаут udp на клиентской машине выставлял до 5000 и при первом обращении клиент зависал на те же 5 секунд ожидая ответа. так же пробовал udppm 1111 192.168.1.3 1111 - результата это не дало. timeouts 1800 так же проблему не решил
190221145128.947 1111 00092 - 192.168.192.2:2005 192.168.1.3:1111 1 1 0
190221145228.968 1111 00092 - 192.168.192.2:2005 192.168.1.3:1111 3 30 0
190221145328.970 1111 00092 - 192.168.192.2:2005 192.168.1.3:1111 3 0 0

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/man3/3proxy.cfg.3.html и там timeouts

**Comment by ZarRoman** [comment]
ссделал
timeouts 1 5 30 300 180 1800 15 60 15 5
ситуация не поменялась
когда сделал 
timeouts 1 5 30 1800 180 1800 15 60 15 5
в логе записей так и не дождался

**Comment by z3APA3A** [comment]
Значит соединение установлено и держится, будет держаться полчаса. А ты уверен что протокол в принципе такой, что будет работать через маппинг порта?

**Comment by ZarRoman** [comment]
через проброс порта на роутере работает.

**Comment by ZarRoman** [comment]
И через вот это вот заработало [Simple UDP proxy/pipe 0.4.1 ](https://aluigi.altervista.org/mytoolz.htm), стандартный таймаут тоже 60. Но 3proxy больше нравится. хотелось бы разобраться почему не работает....

**Comment by Str1ker17** [comment]
Аналогичный вопрос. Хочу сделать портмаппинг на второй DNS сервер:

`udppm 1053 10.0.0.33 53`

Однако, эта конструкция выдерживает только один DNS-запрос, а потом портмаппинг отваливается с ошибкой 92.
Полагаю, дело в том, что второй и следующие запросы приходят с другого source порта. Это так и было задумано? UDP portmapping нельзя использовать для множественных подключений?
Пробовал и с опцией -s тоже - не помогло.

P.S.: если будет вопрос, на кой мне мапить DNS - нужно сделать доступными два разных сервера. Если бы dnspr умел в такое, например
```
nserver 192.168.0.1
dnspr
nserver 10.0.0.33
dnspr -p1053
```
я бы был очень рад, но директивы nserver суммируются, и запросы к 1053 порту всё равно улетят на 192.168.0.1 :(
помог бы аналог команды flush для сброса всех настроек, а не только ACL.

**Comment by z3APA3A** [comment]
udppm -s должен работать в данном случае, если не работает - опиши какая проблема возникает. Можно так же запустить несколько экземпляров 3proxy с разными конфигурациями nservers, вообще нет причин держать один экземпляр 3proxy, работать с несколькими конфигурациями обычно проще и обновлять их проще.

**Comment by Str1ker17** [comment]
Спасибо за ответ!

> вообще нет причин держать один экземпляр 3proxy
А если хочется 3proxy крутить как сервис в винде? Это ж только один экземпляр, с одной конфигурацией.

> udppm -s должен работать в данном случае, если не работает - опиши какая проблема возникает
Попробую сегодня с ней ещё, может действительно где-то опечатался. Сохраню логи, если так и не получится завести - опишу

**Comment by z3APA3A** [comment]
Что мешает насоздавать столько сервисов, сколько надо?
sc create 3proxy-2 binpath="path/to/3proxy path/to/config" start= auto

**Comment by Str1ker17** [comment]
Да, с `-s` и правда работает, видимо вчера впопыхах отредактировал копию конфига вместо самого конфига =) Спасибо! Пользуюсь 3proxy уже почти 12 лет, буду и дальше =)

@ZarRoman тебе тоже должно помочь

**Comment by z3APA3A** [comment]
udppm сейчас действительно требует отдельного маппинга для каждого клиента и не будет работать если с двух клиентов или двух портов одного клиента одновременно идут запросы в один маппинг, потому что прокси не открывает дополнительного порта для каждого порта клиента. -s помогает это решить для некоторых протоколов типа DNS, но не в общем случае не решает проблемы.

**Comment by Str1ker17** [comment]
Хм, кажется я понял: если схема пересылки пакетов один запрос - один ответ обломается, например, второй DNS-запрос на udppm придёт раньше, чем будет получен ответ от вышестоящего сервера, то программа не сможет различить, в какой source port послать DNS-ответ. Вероятно, отправит его туда, откуда был последний запрос, и тогда первый запрос не получит ответа.
То есть схема с udppm -s рабочая, но не очень устойчивая. Тут бы dnspr использовать (знает о внутренностях протокола, и может соотносить source port с хостнеймом) или socks (на каждую UDP-ассоциацию выделяет отдельный destination port). Так?

**Comment by z3APA3A** [comment]
в случае -s схема устойчивая, но работает только с сервисами которые шлют 1 запрос и ожидают 1 ответ

**Comment by Str1ker17** [comment]
Что будет, если кинуть второй DNS-запрос с другого source port, пока не пришёл ответ на первый (очень маленький интервал между двумя запросами/пакет потерялся на пути от 3proxy до DNS-сервера/сервер был в дауне)?

**Comment by z3APA3A** [comment]
запросы обрабатываются независимо, ответ идет на тот порт, с которого пришел запрос

**Comment by Str1ker17** [comment]
Так, если всё-таки послать два DNS-запроса подряд, то поток udppm крашится и больше не поднимается:

211102170624.973 1053 00000 - 192.168.75.134:1813 10.0.0.33:53 33 49 0
211102170624.973 1053 00000 - 192.168.75.134:1813 10.0.0.33:53 33 49 0
211102170624.974 1053 00214 - 192.168.75.1:1053 0.0.0.0:0 0 0 0
211102170624.975 1053 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 poll(): Unknown error/10038
211102170624.975 1053 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting thread

(192.168.75.1 - интерфейс на котором 3proxy, 192.168.75.134 - интерфейс клиента, 10.0.0.33 - адрес DNS-сервера)
Было бы неплохо пофиксить. Если нужна помощь - могу сам накидать pull request
