### ISSUE TITLE
Error 00100 - 502 on some action.

### ISSUE THREAD

**Issue by BrokedTV** [z3APA3A/3proxy#336]
Hi, i have been stuck for days and i tried so many different cfg and still can't make the proxy run properly.
I have 2 connection on a local machine. I can use the proxy from the browser, both local and remote.
I need to use the proxy on a platform, already opened the ports on the server. I can add the proxy to the platform, and i can do action on the account i use the proxy on, but i cannot add the accounts to the platform with this proxy.
Every time i get a 502 error and from the log i always see this

16 46 19 PROXY.3129 00000 lolaria vpsip:39154 31.11.94.245:80 120 241 0 GET_http://www.targetsite.com/_HTTP/1.1
16 46 20 PROXY.3129 00000 lolaria vpsip:39156 31.11.94.245:443 799 36477 0 CONNECT_www.targetsite.com:443_HTTP/1.1
16 46 22 PROXY.3129 00100 - vpsip:39160 0.0.0.0:0 0 0 0 CONNECT_i\.targetsite.com:443_HTTP/1.1
16 46 22 PROXY.3129 00000 lolaria vpsip:39158 31.11.94.245:443 9001 16147 0 CONNECT_b.i.targetsite.com:443_HTTP/1.1

error 00100

This is my .CFG ( at least the lastest version)

#!/usr/local/bin/3proxy
daemon
#pidfile /etc/3proxy/3proxy.pid
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
users lolaria:CL:asji7239dsf
log /home/pi/logpx/3proxy.log D
logformat "- +_L%H %M %S %N.%p %E %U %C:%c %R:%r %O %I %h %T"
#archiver rar rar a -df -inul %A %F
#rotate 30
setgid 1000
setuid 1000
auth iponly
allow * VPS IP
flush
proxy -p3129 -e192.168.8.100

I tried with auth strong, no auth etc etc etc
I would really appreciate if you can help me sort this out. 
Thanks in advance!

**Comment by z3APA3A** [comment]
Error 100 means proxy fails to resolve the name in request
https://3proxy.ru/howtoe.asp#ERRORS

**Comment by BrokedTV** [comment]
I already checked the error code on the wiki, but still haven't figured out how to solve the porblem. I read lot's of post in here to try to get some clue but still haven't found the way.

Is a Name server problem? i tried to modify, add 8844, use 1111, remove them...
i'm kinda lost at this point

**Comment by BrokedTV** [comment]
@z3apa3a can you point me somewhere? Some other guide/faq/anything

**Comment by z3APA3A** [comment]
Try resolving 
nslookup -type=A i.targetsite.com 8.8.8.8
where i.targetsite.com is problematic hostname.

**Comment by BrokedTV** [comment]
@z3APA3A
pi@raspberrypi:~ $ nslookup -type=A i.instagram.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
i.instagram.com canonical name = instagram.c10r.facebook.com.
Name:   instagram.c10r.facebook.com
Address: 31.13.86.52

earlier i was able to add an account to the platform, now i'm not, if i check my dns while using the proxy it say i'm using google dns.


10 08 19 PROXY.3129 00000 - 285:837:37:11:49610 31.13.86.174:80 120 241 0 GET_http://www.instagram.com/_HTTP/1.1
10 08 20 PROXY.3129 00000 - 285:837:37:11:49612 31.13.86.174:443 799 37016 0 CONNECT_www.instagram.com:443_HTTP/1.1
10 08 22 PROXY.3129 00100 - 285:837:37:11:49616 0.0.0.0:0 0 0 0 CONNECT_i\.instagram.com:443_HTTP/1.1
10 08 22 PROXY.3129 00000 - 285:837:37:11:49614 31.13.86.174:443 9001 16187 0 CONNECT_b.i.instagram.com:443_HTTP/1.1


completely stuck at this point.

**Comment by BrokedTV** [comment]
Hey @z3APA3A, don't wanna be boring, or spoonfeeded, i know that you give this projet lots of time, but i'm really lost, have spent days and days and i can't really get to the solution.

**Comment by z3APA3A** [comment]
Sorry, but I have nothing to add, 00100 means proxy fails to resolve the name with given timeout. I can recommend to avoid public DNS, specially if you have large number of requests and to use local caching recursor. More recommendations are here:
https://3proxy.ru/highload.asp

**Comment by z3APA3A** [comment]
Also, it looks like you're running proxy behind NAT. Each name resolution via external DNS requires separate NAT UDP mapping, these mapping are usually long living. If NAT is performed by SOHO-grade router it can be a problem. In this case, it may be better to configure recursor on the router itself.
