### ISSUE TITLE
Permission denied в логах 

### ISSUE THREAD

**Issue by kombinrator** [z3APA3A/3proxy#339]
setgid 118
setuid 111
nserver 8.8.4.4
nserver 8.8.8.8
#nserver 82.209.240.241
#nserver 82.209.243.241
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
users $/etc/3proxy/.proxyauth
daemon
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
#log /dev/null
maxconn 64
auth cache strong
proxy -n -p10001 -a
socks -p10000 -a
proxy -n -a -i87.252.241.57 -e87.252.241.57 -p10001
socks -i87.252.241.57 -e87.252.241.57 -p10000 -a
dnspr

permisiion denid в логах с 
nserver 82.209.240.241
nserver 82.209.243.241

и работает с 
nserver 8.8.4.4
nserver 8.8.8.8
как исправить ?

на другом vds с nserver 82.209.240.241 работает , на текущем нет

**Comment by z3APA3A** [comment]
Исправить, прописав правильный резолвер. Лучше всего установить локальный резолвер на хост с 3proxy чтобы не ходить в резолвер по сети.
