### ISSUE TITLE
0.8.3 не компилируется

### ISSUE THREAD

**Issue by shark136** [z3APA3A/3proxy#34]
proxymain.c: In function 'mainfunc':
proxymain.c:319: error: expected ')' before 'BUILDDATE'
proxymain.c:350: error: expected ')' before 'BUILDDATE'
make[1]: *** [mainfunc.o] Error 1
make[1]: Leaving directory `/root/3proxy-3proxy-0.8.3/src'
make: *** [all] Error 2

**Comment by timp87** [comment]
У меня на FreeBSD версия 0.8.3 тоже не компилируется
./proxymain.c:319:41: error: expected ')'
                fprintf(stderr, "%s of " VERSION " (" BUILDDATE ")\n"

**Comment by z3APA3A** [comment]
Поправил релиз, менять номер не стал, т.к. там там нет правок по функционалу, поправлен только файл с версией релиза.
