### ISSUE TITLE
3proxy: socks service stops serving connections

### ISSUE THREAD

**Issue by diizzyy** [z3APA3A/3proxy#340]
Hi,
Not sure if I'm doing anything (same config works fine on FreeBSD 12.0 running 0.8.12) but on Linux 4.14 with 0.9-devel (https://github.com/z3APA3A/3proxy/commit/37cebe08af771cf6c27b05f4868ca1a1d1ed04b5) serves a few connections then pretty much stops serving any connections.

```TCP: request_sock_TCP: Possible SYN flooding on port 1080. Sending cookies.``` shows up pretty much instantly and tuning ```net.core.somaxconn``` (2048) and ```net.ipv4.tcp_max_syn_backlog``` (512) doesn't seem to help. Quite a bit of RAM is still available and CPU isn't overloaded.

config (internal and external changed):
```
daemon
internal 192.X.X.X
external 92.X.X.X
auth none
allow *
flush
socks -p1080 -u
```

Hardware: D-Link DIR-860L B1 (MIPS)
Software:
OpenWrt (master)
Linux 4.14.103
musl 1.1.21

https://github.com/diizzyy/packages/commits/net-3proxy (last 2 commits are relevant for 3proxy)

Client software:
Chrome and Firefox

**Comment by z3APA3A** [comment]
3proxy doesn't generate an error message like this, if you got it, you probably have some flood protection mechanism (DDoS protection) and you have to check the ratelimits for it or disable it completely.
There is no need to set up backlog, 3proxy adjusts backlog automatically based on  'maxconn' parameter.

**Comment by z3APA3A** [comment]
P.S. last time I was trying musl, it was not supporting splice(), so I'm not sure how you were able to build 3proxy for musl with -DWITHSPLICE and I strongly advice to use glibc. glibc and musl can be used at the same time on OpenWRT, just add glibc shared libraries.

**Comment by diizzyy** [comment]
https://git.musl-libc.org/cgit/musl/tree/WHATSNEW#n656
https://git.musl-libc.org/cgit/musl/tree/src/linux/splice.c
Latest version appears to run fine on Alpine Linux so I'll try bumping the version OpenWrt and see what happens.
