### ISSUE TITLE
Proxy changing my user-agent build strings

### ISSUE THREAD

**Issue by momoTN** [z3APA3A/3proxy#342]
I'm making 2 connections to a web server. The first one is not using a proxy and the second one is using a proxy (based on 3proxy).
In the web server access.log I can see my user agent reported in two different ways.

Not using proxy:
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

Using Proxy (based on 3proxy configuration):
Mozilla/5.0 (Windows NT 6.1; WOW64; rv:51.0) Gecko/20100101 Firefox/5AC2 Also the 5AC2 changes every request,

The modified part is different if I use another proxy (based on 3proxy configuration).

Any idea, how to configure 3proxy to avoid that user-agent make a modification in build strings? Thank you!!!

**Comment by z3APA3A** [comment]
3proxy does not change request headers.
