### ISSUE TITLE
3Proxy 0.9b-devel Installation Help

### ISSUE THREAD

**Issue by TheScarface** [z3APA3A/3proxy#344]
Hello, I am installing 0.9b-devel Beta Version of 3Proxy.

But I am getting this question. How do I proceed forward?

It is not moving forward, maybe asking for some input?

P.S.: I am not experienced with Linux.

![screenshot_938](https://user-images.githubusercontent.com/4048189/55421918-1491cc00-5598-11e9-8606-71c4b910742f.png)

**Comment by z3APA3A** [comment]
You have instructions on screen, configure 3proxy, start and use it.

**Comment by TheScarface** [comment]
I'm not used to CLI. Could you tell me the process? :(

**Comment by z3APA3A** [comment]
3proxy is an instrument, it's just not enough to take it out of box. I can help you with instrument, I can't help you with building the house. You should either learn how to use it and you need networking and Linux basics for it, or you should hire someone (not me) who can  do the job.

**Comment by TheScarface** [comment]
> 3proxy is an instrument, it's just not enough to take it out of box. I can help you with instrument, I can't help you with building the house. You should either learn how to use it and you need networking and Linux basics for it, or you should hire someone (not me) who can do the job.

True. I just don't know where to hire one who knows 3Proxy.

**Comment by z3APA3A** [comment]
You do not need someone with 3proxy knowledge, you need someone with Linux and networking.
