### ISSUE TITLE
Slow Speed?

### ISSUE THREAD

**Issue by Saman24** [z3APA3A/3proxy#345]
Hello
I just installed 3Proxy version 8.2 on my windows 2008 r2. Server located in Netherlands with 1GB port
but there is a problem that when I use it as proxy on my pc, speed is really slow, speed is 100kb when only one connection established.
here is my config
auth strong
users xxxxxxxxxx:CL:x
proxy -p1814

**Comment by Saman24** [comment]
There seems something limited. I have looked into it for a few hours today to see what is the problem. its not from windows server, its from 3proxy.
for every established connection it gives exactly 122kb. so if i set download manager to use two established connections speed will be 244kb/s.

**Comment by z3APA3A** [comment]
3proxy doesn't limit connection speed, unless you have configured it. You may have connection speed limited by provider/hoster, windows settings or it may be due to invalid MTU/MSS/window size settings.

**Comment by Saman24** [comment]
Then why is it fast when I use CCPROXY?
