### ISSUE TITLE
[Request] Support true file inclusion

### ISSUE THREAD

**Issue by johnnybubonic** [z3APA3A/3proxy#346]
Currently, 3proxy's include directive isn't a true inclusion in that the included file uses a different syntax - namely that the linebreaks are parsed as spaces in the command. This makes managing 3proxy from templating change management (such as SaltStack, Ansible, etc.) extremely difficult when running multiple services and/or daemons on a single server.

I'd like to request supporting a more thorough file inclusion directive such that the included file can follow the same exact format as the parent/main config.

I'd recommend creating a new directive name for it to avoid breaking existing configs out there - say, **insert**, to set it apart from the existing **include** behaviour.

Alternatively/additionally, recursion (at the LEAST to a single level so that one can specify a directory of configuration files) would be extremely useful along these lines.

**Comment by z3APA3A** [comment]
3proxy supports $ inline substitution and 'include' command. 'include' command is what you need.

**Comment by johnnybubonic** [comment]
per https://3proxy.ru/doc/man3/3proxy.cfg.3.html:

> File inclusion:
> You can include file by using $FILENAME macro (replace FILENAME with a path to file, for example $/usr/local/etc/3proxy/conf.incl or
> $"c:\\Program Files\3proxy\include.cfg" Quotation is required in last example because path contains space character. **For included file <CR> (end of line characters) is treated as space character (arguments delimiter instead of end of command delimiter). Thus, include files are only useful to store long signle-line commands (like userlist, network lists, etc).** To use dollar sign somewhere in argument it must be quoted. Recursion is not allowed.

This is what I mean.

I wish to be able to include a file containing multiple commands, not one file per command.

**Comment by z3APA3A** [comment]
Just few lines below:
https://s.mail.ru/8L4A/y55nQ465X

**Comment by johnnybubonic** [comment]
OH! I am so sorry. I was entirely reading that wrong. My apologies; the way the inline inclusion documentation was written, it sounded as if the same syntax applied to both inline inclusion _and_ inclusion done via **include** directive. However, it seems what I quoted applies _only_ to inline. Sorry again, and thanks!
