### ISSUE TITLE
Domain / Website Whitelist

### ISSUE THREAD

**Issue by TheScarface** [z3APA3A/3proxy#347]
Hello, I want to restrict the 3Proxy Proxies except for the certain whitelisted website.

Like, I don't want people to access Facebook.com but I want them to access the Google.com

What to use in that case?

Thanks.

**Comment by z3APA3A** [comment]
you can list google domains or google networks like this:
```

allow * * google.com,*.google.com,*.gstatic.com
deny *
proxy
```

**Comment by clintnetwork** [comment]
Hello @z3APA3A, I've a close question, is it possible to do an IP auth with a domain instead of an IP?

I tried:
```
allow * domain.com * *
```

But it seem don't works

**Comment by z3APA3A** [comment]
It's possible to use the PTR (hostname) instead of username, see 'auth dnsname'

**Comment by fluxx03** [comment]
> you can list google domains or google networks like this:
> 
> ```
> 
> allow * * google.com,*.google.com,*.gstatic.com
> deny *
> proxy
> ```

hey how can i use file which has a list of domains to be block?

**Comment by fluxx03** [comment]
hey thanks for solution its working perfectly .

i have one more doubt 
i squid proxy i have created conf that if 
domain is in redirect.txt file the rule will redirect traffic for that domain to another proxy 
i want to implement in 3proxy

i found conf rule for redirecting traffic here
`parent 1000 http xx.host.com 9989 user:password`
above rule is redirecting all trafic to different proxy 
but how can i redirect only redirect.txt  to other proxy 

thank you in advance

**Comment by j4uonline** [comment]
auth strong
allow * * facebook.com,*.facebook.com
allow user1
deny *
proxy
flush

# hey, this comand is not working, "user1" connect all website
# i fix it
auth strong
allow * * facebook.com,*.facebook.com
deny *
allow user1
proxy
flush

# and "user1" cannot conect any website.
# how to set "user1" connect only to facebook.com?

**Comment by Theodikes** [comment]
> # how to set "user1" connect only to facebook.com?

auth strong
allow user1 * facebook.com,*.facebook.com
proxy
