### ISSUE TITLE
_beginthreadex(): Not enough space

### ISSUE THREAD

**Issue by CrazyASCode** [z3APA3A/3proxy#348]
Здравствуйте.
Стала возникать такая ошибка
![image](https://user-images.githubusercontent.com/27917113/56860456-6400c780-699f-11e9-82a1-6b778d7a8aed.png)

Вот конфиг:

stacksize 8192000
nscache 65536
auth iponly

auth iponly
maxconn 100
allow * СПИСОК_IP
parent 10 socks5 IP0 PORT0
...
parent 10 socks5 IP99 PORT99
socks -p1080
flush

Система:
2x Xeon L5630
12 GB ОЗУ

**Comment by CrazyASCode** [comment]
Скачал 3proxy-0.9-devel-x64, пока что нормально работает

**Comment by z3APA3A** [comment]
Диагностика вполне достаточная - кончилось место в системе. А зачем выделать 8 мегабайт на каждый поток?
