### ISSUE TITLE
Помогите разобраться с цепочками прокси!

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#349]
Настраиваю 3proxy впервые (Windows). Никак не могу разобраться с цепочками.
Есть первый прокси, к которому подключается браузер. Если я правильно разобрался в терминологии - родительский прокси. Его локальный адрес 172.16.0.4
Вот его конфиг:
------------------------------------------------------------------------
monitor "C:\3proxy\bin64\3proxy.cfg"
nserver 172.16.0.1
auth none
log
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -n -a
------------------------------------------------------------------------
Я хочу, чтобы соединения с него перенаправлялись на следующий за ним прокси.
Он слушает несколько своих адресов.
Вот его конфиг:
------------------------------------------------------------------------
monitor "C:\3proxy\bin64\3proxy.cfg"
nserver 172.16.0.1
auth none
log
allow *
parent 1000 http 172.16.0.4 3128
proxy -n -a -i172.16.101.101 -e172.16.101.101 -p3128
proxy -n -a -i172.16.102.101 -e172.16.102.101 -p3128
proxy -n -a -i172.16.103.101 -e172.16.103.101 -p3128
------------------------------------------------------------------------

Документацию по 3proxy исчитался уже, понимания нет к сожалению.
Что делаю не так?
Помогите!

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#LIMITS

> Q: Почему не работают ограничения доступа (перенаправления, ограничения по скорости, трафику и т.д.)?
> 
> A: Обычные ошибки - использование auth none ....

**Comment by spiller1975** [comment]
Добавил авторизацию.
Все равно не работает.
Еще в конфиге что-то не так.(((

**Comment by z3APA3A** [comment]
Ну так покажите что в конфиге и что в логах.

**Comment by spiller1975** [comment]
Это родительский конфиг:

monitor "C:\3proxy\bin64\3proxy.cfg"
nserver 172.16.0.1
auth strong
users test:CL:test
log
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
allow test
parent 1000 http 172.16.101.101 3128 test test
proxy -n -a

адрес, на котором он работает - 172.16.0.4

А это конфиг прокси, на который пытаюсь перенаправить:

monitor "C:\3proxy\bin64\3proxy.cfg"
nserver 172.16.0.1
auth strong
users test:CL:test
log
allow test
parent 1000 http 172.16.0.4 3128 test test

proxy -n -a -i172.16.101.101 -e172.16.101.101 -p3128
proxy -n -a -i172.16.102.101 -e172.16.102.101 -p3128
proxy -n -a -i172.16.103.101 -e172.16.103.101 -p3128

он запущен на нескольких адресах.

При такой конфигурации на родительском прокси такое появляется:

190520111936.283 3128 00522 test 172.16.101.101:57679 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.392 3128 00522 test 172.16.101.101:57680 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.501 3128 00522 test 172.16.101.101:57681 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.611 3128 00522 test 172.16.101.101:57682 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.720 3128 00522 test 172.16.101.101:57683 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.829 3128 00522 test 172.16.101.101:57684 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111936.939 3128 00522 test 172.16.101.101:57685 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.048 3128 00522 test 172.16.101.101:57686 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.158 3128 00522 test 172.16.101.101:57687 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.267 3128 00522 test 172.16.101.101:57688 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.376 3128 00522 test 172.16.101.101:57689 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.486 3128 00522 test 172.16.101.101:57690 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.595 3128 00522 test 172.16.101.101:57691 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.704 3128 00522 test 172.16.101.101:57692 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.814 3128 00522 test 172.16.101.101:57693 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111937.923 3128 00522 test 172.16.101.101:57694 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520111938.033 3128 00522 test 172.16.101.101:57695 172.16.101.101:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1


И в дочернем логе тоже аналогично:

190520140414.544 3128 00522 test 172.16.0.4:57591 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140414.638 3128 00522 test 172.16.0.4:57592 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140414.747 3128 00522 test 172.16.0.4:57593 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140414.857 3128 00522 test 172.16.0.4:57594 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140414.966 3128 00522 test 172.16.0.4:57595 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.060 3128 00522 test 172.16.0.4:57596 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.185 3128 00522 test 172.16.0.4:57597 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.278 3128 00522 test 172.16.0.4:57598 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.403 3128 00522 test 172.16.0.4:57599 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.497 3128 00522 test 172.16.0.4:57600 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.622 3128 00522 test 172.16.0.4:57601 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.716 3128 00522 test 172.16.0.4:57602 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.825 3128 00522 test 172.16.0.4:57603 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1
190520140415.950 3128 00522 test 172.16.0.4:57604 172.16.0.4:3128 142 0 1 CONNECT mtalk.google.com:5228 HTTP/1.1

**Comment by z3APA3A** [comment]
А что должен делать
parent 1000 http 172.16.101.101 3128 test test
в конфиге родительского прокси?

**Comment by spiller1975** [comment]
Да это я уже методом научного тыка пробую.
Убрал, в логах родительского прокси судя по всему напрямую идет:


190520114839.766 3128 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Accepting connections [3504/372]
190520114851.188 3128 00000 test 172.16.103.99:61605 173.194.222.156:443 645 0 0 CONNECT pagead2.googlesyndication.com:443 HTTP/1.1
190520114851.268 3128 00100 - 172.16.103.99:61606 0.0.0.0:0 0 0 0 CONNECT www.ipv6.browserleaks.com:443 HTTP/1.1
190520114851.620 3128 00100 - 172.16.103.99:61623 0.0.0.0:0 0 0 0 CONNECT 325b3u0iy66xk4jr.dig.browserleaks.com:443 HTTP/1.1
190520114851.674 3128 00000 test 172.16.103.99:61632 151.101.244.134:443 1056 22723 0 CONNECT browserleaks.disqus.com:443 HTTP/1.1
190520114852.522 3128 00000 test 172.16.103.99:61635 151.101.128.134:443 1412 600 0 CONNECT disqus.com:443 HTTP/1.1
190520114852.934 3128 00000 test 172.16.103.99:61636 151.101.64.134:443 1238 2950 0 CONNECT disqus.com:443 HTTP/1.1
190520114853.742 3128 00000 test 172.16.103.99:61637 151.101.244.134:443 1613 469 0 CONNECT referrer.disqus.com:443 HTTP/1.1
190520114906.771 3128 00000 test 172.16.103.99:61633 193.0.6.142:443 1089 6867 0 CONNECT rdap.db.ripe.net:443 HTTP/1.1
190520114906.813 3128 00000 test 172.16.103.99:61594 138.201.8.17:443 2952 17933 0 CONNECT creative.rutarget.ru:443 HTTP/1.1
190520114908.561 3128 00000 test 172.16.103.99:61603 138.201.8.61:443 5388 99790 0 CONNECT cdn.rutarget.ru:443 HTTP/1.1
190520114912.405 3128 00013 test 172.16.103.99:61611 212.109.215.202:443 0 0 0 CONNECT kotmc0hiaoc0yomp.dig.browserleaks.com:443 HTTP/1.1
190520114912.406 3128 00013 test 172.16.103.99:61608 212.109.215.202:443 0 0 0 CONNECT 8mpt3j2ge5sl8xc0.dig.browserleaks.com:443 HTTP/1.1
190520114912.406 3128 00013 test 172.16.103.99:61612 212.109.215.201:443 0 0 0 CONNECT 6etvlq17o00fxe4t.dig.browserleaks.com:443 HTTP/1.1
190520114912.406 3128 00013 test 172.16.103.99:61609 212.109.215.202:443 0 0 0 CONNECT abv527x142u877ql.dig.browserleaks.com:443 HTTP/1.1
190520114912.436 3128 00013 test 172.16.103.99:61614 212.109.215.202:443 0 0 0 CONNECT 9nqrgobeggeqr8qz.dig.browserleaks.com:443 HTTP/1.1
190520114912.437 3128 00013 test 172.16.103.99:61615 212.109.215.201:443 0 0 0 CONNECT rsyd7nz0dpqc6n7x.dig.browserleaks.com:443 HTTP/1.1
190520114912.437 3128 00013 test 172.16.103.99:61616 212.109.215.202:443 0 0 0 CONNECT wemkraw8f6lvustf.dig.browserleaks.com:443 HTTP/1.1
190520114912.437 3128 00013 test 172.16.103.99:61619 212.109.215.202:443 0 0 0 CONNECT 1z5syvq6os1mu27w.dig.browserleaks.com:443 HTTP/1.1
190520114912.437 3128 00013 test 172.16.103.99:61610 212.109.215.202:443 0 0 0 CONNECT xml7y02gbvvjjq4j.dig.browserleaks.com:443 HTTP/1.1

В логах дочернего прокси ничего.

**Comment by spiller1975** [comment]
То есть теперь родительский конфиг такой:

monitor "C:\3proxy\bin64\3proxy.cfg"
nserver 172.16.0.1
auth strong
users test:CL:test
log
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -n -a

**Comment by spiller1975** [comment]
Кстати, может это важно.
Адреса, на которых запущен дочерний прокси - это алиасы, дополнительные адреса на физической сетевой карте:
proxy -n -a -i172.16.101.101 -e172.16.101.101 -p3128
proxy -n -a -i172.16.102.101 -e172.16.102.101 -p3128
proxy -n -a -i172.16.103.101 -e172.16.103.101 -p3128

разумеется все пингуется, файерволлы везде отключены

**Comment by z3APA3A** [comment]
так и что _теперь_ в конфигах и логах?

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS

попробуй сделать 
nc -s 172.16.101.101 212.109.215.202 443
где 172.16.101.101 это тот адрес, который ты используешь в -e. Если коннект не пройдет - значит что-то ты недонастроил.

**Comment by spiller1975** [comment]
Буду пробовать, разбираться.

Будьте добры, подскажите какой прокси сервер можно использовать в качестве родительского?
То есть этот прокси будет стоять первым и слать коннекты на несколько адресов, на которых слушает 3proxy. С каким прокси будет корректно работать цепочка?

Просто такой вариант я предполагал как альтернативный...

**Comment by z3APA3A** [comment]
Можно использовать любой прокси, но адрес, который ты прописал в -e должен быть рабочим, а сейчас у тебя с этого адреса исходящие соединения не проходят.

**Comment by spiller1975** [comment]
Вообще проходят.
Я не указывал, но я напрямую к этому адресу из браузера цепляюсь, все работает.
И к любому из адресов, на которых запущен прокси.

Нашел команду nc под винду, запустил, ничего не выдает.
Ни ошибки ни какого-то результата.
После ввода команды заметная пауза (5-10 сек) и происходит перевод строки, а вывода никакого.

Буду искать.

**Comment by z3APA3A** [comment]
У вас проходят соединения по локальной сети к этому адресу, этого достаточно чтобы использовать этот адрес в -i. Но не проходят соединения с этого адреса во внешнюю сеть, а это необходимо чтобы использовать этот адрес в -e.  Скорей всего, сеть, которой он принадлежит не настроена на маршрутизаторе и для нее не выполняется NAT. Поставьте этот адрес на интерфейсе как единственный и проверьте есть ли при этом доступ в интернет.

**Comment by OmetovVlad** [comment]
Добрый день.
У меня вопрос касаемо цепочек прокси - у нас есть список прокси, нам нужно чтобы из под наших прокси работали прокси из списка. 

Делаем следующим образом:

allow *
parent 1000 http proxy port login pass
proxy -n -p10000

flush
allow *
parent 1000 http proxy2 port login pass
proxy -n -p10001

Но при подключении к нашей прокси мы видим наш ip, а должны видеть ip прокси которую указали в parent
