### ISSUE TITLE
MS Win 2003. 3proxy-0.8.3-lite вылетает, при попытке открыть из админки "Счетчики"

### ISSUE THREAD

**Issue by Vzhik9** [z3APA3A/3proxy#35]
3proxy-0.8.3-lite вылетает, при попытке открыть из админки "Счетчики"
В логах "Faulting application 3proxy.exe, version 0.0.0.0, faulting module msvcrt.dll, version 7.0.3790.3959, fault address 0x0003399b."

Тот же конфиг в 3proxy-0.7.1.4-lite работает

**Comment by z3APA3A** [comment]
пришли конфиг (то, что касается счетчиков) и файл счетчиков на 3proxy@3proxy.ru

**Comment by z3APA3A** [comment]
Попробуй http://3proxy.ru/current/3proxy-0.9-lite-devel.zip, в ней дать команду в начале файла конфигурации
stacksize 8192
поможет?

**Comment by Vzhik9** [comment]
Проверить не удалось, т.к. 3proxy-0.9-lite-devel-160217182519.zip
через 2 секунды просто самопроизвольно крешится.

**Comment by z3APA3A** [comment]
А какая информация в креше? Можешь прислать крэшдамп?

**Comment by Vzhik9** [comment]
> Можешь прислать крэшдамп?
Как его сохранить? В консольке 3proxy ничего не пишет при падении, в логах тоже ничего нет.

**Comment by z3APA3A** [comment]
https://blogs.technet.microsoft.com/askperf/2007/06/15/capturing-application-crash-dumps/

**Comment by z3APA3A** [comment]
Попробуй текущий http://3proxy.ru/current/3proxy-0.9-lite-devel.zip - перешел на OpenWatcom для lite-версии, должен быть лучше совместим со старыми версиями Windows.
