### ISSUE TITLE
Error compiling 3proxy with SSLPlugin on entware

### ISSUE THREAD

**Issue by mirecg** [z3APA3A/3proxy#350]
Hello, I wanted to compile 3proxy on tomato-by-shibby firmware on top of entware tooling.

I've got this error:
errno@@GLIBC_PRIVATE: TLS definition in /opt/lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/libc.so.6 section .tbss mismatches non-TLS definition in /lib/libc.so.0 section .bss

Details:
gcc -o ../bin/3proxy -O2 -fno-strict-aliasing -pthread   3proxy.o mainfunc.o auth.o authradius.o conf.o datatypes.o srvproxy.o srvpop3p.o srvsmtpp.o srvftppr.o srvsocks.o srvtcppm.o srvudppm.o sockmap.o sockgetchar.o myalloc.o common.o mycrypt.o md5.o md4.o base64.o ftp.o smbdes.o ntlm.o stringtable.o srvwebadmin.o srvdnspr.o plugins.o  -lcrypto -lssl -ldl 
/opt/bin/ld: warning: libdl.so.0, needed by /usr/lib/libcrypto.so, may conflict with libdl.so.2
/opt/bin/ld: warning: libc.so.0, needed by /usr/lib/libcrypto.so, may conflict with libc.so.6
/opt/bin/ld: errno@@GLIBC_PRIVATE: TLS definition in /opt/lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/libc.so.6 section .tbss mismatches non-TLS definition in /lib/libc.so.0 section .bss
/lib/libc.so.0: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.inc:147: ../bin/3proxy] Error 1
make[1]: Leaving directory '/tmp/home/root/3proxy/src'
make: *** [Makefile.inc:7: all] Error 2

**Comment by z3APA3A** [comment]
It should mean errno is defined in a different way in 2 different libraries (/opt/lib/gcc/arm-openwrt-linux-gnueabi/6.3.0/libc.so.6 and /lib/libc.so.0) so you have conflict in your linking environment and it's probably not 3proxy specific.

**Comment by z3APA3A** [comment]
It looks like you are building 3proxy with different libc from one used to build libcrypto.

**Comment by mirecg** [comment]
Yes you are right. 
I was hoping that some had the simmilar problem. 
I don't know how to bypass linking to /lib/libc.so.

**Comment by z3APA3A** [comment]
Actually, you can remove  -lcrypto -lssl for building 3proxy itself, these libraries are only required to build SSLPlugin. It doesn't resolve the issue itself and I can't guarantee this will build something working, but there is a chance.

**Comment by z3APA3A** [comment]
The correct solution should be to rebuild crypto libraries to match the libc

**Comment by mirecg** [comment]
Thank you for advice. I will try to build crypto libs later today. 
FYI, I can succesfully build 3proxy without SSLPlugin, which is commented by default in Makefile.

**Comment by mirecg** [comment]
Hello, I've compiled the SSLPlugin finally, but I'm getting runtime error `SSLPlugin.ld.so: undefined symbol: CRYPTO_num_locks`.
It's the same error like in #227. 
In https://github.com/openssl/openssl/issues/8573, i found that the CRYPTO_num_locks is not used anymore in later version then 1.0.2.

**Comment by z3APA3A** [comment]
duplicates https://github.com/z3APA3A/3proxy/issues/298
