### ISSUE TITLE
Using 3proxy as socks5 with UDP gives 421 errors

### ISSUE THREAD

**Issue by pb18rlvx** [z3APA3A/3proxy#351]
I'm using 3proxy 0.8.12 on raspbian.

I simplified the configuration so I set auth to none, external and internal ip to the same address on my LAN and start 2 services:

>     proxy at 3128
>     socks on 1080.

The (HTTP/HTTPS) proxy works just fine.

What I wanna do is to let an application use the socks5 with UDP packets. This works in most cases from my desktop PC. Just every now and then the application tells me it cannot connect to my socks server. I retry like 5 times then it works like a charm.

When the connection fails, I get these errors logged in the logfile:

`1556993690.682 SOCK5.1080 00421 - 192.168.211.2:55084 192.168.211.7:0 0 0 0 UNKNOWN_0.0.0.0:0`

So I looked what the error code 00421 means, but 3proxy manual just says

> 400-499 - SOCKS proxy specific bugs

After looking into the sourcecode, I found the line that produced the output, but i cant make anything out of it
```
	 if ((c = sockgetcharcli(param, conf.timeouts[SINGLEBYTE_L], 0)) != 5) {
		RETURN(421);
     } /* version */
```
I also checked the network packets with wireshark
```wireshark
00000000  05 01 00                                           ...
    00000000  05 00                                              ..
00000003  05 03 00 01 00 00 00 00  00 00                     ........ ..
    00000002  05 00 00 01 c0 a8 d3 07  99 79                     ........ .y

```
After checking RFC 1928 for it I still can't find anything wrong.

1. Client sends version 05, 1 method: no authentification
2. Server accepts
3. Client issues command 03 (UDP associate) by type 1 (IP v4)
4. Server accepts and send IP (0xC0A8D307 = 192.168.211.7) 
And then the connection drops and log tells me  error 421.

Can I offer any details to help me further?
Thanks in advance

**Comment by z3APA3A** [comment]
Error 421 means packet from the step 3 was either not received during timeout or it had no 0x05 in the beginning. In this case, server reply should have 0x01 as a response code (repcode = param->res%10 where param->res is 421). 
Your traffic sniff contains 0x00 (success) as a response code (second octet in the code), it can not happen in the case of 421 error generated by proxy, so, most probably traffic sniffed does not correspond to log entry. Either you sniffed a different request and it does not not correspond to log entry or SOCKS response was generated by something else, e.g. by some DLP/IPS software between client and proxy or it was spoofed/modified in some other way.

**Comment by z3APA3A** [comment]
Also, this response contains valid port allocation. It means request from the client was successfully parsed by proxy, it can not happen in the case of error 421, because error 421 indicates request was not received. In this traffic you should see UDP traffic between client and proxy, if you do not see this traffic, you have some issue with client.

**Comment by pb18rlvx** [comment]
Well thats the weired thing sometimes it works sometimes not.
I found three different sort of stream:
```
00000000  05 01 00
    00000000  05 00
```
```
00000000  05 01 00
    00000000  05 00
    00000002  05 01 00 04 00 00 00 00  00 00 00 00 00 00 00 00
    00000012  00 00 00 00 00 00
```
```
00000000  05 01 00
    00000000  05 00
00000003  05 03 00 01 00 00 00 00  00 00
    00000002  05 00 00 01 c0 a8 d3 07  8e d2
```
Each of them ends may end in resetting the tcp stream or in a success.
If its success, there's more UDP traffic of course.

I start to think it may be my Antivirus software that cuts the stream off (Kaspersky).

**Comment by pb18rlvx** [comment]
I completely deactived Kaspersky (stopped & exited) and also deactivated windows firewall and it still happens. Must be something different

**Comment by z3APA3A** [comment]
You can try to increase "timeouts" (BYTE_LONG) default is 5 seconds, see
https://3proxy.ru/doc/man3/3proxy.cfg.3.html
If you see delay of 5 seconds in the second example, you probably see the timeout in action.

**Comment by pb18rlvx** [comment]
Thanks for the hint. Sadly that didn't helped (set it to 30 seconds). 
Also the error comes to quick for even a 5 sec timeout.

Here's the result of `cat /var/log/3proxy.log.2019.05.27 | grep 1080` (last 3 errors before it worked)
`
1558982072.938 SOCKS.1080 00000 - 192.168.211.7:1080 192.168.211.7:0 0 0 0 Accepting_connections_[384/3066221680]

1558982165.883 SOCK5.1080 00421 - 192.168.211.2:52529 192.168.211.7:0 0 0 0 UNKNOWN_0.0.0.0:0

1558982172.535 SOCK5.1080 00421 - 192.168.211.2:52538 192.168.211.7:0 0 0 0 UNKNOWN_0.0.0.0:0

1558982174.251 SOCK5.1080 00421 - 192.168.211.2:52539 192.168.211.7:0 0 0 0 UNKNOWN_0.0.0.0:0
`

**Comment by z3APA3A** [comment]
You can add %D to default logformat (default is "G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T") - it will show you request duration. If duration is above timeout or you see FIN packet coming from client there is nothing to do on the proxy side - you should check for the problem on the client side.
