### ISSUE TITLE
nsrecord не работает + баг с gethostbyname()

### ISSUE THREAD

**Issue by PapaV** [z3APA3A/3proxy#352]
Та же проблема, что и здесь: [(https://github.com/z3APA3A/3proxy/issues/77)]
3proxy 0.8.12, FreeBSD 11.2.
Конфиг (не весь):

```
nserver 1.1.1.1
nserver 8.8.8.8
nscache 65535

# Don't work - BUG
nsrecord ya.ru 0.0.0.0
nsrecord google.com 127.0.0.1

timeouts 1 5 30 60 180 1800 15 60
```

P.S: Если убрать все nserver - dns перестает работать вообще, как будто gethostbyname() сломана

**Comment by z3APA3A** [comment]
0.0.0.0 не является корректным IP для NS record

**Comment by PapaV** [comment]
заменил на 127.0.0.1 - без изменений.

**Comment by z3APA3A** [comment]
А без каких изменений? Что в логе?

**Comment by PapaV** [comment]
В логах есть все что угодно, кроме домена из nsrecord. Вот кусок лога для ya.ru (сайт открывается):

```
1558963846.242  SOCK5.4 00000 - 178.154.131.217:443 946 1629 0 CONNECT_yastatic.net:443
1558963846.243  SOCK5.4 00000 - 178.154.131.216:443 948 967 0 CONNECT_yastatic.net:443
1558963846.250  SOCK5.4 00000 - 178.154.131.217:443 946 1176 0 CONNECT_yastatic.net:443
1558963846.470  SOCK5.4 00000 - 178.154.131.216:443 998 35491 0 CONNECT_yastatic.net:443
1558963846.527  SOCK5.4 00000 - 178.154.131.217:443 1010 64225 0 CONNECT_yastatic.net:443
1558963847.321  SOCK5.4 00000 - 178.154.131.217:443 599 156 0 CONNECT_yastatic.net:443
```

**Comment by z3APA3A** [comment]
Ну значит у тебя нет запросов на ya.ru через прокси

**Comment by PapaV** [comment]
Я сначала тоже так подумал, но, сменив socks на http proxy, в логах вижу это:
`1558969142.851  PROXY.5 00000 87.250.250.242:80 479 373 0 GET_http://ya.ru/_HTTP/1.1`
