### ISSUE TITLE
A remote address overwrite feature request 

### ISSUE THREAD

**Issue by VasiliPupkin256** [z3APA3A/3proxy#353]
Please implement an option to overwrite remote address field (BND.ADDR according to rfc1928) returned to client in SOCKS proxy mode. When a proxy is behind VPN and its external address is local to VPN tun/tap adapter, it is reporting fake local address to clients. This confuses clients who use this remote address to establish incoming connections with BIND and UDP ASSOCIATE. Actually the lack of this feature makes BIND and UDP ASSOCIATE impractical.

This is what 3proxy returns to client now:

Socks Protocol
Version: 5
Results(V5): Succeeded (0)
Address Type: 1 (IPv4)
Remote Address: 10.34.132.100 (10.34.132.100)

what I want to see:

Socks Protocol
Version: 5
Results(V5): Succeeded (0)
Address Type: 1 (IPv4)
Remote Address: 194.59.251.162 (us-east.privateinternetaccess.com)

**Comment by z3APA3A** [comment]
-N option added to socks with ebd7b34159e99424ac3acc33f323072538155b09 (not tested yet)
