### ISSUE TITLE
How to assign port to diffrent user

### ISSUE THREAD

**Issue by raboot** [z3APA3A/3proxy#354]
hello, i have a problem

i use 3proxy on ipv6 proxy server. create 1000 ipv6 proxy and 2 user. testuser1 and testuser2.
x.x.x.x:30000 -> ipv6 proxy 1
x.x.x.x:30001 -> ipv6 proxy 2
.
.
.
x.x.x.x:30999 -> ipv6 proxy 999

i need diffrent user diffrent port as:

allow testuser1 port 30000 to 30500
allow testuser2 port 30501 to 30999.

how that possible? some one tell me please.

**Comment by z3APA3A** [comment]
allow user 1
proxy -p30000
proxy -p30001
...
proxy -p30500
flush
allow user2
proxy -p30501
...
proxy -p30999

**Comment by raboot** [comment]
i did this solution but didn't work. open 

in this case, both user1 and user2 can access all ports seamlessly. Ports not included here are also included.  as an example user1 and user2 port 30250 can access

`setgid 65535
setuid 65535
flush
auth strong
users user1:CL:password user2:CL:password
allow user1
proxy -p30000
proxy -p30001
proxy -p30002
proxy -p30003
flush
allow user2
proxy -p30004
proxy -p30005
proxy -p30006
flush`

If I remove "flush" at the end of the code, only user1 can access all open ports. user2 comes out of the system completely
