### ISSUE TITLE
Multiple auth methods

### ISSUE THREAD

**Issue by Daniilisi** [z3APA3A/3proxy#355]
Здравствуйте, спасибо за 3proxy.
Возможно ли настроить связку где родительский 3proxy имеет 2 вида авторизации по IP и по паролю (нашел в документации строки:

> Disables both authentication and authorization. You can not use ACLs.
> auth iponly

правильно ли я понимаю, что нельзя использовать авторизацию по паролю если используется auth iponly?

**Comment by z3APA3A** [comment]
по вопросу не понятно, идет ли речь о настройке 3proxy как сервера или как клиента, а цитата вообще про auth none, но в любом случае можно.

**Comment by z3APA3A** [comment]
Сформулируй вопрос исходя из задачи, а не из предполагаемой функциональности

**Comment by Daniilisi** [comment]
Могу ли я использовать несколько методов доступа к серверу (авторизация по паролю и акцесс лист по ip).

**Comment by z3APA3A** [comment]
3proxy поддерживает например
auth iponly strong
но из твоего вопроса не понятно, то ли это, что тебе надо, потому что вместо описания задачи, которую надо решить ты спрашиваешь про то, какая функциональность есть.

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#AUTH тут есть подробно с примерами
