### ISSUE TITLE
3Proxy with LTE dongle

### ISSUE THREAD

**Issue by Emmesport** [z3APA3A/3proxy#356]
Hello! I am trying to use 3Proxy (version 0.9) with LTE dongles.
I use raspberry + wvdial.

**the wvdial.conf is:**
[Dialer P0]
Modem=/dev/ttyUSB1
Phone = *99***1#
Username = "blank"
Password = "blank"
New PPPD = yes
Stupid Mode = 1
Dial Command = ATDT

[Dialer P1]
Modem=/dev/ttyUSB3
Phone = *99***1#
Username = "blank"
Password = "blank"
New PPPD = yes
Stupid Mode = 1
Dial Command = ATDT

**the ppp0 configuration in interfaces.d/ppp0 is:**
auto ppp0
iface ppp0 inet wvdial
provider P0

**the ppp1 configuration in interfaces.d/ppp1 is:**
auto ppp1
iface ppp1 inet wvdial
provider P1

**and the 3proxy.cfg is:**
nscache 65536
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
logformat "L%y%o%d %H%M%S %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 60
counter /count/3proxy.3cf

users $/conf/passwd 

include /conf/counters
include /conf/bandlimiters

auth strong
allow admin
proxy -a -i192.168.1.100 -p3128 -Deppp0
proxy -a -i192.168.1.100 -p3129 -Deppp1

The proxy is ok... in the browser I have to enter username and password, but it come out with the public ip address of my wifi connection and not with dongle ip address.
It is the same with IP in -e.

**What’s wrong in my configuration?**

**Comment by nthoait** [comment]
I same your problem, can u help me how to fix it ?
Thanks!

**Comment by z3APA3A** [comment]
-De requires 3proxy to be executed with root privileges. Standard config which is created if you run "make install" is not suitable for this configuration, because it's developed for jailed non-privileged environment. Run 3proxy with root privileges with your own config file.

**Comment by z3APA3A** [comment]
Or, alternativery, use binding to IP address rather than interface name and use source routing to route traffic through specific interface.

**Comment by nthoait** [comment]
> Run 3proxy with root privileges with your own config file.
I run this command for start 3proxy
`sudo service 3proxy start`

> Or, alternativery, use binding to IP address rather than interface name and use source routing to route traffic through specific interface.

Cause IP from 3g dongle is dynamic, so i cannot fixed value for config

**Comment by nthoait** [comment]
Now if i run 
`route add default dev ppp0`

and my proxy will show IP of 3g dongle,  is ok. but i have 2 more issues

**1st issues:** 
I have 2 3g dongles, and I config for 2 proxies port 3128 - ppp0, and 3129 - ppp1 , but i use 2 proxies only show only 1 external IP

**2nd issues:**
If I use external IP is my Internet (Wifi Internet), Nat port is ok, can connect from Internet (Wifi IP WAN)
If I used external IP is my 3g dongle, NAT PORT has a problem, cannot connect from the Internet (Wifi IP WAN). Only can use LAN IP of Proxy Server

**Comment by z3APA3A** [comment]
I can add little to reply previously given.
1. You must add routes through both interfaces in either case. proxy acts on application level and can no manage the routes.
2. Route can either be added as a source route (you can e.g. place IP address of the interface in file, use -e$filename in the proxy and rewrire file / send USR1 signal to 3proxy with if-up script to reload config on address change) or static with interface selection via -De. In last case, you should run 3proxy as root with your own config (because default config drops root privileges)

**Comment by nthoait** [comment]
Im noob in linux, can u tell me how to "add routes through both interfaces"

**Comment by nthoait** [comment]
i can do it.
Change start command by this command
`sudo 3proxy /etc/3proxy/conf/3proxy.cfg &`

Thanks for your help!

**Comment by jack1993** [comment]
> i can do it.
> Change start command by this command
> `sudo 3proxy /etc/3proxy/conf/3proxy.cfg &`
> 
> Thanks for your help!

Do you have a solution to the above problem? Please give me some info tks
