### ISSUE TITLE
Two auth to parent proxy 

### ISSUE THREAD

**Issue by Thomanphan** [z3APA3A/3proxy#357]
Hello
I have a question can you help me
This is my proxy : 111.177.86.75:9596
I want connect this proxy used 3proxy I tried so many time but still issue
this is my code , my code working with IP auth only , can't set username: user1 to my proxy port 704, can you check help me

I want set two auth to my proxy username and ip but not working

```
users user1: CL: user1
auth iponly strong
allow user1
allow * 11.236.66.15
parent 1000 connect 111.177.86.75 9596
proxy -n -p704 -a
flush
```

one more thing if my proxy 111.177.86.75 need username and password to connect How I can add username and pass to this proxy connect
Thank

**Comment by z3APA3A** [comment]
This string:
> users user1: CL: user1
has spaces after  semicolon sign, no spaces should be where.

**Comment by Thomanphan** [comment]
I edited but can't connect to proxy 111.177.86.75:9596

**Comment by z3APA3A** [comment]
If you need username and password add it to 'parent' command.

**Comment by Thomanphan** [comment]
Can you give me an example?

**Comment by z3APA3A** [comment]
See parent command description:
https://3proxy.ru/doc/man3/3proxy.cfg.3.html

**Comment by Thomanphan** [comment]
I try all config but can't connect  can you check my config @z3APA3A 
I try allow my ip 123.2.3.4 and username test to connect to proxy

```
auth iponly strong 
users test:CL:test
allow test
parent 1000 http 145.130.255.147 80 username pass
allow * 123.2.3.4
proxy -n -u -p123 -a
flush
```
Thank

**Comment by z3APA3A** [comment]
put `allow * 123.2.3.4` prior to `allow test`, because `allow test` requires username authentication.

**Comment by Thomanphan** [comment]
But I need two auth ip and username in same port

```
auth iponly strong 
users test:CL:test
allow * 123.2.3.4
allow test
parent 1000 http 145.130.255.147 80 username pass
proxy -n -p123 -a
flush
```
This config not working

**Comment by z3APA3A** [comment]
Explain results you are expecting and results you actually get (with logs, preferably).
