### ISSUE TITLE
The problem with time  of Log refresh 

### ISSUE THREAD

**Issue by CYhyq** [z3APA3A/3proxy#359]
The current refresh time is based on each action refresh, can we limit the refresh amount per unit time?

**Comment by z3APA3A** [comment]
I'm not sure what do you mean by 'refresh', probably you misuse the word, but you may be interested in `logformat` and `logdump` commands, see https://3proxy.ru/doc/man3/3proxy.cfg.3.html

**Comment by CYhyq** [comment]
Now,3proxy refreshes its logs every time when it has a connection. For me, the rating is too high. It causes CPU Occupied 80%. Sometimes it stores 6 G log files a day. The effect I want is to reduce the refresh frequency of 3proxy. I don't know if there is any way to achieve it. I have seen the configuration of your official network, but I haven't found the desired result.




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月24日(星期一) 晚上6:49
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




I'm not sure what do you mean by 'refresh', probably you misuse the word, but you may be interested in logformat and logdump commands, see https://3proxy.ru/doc/man3/3proxy.cfg.3.html

**Comment by z3APA3A** [comment]
> Now,3proxy refreshes its logs every time when it has a connection

Nope, if logging is configured with "log" command with filename, 3proxy uses standard buffered I/O for logging and flushes the buffer only once in a second (or if the buffer is filled). 6GB of logs/day is not an amount which and can cause 80% CPU usage, probably your problem is unrelated to logging or you use VPS hosting with overloaded disk.

**Comment by z3APA3A** [comment]
Also, check "Virtual hosting" section in https://3proxy.ru/highload.asp

**Comment by CYhyq** [comment]
First of all, thank you for your reply.The main problem we care about is that the logs are too big.You said refresh every second, can we let the log refresh every minute?




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:28
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




Also, check "Virtual hosting" section in https://3proxy.ru/highload.asp

**Comment by z3APA3A** [comment]
It's useless, if you understand how memory paging and disk I/O works. You are looking for a problem in a wrong place.

**Comment by CYhyq** [comment]
Okay, thank you.I'll try to solve it in other ways.




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:39
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




It's useless, if you understand how memory paging and disk I/O works. You are looking for a problem in a wrong place.

**Comment by z3APA3A** [comment]
If the logs are too big, you can either change the logformat to have a smaller amount of data logged or use "nolog" option in ACL to prevent some activity from being logged. But it will not help you with CPU usage.

**Comment by CYhyq** [comment]
In fact, this is also on the one hand, on the other hand, our server's 3P In China often has malicious access from Russia.This has resulted in a waste of many of our resources.At present, no solution has been found.Do you have WeChat?This kind of communication seems inconvenient.I sent you a picture, which is one of the log records.






------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>;
发送时间: 2019年6月25日(星期二) 下午4:44
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>;
抄送: "飄零↘評荇綫"<421160052@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




If the logs are too big, you can either change the logformat to have a smaller amount of data logged or use "nolog" option in ACL to prevent some activity from being logged. But it will not help you with CPU usage.

**Comment by z3APA3A** [comment]
Use authentication to prevent malicious access and connlim to limit connections / request ratelimits per user.

**Comment by CYhyq** [comment]
.We set a limit on the number of connections.We also set up authentication,like this.




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:58
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




Use authentication to prevent malicious access and connlim to limit connections / request ratelimits per user.

**Comment by CYhyq** [comment]
,username/password authentication required, we also set up.




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:58
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




Use authentication to prevent malicious access and connlim to limit connections / request ratelimits per user.

**Comment by CYhyq** [comment]
你好，今天突然想到这个问题，冒昧问一下，为什么3p每次新配置的时候如果日志路径没有配置相符的文件夹就会出现3p闪退的现象呢，为什么不可以加一个自动创建日志文件夹的功能呢？




------------------ 原始邮件 ------------------
发件人: "Vladimir Dubrovin"<notifications@github.com>; 
发送时间: 2019年6月25日(星期二) 下午4:58
收件人: "z3APA3A/3proxy"<3proxy@noreply.github.com>; 
抄送: "飄零↘評荇綫"<421160052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [z3APA3A/3proxy] The problem with time  of Log refresh  (#359)




Use authentication to prevent malicious access and connlim to limit connections / request ratelimits per user.
