### ISSUE TITLE
Radius Accounting

### ISSUE THREAD

**Issue by ghasemy50** [z3APA3A/3proxy#361]
Hi
Thanks for your proxy system
I have a question that radius accounting is tested? I couldn't connect it with too many tries.
Anyone can help me to run it?
Thanks all

**Comment by z3APA3A** [comment]
I have tested it with FreeRADIUS, but currently, it only send "stop" event without sending "start", so it can be misenterpreted by some overt servers. Try to sniff network traffic to eliminate connectivity/configuration issues.

**Comment by z3APA3A** [comment]
https://github.com/z3APA3A/3proxy/issues/41
