### ISSUE TITLE
Отображение ip адресов

### ISSUE THREAD

**Issue by Kuscov** [z3APA3A/3proxy#362]
3proxy 0.8.12, Win7
Использую такой конфиг чтобы сделать цепочку ПК-Tоr-Sосks5
```
internal 127.0.0.1
log
auth iponly
allow * 127.0.0.1
parent 1000 socks5 127.0.0.1 9050
parent 1000 socks4 123.255.14.15 31724
proxy -n -p5050
socks -p3128
```
Далее спомощью утилиты SVL Tun2socks (Tun2socks GUI) траффик напрвляется через TAP-адаптер.

![SVL](https://user-images.githubusercontent.com/52589364/60752761-f6969600-9fe2-11e9-82b0-49c64345d2c7.png)

Теперь при проверке на browserleaks.com/webrtc видно ip адрес адаптера, а не реальный адрес.

![tap](https://user-images.githubusercontent.com/52589364/60752766-feeed100-9fe2-11e9-8633-f791ee0261e4.png)

Как можно сделать чтобы отображались одновременно локальный и публичный ip?

**Comment by z3APA3A** [comment]
Один адрес ты видишь, потому что используешь proxy без опции -a и он раскрывает адрес клиента, а другой не видишь, потому что исползуешь socks и он не меняет HTTP запрос и ничего к нему не добавляет. Можешь добавить -a к proxy а на втором сервере заменить socks4 на http-прокси, чтобы он добавил заголовок. Либо если там 3proxy, то можно оставить socks но перенаправлять трафик в локальный прокси. 
Либо можешь поставить PCREPlugin и перезаписывать адрес.
