### ISSUE TITLE
Disable the use of gethostbyname to prevent dns requests leakage

### ISSUE THREAD

**Issue by VasiliPupkin256** [z3APA3A/3proxy#363]
According to the manual `gethostbyname` can still be called even if `nserver` option is specified. It would be handy to have an option that force 3proxy to use only the specified nserver for dns resolution.

**Comment by z3APA3A** [comment]
'fakeresolve' command does exactly this.

**Comment by z3APA3A** [comment]
previously (before 0.9), gethostbyname could be called to e.g.  resolve the name of the parent proxy, and it's still can be used to resolve some configuration things (e.g. the name of SQL server from ODBC configuration) but it's never called for hostname from client's request.

**Comment by VasiliPupkin256** [comment]
Good. Then the manual should be updates, it now says that the system routine may be called if dns query to nserver fails https://github.com/z3APA3A/3proxy/blob/devel/man/3proxy.cfg.3#L381-L383

**Comment by crackwei** [comment]
I already set nserver, but why it still use my local dns server? here are the config:

#timeouts 300 1000 600 2000 600 1800 1500 6000
log D:\software\3proxy\3proxy.log D　
logformat "L%Y-%m-%d %H:%M %N-%p %C:%c %R:%r %O %I %h %T err:%E"
rotate 3
#service

writable
#fakeresolve
nserver 208.67.222.222
nserver 8.8.8.8
nserver 208.67.220.220
nserver 1.1.1.1
nserver 4.4.4.4
nscache 65535
nscache6 65535
dnspr
 
 auth iponly
allow * * 10.0.0.0/8,192.168.0.0/16
allow *
maxconn 200
#external 10.10.10.10
#internal 0.0.0.0
#parent 1000 socks4+ 192.168.168.1 9150
parent 1000 socks5 202.221.117.46 1720 56cc74 94a94b
proxy -a -n -p8118
socks -a -n -p8668
admin -p8998

flush
