### ISSUE TITLE
Fallback for Bind to interface

### ISSUE THREAD

**Issue by clintnetwork** [z3APA3A/3proxy#364]
Hi

When I use the -De parameter and the interface down, the proxy route the connection from eth0, is it possible to prevent this ?

Cheers

**Comment by clintnetwork** [comment]
@z3APA3A

**Comment by z3APA3A** [comment]
No, interface should exist and work on the moment of client request processing. Under Linux/Unix use ifup/ifdown scripts to change proxy configuration on interface state change.

**Comment by clintnetwork** [comment]
Do you have a link or something other ? I think you need to add the possibility to stop the upstream when the interface is not available !

**Comment by z3APA3A** [comment]
It depends on your distro, look for distro-specific manuals. Start with
`man interfaces`
look for up/post-up/down/post-down and if-up.d / if-down.d

**Comment by clintnetwork** [comment]
Ha yes very nice I will see, but how down a specific proxy ? I've a 3proxy configuration with multiple proxies that bind on interface eth1, eth2, eth3, so with a `post-down` script I surely can do something but how to handle 3proxy ?

**Comment by z3APA3A** [comment]
use up/down as a trigger and run a single script to generate 3proxy configuration based on active interfaces and send USR1 signal to 3proxy to re-read configuration.
Alternatively, you can run multiple 3proxy instances with different configurations for every interface and restart only required one with up/down script, in this case use different 'pidfile' to identify the proxy.

**Comment by clintnetwork** [comment]
Ha
