### ISSUE TITLE
fail to use TCP_NODELAY

### ISSUE THREAD

**Issue by pyrrhudite** [z3APA3A/3proxy#365]
Linux kernel 4.19.1-041901-generic x86_64

" proxy -osTCP_NODELAY -ocTCP_NODELAY "

It failed to work, and just wonder how to debug this

**Comment by z3APA3A** [comment]
what is 3proxy version you are using?

**Comment by pyrrhudite** [comment]
@z3APA3A 3proxy-0.8.12 (180418205022)
And as I tried to hardcode these, 3proxy worked still laggy than squid/dante. Sorry no idea why. FYI rtt is around 160ms.
```
                opt = 1;
                if(so._setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, (char *)&opt, sizeof(int)))perror("setsockopt()");
                opt = 1;
                if(so._setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (char *)&opt, sizeof(int)))perror("setsockopt()");
```

```
        opt = 1;
        so._setsockopt(srv.cbsock, SOL_SOCKET, SO_REUSEADDR, (char *)&opt, sizeof(int));
        opt = 1;
        so._setsockopt(srv.cbsock, IPPROTO_TCP, TCP_NODELAY, (char *)&opt, sizeof(int));
```

**Comment by z3APA3A** [comment]
-os / -oc are only supported in 0.9 (devel)

**Comment by pyrrhudite** [comment]
On the other hand, SSH over 3proxy works smoothly, even without TCP_NODELAY in a server with 40ms rtt. Therefore I suppose this is not only a problem with TCP_NODELAY.

**Comment by z3APA3A** [comment]
TCP_NODELAY can be useful in some configurations where both Nagle and TCP delayed ACKs are enabled.

**Comment by pyrrhudite** [comment]
Thanks for your kind remind. Hmm, with due respect, 0.9-dev is still not as responsive as squid/dante with 160ms. Perhaps buffer management or size could be tweaked somehow? Any suggestions?

**Comment by z3APA3A** [comment]
Try to find Path MTU between clients and proxy and between proxy and target servers and set MTU on proxy interface accordingly. Or just set MTU to ~1300 and check if it helps.

**Comment by pyrrhudite** [comment]
But I think SSH packets are very small. In addition, squid is obviously fastest than dante/3proxy, dante is very slightly faster than 3proxy with TCP_NODELAY. No idea how to quantify these measurements.

**Comment by z3APA3A** [comment]
How do you measure delays?

**Comment by z3APA3A** [comment]
can you make e.g. traffic dumps client<->proxy and proxy<->destination for diffent proxies?

**Comment by pyrrhudite** [comment]
e.g.
Client (Russia) 10.0.0.2 -> Tunnel(strongswan/openvpn) -> Server gatway(West US) 10.0.0.1 

Besides SSH, 3proxy/squid/dante are also deployed in this server. Then Client 10.0.0.2 will connect 10.0.0.1:22 via the specific proxy tool (e.g. 10.0.0.1:3128, 3129, 1080, 1081 etc.), using Putty. In this scenario, you will tell the difference between proxys.

**Comment by z3APA3A** [comment]
The question is exactly how  do you measure delays, that is methodology. E.g. you sniff network traffic and check the timing of networking packets generated after pressing the key in terminal.

**Comment by pyrrhudite** [comment]
Sorry to trouble you so much. I  just verified all sets again and tcpdumped all timestamps. Each type+echo cycle finished within about 380ms. And TCP_QUICKACK was also enabled on the server interface.

Anyway thanks for your patient help.
