### ISSUE TITLE
splice() deadlock

### ISSUE THREAD

**Issue by pyhd** [z3APA3A/3proxy#366]
As tested on a low-end (1Ghz 1core Intel Westmere arch) box, 3proxy with splice() would overload abruptly and fall into almost deadlock, unless such web request was killed. It was also notified on newer(2.2Ghz 1core sandybridge) servers that CPU fluctuated severely from time to time, especially for new requests. As a comparison, Haproxy with splice() worked more stable.

**Comment by z3APA3A** [comment]
Can you provide full information on testing scenario (thread, average request sizes, amounts of data send/received, etc), tested 3proxy configuration, system configuration (e.g. hard/soft ulimits) and hardware configuration (that is, was VPS or real hardware server used)?

**Comment by pyhd** [comment]
Well, I just simply tested 1 single Youtube 4K video. Youtube will choose automatically the resolution based on connectivity.
On that ancient cloud server, i.e. Xen with 1core Westmere arch, frequency throttled to only 1Ghz, 3proxy with splice just got stuck at 100% usage, while about 10% with -s0. Bandwidth is throttled around 20mbps.
On the regular VPS with bandwidth 50mbps, both modes worked fine: without splice, CPU would be 5-10%; with splice CPU would be higher than 10% sometimes, but most of time less than 5%. As I'd like to mention, Haproxy would be 1-3%.
Above all, I just found this issue when 0.9-dev was deployed on that ancient cloud server.

**Comment by pyhd** [comment]
Oh, I forgot  to mention, the ancient cloud was installed an older kernel 4.16.0-041600-generic.

**Comment by z3APA3A** [comment]
See https://3proxy.ru/highload.asp, it explains why splice should not be used on cheap VPS.

**Comment by pyhd** [comment]
Thanks for that. It helps me a lot. I will retire this ancient cloud.
