### ISSUE TITLE
Уникальный ip для каждого пользователя

### ISSUE THREAD

**Issue by LouenLeoncoeur** [z3APA3A/3proxy#367]
Centos 7, 3proxy установлен сегодня через git, версия 3proxy-0.9-devel
При этом конфиге socks подключается, но отсутствует необходимая авторизация:
```
auth none
allow a2
parent 1000 extip IPV6 0
allow a3
parent 1000 extip IPV6 0

proxy -6 -n -a -p3123
socks -6 -n -a -p1083
```
Лог подключения:
`128.70.23.30 - a2 [01/Aug/2019:23:14:45 +0300] "CONNECT ::ffff:149.154.167.XXX:443" 00000 85 105 SOCK5/::ffff:149.154.167.XXX:443`

При добавлении авторизации по паролю socks не работает:
```
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
auth strong
allow a2
parent 1000 extip IPV6 0
allow a3
parent 1000 extip IPV6 0

proxy -6 -n -a -p3123
socks -6 -n -a -p1083
```
лог подключения:
`128.70.23.30 - a2 [01/Aug/2019:23:05:38 +0300] "CONNECT ::ffff:149.154.167.XXX:443" 00013 0 0 SOCK5/::ffff:149.154.167.XXX:443`

Я хотел бы, чтобы на каждого пользователя выделялся уникальный ip, авторизация по логину и паролю. Этот конфиг работал два года назад, на свежеустановленной версии не работает. 
Спасибо за разработку!

**Comment by z3APA3A** [comment]
У тебя клиент запрашивает подключение к IPv4 адресу, поэтому когда ты устанавливаешь внешний адрес в IPv6 подключение не проходит. Настрой клиента, чтобы он разрешал имена через прокси или сам запрашивал подключение к IPv6.

**Comment by AntonioSopran0** [comment]
Прошу помощию Почему нет доступа к моему прокси по внешнему ip? Только локально могу подключиться. Что я упускаю?
У меня Raspberry Pi4 и CentOS7


[root@localhost ~]#  **sudo netstat -tuln**
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 192.168.0.120:8054      0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0      0 192.168.0.120:9054      0.0.0.0:*               LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp        0      0 0.0.0.0:68              0.0.0.0:*
udp        0      0 127.0.0.1:323           0.0.0.0:*
udp6       0      0 ::1:323                 :::*


[root@localhost ~]# **sudo iptables -L -n -v**
Chain INPUT (policy ACCEPT 5157 packets, 1693K bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       46.173.153.19        0.0.0.0/0            tcp dpt:8054
    0     0 ACCEPT     tcp  --  *      *       46.173.153.19        0.0.0.0/0            tcp dpt:9054

Chain FORWARD (policy ACCEPT 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination


Chain OUTPUT (policy ACCEPT 4940 packets, 1674K bytes)
 pkts bytes target     prot opt in     out     source               destination

[root@localhost ~]# **sudo iptables -L INPUT -n -v**
Chain INPUT (policy ACCEPT 5214 packets, 1701K bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 ACCEPT     tcp  --  *      *       46.173.153.19        0.0.0.0/0            tcp dpt:8054
    0     0 ACCEPT     tcp  --  *      *       46.173.153.19        0.0.0.0/0            tcp dpt:9054


[root@localhost ~]# **ip route**
default via 192.168.8.1 dev enp1s0u1u3u7u1 metric 100
default via 192.168.0.1 dev eth0 metric 200
192.168.0.0/24 dev eth0 proto kernel scope link src 192.168.0.120 metric 200
192.168.8.0/24 dev enp1s0u1u3u7u1 proto kernel scope link src 192.168.8.147

Конфиг:
daemon
setgid 995
setuid 997
nserver 192.168.8.1
timeouts 1 5 30 60 180 1800 15 60
allow *
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
nscache 65536
auth strong
users login:CL:bikzp123
rotate 30
external 192.168.8.147
internal 192.168.0.120
maxconn 35
socks -p9054
proxy -p8054
flush

[root@localhost ~]#  **sudo tail -f /var/log/3proxy/3proxy.log.2023.12.13**
1702475474.025 PROXY.8054 00000 login 192.168.0.105:50645 142.251.39.74:443 1421 6067 0 CONNECT_maps.googleapis.com:443_HTTP/1.1
1702475475.123 PROXY.8054 00000 login 192.168.0.105:50646 142.251.208.174:443 1695 7880 0 CONNECT_analytics.google.com:443_HTTP/1.1
1702475477.150 PROXY.8054 00000 login 192.168.0.105:50653 142.251.173.84:443 2670 12715 0 CONNECT_accounts.google.com:443_HTTP/1.1
1702475477.150 PROXY.8054 00000 login 192.168.0.105:50674 18.244.102.109:443 1338 20055 0 CONNECT_500px.com:443_HTTP/1.1
1702475477.151 PROXY.8054 00000 login 192.168.0.105:50661 18.244.102.39:443 1441 19021 0 CONNECT_www.academia.edu:443_HTTP/1.1
1702475478.156 PROXY.8054 00000 login 192.168.0.105:50677 157.240.224.35:443 1421 25816 0 CONNECT_www.facebook.com:443_HTTP/1.1
1702475479.940 PROXY.8054 00004 - 192.168.0.194:63677 0.0.0.0:0 0 0 0 CONNECT_mozilla.cloudflare-dns.com:443_HTTP/1.1
1702475498.170 PROXY.8054 00000 login 192.168.0.105:50683 34.120.208.123:443 1321 4655 0 CONNECT_incoming.telemetry.mozilla.org:443_HTTP/1.1
1702475533.574 PROXY.8054 00000 login 192.168.0.105:50633 104.26.4.133:443 36869 91874 0 CONNECT_whoer.net:443_HTTP/1.1
1702475545.211 PROXY.8054 00004 - 192.168.0.194:63688 0.0.0.0:0 0 0 0 CONNECT_mozilla.cloudflare-dns.com:443_HTTP/1.1
1702475563.581 PROXY.8054 00000 login 192.168.0.105:50688 34.120.208.123:443 35770 13428 0 CONNECT_incoming.telemetry.mozilla.org:443_HTTP/1.1

**Comment by z3APA3A** [comment]
@AntonioSopran0 как у тебя нелокальный трафик попадает на 192.168.0.120 и уходит с него обратно?

**Comment by AntonioSopran0** [comment]
@z3APA3A у меня подключен 3G модем. Через него интернет работает но как только пытаюсь подключиться через внешний ip к локальному компьютеру чтобы получить доступ к прокси то ничего не работает. На виндовс все работает. На линукс только локально.

**Comment by z3APA3A** [comment]
Чтобы использовать два канала одновременно нужно настроить роутинг соответствующим образом, сейчас у вас весь трафик идет в канал с меньшей метрикой не зависимо от того с какого адреса он идет. Либо настройте source routing чтобы трафик от 192.168.0.120 роутить в нужном направлении (предпочтительно) либо используйте биндинг к интерфейсу (-Di / -De) в дополнение к биндингу по IP
