### ISSUE TITLE
Прозрачный 3proxy с помощью TransparentPlugin

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#369]
Здравствуйте

Пытаюсь настроить 3proxy на FreeBSD 11.3 в режиме прозрачного прокси с помощью плагина TransparentPlugin.
Нужно настроить проброс портов с белого IP в интернете в локальную сеть на основной прокси сервер (тоже 3proxy).
Чтобы порт 3128 (http, https) и порт 3129 (socks) с адреса в интернете прозрачно перенаправлялись в локальную сеть на несколько parent прокси на те же порты.
Скомпилировано все ок, плагин в конфиге подгружается, не выдавая ошибок в лог.
В сети есть пара примеров, но до конца разобраться не получилось с конфигурацией.

Пытаюсь использовать такую конфигурацию:
plugin /usr/local/lib/3proxy/TransparentPlugin.ld.so transparent_plugin
auth iponly
allow * * * 80
parent 1000 http 0.0.0.0 0
allow *
parent 1000 socks5 172.16.100.2 3129 test test
transparent
tcppm -i188.128.231.209 3129 127.0.0.1 11111
notransparent

Как я понимаю конфиг: слушаем ТСР соединения на адресе 188.128.231.209 на порту 3129 и перенаправляем на локальный адрес 172.16.100.2 на тот же порт.

Лог показывает:

1565009557.293 TCPPM.3129 00579 - 85.112.214.137:25109 172.16.100.2:3129 0 0 1 188.128.231.209
1565009557.338 TCPPM.3129 00579 - 85.112.214.137:25110 172.16.100.2:3129 0 0 1 188.128.231.209
1565009557.493 TCPPM.3129 00579 - 85.112.214.137:25111 172.16.100.2:3129 0 0 1 188.128.231.209
1565009559.622 TCPPM.3129 00579 - 85.112.214.137:25298 172.16.100.2:3129 0 0 1 188.128.231.209
1565009559.830 TCPPM.3129 00579 - 85.112.214.137:25299 172.16.100.2:3129 0 0 1 188.128.231.209

Прошу помощи, подскажите пожалуйста где ошибка!
Заранее благодарю!

**Comment by z3APA3A** [comment]
Убедись, что нет loop'а и трафик от прокси не перенаправляется обратно в прокси.
