### ISSUE TITLE
[Request] Возможность указать внешний IP или IPv6 для каждого пользователя

### ISSUE THREAD

**Issue by MolecularMan** [z3APA3A/3proxy#37]
Здравствуйте.
Очень нужна возможность указать используемый внешний адрес (задаваемый параметром -e) для каждого пользователя индивидуально, вне зависимости от того, к какому сервису он подключился. Например, все пользователи подключаются к HTTP-прокси на порту 3128, а выходят каждый через свой адрес. Те же пользователи, но уже используя SOCKS-сервер на порту 1080, аналогично имели бы на выходе тот адрес, что указан в конфиге.

Так же, думаю, многим хотелось бы, чтобы 3proxy поддерживал авторизацию через RADIUS-сервер, с возможностью указать внешний адрес для каждого пользователя в Framed-IP-Address и Framed-IPv6-Address, или только один из них, если используются параметры -4 или -6 соответственно

**Comment by z3APA3A** [comment]
Попробуй devel-версию, в ней добавлен тип парента extip, должно работать так:
allow user1
parent 1000 extip IP1 0
allow user2
parent 1000 extip IP2 0
...
proxy

**Comment by MolecularMan** [comment]
Попробовал, не пускает:

> 502 Bad Gateway
> Failed to connect parent proxy

Версия:
3proxy-0.9-devel (160128011858)

В конфиге:
```
allow test1
parent 1000 extip 2a02:XXXX:YY:ZZ::aaa 0
allow test2
parent 1000 extip 2a02:XXXX:YY:ZZ::bbb 0
allow test3
parent 1000 extip 2a02:XXXX:YY:ZZ::ccc 0

proxy -p3128 -n -6 -ia.b.c.d
```
В логах:

> PROXY.3128 00030 test1 x.y.z.w:50051 2a00:1450:401b:801::200e:80 0 0 1 GET_http://ipv6.google.com/_HTTP/1.1
> PROXY.3128 00030 test1 x.y.z.w:50059 2a03:b0c0:1:d0::b6:2001:80 0 0 1 GET_http://myip.ru/_HTTP/1.1

**Comment by z3APA3A** [comment]
А devel-версию браз из git или с сайта? Надо из git

**Comment by MolecularMan** [comment]
Разумеется из git

**Comment by z3APA3A** [comment]
А теперь?

**Comment by MolecularMan** [comment]
Ждал обновления репозитория, но увы. Соответственно, результат тот же

**Comment by z3APA3A** [comment]
Забыл запушить. Вот этот коммит: 3680f2d3b170188eb5bd7f4267afe2196c9c0c68

**Comment by MolecularMan** [comment]
Спасибо, заработало!
Уточните, стоит ли ожидать реализации связки с RADIUS?

**Comment by z3APA3A** [comment]
С RADIUS задача несколько сложней, поставь лучше отдельный фичреквест.

**Comment by MolecularMan** [comment]
Хорошо, создам. 
Хотел так же уточнить, можно ли разрешать пользователям доступ к некоторым сайтам только через v6, а к некоторым только через v4? Или как-то разделить список разрешенных сайтов для v6 и v4?
И можно ли указывать parent для определенных доменов\маски доменов, например, для обработки .tor или .i2p доменов, переадресовывая запросы стороннему серверу, а остальные домены пропускать через 3proxy?

**Comment by z3APA3A** [comment]
Можно, по маске. Например 0.0.0.0/0 для всего диапазона IPv4

**Comment by z3APA3A** [comment]
allow user * *.tor,*.i2p
parent 1000 ....
deny user * 0.0.0.0/0
allow user 
разрешит юзеру *.tor,*.i2p через родительский прокси, запретит ему остальной IPv4 и разрешит все остальное (IPv6).

**Comment by MolecularMan** [comment]
Спасибо, попробую
