### ISSUE TITLE
Архивация логов

### ISSUE THREAD

**Issue by v0vas** [z3APA3A/3proxy#371]
Доброго дня!
Не работает ежесуточная архивация логов. Система FreeBSD 12, в конфиге следующее:
```
log /var/log/3proxy/log D
archiver gz /usr/bin/gzip %F
rotate 7
```
Путь до архиватора указан верно:
```
% ll /usr/bin/gzip
-r-xr-xr-x  4 root  wheel  48400 Dec  7  2018 /usr/bin/gzip*
```
В логах архивирование не происходит:
```
root@proxy:/usr/local/etc # ll -h /var/log/3proxy
total 2320
-rw-r--r--  1 root  wheel   362K Jul 28 09:17 log.2019.07.26
-rw-r--r--  1 root  wheel   503K Jul 28 10:25 log.2019.07.28
-rw-r--r--  1 root  wheel   1.0M Aug 11 12:15 log.2019.08.08
-rw-r--r--  1 root  wheel   9.0K Aug 11 12:25 log.2019.08.11
```

**Comment by z3APA3A** [comment]
Какая версия 3proxy? С каким эккаунтом запускается 3proxy? suid/chroot используется? Если используется, есть доступ из-под suid/chroot к логам? 3proxy в полночь запущен?

**Comment by v0vas** [comment]
Версия: 3proxy-0.8.12
Запущен под юзером nobody
chroot не используется
Запущен всегда. 
Насколько я понял, дело в пользователе, под которым запущен демон. Почему тогда логи создаются под root, если в конфиге nobody указан?
```
setgid 65534
setuid 65534
```

**Comment by z3APA3A** [comment]
Ну видимо у тебя команда log в конфиге до setgid/setuid, поэтому создать при запуске лог получается, а ротейтить нет. Пиши логи в отдельную папку, дай туда доступ.
