### ISSUE TITLE
I need Makefile.arm to ARM platform

### ISSUE THREAD

**Issue by wkii** [z3APA3A/3proxy#372]
can you add Makefile.arm files to ARM platform? think you.

**Comment by z3APA3A** [comment]
If you complile 3proxy for Linux on ARM, use Makefile.Linux
If you need to compile with MSVC for ARM64 use Makefile.msvcARM64
If you cross-compile ARM version on different platform, take Makefile.openwrt-mips as an example and correct it as required (basically, only CC and LN variables should be corrected).
