### ISSUE TITLE
Include optionnal file

### ISSUE THREAD

**Issue by clintnetwork** [z3APA3A/3proxy#374]
Hey,

Is it possible to include optionnal files ? 💃 

Thanks @z3APA3A

**Comment by phantomcraft** [comment]
Yes.

`$ man 3proxy.cfg`

**_include <path>_**
_Include config file_

**Comment by clintnetwork** [comment]
Thank you @phantomcraft, the problem is I have this error when I use include:

```
root@fra1:/etc/3proxy# 3proxy 3proxy.cfg
Unable to open included file: lol
Command: 'include' failed with code 1, line 23
```

**Comment by z3APA3A** [comment]
Use full path and check 3proxy account has access to it.

**Comment by clintnetwork** [comment]
Justly, this file does not exist )

**Comment by unk2k** [comment]
root@# /bin/3proxy /etc/3proxy/3proxy.cfg 
Unable to reopen config for writing: /etc/3proxy/3proxy.cfg
Command: 'include' failed with code 1, line 1
root@# ls -la /etc/3proxy/3proxy.cfg 
-rwxrwxrwx 1 root root 119 Nov 21 13:46 /etc/3proxy/3proxy.cfg

**Comment by z3APA3A** [comment]
and the full config is... ?

**Comment by clintnetwork** [comment]
@z3APA3A does your email works, we have contacted you about consulting but you didn't answered (maybe you don't want answer too :D)

**Comment by unk2k** [comment]
> and the full config is... ?

root@# cat /etc/3proxy/conf/3proxy.cfg 
writable
nserver 1.1.1.1
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
log
logformat L%t%. L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T
users iddqd:CL:idkfa
auth strong
maxconn 10000
proxy -a -p9999

**Comment by unk2k** [comment]
Процесс установки следующий,
debian 10 x64 (digiralocean droplet)

```
apt-get install gcc make git build-essential psmisc -y
git clone https://github.com/z3apa3a/3proxy
cd 3proxy
git checkout tags/0.9.1 -b 0.9.1
ln -s Makefile.Linux Makefile
make
make install
scp 3proxy.cfg root@.../etc/3proxy/conf/3proxy.cfg 
/etc/init.d/3proxy restart
```

**Comment by z3APA3A** [comment]
After 
chroot /usr/local/3proxy

/ in all paths is /usr/local/3proxy. before "writable" set config file location with "config /etc/3proxy/conf/3proxy.cfg", overwise it tries to make /etc/3proxy/3proxy.cfg  writable and this file is not available from chroot.

**Comment by z3APA3A** [comment]
log and couneters location must be within /usr/local/3proxy with path relative to /usr/local/3proxy. that is, for /usr/local/3proxy/log use
log /log/logfile.example

**Comment by z3APA3A** [comment]
@clintnetwork I see no unresponded message, for a last days at least. Try to contact from different e-mail address. But, anyway, currently I'm too busy to have any contracts and/or guaranteed SLAs.

**Comment by clintnetwork** [comment]
Could you confirm me your email ? Because I'm pretty sure of contact you from two different mails 😋

**Comment by z3APA3A** [comment]
Use 3proxy@3proxy.ru or 3proxy@3proxy.org

**Comment by unk2k** [comment]
@z3APA3A awesome, thanks.
One more problem that I found. Using 3proxy and connect to a website in 300 parallel requests at time I got a few `timeout` errors. 

```
201121155756.897 8899 00000 aleZLKyB44v6fkkgzgM a.128.f.135:50124 g.82.h.1:443 1109 5961 0 CONNECT _.org:443 HTTP/1.1
201121155756.898 8899 00000 aleZLKyB44v6fkkgzgM a.128.f.135:49982 g.82.h.1:443 0 0 0 CONNECT _.org:443 HTTP/1.1
201121155756.898 8899 00000 aleZLKyB44v6fkkgzgM a.128.f.135:49976 g.82.h.1:443 0 0 0 CONNECT _.org:443 HTTP/1.1
201121155756.900 8899 00000 aleZLKyB44v6fkkgzgM a.128.f.135:49704 g.82.h.1:443 1782 6717 0 CONNECT _.org:443 HTTP/1.1
201121155756.900 8899 00000 aleZLKyB44v6fkkgzgM a.128.f.135:50000 g.82.h.1:443 1109 5961 0 CONNECT _.org:443 HTTP/1.1
```

The lines that contain triple zeros are detected as timeout errors on my software side.
When I use up to 100 parallel requests everything is okay.
How to resolve the problem?

**Comment by clintnetwork** [comment]
> It means you probably was replied, checked the spam folder. Use 3proxy@3proxy.ru or 3proxy@3proxy.org

Okey, we have sent it again, sender is quentin@

**Comment by z3APA3A** [comment]
@unk2k, Sorry, but I just have no answer. Usually, something need to be tuned for large number of connections. It may be a system problem or a router issue, e.g. if you use some SOHO router it just can have a limit on NAT table size or it may be a limitation on provider's side. For 3proxy itself a number of connection does not matter. Some common moments are reflected in
https://3proxy.ru/highload.asp
but this document doesn't cover kernel/hardware tuning issues and ISP's limitations.

**Comment by unk2k** [comment]
@z3APA3A I got one more problem.
```
< HTTP/1.0 200 Connection established
< 
* Proxy replied 200 to CONNECT request
* CONNECT phase completed!
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* CONNECT phase completed!
* CONNECT phase completed!
* error:1408F10B:SSL routines:ssl3_get_record:wrong version number
* Closing connection 0
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
```

Direct request works very well.

**Comment by SalimF** [comment]
```
/usr/bin/3proxy /etc/3proxy/3proxy.cfg
Failed to open pid file /var/run/3proxy/3proxy.pid
Command: 'pidfile' failed with code 1, line 3
```
Still have same issue .

```
 cat  /etc/3proxy/3proxy.cfg
#!/bin/3proxy
#daemon
pidfile /var/run/3proxy/3proxy.pid
chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg
```

```
cat  /etc/3proxy/conf/3proxy.cfg
nscache 65536
nserver 1.1.1.1
nserver 1.0.0.1
config /conf/3proxy.cfg
#monitor /conf/3proxy.cfg
#log /logs/3proxy-%y%m%d.log D
#rotate 60
#counter /count/3proxy.3cf
#include /conf/counters
#include /conf/bandlimiters

auth none
dnspr
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
socks -4 -n -u -p43126  -i0.0.0.0
proxy -4 -n -u -p43129 -a  -e0.0.0.0  -i0.0.0.0
```

```
cat /etc/*release
AlmaLinux release 8.6 (Sky Tiger)
AlmaLinux release 8.6 (Sky Tiger)
NAME="AlmaLinux"
VERSION="8.6 (Sky Tiger)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
```

**Comment by z3APA3A** [comment]
Remove 
 pidfile /var/run/3proxy/3proxy.pid
it's not required with systemd, current master fixes it already.

**Comment by SalimF** [comment]
> Remove pidfile /var/run/3proxy/3proxy.pid it's not required with systemd, current master fixes it already.

Thanks, I was kind to solve it by creating directory `/var/run/3proxy` , now I did as you said remove `3proxy.pid` line ,,
But still I'm not able to connect to the proxy, still diagnostic it, even I enabled the port in the firewall rules, and the proxy were working before I restart my VPS.

I tried both with direct command `/usr/bin/3proxy /etc/3proxy/3proxy.cfg` and systemd service start 
this  is version :-
`3proxy tiny proxy server 3proxy-0.9.3 ()`

**Comment by z3APA3A** [comment]
> I was kind to solve it by creating directory /var/run/3proxy

Don't know about Alma, but systemd-based distros usually remove /var/run content on reboot. You can add
`system "mkdir /var/run/3proxy || true"` prior to `pidfile` to create directory if not present.
