### ISSUE TITLE
fail2ban filter

### ISSUE THREAD

**Issue by al-indigo** [z3APA3A/3proxy#376]
В fail2ban неактуальный фильтр проваленных аутентификаций.

Собственно, добавил детальное описание им прямо туда, но может быть проще и здесь дать ссылку.
https://github.com/fail2ban/fail2ban/issues/2509

**Comment by z3APA3A** [comment]
Привет,
поддержкой правил для fail2ban занимаюсь не я, поэтому отрепортить это fail2ban было правильным.
