### ISSUE TITLE
Как можно ограничить

### ISSUE THREAD

**Issue by U-III** [z3APA3A/3proxy#378]
Сейчас использую для разрешения такую конструкцию
*vk.com,*userapi.com,www.gstatic.com,www.google.com

А мне было бы нужно
вот так 

*vk.com,*userapi.com,www.gstatic.com/recaptcha/,www.google.com/recaptcha/

Так можно?

**Comment by z3APA3A** [comment]
Google использует HTTPS и трафик там шифрован, прокси не видит URI запроса.

Сделать можно через PCREPlugin чтобы ограничивать запросы + SSLPlugin чтобы расшифровывать трафик через подмену сертификата, но делать так в продакшене не стоит, а на живых юзерах ни в коем случае нельзя.

**Comment by U-III** [comment]
Ну я в общем так и думал
А если так напишу
*vk.com,*userapi.com,www.gstatic.com,www.google.com

просто google.com же не откроется
