### ISSUE TITLE
Прозрачная аутентификация Windows пользователей

### ISSUE THREAD

**Issue by alexbosh77** [z3APA3A/3proxy#379]
2 вопроса:
1) Когда будет возможность прозрачной авторизации в домене Windows без введения логина и пароля в браузере.
2) Будет ли возможность allow и deny работать не по пользователям а по группе пользователей?

**Comment by z3APA3A** [comment]
1. Никогда, т.к. поддерживает только IE и только при определенных условиях. Посмотри в сторону dnsauth.
2. Скорей всего тоже никогда, т.к. проверка членства в группах для каждого запроса это слишком "тяжелая" операция по ресурсам, если речь о Windows-группах. Если о группах внутри 3proxy - можно списки пользователей задавать через файл, включать через $.
