### ISSUE TITLE
3proxy на raspbian - 00013 - сбой подключения connect()

### ISSUE THREAD

**Issue by bgvndas** [z3APA3A/3proxy#380]
3proxy на raspbian - 00013 - сбой подключения connect() 
Что это может быть? В raspberry включены 3г модемы. Интернет есть.
конфиг
nscache 65536
nserver 8.8.8.8
timeouts 1 5 30 60 180 1800 15 60
config /conf/3proxy.cfg
monitor /conf/3proxy.cfg
log /logs/3proxy-%y%m%d.log D
rotate 60
users user:CL:pass
auth strong
allow user
proxy -n -a -p18014 -i192.168.0.98 -e192.168.14.100
proxy -n -a -p18015 -i192.168.0.98 -e192.168.15.100
admin -p18001
flush
лог
190901140601.750 18014 00013 user 192.168.0.102:53469 74.125.205.106:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
190901140603.454 18014 00013 user 192.168.0.102:53471 40.112.72.205:80 0 0 0 GET http://xbox.com/ HTTP/1.1

работает прокси только на модеме с более низким metric. при этом proxy на втором модеме не работает - 00013. так же не работают оба модема если проставить более низкий metric на lan интерфейсе

**Comment by z3APA3A** [comment]
сделай 
nc -s 192.168.14.100 74.125.205.106 443
и посмотри почему коннект не проходит
