### ISSUE TITLE
Не открываются заблокированные сайты через 3proxy

### ISSUE THREAD

**Issue by v0vas** [z3APA3A/3proxy#381]
Добрый вечер!
Проблема появилась вчера. При попытке открыть например сайт rutracker.org
В логах следующее:
```
1567627303.749 10059 10.25.14.50 TCP_MISS/200 0 CONNECT 195.82.146.214:80 user DIRECT/195.82.146.214 application/unknown
1567627303.754 10064 10.25.14.50 TCP_MISS/200 0 CONNECT 195.82.146.214:80 user DIRECT/195.82.146.214 application/unknown
1567627304.376 10066 10.25.14.50 TCP_MISS/200 0 CONNECT 195.82.146.214:80 user DIRECT/195.82.146.214 application/unknown
```
Открывается такая страница:
![image](https://user-images.githubusercontent.com/24398074/64287382-34268980-cf68-11e9-9e6a-64f9599e39b6.png)
Пробовал перегружать прокси, тестировал через программу Proxifier, вводил ip вручную в настройках подключения браузеров, результат один. В чем может быть проблема?

**Comment by z3APA3A** [comment]
Этот вопрос к 3proxy отношения не имеет, т.к. очевидно трафик блокируется не 3proxy.

Повесь прокси на нестандартный порт, если это не поможет - используй VPN с шифрованием трафика вместо прокси, т.к. в стандартном прокси нет шифрования запросов между клиентом и прокси.
