### ISSUE TITLE
Друзья помогите пожалуйста разобраться с софтом 3proxy.

### ISSUE THREAD

**Issue by zalmaniddqd** [z3APA3A/3proxy#383]
Windows 2019 server standart.
Выдает лшибку, в журнале ыиндовс ошибок нет
C:\3proxy\3proxy\bin64\3proxy.exe : Failed to create service: No error
At line:1 char:1
+ C:\3proxy\3proxy\bin64\3proxy.exe --install
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Failed to create service: No error:Str 
   ing) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
  вот конфиг:

auth none
log
proxy

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#SERVICE
