### ISSUE TITLE
Error start 3proxy... help me pls

### ISSUE THREAD

**Issue by tannd88** [z3APA3A/3proxy#384]
Hi all,
I use raspberry pi zero w, I need config 3proxy as 3g/4g usb 
My ip internal  wlan0: 192.168.1.51 & 3g/4g usb interface name: ppp0

![image](https://user-images.githubusercontent.com/55658199/65391789-52c5b680-dd97-11e9-9225-47145b9f2805.png)

After install 3proxy and config 3proxy.conf

![image](https://user-images.githubusercontent.com/55658199/65391825-acc67c00-dd97-11e9-891f-61dc8130c88b.png)

Start service 3proxy error 

![image](https://user-images.githubusercontent.com/55658199/65391835-c798f080-dd97-11e9-9919-3879872c03ce.png)

Can you help me pls!!!

**Comment by z3APA3A** [comment]
-De implemented in devel (0.9) version
