### ISSUE TITLE
Как перенаправлять трафик в 3proxy для разных пользователей?

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#385]
Стоит задача в 3proxy настроить "разруливание" трафика по имени пользователей.
Не могли бы вы подсказать как правильно это организовать?
То есть нужно, чтобы пользователи user1, user2 и user3 перенаправлялись на один родительский прокси, а пользователи user4, user5 и user6 перенаправлялись на другой родительский прокси.

Предполагал сделать это с помощью allow и parent следующим образом:

allow user1,user2,user3
parent 1000 http 192.168.1.10 3128

allow user4,user5,user6
parent 1000 http 192.168.1.11 3128

proxy -n -a -i192.168.1.1

Однако на тостере люди мне подсказали, что это не правильно и нужно запускать несколько копий 3proxy.
Тогда как? Подскажите пожалуйста.

**Comment by z3APA3A** [comment]
Да, так можно делать.
