### ISSUE TITLE
Балансировка нагрузки между 2+ исходящими интерфейсами

### ISSUE THREAD

**Issue by Leksandrua** [z3APA3A/3proxy#388]
Подскажите пожалуйста, как можно организовать балансировку нагрузки между 2+ исходящими интерфейсами средствами 3proxy? Подходит вариант, когда одновременно для исходящего трафика используется только один сетевой интерфейс

Использую компьютер с 3+ модеми, задача +/- равномерно размазывать нагрузку по ним

Сейчас использую этот конфиг

```
service
monitor C:\3proxy\bin64\3proxy.txt
maxconn 500
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
auth strong
users login:CL:pass
allow login
proxy -n -a -p8001 -i192.168.241.104 -e192.168.10.100
proxy -n -a -p8002 -i192.168.241.104 -e192.168.11.100
proxy -n -a -p8003 -i192.168.241.104 -e192.168.12.100
flush
```

Пробовал играться с кодом ниже в различных вариациях - безрезультатно
```
auth iponly
allow *
parent 500 http 10.1.1.101 0
parent 500 http 10.2.1.102 0
```

**Comment by z3APA3A** [comment]
https://3proxy.ru/highload.asp в разделе Extending ephemeral port range есть варианты. Для распределения нагрузки по интерфейсам выбора IP адреса недостаточно, необходимо еще выбирать интерфейс через -De или через настройки source uroting.
