### ISSUE TITLE
Ограничения для нескольких прокси

### ISSUE THREAD

**Issue by jokero99** [z3APA3A/3proxy#389]
Подскажите пожалуйста, как распределить ограничения для разных прокси
Для портов 8001 и 8002 - доступ только в инстаграм с ограничения по подключениям = 50
Для порта 8003 полный доступ, но с ограничение по подключения: 200

service
monitor C:\3proxy\bin64\3proxy.txt
auth strong
users login:CL:pass login2:CL:pass
allow login
proxy -n -a -p8001 -i192.168.1.104 -e192.168.10.100
proxy -n -a -p8002 -i192.168.1.104 -e192.168.11.100
flush
allow login2
proxy -n -a -p8003 -i192.168.1.104 -e192.168.12.100
flush

**Comment by z3APA3A** [comment]
смотри описание команд allow/deny, maxconn и connlim. В зависимости от того, что именно тебе надо, например

...
allow login * *instagramm.com
maxconn 50
proxy -n -a -p8001 -i192.168.1.104 -e192.168.10.100
proxy -n -a -p8002 -i192.168.1.104 -e192.168.11.100
flush
allow login2
maxconn 100
proxy -n -a -p8003 -i192.168.1.104 -e192.168.12.100
flush

или, возможно, требуется connlim для более точного управления лимитами.
