### ISSUE TITLE
[Request] Возможность указать размер TCP-пакета для прокси

### ISSUE THREAD

**Issue by AlexeySa** [z3APA3A/3proxy#39]
Прошу добавить возможность указывать размер буфера для HTTP-запроса.
Хотелось бы, чтобы http-запрос от прокси шёл несколькими TCP-пакетами и это можно было бы регулировать.

Помогает для DPI в России :)

**Comment by z3APA3A** [comment]
Размер пакета определяется параметром MTU интерфейса, поменяй MTU на желаемый. Можно поменять параметр MSS через iptables'ы.


В 3proxy есть параметр -b задающий размер внутреннего буфера, например

-b512

но он оказывает лишь косвенное влияние, т.к. в TCP используется алгоритм Нагла.

Но вообще, практически все современные DPI используют stateful-фильтрацию, и обойти их размером пакета не получится.

**Comment by AlexeySa** [comment]
Вы ошибаетесь. Практически все DPI анализируют только один первый пакет из-за затратности по ресурсам. Для примера можно почитать это https://github.com/bol-van/zapret . Приходится клепать свои программки для деления пакетов. Было бы здорово, если 3proxy мог управлять сегментацией первого пакета клиентского HTTP-запроса.
