### ISSUE TITLE
how do I set up multiple dongles with 3proxy on a usb hub in Raspbian? Tried everything

### ISSUE THREAD

**Issue by Proxyseeker2** [z3APA3A/3proxy#391]
Don't know why this is closed because it did not do anything other than not work.
Link to closed issue: https://github.com/z3APA3A/3proxy/issues/387

Thanks for trying to help but it doesn't work. I tried it with only 1 IP and this line did not work also, for example:

proxy -p1111 -a -ixxx.xxx.xxx.xxx -exxx.xxx.xxx.xxx -Deeth1
proxy -p1112 -a -ixxx.xxx.xxx.xxx -exxx.xxx.xxx.xxx -Deeth2

Both don't work.

Removing the -D and using different dongles (2 that have different ips) works, so my configuration is allright. I need for figure out how to do it for the same ip (as mentioned in OP)

**Comment by z3APA3A** [comment]
You've asked the question and you've got the answer. "don't work" means you have some version of 3proxy installed + some configuration, you have expected results for this configuration, you have actual results for this configuration **but** expected results do not match actual ones and you have some log files you have already looked into to understand a problem. You have shared nothing of this.

So, I can only say you either use the wrong version of 3proxy (-De i implemented in devel) or you have an invalid proxy or system configuration, which does not match the expected results.
