### ISSUE TITLE
parent http proxy get "407 Proxy Authentication Required"

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#393]
Same problem here,I changing basic to Basic in the 2 files,but it still got "407 Proxy Authentication Required". What's the 3proxy version?I used 3proxy 0.8.13. I checked the log of 3proxy,the error code is 00000 and I test curl the parent proxy work fine in the same server.

Below is my config section:

allow * MYUSERNAME

parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-hl_XXXX-zone-sharedip-ip-YY.YY.YY.YY PROXYPASSWORD

socks -a -p30001 -i x.x.x.x

--------------------------------------------------------------------------------------------------
**Edit**: found the issue, the problem is not the pluses but the fact that 3proxy send the header ``Proxy-Authorization: basic <base64-encoded-auth>``, changing ``basic`` to ``Basic`` fixes the problem. Lines in question:
https://github.com/z3APA3A/3proxy/blob/22cf9254c57e6f9b55df768cd3800697ae4ad4a3/src/auth.c#L58
https://github.com/z3APA3A/3proxy/blob/22cf9254c57e6f9b55df768cd3800697ae4ad4a3/src/proxy.c#L862

_Originally posted by @Niek in https://github.com/z3APA3A/3proxy/issues/305#issuecomment-542570806_

**Comment by z3APA3A** [comment]
This is not a 3proxy bug, standard requires authentication schema to be matched case insensitively, so this bug is in a parent proxy. Devel version has a patch to deal with buggy parent proxy, for stable version I have no plans to patch anything.

**Comment by raintears2** [comment]
Thank you for reply.
I  installed two 3proxy service for two ips with the same 3proxy version.Both has log file.
FIRSTIP  opens http service with user/password.Use curl test http works fine.
SECONDIP opens socks5 and use parent via first ip to access internet.When connect the SECONDIP with socks5,it display "<html><head><title>407 Proxy Authentication Required</title></head>".

Log file of  FIRSTIP(http proxy) displays   "2019Oct24 100430 -0400,- SECONDIP:60099 error:00004 SECONDIP:2227 use 0.0.0.0 connect to 0.0.0.0:0 requested 104.24.20.50:80 hostname:myip.ipip.net S:0,R:0 hops:0 text:GET http://myip.ipip.net/ HTTP/1.0“

Log fie of SECONDIP(socks5 proxy) displays  "2019Oct24 100430 -0400, MYUSERNAME SOCK5:30000 error:00000 CLIENTIP:55326 use SECONDIP connect to FIRSTIP:60099 requested 104.24.20.50:80 hostname:104.24.20.50 S:166,R:634 hops:1 text:CONNECT 104.24.20.50:80
”

Below is the config section.

allow  MYUSERNAME
parent 1000 http FIRSTIP 60099 MYUSER MYPASSWORD
socks -a -p30000 -iSECONDIP
flush

**Comment by raintears2** [comment]
Thank you for reply.
I installed two 3proxy service for two ips with the same 3proxy version.Both has log file.
FIRSTIP opens http service with user/password.Use curl test http works fine.
SECONDIP opens socks5 and use parent via first ip to access internet.When connect the SECONDIP with socks5,it display "<title>407 Proxy Authentication Required</title>".

Log file of FIRSTIP(http proxy) displays "2019Oct24 100430 -0400,- PROXY:60099 error:00004 SECONDIPA:2227 use 0.0.0.0 connect to 0.0.0.0:0 requested TARGETWEBIP:80 hostname:TARGETWEB S:0,R:0 hops:0 text:GET http://TARGETWEB/ HTTP/1.0“

Log fie of SECONDIP(socks5 proxy) displays "2019Oct24 100430 -0400,lzl SOCK5:30000 error:00000 CLIENTIP:55326 use SECONDIP connect to FIRSTIP:60099 requested TARGETWEBIP:80 hostname:TARGETWEBIP S:166,R:634 hops:1 text:CONNECT TARGETWEBIP:80”

Below is the config section.

allow MYUSERNAME
parent 1000 http FIRSTIP 60099 MYUSER MYPASSWORD
socks -a -p30000 -iSECONDIP
flush

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#ERRORS

**Comment by z3APA3A** [comment]
you can not redirect traffic from socks to http proxy, because socks proxy knows nothing about http. To handle http traffic you have to do local redirection to http proxy first to parse http request.

**Comment by raintears2** [comment]
I have patched 3proxy with this commition https://github.com/z3APA3A/3proxy/commit/9996856698d27510299a4ef23a2710cf8881cc9c  

 When I change the "http" to "connect",it works fine when parent the http proxy(open with 3proxy).
Then I tested the third party http proxy, the log said  error:00033.

parent 1000 connect zproxy.lum-superproxy.io 22225 lum-customer-hl_XXXX-zone-sharedip-ip-YY.YY.YY.YY PROXYPASSWORD

**Comment by raintears2** [comment]
I found  the parent proxy username  like "lum-customer-hl_XXXX-zone-sharedip-ip-YY.YY.YY.YY" can't be got correctly.  In  src/auth.c , in the function "handleredirect",the cur->extuser'value is the parent proxy password, but cur->extpass's value is (null).So it failed to connect the parent proxy and got  error:00033.

**Comment by z3APA3A** [comment]
->extpass will be MYPASSWORD
if you have
parent 1000 http FIRSTIP 60099 MYUSER MYPASSWORD
for 'allow' which match your request.

**Comment by z3APA3A** [comment]
parent http
does not work for socks proxy, because socks doesn't handle or process HTTP requests. For socks proxy it works like 'parent tcp' and it's impossible to add any authentication.

**Comment by z3APA3A** [comment]
You have to redirect HTTP traffic to local 'proxy' first. See
https://3proxy.ru/howtoe.asp#REDIR

**Comment by raintears2** [comment]
Is this config right?
allow * * * 80.443
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername  parentpassword
allow  socksusername
socks -a -p10001

**Comment by z3APA3A** [comment]
No, https traffic should not be parented to http, only http. It should be something like
allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow * * * 443
parent 1000 connect+ zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow socksusername
socks -a -p10001

**Comment by Niek** [comment]
Why not something like this? Works with HTTP+HTTPS:
```
auth iponly
allow * 127.0.0.1 * *
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
proxy -p10001 -i127.0.0.1 -a
```

**Comment by raintears2** [comment]
I need socks5 proxy,and 3rd party only provide http proxy.
I changed to below config.and it works now.But I can't understand why should write  "allow * * * 80".

allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow SOCKSUERNAME
socks -a -p10001

**Comment by raintears2** [comment]
I need socks5 proxy with Username/password authentication,and 3rd party only provide http proxy.

I changed to below config.and it works now.But I can't understand why should write "allow * * * 80".

allow * * * 80
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow SOCKSUERNAME
socks -a -p10001

**Comment by z3APA3A** [comment]
'parent' command extends last 'allow' command, that is only traffic for tcp/80 should be redirected to local http proxy

**Comment by raintears2** [comment]
There is a error:00512 in the log.
When I browse the websites (https,port :443) in the Chrome via Proxifier in windows 7 ,it failed and has error:00512 in 3proxy log file. 
But when browse the websites with port :80,it succeed.How to fixed it

allow * * * 80,443
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow SOCKSUERNAME
socks -a -p10001

Below is config file


allow * * * 80,443
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow SOCKSUERNAME
socks -a -p10001

**Comment by raintears2** [comment]
When I browse the websites (https,port :443) in the Chrome via Proxifier in windows 7 ,it failed and has error:00512 in 3proxy log file.
But when browse the websites with port :80,it succeed.How to fixed it?

allow * * * 80,443
parent 1000 http 0.0.0.0 0
parent 1000 http zproxy.lum-superproxy.io 22225 lum-customer-parentusername parentpassword
allow SOCKSUERNAME
socks -a -p10001

**Comment by raintears2** [comment]
curl -vvv --socks5 SOCKSUERNAME:SOCKSPWD@PROXYIP:10001 https://ip.cn
* About to connect() to proxy PROXYIP port 10001 (#0)
*   Trying PROXYIP ... connected
* Connected to PROXYIP port 10001 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS error -12263
* Closing connection #0
* SSL connect error
curl: (35) SSL connect error

**Comment by z3APA3A** [comment]
Read config from this reply
https://github.com/z3APA3A/3proxy/issues/393#issuecomment-554898400
and all messages from this thread _carefully_.

The same answer for the 3rd time: HTTP traffic should be redirected to local proxy before redirecting to external http proxy to parse HTTP request, because HTTP request needs to be parsed as HTTP in order to add authentication. 

HTTPS traffic _should not_ be sent to local http proxy, because it's encrypted and can not be parsed. It should be sent to external proxy via 'connect' method.
