### ISSUE TITLE
Questions, comments, bugreports and feature requests #2

### ISSUE THREAD

**Issue by z3APA3A** [z3APA3A/3proxy#395]
For feature requests and bugreports please create an issue.
If you have any questions or comments you can create an issue or write to 3proxy@3proxy.ru.
Please read at least FAQ and How To before asking:
http://3proxy.ru/doc/
http://3proxy.ru/documents/

begins in #11

**Comment by m3adow** [comment]
Hey, thanks for the work on 3proxy.

I'm trying to configure 3proxy to proxy http-proxy requests through a connect proxy, but I can't get it to run.

My config (3proxy is currently running in a Docker container):

```
nserver 1.1.1.1
nserver 9.9.9.9
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
log /dev/stdout
logformat "L%N.%p %E %U %C:%c %R:%r %O %I %h %T"
allow *
parent 1000 connect theconnectproxy.com  user password
allow *
proxy -p3128
```

3proxy reports a "32" error, so timeout/wrong reply. When testing the 3proxy connection with curl, 3proxy returns a 502. When testing the connection directly with curl, it works like a charm.

Where is my error? In the configuration or in my train of thought?

**Comment by z3APA3A** [comment]
in example above port is missed in 'parent' config, but "32" error means no valid response was received from parent proxy. I can guess "connect" does not match actual type of parent proxy.

**Comment by phantomcraft** [comment]
When an upstream proxy is provided by 3proxy itself, IPv6 connections don't work:

```
socks -l -p1111

3proxy << EOT
fakeresolve
allow *
parent 1000 socks5+ 127.0.0.1 1111
socks -p1112

curl --proxy socks5://127.0.0.1:1111 [2620:12e:1000::a00:f]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.<br />
</p>
</body></html>

curl --proxy socks5://127.0.0.1:1112 [2620:12e:1000::a00:f]
curl: (52) Empty reply from server

```

**Comment by z3APA3A** [comment]
You have missed the logs and 3proxy version

**Comment by phantomcraft** [comment]
My version is 3proxy-0.9-devel, the latest commit for now.

**Comment by z3APA3A** [comment]
and logs from both services?

**Comment by phantomcraft** [comment]
```
$ socks -l -p1111
191127030251.550 1111 00000 - 0.0.0.0:1111 0.0.0.0:0 0 0 0 Accepting connections [53823/4164802368]
```

```
$ 3proxy << EOT
log
fakeresolve
allow *
parent 1000 socks5+ 127.0.0.1 1111
socks -p1112
EOT
191127030302.249 1112 00000 - 0.0.0.0:1112 0.0.0.0:0 0 0 0 Accepting connections [53833/2585831168]
```

### 1)

```
curl --proxy socks5://127.0.0.1:1111 [2620:12e:1000::a00:f]
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /
on this server.<br />
</p>
</body></html>
```

Logs from port 1111:

`191127030439.257 1111 00000 - 127.0.0.1:46766 2620:12e:1000::a00:f:80 86 406 0 CONNECT 2620:12e:1000::a00:f:80`


### 2)

```
$ curl --proxy socks5://127.0.0.1:1112 [2620:12e:1000::a00:f]
curl: (52) Empty reply from server
```

Logs from port 1111:

`191127031145.990 1111 00100 - 127.0.0.1:49953 0.0.0.0:0 0 0 0 CONNECT 2620:12e:1000::a00:f:0`

Logs from port 1112

`191127031145.990 1112 00000 - 127.0.0.1:59070 127.0.0.1:1111 0 39 1 CONNECT 2620:12e:1000::a00:f:80`

**Comment by z3APA3A** [comment]
as a workaround, try to use

```
allow * * 127.0.0.2
parent 1000 socks5+ 127.0.0.1 1111
allow *
parent 1000 socks5 127.0.0.1 1111
```

to forward IPv4/IPv6 address to parent proxy as an address rather than name, I will add a fix to make behavior consistent between client and server part for this case.

**Comment by z3APA3A** [comment]
@phantomcraft 
I can't reproduce this behavior in current devel. In my case logs from 1111 show valid CONNECT operation:

191127092055.923 1111 00000 - 0.0.0.0:1111 0.0.0.0:0 0 0 0 Accepting connections [9152/17232]
191127092155.486 1111 00013 - 127.0.0.1:58734 2620:12e:1000::a00:f:80 0 0 0 CONNECT 2620:12e:1000::a00:f:80

**Comment by komato3huk** [comment]
Постоянно сыпет 21 ошибку. 
Пропадает конект. Использую 20 прокси под вэб серфинг.

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/howtor.html#ERRORS
у тебя память кончилась или ты уперся в лимиты по памяти, см https://3proxy.ru/highload.asp

**Comment by komato3huk** [comment]
> https://3proxy.ru/doc/howtor.html#ERRORS
> у тебя память кончилась или ты уперся в лимиты по памяти, см https://3proxy.ru/highload.asp
Спасибо в debian исправил. 
Но теперь схожая трабла в win2016 после поднятия прокси система начинает оооочень медленно реагировать и все сетевые службы начинают троить и отвечать через раз. Нет ли тонкостей снятия ограничений в win подобных системах? Понимаю что это не приоритет но было бы отлично дать рекомендации по highload в win подобных

**Comment by manishb7** [comment]
Is it possible to allocate a proxy from a list of proxies to a pool of users according to availability?
Ex- user1, user2 and user3 reaching the proxy server via port 3128, 3129 and 3130 respectively but get allocated to external proxy list 192.168.1.1 or 192.168.2.1 whichever is not being used at that moment. I want all the traffic to have a single thread for each proxy but users could share them at different times.

**Comment by z3APA3A** [comment]
It's possible to assign external proxy randomly, see 'parent' command
https://3proxy.ru/howtoe.asp#REDIR
https://3proxy.ru/howtoe.asp#ROUNDROBIN
https://3proxy.ru/howtoe.asp#CHAIN

**Comment by merlinjk** [comment]
hi is it possible to make just a backconnect server .
because i have a pool of proxies but i can just put 1 whitelist ip and i want to use my server for backconnect it like

me -- backconnectserver -- poolproxieswhitelistforbackconnectserver

and set user password on backconnect server
like 0.0.0.0:10000 on backconnectserver redirect to 1.1.1.1:3128

**Comment by ezbik** [comment]
>It's possible to assign external proxy randomly, see 'parent' command

Yeah but just a 1k-pool of them at once ? Because the minimum granularity is 1 and maximum is 1000.

**Comment by z3APA3A** [comment]
A simpliest way if no additional authentication is required is 
```
tcppm 10000 1.1.1.1 3128
tcppm 10001 1.1.1.2 3128

```etc

**Comment by merlinjk** [comment]
i just need auth strong on 0.0.0.0 with iponly it work but ..

**Comment by APX403** [comment]
Hello,

I have this configuration to run 2 differents proxy with 2 differents users : 

```
auth iponly strong
flush
deny *

flush
users "user1:CR:$1$9i9Xuy4A$48Cy0WhhP0DdYBsJKyVNt."
allow user1
proxy -a -i192.168.0.71 -p7001 -Deups1 -olSO_REUSEADDR,SO_REUSEPORT -ocTCP_TIMESTAMPS,TCP_NODELAY -osTCP_NODELAY
socks -a -i192.168.0.71 -p8001 -Deups1

flush
users "user2:CR:$1$9i9Xuy4A$48Cy0WhhP0DdYBsJKyVNt."
allow user2
proxy -a -i192.168.0.71 -p7002 -Deups2 -olSO_REUSEADDR,SO_REUSEPORT -ocTCP_TIMESTAMPS,TCP_NODELAY -osTCP_NODELAY
socks -a -i192.168.0.71 -p8002 -Deups2
```

It's working but is it a good way to do it ? Do you have an example to do the same thing with RADIUS ?

Thanks a lot for your help :) !!

**Comment by z3APA3A** [comment]
It's OK, i just can recommend to use authentication cache with crypted password, the crypt needs to be calculated for every request otherwise. 

In the case of RADIUS you need no users/allow/deny, because authorization is performed by RADIUS, authentication cache is also recommended. See https://3proxy.ru/doc/man3/3proxy.cfg.3.html for supported attrbiutes. That is all need something like

authcache ...
radius ...
auth cache radius

proxy ...
socks ...
proxy ...
socks ...

**Comment by z3APA3A** [comment]
Continued in #560
