### ISSUE TITLE
Windows version parent not working

### ISSUE THREAD

**Issue by ovs1** [z3APA3A/3proxy#398]
I can´t get parent to work. I try to forward the proxy request to a new proxy but it only takes the server ip as proxy.

Config File:

#!/usr/bin/3proxy
service

log 3proxy.log
fakeresolve
nserver 8.8.8.8
nserver 8.8.4.4

auth none
allow *
parent 1000 http proxy.ipB 8085
proxy -a -p8080

#End Of config

When i try to connect to proxy myserverip:8080 i and i check my ip it shows my server ip not the proxy in parent.

Also if i set auth iponly it displays Username / Password screen. 
Is it better to run 3proxy on a linux server? Is there a diffrence?

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqe.asp

Q: Why restrictions (redirections, limits, etc) do not work?
A: Most probable reasons: 'auth none' or no auth is used. For any ACL based feature one of 'iponly', 'nbname' or 'strong' auths required. Sequence of commands may be invalid. Commands are executed one-by-one and 'proxy', 'tcppm', 'socks' or another service commands must follow valid configuration. Invalid sequence of ACLs. First matching ACL is used (except of internal redirections, see below). If ACL contains at least one records last record is assumed to be 'deny *'.

**Comment by Str1ker17** [comment]
Such a opaque requirement. I spent 3 hours trying to make `parent` work with `auth none`... A warning in log is a must, IMHO.

Btw thanks for you work! With `auth iponly` it works as expected.
