### ISSUE TITLE
fakeresolve should work better by only fakeresolve parented requests.

### ISSUE THREAD

**Issue by Twilight** [z3APA3A/3proxy#4]
consider this situation:

    auth iponly
    allow * * google.com,*.google.com
    parent 1000 socks5+ 192.168.0.1 8000
    allow *
    proxy -p8080 -a
    flush

In my network, some hosts won't resolve, like google.com, but fakeresolve won't work for me since I need to connect to hosts other than google.com directly, I found an ugly fix: comment out the targetip test in handleredirect(auth.c), it works but it still tries to resolve them in the first place and it's painfully slow.

the ugly fix works for 0.7.1.2 and I see that in the current git version, that should be SAISNULL, I didn't test it though.

I here by propose that fakeresolve should only apply to host capable parented requests, so eliminate the unnecessary resolve and still able to handle un-parented requests.

**Comment by z3APA3A** [comment]
Valid solution here is to use nsrecord instead of the fakeresolve. nsrecord allows to add resolution for individual records like
nsrecord google.com 127.0.0.2

**Comment by Twilight** [comment]
but nsrecord doesn't support wildcard, like:

    23.client-channel.google.com
    clients4.google.com
    clients6.google.com

I don't think I can cover them one by one

**Comment by z3APA3A** [comment]
This logic of name resolution schema like this is too complicated to implement it inside proxy server, valid solution here is to install dns resolver in parallel with 3proxy and configure local zones for domains like google.com/googlevideo.com with wildcards with main resolver as a smart host.

**Comment by Twilight** [comment]
Thanks, actually I've been using this method for a while.
