### ISSUE TITLE
Help with configure 3proxy as a transparent proxy

### ISSUE THREAD

**Issue by Ryo-Zi** [z3APA3A/3proxy#401]
Please help configure 3proxy as a transparent proxy.
It is necessary that all local traffic go to a remote HTTPS/SOCKS5 proxy with authorization.
Now I'm trying to configure with these settings:

```
nserver 213.133.xx.xx
nserver 213.133.xx.xx
nscache 65536
log 
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
rotate 30
auth none
internal localhost
external 95.216.xx.xx
allow *
parent 1000 socks5 94.158.xx.xx 1051 user password
proxy -p3128 -n
```
But when I try to check my external IP through sites (ipleak.com, ip8.com), I see a real IP address that is not hidden using a proxy. Please help me with the settings.

**Comment by z3APA3A** [comment]
1. you need -a option to proxy to make it anonymous,
2. "auth none" is used to disable all ACL-based rules, including redirections. Please read FAQ/HowTo before asking the question, because it's the first answer to the first question in FAQ.
