### ISSUE TITLE
Как мониторить 3proxy

### ISSUE THREAD

**Issue by yuyaryshev** [z3APA3A/3proxy#402]
Как лучше мониторить 3proxy? В смысле как можно проверить что он - работает?
Только по PID? или есть какой-то порт, который можно прочитать.

Я хочу настроить monit (https://mmonit.com/monit/documentation/) на мониторинг и перезапуск 3proxy.

И я бы хотел проверить что 3proxy не завис - например, отправлять регулярно какой-то http запрос 3proxy, и, если нет ответа - перезапускать 3proxy.

На текущий момент я мониторю так:
 check process 3proxy with pidfile /var/run/3proxy/3proxy.pid
   group www
   group 3proxy
   start program = "/etc/init.d/3proxy start"
   stop program = "/etc/init.d/3proxy stop"
   if 5 restarts with 5 cycles then timeout
   хотелосб бы добавить: if failed port 12345 protocol http request "/" then restart

**Comment by MonkAlex** [comment]
А есть проблемы? Я год назад настроил и не трогал с тех пор, работает.

**Comment by z3APA3A** [comment]
что ты хочешь, чтобы прокси делал по твоему запросу и какую проблему/ситуацию ты хочешь этим решить?

**Comment by z3APA3A** [comment]
Ну в общем можешь, например, запустить admin и его дергать, но не понятно зачем и какую информацию тебе это даст.

**Comment by yuyaryshev** [comment]
"что ты хочешь, чтобы прокси делал по твоему запросу" - 90% что у меня запрос на доработку документации, а не на доработку программы. 

Я бы хотел какой http/https запрос отправить на прокси чтобы проверить что он работает.
Ну например как можно через него загрузить сайт myip.com. Что именно нужно направить и на какой адрес/какой порт? Я (как навертное и многие пользователи) просто не знаю как именно работает прокси - что там за протокол, какие заголовки куда слать.
