### ISSUE TITLE
3proxy can't handle domain names when the upstream proxy is on an upper network.

### ISSUE THREAD

**Issue by phantomcraft** [z3APA3A/3proxy#403]
First I put an socks5 proxy (SSH) listening at 0.0.0.0:1080.

A network namespace is added with a veth pair with addresses:
```

ip netns add nsx
ip link add vethx type veth peer name peerx netns nsx
ip link set vethx up
ip address add 10.0.0.1/24 dev vethx

ip netns exec nsx ip link set peerx up
ip netns exec nsx ip address add 10.0.0.2/24 dev peerx
ip netns exec nsx ip route add default via 10.0.0.1 dev peerx
ip netns exec nsx ip link set lo up
```

Inside the network namespace I put 3proxy running with a connect proxy pointing to the upstream socks5 proxy:

```
ip netns exec nsx 3proxy << EOT
log
allow *
parent 1000 socks5+ 10.0.0.1 1080
proxy -i127.0.0.1 -p3128
EOT
```

I use proxychains-ng to access any address through the proxy:

`ip netns exec nsx proxychains4 -q w3m 1.1.1.1`

It works fine when the address is an IP but when it's an domain an error occurs:

```
ip netns exec nsx proxychains4 -q w3m google.com
w3m: Can't load google.com.
```

Across networks 3proxy can't handle domain names going to an upstream proxy.

When I test the same scheme above using local loopback address (127.0.0.1) everything runs fine.

**Comment by z3APA3A** [comment]
https://3proxy.ru/doc/faqe.html

Q: Is it possible to resolve names through parent proxy?
A: Yes, use 'proxy', 'connect+', 'socks4+' or 'socks5+' as parent proxy type. 3proxy itself requires name resolutions for ACL checks, so, if it's impossible to resolve names from 3proxy host, use

fakeresolve

command. Fakeresolve resolves any name to 127.0.0.2.

**Comment by wgf4242** [comment]
I use this config, 3proxy not work.
```
auth iponly
allow *
parent 1000 http proxy2.aa.xyz 8080
proxy -a -p1235
```

**Comment by z3APA3A** [comment]
Use "fakeresolve" command if you do not need resolving on proxy side.
