### ISSUE TITLE
Allow ACL - Include all users in users config file

### ISSUE THREAD

**Issue by john-d13** [z3APA3A/3proxy#404]
I have a list of 100 username and passwords defined in the users (passwd) include file. I'd like to define them all with a variable name instead of specifying one by one comma delimited in the allow argument in the base 3proxy.cfg file.  Is it possible? 

ie. 

users $/etc/3proxy/conf/passwd
allow (users) 

(users) = All users in the /etc/3proxy/conf/passwd file

Other question,  can 3proxy dynamically load configuration changes in the Inclide file instead if having to reload the server? 

Finally, 

I read release notes and you noted support for PAMAuth in version 0.8. I cannot find any reference in the help command lines. I see radius was added. Any roadmap for Linux PAM Auth? 

Thank you!

**Comment by z3APA3A** [comment]
You should create the second file with user list. For standard authentication configuration must be reloaded, because accounts are configured in config file. There is an (unsupported, but probably working) PamAuth plugin, you can enable it in Makefile. Usage examples are in src/plugins/PamAuth/PAMAUTH.TXT

**Comment by john-d13** [comment]
Thank you.  Is there a way to allow all users in the userlist file with one "allow" command instead of having to define each username individually?

**Comment by z3APA3A** [comment]
allow $/path/to/userlist

userlist must be comma-separated (without spaces)

**Comment by john-d13** [comment]
Tried and doesent seem to work.  In 

auth strong
allow $/etc/3proxy/conf/passwd


# pwd
/etc/3proxy

# cat conf/passwd
gdinardo:CL:pass123


Browser keeps attempting auth without success.  if I add "allow gdinardo" in the 3proxy.cfg it works ok.

# tail -2 /var/log/3proxy.log.2019.11.27
1574865962.321 PROXY.51313 00003 gdinardo 72.142.92.204:63345 0.0.0.0:0 0 0 0 CONNECT_img-getpocket.cdn.mozilla.net:443_HTTP/1.1
1574865962.388 PROXY.51313 00003 gdinardo 72.142.92.204:63346 0.0.0.0:0 0 0 0 CONNECT_img-getpocket.cdn.mozilla.net:443_HTTP/1.1

 
Running version - 3proxy-0.9-devel

**Comment by z3APA3A** [comment]
> userlist must be comma-separated (without spaces)

**Comment by john-d13** [comment]
Perfect!!   works now.   BTW,  kudos on the design of 3proxy,  I love the fact I can run both http and socks proxies on the same listening port :)
