### ISSUE TITLE
Пропадает соединение через http proxy, socks всегда работает идеально!

### ISSUE THREAD

**Issue by zhanadamian** [z3APA3A/3proxy#405]
Опишу:
- 3proxy установлено на разных ОС: ubuntu, win7, win10. 
- интерфейсы: на входе - ethernet, выход - карта rndis (3g modem в hilink). 
- ip на интерфейсах прописаны статично.  
- в конфигах все привязано к ip.

У меня есть необходимость перезагружать 3g модем и тогда rndis исчезает на секунд 30 из интерфейсов, а также периодически делать реконнект модема с пропаданием инета на 30сек - минуту (в этом случае rndis и его внутр ip шлюза не меняются и остаются доступны)
В случае с http - прокси после описанных манипуляций остается висеть в процессах/как запущенный сервис, но реально не работает...
В течении минуты-две в примерно 80% случаев все опять начинает работать.
В остальных 20% лечится перезагрузкой http прокси. 
Возможно это таймауты или еще что, подскажите, куда копать!
При необходимости дам логи.
И в любом случае - огромное Спасибо за Супер программу!

запускается socks и http отдельными конфигами и сервисами вот такими строками
proxy -n -a -p33333 -ix.x.x.x -ex.x.x.x
socks -n -a -p33343 -ix.x.x.x -ex.x.x.x
--------конфиг-------
monitor /..../3proxyXX.cfg
daemon
timeouts 1 5 30 60 180 1800 15 60
nserver Y.Y.Y.Y
nscache 65536
users aaaa:CL:bbbbb
authcache ip 3600
auth cache strong
allow aaaa
maxconn 125
#socks -n -a -p3333 -ix.x.x.x -eY.Y.Y.Y
proxy -n -a -p3334 -ix.x.x.x -eY.Y.Y.Y
flush
end

**Comment by z3APA3A** [comment]
Прием и обработка входящих соединений делается всегда одним и тем же кодом до того, как запускается обработчик socks или proxy, соответственно никакой разницы в приеме входящих соединение нет. Если есть наблюдаемая разница, то она в чем-то другом, например в поведении клиентов. Что значит "висит", какие симптомы? Сколько при этом наблюдается открытых сокетов? Нет ли ботлнеков в ресурсах?  https://3proxy.ru/highload.asp читал? (в момент перезапуска может быть вдвое больше запущеных сервисов)

**Comment by zhanadamian** [comment]
Спасибо за заданное направление!
Буду копать!
