### ISSUE TITLE
IPv6

### ISSUE THREAD

**Issue by russoisraeli** [z3APA3A/3proxy#407]
Is IPv6 supported for "allow" statements? If so, what is the proper format?

Thank you

**Comment by z3APA3A** [comment]
Comma delimited list can contains: Single IPv6 addresses, e.g ::1 ranges e.g. ::1-::2 or CIDRs, e.g. ::2/127

**Comment by z3APA3A** [comment]
TransparentPlugin is, of cause, required in this configuration.
