### ISSUE TITLE
rpmlint warning missing-call-to-chdir-with-chroot

### ISSUE THREAD

**Issue by jayvdb** [z3APA3A/3proxy#409]
rpmlint complains

> 3proxy.x86_64: W: missing-call-to-chdir-with-chroot /usr/bin/3proxy
> This executable appears to call chroot without using chdir to change the current directory. This is likely an error and permits an attacker to break out of the chroot by using fchdir. While that's not always a security issue, this has to be checked.

I didnt see an issue about it.  Has this been checked?

**Comment by z3APA3A** [comment]
It's a kind of BCP to avoid some jail escaping techniques, current devel should do it.
