### ISSUE TITLE
[Request] RADIUS

### ISSUE THREAD

**Issue by MolecularMan** [z3APA3A/3proxy#41]
Хотелось бы, чтобы 3proxy поддерживал аутентификацию через RADIUS-сервер, а так же принимал от него параметры Framed-IP-Address и Framed-IPv6-Address в качестве extip для пользователя. И если говорить о полноценной интеграции, то так же отправлял информацию о количестве трафика пользователя радиусу.

**Comment by Strykar** [comment]
This'd be great, it might also fix https://github.com/z3APA3A/3proxy/issues/5 as RADIUS can limit parallel connections via secondary/tertiary authentication attempts.

**Comment by z3APA3A** [comment]
RADIUS support added to devel version. Authentication only currently. 
Example usage:
```
radius SECRET 192.168.0.1 192.168.0.2
authcache ip,user,password
auth cache radius
```
Attributes within requested:
User-Name, Password: (username and password if presented by client)
Service Type: Authenticate-Only
NAS-Port-Type: NAS-Port-Virtual
NAS-Port-ID: (proxy service port)
NAS-IPv6-Address / NAS-IP-Address: (proxy interface accessed by client)
NAS-Identifier: (text identifing proxy, e.g. PROXY or SOCKSv5)
Framed-IPv6-Address / Framed-IP-Address: (IP address of the client)
Called-Station-ID: (requested Hostname, if presents)
Login-Service: type of request, e.g. 1 - SOCKS CONNECT, 10 - HTTP GET, 13 - HTTP CONNECT
Login-TCP-Port: requested port
Login-IPv6-Host / Login-IP-Host: requested IP

**Comment by MolecularMan** [comment]
Спасибо, постараюсь протестировать в ближайшее время.
Сразу пара вопросов:
1. Обязательно ли использовать кеширование, или можно обойтись без него?
2. Сколько времени актуален кеш авторизации через радиус? можно ли поменять данный параметр?

**Comment by z3APA3A** [comment]
Framed-IP-Address / Framed-IPv6-Address in servers's reply (only one address may present and is used as 'external' IP) - added, but not tested.

**Comment by z3APA3A** [comment]
Кэширование не обязательно, но без него запросов будет очень много. Время кэширования задается вторым параметром в authcache.
authcache <cachtype> <cachtime>

**Comment by z3APA3A** [comment]
Reply-Message with decimal code may be used with REJECT to provide error code:
http://3proxy.ru/howtoe.asp#ERRORS
E.g. you can use "1" as a reply message to block access without asking for username / password.

**Comment by nutinshell** [comment]
Any plan to add accounting support for radius? That would be cool.

**Comment by z3APA3A** [comment]
Yes, it will be.

**Comment by laur2016** [comment]
Hello guys,

Any news on this implementation?
Thank you in advance,

**Comment by z3APA3A** [comment]
Current state is authentication is implemented in devel branch, accounting is under development.

**Comment by z3APA3A** [comment]
I've added preliminary accounting, can be enabled with

log radius

for a while it can slow down the proxy (depending on RADIUS  server reply speed).
Configuration will probably change, I will add separate logging RADIUS configuration, but functionality and format of packets can already be tested.

**Comment by mohammad-rj** [comment]
Hi, I'm using 3proxy
And I connected it to freeradius
User passwords are read from freeradius and work correctly (authentication)
But online people are not listed in freeradius
As well as freeradius attributes
For example, Simultaneous-Use does not work to specify the number of people who can be connected at the same time with a username and password. (authorization)

I'm using devel version (9) . on sentos 7

My goal is to create a restriction on the connection of a username. (authorization)
Given that I already use freeradius for authentication
How do I do this now?

**Comment by DesSolo** [comment]
Как корректно организовать ACL средствами ответа в FreeRadius?
На данный момент конфиг:
`nserver 8.8.8.8
nserver 8.8.4.4

nscache 65536
timeouts 1 5 30 60 180 1800 15 60

radius testing123 127.0.0.1
authcache ip,user,password 86400

daemon
log /var/log/3proxy/3proxy.log D
logformat "- %y/%m/%d|%H:%M.%S %N.%p %E %U %C:%c %R:%r %O %I %h %T"

archiver gz /bin/gzip %F
rotate 30

auth cache radius
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
proxy -a

flush
auth cache radius
maxconn 1000
socks -p443
`
SQL:
`radius=# SELECT * FROM radgroupreply;
 id | groupname |   attribute   | op |      value      
----+-----------+---------------+----+-----------------
  1 | disable   | Auth-Type     | := | Access-Reject
  2 | vk        | Reply-Message | := | deny * * vk.com
(2 rows)

radius=# SELECT * FROM radusergroup WHERE groupname='vk';
 id | username | groupname | priority 
----+----------+-----------+----------
 45 | tetete3  | vk        |        1
(1 row)

`

3proxy log:
` 19/02/19|06:48.34 SOCK5.443 00000 tetete3 USER_IP:55380 SERVER_IP:443 0 0 0 CONNECT vk.com:443`

**Comment by z3APA3A** [comment]
@DesSolo выше есть список аттрибутов, которые 3proxy отправляет в запросе к RADIUS и которые может обрабатывать в ответе от RADIUS, на основе этих аттрибутов на стороне RADIUS должно приниматься решение пускать/непускать пользователя.

**Comment by devilus** [comment]
На данный момент авторизацию с помощью radius можно использовать в текущей версии 0.8.12?

**Comment by clintnetwork** [comment]
Hi, what is RADIUS ?

**Comment by z3APA3A** [comment]
@clintnetwork 
https://en.wikipedia.org/wiki/RADIUS

**Comment by Griffin-3** [comment]
I am trying to use RADIUS authentication in 3proxy (am using it), and I am trying to return a value from RADIUS to be used as the port for the following "parent" line in the config.  For example, if the config file was:

```
radius SECRET 192.168.0.1 192.168.0.2
# ... setup for several hundred ports, like:
auth radius
parent 1000 socks5 127.0.0.1 $returned_port
socks -p7000
proxy -a -p6000
flush
```
and the parent port would be a value returned by RADIUS, based on which user was authenticated.  So I look at authradius.c:622, which I _think_ is where it pushes the returned Framed_IP_Address value into the external ip address:
```
if (!vendor && attr[0] == PW_FRAMED_IP_ADDRESS && attr[1] == 6) {
	*SAFAMILY(&param->sinsl) = AF_INET;
	memcpy(SAADDR(&param->sinsl), attr+2, 4);
}
```
[from issue #274, June 18, 2018:
the external address must arrive from the RADIUS server in Framed-IPv6-Address]

but I cannot see how to put a port value into the first link in the chain structure of the parent proxy.

Can you offer any advice?  Am I even looking in the right place?

**Comment by z3APA3A** [comment]
@Griffin-3
it's not that simple. The best and most compatible way is to create 2 instances of structures

```
struct chain {
	struct chain * next;
	int type;
#ifndef NOIPV6
	struct sockaddr_in6 addr;
#else
	struct sockaddr_in addr;
#endif
	unsigned short weight;
	unsigned char * exthost;
	unsigned char * extuser;
	unsigned char * extpass;
};
```

with 'parent' data where type is one of
```
typedef enum {
	R_TCP,
	R_CONNECT,
	R_SOCKS4,
	R_SOCKS5,
	R_HTTP,
	R_POP3,
	R_SMTP,
	R_FTP,
	R_CONNECTP,
	R_SOCKS4P,
	R_SOCKS5P,
	R_SOCKS4B,
	R_SOCKS5B,
	R_ADMIN,
	R_EXTIP
} REDIRTYPE;

```
and either addr contains external address/port, or it only contains port and exthost contains symbolic name (pre-init structure with memset to 0). Than use this structure to init matching 'allow' rule:

struct ace {
	struct ace *next;
	int action;
	int operation;
	int wdays;
	int weight;
	int nolog;
	struct period *periods;
	struct userlist *users;
	struct iplist *src, *dst;
	struct hostname *dstnames;
	struct portlist *ports;
	struct chain *chains;
};

with action=REDIRECT (2) and chains=chain (also pre-init structure with memset to 0).

and call 
`
int handleredirect(struct clientparam * param, struct ace * acentry);`

**Comment by z3APA3A** [comment]
Consider RADIUS as implemented experimental feature

**Comment by clintnetwork** [comment]
I'm not familiar with RADIUS, could you write a little documentation to the good attributes to use to configure proxy in RADIUS, I would like to have a port by user/pass.

**Comment by z3APA3A** [comment]
@clintnetwork 3proxy sends NAS-Port-ID, User-Name, Password attributes to RADIUS, RADIUS server must authenticate (by username and password) and authorize user (to allow or deny access to given port). That's all. Details depend on RADIUS server.

**Comment by tyurin-ilya** [comment]
Хочу поднять radius server на nodejs.
Само сообщение от 3proxy я успешно получаю, но дешифровать его не получается. Библиотека radius дает ошибку при попытке декодирования на любых версиях ноды. Больше никаких библиотек я нагуглить не смог. Если кто-то поднимал radius server на nodejs, расскажите, пожалуйста, как декодировать сообщение?

**Comment by z3APA3A** [comment]
Попробуй на текущем мастере, там есть 266e62644c2afb5f068a670f8a9aead7db0d7793

**Comment by tyurin-ilya** [comment]
Попробовал на текущем мастере, ошибка такая же, только чуть другой пакет прилетает. Если в консоль вывести msg.toString(), то на прошлых версиях было такое:
9�*����E�a~�,657105507.862.1819428416='�h�� SOCK�O��app.octobrowser.net��h
                                                                          test�E��O-��nG="N�

А на текущем мастере:
testh}��|�BD�wfA��:�06107.806.3130627712='�h�� SOCK�O��app.octobrowser.net��h

Логин и пароль были test, запрос на проверку прокси отправлял из окто браузера.

**Comment by tyurin-ilya** [comment]
> Попробуй на текущем мастере, там есть [266e626](https://github.com/3proxy/3proxy/commit/266e62644c2afb5f068a670f8a9aead7db0d7793)

Спасибо. На текущем мастере я наконец-то смог настроить прием пакетов.

Авторизация работает корректно, но столкнулся с новой проблемой: не могу динамически задать исходящий IPv6 адрес. Отправляю ipv6 в атрибуте `Framed-IPv6-Address`, но вне зависимости от того, какой ip возвращает радиус сервер, внешний ipv6 всегда один и тот же.
Все тесты проводил на ubuntu 22.04

Пример ответа от радиус сервера
```
RadiusPacket {
  code: Access-Accept
  identifier: 62
  attributes: {
    Framed-IPv6-Address: 2a01:7e01:e002:8400:2a01:7e01:e002:8400
  }
}
```

Пример конфига, в котором внешний ip не задан и при любом ответе радиус сервера (я тестировал разные ip), внешний ip на моем сервере всегда будет тот, который я ранее вешал на сетевой интерфейс через команду _ip addr add_.
```
radius secret 1.1.1.1
auth radius
socks -n -a -6 -p10000
```

Пример конфига, в котором задан внешний ipv6 и именно с этим ip работает прокси. Такой конфиг работает корректно даже если не добавлять ip в интерфейс через команду _ip addr add_
```
radius secret 1.1.1.1
auth radius
socks -n -a -6 -p10000 -e2a01:7e01:e002:8400:2a01:7e01:e002:8400
```

Подскажите, пожалуйста, в чем может быть проблема?

**Comment by tyurin-ilya** [comment]
При получении внешнего ip через атрибут Framed-IPv6-Address перестает работать ipv4 адрес с настройкой -64.

Не работает при таком конфиге:
`socks -64 -p10000`
И при таком тоже:
`socks -64 -p10000 -e1.1.1.1`

Можно ли сделать так, чтобы ipv4 работал одновременно с ipv6 при авторизации через радиус сервер?
Например принимать оба заголовка `Framed-IPv6-Address` и `Framed-IP-Address`
Или ipv4 адрес брать из параметра -e
