### ISSUE TITLE
Ограничения на ip

### ISSUE THREAD

**Issue by jokero99** [z3APA3A/3proxy#411]
Добрый день
Имеется конфиг:
service
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
log C:\proxy.log D
rotate 10
users proxy1:CL:proxy1 proxy2:CL:proxy2
auth strong
flush
allow proxy1
proxy -n -a -p8000 -i192.168.1.5 -e192.168.2.2
flush
allow proxy2
maxconn 100
proxy -n -a -p8001 -i192.168.1.5 -e192.168.3.3
flush

Пользователь подключается с ip 192.168.1.10 к прокси "proxy1" и имеет доступ ко всем сайтам.
1) Как запретить пользователю "proxy1" доступ к ip 192.168.2.1, то есть, если пользователь подключенный к "proxy1" не имел возможности открыть содержимое только этого адреса, но все остальное разрешить.
2) как запретить запретить вообще всем пользователям доступ к определенным ip
Пример, запретить доступ к: 192.168.2.1, 192.168.3.1, 192.168.*.1 

Пробовал так (не работает): 
users proxy1:CL:proxy1 proxy2:CL:proxy2
deny * * 192.168.2.1 *
auth strong

Пробовал так (не работает): 
users proxy1:CL:proxy1 proxy2:CL:proxy2
nsrecord www.anekdot.ru 87.250.251.11
auth strong

То есть, даже сайт anekdot не могу запретить...
Как правильно прописать запрет в данном конфиге. подскажите пожалуйста.
Версия: 3proxy 0.8.13 Вышел 01 августа 2019.

**Comment by z3APA3A** [comment]
> Пробовал так (не работает):

а как полностью выглядил конфиг и что в логах?

**Comment by jokero99** [comment]
> > Пробовал так (не работает):
> 
> а как полностью выглядил конфиг и что в логах?

Конфиг так и выглядит полностью.
Пользователь удаленно подключается через внешний ип, маршрутизатор переадресовывает по порту 8000 на модем 192.168.2.2 - а дальше уже работает доступ к любому сайту.
но у модема есть своя вебморда по адресу 192.168.2.1, и если пользователь введет этот адрес, подключившись к ип, то он попадает на вебморду. 
вопрос, как ограничить доступ для всех пользователей кто подключен через маршрутизатор к ип 192.168.2.1, 192.168.3.1 ... 192.168.255.1

**Comment by z3APA3A** [comment]
Вопрос был как выглядит конфиг 3proxy, как он должен работать по замыслу и что в логах.
Ну ОК, будем гадать:

nsrecord не работает, потому что не задан nscache / nserver

deny * * 192.168.2.1 *
если добавить только его блокирует весь трафик, т.к. нет разрешающего правила, см FAQ.

**Comment by jokero99** [comment]
> Вопрос был как выглядит конфиг 3proxy, как он должен работать по замыслу и что в логах.
> Ну ОК, будем гадать:
> 
> nsrecord не работает, потому что не задан nscache / nserver
> 
> deny * * 192.168.2.1 *
> если добавить только его блокирует весь трафик, т.к. нет разрешающего правила, см FAQ.

Зачем гадать? :) он так и выглядит, я ведь описал его, это полное содержимое 3proxy.cfg:
service
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
log C:\proxy.log D
rotate 10
users proxy1:CL:proxy1 proxy2:CL:proxy2
auth strong
flush
allow proxy1
proxy -n -a -p8000 -i192.168.1.5 -e192.168.2.2
flush
allow proxy2
maxconn 100
proxy -n -a -p8001 -i192.168.1.5 -e192.168.3.3
flush

В этом и вопрос, как разрешить доступ ко всем сайтам, но запретить доступ к 192.168.2.1
то есть если вы подключаетесь удаленно (по внешнему ip) к прокси, то как ограничить доступ к 192.168.2.1

**Comment by jokero99** [comment]
Или вы может посоветуете как сделать грамотней, то есть у меня по идее там список юзеров большой  "users proxy1:CL:proxy1 proxy2:CL:proxy2" и каждый раз у меня повторяется с заменой порта и -е 
allow proxy2
maxconn 100
proxy -n -a -p80** -i192.168.1.5 -e192.168.*.1
flush

**Comment by z3APA3A** [comment]
запретить одному юзеру доступ к одному сайту и разрешить все остальное

deny user * 192.168.0.1
allow *

запретить всем пользователям доступ к одному сайту и разрешить все остальное:

deny * * 192.168.0.1
allow *

**Comment by z3APA3A** [comment]
https://3proxy.ru/highload.asp в Extending ephemeral port range есть варианты выбора внешнего IP

**Comment by jokero99** [comment]
Вставил
> deny * * 192.168.0.1
> allow *
Все равно удаленно открывает  192.168.0.1

**Comment by jokero99** [comment]
Может я расскажу цель, а вы уже поймете причину.
Суть такова. 
у меня имеется мобильный модем 4г
Мне нужно дать вам доступ к модему
доступ даю через внешний ip провайдера:порт

Мне необходимо что бы вы имели полный доступ в интернет, но скрыть от вас вебморду модема, что бы вы не имели к нему доступ.
ведь морда находится по адресу 192.168.2.1

**Comment by z3APA3A** [comment]
flush сбрасывает ACL
