### ISSUE TITLE
Автозамена прокси

### ISSUE THREAD

**Issue by sergey837** [z3APA3A/3proxy#412]
Привет ребят.
Нужно что бы с каждым соединением менялся IP
Использовал функцию parent
Но при добавлении несколько прокси, почему то переключение идет на 2 прокси, хотя добавил 10, и то меняет не всегда. Был бы признателен если поможете. 

auth iponly
allow *
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
parent 100 http IP PORT 
proxy -T -p3311

**Comment by z3APA3A** [comment]
Потому что так работает вес в parent, если ты хочешь чтобы хоп всегда был ровно один, то суммарный вес всех парентов в правиле должен равняться 1000, см. 
https://3proxy.ru/howtor.asp#CHAIN

если просто надо выбирать внешний адрес, то лучше использовать parent extip а не http

**Comment by sergey837** [comment]
> Потому что так работает вес в parent, если ты хочешь чтобы хоп всегда был ровно один, то суммарный вес всех парентов в правиле должен равняться 1000, см.
> https://3proxy.ru/howtor.asp#CHAIN
> 
> если просто надо выбирать внешний адрес, то лучше использовать parent extip а не http

Я ставил 1000, но IP так же берется только 1, и редко когда переключается на другой.

**Comment by z3APA3A** [comment]
Либо есть еще какие-то проблемы конфигурации, либо ты не учитываешь что в HTTP несколько запросов могут идти в одном соединении. В таком случае IP разумеется останется там же.
