### ISSUE TITLE
2 DNS

### ISSUE THREAD

**Issue by nsimanskij** [z3APA3A/3proxy#413]
Вечер добрый. Имею сервер на котором есть 2 IP адреса. Один IP NL,  другой UK. Можно ли настроить сервер так, чтобы каждый IP использрвал свой конкретный DNS?

**Comment by z3APA3A** [comment]
Проще всего запустить 2 инстанса 3proxy с разными конфигами, потому что кеш DNS и бендлимиты/рейтлимиты это единственное общее что есть у сервисах в рамках одного инстанса.

**Comment by nsimanskij** [comment]
Спасибо! Кое как запустил 2 конфига. Пока всё работает без проблем
