### ISSUE TITLE
3proxy and libgen library genesis

### ISSUE THREAD

**Issue by Janaue** [z3APA3A/3proxy#415]
I have firefox  nightly 73.0a1 (2019-12-19) (64-bit) on w10 and I run 3proxy tiny proxy server 3proxy-0.9-devel (190821152138) 

When i go to http://gen.lib.rus.ec/ when firefox is NOT configured to use 3proxy, I get the config page of 3proxy, **I want to access http://gen.lib.rus.ec/ even when firefox does not use 3proxy.**
<img width="562" alt="sshot-575" src="https://user-images.githubusercontent.com/10972636/71161969-a20e6c80-224a-11ea-874a-5a778f4d8a55.png">

the 3proxy.cfg is a copy of  3proxy.cfg.sample, ALL SETTINGS ARE STOCK but this

```
#  sharing access to internet

external 192.168.1.14
# external is address 3proxy uses for outgoing connections. 0.0.0.0 means any
# interface. Using 0.0.0.0 is not good because it allows to connect to 127.0.0.1

internal 127.0.0.1
# internal is address of interface proxy will listen for incoming requests
# 127.0.0.1 means only localhost will be able to use this proxy. This is
# address you should specify for clients as proxy IP.
# You MAY use 0.0.0.0 but you shouldn't, because it's a chance for you to
# have open proxy in your network in this case.
```

**Comment by z3APA3A** [comment]
Probably, it means gen.lib.rus.ec resolves to 127.0.0.1. Check resolver / /etc/hosts settings.
