### ISSUE TITLE
Переустановка 3proxy

### ISSUE THREAD

**Issue by mileskanda** [z3APA3A/3proxy#416]
3proxy начал создавать на сервере очень много процессов, перегружая память, что, собственно поспособствовало диким лагам всего.
Пытался удалить 3proxy стандартным методам, но цель uninstall отсутсвует.
в Howto отсутствует пункт по удалению 3proxy с систем Ubuntu, я использую версию 18.04.3 LTS на VPS Scaleway.
Я правильно понимаю, что основной каталог пакета  находится в:
/usr/local/3proxy
/etc/3proxy?
Хотелось бы переустановить. Ранее такого поведения не замечал.

**Comment by z3APA3A** [comment]
3proxy не входит в пакеты Ubuntu, и переустанавливать его надо тем же способом, которым производилесь установка, например сборкой из сорсов. Однако, судя по описанию проблемы, проблема не в 3proxy, а в  его конфигурации, например прокси открыт без аутентификации или с предсказуемым паролем наружу.
