### ISSUE TITLE
[Request] build for iOS

### ISSUE THREAD

**Issue by ienthach** [z3APA3A/3proxy#418]
3proxy supports  almost platform but i can not find how to build 3proxy for iOS. Could you make a guide for iOS.

**Comment by lostinwoods** [comment]
You can build it on macos, the proces is quite simple
https://github.com/z3APA3A/3proxy/wiki/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D1%8F%D1%86%D0%B8%D1%8F-%D0%B8-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-3proxy-%D0%BD%D0%B0-MacOS
