### ISSUE TITLE
[Request] Поддержка нескольких ядер

### ISSUE THREAD

**Issue by ariutk** [z3APA3A/3proxy#42]
Сейчас 3proxy работает на одном ядре, хочу распределить его по всем ядрам. Чтобы он использовал все доступные ресурсы сервера. Реализован ли, такой функционал?

При большой нагрузке запросы выполняются очень медленно, а нагрузка CPU едва ли выше пары процентов.

**Comment by z3APA3A** [comment]
3proxy использует отдельный поток на каждый клиентский запрос и потому масштабируется на любое количество ядер. Причину медленных запросов ищи в другом, например в Ulimit'ах или недостаточном maxconn.
