### ISSUE TITLE
3proxy in a virtual routing table, on a tunnel interface

### ISSUE THREAD

**Issue by russoisraeli** [z3APA3A/3proxy#420]
Hello,

The setup is a tiny bit complex, so if necessary, I can translate to Russian.

Running on FreeBSD 11.3-REL. FreeBSD supports virtual routing tables, called "fibs". In a separate "fib" I am running an OpenVPN client (using tun interface).
I would like 3Proxy to connect via the tunnel.

3proxy is started with "setfib", and it indeed uses the correct routing table (for incoming connections to "internal").
However, it refuses to connect via the tunnel interface. I used the current tunnel IP for "external", as well as 0.0.0.0.
Nothing appears in tcpdump for tun0.
HTTP proxy returns "Bad gateway, host not found or connection failed". SOCKS returns a connection error.

This is the routing table:

[root@jonathan (0 jobs) ~ ]# netstat -rn -F2 -f inet
Routing tables (fib: 2)

Internet:
Destination        Gateway            Flags     Netif Expire
default            10.8.8.1           UGS        tun0
10.8.8.1           link#7             UH         tun0
10.8.8.5           link#7             UHS         lo0
127.0.0.1          lo0                UHS         lo0

"external" is either 10.8.8.5 or 0.0.0.0 with same effect.

Any ideas?

**Comment by z3APA3A** [comment]
I don't think this question is 3proxy specific. Try to run 'nc' or telnet to some external server in the same environment. If it can not connect to destination server, the problem is in environment configuration. Also, you should check a log for error number, it can give you some thoughts. E.g. 00100 means there is a poblem with name resolution configuration rather than routing issue.

**Comment by russoisraeli** [comment]
Could you please point me to where the error #'s are documented? Or is it in source/header files?

Also, is there a way to really increase logging verbosity and/or debug mode for 3proxy?

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#ERRORS

check 'logformat' specification for setting logging information.

**Comment by ktrace** [comment]
russoisraeli was right, for FreeBSD needed setfib option so like in nginx:

> Синтаксис: 
>  listen      адрес[:порт]     [default_server]     [ssl]     [http2 | spdy]     [proxy_protocol]     **[setfib=число]**     [fastopen=число]     [backlog=число]     [rcvbuf=размер]     [sndbuf=размер]     [accept_filter=фильтр]     [deferred]     [bind]     [ipv6only=on|off]     [reuseport]     [so_keepalive=on|off|[keepidle]:[keepintvl]:[keepcnt]];
 
For example:
```
server {
        listen 80 setfib=1;
        server_name content.example.com
   ....
   }

server {
        listen 1.2.3.4:8080 setfib=2;
        server_name video1a.example.com
   ....
   }
```
For 3proxy it may look like:
```
daemon
...
external 12.23.34.45 setfib 2
internal 172.16.2.1
proxy -n -a

```
I just faced a similar restriction.

**Comment by fenix957** [comment]
Тоже самое 
Это возможно реализовать или же самому как то городить костыли?
