### ISSUE TITLE
bind():_Permission_denied

### ISSUE THREAD

**Issue by opiums9** [z3APA3A/3proxy#421]
Всем привет, захотел пустить socks прокси по 443 порту, но всё время в логах получаю ошибку:
`1577440085.943 SOCKS.443 00000 - 192.168.1.16:443 0.0.0.0:0 0 0 0 bind():_Permission_denied`
Подскажите, как выдать права на использование этого порта, ведь на нём ничего другого не висит.

**Comment by phantomcraft** [comment]
Ports with number lower than 1024 requires root privileges to bind.

**Comment by z3APA3A** [comment]
Выше правильный ответ - для доступа к портам ниже 1024 требуется root.
