### ISSUE TITLE
 countin and dyinamic users

### ISSUE THREAD

**Issue by mazgalici** [z3APA3A/3proxy#422]
countin <number> <type> <limit> 

"number is sequential number of record in this file. If number is 0
	no traffic information  on this counter is saved in file (that is
	if proxy restarted all information is loosed) overwise it should be
	unique sequential number."

My problem is that users can be added and deleted in the same day. So if we delete 2 users and add 2 new ones, the 2 new users will inhert the sequential number of the previous 2 users so they will also have the same bandwidth records for that day?

**Comment by z3APA3A** [comment]
In general, you should not re-use the same number for the different counter. If you really need it, set a short-living counter prior to reuse it, e.g.

countin 1234 C 0 none 0.0.0.0

resets counter 1234 to zero within 1 minute.

**Comment by mazgalici** [comment]
thank you for the info

so is OK to use different numbers, even that they aren't sequential?
