### ISSUE TITLE
Multiplie users

### ISSUE THREAD

**Issue by orelsasi** [z3APA3A/3proxy#423]
So i set up few proxies on same rpi
But i want each proxy to have a user name how exectly it can be possible? 
Like should i add in users anthor line of
Users user:Cl:pass user2:Cl:pass
And in auth i do 
Auth strong? Or should i use somethinf else
And than 
Allow user
Lines of proxies i want it to control
Allow user 2 
Lines of the prozies this user want to control

**Comment by z3APA3A** [comment]
I'm not sure what do you need, but probably you want something like this:

```
alllow user1
proxy -p1111

flush

allow user2
proxy -p2222

flush

allow user3
proxy -p3333
```

**Comment by orelsasi** [comment]
Yes i managed to fix it thx !

בתאריך יום א׳, 5 בינו׳ 2020, 13:27, מאת Vladimir Dubrovin ‏<
notifications@github.com>:
