### ISSUE TITLE
Проблемы маршрутизациии

### ISSUE THREAD

**Issue by lostinwoods** [z3APA3A/3proxy#424]
Настроенный прокси на дебиане через две недели работы внезапно перестал работать по сети. Конфигурация сети следуюая: есть роутер с статическим адресом, подключенный к внешней сети, к нему подключен одноплатник на дебиане с лте модемом на борту.  На роутете проброшен порт на одноплатник. В локальной сети прокси работает, при заходе из внешней, пакеты уходят по првильному адресу, но tcpdump показал, что ответные отправляются на сеть модема.  

> Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.8.1     0.0.0.0         UG    100    0        0 enx0c5b8f279a64
0.0.0.0         192.168.10.1    0.0.0.0         UG    101    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eth0
192.168.8.0     0.0.0.0         255.255.255.0   U     100    0        0 enx0c5b8f279a64
192.168.10.0    0.0.0.0         255.255.255.0   U     101    0        0 eth0

>

**Comment by lostinwoods** [comment]
`Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.8.1     0.0.0.0         UG    100    0        0 enx0c5b8f279a64
0.0.0.0         192.168.10.1    0.0.0.0         UG    101    0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eth0
192.168.8.0     0.0.0.0         255.255.255.0   U     100    0        0 enx0c5b8f279a64
192.168.10.0    0.0.0.0         255.255.255.0   U     101    0        0 eth0
`

**Comment by lostinwoods** [comment]
конфиг

**Comment by z3APA3A** [comment]
Прокси не управляет роутингом, прокси может только выбирать IP адрес источника за счет -i/-e и/или интерфейс за счет -Di/-De, роутинг должен настраиваться системными средствами.

**Comment by lostinwoods** [comment]
Я нашел причину проблеммы, хоть и не разобрался с механизмом ее возникновения. В моем дистрибутиве на базе дебиана (одна из сборок армбиан) для управления сетью используется NetworkManager, похоже, что именно он вмешивался в работу проксисервера перехватывая контроль над сетями. После того, как сеть была перенастроена на правила в /etc/network/interfaces, все пришло в норму.
