### ISSUE TITLE
prevent accessing via http:// in a browser 

### ISSUE THREAD

**Issue by mazgalici** [z3APA3A/3proxy#425]
We are running on port 80, can you please tell us what modification should we make so if somebody is entering http://IP directly in a browser to not get the 407 code and to get a connection reset/deny instead?

**Comment by z3APA3A** [comment]
You can either use 
https://3proxy.ru/plugins/StringsPlugin/
to modify/remove the text or use redirection to some external port which closes connection instead of rejecting it. e.g.

tcppm -i127.0.0.1 12345 0.0.0.1 12346

....
allow *
parent 1000 tcp 127.0.0.1 12345
