### ISSUE TITLE
Apply Bandwidth Filters to individual Services

### ISSUE THREAD

**Issue by john-d13** [z3APA3A/3proxy#426]
Hello,  is there a feature where one can apply the bandlimin/bandlimout for each service individually?   The issue is I am using Parent proxy,  redirecting all incoming connections via IPTables to TCPPM Transparent TLS redirector.   As result,  I cannot use Userlist to filter,  I cannot use target or source Port to filter.   

The only logical choice is to configure it into the directive itself but if I do this its applied globally to all parent proxies. 

For example,  would be nice if this was possible:

allow *
parent 1000 connect 45.57.246.148 1234 xxx xxx
maxconn 4000
bandlimin 2000000 * * * * <<<<
bandlimout 2000000 * * * * <<<<
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 11111
flush

allow *
parent 1000 connect 45.57.246.148 4567 xxx xxx
maxconn 4000
nobandlimin  <<<<
nobandlimout <<<<
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 11111
flush

**Comment by z3APA3A** [comment]
Bandlimiters are common for all services, so you have to either exclude traffic for 45.57.246.148:4567 via nobandlimin/nobandlimout (nobandlimin/nobandlimout or only account traffic for   45.57.246.148 1234, that is either


```
bandlimin 2000000 * *  45.57.246.148 1234
bandlimiout 2000000 * *  45.57.246.148 1234

```

or

```
nobandlimin 2000000 * *  45.57.246.148 4567
nobandlimiout 2000000 * *  45.57.246.148 4567
bandlimin 2000000 *
bandlimiout 2000000 *

```

**Comment by z3APA3A** [comment]
Another option is to run 2 different proxy instances with 2 different configs.

**Comment by john-d13** [comment]
Hmm,  I tested your theory already and tried again with a few different orders but no luck.  Perhaps the bandlimited was not intended to work with upstream parent proxying ?

bandlimin 2000000 * *  45.57.246.148 12334
bandlimout 2000000 * *  45.57.246.148 12334

allow *
parent 1000 connect 45.57.246.148 12334 xxx xxx
maxconn 4000
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 11111
flush

Only way it works if I wildcard the target list and target port but then its applied globally and I have ~2000 proxies.

bandlimin 2000000 * * * * 
bandlimout 2000000 * * * *

**Comment by z3APA3A** [comment]
Sorry, example above is invalid, use different port destination numbers for tcppm, and distinguish traffic by port number, e.g.

bandlimin 2000000 * * 127.0.0.1 12334
bandlimout 2000000 * * 127.0.0.1 12334

allow *
parent 1000 connect 45.57.246.148 12334 xxx xxx
maxconn 4000
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 12334
flush

**Comment by john-d13** [comment]
Appreciate your help,  but still no luck.   Following step by step your instructions.

**Comment by z3APA3A** [comment]
What do you have in config?

**Comment by john-d13** [comment]
---3proxy.conf---

`nserver 1.1.1.1
nserver 1.0.0.1
nscache 65536

timeouts 1 5 30 60 180 1800 15 60
users $/etc/3proxy/conf/passwd
log /var/log/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver rar rar a -df -inul %A %F
rotate 30
plugin /usr/local/3proxy/libexec/TransparentPlugin.ld.so transparent_plugin
include /etc/3proxy/conf/proxies
`

---/etc/3proxy/proxies---

`
allow *
parent 1000 connect 45.57.246.148 12334 xxx xxx
maxconn 4000
bandlimin 2000000 * * 127.0.0.1 12334
bandlimout 2000000 * * 127.0.0.1 12334
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 12334
flush

allow *
parent 1000 connect 185.99.133.124 45000 xxx xxx
maxconn 4000
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10587 127.0.0.1 11111
flush
`


My flow is like this

Client -> Server IPTables Redirect Port 10585 -> TCPPM TLS Redirect -> Parent Proxy 45.57.246.148:12334

I see the traffic going out to 45.57.246.148:12334 but no rate limiting.   Only way it works if I set to any
bandlimin 2000000 * * * * 
bandlimout 2000000 * * * *

**Comment by z3APA3A** [comment]
TransparentPlugin is important moment here, because it changes request desination. In bandlimiter you should use the same rules for source/destination you use to ipfilter rules to redirect traffic to tcppm port.

**Comment by john-d13** [comment]
In this case I dont think it can be done.  My source IP cannot be filtered because they are random private IP.   Destination Port i tried and still not working.  See log below, destination port = 12334.   I think only solution is to run a separate instance and use wildcard. 

1579288582.826 TCPPM.10585 00000 - 10.66.77.6:49769 45.57.246.148:12334 7466 1778 1 68.67.179.122
1579288582.856 TCPPM.10585 00000 - 10.66.77.6:49770 45.57.246.148:12334 7465 1813 1 68.67.179.122
1579288586.656 TCPPM.10585 00000 - 10.66.77.6:49768 45.57.246.148:12334 643 4310 1 23.194.117.103
1579288589.064 TCPPM.10585 00033 - 10.66.77.6:49627 45.57.246.148:12334 0 3934 1 169.61.103.241
1579288590.014 TCPPM.10585 00033 - 10.66.77.6:49646 45.57.246.148:12334 0 3934 1 169.61.103.241

**Comment by john-d13** [comment]
Hi,  sorry to bring this thread up again.  I read over your post,  My IPFilter is redirecting incoming TCP to local listening port 10585 (tccpm port).     

I then set bandlimiter to target port but still not filtering.   Any ideas?

bandlimin 2000000 * * * 10585
bandlimout 2000000 * * * 10585

allow *
parent 1000 connect 45.57.246.148 12334 xxx xxx
maxconn 2000
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 10585
flush

**Comment by z3APA3A** [comment]
If you use transparent plugin, the answer is like one above - same pattern should be used for traffic match in balimin/bandlimout as you use to redirect traffic to proxy port

**Comment by john-d13** [comment]
Yes that is what I did,  something wrong?

**IPTables Rule:**

Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
REDSOCKS   tcp  --  0.0.0.0/0            0.0.0.0/0

Chain REDSOCKS (1 references)
target     prot opt source               destination
RETURN     all  --  0.0.0.0/0            10.0.0.0/8
RETURN     all  --  0.0.0.0/0            127.0.0.0/8
RETURN     all  --  0.0.0.0/0            192.168.0.0/16
RETURN     all  --  0.0.0.0/0            172.16.0.0/12
RETURN     all  --  0.0.0.0/0            0.0.0.0/8
REDIRECT   tcp  --  10.66.77.6          0.0.0.0/0            redir ports 10585

**Traffic LOGS:**

1580178733.640 TCPPM.10585 00000 - 10.66.77.6:59445 45.57.246.148:12334 1855 6376 1 52.114.128.39
1580178734.418 TCPPM.10585 00000 - 10.66.77.6:59457 45.57.246.148:12334 763 3800 1 65.97.255.194


And my **3proxy conf**

bandlimin 2000000 * * * 10585
bandlimout 2000000 * * * 10585

allow *
parent 1000 connect 45.57.246.148 12334 xxx xxx
maxconn 2000
tcppm -osTCP_NODELAY -ocTCP_NODELAY -s0 -i0.0.0.0 10585 127.0.0.1 10585
flush

**Comment by z3APA3A** [comment]
In this case valid rule is

bandlimin 2000000 * 10.66.77.6
bandlimout 2000000 * 10.66.77.6

because your redirection is based on source IP.

**Comment by john-d13** [comment]
Ok thank you,  I need to filter static attribute such as Port,  since source IP is randomly generated by VPN server.    If I cannot apply filter on tcppm port then how about a feature to add directive inside similar to maxconn?

**Comment by z3APA3A** [comment]
if you want to limit all VPN clients, add a rule for IP network used by VPN e.g. 
bandlimin 2000000 * 10.66.77.0-10.66.77.255
If you want to have a separate limit for every VPN client, the only way to do it is to add a rule for every IP address, which can be assigned to client.

**Comment by john-d13** [comment]
I am running 1500 different parent proxies,  tccpm forwarding on unique listening port for each parent proxy.   Objective is to limit traffic on specific tcppm listning ports only.   Some parent proxies i want to limit bandwidth,  globally for each client.

**Comment by z3APA3A** [comment]
it means you have 1500 conditional rules in iptable, use the same conditions you use to rederect traffic in iptables for bandlim rules

**Comment by john-d13** [comment]
Issue is if I create bandlim rule for Source IP client it will throttle all connections regardless which port they connect to.  I want compound rule -  source client IP for example 10.66.77.6 to destination port 10585.  Do not throttle source client IP 10.66.77.6 + dst port 10999

**Comment by z3APA3A** [comment]
How do you determine which port to connect the client?

**Comment by john-d13** [comment]
Based on destination parent proxy.  I keep a mapping table.  For example,  if client wants to connect to parent proxy x.x.x.x:1234 I redirect incoming TCP to tcppm listening port 10585.   

Client Source IP is chosen dynamically and I have VPN client connect script that checks the client dynamic IP and auto creates IPTables rule automatically.   The only static info I have is port mapping,  so I know if any client connect to tcppm listening port xxx throttle,  listening port yyy no throttle.

**Comment by z3APA3A** [comment]
How do you know "client wants to connect to parent proxy  x.x.x.x:1234"?

**Comment by john-d13** [comment]
Here is the flow:

1. Client chooses origin city for proxy connection from Web UI.  ie.  NY
2. Web UI connect to proxy server via API and loads env variable mapping port for NY=10585
3. Client connects to Proxy server over VPN connection.
4. OpenVPN client-connect script detects client username and via Script will know this client wants to connect to NY Location.
5. Client connect script maps client username to client IP.  
6. Client connect script creates IPTables Redirect rule for src client IP to destination port 10585 (it knows it want to connect to NY via API from web UI)

I pre-configure proxy server with NY location map to port 10585 listening on tccpm and parent proxy x.x.x.x:1234 is routed to NY.  I keep track of all these parent proxy mapping.

**Comment by z3APA3A** [comment]
Make few different network ranges based on origin city, e.g. 10.100.1.0/24 for NY and assign client an IP from a network range based on the city. It eliminates the need to manipulate IP Tables (you can route the whole network to the port instead)  and bandlimiters.
