### ISSUE TITLE
disable http 2.0

### ISSUE THREAD

**Issue by giginet2** [z3APA3A/3proxy#427]
we tested the current developement version
we found it buggy (tested on amazon, we get the code 00094, the connection is closed before the entire data is sent), is there an easy way to disable it and go with 1.1?

**Comment by z3APA3A** [comment]
3proxy doesn't implement http 2.0 and has no plans to implement it because most http/2.0 requests are encrypted.
http/2.0 client should use 'connect' method with proxy. For 'connect' method application protocol and it's version does not matter.
