### ISSUE TITLE
странное поведение socks с IPv6

### ISSUE THREAD

**Issue by alexandropulus** [z3APA3A/3proxy#43]
приветствую.
прежде всего спасибо за сервер и его развитие - очень нужный пакет.

возник вопрос  по работе пакета 3proxy-0.9-devel:
Очень странное поведение пакета при попытке шлюзования IPv4 -> IPv6 посредством socks.
в обычных http/https все отлично работает при ключике -6 и IPv6_N меняется в зависимости от порта, тогда как в случае socks именно ключ -6 не работает, но работают любые другие. При этом, если включен один из работающих ключей, то работать будут абсолютно все порты и определяться как адрес IPv4 (в примере 1.1.1.1)

#### кусок конфига (пронумеровал строки socks для более понятного описания проблемы)
nserver 2620:0:ccc::2
nscache6 65536
users user:CL:pass
auth strong
maxconn 50
allow user
deny * * 127.0.0.1,192.168.1.1 25,465,2525,587,2526
1. socks -6 -i1.1.1.1 -eIPv6_1 -p1080
2. socks -46 -i1.1.1.1 -eIPv6_2 -p1081
3. socks -64 -i1.1.1.1 -eIPv6_3 -p1082
4. socks -4 -i1.1.1.1 -eIPv6_4 -p1083
5. socks -6 -i1.1.1.1 -eIPv6_5 -p1085

т.е на примере конфига, если включены только строки 1 и/или 5 (остальные закомментированы или отсуствуют), то соединение не проходит. Если же в конфиг добавлена любая из строк 2, 3 или 4, то работают абсолютно все порты, в том числе и 1080/1085, но IP определяется как 1.1.1.1

для проксификации использую Proxyfier 3.21 который вроде как поддерживает все фичи IPv6 и туннелирования оного через IPv4

в чем может быть затык и вообще решаемо ли сие?

**Comment by z3APA3A** [comment]
Что в логах, желательно прямо с момента старта сервиса?

**Comment by alexandropulus** [comment]
Провел тестирование для всех параметров: чекал проверку соединения с гугл средствами проксифаера и пытался открыть в браузере yandex или whatismyip
можно заметить что в логах неработающих вариантов, соединение из проксифаера почему то показывается как состоявшее, после отлупа от проксифаера, остальные не отображаются

1. Работа только 1 и 5 строк с параметром -6

160217132617.660 1080 00000 - Ipv4:1080 2001:67c:2f0:6001::2b8:0 0 0 0 Accepting connections [9580/3069565808]
160217132617.661 1085 00000 - Ipv4:1085 2001:67c:2f0:6001::2cc:0 0 0 0 Accepting connections [9580/3069533040]
160217133053.471 1080 00000 username CLIENT_IP:56522 2a00:1450:4010:c02::6a:80 0 0 0 CONNECT www.google.com:80

тут надо заметить что проверка проксифаером выдает инфу

[26:53] Testing Started.
	Proxy Server
	Address:	IPv4:1080
	Protocol:	SOCKS 5
	Authentication: YES
	Username:	username

[26:53] Starting: Test 1: Connection to the Proxy Server
[26:53] IP Address: IPv4
[26:53] Connection established
[26:53] Test passed.
[26:53] Starting: Test 2: Connection through the Proxy Server
[26:53] Authentication was successful.
тут виснет на 3-4 минуты
[30:53] Error : connection to the proxy server was closed unexpectedly.
[30:53] Test failed.
[30:53] Testing Finished.

2. Работа стандартной строки socks -iIPv4 -eIPv6_N -p1084

# cat /var/log/3proxy-socks.log
160217130106.535 1084 00000 - IPv4_4:1084 0.0.0.0:0 0 0 0 Accepting connections [32236/3069823856]
160217130120.776 1084 00094 username CLIENT_IP:52510 74.125.205.105:80 43 467 0 CONNECT www.google.com:80
160217130158.501 1084 00094 username CLIENT_IP:53105 74.125.205.105:80 43 467 0 CONNECT www.google.com:80
160217130252.017 1084 00000 username CLIENT_IP:53983 212.188.7.222:80 0 0 0 CONNECT 212.188.7.222:80
160217130253.031 1084 00000 username CLIENT_IP:53987 212.188.7.221:80 0 0 0 CONNECT 212.188.7.221:80
160217130253.031 1084 00000 username CLIENT_IP:53990 212.188.7.221:80 0 0 0 CONNECT 212.188.7.221:80
160217130254.020 1084 00000 username CLIENT_IP:53993 212.188.7.221:80 0 0 0 CONNECT 212.188.7.221:80
160217130254.022 1084 00000 username CLIENT_IP:53996 212.188.7.221:80 0 0 0 CONNECT 212.188.7.221:80
160217130255.569 1084 00000 username CLIENT_IP:53999 192.230.68.192:443 866 4419 0 CONNECT 192.230.68.192:443
160217130258.872 1084 00000 username CLIENT_IP:54059 194.226.131.227:443 1051 3401 0 CONNECT 194.226.131.227:443
160217130259.075 1084 00000 username CLIENT_IP:54077 194.226.131.227:443 1402 3401 0 CONNECT 194.226.131.227:443


3. Работа только 4 строки с параметром -4

# cat /var/log/3proxy-socks.log
160217130721.255 1083 00000 - IPv4:1083 0.0.0.0:0 0 0 0 Accepting connections [2195/3069291376]
160217130822.668 1083 00094 username CLIENT_IP:54162 74.125.205.147:80 43 467 0 CONNECT www.google.com:80
160217130830.351 1083 00000 username CLIENT_IP:54168 192.230.68.192:443 1123 4107 0 CONNECT 192.230.68.192:443
160217130831.649 1083 00000 username CLIENT_IP:54210 194.226.130.228:443 1179 3401 0 CONNECT 194.226.130.228:443
160217130832.318 1083 00000 username CLIENT_IP:54171 87.250.250.12:443 3302 52865 0 CONNECT 87.250.250.12:443

4. Работа только 3 строки с параметром -64

# cat /var/log/3proxy-socks.log
160217131415.588 1082 00000 - IPv4:1082 IPv6_2:0 0 0 0 Accepting connections [4832/3069348720]
160217131847.398 1082 00000 username CLIENT_IP:54247 2a00:1450:4010:c02::69:80 0 0 0 CONNECT www.google.com:80

в данном случае прокси фаер показывает

[14:47] Testing Started.
	Proxy Server
	Address:	IPv4:1082
	Protocol:	SOCKS 5
	Authentication: YES
	Username:	username

[14:47] Starting: Test 1: Connection to the Proxy Server
[14:47] IP Address: IPv4
[14:47] Connection established
[14:47] Test passed.
[14:47] Starting: Test 2: Connection through the Proxy Server
[14:47] Authentication was successful.
и на этом этапе соединение подвисает на минуту-полторы и после выдает
[18:47] Error : connection to the proxy server was closed unexpectedly.
[18:47] Test failed.
[18:47] Testing Finished.

5. Работа 4 строки и 1

первым чекаю 1 строку, второй 4. Надо заметить, что браузер работает корректно, тогда как чекалка проксифаера по порту 1 строки ведет себя также как и в п.4, поэтому гугл, не смотря что я его проверку запускаю первой, в логах показывается после яндекса

# cat /var/log/3proxy-socks.log
160217142248.810 1080 00000 - IPv4:1080 IPv6_1:0 0 0 0 Accepting connections [30735/3069041520]
160217142248.811 1083 00000 - IPv4:1083 0.0.0.0:0 0 0 0 Accepting connections [30735/3069008752]
строка 1, порт 1080
160217142330.876 1083 00000 username CLIENT_IP:58382 192.230.68.192:443 977 4342 0 CONNECT 192.230.68.192:443
160217142332.566 1083 00000 username CLIENT_IP:58456 194.226.130.229:443 1067 3401 0 CONNECT 194.226.130.229:443
160217142333.207 1083 00000 username CLIENT_IP:58471 194.226.130.228:443 1402 3401 0 CONNECT 194.226.130.228:443
160217142333.922 1083 00000 username CLIENT_IP:58388 192.230.68.192:443 1048 4495 0 CONNECT 192.230.68.192:443
160217142335.458 1083 00000 username CLIENT_IP:58395 77.88.55.55:80 0 0 0 CONNECT 77.88.55.55:80
160217142336.459 1083 00000 username CLIENT_IP:58425 87.250.250.91:443 599 156 0 CONNECT 87.250.250.91:443
160217142336.460 1083 00000 username CLIENT_IP:58434 212.188.15.168:80 0 0 0 CONNECT 212.188.15.168:80
160217142336.461 1083 00000 username CLIENT_IP:58404 62.149.1.74:80 0 0 0 CONNECT 62.149.1.74:80
160217142336.468 1083 00000 username CLIENT_IP:58413 87.250.250.75:80 0 0 0 CONNECT 87.250.250.75:80
160217142336.471 1083 00000 username CLIENT_IP:58401 5.255.255.55:443 380 6661 0 CONNECT 5.255.255.55:443
160217142338.470 1083 00000 username CLIENT_IP:58450 87.250.251.119:443 599 156 0 CONNECT 87.250.251.119:443
160217142338.471 1083 00000 username CLIENT_IP:58453 87.250.251.119:443 599 156 0 CONNECT 87.250.251.119:443
160217142338.471 1083 00000 username CLIENT_IP:58468 213.180.204.143:443 599 156 0 CONNECT 213.180.204.143:443
160217142338.473 1083 00000 username CLIENT_IP:58474 194.226.130.228:443 944 2863 0 CONNECT 194.226.130.228:443
160217142338.473 1083 00000 username CLIENT_IP:58462 194.226.130.229:443 619 2863 0 CONNECT 194.226.130.229:443
160217142338.474 1083 00000 username CLIENT_IP:58447 87.250.251.119:443 599 156 0 CONNECT 87.250.251.119:443
160217142704.445 1080 00000 username CLIENT_IP:58379 2a00:1450:4010:c02::67:80 0 0 0 CONNECT www.google.com:80
160217142706.673 1083 00000 username CLIENT_IP:58415 5.255.255.55:443 3393 7221 0 CONNECT 5.255.255.55:443
строка 4, порт 1083
160217142832.677 1083 00000 username CLIENT_IP:58477 213.180.193.210:443 1079 6827 0 CONNECT 213.180.193.210:443
160217142837.059 1083 00000 username CLIENT_IP:58479 213.180.204.210:443 1027 6826 0 CONNECT 213.180.204.210:443
160217142838.555 1083 00000 username CLIENT_IP:58484 192.230.68.192:443 981 4033 0 CONNECT 192.230.68.192:443
160217142839.264 1083 00000 username CLIENT_IP:58541 194.226.130.229:443 1099 3401 0 CONNECT 194.226.130.229:443
160217142842.602 1083 00000 username CLIENT_IP:58489 192.230.68.192:443 379 3247 0 CONNECT 192.230.68.192:443
160217142843.609 1083 00000 username CLIENT_IP:58529 213.180.204.75:80 0 0 0 CONNECT 213.180.204.75:80
160217142843.610 1083 00000 username CLIENT_IP:58526 87.250.250.91:443 599 156 0 CONNECT 87.250.250.91:443
160217142843.613 1083 00000 username CLIENT_IP:58532 5.255.255.55:443 635 154 0 CONNECT 5.255.255.55:443
160217142843.615 1083 00000 username CLIENT_IP:58520 212.188.15.178:80 0 0 0 CONNECT 212.188.15.178:80
160217142843.616 1083 00000 username CLIENT_IP:58493 62.149.1.74:80 0 0 0 CONNECT 62.149.1.74:80

**Comment by alexandropulus** [comment]
самое интересное, что забыв выключить после последнего теста сервер, обнаружил, что спустя минут 5-10 сервер перестает работать в обоих вариантах из браузера, хотя проверка проксифаером продолжает отрабатывать корректно для параметра -4
видимо из-за того что порты ушли за 60к

160217144310.457 1080 00013 username CLIENT_IP:61500 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144310.531 1080 00013 username CLIENT_IP:61503 ::ffff:77.88.55.66:80 0 0 0 CONNECT ::ffff:77.88.55.66:80
160217144310.631 1080 00013 username CLIENT_IP:61506 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.131 1080 00013 username CLIENT_IP:61509 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.205 1080 00013 username CLIENT_IP:61512 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.207 1080 00013 username CLIENT_IP:61515 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144311.208 1080 00013 username CLIENT_IP:61518 ::ffff:62.149.1.74:80 0 0 0 CONNECT ::ffff:62.149.1.74:80
160217144311.313 1080 00013 username CLIENT_IP:61521 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.458 1080 00013 username CLIENT_IP:61524 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.460 1080 00013 username CLIENT_IP:61527 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144311.462 1080 00013 username CLIENT_IP:61530 ::ffff:62.149.1.74:80 0 0 0 CONNECT ::ffff:62.149.1.74:80
160217144311.489 1080 00013 username CLIENT_IP:61532 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144311.617 1080 00013 username CLIENT_IP:61536 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144311.620 1080 00013 username CLIENT_IP:61539 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144311.709 1080 00013 username CLIENT_IP:61542 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144311.870 1080 00013 username CLIENT_IP:61545 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144311.875 1080 00013 username CLIENT_IP:61548 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144312.163 1080 00013 username CLIENT_IP:61551 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144312.229 1080 00013 username CLIENT_IP:61554 ::ffff:62.149.1.74:80 0 0 0 CONNECT ::ffff:62.149.1.74:80
160217144312.311 1080 00013 username CLIENT_IP:61557 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144312.312 1080 00013 username CLIENT_IP:61560 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144312.339 1080 00013 username CLIENT_IP:61563 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144312.482 1080 00013 username CLIENT_IP:61566 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144312.485 1080 00013 username CLIENT_IP:61569 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144312.558 1080 00013 username CLIENT_IP:61572 ::ffff:62.149.1.74:80 0 0 0 CONNECT ::ffff:62.149.1.74:80
160217144312.650 1080 00013 username CLIENT_IP:61575 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144312.661 1080 00013 username CLIENT_IP:61578 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144312.890 1080 00013 username CLIENT_IP:61581 ::ffff:216.239.32.61:80 0 0 0 CONNECT ::ffff:216.239.32.61:80
160217144312.962 1080 00013 username CLIENT_IP:61584 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144313.361 1080 00013 username CLIENT_IP:61587 ::ffff:87.250.250.75:80 0 0 0 CONNECT ::ffff:87.250.250.75:80
160217144313.563 1080 00013 username CLIENT_IP:61590 ::ffff:87.250.250.75:80 0 0 0 CONNECT ::ffff:87.250.250.75:80
160217144313.852 1080 00013 username CLIENT_IP:61592 ::ffff:87.250.250.75:80 0 0 0 CONNECT ::ffff:87.250.250.75:80
160217144313.999 1080 00013 username CLIENT_IP:61596 ::ffff:87.250.250.75:80 0 0 0 CONNECT ::ffff:87.250.250.75:80
160217144314.380 1080 00013 username CLIENT_IP:61599 ::ffff:87.250.251.75:80 0 0 0 CONNECT ::ffff:87.250.251.75:80
160217144314.596 1080 00013 username CLIENT_IP:61602 ::ffff:87.250.251.75:80 0 0 0 CONNECT ::ffff:87.250.251.75:80
160217144314.875 1080 00013 username CLIENT_IP:61605 ::ffff:87.250.251.75:80 0 0 0 CONNECT ::ffff:87.250.251.75:80
160217144315.021 1080 00013 username CLIENT_IP:61608 ::ffff:87.250.251.75:80 0 0 0 CONNECT ::ffff:87.250.251.75:80
160217144315.542 1080 00013 username CLIENT_IP:61611 ::ffff:77.88.21.75:80 0 0 0 CONNECT ::ffff:77.88.21.75:80
160217144315.697 1080 00013 username CLIENT_IP:61614 ::ffff:77.88.21.75:80 0 0 0 CONNECT ::ffff:77.88.21.75:80
160217144315.899 1080 00013 username CLIENT_IP:61617 ::ffff:77.88.21.75:80 0 0 0 CONNECT ::ffff:77.88.21.75:80
160217144316.040 1080 00013 username CLIENT_IP:61620 ::ffff:77.88.21.75:80 0 0 0 CONNECT ::ffff:77.88.21.75:80
160217144316.570 1080 00013 username CLIENT_IP:61623 ::ffff:213.180.204.75:80 0 0 0 CONNECT ::ffff:213.180.204.75:80
160217144316.733 1080 00013 username CLIENT_IP:61625 ::ffff:213.180.204.75:80 0 0 0 CONNECT ::ffff:213.180.204.75:80
160217144316.917 1080 00013 username CLIENT_IP:61629 ::ffff:213.180.204.75:80 0 0 0 CONNECT ::ffff:213.180.204.75:80
160217144317.057 1080 00013 username CLIENT_IP:61632 ::ffff:213.180.204.75:80 0 0 0 CONNECT ::ffff:213.180.204.75:80
160217144317.595 1080 00013 username CLIENT_IP:61635 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144317.769 1080 00013 username CLIENT_IP:61638 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144317.944 1080 00013 username CLIENT_IP:61641 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144318.081 1080 00013 username CLIENT_IP:61644 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80
160217144318.643 1080 00013 username CLIENT_IP:61647 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144318.805 1080 00013 username CLIENT_IP:61650 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144319.043 1080 00013 username CLIENT_IP:61653 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144319.113 1080 00013 username CLIENT_IP:61656 ::ffff:93.158.134.75:80 0 0 0 CONNECT ::ffff:93.158.134.75:80
160217144332.986 1083 00094 username CLIENT_IP:61657 74.125.205.104:80 43 467 0 CONNECT www.google.com:80

**Comment by z3APA3A** [comment]
`160217144318.081 1080 00013 username CLIENT_IP:61644 ::ffff:213.180.193.75:80 0 0 0 CONNECT ::ffff:213.180.193.75:80`
это в прокси запущенный с -6 пришел клиент, который запросил адрес IPv4.

**Comment by z3APA3A** [comment]
160217133053.471 1080 00000 username CLIENT_IP:56522 2a00:1450:4010:c02::6a:80 0 0 0 CONNECT www.google.com:80

- можешь дать сниф трафика (tcpdump или wireshark) во время тестирования проксификатора, можно на 3proxy@3proxy.ru. По этой записи - клиент пришел, запросил установку соединения, но ничего передавать не стал.

**Comment by alexandropulus** [comment]
для всех пунктов снифить или только для последнего?

**Comment by z3APA3A** [comment]
Для самого первого, где только с параметром -6.

**Comment by alexandropulus** [comment]
отправил в архиве на почту

**Comment by z3APA3A** [comment]
По дампу трафика все ровно как в логе, см например по фильтру tcp.stream eq 6 в wireshark - клиент просит установить соединение с www.google.com:80
прокси устанавливает соединение и сообщает серверу об успешно установленном соединении (пакет 1593), после чего от клиента ничего не приходит. Все висит 4 минуты, после чего гугл закрывает соединение, прокси со своей стороны тоже закрывает соединение.
Проверь не вмешивается ли в работу, например, антивирус со стороны клиента, если ничего такого нет - отправб багрепорт разработчикам проксификатора.

**Comment by alexandropulus** [comment]
там антивиря нет, т.ч значит дуркует именно проксифаер 
спасибо за помощь!
