### ISSUE TITLE
При проксировании по протоколу SOCKS утекает локальный Ip.

### ISSUE THREAD

**Issue by FastSpace123** [z3APA3A/3proxy#430]
Всем привет. Есть одна очень досадная проблема.

При использовании протокола socks5 происходит утечка локального ip. Тоесть ip компьютера который подключаеться к прокси расположенным на другом компьютере. Либо это локальный роутера, либо самого провайдера.

Утечку проверял через сайт proxyleak.com внизу в разделе ip.
socks -n -a -pxxx -ilocal -exxxxx

Однако если использовать протокол http такой проблемы нет.
proxy -n -a -pxxx -ilocal -exxxxx

**Comment by z3APA3A** [comment]
Прокси при всем желании не умеет прокидывать IP клиента socks наружу, т.к. прокидывать его в общем случае негде. Если IP откуда-то утекает, то это происходит не от прокси, а от клиента.

**Comment by FastSpace123** [comment]
> Прокси при всем желании не умеет прокидывать IP клиента socks наружу, т.к. прокидывать его в общем случае негде. Если IP откуда-то утекает, то это происходит не от прокси, а от клиента.

Я бы поверил этому, если бы не одно но.
Я тестировал разные прокси подобного типа как у меня из магазинов и там не было этой утечки. Тоесть с моей стороны ничего не утекало.
