### ISSUE TITLE
Перенаправления проксей 

### ISSUE THREAD

**Issue by altrof** [z3APA3A/3proxy#431]
Добрый день!

Хотел бы задать вопрос об перенапрвлениях.
Если ставишь maxconn 5, то он разрешает максимум 5 подключений на 1 пользователя.
Как сделать чтобы на 1 прокси было 1 максимальное подключение, если второй пытается подключиться, то его перекидывает на второй прокси автоматом и т.д.?

**Comment by z3APA3A** [comment]
Что значит перекидывает на второй прокси, чем второй прокси отличается от первого?

**Comment by altrof** [comment]
Спасибо за столь быстрый ответ!

1прокси = 1 4г модем
нужно сделать так чтобы был 1 пул проксей (1пул проксей в себе содержит до 5модемом т.е. проксей), и к 1 пулу можно подключаться по 1 порту и по 1 юзеру. Я так полагаю это делается перенаправлениями (редиректами)? Перенаправления он делает засчет maxcon на 1 прокси 
А пул я так полагаю 1 сервер и на сервере до 5 проксей.
Использоваться это будет в мултилогине.
Каждому модему 4г меняю ip

**Comment by z3APA3A** [comment]
Это можно попробовать сделать путем запуска нескольких прокси на одном порту. Пример есть в 
https://3proxy.ru/highload.asp
