### ISSUE TITLE
parent only

### ISSUE THREAD

**Issue by ia2130** [z3APA3A/3proxy#432]
Подскажите как разрешить пользователям ходить только через родительский прокси сервер и запретить ходить через основной в случае если родительский не работает

nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
service
allow usrprx
users $"c:\\3proxy\bin64\userlist"
auth iponly strong
maxconn 100
fakeresolve
parent 1000 socks5+ 127.0.0.1 23321
proxy -a -n -p5000 

в случае когда родительский сервер падает на порту 23321 пользователи выходится в инет через основной прокси сервер что необходимо запретить

**Comment by z3APA3A** [comment]
parent расширяет предыдущую команду allow (и записывать ее иммет смысл после allow чтобы самому себя не путать) и при весе 1000 действует с вероятностью 100%. В такой конфигурации usrprx будет всегда перенаправлять в родительской прокси.
