### ISSUE TITLE
odbc

### ISSUE THREAD

**Issue by safetylab** [z3APA3A/3proxy#434]
centos8 3proxy-0.8.13 собран с LIBS = -ldl -lodbc
Конф
log &3proxy,3proxy
logformat "LINSERT INTO log ("time", bytesin, bytesout, username, url, host, port, service) values ('%Y-%m-%d %H:%M:%S', %I, %O, '%U', '%Q', '%Q', %q, %I);"
odbc.ini
[3proxy]
Description     = MySQL ODBC Driver
Driver          = MySQL
Socket          = /var/lib/mysql/mysql.sock
Server          = localhost
Database        = 3proxy
Option          = 3
User            = 3proxy
Password        = password
Не пишет лог в базу - если делаю лог в конф и беру инстерт оттуда все ок вставляет
В логе 3proxy[2503]: segfault at 7fad340fb318 ip 00007fad3577e1ed sp 00007fad340fb318 error 6 in libodbc.so.2.0.0[7fad3572a000+65000]
Прошу проверить и исправить

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#CRASH
увеличивай размер стека 
+ не все версии odbc и драйверов thread safe, надо искать рабочую.

**Comment by bigskygroup** [comment]
скажите версию с которой работает у вас - будем пробовать туже у себя.

**Comment by z3APA3A** [comment]
Начни с увеличения стека. Поставь, например,
stacksize 8388608
если заработает - дели пополам, пока продолжает работать.
Я не пользуюсь ODBC под Linux.

**Comment by safetylab** [comment]
не заработало - куда копать?

**Comment by z3APA3A** [comment]
Как не заработало, что в конфиге?

**Comment by safetylab** [comment]
stacksize 8388608
daemon
log &3proxy,3proxy
logformat "LINSERT INTO log ("time", bytesin, bytesout, username, url, host, port, service) values ('%Y-%m-%d %H:%M:%S', %I, %O, '%U', '%Q', '%Q', %q, %I);"
База и таблица есть - в таблице пусто

**Comment by z3APA3A** [comment]
Процесс крешится или нет?

**Comment by safetylab** [comment]
работает - просто не пишет ничего - не крешится

**Comment by z3APA3A** [comment]
Ну тогда очевидно это уже что-то другое. Проверь, например, connect string, уверен что в нем нужно имя пользователя?

**Comment by z3APA3A** [comment]
Доступ к odbc.ini у эккаунта с которым прокси запускается?

**Comment by safetylab** [comment]
он запускается от рута

**Comment by safetylab** [comment]
odbc.ini лежит в /etc

**Comment by z3APA3A** [comment]
Добавь что-нибудь типа
system "echo $ODBCINI / $ODBCSYSINI  > /tmp/3odbc.log"
в конфиг и посмотри, установлены ли переменные. Если не установлены - установи.
odbc.ini насколько я понимаю тоже должен не так выглядить, вот пример:
https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-dsn-unix.html

**Comment by safetylab** [comment]
Лог пустой - если делать export tо
declare -x ODBCINI="/usr/local/etc/odbc.ini"
declare -x ODBCSYSINI="/usr/local/etc"
odbc.ini
[3proxy]
Description     = MySQL ODBC Driver
Driver          = MySQL
Socket          = /var/lib/mysql/mysql.sock
Server          = localhost
Database        = 3proxy
Option          = 3
User            = 3proxy
Password        = parol
ошибок нет и не пишет

**Comment by z3APA3A** [comment]
Насколько я понимаю, в Driver  должен быть путь к драйверу (shared-библиотеке), и не уверен, что можно/нужно задавать одновременно SOCKET и server, задай что-то одно, что у тебя MySQL слушает.

**Comment by safetylab** [comment]
/usr/local/etc/odbcinst.ini
[MySQL]
Description=ODBC for MySQL
Driver=/usr/lib/libmyodbc5.so
Setup=/usr/lib/libodbcmyS.so
Driver64=/usr/lib64/libmyodbc5.so
Setup64=/usr/lib64/libodbcmyS.so
FileUsage=1

поменял так же не пишет

**Comment by z3APA3A** [comment]
А в конфиге что в итоге? Команда log дается до запуска сервисов?

И таки у тебя лежит-то все в /usr/local/etc или в /etc?

**Comment by safetylab** [comment]
все работает - правильный конфиг odbc
[3proxy]
Description     = MySQL ODBC Driver
Driver          = /usr/lib64/libmyodbc8a.so
Server          = localhost
Database        = 3proxy
Option          = 3
User            = 3proxy
Password        = parol

**Comment by z3APA3A** [comment]
Ну тогда можешь поискать оптимальный размер stacksize, иначе может много памяти жрать

**Comment by atimofeev86** [comment]
Такая же проблема на CentOS 8.
собрана последняя версия 3rpoxy с git.

odbc.ini
[lte]
Description     = MySQL ODBC Driver
Driver          = /usr/lib64/libmaodbc.so
Server          = localhost
Database        = lte
Option          = 3
User            = 3proxy
Password        = Password        

служба запускается, работает, не падает. Но в таблицу ничего не записывается.

Через isql lte -v подключение устанавливается, запись в таблицу добавляется
