### ISSUE TITLE
[Question] Transparent Proxy / Throttle Upload from native

### ISSUE THREAD

**Issue by DoM1niC** [z3APA3A/3proxy#435]
Hey Bro your 3Proxy is awesome!!!

But I missed some configure Stuff.

1. I wanne use the 3Proxy as Transparent Proxy currently I use this workaround. with 
**Transocks_ev**
`transocks_ev -f -H 10.1.0.1 -p 4007 -S 127.0.0.1 -s 3130`
and before
2. **NGINX** (Streams) to limit the Bandwith like Upstream
```
    server {
        listen 127.0.0.1:3130;
        proxy_pass 127.0.0.1:3129;
        #proxy_download_rate 780k;
        proxy_upload_rate   200k;
    }
```
3. after this I set the **NAT** Stuff in **IPTables**
like this 
`/sbin/iptables -t nat -A wlan0_Internet -m mark --mark 0x3 -p tcp --syn -j REDIRECT --to-ports 4007
`

**3Proxy Config**
```
#log /home/3proxy/log D
#rotate 30
internal 10.1.0.1
external 24.134.X.X
auth none
#bandlimin 25007600 * *
socks -p3129 -i127.0.0.1
```

> **e.g.** the TORRC Stuff allowed to set the Server directly without any Transocks_ev

**Comment by phantomcraft** [comment]
Perhaps you missed "iponly" in auth:

#log /home/3proxy/log D
#rotate 30
internal 10.1.0.1
external 24.134.X.X
auth iponly
#bandlimin 25007600 * *
socks -p3129 -i127.0.0.1

**Comment by DoM1niC** [comment]
> Perhaps you missed "iponly" in auth:
> 
> #log /home/3proxy/log D
> #rotate 30
> internal 10.1.0.1
> external 24.134.X.X
> auth iponly
> #bandlimin 25007600 * *
> socks -p3129 -i127.0.0.1

What happen with IPonly the Auth os none all will be allowed, this is not my solution so far... iponly just allowed single IPs or Subnets, but None allows all here and works well.

**Comment by z3APA3A** [comment]
Your report lacks problem description. Try to enable logging and see what you have in logs.
I'm not linux guru, but for me it looks like your iptable only redirects SYN packets for some reason instead of all traffic.

Also, this configuration is too sophisticated, you can consider to use
https://3proxy.ru/plugins/TransparentPlugin/
and 3proxy bandlimiting / connection limiting functionality

**Comment by DoM1niC** [comment]
> Your report lacks problem description. Try to enable logging and see what you have in logs.
> I'm not linux guru, but for me it looks like your iptable only redirects SYN packets for some reason instead of all traffic.
> 
> Also, this configuration is too sophisticated, you can consider to use
> https://3proxy.ru/plugins/TransparentPlugin/
> and 3proxy bandlimiting / connection limiting functionality
> 
> P.S. for this config there is really no difference between `auth none` and `auth iponly`.

THX for your reply the Transparent Proxy Stuff works now!

```
#log /home/3proxy/log D
#rotate 30
plugin /opt/3proxy/bin/TransparentPlugin.ld.so transparent_plugin
internal 10.1.0.1
external 24.134.17.209
auth none
bandlimin 25007600 * *
transparent
socks -p3129 -i127.0.0.1
tcppm -i10.1.0.1 4008 127.0.0.1 11111
```
**tcppm** listen on same Port like **Transocks_ev** & all works here now! But the Bandwith limiting from Upstream is not working yet, I remoced the **--syn** Stuff without any changes.

**Comment by z3APA3A** [comment]
it should be bandlimout (bandlimout limits the speed from proxy to external server), but with * it will probably have a different effect comparing with proxy_upload_rate , because it shares the limit between all connections.

**Comment by DoM1niC** [comment]
> it should be bandlimout (bandlimout limits the speed from proxy to external server), but with * it will probably have a different effect comparing with proxy_upload_rate , because it shares the limit between all connections.

WOW THX all works now :) your Support is awesome Bro 👍

**Comment by z3APA3A** [comment]
you can configure per-connection bandwidth limit with 'tc' if required. Or create a feature request for per-connection bandlimit, it shouldn't be hard to implement, but generally I see no any practical use in per-connection bandwidth limits.

**Comment by DoM1niC** [comment]
> you can configure per-connection bandwidth limit with 'tc' if required. Or create a feature request for per-connection bandlimit, it shouldn't be hard to implement, but generally I see no any practical use in per-connection bandwidth limits.

I got no success with TC but your Proxy works fine in my environment 🥇
