### ISSUE TITLE
3proxy cointin

### ISSUE THREAD

**Issue by Marek521** [z3APA3A/3proxy#438]
Уважаемые друзья, мне нужна ваша помощь.
Пользуюсь командой countin в 3прокси, которая ограничивает трафик, к сожжению когда я перезагружу приложение 3прокси, лимит трафика восстанавливается . Скажите пожалуйста, есть ли какая-нибудь команда, чтобы счётчик трафика продолжал после перезагрузки считать трафик либо другой способ использовать countin?Заранее большое спасибо!

**Comment by z3APA3A** [comment]
Чтобы счетчики были перманентными, необходима команда counter.

**Comment by Marek521** [comment]
Помогите пожалуйста мне хорошо это понять:
Надо пользоваться командой -counter вместе с командой -countiin так, чтобы команда counter сохраняла в файл трафик, тогда команда countin будет пользоваться данными с этого файла?
Есть ли следующая записка корректна, чтобы ограничить трафик до 2гб /день:counter /usr/local/3proxy/count/3proxy.3cf D
countin myname1 D 2000 * 192.168.0.0 
countin myname2 D 2000 * 192.168.0.1
.
.
192.168.0.0 - это адреса IP клиента.
Как часто сохраняется файл 3proxy.3cf ? Что случится, когда на пример 3proxy перезагрузится во время дня?

**Comment by z3APA3A** [comment]
файл сохраняется примерно раз в минуту и при завершении прокси, при запуске восстанавливается сохраненное состояние.
