### ISSUE TITLE
падение с пам авторизацией

### ISSUE THREAD

**Issue by myworking82** [z3APA3A/3proxy#44]
Все привет. Есть конфиг, минимально настроеный для тест под виртуалкой
ОС: Debian 8.3
Ядро: 3.16.0-4-amd64, из доп модулей собирался еще памавторизаловка

# cat /etc/3proxy/3proxy.cfg 
daemon

plugin "/var/lib/3poxy/pamauth.ld.so" start 3proxy

pidfile /var/run/3proxy/3proxy.pid

internal 172.16.35.6
external 172.16.35.6

nserver 8.8.8.8

nscache 65536
timeouts 1 5 30 60 180 1800 15 60

log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

flush
maxconn 32

authcache user,password 60
auth cache pam
allow *

proxy -p3199
socks -p3198

демон стартует, но конект проходит но приеме логина и пароля (нет разныцы верные или нет), прокся валится наглухо, единственное что на рыл, вот в dmesg
[16490.890530] 3proxy[15562]: segfault at 7fa5213d8748 ip 00007fa51fda5558 sp 00007fa5213d8740 error 6 in libaudit.so.1.0.0[7fa51fda0000+1a000]

может кто подскажет, что не так может сделал и т.д.

Заранее всех благодарю за помощь!

**Comment by z3APA3A** [comment]
Попробуй в devel версии дать команду
stacksize 8192
(ну или попробовать найти минимальный размер стека, при котором будет работать).
"тяжелые" сторонние плагины могут требовать больший размер стека чем тот, что используется по умолчанию.

**Comment by myworking82** [comment]
хорошо, спасибо, ща буду пробовать)

**Comment by myworking82** [comment]
прокся не знает о таком параметре (((

http://i.imgur.com/ZfBlneQ.png

**Comment by z3APA3A** [comment]
А ты точно взял код из devel-ветки? В релиз эта команда войдет в 0.8.4.

**Comment by myworking82** [comment]
действительно, сори, буду проверять

**Comment by myworking82** [comment]
получилось, на размере стека 8192 завелось и не ложится, спасибо
