### ISSUE TITLE
3proxy пускает без пароля

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#440]
Владимир, здравствуйте.

Столкнулся с такой ситуацией.
При конфиге, полностью приведенном ниже, 3proxy пускает как без пароля, так и по произвольному логину и паролю.
Перенаправления работают, а вот с ACL никак не могу разобраться.
Помогите, пожалуйста!

daemon
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 5 5 15 5 15 5

log /usr/local/etc/3proxy/3proxy.log

users test1210:CL:42jrC0W7
users test1211:CL:d5seQpco
users test1212:CL:06mmmPPF

internal 43.61.160.227
external 43.61.160.227

auth strong

allow test1210,test1211
parent 200 socks5 192.168.1.91 1080
parent 200 socks5 192.168.1.92 1080
parent 200 socks5 192.168.1.93 1080
parent 200 socks5 192.168.1.94 1080
parent 200 socks5 192.168.1.95 1080
parent 1000 socks5 192.168.1.3 1210 *
proxy -a -p1210
socks -p10210

3proxy работает на FreeBSD 12, пробовал версию из портов (08.13), а так же компилировал 0.9.dev версию. Ситуация одна и та же.

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by spiller1975** [comment]
А в логах станная ситуация.
Показывает, что якобы используется логин из списка.

200221082937.491 1210 00064 test1210 31.173.31.140:48973 192.168.1.94:1080 0 66 2 CONNECT wqwtkrj4ydi6b5yev0kky2c31ja0c109.dnsleak6.browserleaks.org:443 HTTP/1.1
200221082941.598 1210 00092 test1210 31.173.31.140:24327 192.168.1.93:1080 1488 6499 2 CONNECT browserleaks.com:443 HTTP/1.1
200221082942.792 1210 00000 test1210 31.173.31.140:30121 192.168.1.91:1080 1062 7679 2 CONNECT rdap.db.ripe.net:443 HTTP/1.1
200221082943.337 1210 00092 test1210 31.173.31.140:6620 192.168.1.94:1080 1082 2539 2 CONNECT tslp0bye3162bjj98x08ar1ac7p2x6av.dnsleak6.browserleaks.org:443 HTTP/1.1
200221082943.379 1210 00092 test1210 31.173.31.140:51301 192.168.1.91:1080 1083 2528 2 CONNECT tk46p648x86ty5m4421171lnxn5nenk6.dnsleak4.browserleaks.org:443 HTTP/1.1
200221082943.461 1210 00092 test1210 31.173.31.140:4157 192.168.1.92:1080 1082 2527 2 CONNECT tslp0bye3162bjj98x08ar1ac7p2x6av.dnsleak4.browserleaks.org:443 HTTP/1.1

Но я этим логином не пользуюсь, проверял много раз, вбиты данные другие.
Для тестов пользуюсь Firefox + FoxyProxy.
Полностью удалял все настройки прокси из плагина FoxyProxy, вбивал заново.
Вроде дело не в плагине.

3proxy откуда может этот логин приклеивать к сессии?
Что-то ничего не пойму...

**Comment by spiller1975** [comment]
Это речь только про http прокси, socks нормально работает

**Comment by z3APA3A** [comment]
Ну значит прокси тут непричем и этот логин/пароль передается со стороны клиента. Измени пароль для этого эккаунта, например, и сравни результат.
