### ISSUE TITLE
parent

### ISSUE THREAD

**Issue by kharvispektr23** [z3APA3A/3proxy#441]
Мне нужно чтобы подключаясь к моему vds я получал айпи с прокси, запщунной программой на этом вдс. Программа делает локальный socks5 прокси 127.0.0.1 4066 подключение к которому через браузер нормально работает. Авторизаций никаких нет.

logformat "%d-%m-%Y %H:%M:%S %U %C:%c %R:%r %O %I %T"
users admin:CL:pass
fakeresolve 
auth strong
log
rotate 1

allow *
parent 1000 socks5+ 127.0.0.1 4066

proxy -p3166 -n -a

**Comment by kharvispektr23** [comment]
Ошибка при установлении защищённого соединения

При соединении с whoer.net произошла ошибка. PR_END_OF_FILE_ERROR

**Comment by z3APA3A** [comment]
А что в логах?

**Comment by kharvispektr23** [comment]
уже удалил там было чтото типо
запрос на сайт google.ru:80 127.0.0..:... -> 127.0.0.1:4166 (айпи локального сокс) и больше ничего после это строки
https://github.com/GameXG/TcpRoute2 через эту все нормально заработало
