### ISSUE TITLE
allow /21

### ISSUE THREAD

**Issue by atimofeev86** [z3APA3A/3proxy#443]
Использую доступ по маске 
allow * 5.135.209.59,178.33.216.1/21 *2ip.ua*
но 3proxy не пропускаем меня с IP 178.33.217.185, который входит в подсеть 178.33.216.1/21
в логе
2020-02-26 10:33:04 0 0 0 0 - CONNECT 2ip.ru:443 HTTP/1.1 195.201.201.32 443 178.33.217.185 50677 0.0.0.0 0 51.195.10.195 0.0.0.0 2ip.ru

Если изменяю 
allow * 5.135.209.59,178.33.216.1/21 *2ip.ua*
на 
allow * 5.135.209.59,178.33.217.185 *2ip.ua* 
то сайт открывается

**Comment by z3APA3A** [comment]
Во-первых, 178.33.216.1/21 не является корректным CIDR (178.33.216.1 не может быть адресом сети для /21), не уверен как такое правило будет работать.
Во-вторых, у тебя свой формат логов и в нем не видно кода ошибки

**Comment by atimofeev86** [comment]
Разобрался. Спасибо за наводку с кодом ошибки в логе.
У меня стояла авторизация auth iponly strong и сначала была авторизация по логину, затем по IP.
+ были ошибки в ACL.
Изменил ACL - сначала идет по IP, потом по пользователю и все зашуршало.

178.33.216.1/21 - тоже работает ))
