### ISSUE TITLE
1 прокси и 20 шлюзов

### ISSUE THREAD

**Issue by komato3huk** [z3APA3A/3proxy#444]
на debian 20 интерфейсов все смотрят на свои роутеры
192,168,88,1 основной маршрутизатор с которого идет редирект на прокси.
Сам прокси имеет internal 192,168,88,246
в конфиге. 
proxy -n -p5000 -a -i192.168.88.246 -e192.168.87.2
proxy -n -p5001 -a -i192.168.88.246 -e192.168.86.2
external у каждого интерфейса свой.
Но я не могу понять почему при обращении на 5000 порт трафик уходит через 192,168,88,246 в деф маршрут.
Пробовал прописывать на каждый интерфейс отдельно с отличной метрикой и все равно уходит трафик через 88,246

**Comment by z3APA3A** [comment]
В Linux задание IP задает только IP, а не интерфейс, надо дополнительно либо настраивать source routing либо дополнительно задавать интерфей через -De (прокси в таком случае должен работать от root)

**Comment by z3APA3A** [comment]
И маршруты, разумеется, все равно должны быть прописаны

**Comment by komato3huk** [comment]
Спасибо. Но еще одно но. Работает только в dev релизе. Внесите плиз в Вики.
