### ISSUE TITLE
Не срабатывает nsrecord для HTTPS соединений, или я чего-то не понимаю?

### ISSUE THREAD

**Issue by trafostream** [z3APA3A/3proxy#445]
Здравствуйте!

Не могу понять, почему не срабатывает nsrecord для HTTPs запросов.
При обращении по HTTP на хост site1.ru запросы идут на 94.150.10.5 - работает правильно.
При обращении по HTTPs запросы идут на реальный IP, который выдает локальный DNS сервер, не смотря на то, что хост site2.ru прописан - работает НЕ правильно.
Причем в логах все отражается правильно, но на деле не работает.
Нужно чтобы как HTTP, так и HTTPs запросы шли к указанным в nsrecord хостам.
Объясните пожалуйста, что делаю не так?
Спасибо.

Конфиг:

nsrecord site1.ru 94.150.10.5
nsrecord site2.ru 94.150.10.5
allow *
socks -a -p8080 -i127.0.0.1

Лог:

200303185312.692 8080 00000 - 127.0.0.1:8080 0.0.0.0:0 0 0 0 Accepting connections [24618/1053951744]
200303185316.264 8080 00000 - 127.0.0.1:46838 94.150.10.5:80 322 1312 0 CONNECT site1.ru:80
200303185316.559 8080 00000 - 127.0.0.1:46852 94.150.10.5:443 342 1156 0 CONNECT site2.ru:443

**Comment by z3APA3A** [comment]
{noformat}
200303185316.559 8080 00000 - 127.0.0.1:46852 94.150.10.5:443 342 1156 0 CONNECT site2.ru:443
{noformat}
все ушло туда, куда прописан nsrecord, к тому же для socks нет никакой разницы между http и https, ищите проблему не в этом.
