### ISSUE TITLE
Разные днс. Попытка включить include не сколько конфигов.

### ISSUE THREAD

**Issue by Drakoshas** [z3APA3A/3proxy#447]
Хочется для каждой прокси (или группе проксей) привязать нужный dns.
Мысленно это можно сделать несколькими способами:
1) самый простой, не сколько копий 3proxy запустить. 
Минус, на windows несколько служб не создается (ошибка Failed to create service: No error)
2) включить под конфиг и в нем выделить другой днс
Минус не смогли воспользоваться 
Нашел в документации такую настройку include <path> ([https://www.3proxy.ru/doc/man3/3proxy.cfg.3.html])
include $"c:\\3proxy\3proxy-0.8.12\bin\conf\3proxy3.txt" 
При попытки запуски выдается ошибка Unknown command: 'include' line 1

Можете посоветовать как лучше это реализовать?

**Comment by z3APA3A** [comment]
Запустить несколько копий 3proxy. 

include $"c:\3proxy\3proxy-0.8.12\bin\conf\3proxy3.txt"

- здесь не требуется $, $ подставляет содержимое файла.
