### ISSUE TITLE
Ipv6 outgoing configuration 

### ISSUE THREAD

**Issue by nihatalim** [z3APA3A/3proxy#448]
Hello. I have a business scenario. In this scenario, I have an ipv4 address and multiple ipv6 addresses. Expected behavior of proxy is **every port pass the internet traffic throught defined ipv6 address**. 

For example:

I have couple of ipv6 addresses which defined on eth0 adapter.

![image](https://user-images.githubusercontent.com/33811062/76458777-1ee55880-63ec-11ea-9f80-a64b7d06691c.png)

And lets assume, our server ip is 10.11.12.13. In order to pass traffic throught ipv6 addresses which defined in our server, we need to map each port to our specified ipv6 address determined before. 

The expected result should be following:

Proxy server          ->   Internet outgoing ipv6 address
10.11.12.13:10000 -> 2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f10
10.11.12.13:10001 -> 2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f11
10.11.12.13:10002 -> 2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f12
10.11.12.13:10003 -> 2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f13

I know that I can do this requirement with squid http proxy. Although there is a solution for http proxy, I need this requirement for SOCKS5 proxy. Can you help me how can I solve this problem, please?

Thank you!

**Comment by z3APA3A** [comment]
socks -i10.11.12.13 -p10000 -6 -e[2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f10]
socks -i10.11.12.13 -p10001 -6 -e[2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f11]
...

**Comment by nihatalim** [comment]
Unfortunately this configuration did not work. I tried like:

socks -i10.11.12.13 -p10000 -6 -e2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f10
socks -i10.11.12.13 -p10000 -6 -e[2a0c:b9c0:f:XXXX:573e:d3d6:acbf:2f10]

Those type of configs didn't work for me. Socks works for ipv4 but not work on ipv6. How can I do pass traffic through an ipv6 address? Thank you very much.

**Comment by z3APA3A** [comment]
What do you have in logs?

**Comment by andersonpfx** [comment]
I already tried that way but it doesn't work, the output still continues the ipv4.

Do you need to do any configuration on the server besides configuring 3proxy.cfg? for ipv6 forwarding to work?

**Comment by z3APA3A** [comment]
what exactly do you have in config and in logs and which 3proxy version do you use?
