### ISSUE TITLE
очень огромный конфиг

### ISSUE THREAD

**Issue by valdemarttito** [z3APA3A/3proxy#449]
Доброго времени . Извиняюсь за беспокойство :) Помогите с вопросом, как быть ?
Имеем : 
10к пользователей вида 
user1-user10000  - 10000 строк в конфиге
для каждого пользователя свой acl  - это ещё 20 тыс строк .
в итоге нагрузка на проц сервера естественно идёт бешенная при конфиге в 30000 строк .
Остальное всё на сервере уже оптимизировано на сколько можно . Появилась необходимость расширения конфига до 20000 пользователей но под нагрузкой сервер вешается - не удивительно.
конфиг примерно так идёт

```
= = = = = 
noforce
stacksize 131072
daemon
maxconn 2000
nscache 131072
timeouts 1 5 30 60 180 1800 15 60
flush
auth strong
flush
users user1:CL:pass 
...здесь 9998 строк user(id)
users user10000:CL:pass 

allow user1 * 
parent 1000 socks5+ 127.0.0.2 3333 user1 pass
...здесь ещё 9998x2 строк


allow user10000 * 
parent 1000 socks5+ 127.0.0.2 3333 user10000 pass

allow *


socks -s0 -osTCP_NODELAY -ocTCP_NODELAY -n  -a -p3002	-i111.11.111.11 -e111.11.111.11

= = = = = = = =
```

Этот бред сумашедшего *меня* весит 2мб ) сервер под нагрузкой держится но с трудом.
подскажите в данной ситуации возможно как то облегчить жизнь Cpu сервера ?))
конфиг на 15000 он уже тянет в LA 50 ) на 10тыс - la ~9-11 под нагрузкой )) .
http://prntscr.com/rjwnuq

Перерыл наверное всё что мог , подскажите пожалуйста что тут может помочь ? Такое извращение с кол-вом пользователей и индивидуальный acl для каждого пользователя необходимо сохранить, может как то можно переменными конфиг указать типа :
users user1-10000:CL:pass 

allow user(id) * 
parent 1000 socks5+ 127.0.0.2 3333 user(id) pass
здесь всё кроме (id) статично одинаковое у всех 10000 пользователях.
 
или может попробовать несколько копий 3proxy запустить ? возможно ли при одном и том же 
internal \ external  запустить 2 копии 3proxy у одного в конфиге 1-5000 юзеры во втором 5000-10000 ? не будет ли конфликтов ? в теории если заработает то cpu облегчится ведь обработка строк идёт последовательная . 
Надеюсь на вашу помощь :)

**Comment by z3APA3A** [comment]
Используй RADIUS или напиши свой плагин для аутентификации, 3proxy обрабатывает все списки последовательно.
https://3proxy.ru/highload.asp
