### ISSUE TITLE
‘ssl_certcache’ in sslplugin has no effect

### ISSUE THREAD

**Issue by wyzegob** [z3APA3A/3proxy#45]
No matter how ssl_cert cache settings, 3proxy.exe always read 3proxy.pem from the app path where 3proxy.exe is.

**Comment by z3APA3A** [comment]
I can't confirm this behaviour. Can you show your config file?

**Comment by z3APA3A** [comment]
Sorry, I see the problem, this commit https://github.com/z3APA3A/3proxy/commit/c96d415020166801bb78a36bcd4fcf6f957b08a6 should fix it.
