### ISSUE TITLE
get  the packets through the proxy

### ISSUE THREAD

**Issue by maryXielee** [z3APA3A/3proxy#450]
Hi, I want to analyze the packets going through the proxy, where could I get these packets?

**Comment by z3APA3A** [comment]
Proxy works on application layer, it doesn't deal with packets. If you want to analyze the traffic on socket layer you may want to look into plugins API
https://3proxy.ru/doc/devref.rtf
(may be a bit outdated)

**Comment by maryXielee** [comment]
hi,
I want to get the packet and analyze it myself，Do you mean I need develop my own plugin to get it？
You see the log can output IP and other information,&nbsp;Isn't this information get from packets?
Thanks for answering my question




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Vladimir Dubrovin"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月23日(星期一) 下午4:28
收件人:&nbsp;"z3APA3A/3proxy"<3proxy@noreply.github.com&gt;;
抄送:&nbsp;"淼淼"<maryxielee@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [z3APA3A/3proxy] get  the packets through the proxy (#450)





 
Proxy works on application layer, it doesn't deal with packets. If you want to analyze the traffic on socket layer you may want to look into plugins API
 https://3proxy.ru/doc/devref.rtf
 (may be a bit outdated)
