### ISSUE TITLE
CONNECT http header wrong and this is causing 502 error

### ISSUE THREAD

**Issue by kodmanyagha** [z3APA3A/3proxy#452]
I'm running 3proxy on centos7. I found an interesting issue. I'm seeing this log:

	1585557274.665 PROXY.20059 00000 emir 178.238.239.13:58424 2607:f2d8:4010:8::2:443 460 6137 0 CONNECT api6.ipify.org:443 HTTP/1.1
	1585557276.478 PROXY.20040 00012 emir 178.238.239.13:57146 2607:f2d8:4010:8::2:443 0 0 0 CONNECT_api6.ipify.org:443_HTTP/1.1

Please look end of the log. Some outputs has correct headers, some has wrong headers. For example first log output has correct header, second output has wrong header. There is underscore between headers. This is causing 502 error for example:

	curl: (56) Received HTTP code 502 from proxy after CONNECT

I don't know what is the problem. May be this is a bug or may be I make mistake in config or may be I did wrong thing in centos 7 config for example ulimit settings etc..

In the second row of the log there is an error code: 00012 That means "12 - failed to bind()" (https://3proxy.ru/howtoe.asp#ERRORS) May be this helps to solve the problem.

Please can you help me. Thanks.

Edit: I'm using this version:
3proxy tiny proxy server 3proxy-0.8.13 (190801174904)

My config file:
	nserver 1.1.1.1
	nserver 1.0.0.1
	nscache 65535
	nscache6 65535
	daemon
	timeouts 1 5 30 60 180 1800 15 60
	log /var/log/3proxy/3proxy.log
	logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
	auth strong
	users emir:CL:secretpw
	allow *
	flush
	proxy -6 -n -a -p20000 -i178.238.239.13 -e2a02:c205:2018:9947:692b:b160:8724:30d9
	proxy -6 -n -a -p20001 -i178.238.239.13 -e2a02:c205:2018:9947:3683:3442:1ad2:44d7
	proxy -6 -n -a -p20002 -i178.238.239.13 -e2a02:c205:2018:9947:6add:2955:2bf0:9429
	proxy -6 -n -a -p20003 -i178.238.239.13 -e2a02:c205:2018:9947:e97a:2c48:d549:db20
	proxy -6 -n -a -p20004 -i178.238.239.13 -e2a02:c205:2018:9947:6da6:223b:f1f6:6a9f
	proxy -6 -n -a -p20005 -i178.238.239.13 -e2a02:c205:2018:9947:adf7:83e2:8956:f6bc
	proxy -6 -n -a -p20006 -i178.238.239.13 -e2a02:c205:2018:9947:f142:cc62:b21e:4844
	proxy -6 -n -a -p20007 -i178.238.239.13 -e2a02:c205:2018:9947:74b7:84b0:b0cb:5b6c
	proxy -6 -n -a -p20008 -i178.238.239.13 -e2a02:c205:2018:9947:2aaf:c932:80a1:941d
	proxy -6 -n -a -p20009 -i178.238.239.13 -e2a02:c205:2018:9947:dcc7:ecc9:4e21:eee3
	proxy -6 -n -a -p20010 -i178.238.239.13 -e2a02:c205:2018:9947:6853:679a:aaa9:66dd
	proxy -6 -n -a -p20011 -i178.238.239.13 -e2a02:c205:2018:9947:f223:693e:e4b5:b7a6
	proxy -6 -n -a -p20012 -i178.238.239.13 -e2a02:c205:2018:9947:b8de:2a79:e425:94e0
	proxy -6 -n -a -p20013 -i178.238.239.13 -e2a02:c205:2018:9947:bba7:5667:c4c0:7531
	proxy -6 -n -a -p20014 -i178.238.239.13 -e2a02:c205:2018:9947:f535:5d44:ce49:781c
	proxy -6 -n -a -p20015 -i178.238.239.13 -e2a02:c205:2018:9947:7bed:2721:1724:2065
	proxy -6 -n -a -p20016 -i178.238.239.13 -e2a02:c205:2018:9947:4dc4:3d88:87d0:1896
	proxy -6 -n -a -p20017 -i178.238.239.13 -e2a02:c205:2018:9947:d82a:ceda:2453:1cd2
	proxy -6 -n -a -p20018 -i178.238.239.13 -e2a02:c205:2018:9947:d61e:92bd:df78:8a8d
	proxy -6 -n -a -p20019 -i178.238.239.13 -e2a02:c205:2018:9947:9160:d283:3c1b:5ab7
	proxy -6 -n -a -p20020 -i178.238.239.13 -e2a02:c205:2018:9947:7a84:758a:dc78:c8b7
	proxy -6 -n -a -p20021 -i178.238.239.13 -e2a02:c205:2018:9947:2c90:2be3:74dc:abe5
	proxy -6 -n -a -p20022 -i178.238.239.13 -e2a02:c205:2018:9947:e62a:e57b:dd46:8b4d
	proxy -6 -n -a -p20023 -i178.238.239.13 -e2a02:c205:2018:9947:ec35:af42:9e66:3d44
	proxy -6 -n -a -p20024 -i178.238.239.13 -e2a02:c205:2018:9947:ca34:3bc7:79cf:2b28
	proxy -6 -n -a -p20025 -i178.238.239.13 -e2a02:c205:2018:9947:8455:b689:ccdb:b26f
	proxy -6 -n -a -p20026 -i178.238.239.13 -e2a02:c205:2018:9947:74c2:506c:d91e:2d84
	proxy -6 -n -a -p20027 -i178.238.239.13 -e2a02:c205:2018:9947:f48f:bf1e:d8ed:b186
	proxy -6 -n -a -p20028 -i178.238.239.13 -e2a02:c205:2018:9947:de1d:e51f:1554:9b7a
	proxy -6 -n -a -p20029 -i178.238.239.13 -e2a02:c205:2018:9947:d9d0:b81f:d1b7:b53b
	proxy -6 -n -a -p20030 -i178.238.239.13 -e2a02:c205:2018:9947:2cc1:55f0:eeae:3e56
	proxy -6 -n -a -p20031 -i178.238.239.13 -e2a02:c205:2018:9947:26aa:8bf9:183d:a861
	proxy -6 -n -a -p20032 -i178.238.239.13 -e2a02:c205:2018:9947:f385:c87c:c6c3:deed
	proxy -6 -n -a -p20033 -i178.238.239.13 -e2a02:c205:2018:9947:3c81:ec9a:2e6e:b4a0
	proxy -6 -n -a -p20034 -i178.238.239.13 -e2a02:c205:2018:9947:5957:8785:929b:a570
	proxy -6 -n -a -p20035 -i178.238.239.13 -e2a02:c205:2018:9947:b6f2:cd65:ec7a:4949
	proxy -6 -n -a -p20036 -i178.238.239.13 -e2a02:c205:2018:9947:4620:73f0:1ddf:aff2
	proxy -6 -n -a -p20037 -i178.238.239.13 -e2a02:c205:2018:9947:41c2:c8c2:9bd7:95ea
	proxy -6 -n -a -p20038 -i178.238.239.13 -e2a02:c205:2018:9947:a680:4f65:4e36:d63b
	proxy -6 -n -a -p20039 -i178.238.239.13 -e2a02:c205:2018:9947:20bf:32d8:8e27:e671
	proxy -6 -n -a -p20040 -i178.238.239.13 -e2a02:c205:2018:9947:d58b:9b63:773c:1c19
	proxy -6 -n -a -p20041 -i178.238.239.13 -e2a02:c205:2018:9947:a79c:bdb3:ec3e:4bcb
	proxy -6 -n -a -p20042 -i178.238.239.13 -e2a02:c205:2018:9947:cdca:a5f3:2ac4:9418
	proxy -6 -n -a -p20043 -i178.238.239.13 -e2a02:c205:2018:9947:8d1a:4fd8:42b1:3e6e
	proxy -6 -n -a -p20044 -i178.238.239.13 -e2a02:c205:2018:9947:6fe9:4570:c974:d8cf
	proxy -6 -n -a -p20045 -i178.238.239.13 -e2a02:c205:2018:9947:dc54:4539:f7cc:bd47
	proxy -6 -n -a -p20046 -i178.238.239.13 -e2a02:c205:2018:9947:4de6:bda4:b485:e26f
	proxy -6 -n -a -p20047 -i178.238.239.13 -e2a02:c205:2018:9947:cce9:3222:28cb:9b68
	proxy -6 -n -a -p20048 -i178.238.239.13 -e2a02:c205:2018:9947:5735:9e21:b51e:bbc4
	proxy -6 -n -a -p20049 -i178.238.239.13 -e2a02:c205:2018:9947:51e1:c646:ef34:3988
	proxy -6 -n -a -p20050 -i178.238.239.13 -e2a02:c205:2018:9947:f5ee:c1b4:ec6d:6b1d
	proxy -6 -n -a -p20051 -i178.238.239.13 -e2a02:c205:2018:9947:9baf:793b:6851:1b1b
	proxy -6 -n -a -p20052 -i178.238.239.13 -e2a02:c205:2018:9947:2dcb:e973:49d0:c9f0
	proxy -6 -n -a -p20053 -i178.238.239.13 -e2a02:c205:2018:9947:63aa:90bf:aba0:478b
	proxy -6 -n -a -p20054 -i178.238.239.13 -e2a02:c205:2018:9947:9a91:21dd:169b:acc0
	proxy -6 -n -a -p20055 -i178.238.239.13 -e2a02:c205:2018:9947:7ac6:b3a0:9086:ad82
	proxy -6 -n -a -p20056 -i178.238.239.13 -e2a02:c205:2018:9947:3671:ee9e:1e2f:3181
	proxy -6 -n -a -p20057 -i178.238.239.13 -e2a02:c205:2018:9947:37b3:e943:4ce1:50ae
	proxy -6 -n -a -p20058 -i178.238.239.13 -e2a02:c205:2018:9947:8126:9388:4c2e:58c0
	proxy -6 -n -a -p20059 -i178.238.239.13 -e2a02:c205:2018:9947:3c35:c218:7b87:7c57
	proxy -6 -n -a -p20060 -i178.238.239.13 -e2a02:c205:2018:9947:2376:1a92:6bd9:33a1
	proxy -6 -n -a -p20061 -i178.238.239.13 -e2a02:c205:2018:9947:7769:5476:1472:4a7c
	proxy -6 -n -a -p20062 -i178.238.239.13 -e2a02:c205:2018:9947:84e2:8540:8da6:ee43
	proxy -6 -n -a -p20063 -i178.238.239.13 -e2a02:c205:2018:9947:31cd:9e7c:71ce:4485
	proxy -6 -n -a -p20064 -i178.238.239.13 -e2a02:c205:2018:9947:6c27:b65c:e762:a0ea
	proxy -6 -n -a -p20065 -i178.238.239.13 -e2a02:c205:2018:9947:9571:f9c9:98c9:842a
	proxy -6 -n -a -p20066 -i178.238.239.13 -e2a02:c205:2018:9947:bc94:c4ad:b6e8:efb8
	proxy -6 -n -a -p20067 -i178.238.239.13 -e2a02:c205:2018:9947:1f8c:2c91:bd81:ce85
	proxy -6 -n -a -p20068 -i178.238.239.13 -e2a02:c205:2018:9947:567b:e350:4034:62ca
	proxy -6 -n -a -p20069 -i178.238.239.13 -e2a02:c205:2018:9947:24ce:2a86:1d47:1b55
	proxy -6 -n -a -p20070 -i178.238.239.13 -e2a02:c205:2018:9947:4250:e3ea:b399:e3f5
	proxy -6 -n -a -p20071 -i178.238.239.13 -e2a02:c205:2018:9947:3bd1:8271:be62:3148
	proxy -6 -n -a -p20072 -i178.238.239.13 -e2a02:c205:2018:9947:be29:8c56:bf50:d41d
	proxy -6 -n -a -p20073 -i178.238.239.13 -e2a02:c205:2018:9947:7266:8c7b:65a1:4945
	proxy -6 -n -a -p20074 -i178.238.239.13 -e2a02:c205:2018:9947:b47a:acaa:45b0:95c0
	proxy -6 -n -a -p20075 -i178.238.239.13 -e2a02:c205:2018:9947:8faa:4873:d573:b159
	proxy -6 -n -a -p20076 -i178.238.239.13 -e2a02:c205:2018:9947:6685:314a:6450:53f6
	proxy -6 -n -a -p20077 -i178.238.239.13 -e2a02:c205:2018:9947:22b8:8aac:887a:424a
	proxy -6 -n -a -p20078 -i178.238.239.13 -e2a02:c205:2018:9947:e049:159e:df74:438b
	proxy -6 -n -a -p20079 -i178.238.239.13 -e2a02:c205:2018:9947:766e:b748:56b7:b7a4
	proxy -6 -n -a -p20080 -i178.238.239.13 -e2a02:c205:2018:9947:463f:df94:b88e:9cb3
	proxy -6 -n -a -p20081 -i178.238.239.13 -e2a02:c205:2018:9947:399f:4058:b198:8ed1
	proxy -6 -n -a -p20082 -i178.238.239.13 -e2a02:c205:2018:9947:dd9a:f7c1:41f9:a37e
	proxy -6 -n -a -p20083 -i178.238.239.13 -e2a02:c205:2018:9947:1c88:a54d:3ed9:9339
	proxy -6 -n -a -p20084 -i178.238.239.13 -e2a02:c205:2018:9947:a168:28f4:54d0:2fd0
	proxy -6 -n -a -p20085 -i178.238.239.13 -e2a02:c205:2018:9947:f0c7:9d46:6f7d:9e48
	proxy -6 -n -a -p20086 -i178.238.239.13 -e2a02:c205:2018:9947:be73:2ecc:ecab:5487
	proxy -6 -n -a -p20087 -i178.238.239.13 -e2a02:c205:2018:9947:d5a2:15a0:5223:ac71
	proxy -6 -n -a -p20088 -i178.238.239.13 -e2a02:c205:2018:9947:7992:86a8:e5df:b3d9
	proxy -6 -n -a -p20089 -i178.238.239.13 -e2a02:c205:2018:9947:53e6:2832:f331:27b9
	proxy -6 -n -a -p20090 -i178.238.239.13 -e2a02:c205:2018:9947:b18e:e4cd:7c44:b93e
	proxy -6 -n -a -p20091 -i178.238.239.13 -e2a02:c205:2018:9947:2aee:beab:8875:6433
	proxy -6 -n -a -p20092 -i178.238.239.13 -e2a02:c205:2018:9947:f82b:cc26:f4cd:96e6
	proxy -6 -n -a -p20093 -i178.238.239.13 -e2a02:c205:2018:9947:84e2:ae22:b9a3:ec7c
	proxy -6 -n -a -p20094 -i178.238.239.13 -e2a02:c205:2018:9947:2fee:7c58:b8a2:bad4
	proxy -6 -n -a -p20095 -i178.238.239.13 -e2a02:c205:2018:9947:2ef6:a671:c2d2:344f
	proxy -6 -n -a -p20096 -i178.238.239.13 -e2a02:c205:2018:9947:7b44:ef8b:b2ee:bc67
	proxy -6 -n -a -p20097 -i178.238.239.13 -e2a02:c205:2018:9947:d934:be3b:ae27:bb7e
	proxy -6 -n -a -p20098 -i178.238.239.13 -e2a02:c205:2018:9947:3be0:3db9:2b3b:2873
	proxy -6 -n -a -p20099 -i178.238.239.13 -e2a02:c205:2018:9947:8971:9381:6128:6986
	proxy -6 -n -a -p20100 -i178.238.239.13 -e2a02:c205:2018:9947:e7c5:9825:349a:acd2

ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 47330
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by z3APA3A** [comment]
It means proxy fails to bind to specified external IP. Either IP is wrong or there is a lack of ephemeral ports or open files limit.
