### ISSUE TITLE
3proxy crash

### ISSUE THREAD

**Issue by atimofeev86** [z3APA3A/3proxy#453]
падает служба на centos.
вот такое в логе есть
Mar 30 18:41:11 proxy01 kernel: 3proxy[29771]: segfault at 0 ip 00007f04076bea1c sp 00007f026b01d6b0 error 4 in libc-2.28.so[7f040768f000+1b9000]
Mar 30 18:41:11 proxy01 kernel: Code: 00 00 8b 15 06 2d 39 00 41 54 49 89 fc 55 53 85 d2 75 63 31 db eb 0b 0f 1f 80 00 00 00 00 48 83 c3 01 89 dd 48 83 fb 06 74 f4 <49> 8b 34 dc 83 7e
30 ff 74 07 89 df e8 53 e5 ff ff 83 fd 0c 75 de
Mar 30 18:41:11 proxy01 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Mar 30 18:41:11 proxy01 systemd[1]: Started Process Core Dump (PID 29773/UID 0).
Mar 30 18:41:14 proxy01 systemd-coredump[29774]: Core file was truncated to 2147483648 bytes.
Mar 30 18:41:14 proxy01 systemd-coredump[29774]: Process 6359 (3proxy) of user 0 dumped core.#012#012Stack trace of thread 29771:#012#0  0x00007f04076bea1c n/a (n/a)
Mar 30 18:41:14 proxy01 systemd[1]: 3proxy.service: Main process exited, code=killed, status=11/SEGV
Mar 30 18:41:14 proxy01 systemd[1]: 3proxy.service: Failed with result 'signal'.

**Comment by z3APA3A** [comment]
А что в конфиге, что в stacksize?

https://3proxy.ru/faqr.asp#CRASH

**Comment by atimofeev86** [comment]
stacksize 8388608

**Comment by z3APA3A** [comment]
Версия 3proxy какая? Что в конфиге?

**Comment by atimofeev86** [comment]
0.8.13
Конфиг большой, там инклюдятся файлы. ODBC используется, stacksize 8388608

**Comment by atimofeev86** [comment]
Если ставлю stacksize 28388608 И отключаю логи то работает чуть-чуть стабильнее.

**Comment by z3APA3A** [comment]
Иши нормально работающий ODBC и коннектор, к сожалению, с ними все плохо. Найдешь - можешь отписаться.

**Comment by atimofeev86** [comment]
Странно, что 2 сервера работают стабильно, а 1 падает.
На том, что падает я отключил запись лога в базу и пишу в файл. 
Но там все равно падает служба когда конфиг обновляется через monitor.
![image](https://user-images.githubusercontent.com/41478386/81071322-3a04ae00-8eed-11ea-8171-e16efcc03c7f.png)

**Comment by z3APA3A** [comment]
https://3proxy.ru/highload.asp

**Comment by z3APA3A** [comment]
См. всего что касается лимитов и монитора и используй devel.
