### ISSUE TITLE
3Proxy on Windows Server 2012 R2 - Failed to create service: No error

### ISSUE THREAD

**Issue by eoksum** [z3APA3A/3proxy#455]
Hi there

I tried installing 3Proxy as service and enabling it on Windows Server 2012 64 bit (Shell as PowerShell) but I keep getting this error below:

PS C:\Users\Administrator\Desktop\3pro\bin64> .\3proxy.exe --install C:\Users\Administrator\Desktop\3pro\3proxy.cfg
Failed to create service: No error
PS C:\Users\Administrator\Desktop\3pro\bin64>

I need to use this as IPv6 proxy for my /32 range please help

Thank you

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqe.asp

> Q: Why doesn't 3proxy work as service under Windows?
> Possible reasons:
> 
>     there are relative paths in configuration file for included files, log files, etc. Always use absolute paths. For example $"c:\3proxy\networks.local" instead of $networks.local. For debugging remove 'service' and 'daemon', log to stdout an try to execute 3proxy from command line from some different directory (for example from disk root).
>     SYSTEM account doesn't have access to executable file, configuration files, log files, etc.
>     configuration files is not located in default path (3proxy.cfg in same location with 3proxy.exe). For alternative configuration file location use
> 
>     3proxy --install full_path_to_configuration_file
> 
>     user has no rights to install or start service
>     service is already installed and/or started 

Service can not access C:\Users\Administrator

**Comment by unoexperto** [comment]
I have same problem folks. I tried it on Win 7 and Win 10. What am I missing ?

```
C:\Program Files (x86)\3proxy\bin64>3proxy --install "C:\Program Files (x86)\3proxy\bin64\3proxy.cfg"
Failed to create service: No error
```

**Comment by z3APA3A** [comment]
There are few possible reason:
1. You are not using elevated privileges. Run 3proxy --install from command prompt with elevated privileges.
2. 3proxy service is alreadt installed

**Comment by DevilLord41** [comment]
Hi, im still getting same error
![image](https://user-images.githubusercontent.com/7568004/235334022-c39f91f4-3c37-45d2-8060-5815fd02dc6a.png)

**Comment by z3APA3A** [comment]
probably you have no config file (3proxy.cfg) in the current directory, specify full path to config
