### ISSUE TITLE
WEBRTC

### ISSUE THREAD

**Issue by kharvispektr23** [z3APA3A/3proxy#456]
Здравствуйте, необходима полная анонимность, т.е. реальная утечка через WEBRTC внешнего айпи прокси.
Ситуация схожа с этим вопросом:
https://github.com/z3APA3A/3proxy/issues/362
 т.е трафик идет через виртуальный адаптер. У меня были покупные socks 5 прокси, и подключая их через программу утекает webrtc нормально, но когда я сам настраиваю socks 5 через 3proxy айпи, так же как и в вопросе выше пустой (не определяется).
Конфиг:
socks -p3128

Есть какие либо гайды как в 3proxy сделать, чтобы webrtc перезаписывался?

**Comment by z3APA3A** [comment]
Вопрос не имеет отношения к прокси, адрес в таком случае утекает через сам протокол, а не от прокси-сервера. Если есть разница в поведении, значит есть разница в интеграции, например ты где-то используешь UDP через прокси, а где-то нет.

**Comment by kharvispektr23** [comment]
> 
> 
> Вопрос не имеет отношения к прокси, адрес в таком случае утекает через сам протокол, а не от прокси-сервера. Если есть разница в поведении, значит есть разница в интеграции, например ты где-то используешь UDP через прокси, а где-то нет.

как понять утекает через протокол? У меня стоит виртуальный интернет адаптер, который перенаправляет любой запрос на прокси, в настройках меняю только адрес прокси - у покупных все нормально, у поднятых мной адрес не утекает. Что это, как не проблема в настройке прокси?
