### ISSUE TITLE
Проблема с загрузкой фото

### ISSUE THREAD

**Issue by nsimanskij** [z3APA3A/3proxy#457]
Добрый день. Уже 4 месяца мучаюсь с тем что при работе с Ebay, у многих из моих коллег возникает ошибка загрузок фото. Tоесть человек пытается в Ebay закинуть новый товар на продажу, делает его описание и дальше заружает фото товара из интернета или ПК. Не важно или подключение идёт через http или socks, но загрузка фото тупо зависает. Если использовать openvpn, то тогда таких проблем не возникает. Скажу сразу, переход на openvpn не вариант  так как есть такие, у которых скорость интернета 5-10 mbps. Это коллеги из Бангладеша и Филипин. Но в основном у многих интернет очень хороший, пэтому проблему из-за скорости сразу можно откинуть в сторонку

Пробовали менять браузеры, OS, отключать все дополнения Chrome, работать через proxifier,  менять MTU значение, итд, но всё безрезультатно. Есть один нюанс что из-за простоты и удобства, многие изначально работуют через http прокси который прописывают в windows настройках, а когда возникают проблемы с загрузкой, переходят на socks и работают через proxifier и тогда всё работает. Но есть у некоторых что и после перехода на socks, вcё равно ничего не работает. Сильно не ругайте, я в логах не особо разбираюсь, но скину сюда логи 2 разых людей, может кто поможет разобраться. За решение проблемы готов заплатить

[logi.zip](https://github.com/z3APA3A/3proxy/files/4455885/logi.zip)

**Comment by z3APA3A** [comment]
По описанию, это типичная проблема MTU. Как именно и где ты пытался менять значение MTU?

**Comment by nsimanskij** [comment]
sudo ifconfig eth0 mtu xxxx

**Comment by z3APA3A** [comment]
И? Где находится этот eth0, кто к нему коннектится/кчему он коннектится  и чему равен xxxx?

**Comment by nsimanskij** [comment]
Это был как пример на ответ на твой вопрос.  Я смотрю через ifconfig через какой сетевой интерфейс идёт связь и тогда менял значение МТУ на нём. Везде по умолянию 1500. Менял на 1400, 1450, 1300 итд. Или я чего не понимаю и не то меняю что нада?
![ifconf](https://user-images.githubusercontent.com/37158032/79041364-f5d90300-7bf7-11ea-90fe-7f8ebfcf4b0b.JPG)
