### ISSUE TITLE
UDP Parent Proxy Support

### ISSUE THREAD

**Issue by john-d13** [z3APA3A/3proxy#458]
Hello,

Will 3proxy ever be supporting UDP Packet forwarding to Parent Proxy?  I see some discussion in the enhancements but no info in the release notes

Forward incoming UDP packet via 3proxy udppm local listener to Parent SOCKS3 proxy

allow *
parent 1000 socks5 50.239.143.238 1700 xxx xxx
maxconn 2000
udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111
flush

**Comment by z3APA3A** [comment]
Duplicate for https://github.com/z3APA3A/3proxy/issues/55

**Comment by john-d13** [comment]
Hello VladimirJust following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? Sample config allow *parent 1000 socks5 50.239.143.238 1700 xxx xxxmaxconn 2000udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111flushI will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. Sent from my Galaxy
-------- Original message --------From: Vladimir Dubrovin <notifications@github.com> Date: 2020-11-17  6:27 p.m.  (GMT-05:00) To: z3APA3A/3proxy <3proxy@noreply.github.com> Cc: john-d13 <giancarlo@dnsflex.com>, Author <author@noreply.github.com> Subject: Re: [z3APA3A/3proxy] UDP Parent Proxy Support (#458) 
Closed #458.

**Comment by john-d13** [comment]
hi I am willing to pay for this feature.  Please advise. 
  
  
   
    On 02/08/2021 10:14 PM Giancarlo D <giancarlo@dnsflex.com> wrote:
   
   
    
   
   
    
   
   
    Hello Vladimir
   
   
    
   
   
    Just following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? 
   
   
    
   
   
    Sample config 
   
   
    
   
   
    allow *
    parent 1000 socks5 50.239.143.238 1700 xxx xxx
    maxconn 2000
    udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111
    flush
   
   
    
   
   
    I will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. 
   
   
    
   
   
    
   
   
    
     Sent from my Galaxy
    
   
   
    
   Hello VladimirJust following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? Sample config allow *parent 1000 socks5 50.239.143.238 1700 xxx xxxmaxconn 2000udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111flushI will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. Sent from my Galaxy
   
    
     -------- Original message --------
    
    
     From: Vladimir Dubrovin <notifications@github.com>
    
    
     Date: 2020-11-17 6:27 p.m. (GMT-05:00)
    
    
     To: z3APA3A/3proxy <3proxy@noreply.github.com>
    
    
     Cc: john-d13 <giancarlo@dnsflex.com>, Author <author@noreply.github.com>
    
    
     Subject: Re: [z3APA3A/3proxy] UDP Parent Proxy Support (#458)
    
    
     
    
   
   
   Closed #458.

**Comment by john-d13** [comment]
Hello? Sent from my Galaxy
-------- Original message --------From: Giancarlo DiNardo <giancarlo@dnsflex.com> Date: 2021-02-10  2:16 p.m.  (GMT-05:00) To: z3APA3A/3proxy <reply@reply.github.com>, z3APA3A/3proxy <3proxy@noreply.github.com> Cc: Author <author@noreply.github.com> Subject: Re: [z3APA3A/3proxy] UDP Parent Proxy Support (#458) 
  
   hi I am willing to pay for this feature.  Please advise. 
  
  
   
    On 02/08/2021 10:14 PM Giancarlo D <giancarlo@dnsflex.com> wrote:
   
   
    
   
   
    
   
   
    Hello Vladimir
   
   
    
   
   
    Just following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? 
   
   
    
   
   
    Sample config 
   
   
    
   
   
    allow *
    parent 1000 socks5 50.239.143.238 1700 xxx xxx
    maxconn 2000
    udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111
    flush
   
   
    
   
   
    I will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. 
   
   
    
   
   
    
   
   
    
     Sent from my Galaxy
    
   
   
    
   Hello VladimirJust following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? Sample config allow *parent 1000 socks5 50.239.143.238 1700 xxx xxxmaxconn 2000udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111flushI will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. Sent from my Galaxy
   
    
     -------- Original message --------
    
    
     From: Vladimir Dubrovin <notifications@github.com>
    
    
     Date: 2020-11-17 6:27 p.m. (GMT-05:00)
    
    
     To: z3APA3A/3proxy <3proxy@noreply.github.com>
    
    
     Cc: john-d13 <giancarlo@dnsflex.com>, Author <author@noreply.github.com>
    
    
     Subject: Re: [z3APA3A/3proxy] UDP Parent Proxy Support (#458)
    
    
     
    
   
   
   Closed #458.

**Comment by john-d13** [comment]
+Lubomir

  
   hi I am willing to pay for this feature.  Please advise. 
  
  
   
    On 02/08/2021 10:14 PM Giancarlo D <giancarlo@dnsflex.com> wrote:
   
   
    
   
   
    
   
   
    Hello Vladimir
   
   
    
   
   
    Just following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? 
   
   
    
   
   
    Sample config 
   
   
    
   
   
    allow *
    parent 1000 socks5 50.239.143.238 1700 xxx xxx
    maxconn 2000
    udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111
    flush
   
   
    
   
   
    I will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. 
   
   
    
   
   
    
   
   
    
     Sent from my Galaxy
    
   
   
    
   Hello VladimirJust following up on this query. Does 3roxy support udppm port map forwarding to parent socks5 / http proxy? Sample config allow *parent 1000 socks5 50.239.143.238 1700 xxx xxxmaxconn 2000udppm -s0 -i0.0.0.0 10001 127.0.0.1 11111flushI will create prerouting iptables rule to redirect all udp packet to 3proxy udppm local listener the. 3proxy to route to parent proxy via socks5 or http. Sent from my Galaxy
   
    
     -------- Original message --------
    
    
     From: Vladimir Dubrovin <notifications@github.com>
    
    
     Date: 2020-11-17 6:27 p.m. (GMT-05:00)
    
    
     To: z3APA3A/3proxy <3proxy@noreply.github.com>
    
    
     Cc: john-d13 <giancarlo@dnsflex.com>, Author <author@noreply.github.com>
    
    
     Subject: Re: [z3APA3A/3proxy] UDP Parent Proxy Support (#458)
    
    
     
    
   
   
   Closed #458.

**Comment by phantomcraft** [comment]
This program supports UDP parent proxy: https://github.com/nadoo/glider

**Comment by john-d13** [comment]
Thanks for sharing!  Only problem I have with glider is looks like there is only one global listener port. I wrote code with 3proxy schema having the ability to configure multiple listener/parent proxy groups within same config file.

**Comment by john-d13** [comment]
@z3APA3A 

Can you confirm in fact this is duplicate of #55

In that feature request you say proxy to parent UDP Proxy but in my case the flow is as such:

IPTABLES Chain:   PREROUTING -p udp -s 0/0 --dports 12345

IPTABLES -> udp:0.0.0.0:12345 (this is uddpm listener) -> socks5h://{external:3345}

External is another 3proxy server listening on socks interface accepting incoming connections.  So I can port forwarding incoming UDP to parent SOCKS5 proxy.

My company is looking to implement this asap and can help fund your new release to expedite the feature.   We use this to support gameserver proxy.

**Comment by z3APA3A** [comment]
Yes, support for UDP via parent proxy is a duplicate of #55.

**Comment by john-d13** [comment]
Good,  do you have ETA or dev release for testing?
