### ISSUE TITLE
Limit trafic and others

### ISSUE THREAD

**Issue by Marek521** [z3APA3A/3proxy#459]
I wish to limit number of connection/threads on each proxy I have in config file.
Lets asume that my config file looks like this:

auth iponly
include /conf/3460_3711
allow * 1.1.1.1,2.2.2.2,3.3.3.3
parent 1000 http 11.11.11.11 20000
proxy -n -a -p10003
flush

auth iponly
include /conf/3460_3711
allow * 1.1.1.1,2.2.2.2,3.3.3.3
parent 1000 http 11.11.11.11 20001
proxy -n -a -p10004
flush

auth iponly
include /conf/3460_3711
allow * 1.1.1.1,2.2.2.2,3.3.3.3
parent 1000 http 11.11.11.11 20002
proxy -n -a -p10005
flush

So I have set up 3 different ptoxies and I want each proxy have different connection limit per second.
Can someone please show me sample entry I have to put in my config file, to for example limit 
first proxy to 5 connections/s second to 10 connections/s and third one let's 15 connections/s

**Comment by z3APA3A** [comment]
Set `connlim` based on the same rules you use to distribute traffic between proxies.

**Comment by Marek521** [comment]
Hello

So I think I do something wrong.
I try to write this rule as this example:

connlim <rate> <period> <userlist> _________<sourcelist> ___________<targetlist>___<targetportlist>

connlim ___5______ 1__________ *_________1.1.1.1,2.2.2.2,3.3.3.3 ________11.11.11.11_______20000

but still see many many more connections to this proxy than 5 in one second.
How should it look like then?

**Comment by z3APA3A** [comment]
this limit only affects connections from 1.1.1.1,2.2.2.2,3.3.3.3 to 11.11.11.11:2000 (where 11.11.11.11:2000 is IP:port requested by client, not IP:port you are redirecting to)
