### ISSUE TITLE
ldap auth

### ISSUE THREAD

**Issue by myworking82** [z3APA3A/3proxy#46]
Добрый день. При сборке с поддержкой LDAP вылазит следующее:

`gcc -o ../../PCREPlugin.ld.so -O2 -pthread -shared pcre_compile.o pcre_config.o pcre_dfa_exec.o pcre_exec.o pcre_fullinfo.o pcre_get.o pcre_globals.o pcre_info.o pcre_maketables.o pcre_newline.o pcre_ord2utf8.o pcre_refcount.o pcre_study.o pcre_tables.o pcre_try_flipped.o pcre_ucp_searchfuncs.o pcre_valid_utf8.o pcre_version.o pcre_xclass.o pcre_dftables.o pcre_plugin.o pcreposix.o
make[2]: Leaving directory '/usr/src/devel/src/plugins/PCREPlugin'
make[2]: Entering directory '/usr/src/devel/src/plugins/TransparentPlugin'
gcc -fpic -g -O2 -c -pthread -DGETHOSTBYNAME_R -D_THREAD_SAFE -D_REENTRANT -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL transparent_plugin.c
gcc -o ../../TransparentPlugin.ld.so -O2 -pthread -shared transparent_plugin.o
make[2]: Leaving directory '/usr/src/devel/src/plugins/TransparentPlugin'
make[2]: Entering directory '/usr/src/devel/src/plugins/PamAuth'
gcc -fpic -g -O2 -c -pthread -DGETHOSTBYNAME_R -D_THREAD_SAFE -D_REENTRANT -DNOODBC -DWITH_STD_MALLOC -DFD_SETSIZE=4096 -DWITH_POLL pamauth.c
gcc -o ../../pamauth.ld.so -O2 -pthread -shared -lpam pamauth.o
make[2]: Leaving directory '/usr/src/devel/src/plugins/PamAuth'
make[2]: Entering directory '/usr/src/devel/src/plugins/LdapPlugin'
Makefile.var:33: Makefile.inc: No such file or directory
make[2]: *** No rule to make target 'Makefile.inc'.  Stop.
make[2]: Leaving directory '/usr/src/devel/src/plugins/LdapPlugin'
make[1]: Leaving directory '/usr/src/devel/src'`

влез один раз относительно путей так это повлекло еще больше проблем с сборкой, такой результат на дев и мастер ветках, подскажите может я что не так делаю!!!!!

**Comment by z3APA3A** [comment]
Там в ldapauth.txt написано как собирать, это неподдерживаемый плагин. 
Я попробовал сделать нужные Makefile'ы но нет возможности проверить. Попробуй с этим коммитом:
https://github.com/z3APA3A/3proxy/commit/57f11407346282c8976466e18143528c329b8a9f
отпишись о результатах.

**Comment by z3APA3A** [comment]
Должно быть пофикшено в 0.8.4.
