### ISSUE TITLE
IPv6 Only Proxy

### ISSUE THREAD

**Issue by vanitysys28** [z3APA3A/3proxy#460]
I'm playing with 3proxy at the moment and whatever I do, I don't manage to make an IPv6 only proxy.

Here is my config file

daemon
pidfile /home/joke/proxy/3proxy.pid
nserver 2001:4860:4860:0:0:0:0:8888
nserver 2001:4860:4860:0:0:0:0:8844
nscache6 65536
users tester:CL:1234
timeouts 1 5 30 60 180 1800 16 60
log /home/joke/proxy/logs/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 3
auth none
flush
allow tester
socks -p3128
proxy -6 -n -a -p8080 -i157.245.82.149 -e2604:a880:400:d0::1765:1

I manage to connect to the proxy all good, but the displayed IP on IP checking website is always the IPv4 IP.

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by z3APA3A** [comment]
It's unrelated, but read this doc, or it will be your next question

https://3proxy.ru/faqe.asp

Q: Why restrictions (redirections, limits, etc) do not work?
A: Most probable reasons: 'auth none' or no auth is used. For any ACL based feature one of 'iponly', 'nbname' or 'strong' auths required. Sequence of commands may be invalid. Commands are executed one-by-one and 'proxy', 'tcppm', 'socks' or another service commands must follow valid configuration. Invalid sequence of ACLs. First matching ACL is used (except of internal redirections, see below). If ACL contains at least one records last record is assumed to be 'deny *'.

**Comment by vanitysys28** [comment]
Here are the logs

`SOCK5.1080 00000 tester 141.8.122.44:57512 104.26.14.174:443 816 1073 0 CONNECT 104.26.14.174:443
SOCK4.1080 00000 - 204.12.234.34:58351 172.226.108.124:443 5114 5482 0 CONNECT 172.226.108.124:443
SOCK4.1080 00000 - 185.244.217.37:64431 146.20.147.247:993 552 5408 0 CONNECT 146.20.147.247:993
SOCK4.1080 00000 - 204.12.234.34:58375 172.226.108.124:443 5119 5482 0 CONNECT 172.226.108.124:443
SOCK5.1080 00000 - 141.98.252.164:65178 81.19.78.86:443 899 8120 0 CONNECT mail.rambler.ru:443
SOCK4.1080 00000 - 204.12.234.34:58380 172.226.108.124:443 5114 5499 0 CONNECT 172.226.108.124:443
SOCK4.1080 00000 - 185.244.217.37:49704 217.146.190.234:993 406 14783 0 CONNECT 217.146.190.234:993
SOCK4.1080 00000 - 190.2.134.46:54334 52.223.198.11:443 1291 3477 0 CONNECT 52.223.198.11:443
SOCK4.1080 00000 - 204.12.234.34:58413 172.226.108.124:443 5117 5482 0 CONNECT 172.226.108.124:443
SOCK4.1080 00000 - 204.12.234.34:58409 172.226.108.124:443 5125 5499 0 CONNECT 172.226.108.124:443
`

**Comment by vanitysys28** [comment]
Alright, I think problem comes from the Docker container I'm using.
For some reason, config isn't being taken into account.

Tried playing with the auth and saw it wasn't not being applied.
Any good github repository for 3proxy with docker support?

**Comment by vanitysys28** [comment]
Tried with a new docker configuration.
Here is what I get now:

1586796489820 L1586796489.820 SOCKS.1080 00000 - 104.248.114.118:1080 2604:a880:400:d1::9d6:c001:0 0 0 0 bind(): Address not available
1586796491420 L1586796491.420 SOCKS.1080 00000 - 104.248.114.118:1080 2604:a880:400:d1::9d6:c001:0 0 0 0 bind(): Address not available
1586796494620 L1586796494.620 SOCKS.1080 00000 - 104.248.114.118:1080 2604:a880:400:d1::9d6:c001:0 0 0 0 bind(): Address not available
1586796501020 L1586796501.020 SOCKS.1080 00000 - 104.248.114.118:1080 2604:a880:400:d1::9d6:c001:0 0 0 0 bind(): Address not available
1586796513820 L1586796513.820 SOCKS.1080 00000 - 104.248.114.118:1080 2604:a880:400:d1::9d6:c001:0 0 0 0 bind(): Address not available

**Comment by vanitysys28** [comment]
Here are logs, config file and ifconfig return

<img width="1009" alt="Capture d’écran 2020-04-13 à 18 56 30" src="https://user-images.githubusercontent.com/20629483/79141178-8a3e9380-7db9-11ea-910c-784cd478d2cc.png">
<img width="482" alt="Capture d’écran 2020-04-13 à 19 03 18" src="https://user-images.githubusercontent.com/20629483/79141185-8e6ab100-7db9-11ea-880e-72ac62fccbbd.png">
<img width="610" alt="Capture d’écran 2020-04-13 à 18 57 04" src="https://user-images.githubusercontent.com/20629483/79141191-9296ce80-7db9-11ea-9cec-1a4e1283bb01.png">

**Comment by vanitysys28** [comment]
Decided to stop trying to do it through docker as enabling IPv6 on docker-compose is quite hard with new version. Installed it on bare metal, directly on a  test server without docker.

Ping6 works in the server, but for some reason, I can't reach a website after trying to connect to proxy. Here is ifconfig, log and 3proxy.cfg

<img width="598" alt="Capture d’écran 2020-04-14 à 00 13 44" src="https://user-images.githubusercontent.com/20629483/79166355-43669300-7de5-11ea-8e83-7aa28db98b47.png">
<img width="1028" alt="Capture d’écran 2020-04-14 à 00 13 26" src="https://user-images.githubusercontent.com/20629483/79166363-45305680-7de5-11ea-9076-dde451f640ba.png">
<img width="544" alt="Capture d’écran 2020-04-14 à 00 15 06" src="https://user-images.githubusercontent.com/20629483/79166367-46fa1a00-7de5-11ea-98b4-5a74aaf2de99.png">

**Comment by z3APA3A** [comment]
> what do you have in logs?

**Comment by z3APA3A** [comment]
P.S. browsers do not support username/password authentication for SOCKS, use 'proxy'.

**Comment by vanitysys28** [comment]
This is the only line I have in my logs
`1586850869. L1586850869.526 PROXY.1080 00000 - 161.35.9.91:1080 2604:a880:400:d0::191f:7001:0 0 0 0 Accepting connections [20155/2939959040]
`

**Comment by z3APA3A** [comment]
It means proxy ip:port was not available to client. Check firewalls and network issue.

**Comment by vanitysys28** [comment]
Firewall is disabled and I'm able to ping6 google.com
No idea where it might come from.
Any idea what file I need to have a look to?

**Comment by z3APA3A** [comment]
Try to telnet/nc to
161.35.9.91:1080
from local host and remote host. If it's accessible from local host and not accessible from remote host it's _definitely_ network or firewall issue.

**Comment by vanitysys28** [comment]
Fixed the issue.
Had to add an IPv4 nserver in my config.
Thanks for your help

**Comment by z3APA3A** [comment]
address for IPv6 nameserver must be in [], because 3proxy allows to specify port is addition to address. But for this case you should have an error with 00100 code in logs.

**Comment by proxybroficial** [comment]
Does the 3proxy.cfg file have any character limits?
I generated 3 thousand proxies and I restarted 3proxy, the same operating normally but all proxies without connection, when I reduced the amount removing some lines, and I restarted it came back to connect.

So my doubt is, how many proxies can I put in 3proxy.cfg?

**Comment by andersonpfx** [comment]
Does the 3proxy.cfg file have any character limits?
I generated 3 thousand proxies and I restarted 3proxy, the same operating normally but all proxies without connection, when I reduced the amount removing some lines, and I restarted it came back to connect.

So my doubt is, how many proxies can I put in 3proxy.cfg?

**Comment by z3APA3A** [comment]
there is no limit for the number of lines in the config, probably you have sdome over limitation, e.g. open descriptors, see
https://3proxy.ru/highload.asp

**Comment by andersonpfx** [comment]
I managed to make the ipv6 proxy work, Thanks! but it does not return the ipv4 that is used as a tunnel on any site, unlike Squid.

Is there any configuration that allows 3proxy to work ipv6 on sites that accept it and other sites that only accept ipv4, return ipv4 from the server?

**Comment by z3APA3A** [comment]
socks -64

**Comment by andersonpfx** [comment]
thanks

**Comment by andersonpfx** [comment]
Print: https://prnt.sc/NMLRI_rbeZw6
today i am facing an intermittent problem with 3proxy
when opening any site, in the print example of facebook, it gives this error, then if you refresh the page 2 or 3 times it opens the site normally.
it is configured for http -64 proxy with ipv6.

it was normal for 5 days, today it started to show this problem.

**Comment by z3APA3A** [comment]
check the logs, may be you have reached maxconn limit, or some resources limit. see 3proxy.ru/highload.asp

**Comment by andersonpfx** [comment]
The server was with low consumption, not even reaching 10% of CPU and memory.

Does maxconn limit the number of simultaneous connections on each proxy/port, right?
For example a proxy can only be connected to 1 computer at a time, you can't have 2 computers connected to the proxy if maxconn is set to 1 ?

**Comment by z3APA3A** [comment]
Single client can create multiple connections to proxy, for example active web browsing may require ~10 connections at some moment. maxconn limits common number of connections to single service, e.g. 'proxy' or 'socks'. See `connlim` command to limit connections and or connection rate per client.

**Comment by SamaelAryan** [comment]
Unable to setup this server in CentOS 9
Need Help
