### ISSUE TITLE
proxy don't disconnect

### ISSUE THREAD

**Issue by Thomanphan** [z3APA3A/3proxy#461]
Hello
is possible update 3proxy.cfg but current proxy no disconnect ? or don't need restart 3proxy service ?
Thank

**Comment by z3APA3A** [comment]
Yes, you can use http request via 'admin', 'monitor' command, SUGUSR1 under *nix or net pause/net continue under Windows, see
https://3proxy.ru/doc/man8/3proxy.8.html

**Comment by Thomanphan** [comment]
yes I used 
monitor /etc/3proxy.cfg
but don't working , can you guide me , my server used centos 
THank

**Comment by z3APA3A** [comment]
'monitor' requires valid path to configuration.
Also 'config' may be required if proxy executed in chroot environment.
