### ISSUE TITLE
setgid

### ISSUE THREAD

**Issue by azatka** [z3APA3A/3proxy#462]
Привет, запускаю так
sudo 3proxy /etc/3proxy/3proxy.cfg

user@proxy:~/3proxy/cfg$ /conf/passwd: No such file or directory
/conf/passwd: No such file or directory
Parse error line 12
Command: 'include' failed with code 21, line 12

**Comment by z3APA3A** [comment]
В стандартной поставке 3proxy использует chroot и сброс привилегий, стартовый конфиг делает chroot, сбрасывает привилегии и дальше уже запускает chroot-конифиг, который работает внутри ограниченной среды. Ты сразу пытаешься запустить 3proxy с chroot-конфигом.
