### ISSUE TITLE
Compilation if  not successful with machine:x64

### ISSUE THREAD

**Issue by maryXielee** [z3APA3A/3proxy#464]
hi, I compile 3proxy with Visual C++ using makefile.msvc64，but it is unsuccessful. It occurs error: 'LNK1112'  :The module computer type "X86" conflicts with the target computer type "x64", could you tell me why? thank you
![image](https://user-images.githubusercontent.com/31302424/79946523-c1403380-84a2-11ea-9e8a-7730d18890df.png)

**Comment by z3APA3A** [comment]
Do `make clean` and try again. 3proxy.obj was built for x86
