### ISSUE TITLE
При мониторе крэшится 3proxy сервис

### ISSUE THREAD

**Issue by altrof** [z3APA3A/3proxy#465]
Здравствуйте, 
появилась необходимость изменения external IP по запросу из веба. Юзер делает реквест из веба и нужный external записывается в текстовый файл. Чтобы 3proxy видел изменения в файле реализовал все через monitor. Все работает как нужно, но сервис 3proxy крэшится по 5 раз в день при таком решении (видимо, когда несколько текстовых файлов изменяются в один момент по реквесту из веба). Windows OS, конфиг такой:

monitor C:\3proxy\bin\3proxy.cfg

monitor C:\3proxy\user1\external_IP1.txt
monitor C:\3proxy\user1\external_IP2.txt

monitor C:\3proxy\user2\external_IP1.txt
monitor C:\3proxy\user2\external_IP2.txt

nscache 65536
timeouts 1 5 30 60 180 1800 15 60

internal 1.2.3.4

auth cache strong
users user1:CL:user1
allow user1

proxy -n -a -p15001 -e$"c:\3proxy\user1\external_IP1.txt"
proxy -n -a -p15002 -e$"c:\3proxy\user1\external_IP2.txt"
flush

auth cache strong
users user2:CL:user2
allow user2

proxy -n -a -p15003 -e$"c:\3proxy\user2\external_IP1.txt"
proxy -n -a -p15004 -e$"c:\3proxy\user2\external_IP2.txt"
flush

**Comment by z3APA3A** [comment]
Не надо в monitor запихивать файл конфигурации, если он генерируется. Здесь описано как надо:
https://3proxy.ru/highload.asp
