### ISSUE TITLE
Compilation is still not successful

### ISSUE THREAD

**Issue by maryXielee** [z3APA3A/3proxy#466]
Do `make clean` and try again. 3proxy.obj was built for x86, probably you have not cleaned it after previous build.

_Originally posted by @z3APA3A in https://github.com/z3APA3A/3proxy/issues/464#issuecomment-617639155_

I download the code and then immediately compile to 64 bits, but it still comes up. Do I need to change anything after downloading the code?

**Comment by z3APA3A** [comment]
Sorry, but I have nothing to add, check your building environment. Try to remove all object files manually, make sure to call vcvars64.bat before building (e.g. ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat```). Currently, 3proxy.obj file is created with ```cl``` in x86 environment.
