### ISSUE TITLE
internal=external inreface/address ?

### ISSUE THREAD

**Issue by IvankoB** [z3APA3A/3proxy#47]
Не могу нащупать настройки 3proxy, при которых можно подключиться через некий интерфейс и далее выполнять через него внешние запросы и через него же возвращать результаты клиенту. Все время получаю SOCK5 error 2 (not allowed by ruleset) на клиенте (установлена прога ProxyCap)

Сценарий: пользование быстрым рабочим анлимом из дома через SOCK5-прокси, установленный на рутере на работе. В моем месте проживания местный (от дома до рабочего прокси) интернет - высоко-скоростной и вообще бесплатный.
Другие прокси (dante, ss5) в этом режиме работают с пол-пинка. Но эти прокси слегка глючноватые - поэтому ищу альтернативу.

**Comment by z3APA3A** [comment]
auth iponly
socks -iIP -eIP

**Comment by z3APA3A** [comment]
Но судя по ошибке у тебя логин с паролем не прописаны для прокси. Если соксификатор не дает их прописать, попробуй добавить опцию -u2 к socks

**Comment by IvankoB** [comment]
у тебя логин с паролем не прописаны для прокси
================
Прописан. На несовпадающих интерфейсах все работает нормально.

socks -iIP -eIP
================
Пробовал в 1-ю очередь. Не помогло.

-u2
================
Что она делает ? (спрашиваю потому что пока откатился на глючноватый ДАНТЕ)

**Comment by IvankoB** [comment]
И да, прога для проксирования - ProxyCap (от ProxyLabs). Именно она логинится нормально, но траффик не пускает.

**Comment by IvankoB** [comment]
Еще важный момент - INTERNAL & EXTERNAL оба 0.0.0.0 (так как ADSL-коннект поднимаетcя после старта "3proxy").  Хотя коннект призязывается к фиксированному IP-адресу на стороне провайдера.
DANTE  в этом режиме вообще кошмарно глючит (пришлось запускать его по CRONTABу после устанвления ADSL-коннекта) - поэтому надеюсь что 3proхy поумнее на PPPOE-коннектах.

**Comment by z3APA3A** [comment]
Что в логах? Что в конфиге?

**Comment by IvankoB** [comment]
Последний конфиг  (поубирал все лимиты кроме "AUTH STRONG"):
--------------------

daemon
external 0.0.0.0
internal 0.0.0.0
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30
nserver localhost
nserver 8.8.8.8
nscache 65536
users "vanosock:CR:<MD5>" 
auth strong
flush
allow username
maxconn 16384
# коннекты из локалки
socks -p<sock_port>
# коннекты из дома
socks -p<sock_port> -i<extIP> -e<extIP>

===========================================================
А вот кусок лога :
--------------------

1456848118.636 SOCKS.3381 00000 - 0.0.0.0:3381 0.0.0.0:0 0 0 0 Accepting_connections_[17738/3078208320]
1456848128.288 SOCK5.3381 00003 vanosock 213.230.78.17:27788 46.101.193.235:80 0 0 0 CONNECT_topdownloads.ru:80
1456848128.815 SOCK5.3381 00003 vanosock 213.230.78.17:38123 93.158.134.3:80 0 0 0 CONNECT_ya.ru:80
1456848129.169 SOCK5.3381 00003 vanosock 213.230.78.17:62862 93.158.134.3:80 0 0 0 CONNECT_www.ya.ru:80
1456848135.520 SOCK5.3381 00003 vanosock 213.230.78.17:39684 93.158.134.3:80 0 0 0 CONNECT_ya.ru:80
1456848135.829 SOCK5.3381 00003 vanosock 213.230.78.17:37463 93.158.134.3:80 0 0 0 CONNECT_www.ya.ru:80
1456848139.284 SOCK5.3381 00003 vanosock 213.230.78.17:42638 46.101.193.235:80 0 0 0 CONNECT_topdownloads.ru:80
1456848150.288 SOCK5.3381 00003 vanosock 213.230.78.17:26546 46.101.193.235:80 0 0 0 CONNECT_topdownloads.ru:80
1456848161.289 SOCK5.3381 00003 vanosock 213.230.78.17:35482 46.101.193.235:80 0 0 0 CONNECT_topdownloads.ru:80
1456848168.858 SOCK5.3381 00003 vanosock 213.230.78.17:14264 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848169.147 SOCK5.3381 00003 vanosock 213.230.78.17:27610 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848169.441 SOCK5.3381 00003 vanosock 213.230.78.17:59375 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848169.735 SOCK5.3381 00003 vanosock 213.230.78.17:4650 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848170.030 SOCK5.3381 00003 vanosock 213.230.78.17:30448 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848170.324 SOCK5.3381 00003 vanosock 213.230.78.17:7098 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848170.618 SOCK5.3381 00003 vanosock 213.230.78.17:47193 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848170.742 SOCK5.3381 00003 vanosock 213.230.78.17:6423 79.137.234.134:80 0 0 0 CONNECT_freepascal.ru:80
1456848170.818 SOCK5.3381 00003 vanosock 213.230.78.17:40885 195.82.146.214:80 0 0 0 CONNECT_rutracker.org:80
1456848170.906 SOCK5.3381 00003 vanosock 213.230.78.17:40648 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848171.199 SOCK5.3381 00003 vanosock 213.230.78.17:6775 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848171.494 SOCK5.3381 00003 vanosock 213.230.78.17:62053 54.68.159.67:443 0 0 0 CONNECT_tiles.services.mozilla.com:443
1456848801.981 SOCKS.3381 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting_thread
1456848983.858 SOCKS.3381 00000 - 0.0.0.0:3381 0.0.0.0:0 0 0 0 Accepting_connections_[19351/3077434176]
1456848997.859 SOCK5.3381 00003 vanosock 213.230.78.17:17123 213.180.204.3:80 0 0 0 CONNECT_www.ya.ru:80
1456849112.830 SOCKS.3381 00000 - 0.0.0.0:0 0.0.0.0:0 0 0 0 Exiting_thread

**Comment by z3APA3A** [comment]
А что после CR?

**Comment by IvankoB** [comment]
Пооле CR ? Ессно MD5, полученный MYCRYPT. 
Судя по логам, аутенификаия проходит нормально - но нет дальнейшего траффика.
(менять конфиг и тестировать могу не раньше 9-го марта)

**Comment by z3APA3A** [comment]
Пример можно, можно с другим паролем?

**Comment by z3APA3A** [comment]
А sockport в обоих случаях один и тот же?

**Comment by IvankoB** [comment]
Не рутере ессно есть серьзный файрвол - но SOCK-порт на нем 100% рабочий (SS5 & DANTE работают)

Пример можно, можно с другим паролем?
=================
соль=123/пароль=qwerty => "CR:$1$123$TZcqXQgTuWumJoo1xl3A/."

А sockport в обоих случаях один и тот же?
=================
Да.

**Comment by z3APA3A** [comment]
Адрес 0.0.0.0 озачает открыть порт на всех интерфейсах, включая extIP. Нельзя запустить две службы на одном интерфейсе на одном порту.

**Comment by IvankoB** [comment]
Адрес 0.0.0.0 озачает открыть порт на всех интерфейсах, включая extIP. Нельзя запустить две службы на одном интерфейсе на одном порту.
=======================
Как тогда сконфирировать опции "external ..", "internal .." и  "sock -i.. -e.." для PPPoE-внешнего интерфейса и чтобы одновремено обслуживать коннекты из локалки и из дома ?

**Comment by z3APA3A** [comment]
Достаточно только первой записи socks
А проблема в том, что у тебя 

allow username

вместо

allow vanosock

**Comment by IvankoB** [comment]
allow username

вместо

allow vanosock
----------------------
Там реально больше пользователей, и я считал что USERNAME - алиас для проверки по паре юзер:пароль до следующей FLUSH, а оказывается здесь ВСЕГДА должно быть конкретное имя конкретного пользваеля, так ? В доке по этой теме неясно .

PS: b все-таки какие значения нужны для "external ..", "internal .." и "sock -i.. -e.. ?

**Comment by IvankoB** [comment]
И кстати как заставить писать в лог ошибки аутенификации ?

**Comment by z3APA3A** [comment]
Если надо разрешать socks всем авторизованным пользователям, то достаточно написать
allow *
А у тебя в логе есть все ошибки аутентификации. 
http://3proxy.ru/howtor.asp#ERRORS

**Comment by IvankoB** [comment]
Если надо разрешать socks всем авторизованным пользователям, то достаточно написать
allow *
-----------------------
Эту опцию не могу - чтобы не ломились из внешнего сегмента Инета. В рабочем конфиге есть список из несколких разрешенных для коннекта сетей.
И что значит "всем авторизованным" ? Перечисленым в "users" до следующей "flush" ?

А у тебя в логе есть все ошибки аутентификации. 
----------------------
Код 3 ? Единичные (<=11) коды ИМХО можно выводить  текстом - они будут встречаться в 99:% случая отладки.

**Comment by IvankoB** [comment]
Что означает "allow username" ?

**Comment by z3APA3A** [comment]
Ты прочитай HowTo хотя бы.

**Comment by IvankoB** [comment]
"allow *" - то, что думал про "allow username" ? 

Замечания по логам: протоколирование "откуда и куда" при нерабочей аутнификации/ACL только запутывает.

**Comment by IvankoB** [comment]
Пофиксил, все заработало с конфигом
--------------------
daemon
maxconn 16384
log /var/log/3proxy/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30
nserver localhost
nserver 8.8.8.8
nscache 65536
flush
users "vanosock:CR:............" "mumussock:................."
auth strong
socks -p1234 -i192.168.1.1
socks -p1234 -i123.123.123.123 -e123.123.123.123
allow * 192.168.1.0/24,10.10.10.0/24,123.0.0.0/8,12.34.0.0/16,10.0.0.0/8
flush
deny *

**Comment by z3APA3A** [comment]
Оба flush не имеют смысла, и прокси надо запускать после allow / deny

**Comment by IvankoB** [comment]
Да, эти упрощения в конфиге работают, спасибо :)
Но еще проблема - намертво (приходится "срубать" процесс ) клинит Torrent-клиент (Tixati) сразу на запуске, 99% что из-за DHT (но без этого режима не обойтись). С DANTE данной проблемы нет.
Вот кусок лога с матюками на UDPMAP:
--------------------------
1457385656.331 SOCKS.3381 00000 - 0.0.0.0:0 213.230.108.220:0 0 0 0 Exiting_thread
1457385658.587 SOCK5.3381 00089 vanosock 10.8.106.152:17672 31.13.72.8:443 43321 32359 0 CONNECT_6-edge-chat.facebook.com:443
1457385659.001 SOCK5.3381 00089 vanosock 10.8.106.152:18219 192.168.1.229:22 55652 777888 0 CONNECT_192.168.1.229:22
1457385706.755 SOCKS.3381 00000 - 192.168.1.229:3381 0.0.0.0:0 0 0 0 Accepting_connections_[5458/3077884736]
1457385706.756 SOCKS.3381 00000 - 213.230.108.220:3381 213.230.108.220:0 0 0 0 Accepting_connections_[5458/3073641280]
1457385733.947 SOCK5.3381 00000 vanosock 10.8.106.152:22240 79.137.234.134:80 694 13365 0 CONNECT_freepascal.ru:80
1457385734.146 SOCK5.3381 00000 vanosock 10.8.106.152:22241 79.137.234.134:80 0 0 0 CONNECT_freepascal.ru:80
1457385735.146 SOCK5.3381 00000 vanosock 10.8.106.152:22247 217.69.136.175:80 0 0 0 CONNECT_top.list.ru:80
1457385737.182 SOCK5.3381 00000 vanosock 10.8.106.152:22245 81.19.88.95:80 1777 9963 0 CONNECT_counter.rambler.ru:80
1457385740.253 SOCK5.3381 00000 vanosock 10.8.106.152:22243 173.194.32.128:80 1097 397 0 CONNECT_www.google-analytics.com:80
1457385740.618 SOCK5.3381 00000 vanosock 10.8.106.152:22246 217.69.133.145:80 330 343 0 CONNECT_top.list.ru:80
1457385741.770 SOCK5.3381 00000 vanosock 10.8.106.152:22248 217.69.133.148:80 582 1481 0 CONNECT_top-fwz1.mail.ru:80
1457385770.217 SOCK5.3381 00421 vanosock 10.8.106.152:22250 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385789.234 SOCK5.3381 00000 vanosock 10.8.106.152:22239 52.25.78.214:443 1072 3405 0 CONNECT_tiles.services.mozilla.com:443
1457385800.665 SOCK5.3381 00421 vanosock 10.8.106.152:22251 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385812.525 SOCK5.3381 00000 vanosock 10.8.106.152:22242 93.158.134.119:443 6267 1887 0 CONNECT_mc.yandex.ru:443
1457385830.151 SOCK5.3381 00000 vanosock 10.8.106.152:22255 79.137.234.134:80 0 0 0 CONNECT_freepascal.ru:80
1457385831.040 SOCK5.3381 00421 vanosock 10.8.106.152:22252 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385861.483 SOCK5.3381 00421 vanosock 10.8.106.152:22257 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385877.978 SOCK5.3381 00000 vanosock 10.8.106.152:22254 74.125.25.94:443 1388 834 0 CONNECT_csi.gstatic.com:443
1457385891.897 SOCK5.3381 00421 vanosock 10.8.106.152:22258 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385913.165 SOCK5.3381 00000 vanosock 10.8.106.152:22249 178.154.131.215:443 1816 1295 0 CONNECT_yandex.st:443
1457385913.167 SOCK5.3381 00000 vanosock 10.8.106.152:22244 178.154.131.216:443 2808 1601 0 CONNECT_site.yandex.net:443
1457385919.687 SOCK5.3381 00000 vanosock 10.8.106.152:22253 173.194.32.142:443 7181 5760 0 CONNECT_plus.google.com:443
1457385920.720 SOCK5.3381 00000 vanosock 10.8.106.152:22256 87.250.251.119:443 3664 1329 0 CONNECT_mc.yandex.ru:443
1457385922.222 SOCK5.3381 00421 vanosock 10.8.106.152:22259 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385952.590 SOCK5.3381 00421 vanosock 10.8.106.152:22260 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457385982.961 SOCK5.3381 00421 vanosock 10.8.106.152:22261 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457386013.291 SOCK5.3381 00421 vanosock 10.8.106.152:22262 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457386015.612 SOCK5.3381 00000 vanosock 10.8.106.152:22263 185.31.17.133:443 402 3860 0 CONNECT_assets-cdn.github.com:443
1457386043.616 SOCK5.3381 00421 vanosock 10.8.106.152:22264 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457386066.447 SOCK5.3381 00000 vanosock 10.8.106.152:22266 87.250.251.119:443 1875 156 0 CONNECT_mc.yandex.ru:443
1457386070.862 SOCK5.3381 00000 vanosock 10.8.106.152:22272 194.226.130.229:443 1101 3401 0 CONNECT_www.tns-counter.ru:443
1457386072.827 SOCK5.3381 00000 vanosock 10.8.106.152:22271 93.158.134.90:443 361 6589 0 CONNECT_an.yandex.ru:443
1457386072.831 SOCK5.3381 00000 vanosock 10.8.106.152:22269 93.158.134.90:443 361 6589 0 CONNECT_an.yandex.ru:443
1457386073.971 SOCK5.3381 00421 vanosock 10.8.106.152:22265 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0

**Comment by z3APA3A** [comment]
Для UDPMAP обязательно указание внешнего интерфейса, не используй 0.0.0.0, запускай с явными указаниями IP.

**Comment by IvankoB** [comment]
внешнего интерфейса, не используй 0.0.0.0, запускай с явными указаниями IP.
------------------------
Так я и задал явно: socks -p1234 -i123.123.123.123 -e123.123.123.123

ПС: каким являтся ADSL PPoE-интерфейс к провайдеру ("поднимающийся" после запуска "3proxy") в случае коннектов из дома ? "internal" или "external" ? Как мне задать опции "internal" и "external" для обслуживания коннектов и из локалки (socks -p1234 -i192.168.1.1), и из дома (socks -p1234 -i123.123.123.123 -e123.123.123.123)?

**Comment by z3APA3A** [comment]
socks -p1234 -i192.168.1.1 -e123.123.123.123 
socks -p1234 -i123.123.123.123 -e123.123.123.123

**Comment by IvankoB** [comment]
Не помогло :
--------------------------
1457430202.317 SOCKS.1234 00000 - 192.168.1.1:1234 123.123.123.123:0 0 0 0 Accepting_connections_[13451/3077561152]
1457430202.318 SOCKS.1234 00000 - 123.123.123.123:3381 123.123.123.123:0 0 0 0 Accepting_connections_[13451/3073317696]
1457430245.230 SOCK5.1234 00421 vanosock 10.8.106.152:12836 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457430275.727 SOCK5.1234 00421 vanosock 10.8.106.152:12837 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457430306.137 SOCK5.3381 00421 vanosock 10.8.106.152:12845 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0

ПС: теоретический вопрос  - какие интерфейсные опции  задавать в случае если PPoE-инерфейс получает динамический адрес ? 
(нет проблем его узнавать и настраивать на него коннекты из Интернета)

**Comment by z3APA3A** [comment]
Добавь в скрипт, который поднимает интерфейс, запись IP адреса в файл, добавь в прокси мониторинг на этот файл.
Попробуй последний devel, поменял код ошибок, будет видно где именно фейлится.

**Comment by IvankoB** [comment]
Который "git pull/clone" ?

Добавь в скрипт, который поднимает интерфейс, запись IP адреса в файл, добавь в прокси мониторинг на этот файл.
===================
Это по теме DHCP-внешки ?

**Comment by IvankoB** [comment]
В GIT-версии UDPMAP фэйлится с кодом 431.

**Comment by z3APA3A** [comment]
> Это по теме DHCP-внешки
Да.
Попробуй текущую версию из Git

**Comment by IvankoB** [comment]
Больше не виснет
---------------
1457434829.791 SOCK5.1234 00013 vanosock 10.8.106.152:16175 46.138.17.219:20571 0 0 0 CONNECT_46.138.17.219:20571
1457434829.924 SOCK5.1234 00000 vanosock 10.8.106.152:16176 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457434830.365 SOCK5.1234 00000 vanosock 10.8.106.152:16178 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0
1457434830.696 SOCK5.1234 00000 vanosock 10.8.106.152:16180 0.0.0.0:0 0 0 0 UDPMAP_0.0.0.0:0

Но торрент-траффика нет - возможно проблема серверной стороны с торрентами.

**Comment by IvankoB** [comment]
После перазагрузки рутера с 3proxy все заработало. Может это быть связано с проксированием ?
("ulimits" для открытых файлов поднято до 65535)

**Comment by IvankoB** [comment]
Извниняюсь, последний фикс в Git - на авось или с логикой ?

**Comment by z3APA3A** [comment]
Ну по крайней мере он не должен повредить.

**Comment by IvankoB** [comment]
Еще не разобрался с автопаковкой старых логов - пока оной не вижу на рутере. 
Нужен ли какой-то особый формат именования лог-файла чтобы он принимался и обрабатывался LOGROTATE ?

**Comment by z3APA3A** [comment]
А archiver как задан? archiver должен сам удалять старый файл, если вызываемая команда этого не делает - надо вместо нее вызывать скрипт.

**Comment by IvankoB** [comment]
А archiver как задан? 
----------------------
Все, что в "/var/log/* обрабатываетcя системным LOGROTATE. 99% что ему нужно имя "3proxy.log" безо всяких суффиксов. 
Какми опциями всего этого достичь ?

**Comment by z3APA3A** [comment]
Чтобы обрабатывал системный logrotate логгировать надо через syslog

**Comment by IvankoB** [comment]
Вот кстати скрипт запуска демона в DEBIANe "/etc/init.d/3proxy" (можно засунуть в HowTo):
--------------------------
#! /bin/sh

### BEGIN INIT INFO
# Provides:          3proxy
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description: Provides 3proxy multiple protocol & SOCK proxy server.
### END INIT INFO

DAEMON=/usr/local/bin/3proxy
DAEMON_ARGS="/usr/local/etc/3proxy/3proxy.conf"

set -e

case "$1" in
  start)
	start-stop-daemon --start --exec $DAEMON -- $DAEMON_ARGS
	;;
  stop)
	start-stop-daemon --stop --exec $DAEMON
	;;
  reload|restart|force-reload)
	start-stop-daemon --stop --exec $DAEMON
	start-stop-daemon --start --exec $DAEMON -- $DAEMON_ARGS
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

**Comment by shark136** [comment]
log /usr/local/3proxy/logs/3proxy.log D
rotate 30
archiver gz /usr/bin/gzip %F

вот пример моего конфига с упаковкой и ротацией в 30 дней

-- 
Новоселов Михаил

**Comment by IvankoB** [comment]
Спасибо. Это конфиг говрит "запаковать прежний день" при начале нового ?

**Comment by shark136** [comment]
да, каждый новый день, предыдущий лог архивируется.
