### ISSUE TITLE
Добавить сессию

### ISSUE THREAD

**Issue by sergey837** [z3APA3A/3proxy#471]
Здравствуйте, подскажите, долго ищу ответ, никак не могу найти, хочу добавить сессию к логину в parent

allow *
parent 1000 http ip port login-%c password

Судя по логам %c это номер сессии, пробовал добавлять "%c", но номер сессии не добавляется к логину.

**Comment by z3APA3A** [comment]
Такой функциональности нет, %-подстановки работают в формате лога и именых файлов. Можешь написать свой плагин, который будет подставлять что-то в имя пользователя.
