### ISSUE TITLE
Показывает настоящий IP вместо parent

### ISSUE THREAD

**Issue by sanasol** [z3APA3A/3proxy#472]
main.conf
```
#!/usr/local/bin/3proxy
timeouts 1 5 30 60 180 1800 15 60
log 3proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

config config.conf
monitor config.hash
```

config.conf
```
users user77:CL:aydzfgdpe1
auth strong
allow *
parent 500 http http_proxy_ip 30011 sanasol test
proxy -a -p30011
external 0.0.0.0
flush

users user52:CL:xyzuhzi0qu
auth strong
allow *
parent 500 socks5 socks_proxy_ip 3001 sanasol test
proxy -a -p3001
external 0.0.0.0
flush
```

Коннектится и т.д. всё отлично, но через раз запросы как-будто идут мимо parent и я вижу IP не от parent прокси, а того сервера на котором стоит 3proxy.

**Comment by sanasol** [comment]
Добавил authcache
Поменял вес parent на 1000

Что-то из этого помогло кажется. Пока не смог воспроизвести опять.
Но вопрос всё равно актуальный для понимания.
По коду не увидел что вес прямо суммарно 1000 должен быть. т.е. этот пункт исключаем.
Видимо помог кеш авторизации в таком случае.
Вопрос в том почему авторизация/переадресация валится если несколько раз подряд обновить страницу в браузере.

**Comment by z3APA3A** [comment]
При весе 500 у тебя половина запросов уходит на parent, половина идет напрямую.

**Comment by sanasol** [comment]
Понятно, внезапно)
