### ISSUE TITLE
An option to pass hostnames directly into the parent proxy (with name resolution).

### ISSUE THREAD

**Issue by phantomcraft** [z3APA3A/3proxy#473]
I want to use this configuration for DNS over SSH, but there is a issue:

```
nserver 127.0.0.1:10052/tcp
nscache 65536
nscache6 65536
dnspr -i:: -p53
allow *
parent 1000 socks5+ 127.0.0.1 1080
parent 250 tcp anycast.censurfridns.dk 53
parent 250 tcp unicast.censurfridns.dk 53
parent 250 tcp resolver1.dns.watch 53
parent 250 tcp resolver2.dns.watch 53
tcppm -i127.0.0.1 10052 127.0.0.1 11111
```

3proxy needs to resolve each domain name in tcp parent, with this configuration it fails because there is no usable resolver.

An option to pass the hostnames directly in the tcp section to the parent proxy with name resolution would be interesting in this case because it can lead to IP leaks in the scheme.

Could you implement this feature?

**Comment by z3APA3A** [comment]
3proxy resolves parent IPs on configuration reading, so the simplest solution is to use

allow *
parent 1000 socks5 127.0.0.1 1080
parent 250 tcp anycast.censurfridns.dk 53
parent 250 tcp unicast.censurfridns.dk 53
parent 250 tcp resolver1.dns.watch 53
parent 250 tcp resolver2.dns.watch 53
tcppm -i127.0.0.1 10052 127.0.0.1 11111
flush
nserver 127.0.0.1:10052/tcp
nscache 65536
nscache6 65536
dnspr -i:: -p53
