### ISSUE TITLE
accessing proxy from own proxy server

### ISSUE THREAD

**Issue by aherlambang** [z3APA3A/3proxy#474]
I am currently using IP authentication for my 3proxy config, here is my config:

```
auth iponly

#deny * * 127.0.0.1,192.168.1.1
allow * 23.229.5.111,127.0.0.1,192.168.1.1  * 80-88,8080-8088 HTTP
allow * 23.229.5.111,127.0.0.1,192.168.1.1  * 443,8443 HTTPS

```
where 23.229.5.111 is the IP of my server where 3proxy is hosted on.. i want to use this proxy on this own server (a.ka: localhost), but doing the above gives me an error 500 when accessing the proxies

now when i change the allow to

allow * * * 1-65535 HTTP
allow * * * 1-65535 HTTPS

it works just fine.. but this is dangerous as it means the proxy is open to the whole world.. 

what did i do wrong ? what do i need to change so i can use this proxy on the localhost ?

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by aherlambang** [comment]
i don't see anything in the logs when i try to make the request
