### ISSUE TITLE
Нестандартное перенаправление

### ISSUE THREAD

**Issue by zarethernet** [z3APA3A/3proxy#477]
Можно ли сделать нестандартное перенаправление.
Есть 2 отдельных вышестоящих прокси-сервера, один только ipv4, второй только ipv6.
Мне они не доступны для управления.
Хотелось бы объединить 2 сервера.
Создать прокси на порту, например 3128, при соединении ipv6 направлять на ipv6, а ipv4 на ipv4.
Есть ли возможность реализовать такую схему?

**Comment by z3APA3A** [comment]
Да, например

```
allow 0.0.0.0/0
parent socks5 server1 port1 login1 password1
alllow ::/0
parent socks5 server2 port2 login2 password2

```
