### ISSUE TITLE
большая нагрузка на процессор 

### ISSUE THREAD

**Issue by npxo** [z3APA3A/3proxy#479]
возникла ситуация, когда в рамках ОС ubuntu при нагрузке исходящего сетевого канала прокси процессор значительно сильнее загружается по сравнению с macos. i9 уходит на 100% при out speed в районе 100 мб\сек. в то время на macos 2-5% максимум как и in speed на убунту. подскажите, с чем это может быть связано?

**Comment by npxo** [comment]
особенно сильно (критично до 800% cpu) при ауте на протоколе сокс

**Comment by z3APA3A** [comment]
см https://3proxy.ru/highload.asp
попробуй отключить сплайсы.

**Comment by npxo** [comment]
помогло. большое спасибо!

пт, 12 июн. 2020 г. в 14:43, Vladimir Dubrovin <notifications@github.com>:
