### ISSUE TITLE
3proxy-0.8.4-x64 crash

### ISSUE THREAD

**Issue by Barabylia** [z3APA3A/3proxy#48]
3proxy-0.8.4-x64, Win7 Вылетает при установке писать логи в файл:
log C:\3proxy\logs\3proxy.log D
если просто
log
то всё нормально.
P.S. В версии 3proxy-0.6.1-x64 тот же конфиг всё логирует нормально в файл.

**Comment by z3APA3A** [comment]
Действительно есть, используй 58a64924ddff9e6e1c9d8d0faa876af0449695d4 - должен пофиксить или в качестве workaround запусти любой сервис (например tcppm) до команды log.

**Comment by z3APA3A** [comment]
Поправил в 0.8.5
