### ISSUE TITLE
Компиляция openwrt 18.06 

### ISSUE THREAD

**Issue by apavlishev** [z3APA3A/3proxy#480]
wget https://3proxy.org/current/3proxy-0.9-devel.tgz
make -f Makefile.unix

`gcc -o ../bin/3proxy -O2 -fno-strict-aliasing -pthread   3proxy.o mainfunc.o auth.o authradius.o conf.o datatypes.o srvproxy.o srvpop3p.o srvsmtpp.o srvftppr.o srvsocks.o srvtcppm.o srvudppm.o sockmap.o sockgetchar.o common.o mycrypt.o md5.o md4.o base64.o ftp.o smbdes.o ntlm.o stringtable.o srvwebadmin.o srvdnspr.o plugins.o  
/usr/bin/ld: cannot find -lpthread
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile.inc:144: ../bin/3proxy] Error 1
make[1]: Leaving directory '/3proxy/src'
make: *** [Makefile.inc:7: all] Error 2`

Библиотека pthread установлена, и до этого места все идет хорошо.

**Comment by z3APA3A** [comment]
Не надо использовать Makefile.unix, openwrt это Linux, там -pthread. + можешь посмотреть Makefile.openwrt-mips там пример кроссбилда.
