### ISSUE TITLE
[Question] Which IPs can I use so that it's detected as being from Canada?

### ISSUE THREAD

**Issue by paulwongx** [z3APA3A/3proxy#481]
I set my IP to 1.1.1.1, 1.1.1.2 etc. and then when I check the location of the proxy along with my userid and password online, it shows it's from Australia.

1) Should I be setting the IP as a number related to the VPS server IP?
2) Don't all IPs need to be unique online, so how am I able to set an IP as 1.1.1.1? (i know it's a super noob question). I still don't get this part, am I able to set the IPs as any series of 4 numbers? How is this possible?
3) How can I set an IP in a city in Toronto for example. Do all IPs start with a certain series of numbers in certain cities? 

Edit: Specifically, at the bottom of the `/etc/3proxy/3proxy.cfg` file, what proxy ID's should be put in place of 1.1.1.1 and 1.1.1.2 and 1.1.1.3 ?

```py
proxy -p3128 -a -i1.1.1.1 -e1.1.1.1
proxy -p3128 -a -i1.1.1.2 -e1.1.1.2
proxy -p3128 -a -i1.1.1.3 -e1.1.1.3
```

**Comment by z3APA3A** [comment]
You can not use proxy to setup random IP, you should have this IP configured on the host running the proxy. To use Canadian IP you can buy a VPS in Canada and run a proxy on this VPS or you can buy a VPN connection and configure proxy to use a VPN for outgoing traffic.
