### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by Goldenbringer2020** [z3APA3A/3proxy#483]
Приветствую! Большое спасибо за работу и замечательный прокси сервер, все работает хорошо. Однако заметил одну проблему с websocket - они через прокси не работают. Проверить можно здесь: https://websocketstest.com/ , мне показывает что соккеты недоступны. Настраивал непрозрачный прокси через socks5 в версии 0.8

**Comment by z3APA3A** [comment]
socks5 все равно какие протоколы пробрасывать, если что-то не работает - значит что-то не так настроено, посмотри по логам.

**Comment by Goldenbringer2020** [comment]
В логах пусто, когда зоху через браузер через прокси, то в консоли пишет:
Firefox can’t establish a connection to the server at wss://websocketstest.com/service.

Когда захожу с того же браузера без прокси - все ок.

Настройки следующие:
daemon
pidfile /usr/local/etc/3proxy/3proxy.pid
nserver 127.0.0.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
log /usr/local/etc/3proxy/logs/3proxy.log D
logformat "G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T %e"
archiver gz /usr/bin/gzip %F
rotate 7
auth strong
users USER:PASSWORD
allow * * * *
socks  -n -a -iXXX.XXX.XXX.XXX -eYYY.YYY.YYY.YYY -p32654
maxconn 256
flush
dnspr
monitor "/usr/local/etc/3proxy/3proxy.cfg"
end

, где XXX.XXX.XXX.XXX и YYY.YYY.YYY.YYY - реальные ИП на сервере

**Comment by z3APA3A** [comment]
Если в логах пусто, значит в 3proxy ничего не приходит. Firefox не умеет использовать SOCKSv5 с аутентификацией, раз у тебя такая конфигурация работает во всем кроме вебсокетов, значит ты используешь какой-то плагин, уточни в его документации поддерживает ли он вебсокеты.
