### ISSUE TITLE
gcc Compile error

### ISSUE THREAD

**Issue by Ygrittevictorlee** [z3APA3A/3proxy#484]
Hi there,

can I get some help with setup please?

when I compile this program,It failed to compile.

Error message：

structures.h:143:32: error: cannot convert to a pointer type
  143 | #define SAPORT(sa)  (&((struct sockaddr_in *)sa)->sin_family == AF_INET6? &((struct sockaddr_in6 *)sa)->sin6_port : &((struct sockaddr_in *)sa)->sin_port)
      |                                ^~~~~~~~~~~
auth.c:807:8: note: in expansion of macro ‘SAPORT’
  807 |        SAPORT(ac->sinsl) = 0;
      |        ^~~~~~
structures.h:143:62: warning: comparison between pointer and integer
  143 | #define SAPORT(sa)  (&((struct sockaddr_in *)sa)->sin_family == AF_INET6? &((struct sockaddr_in6 *)sa)->sin6_port : &((struct sockaddr_in *)sa)->sin_port)
      |                                                              ^~
auth.c:807:8: note: in expansion of macro ‘SAPORT’
  807 |        SAPORT(ac->sinsl) = 0;
      |        ^~~~~~
structures.h:143:85: error: cannot convert to a pointer type
  143 | #define SAPORT(sa)  (&((struct sockaddr_in *)sa)->sin_family == AF_INET6? &((struct sockaddr_in6 *)sa)->sin6_port : &((struct sockaddr_in *)sa)->sin_port)
      |                                                                                     ^~~~~~~~~~~~
auth.c:807:8: note: in expansion of macro ‘SAPORT’
  807 |        SAPORT(ac->sinsl) = 0;

How should i modify？thank you.

**Comment by z3APA3A** [comment]
Should be fixed with 19eef46d7eb53bea25324304d46ff8ecc0a6071b
