### ISSUE TITLE
how to set ipv6 in 3proxy ?

### ISSUE THREAD

**Issue by KawaguchiMaeda123** [z3APA3A/3proxy#487]
if i using ipv4 only my config is

```
allow * * *
deny * * 127.0.0.1,192.168.1.1
allow * * * 80-88,8080-8088 HTTP
allow * * * 443,8443 HTTPS
#allow * * * 1-65535 HTTP
#allow * * * 1-65535 HTTPS
# run http-proxy ... without ntlm-authorization, complete anonymity and port ...                                                 
#                                                                                                                                           
#proxy -n -p3128 -a                                                                                                                         
#Enable admin web-ui on specified port
admin -p3200
socks -n -p1080 -a

socks -n -p3000 -a
```
this work

but

how to setting ipv6 ? i not understand settting

I want to set ipv6 without a username and password

**Comment by z3APA3A** [comment]
If you do not set internal/external address, no configuration on proxy side is required to proxy between IPv4 and IPv6 (except, may be adding internal IPv6 networks to 'deny'). You may want to setup -46 or -64 to make a usage preferences between IPv4 and IPv6 (-46 is default).

**Comment by z3APA3A** [comment]
See https://3proxy.ru/howtoe.asp#IPV6
