### ISSUE TITLE
How to use 3proxy behind nat ?

### ISSUE THREAD

**Issue by burkifaso** [z3APA3A/3proxy#488]
Hey, I would like to configure 3proxy to works with 3proxy servers behind NAT, what I would like to achieve you can check on below image :

![image](https://user-images.githubusercontent.com/38869806/87130109-aa83ce80-c292-11ea-8183-10e317808ddb.png)

so I have VPS with 3proxy installed, and one server with is behind NAT ..

my question is ? how to configure 3proxy on VPS and 3proxy server behind NAT to give client1 who is using connection to VPS Server, external IP from server behind NAT, so simply I want to forward request from client1 to server behind NAT , and get results back from server behind NAT

**Comment by z3APA3A** [comment]
You can use a connect back feature:
https://3proxy.ru/howtoe.asp#CONNBACK

**Comment by burkifaso** [comment]
can you give an example configuration for server and client

**Comment by z3APA3A** [comment]
There are examples by the link

**Comment by hippich** [comment]
Did not want to open a new issue... I am trying to figure out how to setup connect back through the corporate proxy. I.e.

3proxy -> corporate connect proxy -> | FIREWALL | -> my server with 3proxy tcppm

If I specify `parent` - it uses it to make outbound connections for requests but not for connecting back part.

**Comment by z3APA3A** [comment]
parent is not applied to connect back. You can create additional tcppm+parent and specify local ip/port of tcppm as a connect back address.

**Comment by hippich** [comment]
> parent is not applied to connect back. You can create additional tcppm+parent and specify local ip/port of tcppm as a connect back address.

I was thinking along these lines, but yesterday somehow I could not come up with it. After you reply today - I did :) Thank you!

**Comment by ezbik** [comment]
> You can create additional tcppm+parent and specify local ip/port of tcppm as a connect back address.

@z3APA3A sorry, could you please demonstrate it? I don't understand. Thank you.

---


Also @z3APA3A a quick question - is it possible to see original `Proxy_Client` IP address on `3proxy_behind_nat` server?

##### `3proxy_behind_nat` -> `3proxy_in_the_cloud(tcppm)` <- `Proxy_Client`

**Comment by z3APA3A** [comment]
```
...
tcppm -r127.0.0.1:23456 ...
...
flush
allow 127.0.0.1
parent ....
tcppm -i127.0.0.1 23456 remote_ip remote_port
```

in general, case there is no way to transfer client IP between chained proxies. For connect back it's technically possible, but not implemented.
