### ISSUE TITLE
Не ставится на OpenBSD 6.7

### ISSUE THREAD

**Issue by killarbyte** [z3APA3A/3proxy#489]
Пробовал ставить на amd64 и i386

если из коробки с чистой системы сделать:
git clone https://github.com/z3APA3A/3proxy
cd 3proxy/
ln -s Makefile.unix Makefile
make

Результат [screenshot](https://sun9-35.userapi.com/c855336/v855336332/24e9ad/edZ3_qhNJ4E.jpg)

Пробовал по разному. На чистой системе делаю так:
git clone https://github.com/z3APA3A/3proxy
cd 3proxy/

vim Makefile.unix
тут пробовал так
CC = gcc менял на CC = egcc
пробовал и так и так

пробовал удалить -DWITH_STD_MALLOC

ln -s Makefile.unix Makefile
make или gmake или doas make или doas gmake

Я так понял что на OpenBSD нету PAM https://www.openpam.org/ и из за этого не компилит ?
И какие то чудеса по дефолту с gcc - его бинарник почему то имеет такой вид /usr/local/bin/i386-unknown-openbsd6.7-gcc-8.3.0

```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/i386-unknown-openbsd6.7/8.3.0/lto-wrapper
Target: i386-unknown-openbsd6.7
Configured with: /pobj/gcc-8.3.0/gcc-8.3.0/configure --with-stage1-ldflags=-L/pobj/gcc-8.3.0/bootstrap/lib --verbose --program-transform-name='s,^,e,' --disable-nls --with-system-zlib --disable-libmudflap --disable-libgomp --disable-libssp --disable-tls --with-gnu-ld --with-gnu-as --enable-threads=posix --enable-wchar_t --with-gmp=/usr/local --enable-languages=c,c++,fortran,objc,ada --disable-libstdcxx-pch --enable-default-ssp --enable-default-pie --without-isl --enable-cpp --prefix=/usr/local --sysconfdir=/etc --mandir=/usr/local/man --infodir=/usr/local/info --localstatedir=/var --disable-silent-rules --disable-gtk-doc
Thread model: posix
gcc version 8.3.0 (GCC)
```

Если я предварительно не скопировал:
`cp /usr/local/bin/i386-unknown-openbsd6.7-gcc-8.3.0 /usr/local/bin/gcc`
то gcc -v выдаёт:
`ksh: gcc: not found`

Пробовал удалять и заного ставить gcc:
```
pkg_delete gcc
pkg_info -Q gcc
pkg_add gcc-8.3.0p5
pkg_add -u gcc
```

Куда копать ?

**Comment by z3APA3A** [comment]
PAM здесь непричем,  -DWITH_STD_MALLOC тем более. А полный вывод make какой?

**Comment by killarbyte** [comment]
> 
> 
> PAM здесь непричем, -DWITH_STD_MALLOC тем более. А полный вывод make какой?

https://gist.githubusercontent.com/killarbyte/1a8fd17847de6666a3b5416daf9d01d7/raw/d02468fabfd72f38d44311a6a0c584c74be935de/gistfile1.txt

**Comment by z3APA3A** [comment]
gcc по дефолту в OpenBSD должен быть в /usr/bin
Возможно, у тебя как-то странно стоит gcc, возможно он от другой платформы и ты компилируешь кросс-компилятором, а собираешь линкером для своей пдатформы. Попробуй сделать make clean, и поменять gcc на cc в Makefile, можешь еще там же попробовать поменять -fpic на -fPIC и пересобрать.

**Comment by killarbyte** [comment]
Для чистоты эксперимента - поставил по новой OpenBSD 6.7 amd64

syspatch
pkg_add -Uu

pkg_add htop mc speedtest-cli git curl wget nano vim 


Написал gcc -v

Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.7/4.2.1/specs
Target: amd64-unknown-openbsd6.7
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719

потом чекнул вот так /usr/bin/gcc -v

Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.7/4.2.1/specs
Target: amd64-unknown-openbsd6.7
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719


Сразу пробую компилить
git clone https://github.com/z3APA3A/3proxy
cd 3proxy/
ln -s Makefile.unix Makefile
make

результат: https://gist.githubusercontent.com/killarbyte/41f451bad879d7cc0e840743828aad5c/raw/4ded2b6b88f6379d6fa735a6a8d2216a417ea948/gistfile1.txt





Пробую дальше
make clean
vim Makefile.unix


поменял
CC = gcc
на
CC = cc

и
DCFLAGS = -fpic
на
DCFLAGS = -fPIC

rm -rf Makefile
ln -s Makefile.unix Makefile
make

Результат: https://gist.githubusercontent.com/killarbyte/3eb42ad4953110db9f19b87860982d38/raw/2c503b766e4b711bf6677ce922393ca9701dfca2/gistfile1.txt

**Comment by killarbyte** [comment]
Может каких то зависимостей надо скачать ?

**Comment by z3APA3A** [comment]
А вот здесь как раз ошибка на PAM. По этим логам, у тебя все получилось и все собралось кроме плагина PAM в обоих конфигурациях. Если плагина PAM не требуется - убери его из PLUGINS или поставь библиотеки для PAM (обычно что-нибудь типа pam-devel). Или можешь ничего не делать, т.к. сам 3proxy уже должен быть собран.
