### ISSUE TITLE
In the daemon mode, forking as non-priveleged user

### ISSUE THREAD

**Issue by IvankoB** [z3APA3A/3proxy#49]
For instance, "nobody" (or dedicated "proxy" etc ) having "/bin/false" login shell.
(for security reasons)

**Comment by z3APA3A** [comment]
add e.g.
`setuid 65534`
before
`daemon`

**Comment by IvankoB** [comment]
Мабуть "setreuid" ?

**Comment by IvankoB** [comment]
С "setuid 65534" не идет протоколирование в /var/log/*. Понижать права лог-файлов не хочется.

**Comment by z3APA3A** [comment]
Сделай сначала log потом setuid.
В devel есть патч, который делает setreuid.

**Comment by IvankoB** [comment]
В жизнь бы не догадался что положение опций логгирования в конфиге влияет на доступ к логам :)

**Comment by IvankoB** [comment]
Да,забыл сказать - все заработало.

**Comment by z3APA3A** [comment]
3proxy рассматривает файл конфигурации как командный файл и выполняет команды последовательно сразу после получения, поэтому порядок важен. В документации на это внимание обращается многократно.

**Comment by IvankoB** [comment]
Если бы все опции, котры залежат от порядка,  начинались с SET*, то это было бы нагляднее.

**Comment by z3APA3A** [comment]
_все_ опции зависят от порядка.

**Comment by IvankoB** [comment]
Кстати прога пока что постабильнее DANTE. Подозреваю что тому иногда не хватало макс открытых файлов в ULIMITе, но он не делал никаких предупреждений на это счет - в отличие от 3proxy.
