### ISSUE TITLE
How 3proxy limit bandwidth with p2p

### ISSUE THREAD

**Issue by mysparrow** [z3APA3A/3proxy#491]
Hello, I found that 3proxy can NOT limit the speed of p2p(just like BitTorrent protocol) software, How 3proxy limit bandwidth with p2p, thanks.

**Comment by z3APA3A** [comment]
bnadwidth limitation within 3proxy is not protocol dependant. If limitation does not work in means either traffic does not go through the proxy or limitation is not correctly configured.

**Comment by elico** [comment]
@mysparrow You can try to look at https://github.com/vel21ripn/nDPI which might help you better in this specific task.
