### ISSUE TITLE
socks 4 to 6 error 00094 

### ISSUE THREAD

**Issue by duccxx** [z3APA3A/3proxy#492]
I setting up socks gateway but unsuccessfully 4-to-6 traffic, all error 00094. 4-to-4 is OK.
Any helps 🥇

**Comment by z3APA3A** [comment]
What do you have in config and logs?

**Comment by duccxx** [comment]
In log with 4-to-6:
insert into log (l_date, l_user, l_service, l_in, l_out, l_descr, ClientIP, RequestedIP, ExternalIP, RemoteIP, RemotePort, Requested Hostname, Error Code) values ('27-07-2020 09:35:52', 'user1', 'SOCK5', 0, 0, 'CONNECT www.google.com:80', '178.251.49.194', '2404:6800:4005:80e::2004', '2605:1a40::10', '2404:6800:4005:80e::2004', '80', '', '00094')

in config:
nserver 8.8.8.8
nserver 208.67.220.220
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

daemon
logformat "-'+_Linsert into log (l_date, l_user, l_service, l_in, l_out, l_descr, ClientIP, RequestedIP, ExternalIP, RemoteIP, RemotePort, Requested Hostname, Error Code) values ('%d-%m-%Y %H:%M:%S', '%U', '%N', %I, %O, '%T', '%C', '%Q', '%e', '%R', '%r', '%n', '%E')"
log /var/log/3proxy.log D
rotate 30

dnspr


# http (s)
#auth none
#auth strong
#users user1:CL:user1
#allow * * * *
#proxy -6 -n -a -p1000 -i {ipv4} -e {ipv6}
#proxy -6 -n -a -p1001 -i {ipv4} -e {ipv6}

# socks
#auth none
auth strong
users user1:CL:user1
allow * * * *
socks -4 -p1002 -i203.142.142.233 -e203.142.142.233
socks -6 -p1003 -i203.142.142.233 -e2605:1a40::10

in ifconfig: 
- dual stack.
- internal, external on 1 interface.

**Comment by z3APA3A** [comment]
Check if 2605:1a40::10 is really assigned and you can connect to remote host using this IP as a source e.g. with

telnet -b  2605:1a40::10  2404:6800:4005:80e::2004 80

from proxy port

**Comment by duccxx** [comment]
[root@sockv5 ~]# telnet -b 2605:1a40::10 2404:6800:4005:800::200e 80
Trying 2404:6800:4005:800::200e...
Connected to 2404:6800:4005:800::200e.
Escape character is '^]'.

Telnet is OK :(

**Comment by z3APA3A** [comment]
try to check with a curl via proxy next.

**Comment by duccxx** [comment]
You are genius, curl is OK, may be sock client error ?

**Comment by z3APA3A** [comment]
It may be some client issue or result of antivirus/firewall which blocks the request
