### ISSUE TITLE
Opening 2000 ports casues the Host Not Found (100) error

### ISSUE THREAD

**Issue by Shawn-Tong** [z3APA3A/3proxy#495]
If I open 2000 ports and run it for a while, all the requests will get a 100 error code, showing the "Host Not Found" message.

```
nscache 131072
nserver 8.8.8.8
nserver 8.8.4.4
```

```
Limit                     Soft Limit           Hard Limit           Units     
Max stack size            8388608              unlimited            bytes     
Max core file size        0                    unlimited            bytes     
Max processes             65535                65535                processes 
Max open files            99999                99999                files     
Max locked memory         65536                65536                bytes     
...
```

1. I'm using the 0.9-devel version. Max open files soft/hard limit is set to 99999.
2. The CPU and memory usages are both OK when having this problem.
3. When having the problem, I used dig command to check whether 8.8.8.8/8.8.4.4 blocks my requests and find they don't block me.
4. If I change the conf file and only open 1000 ports, the problem is fixed immediately.
5. The problem won't happen immediately after I changed the conf file to 2000 ports. It will happen after running for a while.

Is there any solution that I can open 2000 ports without the DNS problem?

BTW, what is the reason for the 155 error code, I didn't find it in howtoe.asp. Is it about the threads or bandwidth limit?

**Comment by z3APA3A** [comment]
Read
https://3proxy.ru/highload.asp
probably you are trying to set ulimits via limits.conf or run 3proxy with chroot/setuid.

**Comment by Shawn-Tong** [comment]
Did you mean I didn't change the ulimits correctly? If so, 3proxy would give me this error message when reloading: 

`[line XX] Warning: current open file ulimits are too low...`

Now it didn't give that error message. So the ulimits should be OK.

**Comment by z3APA3A** [comment]
It only check the file limits and may not give a warning if multiple proxy instances are running. You may have an issue with e,g, ephemeral ports. Also, you definitely should not use google's DNS with high rates. The fact you can resolve name through a different client means nothing, because ratelimit may be based on DNS client's fingerprint.
There is no any limits in 3proxy itself.
