### ISSUE TITLE
Don't interrupt the service when reload the config file?

### ISSUE THREAD

**Issue by Shawn-Tong** [z3APA3A/3proxy#497]
Both `service 3proxy reload` and `service 3proxy restart` commands kill the service.

Is it possible that it doesn't interrupt the service when reloading the config file, like Nginx and Squid?

**Comment by z3APA3A** [comment]
It depends on init script you use rather than on 3proxy. Default init script from 3proxy distribution reloads config via USR1 signal
https://github.com/z3APA3A/3proxy/blob/3b5fa46e27119a282b456f3aee84a537d4c6e862/scripts/init.d/3proxy.sh#L41
probably, you use a different one.
