### ISSUE TITLE
Запасной парент

### ISSUE THREAD

**Issue by valkiriy** [z3APA3A/3proxy#498]
Подскажите как сделать следующую логику. 
У аккаунта прокси прописан ип интерфейса, через котоырй слат запросы от порта. Но при переконфигурировании сети нетпланом он видимо ожидает пока подключиться модем (рестарт модема путем отключения-подключения) и происходит пауза до 3х минут. При этом прокси не работают на внешку, возможно ли как то сделать так чтобы 3прокси, когда не работает основной интерфейс слал запросы на парент (другой прокси на внешке)?

**Comment by z3APA3A** [comment]
Сделай генерацию конфига через ifup/ifdown скрипты, чтобы при поднятии модема работал конфиг через модем, при опускании интерфейса переключался на резервный конфиг.
