### ISSUE TITLE
   Do you plan to add the function which limit connections for each user in the next version?

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#5]
Hi, 
    If provide 3proxy service for public,any user has no limitaion of connections.So there is an issue,some users have lots of connections,even if we can limit the bandwidth or traffic,it still make the 3proxy server very unstable,like high cpu,high load,the result is the speed is slow and it won't accpet new connecions.Other users can't use the service any more.

   Do you plan to add the function which limit connections for each user in the next version?

   For example like this,each user in the userlist has the same max conneciotns.
   connlimin <amount> <userlist> <sourcelist> <targetlist> <targetportlist> <commandlist> 

Kindly regards
Michael

**Comment by raintears2** [comment]
connlimin     amount    userlist   sourcelist    targetlist    targetportlist    commandlist

**Comment by z3APA3A** [comment]
I will count it as a feature request.

P.S. CPU usage shouldn't depend on number of connections, issues with large number of connections are usually caused by some system limitations.

**Comment by z3APA3A** [comment]
Added to devel.
connlim 100 60 (ACL)
limits to 100 connections per 60 seconds for given ACL.
connlim 10 0 (ACL)
limits to 10 parallel connections for given ACL

**Comment by z3APA3A** [comment]
e.g.
noconnlim * * inthost.compant.com
connlim 60 100  * 192.168.0.1
connlim 60 100  * 192.168.0.2
