### ISSUE TITLE
How to limit connect to website

### ISSUE THREAD

**Issue by Thomanphan** [z3APA3A/3proxy#501]
Hello
I used ipv6 proxy and want limit proxy connect to google.com like 10 request per second How I can do it
In logs file connect to google website like this 

1597080722.860 PROXY.696 00012 myusername 7.79.203.100:51880 123:1450:4009:81a::2004:443 0 0 0 CONNECT_www.google.com:443_HTTP/1.1
Thanks

**Comment by z3APA3A** [comment]
00012 means you were unable to bind to interface specified as external, see
https://3proxy.ru/howtoe.asp#ERRORS
https://3proxy.ru/faqe.asp (seedescription of internal and external)

for ratelimis see 'connlim'
https://3proxy.ru/doc/man3/3proxy.cfg.3.html

**Comment by Thomanphan** [comment]
But I tried add limit
```
connlim 5 60 * google.com
connlim 5 60 * www.google.com
```
but error  Unknown command: 'connlim' line 46

**Comment by z3APA3A** [comment]
Connlim is implemented in current devel version (0.9).
Also, you use google.com as a source IP rather than destination.

**Comment by Thomanphan** [comment]
Thank but google.com with ipv6 has many ip address How I can add it 
some ipv6 like 
2a00:1450:4001:820:0:0:0:200e
2607:f8b0:4006:818:0:0:0:200e
2c0f:fb50:4002:800:0:0:0:200e
and more

How I can limit bandlimin and bandlimout all ipv6

**Comment by ezbik** [comment]
Use txt file with all the addresses. Check the documentation. Use domain name if DNS reolution takes place in 3proxy.

**Comment by Thomanphan** [comment]
> Use txt file with all the addresses. Check the documentation. Use domain name if DNS reolution takes place in 3proxy.

Can you send me link 
I have try with config

```
bandlimin 1500000 * * /etc/google.txt
bandlimout 1500000 * * /etc/google.txt
```

with /etc/google.txt content like
```
2a00:1450:4001:820:0:0:0:200e
2607:f8b0:4006:818:0:0:0:200e
2c0f:fb50:4002:800:0:0:0:200e
2001:4860:4000::/36
2404:6800:4000::/36
```

**Comment by ezbik** [comment]
Prepend the file name with dollar sign. Check the documentation..

**Comment by z3APA3A** [comment]
And user comma-delimited list of IPs
