### ISSUE TITLE
Сборка для Linux

### ISSUE THREAD

**Issue by tz4678** [z3APA3A/3proxy#502]
Какой вообще смысл выкладывать сборки для винды, если количество виндовых серверов стремится к статистической погрешности?

**Comment by tz4678** [comment]
Сборки можно выполнять через github flow:

https://github.com/tz4678/pscan/blob/master/.github/workflows/release.yml

**Comment by Vision20202** [comment]
Смысл такой, что люди активно используют и windows версии.

**Comment by z3APA3A** [comment]
более того, под Windows используется нисколько не реже, просто паттерны разные. Под Linux 3proxy чаще ставят как выделенный сервер. Под Windows, например, 3proxy чаще используется в локальных установках для управления трафиком, например чтобы тестовые среды формировать.

**Comment by z3APA3A** [comment]
Добавил rpm/deb
