### ISSUE TITLE
Separate access.log and error.log?

### ISSUE THREAD

**Issue by Shawn-Tong** [z3APA3A/3proxy#503]
A suggestion. It's better to separate access.log and error.log in different files, just like Nginx and Squid.

```
log /logs/access-%y%m%d.log D
errorlog /logs/error-%y%m%d.log D
```

Thus it will be easier for the administrator to find the problem of the server.

**Comment by z3APA3A** [comment]
You can actually achieve this result with syslog, see syslog logging in 3proxy.
