### ISSUE TITLE
Проксирование WebSocket

### ISSUE THREAD

**Issue by Jen0k** [z3APA3A/3proxy#504]
Добрый день.

Заметил, что не проксируется трафик websocket'ов через http прокси.

Хост для теста: https://websocketstest.com
Запрос из консоли браузера:
```
wss://websocketstest.com/service
GET

Host: websocketstest.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://websocketstest.com
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: tS90AETz/3M0tSX60DLrJA==
Connection: keep-alive, Upgrade
Cookie: _ws_test_session=BAh7BzoPc2Vzc2lvbl9pZEkiJWJkODlmMzJiY2VmMmVhYTQ4MTk5NTA4YjgzNmVlNTlkBjoGRUY6CGNpZGkEU2CGAQ%3D%3D--a6c2388c967ff8e212b940bf1873427ec2caf02f
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```

Согласно спецификации должен вернуться ответ типа такого:
```
HTTP/1.1 101 Web Socket Protocol Handshake
Upgrade: WebSocket
Connection: Upgrade
Sec-WebSocket-Origin: http://websocketstest.com
Sec-WebSocket-Location: ws://websocketstest.com/service
Sec-WebSocket-Protocol: service
```

Или такого:
```
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: s3pPLMBiTxaQ9kYGzzhZRbK+xOo=
Sec-WebSocket-Protocol: service
```
После чего через установленное соединение должен происходить двухсторонний обмен произвольными данными. Однако при запросе через 3proxy соединение дропается без кода ответа.

Техническая возможность предположительно существует, так как я сталкивался с рабочим примером проксирования web-socket'ов через реверс-прокси на базе nginx. Просьба добавть фичу в 3proxy.

Использую последний на текущий момент билд из ветки devel.

**Comment by z3APA3A** [comment]
А что таки в GET? ты транспарентный запрос делаешь?

**Comment by z3APA3A** [comment]
wss никак не может попасть в прокси, он идет с шифрованием. Вебсокеты в прокси могут попасть только транспарентно по 80му порту (не wss, они идут на 443й). Если прокси в браузере прописан, то вебсокеты должны идти через CONNECT (https://tools.ietf.org/html/rfc6455#section-4.1 пункт 3) даже если они без шифрования. CONNECT в 3proxy разумеется реализован и ему все равно что подключать.

**Comment by Jen0k** [comment]
В теле запроса GET нет ничего. 

Как я понимаю, предполагается, что обмен запросами с HTTP заголовками нужен только чтобы клиент и сервер договорились, что соединение будет использоваться как websocket, после чего через него могут идти любые, хоть бинарные, данные в обе стороны, по сути туннель. Хотя я могу ошибаться в деталях реализации.

Живой пример можно увидеть в консоли браузера на https://websocketstest.co просто обновив страницу, запросы вебсокетов обычно подписаны (в mozilla в столбце "инициатор").

Скриншот: https://ibb.co/tpBcbjr

**Comment by z3APA3A** [comment]
Так все-таки, как у тебя трафик из браузера в прокси пропадает? Что в логах? Проблем с веб-сокетами быть не должно, браузер делает для них CONNECT-запрос так же, как для https://. Если ты используешь какие-то прокси-плагины, то проблема скорей всего в плагине, на стороне прокси не требуется дополнительной обработке для ws, если только это не транспарентно перенаправленный запрос.

**Comment by z3APA3A** [comment]
Между wss и https для прокси вообще нет разницы, оно идет внутри TLS и прокси в принципе не может знать что там - wss или https.

**Comment by Jen0k** [comment]
Настройки установлены вручную в браузере Mozilla Firefox 77.0.1 под Linux Mint 19.3, хотя под виндой аналогичное поведение.

![Браузер](https://user-images.githubusercontent.com/6694201/90528423-4569a580-e17b-11ea-9530-e97458d8c551.png)

Конфиг прокси:
```
pidfile ./3proxy.pid

nscache 65636
timeouts 1 5 30 60 180 1800 15 60

log ./logs/3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
rotate 30

flush

auth strong
include ./users/userlist.txt

maxconn 1024

proxy -p666
socks -p668
```

В логе подключения вижу:
`1597762357.420 PROXY.666 00000 ****** **.**.**.**:45276 **.**.**.**:443 2233 852 0 CONNECT_websocketstest.com:443_HTTP/1.1`

Соответствующие порты на файволе хоста открыты:
```
**.**.**.** 666/tcp     ALLOW       Anywhere                  
**.**.**.** 668/tcp     ALLOW       Anywhere                  
**.**.**.** 668/udp     ALLOW       Anywhere  
```

Значит как минимум браузер понимает, что запрос нужно обернуть в CONNECT, хмм.

**Comment by z3APA3A** [comment]
Ну судя по логам у тебя все нормально прошло через прокси и данные ходили в обе стороны.

**Comment by Jen0k** [comment]
Попробовал с домашнего ПК, где точно нет никаких корпоративных файрволов - картина та же.

Возможно у меня что-то не так с конфигурацией самого хоста с проксёй, было бы здорово проверить на другом инстансе результат запроса к https://websocketstest.co/. Попробую вечером поднять тестовый нулёвый голый инстанс и проверю.

**Comment by z3APA3A** [comment]
Я посмотрел, FF по умолчанию прописывает не только HTTP/HTTPS но и SOCKS прокси и для wss в такой конфигурации пытается лезть через SOCKS. Если не прописывать SOCKS, то все нормально.

**Comment by Jen0k** [comment]
Спасибо, помогло!
