### ISSUE TITLE
Как выбрать подключение для 3proxy?

### ISSUE THREAD

**Issue by ahammers88** [z3APA3A/3proxy#505]
Всем привет!
Имеется компьютер с двумя подключениями:

    192.168.0.101 (ip от роутера, выход в интернет)
    192.168.102.48 (vpn)

Подскажите пожалуйста, как сделать так, что бы 3proxy раздавал интернет только с VPN, так что бы несколько компьютеров в моей локальной сети могли через прокси пользоваться VPN.

**Comment by z3APA3A** [comment]
В 0.9 под Linux/Unix можно использовать -DeINTERFACE для биндинга к интерфесу (прокси должен быть запущен от root, без suid / chroot в конфиге), либо можно использовать биндинг по IP (указать внешний интерфейс -e или external) и настроить source routing системными средствами. В Windows обычно достаточно использовать биндинг по IP.
