### ISSUE TITLE
Current open file ulimits are too low

### ISSUE THREAD

**Issue by valkiriy** [z3APA3A/3proxy#506]
Приветствую. Когда ставлю maxconn 10000 то 3прокси ругается ошибкой "[line 12] Warning: current open file ulimits are too low (cur: 10000/max: 10000), maxconn requires at least 16000 for every running service. Configure ulimits according to system documentation" хотя все лимиты в системе увеличены. ОС UBUNTU 18.04
![image](https://user-images.githubusercontent.com/1162517/91300316-c04e4400-e7ab-11ea-8014-b5000c964837.png)
 
![image](https://user-images.githubusercontent.com/1162517/91300423-ed025b80-e7ab-11ea-8735-f16a74c8c1a3.png)

в /proc/sys/fs/file-max так же увеличино. Куда еще Копать?

и второй вопрос - возможно ли что изза нехватки ресурсов вылетает на проксях 502 ошибка?

**Comment by z3APA3A** [comment]
https://3proxy.ru/highload.asp

в линуксах с systemd для сервисов лимиты конфигурируются отдельно через user.conf / system.conf, см. документацию своего дистрибутива.
502 вполне может вылетать из-за нехватки ресурсов.
