### ISSUE TITLE
Block all traffic except one website

### ISSUE THREAD

**Issue by mntnrk** [z3APA3A/3proxy#509]
Hi,

Tried to find information in the manual without any luck.

Is it possible to block all traffic but leave one website to have access to? The problem is that whenever my LAN connection drops, I use up all of my mobile data.

**Comment by ezbik** [comment]
Sure it is possible. There should be 2 rules following each other:

Allow That_website
deny other_websites

And of course, for proper website rendering, you may want  to allow all the website's dependant sub-elements (images, CSS, embedded content) which may come from different 3rd party websites.

**Comment by z3APA3A** [comment]
```
allow * * sitename,*.another.site,1.2.3.4
deny *
```
