### ISSUE TITLE
pam + разные сервера

### ISSUE THREAD

**Issue by myworking82** [z3APA3A/3proxy#51]
Добрый день. Скажите пожалуйста, при pam авторазации, возможно ли каким-то образом pam модулю указать с какой именно прокси пришла авторазация?............................суть в том, что нам нужно как разделять с авторизаци по разным проксям отдельно.

**Comment by z3APA3A** [comment]
plugin "pamauth.so" start service_name
насколько я понимаю, можно идентифицировать сервис 4м параметром. Оно? Или имеется ввиду разделять аутентификацию по разным сервисам в рамках одного инстанса 3proxy?

**Comment by myworking82** [comment]
совершенно верно, в рамках одного инстанса нужно

**Comment by z3APA3A** [comment]
Но параметр тот? Если в нем можно будет использовать спецификаторы аналогичные logformat, например номер порта  - этого будет достаточно?

**Comment by myworking82** [comment]
сегодня буду пробывать, позже отпишу

**Comment by myworking82** [comment]
врнее не так, как мне пож каждый прокси отдельно прописакть отдельные параметры для авторизации, например для proxy свой будет "plugin "pamauth.so" start service_name", а для socks свой будет "plugin "pamauth.so" start service_name"?

**Comment by z3APA3A** [comment]
Пока никак. Пока надо понять, решит такая возможность, если ее добавить, твою проблему, или нет.

**Comment by myworking82** [comment]
может я сформулирую вопрос по другому, как я могу разделить отдельно авторизацию по видам просей, что бы была возможность разрешать конекретному юзеру ломится лишь на конкретную проксю?

**Comment by z3APA3A** [comment]
allow user1
proxy -p1
flush
allow user2
proxy -p2

**Comment by myworking82** [comment]
речь идет о пам авторизаловке с таким функионалом

**Comment by myworking82** [comment]
тоесть есть пам, но мне нужно юзеров разделить по проксям, что бы одни имели доступ к одной и адругие к другой, а в самом паме я смогу уже разделить их по группам

**Comment by z3APA3A** [comment]
Я с PAM не работал и плагин для PAM в unsupported. Но я могу его поправить как писал выше - чтобы в строке, которая сейчас задается статически как  service_name одна на все службы можно было использовать форматные спецификаторы, в частности IP и порт прокси. Мне прежде чем так делать, надо понять решит это твою задачу или нет.

**Comment by myworking82** [comment]
а динамика по клиентам каким-то образом есть, тоесть что бы добавить юзвера или удалить без рестарта сервера (инстанса)?

**Comment by z3APA3A** [comment]
нет, нельзя. Но рестарт можно делать без простоя и обрыва существующих подключений.

**Comment by myworking82** [comment]
а каким образом?

**Comment by z3APA3A** [comment]
через SIGUSR1, веб-интерфейс (admin) или команду monitor на файл

**Comment by myworking82** [comment]
хорошо, будем иметь в виду, спс

**Comment by z3APA3A** [comment]
Так функционал с pam'ом-то нужен?

**Comment by myworking82** [comment]
нужен, только в том ракурсе что мы выше расписали
