### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by xuxin18** [z3APA3A/3proxy#510]
hello, Some problems have bothered me for a long time.I want to set whitelist，just like this：

### 
daemon
log /var/log/3proxy.log D
rotate 30
maxconn 10000
fakeresolve
config /root/3proxy.cfg
monitor /root/3proxy.cfg

allow * * *.google.com
deny *

users "174.129.75.182:CL:password1"

auth strong
allow 174.129.75.182
parent 1000 http 174.129.75.182 20001 user2 password2

allow none
proxy -p20004
###

but it can't work，I can't access the Google.com.
What to use in that case?
Thanks.

**Comment by z3APA3A** [comment]
probably, you mean
`allow * * *.google.com,google.com`
All allow/deny commands after 

`deny *`

are useless, I'm not sure what exactly do you expect from this config.
