### ISSUE TITLE
High load 3proxy configuration

### ISSUE THREAD

**Issue by clintnetwork** [z3APA3A/3proxy#512]
Hi,

We are using 3proxy from a certain time and we have some difficulties with high load situation, these problemes happens:

- Sometime the page cannot load and this error is shown: `Secure Connection Failed` or `Connection reset`

We does not success to have a correct high load setup, hope you can help us @z3APA3A!

Thank you

**Comment by clintnetwork** [comment]
Problem fixed, we had a `connlim` parameter too low, anyway if you have some tips to improve high load configuration 
we would be very grateful

**Comment by ezbik** [comment]
Make sure you set higher limits in systemd service scope. Your ulimit -n 
command showed the limit in the current user session, which is different.

**Comment by z3APA3A** [comment]
Check https://3proxy.ru/highload.asp
