### ISSUE TITLE
Need some help on configuring 4G proxy

### ISSUE THREAD

**Issue by mntnrk** [z3APA3A/3proxy#513]
Hello,

I cannot get a 4G proxy to work, asking for help as I cannot proceed and unable to find a solution by myself and reached a dead end.

I did a clean install of Raspberry Pi, configured 3proxy, added Huawei e3372h. When I test the proxy on Jarvee it shows that it is valid, but when I try to browse using an embedded browser, I get a blinking screen (black/white).

Log after trying to connect:

```
200910144049.021 3128 00000 - 0.0.0.0:3128 0.0.0.0:0 0 0 0 Accepting connections [997/3066102880]
200910144110.829 3128 00000 - 192.168.1.229:63104 157.240.221.174:443 700 14358 0 CONNECT www.instagram.com:443 HTTP/1.1
```
I am connected to Raspberry through SSH (wifi) on my local network, but when I try checking IP of the Raspberry Pi using `curl ipinfo.io/ip`, it shows the IP of 4G and not my local IP. 

my 3proxy configuration:
```
#! /usr/local/bin/3proxy
daemon
nserver 8.8.8.8
nscache 65536
timeouts 1 5 30 60 180 15 60
users login:CL:pass
log /var/log/3proxy.log
rotate 30
setgid 13
setuid 13
auth none
allow login
proxy -p3128 -n -a
flush
```

Do I have to do something with IP route?
I haven't touched this, but it is configured like this:
```
default via 192.168.3.1 dev eth0 proto dhcp src 192.168.3.10 metric 203 
default via 192.168.1.1 dev wlan0 proto dhcp src 192.168.1.20 metric 304 
192.168.1.0/24 dev wlan0 proto dhcp scope link src 192.168.1.20 metric 304 
192.168.3.0/24 dev eth0 proto dhcp scope link src 192.168.3.10 metric 203 
```

Thank you in advance 🐙

**Comment by fastiovanu** [comment]
Try to open other website. The log says the config is working.

**Comment by z3APA3A** [comment]
This log shows successful connection. Check if client can access the proxy and is configured to use the proxy. If there is no log records for client activity, it means there are no reqests from client to proxy.
