### ISSUE TITLE
Нестабильная работа мобильных прокси.

### ISSUE THREAD

**Issue by DenysCat** [z3APA3A/3proxy#514]
Доброго времени суток. Использую 3proxy, в качестве утилиты, для создания мобильных прокси. Недавно заметил, что при большом количестве запросов начинают появляться ошибки (00013, 00093, 00092 и подобные). Причем, если перезапускать службу, первые 30 секунд проблем нет вообще. Пробовал фиксить по разному: увеличил maxconn, увеличил лимиты в windows, прописывал netserver 8.8.8.8. Ничего не помогает.
Конфиг:
monitor C:\3proxy\bin64\3proxy.cfg
maxconn 99999
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
log C:\3proxy\3proxy.log D
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
auth iponly
allow * 192.168.x.x
proxy -n -a -p1111 -i192.168.x.x -e192.168.x.100
flush

**Comment by z3APA3A** [comment]
см https://3proxy.ru/highload.asp, по описанию скорей всего не хватает каких-то ресурсов. Коды ошибок есть здесь
https://3proxy.ru/howtoe.asp#ERRORS

**Comment by DenysCat** [comment]
Да, видел ошибки. Просто понять не могу, из-за чего возникают. Насколько
понял, из-за того, что ПК не вывозит. В любом случае, спасибо.

пн, 14 сент. 2020 г. в 11:12, Vladimir Dubrovin <notifications@github.com>:

**Comment by DenysCat** [comment]
П.С., также заметил, что у меня на 3прокси пинг повышается. Это тоже может
быть вызвано слабым железом?

пн, 14 сент. 2020 г. в 11:12, Vladimir Dubrovin <notifications@github.com>:

**Comment by DenysCat** [comment]
В данный момент попоробовал на более мощном ПК. Проблема осталась.

пн, 14 сент. 2020 г. в 11:12, Vladimir Dubrovin <notifications@github.com>:

**Comment by z3APA3A** [comment]
Мощность железа здесь, скорей всего, непричем. Держать 99999 соединений в принципе невозможно на одном IP, прочитай статью-то. Сколько реально идет параллельных соединений и суммарно трафика (можно, например, по логам прокси посчитать суммарный траффик за час)

**Comment by DenysCat** [comment]
Спасибо. Насколько понял, проблема в google dns. Можете посоветовать, как в конфиг добавить fakeresolve? Просто local caching recursor через простой windows по нормальному сделать не выходит.

**Comment by z3APA3A** [comment]
ошибки 00013, 00093, 00092 никак не связаны с DNS (если только DNS не возвращает какие-то поддельные ответы, например в случае фильтра Роскомнадзора).
fakeresolve можно использовать только в том случае, если все запросы уходят на родительский прокси
https://3proxy.ru/faqr.asp#NAMES

**Comment by DenysCat** [comment]
Просто я думаю, что все упирается в ограничение 8.8.8.8. Так как при смене ip на модеме, при перезагрузке службы (noforce не включен) или же при ожидании проблема пропадает на время. Что проблема по железу, тоже не думаю. На 1 прокси максимум приходит за раз 500 запросов, а этих прокси у меня в данный момент всего 6 работает. В целом, все достаточно запутанно. Я даже грешил на операторов, так как с некотрыми глюков меньше, с некотрыми больше.

**Comment by z3APA3A** [comment]
Не думаешь, что проблема может быть на стороне сотового провайдера, который ограничивает коннекты или на самом модеме (например маленькая таблица для NAT)?

**Comment by DenysCat** [comment]
Думал. Но могу привести пример. При многократной попытке пройти speedtest, если делать это через 3proxy, у меня очень сильно растет пинг. Если же это делать напрямую, то пинг всегда стабилен. Поэтому ищу проблему именно в конфиге.

**Comment by z3APA3A** [comment]
Пинг не ходит через прокси. Если растет пинг, то проблемы не в прокси.

**Comment by DenysCat** [comment]
Понял. Скорее всего, вся проблема в роутере и в операторе, а не в днс и прочем. Спасибо.

**Comment by z3APA3A** [comment]
Да может и вообще проблемы нет, например ты нагружаешь так, что выжираешь весь канал, а таймауты у тебя не очень большие, поэтому они начинают стрелять.
