### ISSUE TITLE
3proxy stop after i connect and open page other than google

### ISSUE THREAD

**Issue by iamat8080** [z3APA3A/3proxy#515]
if I make the proxy connection more than 350 ipv6
and after I try to connect and open whatismyip 3proxy stop working 
but surfing google.com and searching there no problem
and I can see service not running netstat -tunlp
amusing centos7x64

**Comment by z3APA3A** [comment]
probably, proxy fails to start in your configuration (try to run it manually and check for error output) and you do not use proxy to accecss google.

**Comment by iamat8080** [comment]
i checked all proxies were running fine I used google for speed testing if I open a website other than google it's crash and stop
