### ISSUE TITLE
Ошибка при компиляции Linux 3.16.0-11-amd64 on x86_64 Debian 8 , как победить?

### ISSUE THREAD

**Issue by LDRunner355** [z3APA3A/3proxy#516]
Hi

Ошибка при компиляции Linux 3.16.0-11-amd64 on x86_64 Debian 8 , как победить? 

make -f Makefile.unix

cat Makefile.unix > src/Makefile.var                                                                                                                                       

make[1]: Entering directory '/home/3proxy-0.8.13/src'                                                                                                                      

gcc -o 3proxy -O2 -fno-strict-aliasing -pthread   3proxy.o mainfunc.o auth.o conf.o datatypes.o srvproxy.o srvpop3p.o srvsmtpp.o srvftppr.o srvsocks.o srvtcppm.o srvicqpr.

o srvudppm.o sockmap.o sockgetchar.o myalloc.o common.o mycrypt.o md5.o md4.o base64.o ftp.o smbdes.o ntlm.o stringtable.o srvwebadmin.o srvdnspr.o plugins.o              

conf.o: In function `h_plugin':                                                                                                                                            

/home/3proxy-0.8.13/src/conf.c:1296: undefined reference to `dlopen'                                                                                                       

/home/3proxy-0.8.13/src/conf.c:1298: undefined reference to `dlsym'                                                                                                        

collect2: error: ld returned 1 exit status                                                                                                                                 

Makefile.inc:159: recipe for target '3proxy' failed                                                                                                                        

make[1]: *** [3proxy] Error 1                                                                                                                                              

make[1]: Leaving directory '/home/3proxy-0.8.13/src'                                                                                                                       

Makefile.inc:6: recipe for target 'all' failed                                                                                                                             

make: *** [all] Error 2

**Comment by z3APA3A** [comment]
Использовать Makefile.Linux
