### ISSUE TITLE
Подсчет и ограничение общего трафика (входящего и исходящего)

### ISSUE THREAD

**Issue by srvh** [z3APA3A/3proxy#517]
Сделайте, пожалуйста, подсчет и ограничение общего трафика (входящего и исходящего) в сумме.
Можно по аналогии с countin и countout сделать переменную countall.

Параметры оставить такие же, как для countin (то есть номер счетчика, ограничение в Мегабайтах, лимит на день, месяц, год или N - без ограничения времени).

**Comment by z3APA3A** [comment]
Попробуй текущий devel, должно работать с https://github.com/z3APA3A/3proxy/commit/d0725163d110669d5e283f0a22f458a8b3489cea (но не тестировал)

**Comment by srvh** [comment]
Скачал devel репозиторий так:
git clone --branch devel https://github.com/z3APA3A/3proxy

Вижу, что измененные файлы есть.
Затем установил эту сборку.

Добавил строку countall в конфиг
Первые 3 строки countin старые. С ними все работало корректно. 

countin 1/month M 1000000 *
countin 2/day D 1000000 *
countin 3 N 40 12
countall 4 N 100 12

То есть для пользователя с логином 12 ограничение на общий трафик 100 Мб

При рестарте 3proxy выдает ошибку
Unknown command: 'countall' line 5

Если удаляю строку "countall 4 N 100 12" , то 3proxy стартует корректно.

В чем может быть проблема?

**Comment by z3APA3A** [comment]
Убедись, что папки 3proxy не существовало на момент git clone
