### ISSUE TITLE
ошибка прокси 00093

### ISSUE THREAD

**Issue by Boris991420** [z3APA3A/3proxy#519]
Добрый день. У меня возникает частая ошибка на прокси 00093.
Это происходит очень часто.
Настроены мобильные прокси, где исходящее соединение-это ip 4g модема.
Пример  моего конфига
############################
monitor /usr/local/3proxy/mob/server80-192.168.11.100.cfg
daemon
#pidfile /usr/local/3proxy/mob/server80-192.168.11.100.pid
timeouts 1 5 30 60 180 1800 15 60
maxconn 5000
nscache 65535
nserver 192.168.11.1 
log /usr/local/3proxy/mob/log/server80-192.168.11.100.log D
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
rotate 180
archiver rar rar a -df -inul %A %F
connlim 100 0 926157f45a
auth strong
bandlimin 5000000 926157f45a
bandlimout 5000000 926157f45a
users 926157f45a:CL:976f14aa27
allow 926157f45a * $/usr/local/3proxy/whitelist62.list * * *
deny 926157f45a * * * * * *
proxy -s0 -n -a -p42501 -i192.168.1.72 -e192.168.11.100
socks -s0 -n -a -p46433 -i192.168.1.72 -e192.168.11.100
monitor /usr/local/3proxy/whitelist62.list
flush
############################
и таких конфигов на сервер много-для каждого исходящего ip модема "-e" , создан 1 конфиг
1 модем - 1 конфиг
это сделано чтобы у каждого прокси были свои днс от моб оператора.
############################
ps -fe|grep "[3]proxy"
root      1832     1  0 окт03 ?     00:00:07 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.12.100.cfg
root      1848     1  0 окт03 ?     00:00:06 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.15.100.cfg
root      1867     1  0 окт03 ?     00:00:06 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.19.100.cfg
root      1876     1  0 окт03 ?     00:00:10 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.22.100.cfg
root      1886     1  0 окт03 ?     00:00:11 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.24.100.cfg
root      1927     1  0 окт03 ?     00:00:52 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.34.100.cfg
root      1931     1  0 окт03 ?     00:00:12 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.35.100.cfg
root      1942     1  0 окт03 ?     00:00:07 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.37.100.cfg
root      1950     1  0 окт03 ?     00:00:07 /usr/local/3proxy/3proxy /usr/local/3proxy/mob/server80-192.168.39.100.cfg
############################
каждый модем делает обрыв соединения (смену внешнего ip что выдаёт на БС)
В момент смены ip часто возникают ошибки 00093. 
Если клиент работает с целевым сайтом instagram.com, то запросы падают с этой ошибкой, т.е под прокси сайт instagram.com не доступен. Все остальные сайты открывает.
Помогает рестар процесса 3proxy, но каждый раз рестартить процессы -по мне не очень хорошее решение.
Возможно нужно отключить опцию nscache в конфиге ? Подскажите пожалуйста.

Привожу логи с ошибкой
############################
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:13 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:14 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:15 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:16 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:17 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:19 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:20 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:21 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:22 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:23 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:25 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:26 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:27 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:28 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:29 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:31 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:32 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443
88.198.219.40 - 926157f45a [04/Oct/2020:12:40:33 +0300] "CONNECT i.instagram.com:443" 00093 0 0 SOCK5/192.168.11.1:443`
############################
Прошу подсказать как устранить данную ошибку.

**Comment by z3APA3A** [comment]
93 это ожидаемая ошибка в момент смены IP адреса, т.к. смена адреса приводит к обрыву всех установленых соединений. Если соединение долго висело без передачи данных, то ошибка может быть получена после, т.к. стороны не знают что что-либо изменилось. Логгируйте длительность соединений, если соединение началось до рестарта модема - то ничего с этим делать не надо.
