### ISSUE TITLE
Whitelist with Transparent Proxy

### ISSUE THREAD

**Issue by DoM1niC** [z3APA3A/3proxy#520]
like #510

I see the Transparent Proxy over IPTables dosn't resolve the DNS Entries with my whitelist, SOCKSv5 works fine with this, but resolve directly if I open a Website from my whitelist, native IPs so works too with the **tcppm**, what is the trick to get it working with **tcppm** & Domains?

```
log /opt/3proxy/log D
rotate 30
plugin /opt/3proxy/bin/TransparentPlugin.ld.so transparent_plugin
internal 10.1.0.1
external 24.134.17.209

nserver 127.0.0.1
nscache 65536
auth iponly

#bandlimin 1007600 * *
bandlimout 10007600 * 10.1.0.0/24
bandlimout 10007600 * 10.10.0.0/24

bandlimout 20007600 * 192.168.0.0/16
bandlimin 20007600 * 192.168.0.0/16

allow * * * 53
allow * * * 853
allow * * * 8080
allow * * * 8443
allow * * $/opt/3proxy/whitelist 80
allow * * $/opt/3proxy/whitelist 443
allow * * * 80
allow * * * 443
deny * * *
#allow *

transparent
tcppm -i10.1.0.1 4008 127.0.0.1 11111
#udppm -i10.1.0.1 4008 127.0.0.1 11111
flush
```

**Comment by z3APA3A** [comment]
3proxy never resolves names in ACL, it compares name in client request  with a name in ACL and it's only possible if client request contains the name. In the case of transparent redirection , name is never known to 3proxy, only IP addresses can be used for ACLs.
