### ISSUE TITLE
Impossible to deal with more than 10 proxies simulatenously

### ISSUE THREAD

**Issue by vanitysys28** [z3APA3A/3proxy#521]
Hello,

I have multiple chrome profiles all linked to different IPv6 proxies.
Everything is working fine until I start to use more than 10 profiles simultaneously.

These are my first lines of my config file. I have no maxconn set (so default 100 is applied), and even when I tried to set a higher number, didn't fix the issue. Will increase the nscache6 fix the issue?

nserver [2001:4860:4860::8888]  
nserver [2001:4860:4860::8844]
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60

Here is an example of my logs where there are error codes that start to appear.
I see some errors 11 and 100, but after looking at the error code reference, I don't seem to find a solution..
What about the "Too many open files" error I see?

Thanks in advance for your answer

![Sans titre](https://user-images.githubusercontent.com/20629483/95391119-c715be00-08f6-11eb-8dbb-42851851beb8.png)

**Comment by GoldLine1337** [comment]
hi just type ulimit -n 65535

**Comment by GoldLine1337** [comment]
then reboot your server

**Comment by z3APA3A** [comment]
Read this article: https://3proxy.ru/highload.asp
