### ISSUE TITLE
3proxy not work

### ISSUE THREAD

**Issue by verngardner1025** [z3APA3A/3proxy#523]
hello 3proxy installation fails, there is an error in your last update

please check

[
![Screenshot_2](https://user-images.githubusercontent.com/2398806/95597790-c183b980-0a57-11eb-8db8-b833071ec8b6.png)
](https://prnt.sc/uw7vtw)

**Comment by z3APA3A** [comment]
probably you use proxy.h from different 3proxy version, https://github.com/z3APA3A/3proxy/blob/devel/src/proxy.h does not have this string. See "fatal" message on git clone. Remove the existing directory before the clone.

**Comment by verngardner1025** [comment]
thank you so much.
