### ISSUE TITLE
/48 IPV6 issue

### ISSUE THREAD

**Issue by GoldLine1337** [z3APA3A/3proxy#524]
Heu Z3APA3a, There is a issue that 3proxy doesnt read if the /48 exists in Ifconfig or the networking.
but if you add a single ip/128 it reads it and it works

and also how can I use parent with IPV6?

**Comment by z3APA3A** [comment]
Sorry, but I don't understand this record. Provide a configuration example, expected behavior and actual result with problem description.

you can use IPv6 anywhere you can use IPv4 in the same way.

**Comment by GoldLine1337** [comment]
Okay here is the configuration of /etc/network/interfaces
auto lo
iface lo inet loopback
auto eth0
address 94.156.128.215
gateway 94.156.128.1
netmask 255.255.255.0
dns-nameservers 8.8.8.8 8.8.4.4
up ip -6 route add 2a07:5740:0100:0000:0000:0000:0000:0001 dev eth0
up ip -6 route add default via 2a07:5740:0100:0000:0000:0000:0000:0001
up ip -6 route add 2a07:5740:138/48 dev eth0


And.. 3proxy.cfg



#!/usr/local/bin/3proxy
daemon
pidfile /usr/local/etc/3proxy/3proxy.pid
nserver 1.1.1.1
nserver 1.0.0.1
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
internal 0.0.0.0
external 0.0.0.0
authcache ip 60
auth iponly
allow *
proxy -p4000 -6 -a -n -i0.0.0.0 -e2a07:5740:138:7bff:b85f:354e:23b6:c6d6
proxy -p4001 -6 -a -n -i0.0.0.0 -e2a07:5740:138:7bff:b8ef:354e:23b6:c6b6
proxy -p4002 -6 -a -n -i0.0.0.0 -e2a07:5740:138:7bff:b8af:354e:23b6:c6f6

**Comment by GoldLine1337** [comment]
If I add a single IP it works but full block it doesnt.

**Comment by z3APA3A** [comment]
This question is Linux related, not 3proxy related. I'm not Linux  guru, but I think addresses are added via `ip addr add`, `ip route add` marks network as directly connected rather than adds IPs to interfaces.

**Comment by z3APA3A** [comment]
There is a difference beween routing and binding. Routing the subnetwok to local interface is not enough for TCP/IP stack to consider the addresses as bound to interface. Addresses must be both routed and bound.

Sorry, but I have nothing to add, your question relates to Linux IPv6 stack rather than to 3proxy. You can ask someone who wrote this paper.

**Comment by ezbik** [comment]
I personally have positive experience with binding 3proxy (or was it squid, 
anyways) to tons of unassigned ipv6's when /48 subnet was routed to 
loopback device, without assigning each particular ipv6 to any interface. 
It is called 'non local binding'.
