### ISSUE TITLE
how to achieve the specified domain name list shunt?

### ISSUE THREAD

**Issue by chenwc520** [z3APA3A/3proxy#526]
Excuse me, how to achieve the specified domain name list shunt? Want to achieve part of the target address to go to the local network, others take the parent agent. Thank you

**Comment by z3APA3A** [comment]
you can use `nsrecord` command to resolve name to given IP. For more flexibility you can use `parent 1000 tcp ...` with given name as a target, e.g. to redirect traffic only for some users.
