### ISSUE TITLE
How to use 3Proxy to connect over VPN?

### ISSUE THREAD

**Issue by InSide24** [z3APA3A/3proxy#528]
Hello, after i tried it for a few days (didnt sleept :/)

I know this is possible but i cant get it running.

I want to connect to my Server over IP + Port with ip authentication and user authentication.

I can get it running that i can switch between different external ips over different ports. Each for IPv4 & IPv6.

But now im trying to send every request as http over internal ip to vpn provider to Target destination.

i checked your Documentations and edited my .cfg

As i know i need to work with parent command.

My cfg (only the connection part)

auth iponly strong
allow * IPofMyComputer
allow user
parent 1000 connect IP PORT Username Password
proxy -a -p10001 -iSERVERIP

It kinda works, but it wont resolve it over the parent, it will always output the SERVERIP not the IP from the VPN Provider. (http is possible at my VPN Provider)

Whats the solution here?

Thanks for any help

**Comment by z3APA3A** [comment]
"connect" requires IP address, you should use "connect+" and "fakeresolve":

```
auth iponly strong
allow * IPofMyComputer
allow user
parent 1000 connect+ IP PORT Username Password
fakeresolve
proxy -a -p10001 -iSERVERIP
```

**Comment by InSide24** [comment]
Check Attached Screenshots....
With fakeresolve it doesnt connect, without it does connect to my server ip

https://prnt.sc/v06dh0
https://prnt.sc/v06e79

Thanks man

**Comment by z3APA3A** [comment]
with fakeresolve you can not use hostnames. Use ip address instead of the name or put fakeresolve after parent (but in last case you will not be able to reload config without restarting 3proxy)

**Comment by InSide24** [comment]
I tried it over your solution, can you add me on telegram?
For sure we pay you ;)

https://t.me/nicerdizer
