### ISSUE TITLE
Use 3proxy create residential proxy with a Raspbery

### ISSUE THREAD

**Issue by xuan2261** [z3APA3A/3proxy#533]
![image](https://user-images.githubusercontent.com/17797687/96362825-465a8b80-115a-11eb-8659-ab61fbb7d339.png)
Hi everybody.
Can anyone give me instructions on how to use 3proxy to create a residential proxy using Raspbery similar to the one above?
Thank you very much.

**Comment by z3APA3A** [comment]
Use 3proxy as a proxy server.

Sorry, but your question is too common. In general you need to:
1. Formulate the functionality you want to achieve in the terms of traffic flows and restrictions
2. Read 3proxy documentation on how to implement the functionality required.
