### ISSUE TITLE
3proxy issue

### ISSUE THREAD

**Issue by GoldLine1337** [z3APA3A/3proxy#534]
Hi, there is an issue when you try add a fresh IP to the config and you restart... you have to send 2 requests. for the first request it times me out and the second one it works why is this happening, it happens for once when I change IPs, I need a fix for this because I change ips so much.

**Comment by GoldLine1337** [comment]
> Hi, there is an issue when you try add a fresh IP to the config and you restart... you have to send 2 requests. for the first request it times me out and the second one it works why is this happening, it happens for once when I change IPs, I need a fix for this because I change ips so much.

==edited
I have to do this for every port I open

**Comment by z3APA3A** [comment]
Describe in details:
1. Your configuration (network, 3proxy)
2. Your actions (step-by-step)
3. Expected result
4. Actual result.
