### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by Thiencau20** [z3APA3A/3proxy#536]
Hello,
I have setup 3proxy server accroding to this script https://github.com/dukaev/ipv4-ipv6-proxy/blob/master/README.md
On CentOs7
I check port on this site https://www.yougetsignal.com/tools/open-ports/ and it open
I curl proxy xxx.xxx.xxx.xxx:10000 and it work
but when I add it to browser(chrome,firefox) and load check ip connection is ERR_PROXY_CONNECTION_FAILED. Also check port and now it closed

I also open port in firewall,iptable too!

And After I reboot server from console vutrl, and proxy work again in curl mode but in browser it still not connect and port close too!

Here is nmap
https://prnt.sc/v3ksnc

How to resolve this issue ?

**Comment by z3APA3A** [comment]
Sorry, but I can't help you with 3rd party scripts. Check if 3proxy is running, check 3proxy configuration, check the port is open and connections to your proxy with netstat. It's quite possible you created an open proxy configuration and your installation was abused.
