### ISSUE TITLE
input Ipv4 and exit with IPv6

### ISSUE THREAD

**Issue by Thiencau20** [z3APA3A/3proxy#537]
Hello, How to make proxy is Ipv4 with port and exit with Ipv6. I have use this setting

auth strong
allow usrCKBir
proxy -6 -n -a -p10000 -ixxx.xxx.xxx.xxx -e2001:19f0:6001:25ea:3bd8:bae4:65cd:d403
flush

but when check 3proxy service it inactive.

Remove -6 and start 3proxy service again and it active and proxy working but it point to IPv4 not IPv6

How to make input Ipv4 and exit with Ipv6 ?

Thank you

**Comment by z3APA3A** [comment]
Add "log" and try to start 3proxy manually with this config, check the output.

**Comment by Thiencau20** [comment]
> 
> 
> Add "log" and try to start 3proxy manually with this config, check the output.

`Redirecting to /bin/systemctl status 3proxy.service
● 3proxy.service - 3proxy Proxy Server
   Loaded: loaded (/usr/lib/systemd/system/3proxy.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2020-10-21 12:22:52 UTC; 2s ago
  Process: 10050 ExecStart=/usr/bin/3proxy /etc/3proxy.cfg (code=exited, status=0/SUCCESS)
 Main PID: 10051 (code=exited, status=0/SUCCESS)

Oct 21 12:22:52 vultr.guest 3proxy[10050]: -lFILENAME log to FILENAME
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -bBUFSIZE size of network buffer (default 4096 for TCP, 16384 for UDP)
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -t be silent (do not log service start/stop)
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -iIP ip address or internal interface (clients are expected to connect)
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -eIP ip address or external interface (outgoing connection will have this)
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -pPORT - service port to accept connections
Oct 21 12:22:52 vultr.guest 3proxy[10050]: -n - no NTLM support
Oct 21 12:22:52 vultr.guest 3proxy[10050]: Example: proxy -i127.0.0.1
Oct 21 12:22:52 vultr.guest 3proxy[10050]: Service not started on line: 39
Oct 21 12:22:52 vultr.guest 3proxy[10050]: Command: 'proxy' failed with code 40, line 39`

I get this output when checking status 3proxy service

this this is my 3proxy.cfg file

`
auth strong
#allow usrCKBir
proxy -4 -n -a -p10000 -i14x.2x.6x.19x -e2001:19f0:6001:25ea:3bd8:bae4:65cd:d403
flush

#Enable admin web-ui on specified port
admin -p3200
`

**Comment by z3APA3A** [comment]
-4 disables IPv6 support, you can not use IPv6 address with -4.

**Comment by z3APA3A** [comment]
Also, check the version. It looks like you are using the older version without IPv6 support.

**Comment by Thiencau20** [comment]
> 
> 
> Also, check the version. It looks like you are using the older version without IPv6 support.

Yes, It it older version that I install via yum install 3proxy it has only 0.7 version

And I have update new version but check service and got this 👍 

[root@guest ~]# service 3proxy status
Redirecting to /bin/systemctl status 3proxy.service
Unit 3proxy.service could not be found.

**Comment by z3APA3A** [comment]
Use scripts from your system dstribution, replace 3proxy binary only. You can try to contact package maintainer to update 3proxy version to actual one. 0.7 is not supported for quite a long time.

**Comment by Thiencau20** [comment]
> 
> 
> Use scripts from your system dstribution, replace 3proxy binary only. You can try to contact package maintainer to update 3proxy version to actual one. 0.7 is not supported for quite a long time.

Thanks

but I got another issue, after done everything you said
Proxy IPv4 is OK
Proxy IPv6 is OK except I got this when checking in ipv6-test.com
502 Bad Gateway
Host Not Found or connection failed

How to resolve this ? 
Thank you

**Comment by z3APA3A** [comment]
Check the logs, it should have an error code.

**Comment by Thiencau20** [comment]
> 
> 
> Check the logs, it should have an error code.

Thanks for help! I did it!!

**Comment by xbeowulfx** [comment]
@Thiencau20 can you help me how you resolved 502 bad gateway error

**Comment by thanhvodad** [comment]
> > Check the logs, it should have an error code.
> 
> Thanks for help! I did it!!

Giúp tôi với Sư Huynh :(
