### ISSUE TITLE
Проблема с сокс5

### ISSUE THREAD

**Issue by dfgdfsgd** [z3APA3A/3proxy#538]
Проблема следующая.
Использую parent socks5+ с fakeresolve.

Часть соксов не хотят работать при такой конфигурации. Происходит подлючение к parent но не идет трафик. При этом если я меняю конфиг на parent socks5 то все работает хорошо, но днс не резолвится само собой. У родительского сокса вроде нет проблем с днс, при подключении напрямую все резолвится нормально.

И так не со всеми родительскими socks5+, скорее 60/30 в пользу socks5+

С конфигом все норм вроде 

setgid 112
setuid 106

nscache 65536
timeouts 30 30 60 60 180 1800 60 120

daemon

maxconn 1000
auth iponly

allow * {{IPS}}
fakeresolve
parent 1000 socks5+ {{socks}} {{port}}
socks -n -p3128 -a
flush

**Comment by z3APA3A** [comment]
А запрос с --socks5-hostname к проблемному хосту проходит?

**Comment by dfgdfsgd** [comment]
да, проблема именно в socks5+ и fakeresolve.Когда конфиг просто socks5(без + и без fakeresolve) то все работает

**Comment by z3APA3A** [comment]
так еще раз, curl --socks5-hostname parent_proxy:parent_port https://example.com проходит? Если не проходит, значит родительский прокси не поддерживает разрешение имен

**Comment by dfgdfsgd** [comment]
Да, верно
