### ISSUE TITLE
Проблема с сокс5 

### ISSUE THREAD

**Issue by dfgdfsgd** [z3APA3A/3proxy#539]
Проблема следующая. 
Использую parent socks5+ с fakeresolve.  Часть соксов не хотят работать при такой конфигурации. Происходит подлючение к parent но не идет трафик. При этом если я меняю конфиг на parent socks5 то все работает хорошо, но днс не резолвится само собой. У родительского сокса вроде нет проблем с днс, при подключении напрямую все резолвится нормально.  И так не со всеми родительскими socks5+, скорее 60/30 в пользу socks5+  
С конфигом все норм вроде  
setgid 112 
setuid 106  
nscache 65536 
timeouts 30 30 60 60 180 1800 60 120  
daemon  
maxconn 1000 
auth iponly  
allow * {{IPS}} 
fakeresolve 
parent 1000 socks5+ {{socks}} {{port}} socks -n -p3128 -a 
flush

В лог следующие ошибки
00057, 00052, 00065

Через curl socks5-hostname все работает как положенно

**Comment by dfgdfsgd** [comment]
и все время пишет в логе CONNECT_64.233.162.99:443, независимо от ресурса к которому я пытаюсь подключиться

**Comment by z3APA3A** [comment]
Если там ip и этот ip отличен от 127.0.0.2, значит так попросил клиент, т.е. клиент разрешил имя сам.
57 и 52 означает, что не был получен ответ от родительского прокси. 65 в актуальных версиях 3proxy быть не может, возможно ты исользуешь какую-то старую версию. Обнови 3proxy до актуальной версии.

**Comment by z3APA3A** [comment]
В старых версиях 65 означает, что удаленный сокс вернул  статус "CONNECTION REFUSED".

**Comment by dfgdfsgd** [comment]
Но суть в том что через curl все работает нормально, а вот через 3proxy не хочет. Я так подозреваю что софт который стоит на родительском сервере не дружит с 3proxy, почему то( Вот думал этому есть решение. Версия стоит 8.13

**Comment by z3APA3A** [comment]
Я ничем не могу помочь без конкретного примера. Мне надо знать какой запрос клиент сделал в 3proxy, какой запрос 3proxy сделал в родительский сервис и какую ошибку он получил (и желательно почему). Можешь, например, записать дамп трафика между клиентом и прокси и прокси и родительским прокси для одного конкретного запроса?
