### ISSUE TITLE
Запрет сайтов

### ISSUE THREAD

**Issue by fastitua** [z3APA3A/3proxy#54]
Доброе утро!
Используется 3proxy и параметр -e чтобы получить на выходе определенный IP.
Скажите, как можно запретить вход на все сайты кроме google.nl?

Строчка:
```
allow * google.nl * * * *
deny * 
```

не помогает, перезапуск процесса тоже.

**Comment by z3APA3A** [comment]
https://github.com/z3APA3A/3proxy/wiki/How-To-%28%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9%29#ACL

allow * * google.nl
deny

при условии, что auth отличен от none.

**Comment by fastitua** [comment]
```
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
pidfile /var/tmp/3proxy.pid
timeouts 1 5 30 60 180 1800 15 60
users user:CL:user1
users user2:CL:user22
daemon
log /var/log/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /bin/gzip %F
rotate 30
auth strong
flush
#external 0.0.0.0
allow * * google.nl
deny
internal 0.0.0.0
allow user
maxconn 500
....
```
Вот так прописал, но не помогло(

**Comment by z3APA3A** [comment]
А дальше что в конфиге? У тебя там мешанина какая-то

**Comment by fastitua** [comment]
Продолжение

```
maxconn 500
proxy -a -6 -e2a00:_:a7::54b -p40001
auth strong
flush
#external 0.0.0.0
internal 0.0.0.0
allow user2
maxconn 500
#proxy -a -6 -e2a00:_:a7::4f7 -p40005
```

**Comment by z3APA3A** [comment]
А что в логах с момента перезапуска?

**Comment by fastitua** [comment]
Это как посмотреть? В логе после start строчки типа и ничего более:

```
1458545818.832 PROXY.40070 00000 - 0.0.0.0:40070 2a00:_:a7::3ed:0 0 0 0 Exiting_thread
1458545821.922 PROXY.40001 00000 - 0.0.0.0:40001 2a00:_:a7::54b:0 0 0 0 Accepting_connections_[13827/1642608384]
```

**Comment by z3APA3A** [comment]
Значит никто к прокси не коннектился, ты уверен что у тебя клиенты в прокси попадают?

**Comment by fastitua** [comment]
А, я просто вырезал строчки с коннектом, прописал вот так:
```
auth strong
flush
#external 0.0.0.0
allow * * google.nl
deny *
internal 0.0.0.0
```
все сайты отдают 403 ошибку, прописал вот так

```
allow * * google.nl
deny *
flush
internal 0.0.0.0
```
ограничения не работают, как правильно прописать?)

**Comment by z3APA3A** [comment]
flush сбрасывает все правила, которые выше него написаны, не нужен здесь flush вообще.
У тебя и должны возвращать ошибку все сайты кроме google.nl. Что в логах при этом?

**Comment by fastitua** [comment]
Вроде нашел проблему и исправил, поддержка супер у прокси-сервера!
Скажите, а как прописать не только google но и еще домены какие захочу?

`allow * * google.nl, google.com `
если так, то отдает:

`Command: 'allow' failed with code 1, line 15`

**Comment by z3APA3A** [comment]
без пробела, можно использовать звездочки в именах доменов.
