### ISSUE TITLE
socks proxy error 401

### ISSUE THREAD

**Issue by s00ny5** [z3APA3A/3proxy#541]
Hello,

I setup a proxy server but for some reasons the socks wont work.

this is my config:

daemon
nserver 1.1.1.1
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
log /var/log/3proxy.log
logformat "G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T"
auth iponly
flush
allow * {IPS}
proxy
deny *

works perfect with http proxy but with socks I get this in logs:

201023135033.276 12000 00401 - IPv4:56109 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0
201023135033.325 12000 00401 - IPv4:56110 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0

Any help?

Tried on firefox. and this is the error on it:
Secure Connection Failed: PR_END_OF_FILE_ERROR

Regards

**Comment by z3APA3A** [comment]
401 is socks proxy code, not http proxy code, it doesn't match to this configuration. This error code means socks proxy received non-socks request from client. Probably, you are running another 3proxy instance with the socks on the same port. killall 3proxy instances and run 3proxy with valid config, make sure you are not running different proxy types on the same port.

**Comment by s00ny5** [comment]
I dont run multiple 3proxy.
The config for socks is this (I also said when I change..):

daemon
nserver 1.1.1.1
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
log /var/log/3proxy.log
logformat "G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T"
auth iponly
flush
allow * {IPS}
socks
deny *

Log:
201023135033.276 12000 00401 - IPv4:56109 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0
201023135033.325 12000 00401 - IPv4:56110 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0

I use firefox latest version to test the sock proxy.

**Comment by z3APA3A** [comment]
Probably, it means you configured the wrong proxy type / port number in firefox. 'socks' and 'proxy' should use different ports, and should match the ports configured in firefox. Curretly, you configured the port of the socks proxy as http/https proxy in Firefiox.
