### ISSUE TITLE
socks proxy error 401

### ISSUE THREAD

**Issue by s00ny5** [z3APA3A/3proxy#542]
No idea why you closed the other...

I don`t run multiple 3proxy.
The config for socks is this (I also specified in the other issue post that I change for socks):

daemon
nserver 1.1.1.1
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
log /var/log/3proxy.log
logformat "G%y%m%d%H%M%S.%. %p %E %U %C:%c %R:%r %O %I %h %T"
auth iponly
flush
allow * {IPS}
socks -6 -n  -a -p12000 -iIPv4 -eIPv6:2783
deny *

Log:
201023135033.276 12000 00401 - IPv4:56109 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0
201023135033.325 12000 00401 - IPv4:56110 IPv6:0 0 0 0 UNKNOWN 0.0.0.0:0

I use firefox latest version to test the sock proxy.

Regards

**Comment by z3APA3A** [comment]
Sorry, but I have nothing to add to previous reply.  You are running socks proxy, but you are trying to access it as http/https proxy from browser.

**Comment by s00ny5** [comment]
https://prnt.sc/v5ghm7

**Comment by z3APA3A** [comment]
And what about http/htps proxy field?

**Comment by s00ny5** [comment]
Also tried socks4 to select

https://prnt.sc/v5gp1y

Got this in logs for socks5
201023164903.600 12000 00004 - ipv4:57912 ::ffff:34.107.221.82:80 0 0 0 CONNECT ::ffff:34.107.221.82:80
201023164906.709 12000 00004 - ipv4:57913 ::ffff:34.107.221.82:80 0 0 0 CONNECT ::ffff:34.107.221.82:80
201023164906.957 12000 00004 - ipv4:57914 ::ffff:34.107.221.82:80 0 0 0 CONNECT ::ffff:34.107.221.82:80

and socks4
201023165030.924 12000 00100 - ipv4:58031 ::ffff:34.107.221.82:0 0 0 0 CONNECT :0
201023165038.928 12000 00100 - ipv4:58039 ::ffff:34.107.221.82:0 0 0 0 CONNECT :0
201023165038.929 12000 00100 - ipv4:58038 ::ffff:34.107.221.82:0 0 0 0 CONNECT :0

**Comment by z3APA3A** [comment]
Nice, I think your initial problem is resolved. Now, it's good time to continue with
https://3proxy.ru/howtoe.asp#ERRORS
and understand this error doesn't match your configuration again, because probably you've got it after switching to "strong". Neither Mozilla nor Chrome support password authentication for socks, use 'proxy' as http/https proxy instead. In addition, you have specified -6 option and you attempt to request IPv4 address.

SOCKSv4 supports neither authentication nor IPv6.

**Comment by s00ny5** [comment]
k so problem is the ipv6

if I just use:
`socks -p12000`
it works but with the server ipv4

if I use:
`socks -6 -n  -a -p12000 -i{IPV4}:12000 -e{IPV6}`

I get this in curl:
curl: (7) Can't complete SOCKS5 connection to IPV6 (5)

And in logs:
01023205729.099 12000 00013 - IPV4:61753 ::ffff:172.217.214.138:443 0 0 0 CONNECT ::ffff:172.217.214.138:443

Can this be because the IPV6 are added as a tunnel ?

with "proxy" all works find and nice.

Regards

**Comment by z3APA3A** [comment]
Use --socks5-hostname instead of --socks5 in curl to do not resolve the name with curl or add -6 to curl. Currently, curl resolve the name to IPv4 address and sends request with IPv4 to proxy. 3proxy is configured to support IPv6 only, so it attempts to use the tunnel address.
