### ISSUE TITLE
Make install failed in alpine linux

### ISSUE THREAD

**Issue by arbabseyfola** [z3APA3A/3proxy#544]
`make -C ./3proxy-0.9.0 -f Makefile.Linux install` 
failed in alpine linux with error:

.
.
.
/bin/sh: useradd: not found
make: *** [Makefile.Linux:137: install] Error 127
make: Leaving directory '/3proxy-0.9.0'

**Comment by phantomcraft** [comment]
**useradd** program is missing in your distro.

In Debian, it belongs to a package called **_passwd_**: https://packages.debian.org/bullseye/passwd

You can find a similar packages in the package manager of your distro.

**Comment by arbabseyfola** [comment]
> **useradd** program is missing in your distro.
> 
> In Debian, it belongs to a package called **_passwd_**: https://packages.debian.org/bullseye/passwd
> 
> You can find a similar package in the package manager of your distro.

Fixed by **[shadow](https://pkgs.alpinelinux.org/package/edge/community/x86/shadow)**.
