### ISSUE TITLE
пускает без пароля 0.9.0

### ISSUE THREAD

**Issue by prostoman** [z3APA3A/3proxy#545]
Здравствуйте.

путь трафа такой:
любой пк ->web-> сервер(openvpn server 10.8.0.1)->web ->device(openvpn client 10.8.0.45, proxy server)->web
настройка на сервере(openvpn server):
iptables -t nat -A PREROUTING -d 333.333.333.333 -p tcp -m tcp --dport 3333 -j DNAT --to-destination 10.8.0.45:3333
iptables -t nat -A POSTROUTING -d 10.8.0.45 -p tcp -m tcp --dport 3333 -j SNAT --to-source 10.8.0.1

пк имеет ip от device и все бы хорошо,  но proxy server на device не умеет socks5 по паролю.
Решил поставить на сервер(openvpn server) 3proxy(0.9.0) чтобы сделать авторизацию по паролю. Но не получается, и по прежнему пускает без пароля. **В чем может быть проблема?** Т.е. нет никакой разницы, запущен 3proxy или нет, разница только в том, что пишутся логи

логи тоже странные:
0.0.0.0 - - [31/Oct/2020:14:52:50 +0300] "Accepting connections [26422/197838592]" 00000 0 0 PROXY/0.0.0.0:0
0.0.0.0 - - [31/Oct/2020:14:52:50 +0300] "Accepting connections [26422/197977856]" 00000 0 0 SOCKS/0.0.0.0:0

конфиг:
```
setgid 113
setuid 108
timeouts 1 5 30 60 180 1800 15 60
users $/etc/3proxy/.proxyauth
daemon
log /var/log/3proxy/3proxy.log D
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
rotate 30
auth strong
proxy -n -a -p3133
socks -n -a -p3333
```
Приму любую помощь, от совета до настройки. Пиво, чай, "плюшки" гарантирую) [telegram](https://t.me/alemonx)

P.S. изменение местообитания бинарного файла после компиляции прибавил седых волос )
P.S.S. не спрашивайте почему такой маршрут, так нужно )

**Comment by z3APA3A** [comment]
Если это все логи, то это означает что трафик в 3proxy не попадает.
