### ISSUE TITLE
502 bad gateway

### ISSUE THREAD

**Issue by clintnetwork** [z3APA3A/3proxy#547]
Hey,

We use 3proxy in a production environment and sometimes we have `502 Bad Gateway` errors and when we restart 3proxy service it works again, how it's possible to fix this, the `maxconn` is already high.

Thank you

**Comment by z3APA3A** [comment]
Check the logs and make sure you have sufficient resources, ulimits and enough number of ephemeral ports available:

https://3proxy.ru/highload.asp
