### ISSUE TITLE
[QUESTION] Does URL restriction works with HTTPS ? 

### ISSUE THREAD

**Issue by APX403** [z3APA3A/3proxy#548]
Hello,

I would like to know if we can do URL restriction (regex check) with HTTPS protocol ?

I found this example : https://github.com/z3APA3A/3proxy/wiki/NoPornLitest.cfg.txt

Thanks a lot !

**Comment by z3APA3A** [comment]
URL restrictions can not work with https, because https traffic is encrypted and is not visible to proxy, unless https://3proxy.ru/plugins/SSLPlugin/ is also insatlled and certificate spoofing is enabled, but I don't recommend to use this configuration in production environment.
