### ISSUE TITLE
unable to build under fedora 33

### ISSUE THREAD

**Issue by zdm** [z3APA3A/3proxy#549]
Here is the part of log, related to the error:
```
if [ -d  ]; then \
 /usr/bin/install -m 755 scripts/init.d/3proxy.sh /root/rpmbuild/BUILDROOT/3proxy-0.9.0-1.fc33.x86_64/usr/etc/init.d/3proxy; \
fi
/usr/bin/install: cannot create regular file '/root/rpmbuild/BUILDROOT/3proxy-0.9.0-1.fc33.x86_64/usr/etc/init.d/3proxy': No such file or directory
make: *** [Makefile.Linux:120: install-init] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.aK9APq (%install)
```

Error is appears in `install-init` section in `Makefile.Linux`. For some reasons condition ` if [ -d $(INITDIR) ]; then \` is empty.

**Comment by zdm** [comment]
This is a typo.
You need to change `INITDIR` to the ``INITDDIR.

**Comment by zdm** [comment]
Also, could you, pls, create relative symlinks in `install-etc-default-config` section.
Absolute synlinks are prevents to build rpm package:
```
warning: absolute symlink: /usr/etc/3proxy/conf -> /root/rpmbuild/BUILDROOT/3proxy-0.9.0-1.fc33.x86_64/usr/local/3proxy/conf
error: Symlink points to BuildRoot: /usr/etc/3proxy/conf -> /root/rpmbuild/BUILDROOT/3proxy-0.9.0-1.fc33.x86_64/usr/local/3proxy/conf
```

**Comment by z3APA3A** [comment]
Can you try devel with this commit:
https://github.com/z3APA3A/3proxy/commit/a0413c89ef0c4c8ad54a16b863bc02e95b1477be
? If it succeeds I will backport changes to master.

**Comment by zdm** [comment]
Yes, works without errors.
