### ISSUE TITLE
Install error: centos-7 make install break

### ISSUE THREAD

**Issue by keligsotchi** [z3APA3A/3proxy#552]
Hello, 

When making a `make install` on my CentOS7, I am getting the following errors: 

### Traces & Logs

```
Default config uses Google's DNS.
It's recommended to use provider supplied DNS or install local recursor, e.g. pdns-recursor.
Configure preferred DNS in /etc/3proxy/conf/3proxy.cfg.
run '/etc/3proxy/conf/add3proxyuser.sh admin password' to configure 'admin' user
Stopping 3Proxy
kill: sending signal to 1579 failed: No such process

Starting 3Proxy
/conf/passwd: No such file or directory
/conf/passwd: No such file or directory
Parse error line 12
Command: 'include' failed with code 21, line 12
```

Could you help please? 

### OS : 

centos 7 64bit

Regards,

**Comment by z3APA3A** [comment]
run '/etc/3proxy/conf/add3proxyuser.sh admin password' to configure 'admin' (or another) user. 6d8a6c67aa44dcb9b8c156c1ac89219694fb06c7 will fix the issue, but you will not be able to use 3proxy anyway before users are configured.

**Comment by keligsotchi** [comment]
Thank you @z3APA3A
