### ISSUE TITLE
Trying to limit traffic for a proxy. 

### ISSUE THREAD

**Issue by bashar-ait** [z3APA3A/3proxy#554]
Hello, 
I'm new to 3proxy  and im trying to set limit the traffic for the proxy i created. I've read the documentation but there are parameters I didn't understand how to use them.

lets say i want to limit the download traffic to 10Megabytes per day. 
is this correct?
```
auth strong
users test:CL:test
allow test
countin 1 D 10 * * *
proxy -a -n -p44462 -i0.0.0.0 -e192.168.8.144
flush

```

**Comment by z3APA3A** [comment]
That's correct, but you also need 'counter' command if you want counter to be persistent. Without 'counter' all states are lost on configuration reload or proxy restart.

**Comment by bashar-ait** [comment]
Thank you for the fast reply, Do i need to specify a file for each proxy?
and the counter line should be like this?
`counter proxy.log D /var/log/`

final config
```
auth strong
users test:CL:test
allow test
counter proxy.log D /var/log/
countin 1 D 10 * * *
proxy -a -n -p44462 -i0.0.0.0 -e192.168.8.144
flush

```

**Comment by z3APA3A** [comment]
counter is a binary file, it stores content of all counters with non-zero numbers. number defines position of the counter in the file.

**Comment by bashar-ait** [comment]
> counter is a binary file, it stores content of all counters with non-zero numbers. number defines position of the counter in the file.

I'm sorry I didnt understand

**Comment by bashar-ait** [comment]
> counter needs to be specified once for 3proxy instance.
Ah, so i need to type this line ` counter proxy.log D /var/log/` at the top of the config file once.

and the number parameter in countin command specify the counter line for this proxy?-

**Comment by bashar-ait** [comment]
> counter (proxy.log in your command) is a binary files, it does not contain any lines, you just need to specify it's location, and it's better to use absolute paths, but once in a day (D) textual traffic reports will be generated in /var/log/

I will go and test it, Thanks alot for the help!

**Comment by bashar-ait** [comment]
Hello again, 
I'm still having issues with it. There are 2 issues i faced:
1- no counter file/report was generated after 2 days.
2- the first proxy reached limit and other proxies got limited too.

here is my config
```
counter proxy_counter D /var/log/3proxy_logs/
auth strong
users test1:CL:test1
allow test1
countin 1 D 5 * * *
deny * 192.168.8.1
proxy -a -n -p37960 -i0.0.0.0 -e192.168.8.60
flush 

####################

auth strong
users user2:CL:pass2
allow user2 
countin 2 D 50 * * *
proxy -a -n -p7000 -i0.0.0.0 -e192.168.8.60
flush 
```

**Comment by z3APA3A** [comment]
use full path to counter file and make sure account 3proxy is executed from has access to both counter file and reports directory. Also, if you use default linux configuration, main 3proxy configuration file (/usr/local/3proxy/conf/3proxy.cfg) is for chroot environment, all paths must be accessible from chroot (that is, located in /usr/local/3proxy/) see README.

**Comment by bashar-ait** [comment]
> use full path to counter file and make sure account 3proxy is executed from has access to both counter file and reports directory. Also, if you use default linux configuration, main 3proxy configuration file (/usr/local/3proxy/conf/3proxy.cfg) is for chroot environment, all paths must be accessible from chroot (that is, located in /usr/local/3proxy/) see README and paths must be relative to chroot (/usr/local/3proxy/)


Thank you for your reply, I totally understands that and 3proxy has full permission on both directories (i used full path now).
The issue right now is if one of the proxies reached its limit the other proxies get limited too.

**Comment by bashar-ait** [comment]
@z3APA3A Can you please give me an example config for limiting bandwidth for 2 different proxies?

**Comment by z3APA3A** [comment]
Use same ACL for bandlimiter and proxy access.

**Comment by bashar-ait** [comment]
I'm pretty sure that there is a bug that causing the 2 different proxies to get "You have exceeded your traffic limit".
If one proxy reached limit all of the other proxies get limit error. PLEASE check this config

When the first proxy (1999) reach the 5MB limit, The other proxy get limited too.
```

####################

countin "15/user66" D 5 * * * * *
auth strong
users tester:CL:1234
allow tester

proxy -a -n -p1999 -i0.0.0.0 -e192.168.0.164
flush

####################
countin "13/tester5" D 500 * * * * *
auth strong
users tester5:CL:1234
allow tester5
internal 127.0.0.1
admin -p8080
proxy -a -n -p9998 -i0.0.0.0 -e192.168.0.164

flush

```

**Comment by z3APA3A** [comment]
It's not a bug, it's how bandwidth limiters are supposed to be used. Bandwidth limiters, traffic counters and DNS cache are shared by all services. If you need to separate any, run few 3proxy instances with different configs.
