### ISSUE TITLE
Возможные ошибки в коде

### ISSUE THREAD

**Issue by supermet** [z3APA3A/3proxy#555]
Нашел возможные ошибки в коде (master ветка).

- В файле [auth.c:509](https://github.com/z3APA3A/3proxy/blob/master/src/auth.c) переменной param->bandlimfunc присваивается NULL, ниже в строке 512 условие всегда будет true и функция завершится.
- В файле [conf.c:1337](https://github.com/z3APA3A/3proxy/blob/master/src/conf.c) нулевой указатель char *s = 0, затем разыменование нулевого указателя *s = 0 и его изменение s++.
- В файле [proxymain.c:342](https://github.com/z3APA3A/3proxy/blob/master/src/proxymain.c) изменение позиции (fseek) в файле, открытом в режиме добавления, не имеет никакого эффекта.
- В файле [plugins/FilePlugin/FilePlugin.c:580](https://github.com/z3APA3A/3proxy/blob/master/src/plugins/FilePlugin/FilePlugin.c) Оператор '!' и операторы сравнения имеют более высокий приоритет, чем побитовые операторы. Наверно вместо (!fps->what & FP_CLIDATA) правильно - !(fps->what & FP_CLIDATA).
- Файл [plugins/PCREPlugin/pcre_plugin.c:374](https://github.com/z3APA3A/3proxy/blob/master/src/plugins/PCREPlugin/pcre_plugin.c) Массив regexp_symbols[3] обращается к индексу 6, который находится вне диапазона.

**Comment by z3APA3A** [comment]
Спасибо, пофиксил в master и devel

**Comment by supermet** [comment]
> Спасибо, пофиксил в master и devel

Вам спасибо!
