### ISSUE TITLE
Blocking specific websites not working.

### ISSUE THREAD

**Issue by bashar-ait** [z3APA3A/3proxy#556]
Hey, I'm trying to block specific websites from my proxy but its not working.

```
auth strong
users test:CL:test
allow test
deny * * eth0.me
proxy -a -n -p37960 -i0.0.0.0 -e192.168.8.60
flush

```

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by bashar-ait** [comment]
> what do you have in logs?
the logs in this directory?
/usr/local/etc/3proxy/log/

i get this 

```
1605972001.660 PROXY.4212 00000 - 127.0.0.1:48386 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.660 PROXY.4212 00000 - 127.0.0.1:48382 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.683 PROXY.4213 00000 - 127.0.0.1:54834 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.700 PROXY.4212 00000 - 127.0.0.1:48398 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.700 PROXY.4212 00000 - 127.0.0.1:48396 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.703 PROXY.4213 00000 - 127.0.0.1:54844 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.723 PROXY.4213 00000 - 127.0.0.1:54856 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.740 PROXY.4212 00000 - 127.0.0.1:48408 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
1605972001.740 PROXY.2214 00000 - 192.168.0.159:41772 5.132.162.27:80 352 163 0 GET_http://eth0.me/_HTTP/1.1
1605972001.760 PROXY.4212 00000 - 127.0.0.1:48412 5.132.162.27:80 95 398 0 GET_http://eth0.me/_HTTP/1.1
```

**Comment by z3APA3A** [comment]
It means you are running 3proxy with different config file. May be you have started few 3proxy instances with different configs or you have not restarted 3proxy after configuration change. do
sudo killall -9 3proxy
and start 3proxy with new configuration.

**Comment by bashar-ait** [comment]
> It means you are running 3proxy with different config file. May be you have started few 3proxy instances with different configs or you have not restarted 3proxy after configuration change. do
> sudo killall -9 3proxy
> and start 3proxy with new configuration.


I did restart 3proxy several times and this config is included in the main config file.

**Comment by bashar-ait** [comment]
I want to block localhost(127.0.0.1) is that possible?
i used deny * * * * * but it didnt block it.
