### ISSUE TITLE
3proxy via proxy

### ISSUE THREAD

**Issue by goodandrewsoft** [z3APA3A/3proxy#557]
For example
```
allow *
proxy -n -a -p24531 -i192.168.1.2
```

and another proxy server started like `192.168.1.2:8802`

How set `3proxy` to work via (`192.168.1.2:8802 proxy`) ?

**Comment by z3APA3A** [comment]
allow *
parent 1000 http 192.168.1.2 8802
proxy ....

also, you may need "fakeresolve". See

https://3proxy.ru/howtoe.asp#REDIR
https://3proxy.ru/howtoe.asp#NAMES
