### ISSUE TITLE
3proxy DNS leaking

### ISSUE THREAD

**Issue by Niek** [z3APA3A/3proxy#559]
Hi there,

I know about issue https://github.com/z3APA3A/3proxy/issues/478 but it was closed without any answers.

It seems that 3proxy is vulnerable to DNS leaking. Here's a quick example config:

```ini
daemon
maxconn 2048
auth iponly
allow * 127.0.0.1 * *
parent 1000 http PROXYHOST PROXYPORT USER PASS
proxy -p23000 -i127.0.0.1 -a
```
You can test it like this:
```bash
curl -sx 127.0.0.1:23000 https://random$(((RANDOM % 100000))).dns.whatleaks.com/ | jq '.'
```

In my case I have chosen a US-based proxy, but I get something like this as a result:
```json
[
  {
    "fl": "NL",
    "ip": "141.101.64.200",
    "cn": "Netherlands",
    "ci": "Amsterdam"
  },
  {
    "fl": "US",
    "ip": "68.228.15.13",
    "cn": "United States",
    "ci": "Norfolk"
  }
]
```
The top IP is the CloudFlare resolver IP close to my location, while the bottom IP is the ISP resolver of the proxy.

Is there any way to disable NS lookups in 3proxy?

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtoe.asp#NAMES

**Comment by z3APA3A** [comment]
Actually, `http` parent can be used either, you just need `fakeresolve`.

**Comment by Niek** [comment]
@z3APA3A thanks for the quick reply. The man page mentions http parent as well for fakeresolve:
https://github.com/z3APA3A/3proxy/blob/09f007e741e57f260de5dff9bb8bff0a59adb136/man/3proxy.cfg.3#L446-L450

However, in my tests I wasn't able to get this working at all. I keep getting:
``curl: (56) Received HTTP code 502 from proxy after CONNECT``. Do you have any ideas?

**Comment by z3APA3A** [comment]
Check the logs and make sure you do not use names (e.g. in "parent") with fakeresolve.

**Comment by Niek** [comment]
Ah, that was the issue! So as a reference for people finding this issue later:
* Use `fakeresolve` in the config
* Provide the IP of the proxy server instead of the hostname. Snippet to get the IP:
```bash
dig +short ${host} | shuf -n1
```
