### ISSUE TITLE
problem with logs in 0.9 develop 

### ISSUE THREAD

**Issue by zett83** [z3APA3A/3proxy#56]
в консоль высыпало:

fopen(): No such file or directory
Command: 'log' failed with code 1, line 14

и после этого прокси перестала работать.
я так понял и в 0.8 подобная история.

**Comment by z3APA3A** [comment]
zett83 пишет:
> в консоль высыпало:
> 
> fopen(): No such file or directory
> Command: 'log' failed with code 1, line 14
> 
> и после этого прокси перестала работать.
> я так понял и в 0.8 подобная история.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/z3APA3A/3proxy/issues/56>
> 
Это значит что путь для команды log указывает в несуществующий каталог

**Comment by zett83** [comment]
с моей старой работает этот путь и тем-же конфигом. теме-же правами.
просто откатываюсь на пред версию и всё работает. а эта ошибка вылазит уже в процессе работы. т.е. сервис запускается работает какое-то время а потом в консоль высыпает вот это.
возможно в процессе перечитывания конфигурации...

**Comment by z3APA3A** [comment]
Попробуй с последним патчем из git
