### ISSUE TITLE
License Agreement

### ISSUE THREAD

**Issue by maximnaro** [z3APA3A/3proxy#562]
Hello all,
I seriously got no idea what I'm doing wrong. I updated from version 0.7 to 0.9.2 today and now every time I try to start the proxy it says I need to read the license file 'copying' ... which I have read 50 times. How do I confirm the license exactly? Couldn't find anything in documentation or in closed issued :/

**Comment by z3APA3A** [comment]
What you see is a standard help message, probably you are starting 3proxy with wrong command line or wrong line in the config file. In the last case check the begging of the text, it should have a line number.
