### ISSUE TITLE
в пакете .deb в файле описания службы systemd лишний & в параметре ExecStart=

### ISSUE THREAD

**Issue by cypa** [z3APA3A/3proxy#563]
сейчас так
ExecStart=/bin/3proxy ${CONFIGFILE} &
должно быть так
ExecStart=/bin/3proxy ${CONFIGFILE}
иначе не запускается служба

**Comment by z3APA3A** [comment]
Было пофикшено в 0.9.3 https://github.com/z3APA3A/3proxy/commit/07603ceea7904479b158c6d800034d405f31540d
