### ISSUE TITLE
Ошибки (?) в коде

### ISSUE THREAD

**Issue by supermet** [z3APA3A/3proxy#564]
При компилляции вышли предупреждения:
- В файле common.c:296:9 - использование результата присвоения в качестве условия без скобок. М.б.вместо `(sp = strchr(se?se:hostname, ':'))` должно быть `((sp = strchr(se?se:hostname, ':')))`  ?
- В файле authradius.c:327:6 - `if(!radiussecret || !nradservers)` - адрес массива 'radiussecret' всегда будет оцениваться как 'true' т.к. выше присваивается radiussecret[64]="", тоесть массив не пуст

**Comment by z3APA3A** [comment]
Эти ворнинги на функциональность не влияют.
