### ISSUE TITLE
How does 3proxy use Socks5 to use UDP proxy

### ISSUE THREAD

**Issue by qsc2675** [z3APA3A/3proxy#567]
How does 3proxy use Socks5 to use UDP proxy

**Comment by z3APA3A** [comment]
3proxy supports SOCKSv5 UDP ASSOCIATE functionality, if you need socks proxy with UDP support you can use 3proxy. 

Currently UDP is not supported for `parent` command, if you are interested in chaining multiple UDP proxies, subscibe to this issue: #55
