### ISSUE TITLE
Ошибки (?) в логическом выражении

### ISSUE THREAD

**Issue by supermet** [z3APA3A/3proxy#569]
**plugins/TrafficPlugin/TrafficPlugin.c:114**
вероятно вместо **`(newitem->port>65535) | (newitem->coeff<=0) | (newitem->coeff>100)`** должно быть **`(newitem->port>65535) || (newitem->coeff<=0) || (newitem->coeff>100)`**?

**plugins/TrafficPlugin/TrafficPlugin.c:149**
вместо **`(!strcmp((char *)argv[3], "udp")) & (newitem->p_service != S_PROXY) & (newitem->p_service != S_TCPPM) & (newitem->p_service != S_POP3P)`** должно быть **`(!strcmp((char *)argv[3], "udp")) && (newitem->p_service != S_PROXY) && (newitem->p_service != S_TCPPM) && (newitem->p_service != S_POP3P)`**?

**plugins/TrafficPlugin/TrafficPlugin.c:160**
вероятно вместо **`(newitem->port>65535) | (newitem->psize<=0)`** должно быть **`(newitem->port>65535) || (newitem->psize<=0)`**?

**Comment by z3APA3A** [comment]
В данном случае результат битовых и логических операций будет одинаковым, но по смыслу да, должны быть логические.

**Comment by z3APA3A** [comment]
Поправил
