### ISSUE TITLE
Config size limit

### ISSUE THREAD

**Issue by termeee** [z3APA3A/3proxy#57]
Добрый день.

Столкнулись с лимитом на размер конфигурационного файла в 4096 байт.
Судя по ошибкам - при превышении 4096 байн он читает конфиг сначала.

Версия: 3proxy-0.9-devel (160228150442)
Система: 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u3 x86_64 GNU/Linux
ldd (Debian GLIBC 2.22-4) 2.22

**Comment by z3APA3A** [comment]
Можно подробней, судя по каким ошибкам? Ограничений на размер конфига нет, есть ограничение на длину строки/размер файла включенного через $.

**Comment by termeee** [comment]
Command: 'parent' failed with code 5, line 128

размер конфига 20477, размер инклуда 5890 байт.

**Comment by z3APA3A** [comment]
Ну у тебя лажа в команде parent в 128й строке

**Comment by z3APA3A** [comment]
там неправильный адрес парента указан

**Comment by termeee** [comment]
нет. если я в любой части файла удалю часть строк, чтобы размер стал меньше 4096 - всё запускается. сейчас попробую другую ошибку воссоздать, она из той же оперы.

**Comment by termeee** [comment]
Вот пример:
Unknown command: 'alinternal' line 129

# more 3proxy.cfg
daemon
internal x.x.x.x
nscache 65536
...
А фактически на 129-й строке:
allow valer
parent 1000 extip x:x:x:x:x:x:x 0

Убираю несколько таких пар - всё нормально.

**Comment by z3APA3A** [comment]
инклюд файлы до этого есть? Нумерация строк такая, как если бы содержимое инклюдов было вставлено.

**Comment by termeee** [comment]
да, инклуды есть. юзеры подключаются.

**Comment by z3APA3A** [comment]
Ну вот вставь содержимое этого инклюда и поищи еще раз 129ю строку

**Comment by termeee** [comment]
в инклюдах только юзеры в формате username:CL:passwd
там строк "alinternal" даже близко быть не может.

**Comment by z3APA3A** [comment]
Их больше 129,

**Comment by termeee** [comment]
нет. 82 аккаунта (строки).

**Comment by z3APA3A** [comment]
Значит вычти 82 и смотри дальше основной конфиг

**Comment by termeee** [comment]
проблема сохраняется даже если удалить включение файла с юзерами:

daemon
internal x.x.x.x
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
flush
maxconn 500
auth strong
allow user1
parent 1000 extip x:x:x:x:x:x:x:x 0
allow user2
parent 1000 extip x:x:x:x:x:x:x:x 0
... (и т.д.)
socks -6 -ix.x.x.x -p16584
proxy -6 -ix.x.x.x -p26584
flush

#wc -l ../etc/3proxy.cfg
211 ../etc/3proxy.cfg

./3proxy ../etc/3proxy.cfg
root@pxyserv:/usr/local/3proxy/bin# Command: 'parent' failed with code 5, line 128

**Comment by z3APA3A** [comment]
Скинь целиком конфиг на 3proxy@3proxy.ru (можно с обфусцированными логинами/паролями)

**Comment by termeee** [comment]
написал скрипт для рисования больших конфигов, тут выяснилось, что проблема плавающая. не получилось пока отловить.

**Comment by z3APA3A** [comment]
Скорее всего ты пересчитываешь конфиг в момент, когда он пишется. Не используй monitor на сами файлы конфигурации, мониторь, например, файл с версией конфигурации и меняй его последним + убедись, что между изменениями конфигурации проходит не менее 2х минут.
