### ISSUE TITLE
Не компилируется версия 0.9.0.*

### ISSUE THREAD

**Issue by Venique** [z3APA3A/3proxy#570]
CentOS Linux release 7.9.2009 (Core)

При попытке выполнить make -f Makefile.Linux в папке с source code из архива 3proxy-0.9.0.tar.gz и выше в src не появляется файл 3proxy. При выполнении make -f Makefile.Linux на исходном коде версии 0.8.13 бинарный файл 3proxy компилируется успешно.

В чём может быть проблема?

**Comment by z3APA3A** [comment]
бинарники складываются в папку bin

P.S. лучше использовать 0.9.3, там есть багфиксы.

**Comment by Venique** [comment]
Тогда просьба пояснить поэтапность установки версий 0.9.* и выше. На версиях 0.8.* работал следующий алгоритм, при условии, что установка производится на CentOS 7 со всеми необходимыми пакетами и никаких следов предыдущей инсталляции 3proxy нет:

```
# скачиваем, распаковываем и переходим в папку с исходным кодом
wget ...
tar -xvzf ...
cd ...

# делаем ссылки на необходимые либы, включаем режим анонимности
ln -s /usr/lib64/libcrypto.so.10 /usr/lib/libcrypto.so
ln -s /usr/lib64/libssl.so.10 /usr/lib/libssl.so
sed -i '1s/^/#define ANONYMOUS 1\n/' ./src/proxy.h

# компилируем
make -f Makefile.Linux

# создаем две директории - корневую 3proxy и bin, директории stats и logs пропускаем из-за отсутствия необходимости
mkdir /usr/local/etc/3proxy
mkdir /usr/local/etc/3proxy/bin

# копируем получившийся бинарный файл в директорию bin
cp src/3proxy /usr/local/etc/3proxy/bin
# копируем получившийся скрипт запуска в init.d
cp scripts/rc.d/proxy.sh /etc/init.d/3proxy
# копируем забекапленный конфиг
cp /username/3proxy.cfg /usr/local/etc/3proxy/3proxy.cfg
# для удобства создаем симлинк на конфиг из директории /etc/
ln -s /usr/local/etc/3proxy/3proxy.cfg /etc/3proxy.cfg
# выдаём права
chown -R root /usr/local/etc/3proxy
chmod +x /etc/init.d/3proxy

# добавляем в автозапуск и стартуем сервис
chkconfig 3proxy on
service 3proxy start
```

При этом в cfg имеется:
```
#!/usr/local/etc/3proxy/bin
daemon
pidfile /usr/local/etc/3proxy/3proxy.pid
```

В этом случае версии 0.8.* корректно работают, в т.ч. после перезапуска сервера. Для установки версий 0.9.*, получается, есть следующие отличия:
1. вместо
`cp src/3proxy /usr/local/etc/3proxy/bin`
надо
`cp src/bin /usr/local/etc/3proxy/`

2. вместо
`cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy`
надо
`cp ./scripts/init.d/proxy.sh /etc/init.d/3proxy`

Но при этом запуск происходит неуспешно. Что ещё я упустил?

**Comment by z3APA3A** [comment]
Для установки поверх старой версии, достаточно перезаписать бинарный файл. Для установки с нуля, рекомендуемый способ

make -f Makefile.Linux 
make -f Makefile.Linux  install

в README расписано про установку и про конфигурацию по умолчанию, но при желании можно установить все руками.
