### ISSUE TITLE
если в вонфиге в строке перед словом dameon стоит символ табуляции - сервер блокирует консоль

### ISSUE THREAD

**Issue by Bogdan107** [z3APA3A/3proxy#571]
Ожидаемый старт сервера со словом "daemon" в конфиге - сервер сразу завершает вывод в stdout. Выглядит как будто программа завершена, хотя процесс запущен и функционирует нормально.

Если в конфиге добавить символ табуляции перед словом "daemon" - сервер запускается, но консоль не освобождает.

Предполагаю, что сервер просто не воспринимает такую строку как валидную инструкцию конфигурации.

У меня конфиги вида:
```
# тут комментарий
    тут команда конфигурации

# тут другой комментарий
    тут другая команда конфигурации 1
    тут другая команда конфигурации 2
```
Т.е. визуально разделены блоки опций.

Желаемое изменение: очищать строку из файла конфигурации до первого всреченного символа, допустимого для имени опции конфигурации (полагаю, первым символом имени опции может быть только буква латинского алфавита - [a-z],[A-Z]).

**Comment by z3APA3A** [comment]
Пробельный символ в начале строки в конфигурации эквивалентен комментарию (строка игнорируется), см. документацию по 3proxy.cfg.
