### ISSUE TITLE
Transparent Proxy with UDP -> udppm

### ISSUE THREAD

**Issue by DoM1niC** [z3APA3A/3proxy#573]
Anyidea how I get a Transparent styled udppm like this -> `tcppm -i10.1.0.1 4009 127.0.0.1 11111`?

if not then it's possible to do a port range ? like 
`udppm -i10.1.0.1 5000-5060 10.10.0.6 5000-5060`

**Comment by z3APA3A** [comment]
Unfortunetely, the only way currently is to add 60 udppms to config.
