### ISSUE TITLE
should 'auth none' prompt for a password?

### ISSUE THREAD

**Issue by lejeczek** [z3APA3A/3proxy#574]
Hi guys.
I've a very basic setup with socks5 and "auth none" and I was expecting my ssh would not get asked for a password to SOCKS5.
Was I wrong and password prompt will always be there no matter the "auth"?
In case my ssh client conf matters, in ~/.ssh/config

CheckHostIP no
Compression yes
Protocol 2
ProxyCommand connect-proxy -5 -S 10.8.9.1:1080 %h %p

many thanks, L.

**Comment by ezbik** [comment]
Hi,
3proxy version? 
Exact config?

**Comment by lejeczek** [comment]
`nscache 65536
timeouts 1 5 30 60 180 1800 15 60
users 3APA3A:CL:3apa3a "test:CR:$1$qwer$CHFTUFGqkjue9HyhcMHEe1"
daemon
log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /bin/gzip %F
rotate 30
auth iponly
external 0.0.0.0
internal 10.8.9.1
flush

socks -u
maxconn 20
auth none
allow * * * 22
flush`

socks of 3proxy-0.7 (140408012613)

-> $ ssh 10.0.0.14
Enter SOCKS5 password for mgr@10.8.9.1: 
Password:

**Comment by ezbik** [comment]
> Enter SOCKS5 password for mgr@10.8.9.1:

now guess what asks for the password? connect-proxy!

Solution:

 ProxyCommand connect-proxy -a none -5 -S 10.8.9.1:1080 %h %p

**Comment by z3APA3A** [comment]
Actually, this configuration uses "auth iponly" with empty ACL, because "auth none"  and "flush" are given after 'socks'. Put `auth` and `allow` prior to socks. `flush` is only required if you need to run few different services with different ACLs.
