### ISSUE TITLE
502 bad gateway и ничего в логах

### ISSUE THREAD

**Issue by dca00** [z3APA3A/3proxy#576]
3proxy tiny proxy server 3proxy-0.9.3 (201203211618)

заведён как все типы прокси в ФФ на моей машине .3. запущен как сервис под вин7 на .2
появляется лог файл на текущий день, но он всегда 0 байт
на каждый HTTP запрос отвечает 502 bad gateway, на HTTPS просто нет соединения.

nserver 192.168.1.1
nscache 65535
maxconn 100                                     
flush
auth strong
users user:CL:123
allow user
bandlimin 10000000 user 
proxy -n -a -p8888 -i192.168.1.2 -e192.168.1.1

log "C:\Program Files\3proxy\log\log" D
logformat "%d-%m-%Y %H:%M:%S %U %C:%c %R:%r %O %I %T"

ЧЯНТД?

**Comment by z3APA3A** [comment]
log и logformat надо указывать до proxy
