### ISSUE TITLE
502 Bad Gateway - продолжение

### ISSUE THREAD

**Issue by dca00** [z3APA3A/3proxy#578]
Переместил лог выше прокси, пошли логи (файл закрывается, кстати, только после останова сервиса), но ничего не изменилось с 502. По-прежнему HTTP даёт 502, а HTTPS просто не соединяется.

nserver 192.168.1.1
nscache 65535
maxconn 100
flush
auth strong
users user:CL:123
allow user
bandlimin 10000000 user
log "C:\Program Files\3proxy\log\log" D
logformat "%d-%m-%Y %H:%M:%S %U %C:%c %R:%r %O %I %T"
proxy -n -a -p8888 -i192.168.1.2 -e192.168.1.1

d-01-2021 14:00:40 - 192.168.1.2:8888 192.168.1.1:0 0 0 Accepting connections [7984/4664]
d-01-2021 14:02:12 user 192.168.1.3:39018 172.217.13.131:443 0 0 CONNECT google.ca:443 HTTP/1.1
d-01-2021 14:04:21 user 192.168.1.3:39108 140.82.112.3:443 0 0 CONNECT github.com:443 HTTP/1.1
d-01-2021 14:04:27 user 192.168.1.3:39122 140.82.112.3:443 0 0 CONNECT github.com:443 HTTP/1.1
d-01-2021 14:04:28 user 192.168.1.3:39126 140.82.112.3:443 0 0 CONNECT github.com:443 HTTP/1.1
d-01-2021 14:04:29 user 192.168.1.3:39128 140.82.112.3:443 0 0 CONNECT github.com:443 HTTP/1.1
d-01-2021 14:04:30 user 192.168.1.3:39132 172.217.13.131:443 0 0 CONNECT www.google.ca:443 HTTP/1.1
d-01-2021 14:04:31 user 192.168.1.3:39134 172.217.13.131:443 0 0 CONNECT www.google.ca:443 HTTP/1.1
d-01-2021 14:07:04 - 0.0.0.0:0 192.168.1.1:0 0 0 Exiting thread

Не спешите закрывать инциденты, пожалуйста. В этом нет никакой острой необходимости, а дополнительные вопросы и соображения появляются, как видим.

**Comment by dca00** [comment]
Сменил формат лога на строку из sample файла:

08-01-2021 14:21:29 -0500 PROXY.8888 00012 user 192.168.1.3:39886 52.149.246.39:443 0 0 0 CONNECT ac.duckduckgo.com:443 HTTP/1.1
08-01-2021 14:21:32 -0500 PROXY.8888 00012 user 192.168.1.3:39888 194.85.61.76:443 0 0 0 CONNECT www.nsu.su:443 HTTP/1.1
08-01-2021 14:21:35 -0500 PROXY.8888 00012 user 192.168.1.3:39890 194.85.61.76:80 0 0 0 GET http://www.nsu.su/ HTTP/1.1
08-01-2021 14:21:35 -0500 PROXY.8888 00012 user 192.168.1.3:39892 194.85.61.76:80 0 0 0 GET http://www.nsu.su/favicon.ico HTTP/1.1

На вид всё чики-пуки, но я по-прежнему получают только 502 Bad Gateway

**Comment by ezbik** [comment]
Ошибка 12 - failed to bind.  Что-то вы намутили с  -i -e флагами. Убирайте и тестируйте без них.

**Comment by dca00** [comment]
Убейте, но я не вижу тут ничего намудрённого.
Внутренний адрес интерфейса на хосте, где крутится прокси.
Внешний - адрес раутера.
Если убрать -e, то как прокси на обычной машине в локалке узнает, где интернет? Ему достаточно дефолт гейтвей интерфейса?

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#INTEXT
