### ISSUE TITLE
3proxy connection is not stable

### ISSUE THREAD

**Issue by izmark** [z3APA3A/3proxy#579]
3proxy connection is not stable. When it can connect, sometimes it can't.  How can I optimize it?
which version I am using: 0.9.3

![op](https://user-images.githubusercontent.com/44727524/104475876-2f5cf580-55f2-11eb-80e3-730a41db0f94.png)

**Comment by z3APA3A** [comment]
Check the logs and read https://3proxy.ru/highload.asp, it may give you some hints.
