### ISSUE TITLE
Помогите организовать сеть с прокси

### ISSUE THREAD

**Issue by i1326** [z3APA3A/3proxy#58]
Есть сетка из 1 ХР и 1 WIN7
Создал прокси на windows 7 x86
В конфиге написал:
###############################################################
# ОБЩИЕ ПАРАМЕТРЫ
###############################################################
service
internal 192.168.126.1
external 10.13.XXX.XXX
nserver 10.XX.XX.X
nserver 10.XX.XX.X
nserver 85.95.164.6
nserver 85.95.165.6
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
log c:\3proxy\logs\3proxy.log D
rotate 30
archiver rar “”"c:\Program Files\WinRAR\rar.exe””" a -df -inul %A %F
proxy -p8080
###############################################################
# ЗАДАЕМ ПОЛЬЗОВАТЕЛЕЙ СЧЕТЧИКИ
allow * 192.168.126.1,192.168.126.11 * * 
counter "c:\3proxy\3proxy.3cf" D "C:\3proxy\traf\traf"
###############################################################
# Запрещаю некоторые сайты
###############################################################

auth iponly 
deny * * *sex*,*porn*,*adult*,*xxx*,*gamepark*,*vagina*,*mpp3*,*seks*,*virgin*,*pipisk*,*pastushka*,*1xuk.ru*,*teens*,*zaycev*,*lubovmorkov*,*mp3*,*bannerbank*,*yadro*,*dosug.nu*,*lesbo*,*lesbian*,*eroti*,*viporg.ru*,*intim*,*erohost*,*eross*,*teenfant*,*nudist*,*pimpserver*,*banner*,*ads.sup.com*,*rb.mail.ru*,*counter.rambler.ru*,*carol.ru*,*video.mail.ru*,*pelotka*,*akadostream*,*media.kino-govno.com*,*odnoklassniki.ru*,*vkontakte.ru*,*zhuki.mail.ru*,*fishki.net*,*dofiga.net*
end

###############################################################
# КОНЕЦ КОНФИГА
Запустил как службу 3proxy --install
Соответственно на клиентах в свойствах браузера пишу Прокси 192.168.126.1 порт 8080
В TCP/IP прописываю:
Ip: 192.168.126.11
Маска: 255.255.255.0
Шлюз: 192.168.126.1
DNS: 192.168.126.1
При попытке выйти на сайт (например ya.ru) пишет ошибку 502
Подскажите в чем может быть проблема?

**Comment by halit63** [comment]
Наверное, в том, что сначала надо задать тип авторизации, а потом уже список доступа, а не наоборот.

**Comment by z3APA3A** [comment]
А что в логах?
шлюз прописывать не надо, DNS тоже (раз dnspr не поднимали), в deny для матчинга хостов по части имени надо использовать звездочки и deny надо ставить до allow, т.к. сработает первое найденное правило.
