### ISSUE TITLE
Привет, подскажите как настроить, чтобы не было двухстороннего пинга

### ISSUE THREAD

**Issue by Kass1a** [z3APA3A/3proxy#580]
Привет, подскажите как настроить, чтобы не было двухстороннего пинга

**Comment by z3APA3A** [comment]
Не уверен, что именно ты хочешь спросить - прокси сервер работает на прикладном уровне, он никак не влияет на сетевую связанность вообще и прохождение пинга в частности.

**Comment by ezbik** [comment]
@z3APA3A это техника определения того, сидит ли юзер за прокси. Js скрипт в браузере замеряет "пинг" (это может быть краткий http запрос) и отсылает на сервер; сервер сам замеряет пинг до клиента, т.е. до прокси. И сравнивает эти пинги. Если первый пинг больше значительно, то считается, что юзер сидит за прокси.

**Comment by ezbik** [comment]
П.с. решение, на публичном адресе прокси, закрыть все файрволом. Как вариант. Может, поможет.
