### ISSUE TITLE
Происходит утечка DNS от главного сетевого подключения.

### ISSUE THREAD

**Issue by salexua** [z3APA3A/3proxy#581]
Помогите пожалуйста, третий день борюсь.

Имею такой конфиг для использования мобильного прокси:

monitor C:\3proxy\bin\3proxy.txt
nscache 65535
timeouts 1 5 30 60 180 1800 15 60
proxy -n -a -p1081 -i192.168.1.32 -e192.168.42.1
socks -n -a -p1080 -i192.168.1.32 -e192.168.42.1

При использовании прокси 192.168.1.32:1081 (И socks тоже) происходит утечка DNS сервера от Главного сетевого подключения 192.168.1.32 (DNS 192.168.1.1). 
Нужно чтобы при использовании этого прокси, срабатывал ДНС мобильного подключения по ЮСБ которое расположено под ip 192.168.42.1 (DNS 192.168.42.1) 

Помогите пожалуйста это реализовать.

**Comment by z3APA3A** [comment]
См. команду nserver.
Пропиши в качестве nserver тот сервер, который прокси должен использовать.
