### ISSUE TITLE
Feature Request: allow retries for parent proxy

### ISSUE THREAD

**Issue by Niek** [z3APA3A/3proxy#583]
Discussion: https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762443237 https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762757633 https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762758792

It would be great if it'd be possible to retry a request X times in case the parent proxies replies with an error. This makes it possible to transparently retry requests in case the proxy fails. This is especially useful in case of unstable proxies, like residential IPs.

**Comment by z3APA3A** [comment]
Try with this patch
cbe0c2f511f402c65f44e0241956ebf787143707
(current master). It adds `parentretries` command and defaults it to 2.

**Comment by z3APA3A** [comment]
@Niek do you need any help to check if fixes your scenario?

**Comment by z3APA3A** [comment]
Compilation issues on Linux fixed with c30065256f96c36b2164e715e50c2e4cd7c1515b

**Comment by Niek** [comment]
Thanks for the quick responses @z3APA3A! The latest master builds fine (on macOS) and seems to work. I am just thinking of how to best simulate dropping connections to see the difference with 0.9.3. I'll do some more testing.

**Comment by z3APA3A** [comment]
I think the best possible way is to test in real environment. "redirections" field in log file contains a number of redirection attempts.If you see more than 1 redirection, it means it was re-attempted.

**Comment by Niek** [comment]
I don't see retries happening yet, see for example this:
```bash
$ for i in $(seq 1 100); do curl -sx localhost:8888 --fail --show-error ipinfo.io 1>/dev/null; done
curl: (22) The requested URL returned error: 502 Proxy Error
curl: (22) The requested URL returned error: 502 Proxy Error
curl: (22) The requested URL returned error: 502 Proxy Error
curl: (22) The requested URL returned error: 502 Proxy Error
```
I see the proxy returned an error 4 times out of 100, but no retries were done. This is with `parentretries` set to default and with a `http` parent proxy. In the log output the `%h` value is always 1.

**Comment by z3APA3A** [comment]
what do you have in the error code?

**Comment by Niek** [comment]
The error code is `00000` every time, the failed requests don't seem to show up in the log. This is the full config:
```ini
pidfile /tmp/3proxy.pid
auth iponly
nserver 1.1.1.1
log
logformat "L%R:%r %E %h %O %I %T"
parentretries 2
allow * 127.0.0.1 * *
parent 1000 http proxy.host.name 22225 username password
proxy -p8888 -i127.0.0.1 -a
```

**Comment by jokedroid** [comment]
> Discussion: [#561 (comment)](https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762443237) [#561 (comment)](https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762757633) [#561 (comment)](https://github.com/z3APA3A/3proxy/issues/561#issuecomment-762758792)
> 
> It would be great if it'd be possible to retry a request X times in case the parent proxies replies with an error. This makes it possible to transparently retry requests in case the proxy fails. This is especially useful in case of unstable proxies, like residential IPs.

I suggest improving the parentretries parameter by adding a variable to change parent. Let's say one of the parent proxies did not respond after 3 attempts (its link fell off). In this case, I think it is logical to try to change the parent proxy for this connection (if it is not one) and try again. It is also quite logical to introduce the parentblock parameter, which will temporarily block a non-working parent, excluding it from the selection for a user-defined time after reaching a critical number of parentretries.

Предлагаю улучшить параметр parentretries, добавив переменную для смены parent. Допустим, один из родительских прокси не ответил после 3-х попыток (у него отвалился линк). Считаю логичным в таком случае попробовать сменить родительский прокси для данного соединения (если он не один) и попробовать снова. Также вполне логично ввести параметр parentblock, который позволит временно блокировать нерабочий parent, исключая его из выбора на определенное пользователем время после достижения критического количества parentretries.

**Comment by z3APA3A** [comment]
@Niek, in the case of HTTP proxy and http (not https) request, there is no separate request to proxy without sending a client request, and, as it was pointed before, I don't want to re-send a client's request, because it may lead to unpredictable results. Use connect+ instead of http parent type.

@jokedroid the current implementation restarts parent selection in the case multiple parents are specified, so another parent may be randomely choosen. It affects all services and all ACLs/parents.
The functionality you want is parent-specific, so it's a different feature and requires different implementation. Make a separate feature request for parent fallback.

As for non-working parent exclusions, I don't want to implement this feature. There is a separate software to check and manage proxy servers list. If proxy servers list is unreliable and requires re-checking and management, it's legality is questionable. I don't want to implement any functionality which can be linked to illegal activities.

**Comment by jokedroid** [comment]
If the current implementation of "parentretries" restarts a random selection of parent proxies, which adds fault tolerance and is invisible to the user, then I have nothing more to add for this request. I also agree that the controversial "parentblock" should not be included in the product yet.
 P.S. If after this dialogue there are useful ideas for creating other requests, then help to formulate them for new features.

Если текущая реализация "parentretries" перезапускает случайный выбор родительских прокси, что добавляет отказоустойчивости и происходит незаметно для пользователя, то больше мне нечего добавить для этого запроса.  Также согласен, что спорный "parentblock" включать в продукт пока не нужно. 
 P.S. Если после этого диалога остались полезные идеи для создания других запросов, то помогите их сформулировать для новых фич.

**Comment by lafftar** [comment]
> Try with this patch
> [cbe0c2f](https://github.com/3proxy/3proxy/commit/cbe0c2f511f402c65f44e0241956ebf787143707)
> (current master). It adds `parentretries` command and defaults it to 2.

Hey man, is it possible to make a windows .exe of this commit? I'm getting this error when trying to use the latest version:

![](https://i.gyazo.com/71f7f325de0cdf461661a0a83f857dbc.png)

I'm in a similar situation to @Niek. I'm using a residential proxy service that's a bit unstable unfortunately, I could really use this to help with stability of my ports. If it's too much trouble, i'd love if you could link me to a guide on how to do it myself. I'm unsure what to even search.

**Comment by z3APA3A** [comment]
@laftar you have quite strange configuration with the chain of 3 local proxies. Probably you need different weights, e.g. 333/333/334 if you want random selection see https://3proxy.org/howtoe.asp#ROUNDROBIN
You can get compiled 64-bit version here: https://cloud.mail.ru/public/M67Z%2FMYMAnsqL8
