### ISSUE TITLE
Compilation on windows fails

### ISSUE THREAD

**Issue by Kiblyn11** [z3APA3A/3proxy#585]
Hello,

I'm trying to compile on Windows but instructions are very concise.
I've tried with VC++ 2019 but I've got errors.

OS : Windows 10
Compiler: VC++ 2019
Installed Windows 10 SDK

![image](https://user-images.githubusercontent.com/4669951/105387052-73b14c80-5c15-11eb-9db1-d354c9c723d1.png)

![image](https://user-images.githubusercontent.com/4669951/105387079-7ca21e00-5c15-11eb-87c1-d6ba4fdb5644.png)

Could you please provide detailed instructions on how to compile project ?

Thanks

**Comment by z3APA3A** [comment]
Usr vcvars .bat file from VC distribution,  usually it's something like ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary
\Build\vcvars32.bat``` to set correct environment.
