### ISSUE TITLE
Прокси не работает на OS ubuntu

### ISSUE THREAD

**Issue by Orioleon** [z3APA3A/3proxy#587]
Добрый день! Не первый день я и мои товарищи в команде пытаемся на 1 физ.машине настроить 3proxy. У нас 1 мопед и eth. Если eth выключить и оставить мопед и curl -x через прокси - всё работает, если подключено 2 интерфейса сетевых - то работает только основной. При этом через прокси он пишет CONNECT 00013. Нам нужно n-е кол-во интерфейсов, желательно без вм на ubuntu. 

Config:                                                                         
/usr/local/3proxy/conf/3proxy.cfg                                                                                   
nscache 65536
nserver 127.0.0.53
nserver 8.8.8.8
nserver 8.8.4.4

config /conf/3proxy.cfg
monitor /conf/3proxy.cfg

log /logs/3proxy-%y%m%d.log D
rotate 1
counter /count/3proxy.3cf

users $/conf/passwd

include /conf/counters
include /conf/bandlimiters

#external 192.168.10.100
#internal 127.0.0.1

auth none
#deny * * 127.0.0.1
allow * * * 80-88,8000-8100 HTTP
allow * * * 443,8443 HTTPS
proxy -n -p8009 -i192.168.10.100 -e192.168.10.100
socks -n -p8008 -i192.168.10.100 -e192.168.10.100
flush
allow admin

admin -p8080

210125144044.079 8009 00013 - 192.168.10.100:40824 173.194.73.103:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
210125144044.173 8009 00013 - 192.168.10.100:40826 173.194.73.103:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
210125144046.213 8009 00013 - 192.168.10.100:40828 173.194.73.103:443 0 0 0 CONNECT www.google.com:443 HTTP/1.1
210125144046.977 8009 00013 - 192.168.10.100:40830 104.244.42.193:443 0 0 0 CONNECT twitter.com:443 HTTP/1.1

Заранее спасибо за ответ!

**Comment by z3APA3A** [comment]
В Linux по умолчанию не используется source routing и выбор ip не выбирает интерфейс. Необходимо дополнительно выбирать внешний интерфейс в proxy или настраивать source routing, чтобы трафик с данного IP шел через нужный интерфейс
