### ISSUE TITLE
outgoing ipv6 problem

### ISSUE THREAD

**Issue by minhdv92** [z3APA3A/3proxy#588]
hi
Thank for your project.

I installed socks servers on my servers with incomming ipv4 and outgoing is ipv6 (socks -p2020 -i0.0.0.0 -exxx:xxxx:2 -6)
The problem on clients.
I tried request to https://www.google.com/, if the client support ipv6 it working fine, but if client only support ipv4 I got the error: curl: (7) Can't complete SOCKS5 connection to xxxxxxcc7d:2b7f:0000:0086:68cf:10. (5)

**Comment by z3APA3A** [comment]
what to you have in logs?

**Comment by minhdv92** [comment]
this is log

```
[root@s173728 ~]# socks -p2020 -i0.0.0.0 -exxxxx:0:0:0:2 -6 -l
210126114402.958 2020 00000 - 0.0.0.0:2020 xxxx:a:30e::2:0 0 0 0 Accepting connections [9285/2373773120]
210126114412.307 2020 00013 - xxxx7.50:43132 ::ffff:xxxx8:443 0 0 0 CONNECT ::ffff:xxxx.68:443

```

**Comment by z3APA3A** [comment]
00013 means proxy fails to connect. If you have multiple interfaces, probably you either need to select interface in addition to IP or set up a srouce routing. You can try to check connection with e.g. telnet

telnet -s xxxxx:0:0:0:2 ::ffff:xxxx.68 443

**Comment by minhdv92** [comment]
I can connect from client support ipv6 or same server. But with client not support ipv6 it will be failed.
I has multiple interfaces, but I use only one interface. This interface has many ipv6, I want setup proxy with mutil port on incomming connection and each outgoing is one ipv6.

Thanks

**Comment by z3APA3A** [comment]
Probably, it's because you use curl --socks5 option instead of --socks5h.

**Comment by minhdv92** [comment]
Oh yes. me can access now.
But I has other problem, when i run command a long time
`socks -p2020 -i0.0.0.0 -exxx:0:0:2 -6 -l`
then it the ipv6 cannot access, I cannot ping to this ipv6. I need restart network and run command again

**Comment by z3APA3A** [comment]
Your configuration may be insecure, and may be abused by anyone on the net, if the proxy is accessible, exhausting available resources. Secure proxy with ACL or authentication. If you do a large number of connections by yourself, you probably need to read this article:
https://3proxy.ru/highload.asp

**Comment by minhdv92** [comment]
I'm testing only with 1 ipv6 address.
I see the log, only me using this proxy. It will error after 30 min.
My command: 
`socks -p2020 -i0.0.0.0 -exxx:0:0:0:2 -6 -l`
after 30 min, I cannot ping to my ip xxx:0:0:0:2 and need restart again

**Comment by z3APA3A** [comment]
3proxy acts on application level. It can not affect network connectivity.
