### ISSUE TITLE
How to receive all configuration parameter information from the console?

### ISSUE THREAD

**Issue by sunlewuyou** [z3APA3A/3proxy#592]
Can I receive parameter information from the console instead of using the configuration file?

**Comment by z3APA3A** [comment]
In Linux/Unix version if you run 3proxy without configuration file specification, configuration is expected from stdin, "end" command is required at the end of configuration.

**Comment by sunlewuyou** [comment]
I am running on the windows platform.

**Comment by z3APA3A** [comment]
For Windows config is required parameter. You can GET/POST configuration via 'admin' service (configuration must contain "writable" parameter).

**Comment by sunlewuyou** [comment]
```
for(cm = commandhandlers; cm; cm = cm->next){
		if(!strcmp((char *)argv[0], (char *)cm->command) && argc >= cm->minargs && (!cm->maxargs || argc <= cm->maxargs)){
			res = (*cm->handler)(argc, argv);
			if(res > 0){
				fprintf(stderr, "Command: '%s' failed with code %d, line %d\n", argv[0], res, linenum);
				return(linenum);
			}
			if(!res) break;
		}
	}
```
Hello, is the above code the key code to read the configuration file information? It took a long time to read and I can’t quite understand, please give me some advice, thank you!

**Comment by z3APA3A** [comment]
I'm not sure what exactly is a "key" for you. This code compares first word from the line in configuration file with a list of a known commands and executes command handler.

**Comment by sunlewuyou** [comment]
Thank you, can you explain the whole detailed process of 3proxy loading configuration file?

**Comment by sunlewuyou** [comment]
If you want to encrypt the configuration file, or read the configuration file from the network, how to change the code? Can you give me some suggestions?

**Comment by z3APA3A** [comment]
Actually, you can read the config from the console, just run

3proxy.exe CON

finish config with "end"

**Comment by sunlewuyou** [comment]
If you want to read the configuration file from the network, how to change the code? Can you give me some suggestions?

**Comment by z3APA3A** [comment]
There is no simple reply to your question, because it depends on how you want to handle it. As an example, you can change/replace readconfig() function from conf.c and all calls to it.

**Comment by sunlewuyou** [comment]
Yes, the biggest problem is that I cannot understand the readconfig() function. It seems very complicated. Can you explain the readconfig() function?

**Comment by sunlewuyou** [comment]
The most important reason is: I don’t know how to put the project source code into Visual Studio for development and debugging?

**Comment by sunlewuyou** [comment]
![image](https://user-images.githubusercontent.com/19728435/106893406-7be6ad00-6728-11eb-8321-91d4d7366cb8.png)

**Comment by z3APA3A** [comment]
Sorry, but I can't help you on this. 3proxy is not the the entry level project, you need some experience

**Comment by sunlewuyou** [comment]
Thank you very much for developing such a lightweight and powerful software, thank you for your reply!
