### ISSUE TITLE
Question about speed limit and threads

### ISSUE THREAD

**Issue by Shawn-Tong** [z3APA3A/3proxy#593]
For example:

```
# limit its speed to 1Kb/s
bandlimin 1024 * 1.2.3.4
# allow 100 threads
connlim 100 0 * 1.2.3.4
```

If user 1.2.3.4 uses 100 threads, is its total speed 1Kb/s or 100Kb/s?

**Comment by z3APA3A** [comment]
It's a total limit for all connections matching bandlimin ACL.

bandlims are in bits per second (bps or b/s), 1024 is very low value (~0.125 KB/s)
