### ISSUE TITLE
Load ACL's from database

### ISSUE THREAD

**Issue by nyanmark** [z3APA3A/3proxy#595]
Is there a way or would it be possible to load ACL's externally, such as loading ACL's from a MySQL database so when you use the
 "auth iponly" parameter in 3proxy the ACL source IP's are loaded from a database of allowed IP addresses. So for example an ACL could be "allow * mysql://table * * *"

**Comment by z3APA3A** [comment]
with RADIUS you can authorize requests with RADIUS server. FreeRADIUS (and probably others) support MySQL.

**Comment by nyanmark** [comment]
Alright, I do not know anything about radius so I did not realize I could do that. Thanks.
