### ISSUE TITLE
problems about service remove

### ISSUE THREAD

**Issue by sunlewuyou** [z3APA3A/3proxy#596]
Hello, I found a small problem: when I use "- remove" to unload the service, although the service is successfully unloaded, the service process is not stopped first and then unloaded. The process does not stop, and the service item only disappears after manually terminating the process.

**Comment by sunlewuyou** [comment]
I tested it on Windows 10 Enterprise LTSC.

**Comment by z3APA3A** [comment]
Yes, you have to stop service before removing (e.g. `net stop 3proxy`)
