### ISSUE TITLE
Password-protected FTP over HTTP

### ISSUE THREAD

**Issue by timp87** [z3APA3A/3proxy#6]
Hi!
Seems like 3proxy doesn't ask user for login and pass for password-protected FTP if one uses FTP over HTTP. It just tries to login as anonymous, and shows
401 FTP Server requires authentication
This FTP server rejects anonymous access
530 User cannot log in. 

and that's it. No questions for user.

**Comment by z3APA3A** [comment]
Can you give an address of your FTP server or complete session of FTP handshake with 401/530 error? I've looked into the code and I see proxy should request FTP authentication in this case.

**Comment by timp87** [comment]
@z3APA3A, how can I write private message?

**Comment by z3APA3A** [comment]
Mail to 3proxy@3proxy.ru

**Comment by z3APA3A** [comment]
This commit should fix the problem:
https://github.com/z3APA3A/3proxy/commit/3198f1614f35164276aad0fc67c1a837e496b6b6

**Comment by timp87** [comment]
@z3APA3A so, looks like it never worked before

**Comment by timp87** [comment]
@z3APA3A this fix works for 3proxy-0.7.1.2 too! Thank you!

**Comment by timp87** [comment]
@z3APA3A, well, I was wrong. It helps only partially. It actually asks for a password now, but no matter if it's right 3proxy asks for a pass again and again.
Meanwhile no problem if I pass login and pass as part of url like "user:pass@ftp://..".

**Comment by z3APA3A** [comment]
This fix https://github.com/z3APA3A/3proxy/commit/4ca8988831cd42523d80d3760bf9800b7cd10e5e is also required.

**Comment by timp87** [comment]
Yes, everything is good now.
