### ISSUE TITLE
Problem with connlim settings and implementing

### ISSUE THREAD

**Issue by benio-star** [z3APA3A/3proxy#600]
Hello.

I use 3proxy-0.9.3 and I am trying to set up some limitation on my proxies based on connlim. Roughly speaking, it looks like this:

auth iponly
allow * 100.100.100.100,200.200.200.200
parent 1000 http 5.5.5.5 2001
proxy -n -a -p1001
connlim 1 60 * * *bing* 443
flush

auth iponly
allow * 100.100.100.100,200.200.200.200
parent 1000 http 6.6.6.6 2001
proxy -n -a -p1002
connlim 1 60 * * *bing* 443
flush

So on my server I set up 2 proxies on ports: 1001 and 1002which redirect to parent proxies 5.5.5.5:2001 and 6.6.6.6:2001, and on each port I would like to use connlim to limit number of connections sending to Bing (https) in 60 seconds:
connlim 1 60 * * *bing* 443
Connections into both ports come from the same IPs: 100.100.100.100,200.200.200.200

Unfortunately, I encountered two problems:

1. In this configuration it looks like the first record with connlim works for both ports, so if the first port (1001) sends request to the www.bing.com:443 the subsequent requests will be blocked for the next 60 seconds regardless of which port I use. Of course, my intention was to put a connection limit on each port individually. Would I then have to use another 3proxy service to effectively limit in this version for the second port?
2. Also if I change the connlim value in the first port i.e. on: "connlim 3 60 * * *bing* 443" it will accept the lower value from the second record of connlim so only 1 request for 60 sec. will be accepted.

So are the connlim entries misconfigured or is there something else going on?

**Comment by z3APA3A** [comment]
Flush only flushes ACLs (allow+parent/deny). DNS/cache settings, connlims/bandlims/traffic counters are common for all services, you can run few 3proxy instances with different configs.

**Comment by benio-star** [comment]
Thank you for reply.

Wouldn't running separate instances of 3proxy for e.g. 500 ports be excessive? Is there any reasonable limit of running separate instances of 3proxy?

**Comment by z3APA3A** [comment]
I don't think there is any practical difference in running 500 processes vs running 500 threads.

**Comment by benio-star** [comment]
I understand.

Thank you for your help and the great job you did with 3proxy. All the best!
