### ISSUE TITLE
Run multiple instances

### ISSUE THREAD

**Issue by spotterus** [z3APA3A/3proxy#601]
Hello.

How can I effectively create new instances of 3proxy, so I can run them with separate config?

I have tried to add entries in /etc/3proxy/3proxy.cfg with path to the new config files (located in /usr/local/3proxy/conf/) like:

#!/bin/3proxy
#daemon
pidfile /var/run/3proxy/3proxy.pid
chroot /usr/local/3proxy proxy proxy
include /conf/3proxy.cfg
include /conf/3proxy1.cfg
include /conf/3proxy2.cfg
include /conf/3proxy3.cfg

But it seems that all these config files work under the same global settings like bandlim. Even I set different bandlim in every single config file all use settings from the smallest bandlim limit. Should I create separate files for these entries in every single cfg file:

counter /count/3proxy.3cf
include /conf/counters
include /conf/bandlimiters

Which could looks like:

counter /count/3proxy1.3cf
include /conf/counters1
include /conf/bandlimiters1

?

**Comment by ezbik** [comment]
Learn about systemd templates .

**Comment by z3APA3A** [comment]
You can use "system" to run new instance of 3proxy from 3proxy, but it's really much better to start multiple insances with systemd.
