### ISSUE TITLE
Ограничение подключений на порт

### ISSUE THREAD

**Issue by pursiyanov** [z3APA3A/3proxy#602]
Добрый день. У меня есть несколько вопросов, подскажите пожалуйста, можно ли реализовать как-то:
1) Нужно поднять 3proxy, на разных портах (http proxy)
Допустим от 50000-50015, получается 15 портов
2) Нужно создать 15 пар логин:пас и привязать каждый к отдельному порту
3) Можно ли как-то установить ограничение, на подключение с любого ip до 1 устройства на порт ( Тоесть, если один клиент подключен со своим логином и паролем к своему порту, чтобы второй ip адрес уже не мог подключиться с этим же логином и паролем к этому порту)

Заранее благодарю

**Comment by z3APA3A** [comment]
```
allow user1
proxy -p1001

flush

allow user2
proxy -p1002

flush
...
allow user15
proxy -p1015
```

**Comment by z3APA3A** [comment]
по 3му пункту смотри команду authcache
