### ISSUE TITLE
Разные DNS на разные прокси в однов конфиге ? 

### ISSUE THREAD

**Issue by XRegem** [z3APA3A/3proxy#604]
Здравствуйте, есть не сложный конфиг на 3 модема

timeouts 1 5 30 60 180 1800 15 60
auth strong
users 1***:CL:2***
allow 1***
maxconn 10000
proxy -n -a -p4451 -i10.9.0.20 -e192.168.7.100
socks -n -a -p7031 -i10.9.0.20 -e192.168.7.100
proxy -n -a -p4452 -i10.9.0.20 -e192.168.8.100
socks -n -a -p7033 -i10.9.0.20 -e192.168.8.100
proxy -n -a -p4453 -i10.9.0.20 -e192.168.9.100
socks -n -a -p7035 -i10.9.0.20 -e192.168.9.100
flush

Скажите,  можно  как  то  это  скрыть , убрать, чтоб ДНС показывался от
провайдера, у меня это мегафон, билайн и теле2.

Или как мне для каждого модема задать свой отдельный DNS ?

Я понимаю что могу добавить:

nserver 8.8.8.8
nserver 77.88.8.8

но они будут браться рандомно, а как сказать ты туда а ту туда и ни как иначе !?

**Comment by z3APA3A** [comment]
Настройки nserver/nscache не привязаны к сервису, они общие для всех сервисов (proxy, socks и т.д.). Можно запустить несколько экземпляров 3proxy с разными настройками.
