### ISSUE TITLE
-De configuration on windows

### ISSUE THREAD

**Issue by mehmetbeyHZ** [z3APA3A/3proxy#605]
How can i configure -De on windows?

ipconfig;
![image](https://user-images.githubusercontent.com/12996462/108887728-ad61e280-761b-11eb-8274-b30f8671d7bc.png)

my conf;
![image](https://user-images.githubusercontent.com/12996462/108887849-ccf90b00-761b-11eb-97cc-05737bdf8e13.png)
(this way linux works fine too)

**Comment by z3APA3A** [comment]
Under windows, binding to IP address also binds to interface, and there is no support for interface binding without binding to IP. That is, short answer is use `-e192.168.1.149`.
