### ISSUE TITLE
logformat always use Global Time(not Local Time) in 0.9.3

### ISSUE THREAD

**Issue by wuhanbin** [z3APA3A/3proxy#606]
Even if the parameter begin with "L"，timezone in log file always +0000，time also is Global Time
3proxy version:0.9.3 
proxy type:socks
system: centos7

**Comment by z3APA3A** [comment]
Please provide more details - log format, local time, example of corresponding log entry. Start 3proxy manually. If you you only see the problem if 3proxy is started via systemd, search for information on how to set timezone for systemd, because systemd uses UTC by default.

**Comment by wuhanbin** [comment]
![image](https://user-images.githubusercontent.com/24507084/109289894-d70c4b00-7861-11eb-9a53-12a361a91c84.png)
yes, start via systemd，user name is proxy
download & install from official  x86_64 rpm package

**Comment by z3APA3A** [comment]
Google on how to change timezone for systemd, e.g. https://hungryadmin.com/setting-the-tz-variable-for-systemd.html

**Comment by wuhanbin** [comment]
Tks a lot, I will try it.

**Comment by z3APA3A** [comment]
If you run 3proxy in chroot envrionment, you may need to add /etc/localtime to 3proxy chroot dir (/usr/local/3proxy). Try to copy /etc/localtime to /usr/local/3proxy/etc/localtime

**Comment by wuhanbin** [comment]
Thanks a lot, now it works!
