### ISSUE TITLE
502 Bad Gateway на Windows

### ISSUE THREAD

**Issue by logoskir** [z3APA3A/3proxy#607]
Добрый день. 
Пытаюсь настроить 2000 ipv6 /48. На Ubuntu проблем не возникает, но на Windows возникают ошибки 502 Bad Gateway или пустой ответ при отправки GET запроса.
Если я отправляю 5 запросов в минуту, то все хорошо работает, но если пытаюсь больше, то сыпятся ошибки. На Ubuntu хоть разом 2к запросов могу отправить. Настройка самих прокси через 3proxy одинаковая что на Ubuntu что на Windows.
В чем может быть проблема?

maxconn 100
nscache 65536
timeouts 1 5 30 60 180 1800 15 60
log "C:\3proxy.log" D
flush

auth strong
users admin:CL:HJDBASDpu
allow admin

**Comment by logoskir** [comment]
В логах ошибка 00000 и 00100.

**Comment by z3APA3A** [comment]
00000 означает что на стороне прокси не было проблем и соединение закрыто клиентом или сервером, 502й ошибки клиент при этом не может получить. 00100 означает что прокси не смог разрешить имя. Возможно, есть какие-то лимиты или затыки на стороне DNS-сервера, антивируса, NAT или самой системы или просто DNS в windows плохо работает если сконфигурировано 2000 адресов. 
Как минимум, необходимо прописать nserver, чтобы не использовать резолвер Windows, а при использовании IPv6 кроме nscache еще и nscache6 чтобы не дергать DNS на каждый запрос.

**Comment by z3APA3A** [comment]
https://3proxy.ru/howtor.asp#ERRORS

**Comment by logoskir** [comment]
В логах _beginthreadex(): Not enough space - очень частая ошибка, как можно ее побороть?
