### ISSUE TITLE
_beginthreadex(): Not enough space

### ISSUE THREAD

**Issue by logoskir** [z3APA3A/3proxy#608]
Добрый день.
В логах частая ошибка _beginthreadex(): Not enough space. 
Как побороть подобную ошибку? Из-за нее приходят пустые GET ответы, обрываются скачивания файлов через прокси.

ОС Windows 

daemon
#nserver 2001:470:20::2
maxconn 10000
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60

flush
auth strong
users admin:CL:HJDBAsdSDpu
allow admin
log "C:\3proxy.log" D

**Comment by z3APA3A** [comment]
Скорей всего, вы используете 32-биную версию приложения и упираетесь в нехватку адресного пространства. См https://3proxy.ru/highload.asp
