### ISSUE TITLE
When add or del sourcelist in allow section,all connections are closed on 0.9 devel version

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#61]
HI,

When add or del sourcelist in allow section,all connections are closed on 0.9 devel version and status was changed from ESTAB to TIME-WAIT.

below is part of 3proxy.cfg,I monitor /etc/ipsallowlist,add or del ip in  /etc/ipsallowlist.It worked fine on version 0.7.1.* 
……
authcache ip 86400
auth cache iponly strong
allow * $/etc/ipsallowlist
monitor /etc/ipsallowlist
……

**Comment by zett83** [comment]
I confirm, the same behavior on 0.9 devel,
also when I reload config by -USR1, all connections are closed.

**Comment by z3APA3A** [comment]
Try devel with latest commit
