### ISSUE TITLE
(Ubuntu)Прокси не работают без nserver

### ISSUE THREAD

**Issue by itgraine** [z3APA3A/3proxy#611]
Здравствуйте!
Поднял прокси на virtualbox(ubuntu) под один модем, но если в 3proxy.cfg не указаны днс адреса то прокси не работают(сайты не открываются), подскажите пожалуйста как сделать так чтобы днс были от провайдера модема? Сейчас если я убираю из настроек nserver то все перестает работать.

**Comment by ezbik** [comment]
Если модем hilink, то его ip это есть dns сервер.

**Comment by itgraine** [comment]
> Если модем hilink, то его ip это есть dns сервер.

Спасибо за ваш ответ, нет у меня можем в режиме stick, режим только модем.

**Comment by z3APA3A** [comment]
Если ты используешь дефолтную инсталляцию 3proxy, то она делает chroot в /usr/local/3proxy и, как миниум, надо пробросить в chroot /etc/resolv.conf для стандартного резолвера, либо использовать 3proxy без chroot.

**Comment by ezbik** [comment]
> режим только модем.

тогда надо ловить DNS от сотового оператора, которые получает демон PPP. И прописывать их в конфиг 3proxy. Иначе никак. 
Или делать какой-то DNSproxy локально, который к этим же DNS обращается.

**Comment by itgraine** [comment]
> Если ты используешь дефолтную инсталляцию 3proxy, то она делает chroot в /usr/local/3proxy и, как миниум, надо пробросить в chroot /etc/resolv.conf для стандартного резолвера, либо использовать 3proxy без chroot. Чтобы использовать без chroot можно конфигурацию перенести в /etc/3proxy/3proxy.cfg, все пути в ней должны быть абсолютными.

Спасибо, получилось! Подскажите, есть возможность скрыть dns основного провайдера? В данный момент при проверки видны днс мобильного оператора и днс выделенного интернета?
