### ISSUE TITLE
Перенаправлять на parent, но с "auth strong"?

### ISSUE THREAD

**Issue by norus** [z3APA3A/3proxy#612]
Имеется внешний прокси на `1.1.1.1:8080`, но на нем нет пользовательского функционала (работает без аутентификации).

Пытаюсь поставить _3proxy_ между пользователем и той прокси, чтобы:

1. требовать аутентифицироваться
2. перенаправлять все запросы

Так работает (без аутентификации):
```shell
nserver 1.1.1.1
nserver 8.8.8.8
nscache 65536
log /var/log/3proxy.log
users someuser:CL:somepass
auth iponly
allow *
parent 1000 http 1.1.1.1 8080
proxy -a -n
```

Так не работает (с аутентификацией):
```shell
nserver 1.1.1.1
nserver 8.8.8.8
nscache 65536
log /var/log/3proxy.log
users someuser:CL:somepass
auth strong
allow *
parent 1000 http 1.1.1.1 8080
proxy -a -n
```

Доки читал, но не нашел ответа. Спасибо создателю!

**Comment by z3APA3A** [comment]
А что значит не работает, как это проверяется и что в логах?

**Comment by norus** [comment]
> А что значит не работает, как это проверяется и что в логах?

В логах, в принципе, все запросы показываются верно и если проверять тем же curl'ом, то ответ приходит верный в обоих случаях. Например:
```shell
curl --proxy 192.168.1.230:3128 --proxy-user someuser:somepass https://ifconfig.me
123.123.123.123
```
Но если прописать proxy в настройках айфона и открыть Facebook или Instagram, то он не загружает все ресурсы, жалуется на сеть. Если же запустить 3proxy с `auth iponly`, то на айфоне работает на 100%. То есть ломается из-за `auth strong` почему-то.

**Comment by z3APA3A** [comment]
Если в логе нет запросов, значит до прокси они не доходят и дело не в auth strong. Попробуй в браузере открыть http://192.168.1.230:3128, ты должен получить ошибку прокси

**Comment by norus** [comment]
Запросы в логе все. У меня логин и пароль прописаны в настройках сети:
![Screen Shot 2021-03-05 at 10 06 39 AM](https://user-images.githubusercontent.com/234848/110093144-a9139300-7d9a-11eb-927b-63d96889b77b.png)

Затем открываю браузер и иду на https://instagram.com:
![Screen Shot 2021-03-05 at 10 05 42 AM](https://user-images.githubusercontent.com/234848/110093223-c0eb1700-7d9a-11eb-950d-91a91c72d40c.png)
В логах видно, что пользователя еще нет:
```shell
210305090601.372 3128 00004 - 192.168.1.201:51048 0.0.0.0:0 0 0 0 CONNECT instagram.com:443 HTTP/1.1
```

Затем ввожу логин и пароль и в логах появляется логин (ruslan):
```shell
210305090615.176 3128 00000 ruslan 192.168.1.201:51039 81.164.212.143:20801 1313 3095 1 CONNECT www.instagram.com:443 HTTP/1.1
```

То есть, непонятно, почему спрашивает логин и пароль, если они уже прописаны в системе. Я проверил, что данные там верные. Видимо, на айфонах происходит то же самое, просто т.к. открываю аппликацию Instagram, то там нет окна для basic auth, поэтому он просто не может загрузить и показывает, что нет соединения. При выключенной аутентификации (auth none) все работает как надо. Я буду рад помочь, если нужны детали по-подробнее.

**Comment by z3APA3A** [comment]
Это стандартное поведение браузера и прокси, логин и пароль прокси передается при получении 407 от прокси, поэтому сначала делается запрос без логина и пароля. Почему не используется логин и пароль прописаный для соединения я сказать не могу, т.к. это вопрос не к прокси.
