### ISSUE TITLE
3g/4g http proxy getting empty reply

### ISSUE THREAD

**Issue by mcaras99** [z3APA3A/3proxy#615]
Hello.

	I am trying to make a 3g/4g proxy for instagram/facebook and have some issues.

	IP of the raspberry pi : 192.168.0.150
	IP of the 4g modem : 192.168.8.100 (when i put it in usb, all have the same ip, i wish i could change them by default, i use HiLink soft)

	I was  following this tutorial, tried a lot of variants :
		https://learnproxy.altervista.org/create-your-own-mobile-4g-proxies-for-instagram-tutorial-2020/

	/home/pi/3proxy.cfg
		#! /usr/local/bin/3proxy
		daemon
		nserver 8.8.8.8
		nscache 65536
		timeouts 1 5 30 60 180 15 60
		users root:CL:pass
		log /var/log/3proxy.log
		#rotate 30
		setgid 13
		setuid 13
		auth none
		allow root
		#DiINTERFACE eth1
		proxy -p3128 -i192.168.0.151 -e192.168.0.151
		#proxy -p3128
		#socks -p3128 -e192.168.8.100
		flush

	ifconfig
		eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
		        inet 192.168.0.150  netmask 255.255.255.0  broadcast 192.168.0.255
		        inet6 fe80::166:abd8:fda7:fb2d  prefixlen 64  scopeid 0x20<link>
		        ether b8:27:eb:af:8a:5e  txqueuelen 1000  (Ethernet)
		        RX packets 3103  bytes 681393 (665.4 KiB)
		        RX errors 0  dropped 0  overruns 0  frame 0
		        TX packets 1683  bytes 280486 (273.9 KiB)
		        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

		eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
		        inet 192.168.8.100  netmask 255.255.255.0  broadcast 192.168.8.255
		        inet6 fe80::151f:4e37:5c61:6be3  prefixlen 64  scopeid 0x20<link>
		        ether 0c:5b:8f:27:9a:64  txqueuelen 1000  (Ethernet)
		        RX packets 6999  bytes 3325464 (3.1 MiB)
		        RX errors 0  dropped 0  overruns 0  frame 0
		        TX packets 70  bytes 9061 (8.8 KiB)
		        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

		lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
		        inet 127.0.0.1  netmask 255.0.0.0
		        inet6 ::1  prefixlen 128  scopeid 0x10<host>
		        loop  txqueuelen 1000  (Local Loopback)
		        RX packets 0  bytes 0 (0.0 B)
		        RX errors 0  dropped 0  overruns 0  frame 0
		        TX packets 0  bytes 0 (0.0 B)
		        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

		wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
		        ether b8:27:eb:fa:df:0b  txqueuelen 1000  (Ethernet)
		        RX packets 0  bytes 0 (0.0 B)
		        RX errors 0  dropped 0  overruns 0  frame 0
		        TX packets 0  bytes 0 (0.0 B)
		        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

	Sudo echo "Let's setup the IP"
		sudo ifconfig eth1 192.168.0.151
		sudo ip route add 192.168.0.0/24 dev eth1 src 192.168.0.151 table gw1
		sudo ip route add default via 192.168.0.1 dev eth1 table gw1
		sudo ip rule add from 192.168.0.151/32 table gw1
		sudo ip rule add to 192.168.0.151/32 table gw1

	this changes the modem ip (eth1) to 192.168.0.151

		sudo 3proxy /home/pi/3proxy.cfg

	/var/log/3proxy.log
		210310152234.875 3128 00000 - 192.168.0.151:3128 192.168.0.151:0 0 0 0 Accepting connections [1957/1995748448]

	sudo curl -s https://wtfismyip.com/text --interface eth0
	IP_OF_THE_RAPSBERRY_PI

	sudo curl -s https://wtfismyip.com/text --interface eth1
	IP_OF_THE_MODEM

	Not working when trying to surf trough proxy, get empty reply
		pi@raspberrypi:~ $ sudo curl -s http://wtfismyip.com/text -v --proxy "192.168.0.151:3128" -U "root:pass"
		* Expire in 0 ms for 6 (transfer 0x1a168b0)
		*   Trying 192.168.0.151...
		* TCP_NODELAY set
		* Expire in 200 ms for 4 (transfer 0x1a168b0)
		* Connected to 192.168.0.151 (192.168.0.151) port 3128 (#0)
		* Proxy auth using Basic with user 'root'
		> GET http://wtfismyip.com/text HTTP/1.1
		> Host: wtfismyip.com
		> Proxy-Authorization: Basic cm9vdDpwYXNz
		> User-Agent: curl/7.64.0
		> Accept: */*
		> Proxy-Connection: Keep-Alive
		> 
		* Empty reply from server <============= i get empty reply
		* Connection #0 to host 192.168.0.151 left intact
		pi@raspberrypi:~ $ 

	/var/log/3proxy.log
		210310152242.023 3128 00518 root 192.168.0.151:58634 95.217.228.176:80 0 0 0 GET http://wtfismyip.com/text HTTP/1.1

	What is happening? I might do some routes wrong, but i don't know for sure. All i want to do is to have 192.168.0.151:3001, 192.168.0.151:3002, 192.168.0.151:3003 as proxies. I might do some routes wrong, but i don't know for sure.

	Thank you.

**Comment by z3APA3A** [comment]
Setting external IP is usually not enough for Linux to route traffic through an interface this IP belongs to. Source routing or binding to interface is additionally required. See -De option for interface bidnig, but source routing is usually a better option. Interface binding requires root and is not compatible with setuid.

**Comment by mcaras99** [comment]
Can you please show me an example or something? Problem is with IPTABLES or the 3proxy config ?

**Comment by z3APA3A** [comment]
What "now i cannot use 2 modems" exactly means? According to logs, you have successful connections to wtfismyip.com through both ports. I do not use modems and I can't reply modem-specific questions.

**Comment by mcaras99** [comment]
inet 192.168.8.100 netmask 255.255.255.0 broadcast 192.168.8.255
inet6 fe80::151f:4e37:5c61:6be3 prefixlen 64 scopeid 0x20
ether 0c:5b:8f:27:9a:64 txqueuelen 1000 (Ethernet)

they have same mac ip, sometimes i get 

210311010400.705 3002 00013 - 192.168.0.73:33748 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311010637.971 3002 00092 - 192.168.0.73:33780 185.60.218.19:443 3258 4206 0 CONNECT web.facebook.com:443 HTTP/1.1
210311010907.982 3002 00092 - 192.168.0.73:33802 185.60.218.19:443 3265 4191 0 CONNECT web.facebook.com:443 HTTP/1.1
210311010928.523 3002 00092 - 192.168.0.73:33806 185.60.218.19:443 1568 3940 0 CONNECT web.facebook.com:443 HTTP/1.1
210311011137.980 3002 00092 - 192.168.0.73:33824 185.60.218.19:443 3277 4190 0 CONNECT web.facebook.com:443 HTTP/1.1
210311011352.698 3002 00012 - 192.168.0.73:33852 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311011622.751 3002 00012 - 192.168.0.73:33942 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311011852.702 3002 00012 - 192.168.0.73:33950 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311012122.701 3002 00012 - 192.168.0.73:33964 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311012352.754 3002 00012 - 192.168.0.73:33970 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311012622.699 3002 00012 - 192.168.0.73:33980 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
210311012747.908 3002 00012 - 192.168.0.73:33990 185.60.218.19:443 0 0 0 CONNECT web.facebook.com:443 HTTP/1.1
root@rasp

any idea why? 12 and 92 error

**Comment by z3APA3A** [comment]
On the moment of these errors external interface was not available. See https://3proxy.ru/howtoe.asp#ERRORS

**Comment by mcaras99** [comment]
i surfed with the proxies for over 3 days, sometimes i got to do a refresh ... any idea why?

cat /var/log/3proxy.log | cut -d " " -f3 | sort | uniq -c
   7085 00000
    136 00012
     55 00013
  15720 00092
     25 00095
     23 00096
     26 00100
      1 00401
     18 00511
      9 00518
      5 00522
      1 00535

so i get a lot of  "92 - connection terminated by timeout (see timeouts)"

any idea why and how to solve? thanks

**Comment by z3APA3A** [comment]
timeout means data expected from client or from server is not received within configured time or connection to server can not be established within configured time. Find a reason for that, for example your connection may be too slow or provider limits a number of connections / rates.

**Comment by mcaras99** [comment]
thank you, you are so kind

timeouts <BYTE_SHORT> <BYTE_LONG> <STRING_SHORT> <STRING_LONG> <CONNECTION_SHORT> <CONNECTION_LONG> <DNS> <CHAIN> <CONNECT> <CONNECTBACK>
Sets timeout values, defaults 1, 5, 30, 60, 180, 1800, 15, 60, 15, 5. 

this is what i have now
timeouts 1 5 30 60 180 15 60

i don't know what to rise, maybe all of them with + 100%?, i stetted up a proxy on the raspberry pi on the main ip itself (no modem), to see if my connection is ok

youtube and other UDP goes trough those proxies? or only TCP ?
