### ISSUE TITLE
domain blacklist

### ISSUE THREAD

**Issue by IUwwju** [z3APA3A/3proxy#618]
приветствую!
голову сломал, почему не работает нормально блэклист доменов.
хочу на сервере заблокировать допустим ya.ru

никакие варианты в конфиге не срабатывают, только один работает , и то НАОБОРОТ =) 

allow *
deny * .ya.ru
proxy
flush

при таком написании отрывает ТОЛЬКО ya.ru, все остальные сайты не работают. 
подскажите в чем косяк. спасибо!

**Comment by z3APA3A** [comment]
Косяк примерно во всем, здесь первое правило разрешает весь трафик, до второго правила проверка никогда не пройдет и второе правило с ошибкой, назначение это третий аргумент,а не второй. Почему у тебя сайты не работают не знаю, скорей всего прокси работает с другой конфигурацией.
```deny * * ya.ru,*.ya.ru
allow *
```

**Comment by IUwwju** [comment]
так я тоже пробовал, сайты открываются все, включая ya.ru

**Comment by IUwwju** [comment]
> Косяк примерно во всем, здесь первое правило разрешает весь трафик, до второго правила проверка никогда не пройдет и второе правило с ошибкой, назначение это третий аргумент,а не второй. Почему у тебя сайты не работают не знаю, скорей всего прокси работает с другой конфигурацией или до этих строк есть еще что-то
> 
> ```
> deny * * ya.ru,*.ya.ru
> allow *
> ```
так я тоже пробовал, сайты открываются все, включая ya.ru

**Comment by IUwwju** [comment]
> Косяк примерно во всем, здесь первое правило разрешает весь трафик, до второго правила проверка никогда не пройдет и второе правило с ошибкой, назначение это третий аргумент,а не второй. Почему у тебя сайты не работают не знаю, скорей всего прокси работает с другой конфигурацией или до этих строк есть еще что-то
> 
> ```
> deny * * ya.ru,*.ya.ru
> allow *
> ```

вот такой конфиг. подскажи пожлайста, где не так. спасибо!
----------------------------
  GNU nano 2.5.3                                File: /home/3prox/PortRotator/3proxy.cfg                                                                      

daemon

maxconn 25

pidfile /usr/local/etc/3proxy.pid

deny * * ya.ru,*.ya.ru
allow *

nserver 219.26.0.121
nserver 95.190.137.10
nscache 65535
stacksize 65536

log @flower
logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
timeouts 1800 1800 1800 1800 1800 1800 1800 1800

auth iponly
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6221
proxy -p37915

**Comment by IUwwju** [comment]
> Косяк примерно во всем, здесь первое правило разрешает весь трафик, до второго правила проверка никогда не пройдет и второе правило с ошибкой, назначение это третий аргумент,а не второй. Почему у тебя сайты не работают не знаю, скорей всего прокси работает с другой конфигурацией или до этих строк есть еще что-то
> 
> ```
> deny * * ya.ru,*.ya.ru
> allow *
> ```

так что в итоге может сказываться на конфиг ? как там может быть нарушен порядок ? можно поподробнее на примере моего конфига? спасибо !

**Comment by z3APA3A** [comment]
У тебя сейчас

deny * * ya.ru,*.ya.ru
allow *
...
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6221

что ты хотел-то? Какой результат от этого ожидается? Опиши что ты хочешь, что ты делаешь, что ты в итоге получаешь (лучше с примером лога)

**Comment by IUwwju** [comment]
> У тебя сейчас
> 
> deny * * ya.ru,*.ya.ru
> allow *
> ...
> allow * 52.14.13.14
> parent 1000 connect 23.133.2.1 6221
> 
> что ты хотел-то? Какой результат от этого ожидается? Опиши что ты хочешь, что ты делаешь, что ты в итоге получаешь (лучше с примером лога)

ну смотри, у меня ротатор направляет трафик с портов провайдера в порты клиентов через мой сервер. 
```
auth iponly
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6221
proxy -p37915

flush
```
вот это блок типичного редиректа трафика с одного порта на другой (их там много, они все выглядят одинакого, только разные айпишники и порты)

выше этого блока идет кусок конфига, больше ничего нет.

мне нужно заблокировать ТОЛЬКО домен ya.ru , чтобы на запросы по этому домену происходил reject или что угодно, просто чтобы трафик не шел на ya.ru

как мне в конфиге написать, чтобы заработало ? 
спасибо !

**Comment by z3APA3A** [comment]
flush сбрасывает предыдущие ACL. deny надо поставить после flush и перед allow в каждом блоке

**Comment by IUwwju** [comment]
```
flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
deny * * ya.ru,*.ya.ru
parent 1000 connect 23.133.2.1 6222
proxy -p37916

flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
deny * * ya.ru,*.ya.ru
parent 1000 connect 23.133.2.1 6223
proxy -p37917

flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
deny * * ya.ru,*.ya.ru
parent 1000 connect 23.133.2.1 6224
proxy -p37918

итд ...
```
так чтоли ?

**Comment by IUwwju** [comment]
> flush сбрасывает предыдущие ACL. deny надо поставить после flush и перед allow в каждом блоке

еще раз, у меня конфиг генерится с помощью скрипта и выглядит так 

```
daemon

maxconn 25

pidfile /usr/local/etc/3proxy.pid

nserver 219.26.0.121
nserver 95.190.137.10
nscache 65535
stacksize 65536

log @flower
logformat "L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
timeouts 1800 1800 1800 1800 1800 1800 1800 1800


auth iponly
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6222
proxy -p37916

flush
auth iponly
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6223
proxy -p37917

flush
auth iponly
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6224
proxy -p37918

итд вниз много таких блоков

```

куда втыкать 
deny * * ya.ru,*.ya.ru

?

**Comment by ezbik** [comment]
> куда втыкать
> deny * * ya.ru,*.ya.ru

Много раз, перед каждым allow

**Comment by IUwwju** [comment]
> > куда втыкать
> > deny * * ya.ru,*.ya.ru
> 
> Много раз, перед каждым allow
> Перед == на строке предыдущей перед
```

flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6223
proxy -p37917

flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6224
proxy -p37918

flush
auth iponly
deny * * ya.ru,*.ya.ru
allow * 52.14.13.14
parent 1000 connect 23.133.2.1 6225
proxy -p37919
```


так ?

**Comment by IUwwju** [comment]
УРА!! заработало !!!
