### ISSUE TITLE
DNS Leak using both Https/Socks Proxy.

### ISSUE THREAD

**Issue by agarwalbikram** [z3APA3A/3proxy#619]
Hello,
When i use this proxy in Browser i see it leak DNS of PC on which we are using it on.
Proxy is setup on Ubuntu 20.04 with Version 3 proxy 0.8

daemon

fakeresolve

nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1

nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users $/etc/3proxy/.proxyauth

log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 1

maxconn 10000
authcache user 60

auth strong cache
allow *
parent 1000 socks5+ xyzip.com 1080 user pass
socks -n -p33312 -a
proxy -n -p33313 -a

**Comment by z3APA3A** [comment]
"nserver" is contrary to "fakeresolve", fakeresolve does not work in this configuration, because nserver goes after it. Remove nserver and use IP instead of hostname in "parent".

**Comment by agarwalbikram** [comment]
Here is the new Config and it still leak the DNS records.

daemon
fakeresolve
nscache 65536
timeouts 1 5 30 60 180 1800 15 60

users $/etc/3proxy/.proxyauth

log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 1

maxconn 10000
authcache user 60

auth strong cache
allow *
parent 1000 socks5+ 192.168.0.0 1080 user pass
socks -n -p33312 -a
proxy -n -p33313 -a

**Comment by z3APA3A** [comment]
This config can not leak DNS on proxy side because it does not use DNS (nscache is not required here). Either you have not applied this config or DNS is leaked by client (e.g. curl need to be used with --socks5-hostname instead of --socks5).

**Comment by agarwalbikram** [comment]
Ok, Thank You for the prompt response.
