### ISSUE TITLE
3proxy 0.8.6 crash

### ISSUE THREAD

**Issue by halit63** [z3APA3A/3proxy#62]
Служба 3proxy версии 0.8.6 lite регулярно крашится, в журнале Windows (XP SP3) записи вида:
"04.04.2016	11:16:34	Application Popup	Уведомление	Отсутствует	26	Н/Д	PC2	"Всплывающее окно приложения: 3proxy.exe - Ошибка приложения : Инструкция по адресу ""0x77c32a16"" обратилась к памяти по адресу ""0x00000001"". Память не может быть ""read""."

Приходится откатываться на версию 0.7.1.3, с ней такой проблемы нет.

**Comment by z3APA3A** [comment]
Регулярно крешится или вообще все запросы не проходят?

**Comment by halit63** [comment]
Есть 2 варианта. Первый - служба некоторое время работает нормально (несколько часов или даже пару дней, не больше) и потом служба вылетает с указанным сообщением. Второй - служба вылетает сразу при запуске. 
Полагаю, как-то связано с загрузкой службы в целом или какими-то определенными запросами от пользовательских станций.

**Comment by z3APA3A** [comment]
Попробуй последний http://3proxy.ru/current/3proxy-0.9-lite-devel.zip - собрал с другим компилятором, должен лучше поддерживать старые платформы.

**Comment by halit63** [comment]
Спасибо.
Поставил сегодня эту версию, отпишусь через недельку (или раньше, если проблемы опять проявят себя).


>Воскресенье,  4 сентября 2016, 17:03 +04:00 от Vladimir Dubrovin <notifications@github.com>:
>
>Попробуй последний  http://3proxy.ru/current/3proxy-0.9-lite-devel.zip - собрал с другим компилятором, должен лучше поддерживать старые платформы.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Халит Курмаев
halit@mail.ru

**Comment by z3APA3A** [comment]
Если получится - 0.8.7-lite использует ту же сборку

**Comment by halit63** [comment]
Попробую для начала lite 0.9, если будут проблемы - попробую lite 0.8.7.


>Понедельник,  5 сентября 2016, 18:27 +04:00 от Vladimir Dubrovin <notifications@github.com>:
>
>Если получится - 0.8.7-lite использует ту же сборку
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Халит Курмаев
halit@mail.ru

**Comment by z3APA3A** [comment]
Смысла нет, по коду то. что сейчас в devel полностью идентично 0.8.7

**Comment by halit63** [comment]
Третий день прокси 0.9 devel крутится в офисе, полет нормальный :)

Спасибо!


>Понедельник,  5 сентября 2016, 18:31 +04:00 от Vladimir Dubrovin <notifications@github.com>:
>
>Смысла нет, по коду то. что сейчас в devel полностью идентично 0.8.7
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


С уважением,
Халит Курмаев
halit@mail.ru
