### ISSUE TITLE
Cannot use setuid/setgid

### ISSUE THREAD

**Issue by xzycn** [z3APA3A/3proxy#621]
Hi, I'm using version 0.9.3, I got the the error message:
> Unable to set gid 65534Command: 'setgid' failed with code 1, line 10

Below is my conf :

> setgid 65534 
> setuid 65534

What should I to solve this?

**Comment by z3APA3A** [comment]
It means 3proxy is not running as root at this line. If you start 3proxy manually with your own configuration, use sudo. If you use default configs on linux, setuid/setgid are set in pre-chroot config (/etc/3proxy/3proxy.cfg), because chroot config is executed after setuid/setgid.

**Comment by xzycn** [comment]
@z3APA3A 

I‘m using **root**, I start 3proxy using **systemctl start 3proxy**(that is I'm using default configs on linux).

and I found another problem:
the pid in **/var/run/3proxy/3proxy.pid** is 4514
,but the pid is 4517 through **ps** .

**Comment by z3APA3A** [comment]
If you use default configs on linux, setuid/setgid are set in pre-chroot config (/etc/3proxy/3proxy.cfg), because chroot config is executed after setuid/setgid.
for pid file, check pidflie command goes after daemon (because daemon changes pid) and before setuid/setgid/chroot.
