### ISSUE TITLE
Просадки интернета

### ISSUE THREAD

**Issue by logoskir** [z3APA3A/3proxy#622]
Добрый день.
Настроил 3proxy ipv6 /48 на серверах Hetzner(Windows server 2019) и simplecloud(Ubuntu 16), через туннельного брокера tunnelbroker.

Прокси использую для скачивания файлов. Качаю файлы с серверов Hetzner. Если использую прокси, настроенные на simplecloud(Ubuntu), то все хорошо, ошибок не встречается. Если использую Hetzner(Windows), то появляются такие просадки как на скриншоте, соответственно файлы крашатся.
![image](https://user-images.githubusercontent.com/37247790/112301552-1e43fb00-8cab-11eb-87fb-ca61b28f65cf.png)

В логах при обрыве появляются такие строки 210304061817.064 31318 00000 admin 179.хх.хх.хх:57736 2a02:хх:хх:хх::хх:хх:443 1106 1088424215 0 CONNECT site:443 HTTP/1.1.
Количество таких строк равно количеству потоков, скачивающих файл, которые оборвались
В момент таких просадок примерно 10-20 потоков из 800 улетают. И такие обрывы раз в 10 минут

Вопрос: Как мне определить с чем связаны такие просадки

cfg на Windows
maxconn 10000
nscache 65536
nscache6 65536
timeouts 1 5 30 60 180 1800 15 60
flush
auth strong
users admin:CL:pass
allow admin

**Comment by z3APA3A** [comment]
00000 означает что соединение было закрыто в штатном режиме со стороны клиента или со стороны сервера, т.е. скорей всего на них сработал таймаут из-за того что данные не получалось отправить или считать. Судя по тому, что receive гораздо больше чем send прокси не может отправить данные в сторону клиента. Выглядит это так, что действительно просел канал между клиентами и прокси и/или начал срабатывать congestion avoidance.
