### ISSUE TITLE
Radius

### ISSUE THREAD

**Issue by anrednn** [z3APA3A/3proxy#623]
Framed-IP-Address / Framed-IPv6-Address in servers's reply (only one address may present and is used as 'external' IP)
Хотелось бы увидеть отработку двух атрибутов на external))

**Comment by z3APA3A** [comment]
Расскажи полностью usecase, зачем здесь требуется 2 адреса. Адрес назначения уже известен, соответственно он доступен или по IPv4 или по IPv6

**Comment by anrednn** [comment]
Самая примитивная схема когда прилетает 2 значения ipv4\ipv6 для выхода клиента в сеть при настройке 
того же socks\proxy  -64 с указанными явными external ipv4\ipv6

**Comment by z3APA3A** [comment]
2 значения никогда не прилетает в RADIUS, прилетает или  Login-IP-Host или Login-IPv6-Host, соотвественно ответить надо или Framed-IP-Address или Framed-IPv6-Address

**Comment by z3APA3A** [comment]
Я могу придумать только кейс когда родительский прокси выбирается на стороне 3proxy а интерфейс для него на стороне RADIUS, но он кажется совсем странным и не юзабельным.

**Comment by anrednn** [comment]
Да все верно про ответ и говорил, но значения ответа могут быть  Framed-IP-Address или Framed-IPv6-Address или оба есть RFC на эту тему A Model of IPv6/IPv4 Dual Stack Internet Access Service и как раз описания для радиуса тоже
