### ISSUE TITLE
Compile dll

### ISSUE THREAD

**Issue by negativelol** [z3APA3A/3proxy#624]
Возможно ли как то скомпилировать проект в dll 3proxy.
Например скомпилилось 3proxy.dll после запускаем rundll32.exe 3proxy.dll,EntryPoint
Или добавте пожалуйста такую возможность если нельзя.

**Comment by z3APA3A** [comment]
Для легитимного использования этого не требуется, а разработкой для целей нелегитимного использования я не занимаюсь.
