### ISSUE TITLE
Website blacklist not working, I have tried all possible ways

### ISSUE THREAD

**Issue by agarwalbikram** [z3APA3A/3proxy#625]
Hello,
I want to block many websites in the proxy config but i am not able to archive it.
Below is my Config.

daemon

nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1

nscache 65536

timeouts 1 5 30 60 180 1800 15 60

users $/etc/3proxy/.proxyauth

log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 1

maxconn 10000
authcache user 60

flush
auth strong cache
deny * * *.eth0.me
allow *
parent 1000 socks5+ 127.0.0.1 9010

socks -n -p33312 -a
proxy -n -p33313 -a

**Comment by z3APA3A** [comment]
what do you have in logs?

**Comment by agarwalbikram** [comment]
1616752292.020 PROXY.33313 00000 sh 13.127.166.185:63105 13.127.200.48:33312 757 4516 1 CONNECT_mtalk.google.com:5228_HTTP/1.1
1616752292.074 PROXY.33313 00000 sh 13.127.166.185:63043 13.127.200.48:33312 1350 4772 1 CONNECT_accounts.google.com:443_HTTP/1.1
1616752292.074 PROXY.33313 00000 sh 13.127.166.185:63063 13.127.200.48:33312 1768 44940 1 CONNECT_172.217.194.99:443_HTTP/1.1
1616752292.078 PROXY.33313 00000 sh 13.127.166.185:63133 13.127.200.48:33312 808 382 1 CONNECT_eth0.me:80_HTTP/1.1
1616752292.078 PROXY.33313 00000 sh 13.127.166.185:63130 13.127.200.48:33312 0 40 1 CONNECT_eth0.me:80_HTTP/1.1
1616752292.078 PROXY.33313 00000 sh 13.127.166.185:63052 13.127.200.48:33312 581 3300 1 CONNECT_accounts.google.com:443_HTTP/1.1
1616752292.078 PROXY.33313 00000 sh 13.127.166.185:63108 13.127.200.48:33312 581 3655 1 CONNECT_172.217.194.94:443_HTTP/1.1
1616752292.086 PROXY.33313 00000 sh 13.127.166.185:63048 13.127.200.48:33312 1049 4034 1 CONNECT_clientservices.googleapis.com:443_HTTP/1.1
1616752292.086 PROXY.33313 00000 sh 13.127.166.185:63040 13.127.200.48:33312 581 3670 1 CONNECT_clientservices.googleapis.com:443_HTTP/1.1

**Comment by z3APA3A** [comment]
try
deny * * *.eth0.me,eth0.me

**Comment by agarwalbikram** [comment]
Ok, This worked, Why only adding eth0.me one time is not working?

**Comment by z3APA3A** [comment]
eth0.me is enough if you need to block eth0.me without subdomains.

**Comment by agarwalbikram** [comment]
Here is my another use case in this case blacklist is not woking.

daemon

nserver 8.8.8.8
nserver 8.8.4.4
nserver 1.1.1.1
nserver 1.0.0.1

nscache 65536

timeouts 1 5 30 60 180 1800 15 60

users $/etc/3proxy/.proxyauth

log /var/log/3proxy/3proxy.log
logformat "- +_L%t.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 1

maxconn 10000
authcache user 60

flush
auth strong cache
deny * * eth0.me,*.googlesyndication.com,*.googleadservices.com
allow *
parent 1000 socks5+ 13.127.240.48 33312 sh shw5
socks -n -p33312 -a
proxy -n -p33313 -a

flush
auth strong cache
deny * * eth0.me,*.ipinfo.io
allow *
parent 1000 http 13.90.0.189 3128 sh sh09345
socks -n -p33314 -a
proxy -n -p33315 -a

**Comment by z3APA3A** [comment]
what fo you have in logs?

**Comment by agarwalbikram** [comment]
1617034009.198 PROXY.33313 00000 sh 13.127.166.185:61628 13.127.200.48:33312 1594 729 1 CONNECT_5.132.162.27:80_HTTP/1.1
1617034009.198 PROXY.33313 00000 sh 13.127.166.185:61631 13.127.200.48:33312 0 45 1 CONNECT_5.132.162.27:80_HTTP/1.1
1617034018.734 PROXY.33313 00000 sh 13.127.166.185:61646 13.127.200.48:33312 784 383 1 CONNECT_5.132.162.27:80_HTTP/1.1
1617034018.734 PROXY.33313 00000 sh 13.127.166.185:61649 13.127.200.48:33312 0 45 1 CONNECT_5.132.162.27:80_HTTP/1.1
1617034019.694 PROXY.33313 00000 sh 13.127.166.185:61637 13.127.200.48:33312 581 3294 1 CONNECT_172.217.166.45:443_HTTP/1.1
1617034019.694 PROXY.33313 00000 sh 13.127.166.185:61643 13.127.200.48:33312 581 2676 1 CONNECT_142.250.192.36:443_HTTP/1.1
1617034019.701 PROXY.33313 00000 sh 13.127.166.185:61635 13.127.200.48:33312 1049 4019 1 CONNECT_142.250.182.227:443_HTTP/1.1
1617034019.709 PROXY.33313 00000 sh 13.127.166.185:61641 13.127.200.48:33312 659 840 1 CONNECT_142.250.182.227:443_HTTP/1.1

**Comment by z3APA3A** [comment]
This request does not contain hostname. You can try to deny requests with ip address.

**Comment by agarwalbikram** [comment]
Is not resolving hostname issue from my side?

**Comment by agarwalbikram** [comment]
I have tried to reinstall 3proxy in different machine too with same config and also try to block many other websites but i still get no success when i see log i don't see hostname for those websites
Log here:

1617372556.664 PROXY.9998 00000 sh 13.127.166.185:60277 127.0.0.1:9020 0 31 1 CONNECT_65.0.168.119:80_HTTP/1.1
1617372556.665 PROXY.9998 00000 sh 13.127.166.185:60329 127.0.0.1:9040 581 3030 1 CONNECT_216.239.34.21:443_HTTP/1.1
1617372556.666 PROXY.9998 00000 sh 13.127.166.185:60308 127.0.0.1:9010 581 3030 1 CONNECT_216.239.34.21:443_HTTP/1.1
1617372556.666 PROXY.9998 00000 sh 13.127.166.185:60325 127.0.0.1:9020 581 3042 1 CONNECT_216.239.32.21:443_HTTP/1.1
1617372556.667 PROXY.9998 00000 sh 13.127.166.185:60317 127.0.0.1:9030 581 3492 1 CONNECT_172.217.194.154:443_HTTP/1.1
1617372556.668 PROXY.9998 00000 sh 13.127.166.185:60288 127.0.0.1:9040 650 822 1 CONNECT_35.190.88.7:443_HTTP/1.1
1617372556.668 PROXY.9998 00000 sh 13.127.166.185:60282 127.0.0.1:9010 0 31 1 CONNECT_65.0.168.119:80_HTTP/1.1
1617372556.668 PROXY.9998 00000 sh 13.127.166.185:60311 127.0.0.1:9040 654 826 1 CONNECT_142.250.192.110:443_HTTP/1.1
1617372589.757 SOCK5.9999 00000 sh 13.127.166.185:60344 127.0.0.1:9030 2286 536478 1 CONNECT_65.0.168.119:80
1617372616.937 SOCK5.9999 00000 sh 13.127.166.185:60362 127.0.0.1:9010 581 2664 1 CONNECT_142.250.67.132:443
1617372619.803 SOCK5.9999 00000 sh 13.127.166.185:60354 127.0.0.1:9030 0 31 1 CONNECT_5.132.162.27:80
1617372620.034 SOCK5.9999 00000 sh 13.127.166.185:60359 127.0.0.1:9030 0 31 1 CONNECT_5.132.162.27:80
1617372625.581 SOCK5.9999 00000 sh 13.127.166.185:60356 127.0.0.1:9020 879 373 1 CONNECT_5.132.162.27:80

**Comment by z3APA3A** [comment]
client can make request by name or ip address (e.g. curl with socks5 requests IP, curl with socks5h requests by socksname).

**Comment by agarwalbikram** [comment]
I am have tried using socks5 and https too, I am using this proxy in browser.
Is there any we can force hostname and block website, I want to block 30K websites.
Struggling from a week now to archive this.

**Comment by z3APA3A** [comment]
Sending hostname can only be configured on client side.
You can prevent access by IP address, e.g.
deny * * *0,*1,*2,*3,*4,*5,*6,*7,*8,*9

**Comment by agarwalbikram** [comment]
Ok, Thank You. But IP blacklist is not a solution for me because there can be multiple website on same IP, But we can block the whole IP.

**Comment by ezbik** [comment]
@z3APA3A wow. it is something new to me. 

> Ok, Thank You. But IP blacklist is not a solution for me because there can be multiple website on same IP, But we can block the whole IP.

That means request towards IP's will be blocked, if a website is addressed by  IP. Requests towards hostnames are not processed by that ACL line.
