### ISSUE TITLE
Где взять отдельные модули для Windows?

### ISSUE THREAD

**Issue by spiller1975** [z3APA3A/3proxy#626]
Здравствуйте.

Подскажите, пожалуйста, нужен отдельный модуль proxy.exe или socks.exe для Windows.
Можно его где-то скачать в готовом виде?
А то что-то с компиляцией под Windows не получается...

Мне нужен простой вариант прокси сервера без настроек.

**Comment by z3APA3A** [comment]
На proxy.exe/socks.exe стабильно фолзят антивирусы, поэтому в готовом виде они не распространяются. Можешь из сорсов или запустить 
cmd /c (echo proxy | 3proxy con)
cmd /c (echo socks | 3proxy con)
что будет работать ровно так же.
