### ISSUE TITLE
proxy timeout errors

### ISSUE THREAD

**Issue by mcaras99** [z3APA3A/3proxy#627]
Hello.

I have a 4G USB Modem and i use 3proxy for making a proxy. I get a lot of timeouts, sometimes SSL errors. I believe sometimes AJAX request getting timeout and the website gets half-loaded ... JS code won't get executed all the time till the end ... it is horror

Sometimes i get timeout, sometimes not ...

**CONFIG:**

```
daemon
nserver 8.8.8.8
nscache 65536
timeouts 5 15 60 180 180 30 60
users user:CL:pass
log /home/3g4g_lte_proxy/log/3proxy.proxy1.log
auth none
allow root
proxy -p3001 -Dieth0 -Deeth1
```

**ERRORS:**
```
cat 3proxy.proxy1.log  | cut -d " " -f3 | sort | uniq -c
      1 
   1602 00000
    246 00013
   9922 00092 <== the most common error
      5 00095
     17 00096
     19 00100
     47 00522
```

I also tried to do a proxy on the same server but on self ip, everything is ok, so the problem is only when i go trough 4G modem. I suspected that there might be a problem that the modem won't get sufficient amps + volts ... and i bought a usb hub with aux power. Where the problem can be?

Thank you.

**Comment by z3APA3A** [comment]
You've got response in #615. You can check netstat for connection status, if connection is established it means timeouts is for reading/wring data. If you see half-open connections it means you have connection establishing problems.
