### ISSUE TITLE
OpenSSL SSL_connect SSL_ERROR_SYSCALL

### ISSUE THREAD

**Issue by mehmetbeyHZ** [z3APA3A/3proxy#628]
When I run the proxies it randomly gives the following message.
Curl; 
```
OpenSSL`SSL_connect:` SSL_ERROR_SYSCALL in connection to i.instagram.com:443
```
Why does this happen and how can I solve this problem?

Headers and response;

```
{
  "headers": {
    "content_type": null,
    "http_code": 0,
    "header_size": 39,
    "request_size": 253,
    "filetime": -1,
    "ssl_verify_result": 1,
    "redirect_count": 0,
    "total_time": 12.747733,
    "namelookup_time": 0.00001,
    "connect_time": 1.691092,
    "pretransfer_time": 0,
    "size_upload": 0,
    "size_download": 0,
    "speed_download": 0,
    "speed_upload": 0,
    "download_content_length": -1,
    "upload_content_length": -1,
    "starttransfer_time": 0,
    "redirect_time": 0,
    "redirect_url": "",
    "primary_ip": "195.xxx.xxx.xxx",
    "certinfo": [],
    "primary_port": 8096,
    "local_ip": "136.xxx.33.xx",
    "local_port": 52550,
    "http_version": 0,
    "protocol": 2,
    "ssl_verifyresult": 0,
    "scheme": "HTTPS"
  },
  "response": null,
  "curl": "OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to i.instagram.com:443 "
}
````

**Comment by z3APA3A** [comment]
Check the logs. See https://3proxy.ru/howtoe.asp for error code description. Check you have sufficient resources / limits https://3proxy.ru/howtoe.asp

**Comment by mehmetbeyHZ** [comment]
> Check the logs. See https://3proxy.ru/howtoe.asp for error code description. Check you have sufficient resources / limits https://3proxy.ru/howtoe.asp

I checked the error logs, but they all seem to be "0" so successful. but http curl results in Open SSL error. There are 77 4.5G USB Modems on 1 computer, can it be due to the load here? I don't have any performance issues, optimized for high load configuration.
Main modem has 100mbit upload and download 
also usb modems have 50mbit upload/download speed

**Comment by z3APA3A** [comment]
If curl error is stable, it probably means you incorrectly specify proxy type. Check you use http:// as a proxy URI in curl (not https://).

**Comment by mehmetbeyHZ** [comment]
> If curl error is stable, it probably means you incorrectly specify proxy type. Check you use http:// as a proxy URI in curl (not https://). http:// proxy should be used for both http:// and https:// targets.

I checked my 1 day logs again and reached the following results;
```
1617379343.613 PROXY.8090 00096 mroot 192.168.3.51:52718 172.64.99.4:443 0 0 0 CONNECT_jsonplaceholder.typicode.com:443_HTTP/1.1
1617379353.980 PROXY.8090 00096 mroot 192.168.3.51:53402 172.64.99.4:443 517 0 0 CONNECT_jsonplaceholder.typicode.com:443_HTTP/1.1
1617379360.118 PROXY.8090 00095 mroot 192.168.3.51:53832 172.64.99.4:443 39550 472076 0 CONNECT_jsonplaceholder.typicode.com:443_HTTP/1.1
```

3Proxy Description;
```
95 - dirty connection termination by client (or networking issue)
96 - dirty connection termination by server (or networking issue)
```

Is the source of this problem from me or is it from the remote server?

**Comment by z3APA3A** [comment]
You can match it with your problem by time and/or source port
