### ISSUE TITLE
Block an IP

### ISSUE THREAD

**Issue by APX403** [z3APA3A/3proxy#630]
Hello !

I would like to deny an IP to connect to the proxy, how can I achieve that ?

I already tried :

deny * THE_IP_ADDRESS *

But it didn't worked, I still se connexion from that IP in my logs.

Thanks a lot

**Comment by z3APA3A** [comment]
It probably means either the sequence of commands is wrong (e.g. you have matching allow rule prior to deny) or you use `auth none` or you did not applied configuration after changes.
