### ISSUE TITLE
how to add whitelist for both http and socks5

### ISSUE THREAD

**Issue by afatsoum** [z3APA3A/3proxy#632]
I am trying to apply the whitelist to both HTTP & SOCKS5 proxy connections. The whitelist is working for HTTP proxies but completely failing for SOCKS5. Please advise of correct configuration to accomplish this.

Here is the current configuration

```
#HTTP CONFIG

#HTTP whitelist
allow * * *.google.com,google.com,*.bing.com,bing.com
deny *
proxy

#HTTP Authentication
auth strong
users demo:CL:abc123
allow demo

#HTTP proxy
proxy -n -a -p3061 -i192.168.0.5 -e192.168.1.150

#SOCKS5 CONFIG
flush

#SOCKS5 whitelist
allow * * *.google.com,google.com,*.bing.com,bing.com
deny *
socks

#SOCKS5 Authentication
auth strong
users demo:CL:abc123
allow demo

#SOCKS5 proxy
socks -p4061 -i192.168.0.5 -e192.168.1.150
```

If I also add whitelist after flush for socks5 then connection doesn't work at all to any website even whitelisted ones. 

curl -x "socks5://demo:abc123@192.168.0.5:4061" "google.com"
curl: (7) Can't complete SOCKS5 connection to 0000:0000:0000:0000:0000:0000:0000:0000:0. (2)

Here is the log record for the failures:
SOCK5.4061 demo 0.0.0.0 4062 192.168.0.5:62120 142.250.70.196:80 CONNECT_142.250.70.196:80

If I remove whitelist for socks5 then connection is working again
SOCK5.4061 demo 192.168.1.150 4061 192.168.0.5:59287 142.250.70.164:80 CONNECT_142.250.70.164:80

**Comment by z3APA3A** [comment]
Use socks5h:// instead of socks5://.
