### ISSUE TITLE
0.9.3 x64: Ошибка в обработке allow

### ISSUE THREAD

**Issue by JMKh3r** [z3APA3A/3proxy#633]
v. 0.9.3 x64

В конфиге прописано:

```
flush
auth iponly strong
allow  *  *  gosuslugi.ru  80,443  HTTP,HTTPS
allow  *  *  gu-st.ru  80,443  HTTP,HTTPS
deny * * 0.0.0.0 0
deny -
proxy -n -l"3proxy.log"

```

На gosuslugi.ru пускает без проблем.
А на gu-st.ru не пускает с кодом ошибки 00004.
Похоже проблема в тире в доменном имени.
Попробовал еще одно dns-имя с тире - та же ситуация.
Подскажите, это баг или что-то у меня не так в настройках?

**Comment by JMKh3r** [comment]
Попробовал версию 0.8.13 x64.
То же самое - в логе ошибка 00004
Браузеру прокси возвращает: 407 Proxy Authentication Required

**Comment by JMKh3r** [comment]
В версии 0.7.1.4 все работает нормально

**Comment by z3APA3A** [comment]
Что в логе?

**Comment by JMKh3r** [comment]
> Что в логе?

`192.168.xxx.xxx	-	2021-04-12 13:42:17	00004	PROXY/0.0.0.0:0	gu-st.ru	0	0	"CONNECT gu-st.ru:443 HTTP/1.1"`

**Comment by z3APA3A** [comment]
Должно быть пофикшено в текущем мастере/девеле, см #637
