### ISSUE TITLE
How to configure reverse proxy socks5 ?

### ISSUE THREAD

**Issue by sunlewuyou** [z3APA3A/3proxy#635]
Hello everyone, can anyone who is enthusiastic can demonstrate how to set up reverse proxy socks5? I did not find such an introduction in the official documentation. After a lot of detours, I still didn't succeed. Looking forward to your reply!

**Comment by ezbik** [comment]
@sunlewuyou from my experience, 3proxy is not the best software to run *reverse proxies*. 
And to be honest "reverse proxy" means a proxy that is installed before a WEB server, e.g. to provide load balancing or caching or TLS termination. 
What you're referring to, in 3proxy terminology it is called ConnectBack proxy.
Yet ConnectBack is almost not documented.
Here is my humble Howto for ConnectBack in 3proxy.

---


**Connectback limitations**

- It is bound to tcppm therefore is only working with "iponly" ACL type. Which is bad because external IP of the server behind NAT may change.
- if `tcppm -R` CBACK listener accepts more  than 2 clients (`proxy -r`), then it splits the traffic between them.

**Related links**

https://github.com/z3APA3A/3proxy/issues/263
https://3proxy.ru/howtoe.asp#CONNBACK

**cloud VPS (tos.org)**

```
log /log/proxy.log
auth iponly
allow * * *
tcppm -R0.0.0.0:3007 4007 0.0.0.0 7
# why 7? I like the number :-) it just has to be nonzero
# tcppm [-d] [-l[[@]logfile]] [-iinternal_ip] [-eexternal_ip] local_port remote_host remote_port
```

**proxy server in private LAN , behind nat**

```
users xxx:CL:123
auth strong
allow xxx *
proxy -rtos.org:3007 -p
```

**proxy client**

  test_proxy_std tos.org:4007:xxx:123

**Comment by sunlewuyou** [comment]
> @sunlewuyou from my experience, 3proxy is not the best software to run *reverse proxies*. 
> And to be honest "reverse proxy" means a proxy that is installed before a WEB server, e.g. to provide load balancing or caching or TLS termination. 
> What you're referring to, in 3proxy terminology it is called ConnectBack proxy.
> Yet ConnectBack is almost not documented.
> Here is my humble Howto for ConnectBack in 3proxy.
> 
> ---
> 
> 
> **Connectback limitations**
> 
> - It is bound to tcppm therefore is only working with "iponly" ACL type. Which is bad because external IP of the server behind NAT may change.
> - if `tcppm -R` CBACK listener accepts more  than 2 clients (`proxy -r`), then it splits the traffic between them.
> 
> **Related links**
> 
> https://github.com/z3APA3A/3proxy/issues/263
> https://3proxy.ru/howtoe.asp#CONNBACK
> 
> **cloud VPS (tos.org)**
> 
> ```
> log /log/proxy.log
> auth iponly
> allow * * *
> tcppm -R0.0.0.0:3007 4007 0.0.0.0 7
> # why 7? I like the number :-) it just has to be nonzero
> # tcppm [-d] [-l[[@]logfile]] [-iinternal_ip] [-eexternal_ip] local_port remote_host remote_port
> ```
> 
> **proxy server in private LAN , behind nat**
> 
> ```
> users xxx:CL:123
> auth strong
> allow xxx *
> proxy -rtos.org:3007 -p
> ```
> 
> **proxy client**
> 
>   test_proxy_std tos.org:4007:xxx:123
> 
> 

First of all thank you for your reply! In fact, the reverse proxy socks I'm talking about is like this software: https://github.com/kost/revsocks, 3proxy file is much smaller and the function is very powerful, I just want 3proxy to do the same thing as it.

**Comment by ezbik** [comment]
@sunlewuyou ok, my howto covers that. But it describes HTTP proxy installation , not Socks. So change "proxy" with "socks" in the conf file.

**Comment by sunlewuyou** [comment]
@ezbik Thank you very much for your enthusiasm and wish you a happy life! I will test according to your method, thanks again!

**Comment by sunlewuyou** [comment]
@ezbik Facts have proved that your configuration is feasible. But how do we keep the connection uninterrupted? Because I found that it will automatically disconnect, as shown below:
![image](https://user-images.githubusercontent.com/19728435/114539554-3219c600-9c87-11eb-9587-0ccce1dde62f.png)

**Comment by ezbik** [comment]
@sunlewuyou I don't know. May be check internet connection between proxy_client--cback_server---proxy_server

**Comment by z3APA3A** [comment]
use "timeouts" to set CONNECTION_LONG timeout to some high value

**Comment by sunlewuyou** [comment]
@z3APA3A Example: timeouts 1 5 30 60 180 1800 15 60 15 5
The socks connection will remain for 1800 seconds and will not be automatically released, right ?
Thanks !

**Comment by sunlewuyou** [comment]
@z3APA3A After trying this method, it still doesn't work. The connection will be automatically disconnected within a minute, and it will not resume the connection after a few seconds until there is a new connection request.
```
timeouts 1 5 30 60 180 180000 15 60 15 5
users user:CL:password
auth strong
allow user
socks -rvps.com:8443
```

**Comment by z3APA3A** [comment]
It may be a NAT problem, try to set SO_KEEPALIVE (see -or and -oR) and configure small keepalive time (/proc/sys/net/ipv4/tcp_keepalive_time)

**Comment by sunlewuyou** [comment]
@z3APA3A Thank you for your reply. I used revsocks to test that the connection can be kept long. Modifying SO_KEEPALIVE I am worried that it will affect the server. Thank you again for your suggestions.

**Comment by sunlewuyou** [comment]
@z3APA3A According to your suggestion, I conducted some tests, but the problem still exists, the following is the relevant configuration:
```
(server：vps.com)
timeouts 1 5 30 60 180 1800 15 60 15 5
log 3proxy.log
auth iponly
allow * * *
tcppm -oRSSO_KEEPALIVE -R0.0.0.0:1234 3128 0.0.0.0 3128

sysctl -w net.ipv4.tcp_keepalive_time=30

(client)
timeouts 1 5 30 60 180 1800 15 60 15 5
users user:CL:pwd
auth strong
allow user
socks -orSSO_KEEPALIVE -rvps.com:1234
```
