### ISSUE TITLE
Запрет на резолв на стороне клиента

### ISSUE THREAD

**Issue by krok777** [z3APA3A/3proxy#636]
Поднял 3proxy, настроил черные списки доменов и все было хорошо, пока не нашел простой способ эти списки обойти: достаточно подменить DNS на стороне клиента на свои и вот уже на домены из черного списка можно заходить, работает блокировка только по IP доменов, так как резолв происходит уже не на стороне сервера.

Как можно настроить 3proxy, чтобы на socks5 нельзя было сделать такую подмену?

**Comment by ezbik** [comment]
тут пролетало интересное ACL, чтоб забанить обращения по IP. Сам не проверял.

`deny * * *0,*1,*2,*3,*4,*5,*6,*7,*8,*9`

https://github.com/z3APA3A/3proxy/issues/625#issuecomment-812561386

**Comment by z3APA3A** [comment]
можно попробовать
```
allow * * *.*
deny *
```
