### ISSUE TITLE
Проблема с deny punicode доменов

### ISSUE THREAD

**Issue by slonopot** [z3APA3A/3proxy#637]
Приветствую!

Возникла проблема с пуникод-доменами. Блокировка через deny не работает.

Конфиг на примере дом.рф:

```
users te:CL:st

log

auth strong

deny * * *.xn--d1aqf.xn--p1ai
deny * * xn--d1aqf.xn--p1ai
deny * * google.com
deny * * *.google.com
allow *

proxy -n -a -p1234 -i127.0.0.1
```

Лог:

```
210414190735.644 1234 00000 te 127.0.0.1:50440 195.238.250.20:443 788 23976 0 CONNECT xn--d1aqf.xn--p1ai:443 HTTP/1.0
210414190738.800 1234 00001 te 127.0.0.1:50445 0.0.0.0:0 0 0 0 CONNECT google.com:443 HTTP/1.0
```

Версия 0.9.3 стабильная. На 10-devel с 3proxy.ru сохраняется.

При попытке запросить дом.рф соединение устанавливается, с google.com закономерно блокируется.

Буду благодарен, если порекомендуете решение.

**Comment by z3APA3A** [comment]
Попробуй текущий мастер (с коммитом 681182b1e59142cc60d12c6112c057dc46414a17) - должно починиться
