### ISSUE TITLE
Короткое доменное имя

### ISSUE THREAD

**Issue by belovevgenii** [z3APA3A/3proxy#64]
0.8.6

nserver 192.168.0.9
log c:\3proxy\log.log
auth none
proxy

Ввожу http://apmx.ap.local/owa - работает
Ввожу http://apmx/owa - ошибка 502 Bad Gateway Host Not Found or connection failed

И с клиента, и с компа с 3proxy короткое имя разрешается. Как быть? Есть сайт, где в ссылках напихано http://shortdomainname/index.htm. Выдает ошибку 502. Вписываю адрес вместо shortdomainname - страница через прокси открывается. Пробовал вносить в конфиг
nsrecord shortdomainname IP-адрес - не помогает.

**Comment by z3APA3A** [comment]
При указании nserver 3proxy разрешает имена только через указанный DNS-сервер, а короткие имена разрешаются через NetBIOS или с дефолтным доменом. Для использования дефолтного механизма, не указывай nserver или добавь короткие имена через nsrecord.
