### ISSUE TITLE
Как заставить 3proxy использовать днс последнего прокси в цепочке?

### ISSUE THREAD

**Issue by kurevo1996** [z3APA3A/3proxy#65]
Создал конфиг с простой цепочкой 

```
# вешаемся на локалхост
internal 127.0.0.1

flush
auth iponly
allow * 127.0.0.1
parent 1000 socks5 127.0.0.1 9050
parent 1000 socks4 95.58.38.75 1080
proxy -n -p5050
socks -p5052
```

Чекаю используемые днс на whoer.net и вижу что стоят торовские днс. Как сделать чтобы юзался днс последней прокси в цепочке?

**Comment by z3APA3A** [comment]
https://3proxy.ru/faqr.asp#NAMES
используй fakeresolve и socks5+/socks4+ вместо socks5/socks4
