### ISSUE TITLE
Настройка TCP_NODELAY для Socks 5

### ISSUE THREAD

**Issue by mikh-abc** [z3APA3A/3proxy#66]
Здравствуйте, для игровых соединений часто требуется дополнительная настройка TCP соединения:
`int flag = 1;
setsockopt(sock, IPPROTO_TCP, TCP_QUICKACK, (void *)&flag, sizeof(int));        
setsockopt(sock, IPPROTO_TCP, TCP_NODELAY, (char *)&flag, sizeof(int));
`
возможно это добавить?

**Comment by z3APA3A** [comment]
c1beee44efbc7a672baad07bf2eabc9455472f5f
добавляет возможность задавать флаги для сокета в сторону клиента (-ocTCP_NODELAY) или в сторону сервера (-osTCP_NODELAY)
