### ISSUE TITLE
Проблема с IPv6 и Instagram

### ISSUE THREAD

**Issue by MaxWoland** [z3APA3A/3proxy#67]
Здравствуйте.
Сейчас поднимаю IPv6 прокси на своем сервере, в целом все работает с основными соц.сетями, но появился затык с instagram. При переходе в браузере по адресу instagram.com вываливается ошибка 502 Bad GatewayHost Not Found or connection failed, НО если ввести www.instagram.com то сайт нормально открывается. Как решить эту проблему?

**Comment by z3APA3A** [comment]
А что в конфиге и в логах?

**Comment by MaxWoland** [comment]
Запись в логе:
1462974970.524   11.05.2016 16:56:10   PROXY:10002 00100   - 195.20.194.75:42362 0.0.0.0:0   0 0 0 GET http://instagram.com/ HTTP/1.1

Конфиг:
daemon
pidfile /tmp/3proxy.pid
timeouts 1 5 30 60 180 1800 15 60
setgid 65534
setuid 65534
monitor /usr/local/etc/3proxy/3proxy.cfg

log /var/log/3proxy/3proxy.log D
#logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"
logformat "L%t.%.   %d.%m.%Y %H:%M:%S   %N:%p %E   %U %C:%c %R:%r   %O %I %h %T"
archiver gz /usr/bin/gzip %F
rotate 90

nserver 2001:4860:4860::8888
nserver 2001:4860:4860::8844
nserver 8.8.8.8
nserver 8.8.4.4
nscache 65536
nscache6 65535

auth iponly strong
flush

monitor /var/3proxy/auth
include /var/3proxy/auth


Файл /var/3proxy/auth:
allow * CLIENT_IP * *
users max1:CL:max1
allow max1
proxy -6 -n -a -p10000 -i<IPv4> -e2a07:14c0:0:770a:253a:0e71:3b61:b029
socks -6 -p30000 -i<IPv4> -e2a07:14c0:0:770a:253a:0e71:3b61:b029
flush
#max1#

#max2#
users max2:CL:max2
allow max2
proxy -6 -n -a -p10001 -i<IPv4> -e2a07:14c0:0:770a:cb64:1ef8:2576:400d
socks -6 -p30001 -i<IPv4> -e2a07:14c0:0:770a:cb64:1ef8:2576:400d
flush
#max2#

**Comment by z3APA3A** [comment]
У тебя прокси запущен с -6 (работать только с IPv6) а у instagram.com нет IPv6 адреса:

>host -tAAAA instagram.com
instagram.com has no AAAA record

если хочешь, чтобы при отсутствии IPv6 прокси ходил по IPv4 используй -64 вместо -6.

P.S. Возможно у instagram.com есть IPv6 адрес, но только при резолве через IPv6. Гугловые DNS не различают резолв по IPv6 и IPv4 при кэшировании, если надо - поднимай свои.

**Comment by MaxWoland** [comment]
У инстаграмма есть ipv6, только почему-то резолвится он только с www версии.
instagram.c10r.facebook.com	IN	AAAA	ipv6 = 2a03:2880:f01a:14:face:b00c::43fe

И параметр -64 не повлияет на анонимность прокси?

**Comment by z3APA3A** [comment]
нет, не повлияет.
