### ISSUE TITLE
3proxy stops working after I add ports more than 1020

### ISSUE THREAD

**Issue by trackmedown2021** [z3APA3A/3proxy#676]
auth iponly
allow *
parent 1000 http x.x.x.x user1 password
proxy -p30000 -a
flush
auth iponly
allow *
parent 1000 http x.x.x.x user2 password
proxy -p30001 -a
flush
auth iponly
allow *
parent 1000 http x.x.x.x user3 password
proxy -p30002 -a
flush
auth iponly
allow *
parent 1000 http x.x.x.x user4 password
proxy -p30003 -a
flush
auth iponly
allow *
parent 1000 http x.x.x.x user5 password
proxy -p30004 -a
flush
auth iponly
allow *
parent 1000 http x.x.x.x user6 password
proxy -p30005 -a
flush
.
.
.
.
auth iponly
allow *
parent 1000 http x.x.x.x user6 password
proxy -p31019 -a
flush
This is my cfg file configuration. It works perfect from -p30000 to -p31019
But if I add more paretns it won't work. Can anyone tell me what am I doing wrong here.
I want to run 1 Million such parents. How can I achieve that.
It would give me error code 5 at line where I start
auth iponly
allow *
parent 1000 http x.x.x.x user31020 password
proxy -p31020 -a
flush
Looking forward for the solution.
Thank You

**Comment by trackmedown2021** [comment]
![image](https://user-images.githubusercontent.com/87557456/132323986-94775981-0bb8-471f-b304-6ca6a983a2e5.png)
![image](https://user-images.githubusercontent.com/87557456/132323918-1a136a3e-1f1f-4302-b133-d682c656cb05.png)

Please check the screenshots.

**Comment by trackmedown2021** [comment]
![image](https://user-images.githubusercontent.com/87557456/132324400-c05a7498-967f-47d6-9dff-7d76823b50ef.png)
this one is more detailed

**Comment by z3APA3A** [comment]
Current 3proxy version can only return code 1, 3, 4 and 21 for parent, which 3proxy version do you use?

**Comment by trackmedown2021** [comment]
![image](https://user-images.githubusercontent.com/87557456/132438339-ecf9797c-d63b-4540-8f91-a56b59aab971.png)
By the way I also tried this for another normal proxy setup. I configured the 3proxy.cfg for IPv6 as outgoing addresses and It also works fine for ports upto 1000 and after I add more ports It doesn't work. I can share the configuration file with you as well if you want.

**Comment by trackmedown2021** [comment]
![image](https://user-images.githubusercontent.com/87557456/132438848-9aede752-9e02-4889-9fa8-2eac0085ecbf.png)
You can see I am using ports starting from 50000 and goes up to 50999 and they work just fine. and as soon as I add more more IPv6 addresses with different increasing ports it won't work.

**Comment by trackmedown2021** [comment]
actually my question is that do I have to configure this 3proxy differently If I have to use more outgoing addresses and ports?

**Comment by trackmedown2021** [comment]
![image](https://user-images.githubusercontent.com/87557456/132439475-071c4e22-ecda-4abb-a8e1-749fa68a3e58.png)
actually my question is that do I have to configure this 3proxy differently If I have to use more outgoing addresses and ports?

**Comment by trackmedown2021** [comment]
never mind. Thank you for your reply. it was the problem with my ulimits :-)
This Solved my problem so far going good.
echo "root soft nofile 10240" >> /etc/security/limits.conf
echo "root hard nofile 10240" >> /etc/security/limits.con

**Comment by z3APA3A** [comment]
You may be interested in reading this
https://3proxy.ru/highload.asp
In addition to file limits you should also consider available port ranges. Port ranges used for listening port should not overlap with ephemeral ports.

**Comment by trackmedown2021** [comment]
Hello,
Can you please tell me how do I block websites in 3proxy? I tried like
allow *.Google.*
Deny *
But doesn't work. I want to actually block websites those are in a file
/etc/3proxy/websites
Can you please help  me with this?
I am using 0.9 3proxy version

Safron Redbeard
