### ISSUE TITLE
ftppr became not functional somewhere between 0.6.1 and 0.8.5

### ISSUE THREAD

**Issue by drook** [z3APA3A/3proxy#68]
I'm using 3proxy as FTP proxy (squid doesn't support DELETE command).
Config:

````config
nserver 127.0.0.1
nscache 65536

timeouts 1 5 30 60 180 1800 15 60
daemon

log /var/log/3proxy/proxy.log D
logformat "- +_L%t.%.  %N.%p %E %U %C:%c %R:%r %O %I %h %T"

archiver gz /bin/gzip %F

rotate 10

external 0.0.0.0

internal 192.168.3.1

auth iponly
allow * 127.0.0.1,192.168.3.22,192.168.3.41 * *

ftppr -p2121

setgid 22922
setuid 22924
````

After upgrading from 0.6.1 to 0.8.5 ftppr stopped to work:

````ftppr-0.8.5
[root@taiga:local/etc]# ftp 192.168.3.1 2121      
Connected to 192.168.3.1.
220 Ready
Name (192.168.3.1:emz): ftp@ftp.freebsd.org
331 ok
Password: 
230-
230-This is ftp0.ydx.FreeBSD.org, graciously hosted by Yandex.
230-
230-FreeBSD files can be found in the /pub/FreeBSD directory.
230-
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
229 Entering Extended Passive Mode (|||49904|)
ftp: Can't connect to `192.168.3.1:49904': Connection refused
200 OK
550 err
ftp> ^D
221 Goodbye.
````

As simple as that. If the target host is inside LAN, ftppr for some reason allows to work with it, but during `ls` it cannot finish the output and connection hangs (then gets terminated after some timeout). I've spend about an hour trying to debug my configuration and networking problems - without any result. Luckily, I had a machine with old 0.6.1 version, so I decided to downgrade. After doiwngrading 0.8.5 to 0.6.1 ftppr suddenly restored it's functionality, without changing the config.

Same session on 0.6.1, with exactly same config:

````ftppr-0.6.1
[root@taiga:3proxy/3proxy]# service 3proxy restart    
Stopping threeproxy.
Waiting for PIDS: 65700.
Starting threeproxy.
[root@taiga:3proxy/3proxy]# ftp 192.168.3.1 2121      
Connected to 192.168.3.1.
220 Ready
Name (192.168.3.1:emz): ftp@ftp.freebsd.org
331 ok
Password: 
230-
230-This is ftp0.ydx.FreeBSD.org, graciously hosted by Yandex.
230-
230-FreeBSD files can be found in the /pub/FreeBSD directory.
230-
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
229 Entering Extended Passive Mode (|||62859|)
ftp: Can't connect to `192.168.3.1:62859': Connection refused
200 OK
125 data
-rw-r--r--    1 ftp      ftp          5430 Jul 19  2014 favicon.ico
-rw-r--r--    1 ftp      ftp           660 Nov 02  2015 index.html
drwxr-xr-x    3 ftp      ftp             3 Jul 19  2014 pub
226 Directory send OK.
ftp> ^D
221 Goodbye.
````

I am well-aware that since 0.8.x ipv6 support was added, and the host I was using 3proxy has the ipv6 connectivity indeed. And yes, may be it's just the ipv6 connectivity raises this error when it comes to data channel. But I've ruled that out - in the test below command-line ftp client works just fine with ftp.freebsd.org using the ipv6 (furthermore, this error with data channel is reproducible with ipv4-only FTP target servers):

````ftpclient
[root@taiga:/etc]# ftp 2a02:6b8:b010:1001::15:0
Connected to 2a02:6b8:b010:1001::15:0.
220 This is ftp0.ydx.freebsd.org - hosted at Yandex.
Name (2a02:6b8:b010:1001::15:0:emz): ftp
331 Please specify the password.
Password: 
230-
230-This is ftp0.ydx.FreeBSD.org, graciously hosted by Yandex.
230-
230-FreeBSD files can be found in the /pub/FreeBSD directory.
230-
230 Login successful.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
229 Entering Extended Passive Mode (|||58523|)
150 Here comes the directory listing.
-rw-r--r--    1 ftp      ftp          5430 Jul 19  2014 favicon.ico
-rw-r--r--    1 ftp      ftp           660 Nov 02  2015 index.html
drwxr-xr-x    3 ftp      ftp             3 Jul 19  2014 pub
226 Directory send OK.
ftp> ^D
221 Goodbye.
````

**Comment by z3APA3A** [comment]
> |ftp: Can't connect to `192.168.3.1:62859': Connection refused|

you have this error with both 0.6.1 and 0.8.5 versions according to
logs. Check you do not block access to non-privileged ports with firewall.

**Comment by drook** [comment]
Yup, but 0.8.x bails out after that, but 0.6.x continues to work. And no, I'm not blocking anything inside LAN. In the example balow I will use passive mode with same 192.168.3.1, which happens to run the FTP server itself:

````ftp-session
[root@taiga:local/etc]# ftp 192.168.3.1
Connected to 192.168.3.1.
220 taiga FTP server (Version 6.00LS) ready.
Name (192.168.3.1:emz):  
331 Password required for emz.
Password: 
230 User emz logged in.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
229 Entering Extended Passive Mode (|||60566|)
150 Opening ASCII mode data connection for '/bin/ls'.
total 115880
drwx------   3 emz      wheel           3 Dec  9  2013 .cache
drwx------   3 emz      wheel           3 Dec  9  2013 .config
drwxr-xr-x   5 emz      wheel           5 Jun 20  2014 .cpan
-rw-r--r--   1 emz      wheel         758 Jan 14  2012 .cshrc
-rw-------   1 emz      wheel          67 Jan 14  2012 .cvspass
-rw-r--r--   1 emz      wheel         433 May 23  2012 .dbshell
-rw-------   1 emz      wheel       26283 May  8 10:51 .histfile
-rw-------   1 emz      wheel        5346 May 16  2015 .history
226 Transfer complete.
ftp>
````

**Comment by z3APA3A** [comment]
Provide logs for failed session

**Comment by z3APA3A** [comment]
Latest versions use getsockname() to determine IP to use for data connection. I had same problem on Windows with Kaspersky antivirus, it was because KAV redirects all traffic to 127.0.0.1:someport and getsockname() for external connections returns 127.0.0.1 instead of local external address. I have no idea why it can happen on FreeBSD, it's really weird. I've added workaround to devel with 8cdf341d0e7f03a6c7b520962d935cdd75ab9c1d, can you try it?

**Comment by drook** [comment]
Yup, this patch does help. Will it make it to the next version ?

**Comment by z3APA3A** [comment]
yes
