### ISSUE TITLE
authcache not working

### ISSUE THREAD

**Issue by Teqnosys** [z3APA3A/3proxy#69]
I use the line: "authcache ip 900" to assume an IP address is the user that authenticated from it within the last 15 minutes. But this is no longer working, the last version it worked was 0.7.1.4.

**Comment by z3APA3A** [comment]
Can you provide full configuration and clarify what makes you think authcache doesn't work?

**Comment by Teqnosys** [comment]
For example:
users Administrator:CL:whatever
authcache ip 900
auth cache strong
proxy
socks

Using this conifguration with version 0.7.1.4 will ask for authentication once and assume the same using for the next 15 minutes.
Later versions will just ask for authentication on every request using the same configuration.

**Comment by z3APA3A** [comment]
Try devel version with this fix fbcdcf3d7b663efa659cb9ef3b34ea7e783e0314

**Comment by Teqnosys** [comment]
Thank you for the quick responses and the fix.
Unfortunately I am not a developer and I do not know how to compile it.
I am not in desperate need of this right now, I just wanted to inform you about it.

**Comment by z3APA3A** [comment]
For Windows, you can get latest devel from here 
http://3proxy.ru/current/3proxy-0.9-devel.zip
(Antivirus/browser can give a warning, because proxy is sometimes classified as a riskware)

**Comment by Teqnosys** [comment]
Okay, thanks!
