### ISSUE TITLE
The parent agent is working again

### ISSUE THREAD

**Issue by derrick5788** [z3APA3A/3proxy#696]
If I configure three parent agents and one of them fails, will 3proxy reconnect other parent agents

**Comment by z3APA3A** [comment]
3proxy makes a number of attempts configured by `parentretries` parameter. If there are multiple parents with random selection configured, random parent is selected on each attempts. It's OK for the case some parent may be temporary unreachable for relatively short period, but in the case your parent proxies are unstable you need some additional solution.
