### ISSUE TITLE
Проблема с UDP при наличии любых deny-правил

### ISSUE THREAD

**Issue by freeacetone** [z3APA3A/3proxy#697]
Использую 3proxy (SOCKS5) в локальной сети предприятия. Прямого выхода в интернет из локалки нет. У некоторых пользователей появилась острая нужда иметь шлюз по умолчанию, а не прокси, применяемый точечно к каждому приложению. Для решения задачи взял [Tun2Socks](https://github.com/xjasonlyu/tun2socks/) ([статья](https://habr.com/ru/post/584162/) на Хабре). Утилита создает у клиента виртуальный сетевой интерфейс и весь трафик с него заворачивает в прокси. В общем, профит полнейший.

На предприятии многие пользователи прокси-сервера имеют тонкие настройки с запретами определенных адресов и доменных имен. Как показали тесты, любое deny-правило в конфиге 3proxy вызывает проблему: Tun2Socks не может работать с UDP-трафиком. Проблему [описал](https://github.com/xjasonlyu/tun2socks/issues/74) в репозитории Tun2Socks. В ответ разработчик Tun2Socks рапортует, что проблема связана с нарушением хендешейка. Если deny-правил в конфиге 3proxy нет - все проблемы с UDP пропадают. TCP-трафик в свою очередь всегда отрабатывает корректно.

Перед открытием тикета протестировал: пробовал использовать прокси через нативные настройки приложений всяческой IP-телефонии. В целом UDP работает корректно. Но связка с Tun2Socks выдает неоднозначное поведение.

Есть ли объяснения с чем это связано, либо какие-то предположения?

**Comment by ezbik** [comment]
можно конфиг 3proxy?

**Comment by ezbik** [comment]
баг есть, проявляется когда есть хоть 1 deny на любой destination (в моем примере 127.100.100.100). Подчеркну, что я никогда не обращаюсь на этот адрес, но его наличие в ACL всё руинит.

```
log /var/log/3proxy/3proxy.log D
logformat "L%Y-%m-%d/%H:%M:%S.%. %N.%p %E %U %C:%c %R:%r %O %I %h %T"

auth strong
### doesn't affect tun2socks/UDP:
deny * 127.100.100.100
## ruins tun2socks/UDP:
#deny * * 127.100.100.100
allow *

socks -n -p23000
flush

users login0001:CL:5XoKgV
```

**Comment by acetoneRu** [comment]
Использование UDP over TCP конечно вариант, но на исключительно крайний случай.
Возможно, в скором времени ответит мэнтейнер и появится какая-то ясность с перспективой исправления бага.

**Comment by z3APA3A** [comment]
@acetoneRu попробуй текущий мастер (с патчем f9347c2f8bb9988de9a572d89526cb64a8e4f804) должно заработать

**Comment by acetoneRu** [comment]
С удовольствием. Момент...
