### ISSUE TITLE
Утечка ресурсов?

### ISSUE THREAD

**Issue by chromotion** [z3APA3A/3proxy#7]
Версия 3proxy: 0.8-devel-150608002425.
При попытке зайти по адресу 127.0.0.1:81/S (т.е. в админку, раздел Running Services) браузер начинает использовать 50-60% ЦП и стремительно поглощать ОЗУ, при этом сам прокси-сервер практически ничего не потребляет. Закрыв браузер процент ЦП перекидывается на 3proxy.exe.
В версии 0.7.1.2, с которой я перешёл на 0.8, этого замечено не было.
Содержание 3proxy.cfg:
monitor "C:\3proxy\bin\3proxy.cfg"
log
users admin:CL:
auth strong
allow admin
admin -i127.0.0.1 -p81

На скриншоте один 3proxy — основной (установлен как служба), другой — для тестов (просто запущен из папки).
![screenshot-1](https://cloud.githubusercontent.com/assets/14054246/9579335/80d77bc8-4ffa-11e5-89da-378838e9a921.jpg)

**Comment by z3APA3A** [comment]
Привет,
в 0.8 действительно есть баг в admin который приводит к вечному циклу и
подвисанию, закрывается этим коммитом:
https://github.com/z3APA3A/3proxy/commit/ef67ef4072512c715279162559a36d41b7cdb706
если можешь собрать из сорсов - можешь пофиксить.
Собранные бинарники я постараюсь выложить вечером.

chromotion пишет:

**Comment by z3APA3A** [comment]
Попробуй последний devel
http://3proxy.ru/download/
