### ISSUE TITLE
Проблема с хэшем пароля в конфиге

### ISSUE THREAD

**Issue by MaxWoland** [z3APA3A/3proxy#70]
Здравствуйте.
С помощью php и функции password_hash() генерирую хэш пароля, но после добавления его в конфиг 3pxoxy крэшится и выдает:
Failed to open E.qIkgRYvOrc7YPXp0gxDuPHMb1zuIZnXYeGy7W80U4Z05DoQdy0G
Unknown command: 'users' line 2
Command: 'include' failed with code 2, line 2

Запись выглядит таким образом:
users user1:CR:$2y$10$E.qIkgRYvOrc7YPXp0gxDuPHMb1zuIZnXYeGy7W80U4Z05DoQdy0G

Что можно сделать? Может слишком длинный хэш?

upd: Если взять запись в кавычки, то 3proxy запускается, но пароль не принимает в итоге

**Comment by shark136** [comment]
Попробуйте тут сгенерировать - http://hash.online-convert.com/ru/apache-htpasswd
какой-то у вас хеш получается явно не перевариваемый

**Comment by z3APA3A** [comment]
во-первых, необходимо использовать двойные кавычки:
во-вторых 3proxy поддерживает только MD5-хэши.
http://3proxy.ru/howtor.asp#USERS
