### ISSUE TITLE
cat 3proxy pid на единицу меньше реального pid

### ISSUE THREAD

**Issue by logan23** [z3APA3A/3proxy#71]
Добрый день. 0.8.6
cat 3proxy pid - 2332
pidof 3proxy - 2333
Pid из файла всегда на единицу меньше, чем реальный. Из-за этого /bin/kill `cat /usr/local/etc/3proxy/3proxy.pid` не работает.

**Comment by z3APA3A** [comment]
так это наверняка потому, что daemon в конфиге указан после pidfile. После daemon меняет идентификатор процесса.
