### ISSUE TITLE
Деление заголовка запроса

### ISSUE THREAD

**Issue by AlexeySa** [z3APA3A/3proxy#72]
Пожалуйста, добавьте возможность делить исходящий http-заголовок запроса на указанное количество байт. Нужно, чтобы заголовок уходил не одними пакетами, а несколькими.

**Comment by z3APA3A** [comment]
Слишком специфический функционал для основного кода. Можешь реализовать через фильтр
http://3proxy.ru/doc/devref.rtf 2.3.4
создать фильтр на filter_header_cli
