### ISSUE TITLE
Не хочет работать socks на IPv6

### ISSUE THREAD

**Issue by MaxWoland** [z3APA3A/3proxy#73]
Здравствуйте. 
Возникла проблема с socks протоколом, при этом http работает отлично.

Мой конфиг: 
daemon
setgid 99
setuid 99
pidfile /tmp/3proxy.pid
monitor /usr/local/etc/3proxy/3proxy.cfg

timeouts 1 5 30 60 180 1800 15 60
maxconn 20000

auth iponly strong
flush

users user1:CL:user1
allow user1
proxy -6 -n -a -p10000 -i185.118.65.241 -e4a07:ffc0:0:770a:253a:0e71:3b61:b029
socks -6 -p30000 -i185.118.65.241 -e4a07:ffc0:0:770a:253a:0e71:3b61:b029
flush

ProxyChecker при тесте socks порта выдает:
[02:26] Starting: Test 2: Connection through the Proxy Server
[02:26] Authentication was successful.

И все дальше замирает, в логах нет ничего.
http проходит нормально.

Подскажите пожалуйста в чем может быть проблема?

**Comment by z3APA3A** [comment]
Так в логах нет ничего, потому что нет логов. Добавь логгирование, посмотри что в логах.

**Comment by MaxWoland** [comment]
Да нет, я просто опустил эту запись здесь, логи ведутся, но там нет ошибок, единственное порой есть запись Address already is used. Может это оттого что на http и socks я вешаю один и тот же IPv6 адрес?

**Comment by z3APA3A** [comment]
Что значит "нет ошибок"? Что конкретно в логах по тому запросу который фейлится? Если совсем ничего - значит запрос не попадает в прокси-сервер, проверяй конфигурацию сервера, клиента, доступность портов.

**Comment by MaxWoland** [comment]
Сейчас еще раз проверю лог, пару минут

**Comment by MaxWoland** [comment]
1463570865.235   18.05.2016 07:27:45   SOC45:30083 00100   user1 195.20.194.68:15353 ::ffff:87.240.131.120:0   0 0 0 CONNECT user1 :0

**Comment by z3APA3A** [comment]
Так у тебя запрос идет к адресу IPv4 а прокси запущен с ключем -6, т.е. IPv6 only. Включи в socks клиенте разрешение имен через прокси, тогда прокси сам будет определять IP адрес и выбирать IPv6 как приоритетный.

**Comment by MaxWoland** [comment]
А как это сделать, подскажите пожалуйста

**Comment by z3APA3A** [comment]
посмотри настройки SOCKS на клиенте

**Comment by MaxWoland** [comment]
В смысле в самом софте, который к прокси подключается?

**Comment by z3APA3A** [comment]
да

**Comment by MaxWoland** [comment]
Да а где ж такое найти, ни в этом софте ни в браузере нет таких опций.

**Comment by z3APA3A** [comment]
Если ты хочешь разрешить клиентам подключаться к IPv4 адресам - исполmзуй опцию -64 а не -6, но имей ввиду что запрос пойдет через IPv4

**Comment by MaxWoland** [comment]
Мда, тогда получится что на внешку будет светится ipv4 адрес сервера один и тот же, а это никакая не анонимность получается
