### ISSUE TITLE
Проблмела с пробросом портов (tcppm)

### ISSUE THREAD

**Issue by morrozilla** [z3APA3A/3proxy#74]
Добрый день имеется следующая конфигурация 

```
internal 10.80.0.1
external 91.122.206.182 
nserver 77.88.8.8
nscache 65536
log
users proxy:CL:proxy
auth iponly strong
allow * $C:\3proxy\cfg\users.txt *
allow proxy
maxconn 8191
proxy -p8889
flush
auth iponly
allow *
tcppm -i 5551 91.122.222.33 22
tcppm -i 23391 10.80.0.13 3389 
maxconn 2047
socks -p54
ftppr 
```
Проброс портов из внешней сети во внутреннюю работает отлично 
**tcppm -i 23391 10.80.0.13 3389** 

Но вот наоборот не выходит, требуется при обращению к внешнему адресу 91.122.222.33 по порту 5551 порт менялся на 22 пробовал 
так
tcppm -i 5551 91.122.222.33 22
и так 
tcppm -i -e91.122.206.182 5551 91.122.222.33 22
по логам видно что проброс не делается.
160603090519.516 54 00013 - 10.80.0.28:24292 91.122.222.33:**5551** 0 0 0 CONNECT 91.122.201.32:**5551**

**Comment by z3APA3A** [comment]
Потому что для доступа в обратном направлении надо поменять местами internal и external (можно добавить -i и -e к tcppm)
http://3proxy.ru/faqr.asp#INTEXT

**Comment by morrozilla** [comment]
Пробовал самые разные варианты, ни один не помог.
Не могли бы вы на моем примере показать как верно будет прописать tcppm?
Спасибо

**Comment by z3APA3A** [comment]
tcppm -i10.80.0.1 -e91.122.206.182  5551 91.122.222.33 22
tcppm -i91.122.206.182 -e10.80.0.1  23391 10.80.0.13 3389

**Comment by morrozilla** [comment]
Пробовал так, сейчас для уверенности попробовал еще раз. логи такие же. порт не пробрасывается. :(

**Comment by z3APA3A** [comment]
Значит сейчас у тебя работает прокси не с этим конфигом. Ты прокси-то перезапустил после изменения конфига?

**Comment by morrozilla** [comment]
Само собой. Фигня какая то :(

**Comment by z3APA3A** [comment]
Посмотри в диспетчере задач, возможно у тебя работает более 1 экземпляра прокси.

**Comment by morrozilla** [comment]
А может ли быть проблема из за того, что у меня несколько сетевых интерфейсов?

P.s. nsrecord тоже не работает, это нормально ? :)

**Comment by z3APA3A** [comment]
Может, в -e надо ставить тот интерфейс, через которое должно пойти соединение. Можешь поставить в -i и в -e 0.0.0.0 - это должно работать всегда

**Comment by z3APA3A** [comment]
> P.s. nsrecord тоже не работает, это нормально ? :)
что значит "не работает", что в конфиге, что в логе?

**Comment by morrozilla** [comment]
по nsrecord пробовал так
```
internal 10.80.0.1
external 91.122.206.182 
nserver 77.88.8.8
nscache 65536
nsrecord mysite123.ru 10.80.171.194
log
users proxy:CL:proxy
auth iponly strong
allow * $C:\3proxy\cfg\users.txt *
allow proxy
maxconn 8191
proxy -p8889
flush
auth iponly
allow *
tcppm -i 5551 91.122.222.33 22
tcppm -i 23391 10.80.0.13 3389 
maxconn 2047
socks -p54
ftppr 
```
после чего набираю в браузере mysite123.ru и вместо того что бы открылся  локальный сайт 10.80.171.194 показывает 
502 Bad Gateway Host Not Found or connection failed
в логах про nsrecord ни слова
160603123037.391 8889 00100 - 10.80.0.28:27237 0.0.0.0:0 0 0 0 GET http://mysite123.ru/ HTTP/1.1

P.S. Не может ли все это быть из за того что использую версию 3proxy-0.8.6-lite.zip  (OS win2000)

--
По tcppm пробовал все по нулям та же песня...

**Comment by z3APA3A** [comment]
Это означает что у тебя все так же работает прокси с другой конфигурацией.
