### ISSUE TITLE
Привет. Я нуб, но хочу знать, смогу ли использовать как внешний прокси 3Proxy?

### ISSUE THREAD

**Issue by twistms** [z3APA3A/3proxy#75]
Мне нужно через мой комп вести подключения с кафедры университета, там перекрыли TeamViever, а много студентов хотят им пользоваться. В сети есть много различных спиской прокси IP, но я хочу, чтобы было через мой комп и не для всех конечно, смогу ли я это устроить?

**Comment by z3APA3A** [comment]
Использовать 3proxy как прокси для проброса внешних подключений можно. Можно ли использовать твой компьютер - не знаю, это зависит от способ подключения, наличия фаервола и протокола, который необходимо проксировать.

**Comment by twistms** [comment]
Действовать по инструкции, просто должен быть доступ на мой ip извне?

**Comment by z3APA3A** [comment]
Да.

**Comment by twistms** [comment]
спасибо
