### ISSUE TITLE
Log & HTTPS. 

### ISSUE THREAD

**Issue by rty65tt** [z3APA3A/3proxy#76]
В логах нет информации по https запросам. Например заходим на https://yandex.ru/, а в логах ничего не происходит. Так и должно быть?

**Comment by z3APA3A** [comment]
Проверь в настройках браузера, что указан прокси для https. https-запросы должны быть в логах с методом CONNECT.

**Comment by rty65tt** [comment]
В настройках https указал. Использую Windows 10 x64. То что браузер работает через прокси это совершенно точно, но заходишь например на  https://yandex.ru/ а в логах только "160605071122.049 3128 00000 - 192.168.1.201:62657 77.88.21.179:443 2309 4812 0 CONNECT push.yandex.ru:443 HTTP/1.1" и то не всегда.
открываешь "https://yastatic.net/morda-logo/i/bender/logo.svg" в логах ничего.
Я изначально хотел использовать прокси ради логов, чтоб за броузером следить.

**Comment by z3APA3A** [comment]
Запись в логе будет в момент закрытия соединения.
Так а что вы надеетесь, по https увидеть в прокси логи запросов? Там шифрованный трафик идет, в логах будет только имя хоста. Чтобы увидеть шифрованный трафик нужно использовать подмену сертификата
http://3proxy.ru/plugins/SSLPlugin/
и я бы не рекомендовал делать это в production

**Comment by rty65tt** [comment]
Ясно. Работу протокола HTTPS знаю плохо (от слова совсем). Думал url запросов как-то можно смотреть. Значит так и должно быть. Спасибо.
