### ISSUE TITLE
ftppr mysteriously fails with ftp.acnielsen.ru wje

### ISSUE THREAD

**Issue by drook** [z3APA3A/3proxy#78]

**Comment by z3APA3A** [comment]
This server doesn't allow anonymous connections. Can you provide more details?

**Comment by drook** [comment]
Yeah :( I accidentally hit "Enter" when creating this issue and you were kind and fast enough to answer it while I was still filling it for the first time, sorry for that.

Why "mysteriously":
- it does resolve
- it works fine when console ftp is used as a client
- it doesn't originate any packet exchange when monitoring it with tcpdump
- yet it fails:

````log
# ftp -P 2121 192.168.3.1
Connected to 192.168.3.1.
220 Ready
Name (192.168.3.1:emz): XXXXXX@ftp.acnielsen.ru <---- you can try just any username
421 Service not available, remote server has closed connection.
ftp: Login failed
ftp> 
ftp> ^D
````

-it doesn't even asks for a password.

Logs: 

````log
1465299673.627  FTPPR.2121 00100 - 192.168.3.22:22430 0.0.0.0:0 0 0 0
````

When working with it via it's IP everything is fine.
If I would read this story on a serverfault or any other community board, I'd say "man, it surely looks like it doesn't resolve, stop slacking and recheck". But it definitely does. I'm providing it's non-obfuscated name here for reproduction purposes, the password (which it requires) isn't needed.

**Comment by drook** [comment]
Yeah, follow-up with versions:

````versions
# ftppr -v
ftppr of 3proxy-0.6.1 (091211143921)
# uname -a
FreeBSD taiga 10.3-PRERELEASE FreeBSD 10.3-PRERELEASE #0 r294545: Fri Jan 22 15:19:34 YEKT 2016     emz@taiga:/usr/obj/usr/src/sys/TAIGA  amd64
# clang -v
FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
Target: x86_64-unknown-freebsd10.3
Thread model: posix
Selected GCC installation:
````

**Comment by drook** [comment]
If for some reason you need the real username (obviously, I cannot give you the password) - it's 'vivat_norman'.

**Comment by z3APA3A** [comment]
It looks like acnielsen.ru has or had some problems with name resolution and name lookup sometimes fails. I had same problem, but after successful attempt to resolve name it was cached by resolver and now all connections are performed successfully. Check if problem persists, if yes - try to resolve ftp.acnielsen.ru with the same resolver configured for 3proxy.
