### ISSUE TITLE
режет длинные URL и ограничение на число соединений

### ISSUE THREAD

**Issue by mskfire** [z3APA3A/3proxy#79]
давно используем 3proxy, но напрягает две проблемы.

1. режутся длинные URL . например , в яндексе если задать длинный запрос, то при попытке перехода по ссылке в выдаче, яндекс делает редирект через свой сайт, причем передает себе в параметрах URL кучу параметров (текст запроса, параметры компа, ссылка для перехода и т.п.). этот длинный URL режется , и в итоге яндексовский сервер не понимает куда ему редиректить, и выдает ошибку 400. что делать?

2. возможно проблема не в 3proxy, но может тогда подскажете решение. у нас в локалке порядка 20 компов, 3proxy стоит на ПК с WinXP. и очень часто происходит отлуп при загрузке страницы или файлов ("Соединение было сброшено") - не обрыв, а именно не загружается файл самой страницы, css, js или картинки отдельные. приходится обновлять, и бывает что по нескольку раз. подозреваем, что это из-за того что прокси поддерживает ограниченное число соединений, и если в локалке много юзеров серфят одновременно, кто-то получает отлуп.
что можно предпринять, чтобы устранить эту проблему?

PS извините если не так оформил тему, я впервые на гитхаб

**Comment by shark136** [comment]
по п.2 в WinXP есть ограничение на количество полуоткрытых TCP сессий, скорее всего из за этого проблемы, поможет вам с этим - Half-open limit fix

**Comment by z3APA3A** [comment]
Какая версия 3proxy, какой maxconn в конфиге, что в логах?
