### ISSUE TITLE
Как настроить  external.rotation: same-same и perl authentication

### ISSUE THREAD

**Issue by hqot** [z3APA3A/3proxy#80]
Здравствуйте 

1 Можно ли конфигурировать прокси рак чтобы вход и выход был один и тот же итерфейс и добавить множество интерфейсов?

2 Можно ли настроить так чтобы доступ пользователей происходило через perl скрипт

**Comment by z3APA3A** [comment]
1. Можно
2. Если имеется ввиду аутентификация, то можно через кастомный плагин.

**Comment by hqot** [comment]
Спасибо за ответ 

Я приведу пример из squid а 
Можете ли предоставить маленкий пример 

1 
Я не смог найти пример конфигурации части входа и выхода интерфейсов 
В SQUID е это делаеться так 
acl ip1 myip 146.120.240.1
tcp_outgoing_address 146.120.240.1 ip1

2
Какие  кастомный плагин есть 
В SQUID е мы этово добились так 

auth_param basic program /usr/bin/perl /etc/squid/perl_auth.pl
auth_param basic realm Private port. Please go away and have a nice day.
auth_param basic credentialsttl 12 hours
auth_param basic children 5 startup=2 idle=3
auth_param basic key_extras '%la %lp %>a %>ru'

external_acl_type  ip_user_helper ttl=1024 children-max=10 children-startup=4 children-idle=6 %SRC %DST %METHOD %MYADDR %MYPORT /usr/bin/perl /etc/squid/perl_ip_auth.pl

**Comment by hqot** [comment]
acl CONNECT method CONNECT
acl http_port1 myport 4040
acl http_port2 myport 4045
acl password proxy_auth REQUIRED
acl ip_access external ip_user_helper
