### ISSUE TITLE
3proxy падает после первого коннекта к прокси

### ISSUE THREAD

**Issue by ramazk** [z3APA3A/3proxy#81]
Debian 8, в dmesg следующее:
[  402.419677] 3proxy[4758]: segfault at 7f473e51fff0 ip 00007f477ccb868c sp 00007f473e51fff0 error 6 in libc-2.19.so[7f477cbb4000+1a2000]
[  513.637460] 3proxy[5783]: segfault at 7f1312857ff0 ip 00007f1350fd168c sp 00007f1312857ff0 error 6 in libc-2.19.so[7f1350ecd000+1a2000]
[  607.027307] 3proxy[5815]: segfault at 7f799bff8ff0 ip 00007f799b7dc68c sp 00007f799bff8ff0 error 6 in libc-2.19.so[7f799b6d8000+1a2000]
[  709.002203] 3proxy[5840]: segfault at 7f2c1e871ff0 ip 00007f2c1e01568c sp 00007f2c1e871ff0 error 6 in libc-2.19.so[7f2c1df11000+1a2000]

**Comment by z3APA3A** [comment]
http://3proxy.ru/faqr.asp#CRASH - stacksize пробовал увеличивать?

**Comment by ramazk** [comment]
Поставил stacksize 65536 и проблема испарилась. Благодарю!
Есть ли какие-то негативные последствия у этого решения или на работе прокси это никак не отразится?

**Comment by z3APA3A** [comment]
негативные последствия - большее потребление памяти на указанный объем на каждое параллельное клиентское подключение.

**Comment by ramazk** [comment]
Да, первые же тесты показали, что прокси так работают крайне не стабильно, часто падая в bad gateway. Может Вы посоветуете какое значение попробовать поставить stacksize для 4gb озу и 1000 одновременно поднятых проксей?

**Comment by z3APA3A** [comment]
Так а что в логах-то при этом? И зачем поднимать 1000 проксей?
