### ISSUE TITLE
Many connections can't be built and error:00094 displayed in log

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#83]
Hi,
     Sometimes,the connections can't be built and error:00094 displayed in log.I tested with client computer and 3proxy server in the same local LAN.So it's not the net problem.

About 40% connections are built successfully(error:00000),60% failed(error:00094).

     How to fix it?

2016Jun17 104636 +0800,USERNAME SOCK5:61336 error:00000 192.168.137.224:58964 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:58904 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:58905 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:58913 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:58914 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00421 192.168.137.224:59002 use 0.0.0.0 connect to TARGETIP:PORT
2016Jun17 104645 +0800,USERNAME SOCK5:61336 error:00000 192.168.137.224:59003 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104656 +0800,- SOCKS:61336 error:00401 192.168.137.224:59065 use 0.0.0.0 connect to 192.168.137.21:0 requested 0.0.0.0:0 hostname:[0.0.0.0]
2016Jun17 104656 +0800,USERNAME SOCK5:61336 error:00000 192.168.137.224:59064 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104656 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59001 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104656 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59000 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104657 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59009 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59068 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59067 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59066 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,USERNAME SOCK5:61336 error:00000 192.168.137.224:59124 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59126 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104707 +0800,- SOCKS:61336 error:00401 192.168.137.224:59127 use 0.0.0.0 connect to 192.168.137.21:0 requested 0.0.0.0:0 hostname:[0.0.0.0]
2016Jun17 104709 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59079 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104718 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59125 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104718 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59128 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104718 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59142 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104720 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59134 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104729 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59143 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104729 +0800,USERNAME SOCK5:61336 error:00000 192.168.137.224:59214 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104729 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59140 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104729 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59141 use 192.168.137.21 connect to TARGETIP:PORT
2016Jun17 104731 +0800,USERNAME SOCK5:61336 error:00094 192.168.137.224:59144 use 192.168.137.21 connect to TARGETIP:PORT

Kindly regards
Raintears

**Comment by z3APA3A** [comment]
in most cases 94 error means client incorrectlty closes connection before it's processed. It may happen if client application exists without closing connections, or tab is closed in browser while content is still loading, or chromium-based browser pre-create connections to speed-up requests and close these connections on inactivity without sending any data. Do you see any errors in client applications matching 94 errors in logs?

**Comment by raintears2** [comment]
Hi,
     Thank you very much for replying.
    There is not any log output in the client application(it doesn't provide).
     The client application opened 10 connections, 4 connections are successful. 6 connections failed and displayed "connecting",it will retry many times,but always failed.At the same time,3proxy log display  error:00094

    Is there any client application can display detail errors?

Kindly regards

Raintears

**Comment by z3APA3A** [comment]
You should check your client application and network connectivity, because it means you client application thinks it can not establish connection to proxy and can not start data transfer, while proxy successfully accepted connection. Also, check if you have maxconn enougth, overwise connections may wait for acceptance in queue.
