### ISSUE TITLE
internal and external with both IPv4 and IPv6

### ISSUE THREAD

**Issue by romaincointepas** [z3APA3A/3proxy#84]
For socks (or others), how do you specify incoming/outgoing interface name in order to use IPv4 and IPv6?

Something like `internal eth0` or `socks -ieth0' returns an error. The documentation says `sets ip address of internal interface.`.

My goal is to be able to listen and exit on both IPv4 and IPv6 (`internal 0.0.0.0` seems to force ipv4) when eth0 has both IPv4 and IPv6 addresses setup.

Thanks!

**Comment by z3APA3A** [comment]
You have to start 2 separate services with 2 internal addresses, External address can be specified both IPv4 and IPv6. E.g.

proxy -iIP4 -eIP4 -eIP6
proxy -iIP6 -eIP4 -eIP6

Alternatively, you can use ::0 address to accept both IPv4 and IPv6 and omit external to use system-selected address for all interfaces

proxy -i::0

but it may be platform dependent

**Comment by romaincointepas** [comment]
Got it, thanks!
