### ISSUE TITLE
[socks] UDP issues

### ISSUE THREAD

**Issue by romaincointepas** [z3APA3A/3proxy#85]
I am trying to setup a basic SOCKS5 for torrenting (with qbittorrent).

I'm running the most basic `socks` (as standalone without 3proxy, but I have the same problem using 3proxy config file).

TCP connections works great, however I can't seem to get anything back from all UDP trackers.
*(list of best UDP trackers for testing: https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_udp.txt).*

Using `dante-server` (basic setup), I can connect to UDP trackers.

Note:
- I have no firewall on the VPS I'm testing on, so all ports/protocol are open.
- I'm using the `devel` branch of 3proxy because of https://github.com/z3APA3A/3proxy/issues/60

I've sent the proxy IP to 3proxy@3proxy.ru if that can make debugging easier (I didn't feel like posting it publicly).

Thanks!

**Comment by z3APA3A** [comment]
for udpassoc to work, internal and external configuration options are required.

**Comment by romaincointepas** [comment]
Ok, after more testing, here is what I'm coming up with:

dante-server on the same VPS (and multiple SOCKS5 proxies from famous VPNs):
- udp trackers are working
- able to download from peers with µTP protocol, which is UDP-based (https://en.wikipedia.org/wiki/Micro_Transport_Protocol)

standalone socks (3proxy), without and without internal and external set as public IP of the host:
- same udp trackers are NOT working
- apparently still able to download from peers with µTP protocol *(qBittorrent supports SOCKS5 pretty well (and µTP peers seems to be going through `socks`). However I'm not 100% it's going through the SOCKS5 proxy.)*

Is there an easy way to fully test a SOCKS5 proxy? (tcp, udp and co)

**Comment by z3APA3A** [comment]
show you 3proxy.conf

**Comment by romaincointepas** [comment]
I am running `socks` as standalone.

I've encountered another problem when using port 1080, even TCP is not working. My bet is the UDP fail and this is connected. (TCP only was working when I was using port 80).

A simple dante-server or squid works (even on port 1080, just tried).

I've spawned a new Digital Ocean $5 VPS to start from scratch (Ubuntu 14.04.4 x64).

*Note: I did not do anything more than what's below after first boot.*

```shell
apt-get update
apt-get install -y git gcc make

cd /usr/src
git clone https://github.com/z3APA3A/3proxy.git
cd 3proxy
git checkout devel

make -f Makefile.Linux
```

And then:

```shell
/usr/src/3proxy/src/socks -p1080 -i198.211.126.103 -e198.211.126.103 -d
```

Testing it's listening:

```shell
$ netstat -tulnp | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      918/sshd
tcp        0      0 198.211.126.103:1080    0.0.0.0:*               LISTEN      6818/socks
tcp6       0      0 :::22                   :::*                    LISTEN      918/sshd
```

iptables looks okay:

```shell
$ iptables -S
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
```

The thing is, it doesn't work, can't reach the proxy, can't even open a tcp connection to that ip:port.
Again, same setup with squid or dante-server works out of the box.

Here is the IP:PORT to test: `198.211.126.103:1080` (I will let it run for a while).

Tell me if you want me to try anything in particular, I will oblige.

Sorry for the long post, I've spent 2 days on this and I'm lost and stuck :/

**Comment by z3APA3A** [comment]
enable logging and check logfiles. If you start socks without authentication, on 1080 there is a huge chance you get a lot of connections from spammers and run out of maxconn or ulimits.

**Comment by romaincointepas** [comment]
Ok, when putting aside the *any port other than 80 doesn't work* problem and using `-p80`, I'm getting this in the logs:

```
160622182044.555 80 00000 - 198.211.126.103:80 198.211.126.103:0 0 0 0 Accepting connections [7171/2691651392]
160622182117.401 80 00000 - 209.58.130.174:37756 0.0.0.0:8999 0 0 0 BIND 0.0.0.0:8999
160622182118.407 80 00000 - 209.58.130.174:37757 0.0.0.0:0 0 0 0 UDPMAP 0.0.0.0:0
160622182129.949 80 00000 - 209.58.130.174:38005 1.0.216.128:22320 68 0 0 CONNECT 1.0.216.128:22320
160622182129.972 80 00000 - 209.58.130.174:38023 2.2.78.74:59904 68 0 0 CONNECT 2.2.78.74:59904
```

I have a few `UDPMAP` and `BIND`, and all of them have 0.0.0.0 for the last and second to last IPs. Is that normal?

**Comment by z3APA3A** [comment]
And what do you have in logs with e.g. -p8080?

**Comment by romaincointepas** [comment]
Same thing (0.0.0.0 only for BIND and UDPMAP). I also have one entry for UNKNOWN:

```
160622183353.483 8080 00401 - 209.58.130.174:50791 198.211.126.103:0 0 0 0 UNKNOWN 0.0.0.0:0
```

**Comment by z3APA3A** [comment]
You just told 
>  any port other than 80 doesn't work 
have you resolved this issue?

**Comment by romaincointepas** [comment]
Port 8080 and port 80 are the only ones that seems to work on Digital Ocean, really weird. Especially when squid and dante-server works with the same simple setup with any ports (including 1080). And it's not because of scammers (tried many ports), I have no network activity and I can't even `nc` to it.

By the way, the `UNKNOWN` line in the log was my `nc -v ip:port` test, nothing to worry about.

Just tried on another server (a dedicated, same ubuntu version) and it works on other ports but:
- in the logs, I see a lot of `CONNECT`, very few `UDPMAP`
- all `UDPMAP` lines have 0.0.0.0 as last IP (other IPs look fine), looks like below:
```
160622184529.812 1090 00100 - 209.58.130.174:54030 68.116.5.134:6900 12729 13988 0 UDPMAP 0.0.0.0:0
```
- connections to UDP trackers still doesn't work.

**Comment by z3APA3A** [comment]
Probably, your BIND and UDPASSOC problems are caused with the same reason. For these requests 3proxy requires additional unprivileged ports.

**Comment by romaincointepas** [comment]
But why UDP works out-of-the-box with `dante-server` then? Is it doing something automatically that I should be doing manually with `3proxy`?

What would be the correct way to have `socks` (as standalone or using `3proxy`) running with UDP working on a clean ubuntu install?

**Comment by romaincointepas** [comment]
Also, I compared iptables -S with dante-server with UDP working and they are identical (see above, all incoming/outgoing open). There is no other firewall running (clean ubuntu install). Could you point me in the right direction? Did you ever have 3proxy socks with UDP working?

**Comment by z3APA3A** [comment]
With clean default ubuntu install there is definitely no problem like that. You better contact hoster's support or Ubuntu community. The problem may be in e.g. AppArmor profile.

**Comment by romaincointepas** [comment]
Ok thanks.

Regarding the torrent udp tracker not working, I've tried nearly all available SOCKS5 proxies out there (delegate, ss5, 3proxy, dante) and only dante works.

I've also found this: https://sourceforge.net/p/ss5/feature-requests/18/. Does this ring any bell?

**Comment by z3APA3A** [comment]
3proxy support UDPASSOC in accordance to SOCKSv5 RFC. If client requires something non-RFC compatible - yes, it probably will not work.

**Comment by romaincointepas** [comment]
What do you think about the *Edit 1* from my previous comment? Is that something hard to implement? Would it make sense to support this in 3proxy/socks (as dante-server already seems to support it)?

**Comment by z3APA3A** [comment]
It's unrelated to SOCKSv5.

**Comment by romaincointepas** [comment]
While it's not in the latest RFC, it's still related to SOCKSv5.

Also, I was just trying to figure out the cause of the problem, can you confirm that this is probably it?

**Comment by z3APA3A** [comment]
Nope, the comment you're citing doesn't relate to SOCKSv5, it relates to torrent tracker functionality.

**Comment by witaly-iwanow** [comment]
Well, I'm experiencing exactly the same issue. UDP ASSOCIATE succeeds, I get UDP port number in 50-60k range back, but no one is listening on that port. What's more `socks` doesn't even open a single UDP socket according to `lsof`. Exactly the same behavior on both macOS Big Sur and Ubuntu 20.10. Output looks this:
```
bin/socks -i127.0.0.1 -l
210325070859.951 1080 00000 - 127.0.0.1:0 0.0.0.0:0 0 0 0 Accepting connections [59622/251346432]
210325070904.999 1080 00466 - 127.0.0.1:63325 178.128.x.x:4320 0 0 0 UDPMAP 178.128.x.x:4320
```
adding `-e192.168.1.145` (that's what `ifconfig en0` spits out) doesn't change anything at all
