### ISSUE TITLE
socks5 = connection refused - http = http error 502, port = not open

### ISSUE THREAD

**Issue by Owyn** [z3APA3A/3proxy#86]
I use 3proxy to share internet with my notebook (windows sharing doesn't work),

web browser seem to work fine, but when I tried to setup uTorrent for proxy - it just doesn't want to work, neither with http proxy nor with socks5 one
socks5 says connection refused for http trackers
http proxy says http error 502 for http trackers
and udp trackers simply don't work (I don't really care about those)

log:
    192.168.137.2 - - [27/Jun/2016:15:50:31 +0300] "CONNECT pubt.net:2710" 00013 0 0 SOCK5/141.8.225.63:2710

and it's also full of these ones:
    192.168.137.2 - - [27/Jun/2016:15:49:59 +0300] "UDPMAP 0.0.0.0:0" 00421 0 0 SOCK5/0.0.0.0:0
    192.168.137.2 - - [27/Jun/2016:16:24:23 +0300] "" 00508 0 0 PROXY/MyExtIP:0

and also port doesn't seem to be open, internal uTorrent test says: "result port 6112 not open" - so DHT doesn't connect either

config:
auth none
internal 192.168.137.1
external MyExtIP
nscache 65536
log 
logformat "L%C - %U [%d/%o/%Y:%H:%M:%S %z] ""%T"" %E %I %O %N/%R:%r"
proxy
socks -p3129
tcppm -i192.168.137.1 6112 MyExtIP 6112
udppm -i192.168.137.1 6112 MyExtIP 6112

*replaced my real external ip with "MyExtIP"

**Comment by z3APA3A** [comment]
Neither proxy nor socks allow to accept external connection to predefined port. You need reverse tcppm to make port available from outside. 
With SOCKSv5 BIND proxy may be used to accept connections to random port. For bind to work, both -i and -e must be specified for socks. Consult your torrent client manual to check if SOCKSv5 BIND is supported.

**Comment by Owyn** [comment]
but If I specify -i and -e globablly do I have to specify those for socks especially?

I have:

internal 192.168.137.1
external MyExtIP
socks -p3129

**Comment by z3APA3A** [comment]
No, you haven't, but you still can't use predefined port, because SOCKSv5 bind always opens random port. To pass fixed external port use reverse tcppm (that is with swapped internal and external) instead. E.g.
tcppm -iMyExtIP -e192.168.137.1 6112 host_with_torrent_ip 6112
