### ISSUE TITLE
 ipv4 to ipv6

### ISSUE THREAD

**Issue by xdriver666** [z3APA3A/3proxy#87]
Необходимо настроить маршрутизацию таким путем, чтобы при обращении на один внешний ipv4 по разным портам на выходе в интернет имел только ipv6:
111.111.11,11:1001 --> ipv6-1
111.111.11,11:1002 --> ipv6-2
То есть все хосты в инете видели только IPV6 адрес

**Comment by z3APA3A** [comment]
proxy -i111.111.11.11 -p1001 -a -6 -eipv6-1
proxy -i111.111.11.11 -p1002 -a -6 -eipv6-2

**Comment by xdriver666** [comment]
Огромное Вам спасибо, заработало!
