### ISSUE TITLE
Detection as a proxy / Определение как прокси

### ISSUE THREAD

**Issue by notlookingfor** [z3APA3A/3proxy#88]
Добрый день!
При попытке использования как Socks прокси определяется использование прокси:
http://clip2net.com/clip/m0/3d71c-clip-18kb.png
http://clip2net.com/clip/m0/a533d-clip-23kb.png

P.s. установка была:
wget https://github.com/z3APA3A/3proxy/archive/3proxy-0.8.6.tar.gz
tar -xvzf 
cd 3proxy-3proxy-0.8.6

nano src/proxy.h найти и заменить строку на *find and replace to*: #define ANONYMOUS 1

make -f Makefile.Linux
mkdir /usr/local/etc/3proxy; mkdir /usr/local/etc/3proxy/bin; mkdir /usr/local/etc/3proxy/logs; mkdir /usr/local/etc/3proxy/stat
cp src/3proxy /usr/local/etc/3proxy/bin
cp ./scripts/rc.d/proxy.sh /etc/init.d/3proxy
chown -R nobody:nogroup /usr/local/etc/3proxy
cd /usr/local/etc/3proxy
nano /usr/local/etc/3proxy/3proxy.cfg
После настройки конфига:
/usr/local/etc/3proxy/bin/3proxy /usr/local/etc/3proxy/3proxy.cfg

config:
********************************************
nserver 8.8.8.8
nscache 65536

daemon

auth iponly
allow * x.x.x.x * *
socks -n -a -p24519 -ix.x.x.x -ex.x.x.x
flush

maxconn 1000
timeouts 10 15 30 60 180 1800 15 60
********************************************

Подскажите, пожалуйста, где искать корень проблемы? :) Где-то в исходниках 0 на 1 нужно что-то поменять?

**Comment by z3APA3A** [comment]
Так вам там написали. У вас WebRTC ходит напрямую, не через прокси. Ддобейтесь чтобы мимо прокси никакой трафик не шел.
