### ISSUE TITLE
error:00009 when use parent extip,only 1 ip working

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#89]
Hi,
     I am using 3proxy-0.9-devel (160518000524),I have 6 ips in server.

I want to connect main ip:port via socks5 and select randomly in the rest 5 additional ips for external interface.

So I use parent extip.But only the last one ip (ip5) working
Below is config and debug log

3proxy.cfg

allow $/etc/users

parent 200 extip $/root/ip1 0
parent 200 extip $/root/ip2 0
parent 200 extip $/root/ip3 0
parent 200 extip $/root/ip4 0
parent 200 extip $/root/ip5 0

socks -a -p12345

3proxy log:

2016Aug16 142105 +0800,username SOCK5:12345 error:00009 clientip:10113 use ip1 connect to targetip:80 requested targetip:80 hostname:targetip S:0,R:0 hops:1 text:CONNECT targetip:80

2016Aug16 142108 +0800,username SOCK5:12345 error:00000 clientip:10114 use ip5 connect to targetip:80 requested targetip:80 hostname:targetip S:163,R:225 hops:1 text:CONNECT targetip:80

2016Aug16 142109 +0800,username SOCK5:12345 error:00009 clientip:10115 use ip3 connect to targetip:80 requested targetip:80 hostname:targetip S:0,R:0 hops:1 text:CONNECT targetip:80

Kindly regards

Rain

**Comment by z3APA3A** [comment]
Check include files are available for proxy, there is not e.g. extra characters. 
Check IPs used are binded to external interface by e.g.
ping -lIP2 IP2
you can only use IP as external if this ping succeeds.

**Comment by raintears2** [comment]
The include files are available.All ips are binded and ping succeeds.

I also run config with the value not include files,it still has 00009 error,only the last ip 5.5.5.5 working.

allow username
parent 200 extip 1.1.1.1 0
parent 200 extip 2.2.2.2 0
parent 200 extip 3.3.3.3 0
parent 200 extip 4.4.4.4 0
parent 200 extip 5.5.5.5 0
socks -a -p12345

**Comment by z3APA3A** [comment]
Try with this commit: 4e4f71712db29955c626b0dc544b80f96bc9b455

**Comment by raintears2** [comment]
I have complied with the new commit.It works now.Bug fixed.
