### ISSUE TITLE
3proxy suddenly down,the log has error: *** glibc detected *** /usr/bin/3proxy: printf(): Bad file descriptor

### ISSUE THREAD

**Issue by raintears2** [z3APA3A/3proxy#90]
CentOS release 6.8 (Final)
Linux 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
3proxy tiny proxy server 3proxy-0.9-devel (160518000524)

3proxy suddenly down,the log has error:

*** glibc detected *** /usr/bin/3proxy: printf(): Bad file descriptor
corrupted double-linked list: 0x000000000079ef10 ***
2016Aug17 162535 +0800,username SOCK5:12345 error:00000 clientip:45138 use 192.168.1.69 connect to targetip:80 requested targetip:80 hostname:targetip S:163,R:226 hops:0 text:CONNECT targetip:80
======= Backtrace: =========
/lib64/libc.so.6[0x33a4e75f3e]
/lib64/libc.so.6[0x33a4e7a6f4]
/lib64/libc.so.6(__libc_malloc+0x5c)[0x33a4e7abfc]
/lib64/libc.so.6[0x33a4e66e8b]
/usr/bin/3proxy[0x409d1f]
/usr/bin/3proxy[0x40adc7]
/usr/bin/3proxy[0x40cd02]
/usr/bin/3proxy[0x402a5a]
/usr/bin/3proxy[0x402eb6]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x33a4e1ed1d]
/usr/bin/3proxy[0x402399]
======= Memory map: ========
00400000-0042a000 r-xp 00000000 fd:00 2892126                            /usr/local/bin/3proxy
00629000-0062d000 rw-p 00029000 fd:00 2892126                            /usr/local/bin/3proxy
0062d000-0062f000 rw-p 00000000 00:00 0 
00779000-007ea000 rw-p 00000000 00:00 0 
007ea000-00a92000 rw-p 00000000 00:00 0 
33a4600000-33a4620000 r-xp 00000000 fd:00 1966500                        /lib64/ld-2.12.so
33a481f000-33a4820000 r--p 0001f000 fd:00 1966500                        /lib64/ld-2.12.so
33a4820000-33a4821000 rw-p 00020000 fd:00 1966500                        /lib64/ld-2.12.so
33a4821000-33a4822000 rw-p 00000000 00:00 0 
33a4a00000-33a4a02000 r-xp 00000000 fd:00 1966503                        /lib64/libdl-2.12.so
33a4a02000-33a4c02000 ---p 00002000 fd:00 1966503                        /lib64/libdl-2.12.so
33a4c02000-33a4c03000 r--p 00002000 fd:00 1966503                        /lib64/libdl-2.12.so
33a4c03000-33a4c04000 rw-p 00003000 fd:00 1966503                        /lib64/libdl-2.12.so
33a4e00000-33a4f8a000 r-xp 00000000 fd:00 1966501                        /lib64/libc-2.12.so
33a4f8a000-33a518a000 ---p 0018a000 fd:00 1966501                        /lib64/libc-2.12.so
33a518a000-33a518e000 r--p 0018a000 fd:00 1966501                        /lib64/libc-2.12.so
33a518e000-33a5190000 rw-p 0018e000 fd:00 1966501                        /lib64/libc-2.12.so
33a5190000-33a5194000 rw-p 00000000 00:00 0 
33a5200000-33a5217000 r-xp 00000000 fd:00 1966510                        /lib64/libpthread-2.12.so
33a5217000-33a5417000 ---p 00017000 fd:00 1966510                        /lib64/libpthread-2.12.so
33a5417000-33a5418000 r--p 00017000 fd:00 1966510                        /lib64/libpthread-2.12.so
33a5418000-33a5419000 rw-p 00018000 fd:00 1966510                        /lib64/libpthread-2.12.so
33a5419000-33a541d000 rw-p 00000000 00:00 0 
33a7200000-33a7216000 r-xp 00000000 fd:00 1966514                        /lib64/libgcc_s-4.4.7-20120601.so.1
33a7216000-33a7415000 ---p 00016000 fd:00 1966514                        /lib64/libgcc_s-4.4.7-20120601.so.1
33a7415000-33a7416000 rw-p 00015000 fd:00 1966514                        /lib64/libgcc_s-4.4.7-20120601.so.1
2b2da31a5000-2b2da31a6000 rw-p 00000000 00:00 0 
2b2da31a8000-2b2da31a9000 ---p 00000000 00:00 0 
2b2da31a9000-2b2da31b0000 rw-p 00000000 00:00 0 
2b2da31b0000-2b2da31b3000 rw-p 00000000 00:00 0 
2b2da31b3000-2b2da31b4000 rw-p 00000000 00:00 0 
2b2da31b4000-2b2da31b5000 ---p 00000000 00:00 0 
2b2da31b5000-2b2da31bd000 rw-p 00000000 00:00 0 
2b2da31bd000-2b2da31be000 ---p 00000000 00:00 0 
2b2da31be000-2b2da31c5000 rw-p 00000000 00:00 0 
2b2da31c5000-2b2da31c6000 ---p 00000000 00:00 0 
2b2da31c6000-2b2da31ce000 rw-p 00000000 00:00 0 
2b2da31ce000-2b2da31cf000 ---p 00000000 00:00 0 
2b2da31cf000-2b2da31d6000 rw-p 00000000 00:00 0 
2b2da31d6000-2b2da31d7000 ---p 00000000 00:00 0 
2b2da31d7000-2b2da31de000 rw-p 00000000 00:00 0 
2b2da3434000-2b2da3435000 ---p 00000000 00:00 0 
2b2da3435000-2b2da343c000 rw-p 00000000 00:00 0 
2b2da343c000-2b2da343d000 ---p 00000000 00:00 0 
2b2da343d000-2b2da3444000 rw-p 00000000 00:00 0 
2b2da4000000-2b2da4021000 rw-p 00000000 00:00 0 
2b2da4021000-2b2da8000000 ---p 00000000 00:00 0 
2b2da8000000-2b2da8021000 rw-p 00000000 00:00 0 
2b2da8021000-2b2dac000000 ---p 00000000 00:00 0 
2b2dac000000-2b2dac001000 ---p 00000000 00:00 0 
2b2dac001000-2b2dac008000 rw-p 00000000 00:00 0 
2b2dac008000-2b2dac009000 ---p 00000000 00:00 0 
2b2dac009000-2b2dac010000 rw-p 00000000 00:00 0 
2b2db0000000-2b2db0021000 rw-p 00000000 00:00 0 
2b2db0021000-2b2db4000000 ---p 00000000 00:00 0 
2b2db4000000-2b2db4021000 rw-p 00000000 00:00 0 
2b2db4021000-2b2db8000000 ---p 00000000 00:00 0 
2b2db8000000-2b2db8001000 ---p 00000000 00:00 0 
2b2db8001000-2b2db8008000 rw-p 00000000 00:00 0 
2b2db8008000-2b2db8009000 ---p 00000000 00:00 0 
2b2db8009000-2b2db8010000 rw-p 00000000 00:00 0 
2b2dbc000000-2b2dbc021000 rw-p 00000000 00:00 0 
2b2dbc021000-2b2dc0000000 ---p 00000000 00:00 0 
2b2dc0000000-2b2dc0021000 rw-p 00000000 00:00 0 
2b2dc0021000-2b2dc4000000 ---p 00000000 00:00 0 
2b2dc4000000-2b2dc4001000 ---p 00000000 00:00 0 
2b2dc4001000-2b2dc4008000 rw-p 00000000 00:00 0 
2b2dc4008000-2b2dc4009000 ---p 00000000 00:00 0 
2b2dc4009000-2b2dc4010000 rw-p 00000000 00:00 0 
2b2dc8000000-2b2dc8021000 rw-p 00000000 00:00 0 
2b2dc8021000-2b2dcc000000 ---p 00000000 00:00 0 
2b2dcc000000-2b2dcc021000 rw-p 00000000 00:00 0 
2b2dcc021000-2b2dd0000000 ---p 00000000 00:00 0 
2b2dd0000000-2b2dd0001000 ---p 00000000 00:00 0 
2b2dd0001000-2b2dd0008000 rw-p 00000000 00:00 0 
2b2dd0008000-2b2dd0009000 ---p 00000000 00:00 0 
2b2dd0009000-2b2dd0010000 rw-p 00000000 00:00 0 
2b2dd4000000-2b2dd4021000 rw-p 00000000 00:00 0 
2b2dd4021000-2b2dd8000000 ---p 00000000 00:00 0 
2b2dd8000000-2b2dd8021000 rw-p 00000000 00:00 0 
2b2dd8021000-2b2ddc000000 ---p 00000000 00:00 0 
2b2ddc000000-2b2ddc001000 ---p 00000000 00:00 0 
2b2ddc001000-2b2ddc008000 rw-p 00000000 00:00 0 
2b2ddc008000-2b2ddc009000 ---p 00000000 00:00 0 
2b2ddc009000-2b2ddc010000 rw-p 00000000 00:00 0 
2b2de0000000-2b2de0021000 rw-p 00000000 00:00 0 
2b2de0021000-2b2de4000000 ---p 00000000 00:00 0 
2b2de4000000-2b2de4021000 rw-p 00000000 00:00 0 
2b2de4021000-2b2de8000000 ---p 00000000 00:00 0 
2b2de8000000-2b2de8001000 ---p 00000000 00:00 0 
2b2de8001000-2b2de8008000 rw-p 00000000 00:00 0 
2b2de8008000-2b2de8009000 ---p 00000000 00:00 0 
2b2de8009000-2b2de8010000 rw-p 00000000 00:00 0 
2b2dec000000-2b2dec021000 rw-p 00000000 00:00 0 
2b2dec021000-2b2df0000000 ---p 00000000 00:00 0 
2b2df0000000-2b2df0021000 rw-p 00000000 00:00 0 
2b2df0021000-2b2df4000000 ---p 00000000 00:00 0 
2b2df4000000-2b2df4001000 ---p 00000000 00:00 0 
2b2df4001000-2b2df4008000 rw-p 00000000 00:00 0 
2b2df4008000-2b2df4009000 ---p 00000000 00:00 0 
2b2df4009000-2b2df4010000 rw-p 00000000 00:00 0 
2b2df8000000-2b2df8021000 rw-p 00000000 00:00 0 
2b2df8021000-2b2dfc000000 ---p 00000000 00:00 0 
2b2dfc000000-2b2dfc021000 rw-p 00000000 00:00 0 
2b2dfc021000-2b2e00000000 ---p 00000000 00:00 0 
2b2e00000000-2b2e00001000 ---p 00000000 00:00 0 
2b2e00001000-2b2e00008000 rw-p 00000000 00:00 0 
2b2e00008000-2b2e00009000 ---p 00000000 00:00 0 
2b2e00009000-2b2e00010000 rw-p 00000000 00:00 0 
2b2e04000000-2b2e04021000 rw-p 00000000 00:00 0 
2b2e04021000-2b2e08000000 ---p 00000000 00:00 0 
2b2e08000000-2b2e08021000 rw-p 00000000 00:00 0 
2b2e08021000-2b2e0c000000 ---p 00000000 00:00 0 
2b2e0c000000-2b2e0c001000 ---p 00000000 00:00 0 
2b2e0c001000-2b2e0c008000 rw-p 00000000 00:00 0 
2b2e0c008000-2b2e0c009000 ---p 00000000 00:00 0 
2b2e0c009000-2b2e0c010000 rw-p 00000000 00:00 0 
2b2e10000000-2b2e10021000 rw-p 00000000 00:00 0 
2b2e10021000-2b2e14000000 ---p 00000000 00:00 0 
2b2e14000000-2b2e14021000 rw-p 00000000 00:00 0 
2b2e14021000-2b2e18000000 ---p 00000000 00:00 0 
2b2e18000000-2b2e18001000 ---p 00000000 00:00 0 
2b2e18001000-2b2e18008000 rw-p 00000000 00:00 0 
2b2e18008000-2b2e18009000 ---p 00000000 00:00 0 
2b2e18009000-2b2e18010000 rw-p 00000000 00:00 0 
2b2e1c000000-2b2e1c021000 rw-p 00000000 00:00 0 
2b2e1c021000-2b2e20000000 ---p 00000000 00:00 0 
2b2e20000000-2b2e20021000 rw-p 00000000 00:00 0 
2b2e20021000-2b2e24000000 ---p 00000000 00:00 0 
2b2e24000000-2b2e24001000 ---p 00000000 00:00 0 
2b2e24001000-2b2e24008000 rw-p 00000000 00:00 0 
2b2e28000000-2b2e28021000 rw-p 00000000 00:00 0 
2b2e28021000-2b2e2c000000 ---p 00000000 00:00 0 
2b2e2c000000-2b2e2c021000 rw-p 00000000 00:00 0 
2b2e2c021000-2b2e30000000 ---p 00000000 00:00 0 
2b2e30001000-2b2e30002000 ---p 00000000 00:00 0 
2b2e30002000-2b2e30009000 rw-p 00000000 00:00 0 
2b2e34000000-2b2e34021000 rw-p 00000000 00:00 0 
2b2e34021000-2b2e38000000 ---p 00000000 00:00 0 
2b2e38000000-2b2e38021000 rw-p 00000000 00:00 0 
2b2e38021000-2b2e3c000000 ---p 00000000 00:00 0 
2b2e3c000000-2b2e3c001000 ---p 00000000 00:00 0 
2b2e3c001000-2b2e3c008000 rw-p 00000000 00:00 0 
2b2e3c008000-2b2e3c009000 ---p 00000000 00:00 0 
2b2e3c009000-2b2e3c010000 rw-p 00000000 00:00 0 
2b2e40000000-2b2e40021000 rw-p 00000000 00:00 0 
2b2e40021000-2b2e44000000 ---p 00000000 00:00 0 
2b2e44000000-2b2e44021000 rw-p 00000000 00:00 0 
2b2e44021000-2b2e48000000 ---p 00000000 00:00 0 
2b2e48000000-2b2e48001000 ---p 00000000 00:00 0 
2b2e48001000-2b2e48008000 rw-p 00000000 00:00 0 
2b2e48008000-2b2e48009000 ---p 00000000 00:00 0 
2b2e48009000-2b2e48010000 rw-p 00000000 00:00 0 
2b2e4c000000-2b2e4c021000 rw-p 00000000 00:00 0 
2b2e4c021000-2b2e50000000 ---p 00000000 00:00 0 
2b2e50000000-2b2e50021000 rw-p 00000000 00:00 0 
2b2e50021000-2b2e54000000 ---p 00000000 00:00 0 
2b2e54000000-2b2e54001000 ---p 00000000 00:00 0 
2b2e54001000-2b2e54008000 rw-p 00000000 00:00 0 
2b2e54008000-2b2e54009000 ---p 00000000 00:00 0 
2b2e54009000-2b2e54010000 rw-p 00000000 00:00 0 
2b2e58000000-2b2e58021000 rw-p 00000000 00:00 0 
2b2e58021000-2b2e5c000000 ---p 00000000 00:00 0 
2b2e5c000000-2b2e5c021000 rw-p 00000000 00:00 0 
2b2e5c021000-2b2e60000000 ---p 00000000 00:00 0 
2b2e60000000-2b2e60001000 ---p 00000000 00:00 0 
2b2e60001000-2b2e60008000 rw-p 00000000 00:00 0 
2b2e60008000-2b2e60009000 ---p 00000000 00:00 0 
2b2e60009000-2b2e60010000 rw-p 00000000 00:00 0 
2b2e64000000-2b2e64021000 rw-p 00000000 00:00 0 
2b2e64021000-2b2e68000000 ---p 00000000 00:00 0 
2b2e68000000-2b2e68021000 rw-p 00000000 00:00 0 
2b2e68021000-2b2e6c000000 ---p 00000000 00:00 0 
2b2e6c000000-2b2e6c001000 ---p 00000000 00:00 0 
2b2e6c001000-2b2e6c008000 rw-p 00000000 00:00 0 
2b2e6c008000-2b2e6c009000 ---p 00000000 00:00 0 
2b2e6c009000-2b2e6c010000 rw-p 00000000 00:00 0 
2b2e70000000-2b2e70021000 rw-p 00000000 00:00 0 
2b2e70021000-2b2e74000000 ---p 00000000 00:00 0 
2b2e74000000-2b2e74021000 rw-p 00000000 00:00 0 
2b2e74021000-2b2e78000000 ---p 00000000 00:00 0 
2b2e78000000-2b2e78001000 ---p 00000000 00:00 0 
2b2e78001000-2b2e78008000 rw-p 00000000 00:00 0 
2b2e78008000-2b2e78009000 ---p 00000000 00:00 0 
2b2e78009000-2b2e78010000 rw-p 00000000 00:00 0 
2b2e7c000000-2b2e7c021000 rw-p 00000000 00:00 0 
2b2e7c021000-2b2e80000000 ---p 00000000 00:00 0 
2b2e80000000-2b2e80021000 rw-p 00000000 00:00 0 
2b2e80021000-2b2e84000000 ---p 00000000 00:00 0 
2b2e84000000-2b2e84001000 ---p 00000000 00:00 0 
2b2e84001000-2b2e84008000 rw-p 00000000 00:00 0 
2b2e84008000-2b2e84009000 ---p 00000000 00:00 0 
2b2e84009000-2b2e84010000 rw-p 00000000 00:00 0 
2b2e88000000-2b2e88021000 rw-p 00000000 00:00 0 
2b2e88021000-2b2e8c000000 ---p 00000000 00:00 0 
2b2e8c000000-2b2e8c021000 rw-p 00000000 00:00 0 
2b2e8c021000-2b2e90000000 ---p 00000000 00:00 0 
2b2e90000000-2b2e90021000 rw-p 00000000 00:00 0 
2b2e90021000-2b2e94000000 ---p 00000000 00:00 0 
2b2e94000000-2b2e94021000 rw-p 00000000 00:00 0 
2b2e94021000-2b2e98000000 ---p 00000000 00:00 0 
2b2e98000000-2b2e98001000 ---p 00000000 00:00 0 
2b2e98001000-2b2e98008000 rw-p 00000000 00:00 0 
2b2e98008000-2b2e98009000 ---p 00000000 00:00 0 
2b2e98009000-2b2e98010000 rw-p 00000000 00:00 0 
2b2e9c000000-2b2e9c021000 rw-p 00000000 00:00 0 
2b2e9c021000-2b2ea0000000 ---p 00000000 00:00 0 
2b2ea0000000-2b2ea0021000 rw-p 00000000 00:00 0 
2b2ea0021000-2b2ea4000000 ---p 00000000 00:00 0 
2b2ea4000000-2b2ea4001000 ---p 00000000 00:00 0 
2b2ea4001000-2b2ea4008000 rw-p 00000000 00:00 0 
2b2ea4008000-2b2ea4009000 ---p 00000000 00:00 0 
2b2ea4009000-2b2ea4010000 rw-p 00000000 00:00 0 
2b2ea8000000-2b2ea8021000 rw-p 00000000 00:00 0 
2b2ea8021000-2b2eac000000 ---p 00000000 00:00 0 
2b2eac000000-2b2eac021000 rw-p 00000000 00:00 0 
2b2eac021000-2b2eb0000000 ---p 00000000 00:00 0 
2b2eb0000000-2b2eb0021000 rw-p 00000000 00:00 0 
2b2eb0021000-2b2eb4000000 ---p 00000000 00:00 0 
2b2eb4000000-2b2eb4021000 rw-p 00000000 00:00 0 
2b2eb4021000-2b2eb8000000 ---p 00000000 00:00 0 
2b2eb8000000-2b2eb8001000 ---p 00000000 00:00 0 
2b2eb8001000-2b2eb8008000 rw-p 00000000 00:00 0 
2b2eb8008000-2b2eb8009000 ---p 00000000 00:00 0 
2b2eb8009000-2b2eb8010000 rw-p 00000000 00:00 0 
2b2ebc000000-2b2ebc021000 rw-p 00000000 00:00 0 
2b2ebc021000-2b2ec0000000 ---p 00000000 00:00 0 
2b2ec0000000-2b2ec0021000 rw-p 00000000 00:00 0 
2b2ec0021000-2b2ec4000000 ---p 00000000 00:00 0 
2b2ec4000000-2b2ec4001000 ---p 00000000 00:00 0 
2b2ec4001000-2b2ec4008000 rw-p 00000000 00:00 0 
2b2ec4008000-2b2ec4009000 ---p 00000000 00:00 0 
2b2ec4009000-2b2ec4010000 rw-p 00000000 00:00 0 
2b2ec8000000-2b2ec8021000 rw-p 00000000 00:00 0 
2b2ec8021000-2b2ecc000000 ---p 00000000 00:00 0 
2b2ecc000000-2b2ecc021000 rw-p 00000000 00:00 0 
2b2ecc021000-2b2ed0000000 ---p 00000000 00:00 0 
2b2ed0000000-2b2ed0001000 ---p 00000000 00:00 0 
2b2ed0001000-2b2ed0008000 rw-p 00000000 00:00 0 
2b2ed0008000-2b2ed0009000 ---p 00000000 00:00 0 
2b2ed0009000-2b2ed0010000 rw-p 00000000 00:00 0 
2b2ed4000000-2b2ed4021000 rw-p 00000000 00:00 0 
2b2ed4021000-2b2ed8000000 ---p 00000000 00:00 0 
2b2ed8000000-2b2ed8021000 rw-p 00000000 00:00 0 
2b2ed8021000-2b2edc000000 ---p 00000000 00:00 0 
2b2edc000000-2b2edc001000 ---p 00000000 00:00 0 
2b2edc001000-2b2edc008000 rw-p 00000000 00:00 0 
2b2edc008000-2b2edc009000 ---p 00000000 00:00 0 
2b2edc009000-2b2edc010000 rw-p 00000000 00:00 0 
2b2ee0000000-2b2ee0021000 rw-p 00000000 00:00 0 
2b2ee0021000-2b2ee4000000 ---p 00000000 00:00 0 
2b2ee4000000-2b2ee4021000 rw-p 00000000 00:00 0 
2b2ee4021000-2b2ee8000000 ---p 00000000 00:00 0 
2b2ee8000000-2b2ee8001000 ---p 00000000 00:00 0 
2b2ee8001000-2b2ee8008000 rw-p 00000000 00:00 0 
2b2ee8008000-2b2ee8009000 ---p 00000000 00:00 0 
2b2ee8009000-2b2ee8010000 rw-p 00000000 00:00 0 
2b2eec000000-2b2eec021000 rw-p 00000000 00:00 0 
2b2eec021000-2b2ef0000000 ---p 00000000 00:00 0 
2b2ef0000000-2b2ef0021000 rw-p 00000000 00:00 0 
2b2ef0021000-2b2ef4000000 ---p 00000000 00:00 0 
2b2ef4000000-2b2ef4001000 ---p 00000000 00:00 0 
2b2ef4001000-2b2ef4008000 rw-p 00000000 00:00 0 
2b2ef4008000-2b2ef4009000 ---p 00000000 00:00 0 
2b2ef4009000-2b2ef4010000 rw-p 00000000 00:00 0 
2b2ef8000000-2b2ef8021000 rw-p 00000000 00:00 0 
2b2ef8021000-2b2efc000000 ---p 00000000 00:00 0 
2b2efc000000-2b2efc021000 rw-p 00000000 00:00 0 
2b2efc021000-2b2f00000000 ---p 00000000 00:00 0 
2b2f00000000-2b2f00001000 ---p 00000000 00:00 0 
2b2f00001000-2b2f00008000 rw-p 00000000 00:00 0 
2b2f00008000-2b2f00009000 ---p 00000000 00:00 0 
2b2f00009000-2b2f00010000 rw-p 00000000 00:00 0 
2b2f04000000-2b2f04021000 rw-p 00000000 00:00 0 
2b2f04021000-2b2f08000000 ---p 00000000 00:00 0 
2b2f08000000-2b2f08021000 rw-p 00000000 00:00 0 
2b2f08021000-2b2f0c000000 ---p 00000000 00:00 0 
2b2f0c000000-2b2f0c001000 ---p 00000000 00:00 0 
2b2f0c001000-2b2f0c008000 rw-p 00000000 00:00 0 
2b2f0c008000-2b2f0c009000 ---p 00000000 00:00 0 
2b2f0c009000-2b2f0c010000 rw-p 00000000 00:00 0 
2b2f0c010000-2b2f0c011000 ---p 00000000 00:00 0 
2b2f0c011000-2b2f0c018000 rw-p 00000000 00:00 0 
2b2f0c018000-2b2f0c019000 ---p 00000000 00:00 0 
2b2f0c019000-2b2f0c020000 rw-p 00000000 00:00 0 
2b2f0c020000-2b2f0c021000 ---p 00000000 00:00 0 
2b2f0c021000-2b2f0c028000 rw-p 00000000 00:00 0 
2b2f0c028000-2b2f0c029000 ---p 00000000 00:00 0 
2b2f0c029000-2b2f0c030000 rw-p 00000000 00:00 0 
2b2f0c030000-2b2f0c031000 ---p 00000000 00:00 0 
2b2f0c031000-2b2f0c038000 rw-p 00000000 00:00 0 
2b2f0c038000-2b2f0c039000 ---p 00000000 00:00 0 
2b2f0c039000-2b2f0c040000 rw-p 00000000 00:00 0 
2b2f10000000-2b2f10021000 rw-p 00000000 00:00 0 
2b2f10021000-2b2f14000000 ---p 00000000 00:00 0 
7ffd610ad000-7ffd610c2000 rw-p 00000000 00:00 0                          [stack]
7ffd611cc000-7ffd611cd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by raintears2** [comment]
It printed "printf(): Bad file descriptor" some times in the terminal screen.
It kill the 3proxy process by itself and quit.

**Comment by z3APA3A** [comment]
Try to adjust 'stacksize', if it doesn't help send binaries and coredump to 3proxy@3proxy.ru

**Comment by z3APA3A** [comment]
Probably was duplicate to https://github.com/z3APA3A/3proxy/issues/48
