### ISSUE TITLE
[Request] tcp_outgoing_address like squid3

### ISSUE THREAD

**Issue by soffchen** [z3APA3A/3proxy#91]
```
#  TAG: tcp_outgoing_address
#       Allows you to map requests to different outgoing IP addresses
#       based on the username or source address of the user making
#       the request.
```

3proxy server sometimes has multiple outgoing tcp addresses, and we have to choose one :)

**Comment by z3APA3A** [comment]
you can do it with 'extip' type redirections. E.g.

allow user 1
parent 1000 extip 1.1.1.1 0
allow user 2
parent 1000 extip 2.2.2.2 0
