### ISSUE TITLE
Как дополнить заголовок к запросу клиента

### ISSUE THREAD

**Issue by MeGaPk** [z3APA3A/3proxy#93]
Добрый день!
Вопрос такой.
Имеется прокси сервер версией 0.8+
Нужно, что бы используя прокси сервер, добавлялся дополнительный заголовок к запросу пользователя.
Например в Headers добавить '3Proxy: YES'.

почитал про pcre, то что то не получается завести. 
Выбивает ошибку на первой же строке: Command: 'plugin' failed 

Жду ответа, заранее благодарю!

**Comment by z3APA3A** [comment]
Да, это надо делать именно через PCRE. А что именно в команде plugin и какой полный текст ошибки??
