### ISSUE TITLE
Wrong error code on name resolution problem in 'proxy' (Secured services react differently to the same client)

### ISSUE THREAD

**Issue by AnrDaemon** [z3APA3A/3proxy#94]
I don't quite understand, what's going on, but here's the test results:

3proxy 0.8.6
Linux daemon1.ads.darkdragon.lan 4.4.0-36-generic #55~14.04.1-Ubuntu SMP Fri Aug 12 11:49:30 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

```
$ curl -siIx http://proxy:3128 -- http://download.webmoney.ru/wmk_ru.exe
HTTP/1.0 403 Forbidden
Proxy-Connection: close
Content-type: text/html; charset=utf-8

$ curl -siIx socks5://proxy:1080 -- http://download.webmoney.ru/wmk_ru.exe
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Fri, 02 Sep 2016 10:58:54 GMT
Content-Type: text/html
Connection: keep-alive
Location: http://dl.webmoney.ru/v3997b4297/wmkeeper_ru.exe
X-Frame-Options: DENY
```

Logs:

```
2016.09.02 13:58:45.970 PROXY:3128 "-" 192.168.1.10:61230 (0)0.0.0.0:0/00001 0 0 HEAD http://download.webmoney.ru/wmk_ru.exe HTTP/1.1
2016.09.02 13:58:54.073 SOCK5:1080 "-" 192.168.1.10:61233 (0)62.210.115.140:80/00000 95 218 CONNECT 62.210.115.140:80
```

Config: 

```
#!/opt/3proxy/bin/3proxy
nserver 127.0.0.1
nscache 65536
log "/var/log/3proxy/3proxy.log"
logformat "L%Y.%m.%d %H:%M:%S.%. %N:%p ""%U"" %C:%c (%h)%R:%r/%E %O %I %T"
auth none
auth none
internal 192.168.1.12
auth iponly
deny * * 192.168.19.1,192.168.1.12,127.0.0.0/8 *
allow * * * 20,21,22,23,25,80-88,110,443
allow * * * 433
deny * * * 0-1023,3080
allow * 192.168.1.0/27
proxy -a -n -p3128
socks -p1080
tcppm 26000 87.237.38.200 26000
tcppm 2106 216.107.242.199 2106
flush
auth iponly
internal 127.0.0.1
allow * 127.0.0.1
maxconn 3
admin -p3080
```

**Comment by z3APA3A** [comment]
check
nslookup download.webmoney.ru 127.0.0.1
from proxy server.

Are you sure this is exactly the configuration you are running? According to logs, it looks like you have a list of allowed methods for proxy and there is no HEAD in this list. kill all 3proxy instances and restart it with this configuration.

**Comment by AnrDaemon** [comment]
Yes, this is exactly the configuration I'm running.
I've killed it multiple times, and even restarted the host.

```
$ nslookup download.webmoney.ru 127.0.0.1
Server:         127.0.0.1
Address:        127.0.0.1#53

Non-authoritative answer:
Name:   download.webmoney.ru
Address: 62.210.115.140
Name:   download.webmoney.ru
Address: 5.199.142.158
Name:   download.webmoney.ru
Address: 88.198.43.118
```

```
# ps ax | grep 3pro
 4210     1 ?        Ssl  00:01:04 /usr/local/sbin/3proxy /etc/3proxy/3proxy.conf
```

```
# cat /etc/3proxy/3proxy.conf
#!/opt/3proxy/bin/3proxy
nserver 127.0.0.1
nscache 65536
log "/var/log/3proxy/3proxy.log"
logformat "L%Y.%m.%d %H:%M:%S.%. %N:%p ""%U"" %C:%c (%h)%R:%r/%E %O %I %T"
auth none
auth none
internal 192.168.1.12
auth iponly
deny * * 192.168.19.1,192.168.1.12,127.0.0.0/8 *
allow * * * 20,21,22,23,25,80-88,110,443
allow * * * 433
deny * * * 0-1023,3080
allow * 192.168.1.0/27
proxy -a -n -p3128
socks -p1080
tcppm 26000 87.237.38.200 26000
tcppm 2106 216.107.242.199 2106
flush
auth iponly
internal 127.0.0.1
allow * 127.0.0.1
maxconn 3
admin -p3080
```

**Comment by z3APA3A** [comment]
Does the problem persists with 0.8.7?

**Comment by z3APA3A** [comment]
And please add %Q:%p to log

**Comment by AnrDaemon** [comment]
Will test once I get a load off my shoulders, even if a little.

В эту субботу умерла моя мама… похороны завтра… Так что мне сейчас несколько… не до тестов. Извини.

**Comment by AnrDaemon** [comment]
While I was testing it, I've stumbled upon an interesting effect.
This issue can be observed immediately following a service restart, but if I let it settle for a few days (the server was running for 5 days while I was sorting the abovementioned issue), it suddenly works just fine with the same config.
But now I've installed a freshly compiled 0.8.7 and
```
2016.09.07 17:26:24.657 PROXY:3128 "-" 192.168.1.10:51864 0.0.0.0:80 (0)0.0.0.0:0/00001 0 0 HEAD http://download.webmoney.ru/wmk_ru.exe HTTP/1.1
2016.09.07 17:26:44.714 SOCK5:1080 "-" 192.168.1.10:51870 5.199.142.158:80 (0)5.199.142.158:80/00000 95 218 CONNECT 5.199.142.158:80
```
```
#!/opt/3proxy/bin/3proxy
nserver 127.0.0.1
nscache 65536
log "/var/log/3proxy/3proxy.log"
logformat "L%Y.%m.%d %H:%M:%S.%. %N:%p ""%U"" %C:%c %Q:%q (%h)%R:%r/%E %O %I %T"
auth none
auth none
internal 192.168.1.12
auth iponly
deny * * 192.168.19.1,192.168.1.12,127.0.0.0/8 *
allow * * * 20,21,22,23,25,80-88,110,443
allow * * * 433
deny * * * 0-1023,3080
allow * 192.168.1.0/27
proxy -a -n -p3128
socks -p1080
tcppm 26000 87.237.38.200 26000
tcppm 2106 216.107.242.199 2106
flush
auth iponly
internal 127.0.0.1
allow * 127.0.0.1
maxconn 3
admin -p3080
```

**Comment by z3APA3A** [comment]
It looks like problem with DNS server, it fails to resolve names. After server restart name cache is empty and it causes more requests to DNS. Via SOCKS you use name resultion on client and it doesn't require to resolve name on server side. 
Check / adjust ratelimits for your name server and/or try to add additional nserver entry.

**Comment by AnrDaemon** [comment]
Can't be true.
```
# dig @127.0.0.1 download.webmoney.ru.

; <<>> DiG 9.9.5-3ubuntu0.8-Ubuntu <<>> @127.0.0.1 download.webmoney.ru.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26861
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 3, ADDITIONAL: 4

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;download.webmoney.ru.          IN      A

;; ANSWER SECTION:
download.WEBMONEY.ru.   3797    IN      A       88.198.43.118
download.WEBMONEY.ru.   3797    IN      A       62.210.115.140
download.WEBMONEY.ru.   3797    IN      A       5.199.142.158

;; AUTHORITY SECTION:
WEBMONEY.ru.            243883  IN      NS      ns.relsoft.RU.
WEBMONEY.ru.            243883  IN      NS      ns.molot.RU.
WEBMONEY.ru.            243883  IN      NS      ns.relsoftcom.RU.

;; ADDITIONAL SECTION:
ns.MOLOT.ru.            243883  IN      A       212.158.173.4
ns.RELSOFT.ru.          243883  IN      A       82.198.171.4
ns.RELSOFTCOM.ru.       243883  IN      A       212.118.48.4

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Wed Sep 07 17:50:51 MSK 2016
;; MSG SIZE  rcvd: 275
```

**Comment by AnrDaemon** [comment]
My only guess, is if 3proxy doesn't handle long DNS replies gracefully.
:BRB:

**Comment by z3APA3A** [comment]
Try to change nserver to e.g. 8.8.8.8

**Comment by z3APA3A** [comment]
```
>curl -siIx http://127.0.0.1:3128 -- http://download.webmoney.ru/wmk_ru.exe
HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 07 Sep 2016 15:00:47 GMT
Content-Type: text/html
Location: http://dl.webmoney.ru/v3997b4297/wmkeeper_ru.exe
X-Frame-Options: DENY
Connection: Close
Proxy-Connection: Close

``````
>3proxy 3proxy.cfg
2016.09.07 17:59:53.402 PROXY:3128 "-" 0.0.0.0:3128 (0)0.0.0.0:0/00000 0 0 Accep
ting connections [22876/24896]
2016.09.07 17:59:53.411 SOCKS:1080 "-" 0.0.0.0:1080 (0)0.0.0.0:0/00000 0 0 Accep
ting connections [22876/2840]
2016.09.07 17:59:53.420 TCPPM:26000 "-" 0.0.0.0:26000 (0)0.0.0.0:0/00000 0 0 Acc
epting connections [22876/18064]
2016.09.07 17:59:53.430 TCPPM:2106 "-" 0.0.0.0:2106 (0)0.0.0.0:0/00000 0 0 Accep
ting connections [22876/4220]
2016.09.07 17:59:53.440 ADMIN:3080 "-" 127.0.0.1:3080 (0)0.0.0.0:0/00000 0 0 Acc
epting connections [22876/23660]
2016.09.07 18:00:47.248 PROXY:3128 "-" 127.0.0.1:62562 (0)5.199.142.158:80/00000
 119 218 HEAD http://download.webmoney.ru/wmk_ru.exe HTTP/1.1
```

```
>cat 3proxy.cfg
nserver 8.8.8.8
nscache 65536
log
logformat "L%Y.%m.%d %H:%M:%S.%. %N:%p ""%U"" %C:%c (%h)%R:%r/%E %O %I %T"
auth none
auth none
#internal 192.168.1.12
auth iponly
deny * * 192.168.19.1,192.168.1.12,127.0.0.0/8 *
allow * * * 20,21,22,23,25,80-88,110,443
allow * * * 433
deny * * * 0-1023,3080
allow * 192.168.1.0/27
proxy -a -n -p3128
socks -p1080
tcppm 26000 87.237.38.200 26000
tcppm 2106 216.107.242.199 2106
flush
auth iponly
internal 127.0.0.1
allow * 127.0.0.1
maxconn 3
admin -p3080
```

**Comment by AnrDaemon** [comment]
As I said, I found it working after I was away for an extended period of time.
I'll see if I spot it working again, and try to get more data.
Using an external DNS isn't really a good idea. I have local configuration with redundancy and automatic forwarder switching.

**Comment by z3APA3A** [comment]
I ask to try to switch to external resolver in attempt to identify the problem. Your resolver behavior is a bit weird, it replies with download.WEBMONEY.ru in reply to download.webmoney.ru, it may be a source of problem.

**Comment by z3APA3A** [comment]
The problem is definitely in name resolution, I fixed the problem with error code (00001 instead of 00100) in devel.

**Comment by z3APA3A** [comment]
Error code is fixed here: 88263ebde93c3d7fdcf493f8804576cf1197e57d
it doesn't fix your problem though.

**Comment by AnrDaemon** [comment]
It seems like I've lost the reply I was typing…
Anyway, I've tested all published NS of theirs and one apparently have connectivity issues. But none of the available serve mixed case names ATM, so I purged resolver cache and got the working system.

However, according to https://tools.ietf.org/html/rfc1034#section-3.1 (paragraph 5), conformant DNS client must use caseless comparison of domain names.

**Comment by z3APA3A** [comment]
The problem is not in the case sensitivity itself. 3proxy doesn't perform case sensitive match, but some clients, including well known browsers do, see https://deepthought.isc.org/article/AA-01113/0/Case-Insensitive-Response-Compression-May-Cause-Problems-With-Mixed-Case-Data-and-Non-Conforming-Clients.html This fact may point to some problems with resolve.

**Comment by AnrDaemon** [comment]
Since I'm using curl… Not a browser. the problem is that it's SSH, which makes it harder to debug. But there's apparently no traffic between 3proxy and outside world on failed request, which led me to believe that the problem is internal.

**Comment by z3APA3A** [comment]
Mixed case resolution issues will be solved here: https://github.com/z3APA3A/3proxy/issues/120
