### ISSUE TITLE
Не работают некоторые IP

### ISSUE THREAD

**Issue by fastitua** [z3APA3A/3proxy#95]
Доброе утро!
Все настроил, почти все работает, но есть моменты, некоторые IP не работают. 
Конфиг:
```
...
```

40502 и 40504 работают нормально, а вот 40503 не работает совсем, пишет при заходе:

> 502 Bad Gateway
> Host Not Found or connection failed

Проверил через ping6 -I IP GOOGLE.RU, оказалось что с некоторых интерфейсов не идет пинг, где может быть проблема? 

Спасибо!

**Comment by z3APA3A** [comment]
Проблема в том, что этот адрес не прибинжен к интерфейсу, добавьте его в конфигурацию.
