### ISSUE TITLE
Socks + IPv6

### ISSUE THREAD

**Issue by gggrafff** [z3APA3A/3proxy#96]
Здравствуйте.
У меня проблема не в сервере, а в клиенте. Помогите, пожалуйста. Пишу код, нужно через прокси сервер загрузить страничку. Всё просто как дважды два. Но проблема возникает, когда я обращаюсь к прокси-серверу по IPv4, а его внешний адрес находится в IPv6 сети. При этом http прокси работает исправно, а socks - нет. 

Заглянул в логи сервера и увидел следующее:
160903173357.998 2004 00000 root 83.220.239.150:40264 **2a00:bdc0:2:18:1:0:213:17**:80 69 307 0 GET http://vk.com HTTP/1.1
160903173409.917 2005 00013 root 83.220.239.150:60107 ::ffff:**95.213.11.148**:80 0 0 0 CONNECT ::ffff:95.213.11.148:80

Первая строчка - работа с http прокси. Вторая - с socks.
Адрес vk.com в IPv4 95.213.11.148 (как я понял, может быть и иной, в зависимости от того, откуда пингую).
Адрес vk.com в IPv6 2a00:bdc0:2:18:1:0:213:17.
Ошибка №13, из документации к 3proxy, означает "сбой подключения connect()".
83.220.239.150 - адрес компьютера, с которого обращаюсь

Посмотрел на это и решил, что, похоже, во втором случае обращение происходит по неверному адресу. Ведь сервер к vk.com должен обращаться в IPv6, и адрес должен быть иной.

Мой код:
`bool proxy::check(char typeproxy,QString site){
    bool good=false;
    //необходимые CURL объекты
    CURL *curl;
    CURLcode result;
    //инициализируем curl
    curl = curl_easy_init();
    //проверяем результат инициализации
    if (curl)
    {
      //задаем все необходимые опции
      //определяем, куда выводить ошибки
      curl_easy_setopt(curl, CURLOPT_ERRORBUFFER, errorBuffer);
      //задаем опцию - получить страницу по адресу
      curl_easy_setopt(curl, CURLOPT_URL, site.toStdString().c_str());
      //указываем прокси сервер
      curl_easy_setopt(curl, CURLOPT_PROXY, (adr.getstring()+":"+QString().setNum(port)).toStdString().c_str());
      if (typeproxy==0) curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_HTTP);
      else curl_easy_setopt(curl, CURLOPT_PROXYTYPE, CURLPROXY_SOCKS5);
      curl_easy_setopt(curl, CURLOPT_PROXYUSERPWD , (login+":"+pass).toStdString().c_str());
      //задаем опцию отображение заголовка страницы
      curl_easy_setopt(curl, CURLOPT_HEADER, 1);
      //указываем функцию обратного вызова для записи получаемых данных
      curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, writer);
      //указываем куда записывать принимаемые данные
      curl_easy_setopt(curl, CURLOPT_WRITEDATA, &buffer);
      //запускаем выполнение задачи
      result = curl_easy_perform(curl);
      //проверяем успешность выполнения операции
      if (result == CURLE_OK){
          if (buffer!="") good=true;
      }
      else{
        //выводим сообщение об ошибке
          emit out(QString("Ошибка! ")+QString(errorBuffer));
      }
  }
  //завершаем сессию
  curl_easy_cleanup(curl);
  return good;
}`

Писал с использованием QT, но думаю, здесь это не очень важно.
По libcurl c IPv6 наяндексилась только фраза "libcurl свободна, потокобезопасна, совместима с IPv6...".

[Нашёл пост по теме](http://odminblog.ru/socks5-over-ipv6-issue/)
Отсюда:

> Собственно для того и выкладываю, что если кто то будет искать причину почему не работает socks5 поверх IPv6 – проблема не в сервере, а в клиенте. Тут надо заметить, что по манускриптам, поддержка SOCKS5 в IPv6 работает именно с оговоркой, т.к прохождение пакета требует специальной конфигурации пакета на стороне клиента.

Собственно, вопрос, как это реализовать? Спасибо.

**Comment by z3APA3A** [comment]
Ты запрашиваешь через SOCKS адрес IPv4. Адрес IPv4 не доступен напрямую по IPv6, 3proxy в режиме -6 переводит его в адресацию IPv4 over IPv6 в надежде что кто-то сумеет такой адрес отшлюзовать. Либо запрашивай адрес IPv6 либо делай запрос по имени, тогда при опции -64 или -6 3proxy будет сам разрешать его в IPv6 адрес.

**Comment by z3APA3A** [comment]
В libcurl для этого достаточно использовать CURLOPT_PROXYTYP со значением CURLPROXY_SOCKS5_HOSTNAME

**Comment by gggrafff** [comment]
Спасибо большое. Вроде, работает. )))))
