### ISSUE TITLE
Ошибка free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by zulmaster** [z3APA3A/3proxy#97]
Получаю ошибку 3proxy: free(): corrupted unsorted chunks: 0x00000000011b42a0 *** и работа 3proxy завершается. Происходит если несколько раз, 100-500, послать сигнал SIGUSR1 прокси, чтобы он перегрузил конфигурацию. Куда копать, что посмотреть?
Может поможет вместо SIGUSR1 посылать SIGPAUSE + SIGCONT согласно документации?
SIGPAUSE
stop to accept new connections, on second signal - start and re-read configuration
SIGCONT
start to accept new conenctions

**Comment by z3APA3A** [comment]
А сигнал ты прямо подряд посылаешь?
Какая версия 3proxy, что в конфигурации? Можешь ли запустить под valgrind'ом или хотя бы дать бинарники и корку?

**Comment by zulmaster** [comment]
Сигнал приходит гдето раз в 5-10 секунд.
Версия 3proxy-0.9-devel (160518000524)
Погоняю еще на днях, попробую отловить.

**Comment by zulmaster** [comment]
Нашел проблему. Оказалось что иногда система ускорялась и начинала слать сигнал по несколько раз в секунду. Вопрос закрыт.
